### ISSUE TITLE
beginner's experience improvement?

### ISSUE THREAD

**Issue by vise890** [rust-lang/rustup#1004]
Hi all!

I am completely new to rust. I just installed `rustup` and ran it.
The message was very detailed and even said:
> If you are new to Rust consider running `rustup doc --book` to learn Rust.

(which is a very nice touch!)

But I couldn't figure out how to actually *get* Rust! It took me a few commands:
- `help` (same thing);
- `show` (nothing there)
- `set` (doesn't look like the right one)
- `default` (`error: The following required arguments were not provided:     <toolchain>`)
- `default stable` (AHA! yess)

It's a super small thing, but I'm wondering if the experience could be improved for people just starting out?
Perhaps just changing the message would work:
> If you are new to Rust consider running `rustup doc --book` to learn Rust and `rustup default stable` to install the stable version.

Or maybe you could greet people with no toolchains available with a "tldr" version with a mention of the book and the command to get the stable one ?

**Comment by kinnison** [comment]
We install a toolchain by default, indeed `stable` by default, along with the documentation.  If the current behaviour of `rustup-init.exe` is insufficient, please open a fresh issue detailing what happens and what you'd prefer to see happen.

Thanks.
