### ISSUE TITLE
Teach rustup/rustbuild about optional components

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#1006]
Today rustup knows about two types of packages: components (required), and extensions (optional, non-default). Some components though want to be installed by default, but optional (like [docs](https://github.com/rust-lang-nursery/rustup.rs/issues/998)).

To do this we have to change the manifest format in a backwards-compatible way. I suggest that we add a key "optional = true" to components that don't need to be installed. The build-manifest tool invoked by rustbuild needs to be modified to emit this key, and rustup needs to be taught to consume it.

**Comment by Diggsey** [comment]
I have a slight preference for doing the opposite (ie. flagging extensions as being "install-by-default") so that components are always required, and extensions are always optional. What do you think?

**Comment by brson** [comment]
@Diggsey per discussion we decided to go with the original design, for backwards-compatibility concerns.

**Comment by brson** [comment]
Once this feature exists, rustup-init also needs to be modified with a non-interactive commandline option to disable default components. If the interactive installer allows component selection (I don't recall) then that needs to be modified too, though it could be done as a followup.

**Comment by mikhail-m1** [comment]
I take it, Should I change https://github.com/rust-lang/rust/blob/master/src/tools/build-manifest/src/main.rs or wait until #1112?

**Comment by mikhail-m1** [comment]
add optional to build-manifest tool https://github.com/mikhail-m1/rust/commit/35a30af96fe9d1d56ad3243d53f2dfde67549077. Shell I do pull request to rust-lang/rust?

**Comment by mathstuf** [comment]
Ping? Any progress on this? I'd like to reduce the size of our multi-toolchain build images by nuking docs…

**Comment by kinnison** [comment]
This work has been folded into the concept of installation profiles, which we're actively working on, though the over-all progress is slowed due to recent CI problems with Windows.  You can follow the work in #1673

**Comment by mathstuf** [comment]
Now that profiles have landed, I think this can be closed.

**Comment by kinnison** [comment]
I concur, thank you for the triage.
