### ISSUE TITLE
Please show me the version I'm downloading/updating

### ISSUE THREAD

**Issue by liigo** [rust-lang/rustup#1007]
```
C:\Users\liigo>rustup update
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: downloading component 'rustc'
 23.9 MiB /  28.8 MiB ( 83 %)  51.2 KiB/s ETA:  98 s
```

**Comment by brson** [comment]
The manifest contains the version being downloaded, so the change here is, as soon as that manifest is in-hand and the decision is made to do the upgrade, print another status line containing the version.
