### ISSUE TITLE
Investigate caching on travis builds

### ISSUE THREAD

**Issue by jelford** [rust-lang/rustup#1027]
Travis has some support for caching (https://docs.travis-ci.com/user/caching/). It's not that useful for conserving bandwidth, but I think rustup might be able to get some benefit from caching the compilation of OpenSSL static libs - which looks like it's adding quite a lot onto the build.

Since it's done inside a docker container, you'd have to use the "arbitrary folder" flavour of caching support. I think one would have to make a per-build-target folder, since while travis will give you a different cache per OS, I don't think it'll do it for each set of environment variables in the build matrix.

It coud work something like this:

    root/
        openssl/                                     # cache at this level
            i686-unknown-linux-gnu        # mount each of these to target/$TARGET/openssl/openssl-install
            x64-unknown-linux-gnu

For non-docker builds, travis has "first class" support for cargo.

**Comment by jelford** [comment]
If there's appetite for something like this, I'm happy to get travis running against my own repo and try it out.

**Comment by Diggsey** [comment]
@jelford Looks like travis does take into account env vars: https://github.com/travis-ci/travis-build/pull/706

Please go ahead, anything that reduces the build time would be nice!

**Comment by jelford** [comment]
Oh that's great, should be able to get it going without hacking around with folders then. I'll give it a go.

**Comment by jelford** [comment]
This has landed but I'll leave it open until I've had a chance to look at the effect on some builds and report back findings for others' interest.

**Comment by jelford** [comment]
The numbers for this look ok to me; builds on [travis's history page](https://travis-ci.org/rust-lang-nursery/rustup.rs/builds) have gone from around the 5h30m mark to around the 4h mark. 

In terms of the cache misses I described on the PR (about half the cargo dependency builds are hitting the cache across all configurations), those don't seem to have magically gone away, so if someone with a little experience of getting travis caches to work happens to see this, I'd love to hear about what might be going on here.
