### ISSUE TITLE
"Symbol not found" error doing "cargo test" on Rust stable

### ISSUE THREAD

**Issue by radupopescu** [rust-lang/rustup#1045]
I'm getting the following error running `cargo test` in a project:
```
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
```

I am using macOS 10.12.4 and I have installed Rust with `rustup`. The version of rust-stable is 1.16. I don't see any error if I do `cargo +nightly test`

I also have Homebrew on this computer (which makes symlinks to libraries in `/usr/local/lib`).

My project uses `rust-fuse`, which in turn uses the external C library `libfuse`.

I don't know what other information could be useful.

**Comment by Diggsey** [comment]
This sounds like an issue with rust or maybe cargo? Please re-open if you have some more information suggesting that the issue is caused by rustup.

**Comment by radupopescu** [comment]
The problem went away in Rust 1.17
