### ISSUE TITLE
Avoid downloading scripts to /tmp

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rustup#1050]
`/tmp` often has `noexec` for security reasons, and Docker requires privileged access in order to mount `/tmp`. Please have the rustup install script download to another directory, such as `$HOME`, for better support for these surprising *nix environments.

**Comment by nodakai** [comment]
An environment variable `TMPDIR` should be able to configure the location:

- https://www.gnu.org/software/coreutils/manual/html_node/mktemp-invocation.html
- https://doc.rust-lang.org/std/env/fn.temp_dir.html

You may want to give it a try.

**Comment by kinnison** [comment]
`rustup-init.sh` honours `$TMPDIR` via the `mktemp -d` command.
