### ISSUE TITLE
Promote x86_64-unknown-linux-musl from target to host toolchain

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rustup#1053]
Could the musl toolchain be promoted from something people access with

`rustup target add x86_64-unknown-linux-musl`

to something that people can

`curl https://sh.rustup.rs -sSf | sh -s -- --default-host x86_64-unknown-linux-musl -y`

?

**Comment by mbrubeck** [comment]
Depends on rust-lang/rust#40113.

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/pull/40113 has landed.

**Comment by dwijnand** [comment]
From @alexcrichton's comment https://github.com/rust-lang/rustup.rs/pull/1517#issuecomment-431007160:

> I think it's probably not worth doing this until we get a musl host rustc working, otherwise this rustup won't have anything to download!

This is now tracked upstream as https://github.com/rust-lang/rust/issues/57439.  So this ticket is (effectively) blocked by that.

**Comment by ebkalderon** [comment]
Looks like that upstream issue has been successfully resolved. Is this task now possible?

**Comment by ebkalderon** [comment]
@dwijnand Looks like that upstream issue has been successfully resolved. Is this task ready to move forward?
