### ISSUE TITLE
Invalid TLS Certificate from Travis?

### ISSUE THREAD

**Issue by naftulikay** [rust-lang/rustup#1069]
I'm building an Ansible role to setup a Rust development environment within a Vagrant VM. I'm attempting to run automated tests on this role using Travis-CI. Unfortunately, my tests are failing to download from `https://sh.rustup.rs`, reporting [the following error message](https://travis-ci.org/naftulikay/ansible-role-vagrant-rust-dev/jobs/222254493#L205): 

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for sh.rustup.rs:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: hostname 'sh.rustup.rs' doesn't match either of '*.rust-lang.org', 'rust-lang.org'."}
```

When I attempt to debug the TLS connection locally, I see something interesting:

```
echo q | openssl s_client -connect sh.rustup.rs:443 |& head
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify return:1
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Domain Validation Secure Server CA
verify return:1
depth=0 OU = Domain Control Validated, OU = EssentialSSL Wildcard, CN = *.rust-lang.org
verify return:1
CONNECTED(00000003)
---
```

It appears that the certificate serving `rustup.rs` has a non-matching common name. What's strange is that in local tests, my downloading of the script works without any issue. I have attempted to install `ca-certificates` in my Travis run, but this doesn't seem to affect anything.

Is there some misconfiguration with `sh.rustup.rs`?

**Comment by kinnison** [comment]
I'm going to assume this is no longer an issue given we've changed certificates since this was posted.  if it remains a problem, please open a fresh issue to discuss.
