### ISSUE TITLE
sh: -y: No such file or directory

### ISSUE THREAD

**Issue by rofrol** [rust-lang/rustup#1074]
Looks like short option doesn't work in `git bash` on Windows 7, and I can't use long option because [--no-prompt doesn't work](https://github.com/rust-lang-nursery/rustup.rs/issues/1031).

```shell
$ curl https://sh.rustup.rs -sSf | sh -- -y
sh: -y: No such file or directory
curl: (23) Failed writing body (0 != 9319)
```

**Comment by nodakai** [comment]
A little `-s` was missing from your command line:

```
$ curl https://sh.rustup.rs -sSf | sh -s -- -y
```

In fact I'm not on Windows but I'm 99 % sure that will resolve your issue.

**Comment by rofrol** [comment]
Thanks, works
