### ISSUE TITLE
cargo hangs on Windows 7

### ISSUE THREAD

**Issue by rofrol** [rust-lang/rustup#1075]
To overcome this I need to:

1. backup rust installation to tmp
2. remove original rust installation
3. copy rust installation from tmp

I use script like this:

```shell
mkdir -p tmp && \
cp -r ~/.cargo ~/.rustup tmp/ && \
rm -rf ~/.cargo ~/.rustup && \
cp -r tmp/.cargo ~/ && \
cp -r tmp/.rustup ~/ && \
rm -rf tmp
```

It does work on Windows 10.

**Comment by Diggsey** [comment]
Are you able to reproduce this issue - ie. if you uninstall rustup and reinstall, do you have to go through this backup/restore procedure before it will work again?

I don't have a windows 7 machine to test this on, but I think if it was happening to all windows 7 machines we would be getting more reports - do you know of anything else specific to this machine that might be related?

**Comment by rofrol** [comment]
Yes. I have reproduced it many times. And it hangs windows so much that I have to hard-reset computer.

This is a corporate machine so maybe something with privilieges?

**Comment by Diggsey** [comment]
> it hangs windows so much that I have to hard-reset computer

I'm afraid this is very suggestive of a badly-behaving virus scanner on the corporate machine. Nothing rustup can do, even if it was buggy, should be able to cause that kind of problem. Do you use non-microsoft antivirus software?

**Comment by rofrol** [comment]
Symantec

**Comment by LivingInSyn** [comment]
I also have this bug, also with Symantec. Windows 7 enterprise. Anything I can give you to help troubleshoot this

**Comment by NMZXYCDRL** [comment]
I  have this bug too, also with Win 7 + SEP (Symantec Endpoint Protection).

**Comment by critch** [comment]
I am having this issue with Windows 7 Profesional + SEP as well.

Curious though, I haven't found anything in SEP logs that show it blocking anything. Being a corporate machine, I can't disable it to verify that it is SEP being the problem.

**Comment by Geobert** [comment]
I have this issue on Win 7 Pro + McAffee, corporate machine

**Comment by busyscout** [comment]
I also had this problem with Win7 Ultimate. After installation via rustup-init in ~/.cargo directory all files were blocked as if they were downloaded from network ("this file came from another computer and might be blocked to help protect this computer").

**Comment by rami3l** [comment]
I'm closing this now as outdated, since Windows 7 is no longer tier 1 as per https://doc.rust-lang.org/nightly/rustc/platform-support.html. Sorry :[

**Comment by mrx23dot** [comment]
Well in embedded we need to support products for 10-20+ years, looks like it's back to C then.

So after 2025 you will only support Windows 11? (ignoring that millions of PCs won't be able to install it?)

**Comment by rami3l** [comment]
@mrx23dot I totally understand that you would want to work with rust/rustup on older platforms such as Windows 7, but maintaining support for old platforms is an active effort requiring continuous investment.

Given the fact that the target policy is not in the scope of this repo, if you would like to seek/provide extended support for Windows 7 across the rust project, please feel free to file an issue at https://github.com/rust-lang/rust.
