### ISSUE TITLE
Arch Linux rustup package fails to create rls proxy binary

### ISSUE THREAD

**Issue by chetgurevitch** [rust-lang/rustup#1081]
ref: https://bugs.archlinux.org/task/53711?project=5&opened=25300

 Rustup installed through the arch linux repo (despite being up to date) doesn't create the rls proxy binary in ~/.cargo/bin after running 'rustup component add rls' where rustup installed through rustup.rs does.

This is more of a distribution and packaging issue but I was wondering if the rustup team had any input on what might be the problem or how to go about resolving it.

Edit: Also here's the PKGBUILD used for rustup https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/rustup

**Comment by Diggsey** [comment]
@chetgurevitch You just need to add "rls" to the "_binlinks" variable in the PKGBUILD, since the arch package handles installation itself.
