### ISSUE TITLE
rustup should handle running RLS when the default toolchain is stable

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rustup#1083]
Hello everyone.

Since only nightly has the component RLS, one should either use nightly or use stable, but not use RLS.

I suppose rustup should handle the following case:

### Setup

I have two toolchains: stable, nightly.
I installed the component RLS for the nightly toolchain.
I made the stable toolchain be my default.

### Action

I run `rls`

### Excepted result

rustup runs RLS from the nightly toolchain.

### Actual result

rustup says RLS is not installed for stable.

What do you think about it?

**Comment by Diggsey** [comment]
What happens when rls lands on stable?

**Comment by KalitaAlexey** [comment]
Remove the approach and that's all.

**Comment by Diggsey** [comment]
I just don't think this is worthwhile, and is more likely to result in confusion. It would be too surprising to run programs from a different toolchain that the one that is active.

You can always use `rls +nightly` while on a stable toolchain as workaround.

**Comment by Diggsey** [comment]
Also, rustup is not intended to be tied to specific rustc versions. I'm against changes that we know will have to be reverted in a later version.
