### ISSUE TITLE
internal error: entered unreachable code

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rustup#1084]
After mucking around by deleting files in `~/.rustup` (necessary because nightly would’t install), I got this error from `rustup install stable`

    info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
    thread 'main' panicked at 'internal error: entered unreachable code', src/rustup/toolchain.rs:126
    note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by Diggsey** [comment]
Nightly not installing seems like a bug, so if you have any more info on that it would be good to open an issue.

Other than that, rustup is not expected to work if files are deleted randomly, sorry 😛
