### ISSUE TITLE
FreeBSD: can't determine value for sysroot (ICE)

### ISSUE THREAD

**Issue by spamwax** [rust-lang/rustup#1110]
On a FreeBSD 11.0, I installed rustup using the script from its website.
Compiling a simple project using both nightly/stable toolchain produces the following ICE:

```
$ RUST_BACKTRACE=1 cargo build --verbose
error: failed to run `rustc` to learn about target-specific information
Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --target x86_64-unknown-freebsd` (exit code: 101)
--- stderr
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at '/checkout/src/librustc/session/filesearch.rs:164: can't determine value for sysroot', /checkout/src/librustc/session/mod.rs:858
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
```

Output of `mount`:

```
$ mount
/dev/ada0p2 on / (ufs, local, journaled soft-updates)
devfs on /dev (devfs, local, multilabel)
tank on /tank (zfs, local, noatime, noexec, nfsv4acls)
tank/backup on /tank/backup (zfs, local, noatime, noexec, nfsv4acls)
home on /usr/home (zfs, local, noatime, nfsv4acls)
procfs on /proc (procfs, local)
```

This does not happen with the rustc that I can install using system's package manager (rust 1.16, cargo 0.17)

**Comment by Diggsey** [comment]
@spamwax Could you try installing the same version of rust you installed with rustup, via one of the standalone installation methods available from here: https://www.rust-lang.org/en-US/other-installers.html, and see if it suffers from the same issue?

This looks like an issue with rustc itself, but this will allow us to be sure.

**Comment by spamwax** [comment]
@Diggsey I just tried the standalone installations for the nightly (1.19) and got exact same error.
The reason I included output of `mount` in my first post was because of the comments made in [another (related?) issue](https://github.com/rust-lang/rust/issues/1711#issuecomment-289921827)

which seems to suggest that absence of `/proc` may cause it.

**Comment by Diggsey** [comment]
@spamwax Either this is a new bug (introduced since rust 1.16) or the people who packaged rustc for your OS have included patches to fix this issue.

If you try installing version 1.16 through rustup, you'll be able to determine which it is (patch or new bug).

Could you open an issue against the main rust repo: https://github.com/rust-lang/rust/ and include all the details from here? Thanks!

It does sound closely related to the issue you linked to, but since you *do* have procfs mounted, something else must be going on.

**Comment by spamwax** [comment]
I installed 1.16 through rustup and got same error, so seems packagers patched it.
I will open an issue in the main repo.
