### ISSUE TITLE
Lack of greatness after rust installation in Mac OS Terminal with default colors

### ISSUE THREAD

**Issue by okutane** [rust-lang/rustup#1142]
Today I've installed rust via rustup (again) by typing `curl https://sh.rustup.rs -sSf | sh` in my console. After proceeding with default options I've noticed a hardly readable block of text.
![Screenshot](https://monosnap.com/file/88RgqJjIudtLbF2UCL3af10ybFw5VZ.png)
Really, this one could be more readable if you just turn off highlighting. Maybe **bold** will do the trick?

**Comment by Diggsey** [comment]
Dup of #433
