### ISSUE TITLE
rustup fails to install gcc on some windows platforms

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/rustup#1163]
Recently I started to receive appveyor build errors for all of my projects with the following error message:

```
error: aborting due to previous error(s)
error: Could not compile `smt-expr-derive`.
Caused by:
  process didn't exit successfully: `rustc --crate-name smt_expr_derive smt-expr-derive\src\lib.rs --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C debuginfo=2 -C metadata=6feb16d7e2a8e571 -C extra-filename=-6feb16d7e2a8e571 --out-dir C:\projects\stevia\target\debug\deps -L dependency=C:\projects\stevia\target\debug\deps --extern syn=C:\projects\stevia\target\debug\deps\libsyn-e662069961d8f963.rlib --extern quote=C:\projects\stevia\target\debug\deps\libquote-983cfcbeae6039c8.rlib` (exit code: 101)
```

[Appveyor Link](https://ci.appveyor.com/project/Robbepop/stevia/branch/master/job/19y21gnq9cyv5ueb)

As far as I know rustup is supposed to install gcc on windows but on some windows platforms it no longer does and thus breaks all my appveyor builds. Other platforms, like linux, are not affected as far as I can tell.

I was forwarded to rustup through IRC channel #rust and hope that this is the right place for this issue.

**Comment by mati865** [comment]
The issue is https://github.com/rust-lang/rust/issues/42422
Nightly is fixed already.
