### ISSUE TITLE
No libsyntax folder for nightly toolchains

### ISSUE THREAD

**Issue by gbip** [rust-lang/rustup#1165]
Hello,
It seems that the libsyntax folder is not downloaded on a nightly toolcahin.
Yet it is downloaded for the stable toolchain.
My guess is that `rustup component add rust-src` only add the component for the currently active toolchain.
In that case maybe you could make the readme more explicit about downloading rustc sources files for a nightly toolchain.
Thanks,

**Comment by brson** [comment]
Thanks for the report @gbip.

This sounds like an upstream Rust issue. I have filed it there: https://github.com/rust-lang/rust/issues/42667
