### ISSUE TITLE
Cannot remove linked toolchain

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustup#1169]
I added a toolchain via `rustup toolchain link myrust <path>` that I now want to remove. However, `rustup toolchain uninstall myrust` says `info: no toolchain installed for 'myrust'`. It seems that either it is impossible to uninstall ("unlink") a linked toolchain, or at least that feature it so well hidden that it is very hard to find.

**Comment by brson** [comment]
Hm, that's not expected behavior. If there's a symlink under `~/.cargo/toolchains/myrust`, rustup should remove it in this case.

**Comment by RalfJung** [comment]
I suppose you mean `~/.rustup/...`? Yes, there is such a symlink.

**Comment by RalfJung** [comment]
I tested this again and now it works.

I *think* what may have happened is that the toolchain symlink became stale when I did a `./x.py clean`, and now that I have a compiler built again the symlink works again. Not sure what the intended behavior is in this case, but I'd argue that uninstalling a toolchain should work even if the symlink no longer points to a valid toolchain.

EDIT: Indeed I can reproduce the issue by putting a dead symlink (not pointing to anything) into the toolchain directory and trying to uninstall it.
