### ISSUE TITLE
Docs are not optional / removable for MSVC nigtly toolchain

### ISSUE THREAD

**Issue by GabrielMajeri** [rust-lang/rustup#1170]
According to [this old post](https://users.rust-lang.org/t/psa-rust-documentation-is-now-optional-and-opt-in-when-installing-via-rustup/8072), "Rust documentation is now optional and opt-in".

I am currently using `rustup` on Windows with the `nightly-x86_64-msvc` toolchain, and I am trying to opt-out of using the docs.

```
> rustup component remove rust-docs
error: component 'rust-docs' for target 'x86_64-pc-windows-msvc' is 
required for toolchain 'nightly-x86_64-pc-windows-msvc' and cannot be removed
```

Am I doing something wrong? Why are the docs *required*?

**Comment by Diggsey** [comment]
See #998
