### ISSUE TITLE
cargo doesnt work

### ISSUE THREAD

**Issue by werdahias** [rust-lang/rustup#1171]
Tryied to build my lastest project update. `cargo run` seems lazy and the command doesnt do anything.
![unbenannt](https://user-images.githubusercontent.com/23419969/27292236-1f60bbb4-5513-11e7-88fd-aaa7e42ac7e1.PNG)
Reinstall causes the same problem. Yesterday it worked properly.
Any suggestions?

**Comment by GabrielMajeri** [comment]
This is an issue with Cargo: https://github.com/rust-lang/cargo/issues/4189

It has been fixed in this pull request: https://github.com/rust-lang/rust/pull/42754

Try updating to get the release that includes the fix.

**Comment by werdahias** [comment]
` nightly-x86_64-pc-windows-msvc unchanged - rustc 1.19.0-nightly (04145943a 2017-06-19)`
cargo updated and it´s still lagging.

**Comment by GabrielMajeri** [comment]
Unfortunately this version does not contain the fix, so you will have to wait until the next nightly that contains the fix. As you can see in [the commit list](https://github.com/rust-lang/cargo/commits/master), the version of Cargo that comes with nightly right now is 50b1c24d1, 4 commits behind the one with the fix. 

Until then, perhaps you could use the beta version, and wait until the new nightly gets released.

**Comment by werdahias** [comment]
thanks for the advice given.
