### ISSUE TITLE
Use symlinks for various wrappers

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustup#1173]
Currently, rustup copies itself multiple times into ~/.cargo/bin:
```
$ ls -lah ~/.cargo/bin
total 220M
drwxr-xr-x 2 r r 4,0K Jun 16 16:46 .
drwxr-xr-x 5 r r 4,0K Mai 23 10:22 ..
-rwxr-xr-x 7 r r  12M Jun 11 17:16 cargo
-rwxr-xr-x 7 r r  12M Jun 11 17:16 rls
-rwxr-xr-x 7 r r  12M Jun 11 17:16 rustc
-rwxr-xr-x 7 r r  12M Jun 11 17:16 rustdoc
-rwxr-xr-x 7 r r  12M Jun 11 17:16 rust-gdb
-rwxr-xr-x 7 r r  12M Jun 11 17:16 rust-lldb
-rwxr-xr-x 7 r r  12M Jun 11 17:16 rustup
```
Ideally, these should be symlinks to make things a little more efficient. Also, I feel if these were all symlinks to `~/.cargo/bin/rustup`, that would show more clearly (to someone figuring out what lives where and how which component of rust is called) that these are all wrappers.

**Comment by Diggsey** [comment]
They're already hardlinks

**Comment by RalfJung** [comment]
Oh, I guess I could have checked that.

I think symlinks would be clearer (because anyone doing `ls -la` would see what is going on, and that these are wrappers). But oh well.
