### ISSUE TITLE
Fix 'show' when active toolchain is not installed

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#1178]
Here's what happens when you run 'show' with a toolchain that is not installed:

```
brian@DESKTOP-CODN6ST MINGW64 /c/Users/brian/Documents/dev/rustup.rs
$ rustup override set beta
info: using existing install for 'beta-x86_64-pc-windows-msvc'
info: override toolchain for 'C:\Users\brian\Documents\dev\rustup.rs' set to 'beta-x86_64-pc-windows-msvc'

  beta-x86_64-pc-windows-msvc unchanged - rustc 1.19.0-beta.1 (a87984118 2017-06-06)


brian@DESKTOP-CODN6ST MINGW64 /c/Users/brian/Documents/dev/rustup.rs
$ rustup toolchain remove beta
info: uninstalling toolchain 'beta-x86_64-pc-windows-msvc'
info: toolchain 'beta-x86_64-pc-windows-msvc' uninstalled

brian@DESKTOP-CODN6ST MINGW64 /c/Users/brian/Documents/dev/rustup.rs
$ rustup show
Default host: x86_64-pc-windows-msvc

error: override toolchain 'beta-x86_64-pc-windows-msvc' is not installed
```

Instead of displaying various information about installed toolchains it immediately errors.

It should instead do something like:

```
brian@DESKTOP-CODN6ST MINGW64 /c/Users/brian/Documents/dev/rustup.rs
$ rustup override remove
info: override toolchain for 'C:\Users\brian\Documents\dev\rustup.rs' removed

brian@DESKTOP-CODN6ST MINGW64 /c/Users/brian/Documents/dev/rustup.rs
$ rustup show
Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

active toolchain
----------------

beta-x86_64-pc-windows-msvc (override set by blah blah blah)
(error: override toolchain 'beta-x86_64-pc-windows-msvc' is not installed)
```

Fix will be in `rustup_cli::rustup_mode::show`. Instead of returning the error, print it into the show output.

**Comment by brson** [comment]
Fix up test cases in tests/cli-rustup.rs

**Comment by mati865** [comment]
[Here](https://github.com/rust-lang-nursery/rustup.rs/blob/285e858f6d263929aa82a2770ed892e3173ac9e9/src/rustup-cli/rustup_mode.rs#L548) is thrown the error: `Error(OverrideToolchainNotInstalled("beta-x86_64-unknown-linux-gnu"), State { next_error: Some(Error(Msg("the directory override for \'/home/mateusz/Projects/testing\' specifies an uninstalled toolchain"), State { next_error: None, backtrace: None })), backtrace: None })`.

I don't know how to extract required data from it but it someone wants to fix it this tip may help.

**Comment by michaelfletchercgy** [comment]
I managed to get about 50% done this yesterday evening.  I will be able to finish it over the next five days if nobody needs it sooner.
