### ISSUE TITLE
Teach hyper/rustls HTTP backends to resume partial downloads

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#1181]
The curl backend can already do it, but not the two hyper backends. It should just be a matter of threading the parameter through and setting the HTTP [Range header](http://stackoverflow.com/questions/3303029/ddg#18745164).

Test by compiling with `--features=rustls` and `RUSTUP_USE_HYPER` / `RUSTUP_USE_RUSTLS`, and `--verbose`.

No way to actually write test cases for this though.

**Comment by ghost** [comment]
I can tackle this. I'm currently trying to figure out how to set that `Range` header in the Hyper client.
