### ISSUE TITLE
Github releases?

### ISSUE THREAD

**Issue by alex** [rust-lang/rustup#1185]
Hi all,

In the process of updating `rustup` in Homebrew (https://github.com/Homebrew/homebrew-core/pull/14929) the question came up of whether 1.4.0 and 1.5.0 were the latest releases, since 1.3.0 is marked as such on https://github.com/rust-lang-nursery/rustup.rs/releases/.

Can you confirm if 1.3.0 should be preferred, or simply no one updated that page in the Github UI?

Thanks!

**Comment by Diggsey** [comment]
@brson I may have messed something up when I created the 1.3.0 tag? I think I explicitly created a release, whereas it looks like what github shows in the "releases" page includes the set of normal tags following semver?

**Comment by ilovezfs** [comment]
@Diggsey you have to explicitly publish 1.4.0 and/or 1.5.0 for something other than 1.3.0 to be displayed as the latest release (https://github.com/rust-lang-nursery/rustup.rs/releases/latest).

"Mere" tags will always be listed on the releases page, but the actual releases API requires that you hit the publish button. (https://help.github.com/articles/creating-releases/)

**Comment by alex** [comment]
Alternatively you can remove the 1.3.0 release and just use tags; that's what we do on projects I work on, since Github isn't the official location for our changelog: https://github.com/pyca/cryptography/releases

**Comment by ilovezfs** [comment]
@Diggsey the delete button should be on https://github.com/rust-lang-nursery/rustup.rs/releases/tag/1.3.0 in the upper right:

<img width="1011" alt="screen shot 2017-06-28 at 9 22 30 pm" src="https://user-images.githubusercontent.com/5268928/27671665-34261042-5c4a-11e7-8996-4b3c67a4f106.png">

**Comment by ilovezfs** [comment]
Thanks for fixing this!
