### ISSUE TITLE
Self update fails on Windows ("Access is denied")

### ISSUE THREAD

**Issue by marcogroppo** [rust-lang/rustup#1186]
I couldn't self-update `rustup` to 1.5.0 because the `rustup.exe` file is locked (probably by itself...):

```
> rustup self update
info: checking for self-updates
info: downloading self-update
info: rustup updated successfully to 1.5.0
error: could not remove 'rustup-bin' file: 'D:\Apps\rust\cargo\bin\rustup.exe'
info: caused by: Access is denied. (os error 5)

> rustup --version
rustup 1.4.0 (a77fbedf2 2017-06-09)
```

OS: Windows 10 Creators Update

**Comment by Diggsey** [comment]
This happens if you are currently running the RLS.

For example, you may have VSCode open with the rust plugin enabled, in which case the RLS will be constantly running in the background. Can you confirm if that's the issue?

**Comment by marcogroppo** [comment]
Yes, you're right: the RLS was running... After terminating it, the update process worked fine. Sorry for the false alarm, I should have checked before posting

**Comment by EriKWDev** [comment]
While that is both the issue and still the fix, it would be nice if rustup maybe gave a hint that this is the case. Would it be possible to detect?

**Comment by rami3l** [comment]
Oops, another duplicate of #988. We really need to find some time to fix that... Even a trivial global lock should help.
