### ISSUE TITLE
-y option is not documented in --help output

### ISSUE THREAD

**Issue by patrickod** [rust-lang/rustup#1191]
While attempting to figure out how to run the rustup installation script without the interactive prompt I was pointed to the `-y` flag for rustup by @steveklabnik, however it doesn't appear in the README or the output from `--help`

This flag should be documented so that others might discover it more easily.

**Comment by typesanitizer** [comment]
The version on [master](https://github.com/rust-lang-nursery/rustup.rs/blob/master/rustup-init.sh#L31) already has this. Downloading the installation script from https://sh.rustup.rs also gives me the same. Perhaps you have an older version of the install script?

**Comment by patrickod** [comment]
Hmm you're absolutely right that it's there! I must have just missed it. Apologies for the false-positive issue!
