### ISSUE TITLE
SSE2 instructions in i686 binaries

### ISSUE THREAD

**Issue by fstirlitz** [rust-lang/rustup#1196]
The `rustup-init` binary for i686, and the Rust toolchain it installs, contains SSE2 instructions, which means running it on my perfectly i686-compatible Pentium III laptop generates 'Illegal instruction' errors.

Some digging revealed it's because of rust-lang/rust#14441. Even besides the issue whether excluding actual i686 hardware from an i686 compiler target is sensible, greeting the user with an 'Illegal instruction' message hardly makes a good first impression.

**Comment by shvelo** [comment]
I am faced with the same problem, but I'm replacing the laptop CPU with a Pentium M, which supports SSE2.   
Have you checked if your laptop CPU can be upgraded?

**Comment by kinnison** [comment]
Rust's definition of i686 I think remains one which which expects SSE2, and this isn't something we are likely to change in Rustup.  Even if we targeted something less capable, the stdlib and compiler etc would be unchanged.  As such I'm closing this issue, thank you for your input though.
