### ISSUE TITLE
Windows c++ requirement is unclear

### ISSUE THREAD

**Issue by trondhindenes** [rust-lang/rustup#1202]
According to the installer, I can add the "C++ tools" component of Visual Studio. However, there is no component in Visual Studio 2015 with that name. 

rustup-init should use the exact names of required visual studio component(s).

**Comment by Boddlnagg** [comment]
Somewhat orthogonal to this issue: Given a tool like [vswhere](https://github.com/Microsoft/vswhere), but written in Rust (what https://github.com/retep998/msvc-bunny is supposed to become), rustup could automatically detect whether the C++ build tools component is installed (for VS 2017).

**Comment by Diggsey** [comment]
Closing as dup of #1363
