### ISSUE TITLE
Bad link in README

### ISSUE THREAD

**Issue by perryprog** [rust-lang/rustup#1203]
Line 180 in readme:
```
Rustup gives you easy access to the nightly compiler and its
[experimental features]. To add it just run `rustup install
nightly`:

[experimental features]: http://doc.rust-lang.org/nightly/book/nightly-rust.html
```

That link is dead, closest one I can find is this. <https://doc.rust-lang.org/1.16.0/book/nightly-rust.html>

If anyone wants I can make a PR.

**Comment by kraai** [comment]
The Unstable Book at https://doc.rust-lang.org/unstable-book/ describes unstable features.  Is that the best reference for experimental features?

The table of contents of the second edition of The Rust Programming Language indicates there will be an Appendix D - Nightly Rust but it doesn't appear to exist yet.

**Comment by mark-i-m** [comment]
I think the Unstable book @kraai linked is probably the best link, as it actually lists all current nightly features.
