### ISSUE TITLE
Rustup is unable to download on appveyor

### ISSUE THREAD

**Issue by Marwes** [rust-lang/rustup#1208]
I originally encountered this issue on [gluon's appveyor setup](https://ci.appveyor.com/project/Marwes/gluon) but it appears that [rustup's own appveyor setup](https://ci.appveyor.com/project/brson/rustup-rs/build/job/2biwjm7pxkp3x2on) has the same problem. This may just be an issue on appveyor but since rustup's setup is also affected I figured opening an issue here was relevant.

Might be related to https://github.com/rust-lang/rust/pull/43333 but the solution in that PR does not help.

```
Build started
git clone -q https://github.com/gluon-lang/gluon.git C:\projects\gluon
git fetch -q origin +refs/pull/279/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
curl -sSf -o rustup-init.exe https://win.rustup.rs
rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256' to 'C:\Users\appveyor\.rustup\tmp\ip9r_xhlefdoj47g_file'
info: caused by: error during download
info: caused by: [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.)
Command exited with code 1
```

**Comment by Boddlnagg** [comment]
See https://users.rust-lang.org/t/appveyor-builds-failing-today/11949/3 and http://help.appveyor.com/discussions/problems/7115-curl-cant-download-files-through-ssl#comment_43044339. It's a problem on AppVeyor's side which should be fixed very soon.
