### ISSUE TITLE
Allow to install stable versions by version number

### ISSUE THREAD

**Issue by glandium** [rust-lang/rustup#1210]
If one wants to use rustup to install old stable releases for some reason, they need to find the right date to use. For instance `rustup toolchain install stable-2017-06-08` for 1.18. This is tedious. It would be easier if it were possible to say `rustup toolchain install stable-1.18.0`

**Comment by Diggsey** [comment]
`rustup toolchain install 1.18.0`

**Comment by glandium** [comment]
facepalm

Thanks.
