### ISSUE TITLE
Move components when installing new toolchains

### ISSUE THREAD

**Issue by nrxus** [rust-lang/rustup#1216]
Given I have rust-src added as a component, if I install a new toolchain and set it as default, it would be nice for rustup to know that it needs to pull in the rust-src component for this new toolchain, instead of me having to manually install it for every toolchain. 

Background: 
The nightly toolchain broke and causes an ICE when I try to compile beginning 10 days ago. Due to this issue with that toolchain, I have switched to using a specific toolchain nightly date. This caused racer to complain since it couldn't find the rust source code where it expected it (at the rustc root for the toolchain I am now using) since the rust-src component was not added to that toolchain. It was a super quick fix for me to re-add it, but it seems that I would always want to add that component on a toolchain I have installed (especially if I set it as the default) and that rustup should have enough information to do that for any user.

**Comment by kinnison** [comment]
Given the new profiles support, nightly backtracking, and various other quality-of-life improvements I'm closing this.  If you still want something around this, please open a fresh issue detailing how you'd like it to behave relative to current functionality.
