### ISSUE TITLE
TUF integration tracking issue

### ISSUE THREAD

**Issue by heartsucker** [rust-lang/rustup#1217]
I'm opening this to move the general discussion about how TUF will be integrated into `rustup` and static.rust-lang.org.

I've started poking around in the rustup guts to see how I can get a bare-minimum working version of this out. Work is tracked here:

https://github.com/heartsucker/rustup.rs/tree/tuf

## TUF / PKI

I was planning on using TUF as follows:

- The top level `targets` role never signs for anything
- There are three roles that sign for their respective channels:
  - `stable`
    - offline keys (max security)
  - `beta`
    - also offline keys because of infrequent updates
    - possibly online depending on how you paranoid you are
  - `nightly`
    - online keys given to travis/appveyor
- Each of the roles `stable`, `beta`, and `nightly` would possibly delegate to `linux` and `windows` sub-roles to allow each CI server to sign only for its own builds
- There is an `archive` role with offline keys that signs for all old releases (including nightly).
  - Periodic resigns happen where old builds are resigned to `archive` using the offline keys
- The roles are prioritized `stable`, `archive`, `beta`, `nightly` so that if the `beta` or `nightly` online keys are compromised, anything moved to `archive` is safe

This step is actually opaque to `rustup` and in a sense `rust-tuf`. The external API of the latter will behave the same regardless of what sort of delegation strategy is used.

## Targets don't appear to be hierarchical

The current way delegations work is by authorizing them to sign for a given path, where a path is

- A single file
- Every file under a "directory"

That is, if a role is allowed to sign for

- `foo`
- `bar/`
- `baz/quux`
- `lol/wat/`

Then it can sign for

- Exactly the target `foo`
- Everything prefixed by `bar/` (but not `bar` itself)
- Exactly the target `baz/quux`
- Everything prefixed by `lol/wat/` (but not `lol/wat` itself)

This does not play nicely with the current setup which uses paths like `dist/$date/$item-$channel-$triple`.

For a delegation to be authorized to sign for any target, all parents (recursively) must also be authorized to sign for a given target. I have been hesitant about using glob-style matching because it makes for ambiguous authorizations for delegations.

### Preferred Resolution

Double up where are artifacts are stored, one to the old location, one to a TUF-friendly location. Deprecate the old location / manifest format.

### Workaround

Create an injective mapping from the current targets like `dist/2017-07-18/cargo-beta-arm-unknown-linux-gnueabi.tar.gz` into something like `beta/2017-07-18/linux/arm-unknown-linux-gnueabi/cargo.tar.gz`.

Downside: This would require some decent chunk of `rust-tuf` code to be pulled from private functions and pasted into `rustup`.

## Target and download logic is scattered all over the rustup codebase

This really has two parts. First, `rust-tuf` only supports `hyper` at the moment, and I wasn't planning on supporting any other backends.

And the main issue is that TUF in general, and `rust-tuf` in particular, really need to handle all these operations in one place. The general approach looks something like this:

```rust
let mut client = tuf::client::Client::with_root_pinned(
    PINNED_KEY_IDS,
    Config::default(),
    local_repo,
    remote_repo);
client.update_local()?;
client.update_remote()?;
for (target_name, output_path) in desired_targets.iter() {
    let out = File::new(output_path)?;
    client.fetch_target_to_writer(target_name, out)?;
}
```

This is unquestionably the preferred method for downloading, and using the lower level structures directly could lead to broken security guarantees.

### Preferred Resolution

Only support `hyper`, and centralize the download and verification logic to `rust-tuf`. Download and verify everything. Then do the rest of the `rustup` magic.

### Workaround

`rust-tuf` exposes a wrapper for safely downloading called `SafeReader` that ensures the three TUF properties for a secure download are met:

- some `max_size` is not exceeded
- hashes match at the end
- some `min_bitrate` is met over the course of the download

These need to be met for both targets and metadata.

A `SafeReader` accepts an arbitrary `R: Read` along with parameters for the above 3 requirements. The parameters *could* be grabbed from the `Tuf` struct directly. This step allows us use all 3 backends (I think), but would require some large changes in the codebase.

----------------

Thoughts?

**Comment by alexcrichton** [comment]
I wonder if we could maybe hit two birds with one stone here? Would it be possible to have something like a "virtual filesystem" abstracted through a trait? That way something like rustup could create "pseudo paths" which look like `beta/2017-07-18/linux/arm-unknown-linux-gnueabi/cargo.tar.gz` but actually map to different paths on S3. That'd also get us to the point where we could swap out the download backend as the download logic itself would be implemented in rustup instead of the tuf crate.

Now the tuf crate would have a default implementation of this "virtual filesystem" which does the normal thing and uses hyper/reqwest, but maybe the trait could solve rustup's use case?

**Comment by heartsucker** [comment]
> Would it be possible to have something like a "virtual filesystem" abstracted through a trait?

I think this could be done natively. I'll open a ticket for that.

However, that still doesn't totally solve the second one of the logic being in many different parts of the crate. Is there a reason that this (relatively small) app has so many modules?

**Comment by alexcrichton** [comment]
I think we could work to canonicalize the number of code paths for downloading things, I'd imagine we could get it to a point where there's just one point that makes a client. Rustup's got a long history!

**Comment by heartsucker** [comment]
I'm going to need someone to help with this. A lot of the internals are undocumented, and "just read the code" is a little too tedious for something I'm doing in my spare time. I think most of this could be done in ~4 hours if someone who knew what they were doing could point me in the right direction. Any chance there are contributors in Berlin?

**Comment by Diggsey** [comment]
@heartsucker I'd be happy to answer questions like that on IRC - I'm not in Berlin but a similar timezone at least...

**Comment by heartsucker** [comment]
@Diggsey Which channel?

**Comment by Diggsey** [comment]
#rust-dev-tools, or just PM me

**Comment by kinnison** [comment]
Because this hasn't seen any movement in over two years I'm closing this issue.  There're new tracking issues around the signature verification topic, so go there if you want to join in the current basic plans.
