### ISSUE TITLE
Add a way to install the toolchain specified in the override file

### ISSUE THREAD

**Issue by shinglyu** [rust-lang/rustup#1218]
https://github.com/rust-lang-nursery/rustup.rs/pull/1172 allows us to create a `rust-toolchain` file and specify a version of the toolchain to be used in the current directory. But I can't seem to find a way to install the specified version automatically. 
Now I do `cat rust-toolchain | xargs rustup install`, but it would be nice to have a command like `rustup install rust-toolchain` or maybe simply `rustup install` (fail if the file is not present). 

Thoughts? @brson

**Comment by paulrouget** [comment]
As of now, what happens exactly when the toolchain version is not available? Just fail or fallback to the closest toolchain?

**Comment by paulrouget** [comment]
Just fail.

**Comment by shinglyu** [comment]
Oh sorry for missing this. Yes it just failed with a warning saying the version didn't match
