### ISSUE TITLE
Rust windows installer failed when not run with admin privilege

### ISSUE THREAD

**Issue by buckle2000** [rust-lang/rustup#1223]
Installer: `rustup-init.exe`

# How to reproduce this bug

1. start installer without admin privilege
Wait for download
When download of component `rustc` is completed, the installer says `Access denied` and halts.

2. start installer with admin privilege
the download is now complete, but the installer will request byte range of size 0 from the server, results in error `Cannot get multi-part...`.
`.multirust/` must be deleted to correct and restart installation

**Comment by buckle2000** [comment]
It seems somewhat related to #1188

**Comment by ferrouswheel** [comment]
As well as deleting `.multirust`, I had to remove the partial download from `.rustup\downloads` too.

**Comment by buckle2000** [comment]
@ferrouswheel ironically the downloaded file it is not partial but complete. rustup just need to move it to the appropriate place.

**Comment by abelsromero** [comment]
I am on Windows 8.1 and `rustup-init` required admin rights and installs rust in the admin account. Making it un-avaible for my default non-admin user.
So, is there a way to get a clean install without copying the files manually?

EDIT: I see now that even when I changed to gnu it installed msvc...already reported https://github.com/rust-lang-nursery/rustup.rs/issues/1409

**Comment by Diggsey** [comment]
Do you have `CARGO_HOME` set to something non-default?

Rustup does not normally require admin privileges to install. Does the error message give any more details than just "access denied"? Do you use any additional security software or have any unusual restrictions?

**Comment by abelsromero** [comment]
I just downloaded last version (1.26.1) and could fix this by un-checking the _Run this as administrator_ option in the rust-init properties. By default Windows marks this as admin's right required.
Screenshot in Spanish but I assume the position of the option is the same in other languages. 

![image](https://user-images.githubusercontent.com/5781153/40880027-3acdaa3e-66aa-11e8-908c-0a5901f5cecb.png)

Clarification: after this, rustup, rustc ... installed in my non-admin user correctly and is working fine. No need to define CARGO_HOME or do anything else.

**Comment by rbtcollins** [comment]
Zero idea what was going on here, but the download cannot carry the admin-privileges bit, so it must have been something local / windows 8 specific. Please do reopen if this is still happening.
