### ISSUE TITLE
Better NixOS support

### ISSUE THREAD

**Issue by canndrew** [rust-lang/rustup#1241]
This is related to #673.

I'd like a way to use rustup on NixOS. Because NixOS doesn't keep it's dynamic loader under `/lib64/ld-linux-x86-64.so.2` it's necessary to patch the binaries that rustup downloads to change where they look for the loader. This could be done in a post-unpack phase in rustup which:
  1) Checks if it's running on NixOS
  2) Patches the loader path of the downloaded binaries using `patchelf`
  3) Adds the rustup toolchains directory as a nix garbage collector root.

This should be fairly easy to implement in rustup (in fact I've mostly already done it), but I'd like to get feedback on whether people think this a good direction to go.

**Comment by Diggsey** [comment]
I talked about this before with some people using NixOS, and their opinion was that rustup just didn't fit within the NixOS mentality, so I didn't pursue it further. However, I don't see any harm in adding this functionality if you'd be willing to implement and maintain it, given that the status quo is rustup not working at all on NixOS.

**Comment by canndrew** [comment]
Yeah, I understand that it doesn't fit with the NixOS way of doing things, but for my purposes I'd rather just use rustup for rust development rather than having to install my rust toolchains through nix.

I'll finish off and polish up the implementation I've got and PR it then.

**Comment by Ralith** [comment]
Note that [good rust support, including nightlies](https://github.com/mozilla/nixpkgs-mozilla#rust-overlay) is available on NixOS with very little effort already.

**Comment by sjmackenzie** [comment]
@canndrew how's progress on this? nix rust doesn't have good support for cross compilation, seems this is a viable way (especially when compiling things like `ionpak` and `smoltcp` etc)

**Comment by sjmackenzie** [comment]
nvm I see `rustup` is already in `nixpkgs`
