### ISSUE TITLE
Add option to check for updates without updating

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rustup#1249]
It'd be nice to have a command to run rustup update and check if anything would be downloaded without actually downloading anything. For example, I have a MOTD that shows me if I need to update any packages, and it'd be nice to also show a message if a new stable version of Rust is available to download.

**Comment by ordovicia** [comment]
I'd like to try.
What name is good for the subcommand?

**Comment by clarfonthey** [comment]
Personally I'd add it to the `update` subcommand with a `--no-download` option

**Comment by ordovicia** [comment]
I see. Thank you for your comment.
I'd prefer to add an individual subcommand with name `check` or `check-update`.
I'd like more suggestions widely.

**Comment by Zteve** [comment]
I have added my 2¢ to #1271. I hope this feature comes soon.

**Comment by matthiaskrgr** [comment]
`rustup check` has been implemented, I think this can be closed...?

**Comment by kinnison** [comment]
Yep, well spotted Matthias.
