### ISSUE TITLE
Confusing error when attempting to install `rust-docs` component

### ISSUE THREAD

**Issue by silverjam** [rust-lang/rustup#1251]
Ran the command `curl https://sh.rustup.rs -sSf | sh` to install rustup, then `rustup component add rust-src` which worked, then `rustup component add rust-docs` which fails with the following error:

```
error: component 'rust-docs' for target 'x86_64-apple-darwin' is required for toolchain 'stable-x86_64-apple-darwin' and cannot be re-added
```

Which is not google-able and doesn't seem (to me) to provide any clues on how to resolve the issue... any hints?

**Comment by Diggsey** [comment]
It means the documentation is already installed (it's a required component).

**Comment by silverjam** [comment]
Ok, would suggest re-wording the error... was following instructions here: http://asquera.de/blog/2017-03-03/setting-up-a-rust-devenv/ -- which seems to assume that it's not a required component.

**Comment by silverjam** [comment]
Suggest `error: component 'rust-docs' is already added for target 'x86_64-apple-darwin' because it is required for toolchain 'stable-x86_64-apple-darwin' and cannot be re-added, type blah blah to see the component`
