### ISSUE TITLE
Automatically clean up `tmp` folder

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rustup#1252]
I just realized I have a 10GB `.rustup/tmp` folder on my system full of temporary files...

**Comment by alexcrichton** [comment]
Same for `.rustup/downloads`, it was 1GB large!

**Comment by senden9** [comment]
I use rustup since a few months and my tmp folder is quite small with 4KB.
```
$ du --summarize --human .rustup/* 
4.0K	.rustup/downloads
4.0K	.rustup/settings.toml
188K	.rustup/tmp
1.3G	.rustup/toolchains
12K	.rustup/update-hashes
```
Maybe a bug? Maybe rustup crashed & did not clean up after the next run?

**Comment by bgianfo** [comment]
Just hit this today, my temp folder was 100's of MB, and my downloads folder was in 1-2 GB range...

**Comment by kinnison** [comment]
The `tmp` folder should be cleanable up with a bit of a tweak.  the `downloads` folder we have a PR in the works for.  I'll actually ask if they can add the `tmp` dir to that too, since it is just as good a location to deal with the cleanups.
