### ISSUE TITLE
Show alternate install options on website

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/rustup#1253]
https://rustup.rs tries to figure out what OS you are visiting from, and show appropriate instructions on installation. Sometimes, though rustup.rs is wrong - for example, if you are using anti-fingerprinting software, your browser might return an inaccurate response causing us to believe you are running a different OS than you are.

We should support an option on the main page to switch it to display the installation instructions for other operating systems.

**Comment by jelford** [comment]
I could take this; I will have some time this week to put something together. I'm thinking of button at the bottom that says something like:

    I think you're running on $platform, but if not, <here's> the full list.

... which would just switch to `#platform-instructions-default`. It could maybe show text like `#platform-instructions-unknown` (not exactly the same) below?

For what it's worth, as a NoScript user I see the default screen, and I just assumed that's what everyone saw; I never saw anything wrong with it.

**Comment by jelford** [comment]
I didn't get a chance to look at this while I was on holiday, and I don't think I'll be able to get to it now. If someone else wants to pick it up, that would seem sensible.

**Comment by senden9** [comment]
I added a pull request that pick that issue up. See #1300.
