### ISSUE TITLE
Rustup uses stable version of cargo when default toolchain is set to nightly

### ISSUE THREAD

**Issue by mister-walter** [rust-lang/rustup#1256]
After running `rustup update` earlier today, I started running into issues using cargo. I eventually discovered that, for some reason, the stable version of cargo was being used instead of the nightly version.

I tried switching the default compiler to stable and back again, and then tried uninstalling and reinstalling the nightly toolchain, but `cargo` still redirects to the stable cargo.

The nightly cargo is installed - `rustup run nightly cargo -V` prints out the nightly version number, and calling cargo that way works fine.

Version info:

```
$ rustup -V
rustup 1.6.0 (a11c01e8c 2017-08-30)
```

```
$ rustup show
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-x86_64-apple-darwin (default)

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.22.0-nightly (01c65cb15 2017-09-20)

$ rustup run nightly cargo -V
cargo 0.23.0-nightly (8118b02ac 2017-09-14)
$ cargo -V
cargo 0.21.1
$ which cargo
~/.cargo/bin/cargo
```

**Comment by dsheets** [comment]
Have you tried restarting your shell or running `source ~/.cargo/env`?

**Comment by mister-walter** [comment]
Sorry I haven't been checking up on this issue, it appears to have been solved by something between when I reported the issue and when I ran rustup update recently (maybe the update to rustup 1.7.0?)

Here's my system now, where everything works:
```
$ rustup -V
rustup 1.7.0 (813f7b7a8 2017-10-30)

$ rustup show
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-x86_64-apple-darwin (default)

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.23.0-nightly (2be4cc040 2017-11-01)

$ rustup run nightly cargo -V
cargo 0.24.0-nightly (859c2305b 2017-10-29)

$ cargo -V
cargo 0.24.0-nightly (859c2305b 2017-10-29)
```

Note that I also tried completely uninstalling rustup and reinstalling it when I initially had the problem, to no effect.
