### ISSUE TITLE
Regression: rustup run fails to pass arguments properly

### ISSUE THREAD

**Issue by matklad** [rust-lang/rustup#1262]
On rustup 1.5.0, command `rustup run nightly cargo test -- --nocapture` works correctly, but on 1.6.0 it gives an error:

```
λ rustup run nightly cargo test -- --nocapture
error: Unknown flag: '--nocapture'

Usage:
    cargo test [options] [--] [<args>...]
```

Looks like this is a regression? `cargo +nightly test -- --nocapture` continues to work as expected.

**Comment by SimonSapin** [comment]
Random guess: try with an extra `--` ? Maybe rustup upgraded to a new version of clap that also uses `--` to separate rustup arguments from cargo arguments.

**Comment by matklad** [comment]
>Random guess: try with an extra -- ? Maybe rustup upgraded to a new version of clap that also uses -- to separate rustup arguments from cargo arguments.

We've migrated to `+nightly` syntax in IntelliJ Rust, so this is no longer an issue for us.

**Comment by matklad** [comment]
So, let's close this: hopefully nobody except IntelliJ Rust relied on the old behavior, and if they were, `rustup 1.6.0` should be pretty widespread by this time, so they need to deal with breakage anyway :)
