### ISSUE TITLE
rustup install stable-x86_64-unknown-openbsd fails

### ISSUE THREAD

**Issue by kpcyrd** [rust-lang/rustup#1265]
I found an openbsd target in rustc:
```
$ rustc --print target-list | grep openbsd
i686-unknown-openbsd
x86_64-unknown-openbsd
$
```
but the install fails:
```
$ rustup install stable-x86_64-unknown-openbsd
info: syncing channel updates for 'stable-x86_64-unknown-openbsd'
214.6 KiB / 214.6 KiB (100 %)  28.8 KiB/s ETA:   0 s                
info: latest update on 2017-08-31, rust version 1.20.0 (f3d6973f4 2017-08-27)
error: target not found: 'x86_64-unknown-openbsd'
$ rustup install nightly-x86_64-unknown-openbsd
info: syncing channel updates for 'nightly-x86_64-unknown-openbsd'
230.3 KiB / 230.3 KiB (100 %)  69.1 KiB/s ETA:   0 s                
info: latest update on 2017-10-08, rust version 1.22.0-nightly (05f8ddc46 2017-10-07)
error: target not found: 'x86_64-unknown-openbsd'
$ 
```

**Comment by SimonSapin** [comment]
`rustc --print target-list` shows which targets the compiler knows how to (cross-)compile to. “target not found” in rustup means that corresponding binary builds are not available at rust-lang.org. This matches the “tier 3” status listed at https://forge.rust-lang.org/platform-support.html. So you probably need to compile some stuff yourself, or find out if someone else maintains binary builds.

If you want to cross-compile from another platform (as opposed to running the compiler on OpenBSD), maybe https://github.com/japaric/rust-cross#cross-compiling-the-standard-crates can help.

**Comment by kpcyrd** [comment]
Is there a way to get a platform to tier 3 status with volunteers from the community? I'm asking because it seems this bug blocks https://github.com/japaric/cross/issues/97 which seems to blocks other projects to integrate openbsd into their CI (https://github.com/nix-rust/nix/issues/685, https://github.com/carllerche/mio/issues/593). I would be interested in working on this as I maintain rust programs that target openbsd.

**Comment by gnzlbg** [comment]
@kpcyrd you probably just need to submit a PR to this repo that fixes this.

**Comment by Diggsey** [comment]
I think there's some target/host confusion here.

To add a target to rustc, you would do `rustup target add <target-triple>`

Regardless, issues around platform support should be opened against `rust-lang/rust` unless there is a platform which rustc supports but rustup itself is not built for.
