### ISSUE TITLE
OpenWrt rustup-init: syntax error

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rustup#1273]
I downloaded the rustup-init installers for mips and mipsel, in an attempt to install rust via rustup in OpenWrt. However, the installers report some kind of syntax error.

Trace:

```console
$ opkg install ca-certificates wget
$ wget https://static.rust-lang.org/rustup/dist/mips-unknown-linux-gnu/rustup-init
$ chmod +x rustup-init
$ ./rustup-init
./rustup-init: line 1: syntax error: unexpected "("
```

I'm using OpenWrt 15.05, a uClibc distribution of Linux.

**Update**

I also tried using a mips tarball, but after I extract it and try to run rustc, I get the same strange error:

```console
$ /rust-1.21.0-mips-unknown-linux-gnu/rustc/bin/rustc
/rust-1.21.0-mips-unknown-linux-gnu/rustc/bin/rustc: line 1: syntax error: unexpected "("
```

After tinkering some more, I produced a more specific error message. For what it's worth, OpenWrt uses the ash shell by default rather than bash. So I installed bash and tried running rustc from bash:

```console
$ opkg install bash
$ bash -c /rust-1.21.0-mips-unknown-linux-gnu/rustc/bin/rustc
bash: /rust-1.21.0-mips-unknown-linux-gnu/rustc/bin/rustc: cannot execute binary file: Exec format error
```

So at this point, it looks like the rustup-init executables do not currently support uClibc Linux, but rather GNU glibc Linux distributions. Any plans to port rustup to uClibc, for either the mips or x86_64 architectures?

**Comment by Diggsey** [comment]
Please re-open this issue when it becomes a tier-2 or above platform, until then there are no prebuilt binaries.

`rust-lang/rust` is the right place to track this feature until then.
