### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rustup#1275]
I’d like to get https://github.com/rust-lang-nursery/rustup.rs/pull/1250 in a release. What’s the process? Can I help?

**Comment by alexcrichton** [comment]
The general instructions are at https://github.com/rust-lang-nursery/rustup.rs/blob/master/ci/sync-dist.py, I'll try to get around to that soon

**Comment by alexcrichton** [comment]
Ok this is done now.

**Comment by SimonSapin** [comment]
Thank you! ❤️

**Comment by SimonSapin** [comment]
Sorry for the repeat performance, could we make another one with https://github.com/rust-lang-nursery/rustup.rs/pull/1295 ? Thanks

**Comment by alexcrichton** [comment]
@SimonSapin can you be sure to test this time to make sure the current state of master fixes your issue? A new release will probably be made for https://github.com/rust-lang-nursery/rustup.rs/pull/1294.

**Comment by SimonSapin** [comment]
Fair enough. I’m fairly confident (*this* time, promise ;)) as I have a more precise idea of how exactly I want Servo’s `mach` to use rustup. But I’ll set up a self-compiled rustup on my machine to actually implement it, and report back.

**Comment by SimonSapin** [comment]
I have a Servo PR at https://github.com/servo/servo/pull/19395, it seems to work fine on my machine with rustup built from source.

**Comment by alexcrichton** [comment]
Ok, thanks for testing
