### ISSUE TITLE
Rustup installs 64bit compiler on a 32bit Docker instance

### ISSUE THREAD

**Issue by shaleh** [rust-lang/rustup#1282]
This is what is in my dockerfile:

     RUN curl https://sh.rustup.rs -o rustup.sh && sh rustup.sh --default-toolchain nightly -y && rustup default nightly

Here are some details from the docker instance

    root@cc25a7d3570a:~/test32# uname -a
     Linux cc25a7d3570a 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 i686 i686 i686 GNU/Linux
    root@cc25a7d3570a:~/test32# rustc --version
    rustc 1.23.0-nightly (2be4cc040 2017-11-01)
    root@cc25a7d3570a:~/test32# rustup show
    Default host: x86_64-unknown-linux-gnu

    installed toolchains
    --------------------

    nightly-i686-unknown-linux-gnu (default)
    nightly-x86_64-unknown-linux-gnu

    active toolchain
    ----------------

    nightly-i686-unknown-linux-gnu (default)
    rustc 1.23.0-nightly (2be4cc040 2017-11-01)

I hand installed the i686 compiler by running `rustup install nightly-i686-unknown-linux-gnu`.

You can find the Dockerfile [here](https://github.com/Wilfred/remacs/blob/master/Dockerfile32bit)

**Comment by shaleh** [comment]
The 32 bit Dockerfile can be seen here: https://github.com/Wilfred/remacs/blob/master/docker/ubuntu/32bit/Dockerfile

If I set the default-host explicitly with `--default-host i686-unknown-linux-gnu` then the right thing happens. If I leave it up to rustup-init determining the host I get a mixed i686 and x86_64 Rust install which refuses to run (as you might expect).

**Comment by kinnison** [comment]
I believe this has come up again, and we ought to see if we can fix it.  cf. #2111

**Comment by kinnison** [comment]
I have investigated and I believe that this should be working with current rustup.  Could you please double-check @shaleh and let me know.  If it's not working, can you please add `-x` to the sh cmdline (i.e. `sh -x rustup.sh ...`) and paste from where it looks at `/proc/self/exe` to where it starts downloading the installer please?

**Comment by kinnison** [comment]
It is my strong belief that this is no longer a problem on x86, and with the patch for #2111 it'll be fixed for aarch64/armv7 too.  If it is still an issue, please reopen with details as above.
