### ISSUE TITLE
Add an option to print only the url from `rustup doc`

### ISSUE THREAD

**Issue by naufraghi** [rust-lang/rustup#1288]
In option to #1287, to easy the integration with other tools, `rust doc` can offer a `--print-only` option to print the target url without firing up the browser.

**Comment by Diggsey** [comment]
This is being implemented in #1421

**Comment by kinnison** [comment]
Is this still desired?

**Comment by naufraghi** [comment]
I forgot way I was needing this, I can close and reopen it if I'll have an use-case
