### ISSUE TITLE
Fresh install gets old: rustc 1.21.0-nightly (52a330969 2017-07-27)

### ISSUE THREAD

**Issue by SamuelMarks** [rust-lang/rustup#1292]
Ran `curl https://sh.rustup.rs -sSf | sh` selected `nightly` and got this version.

`rustup update` fixed the problem, but the install script really should grab the latest nightly; right?

Thanks

**Comment by Diggsey** [comment]
This is strange... Are you sure you didn't have rustup already installed?

**Comment by SamuelMarks** [comment]
Um… this was from over 6 months ago. Rustup has had 4 major releases since then.
