### ISSUE TITLE
Can we rely on proxy mode being based on argv[0]?

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rustup#1293]
We’re considering replacing Servo’s rust/cargo bootstrapping code with rustup.rs: https://github.com/servo/servo/issues/11361

My tentative plan is to always use rustup, and run it with a `RUSTUP_TOOLCHAIN` environment variable that selects the appropriate date nightly or versioned stable. However we’d want to make sure we run `cargo` through rustup.rs’s proxy, and not run directly a plain Cargo that would ignore `RUSTUP_TOOLCHAIN` and use a rustc that might not be the appropriate version. (Which would likely cause a confusing build error later on.)

So, to do that we’d start it from Python with something like `subprocess.Popen(["cargo"] + cargo_args, executable="rustup")`. (And similarly for `rustc`, `rustdoc`, etc.) This makes Python look for an executable in `$PATH` named `rustup`, and execute it with `argv[0] == "cargo"`.

So this all relies on what’s probably an implementation detail of rustup.rs: the proxy executable installed at `$CARGO_HOME/bin/cargo` is exactly the same as `$CARGO_HOME/bin/rustup`, and they behave differently based on `argv[0]`.

Is this a bad idea? Is there a better way? Or does it sound fine to rely on running `rustup` with a different `argv[0]` triggering proxy mode?

**Comment by Diggsey** [comment]
If you're always specifying the toolchain, could you just use `rustup run <toolchain> <command>`?

**Comment by SimonSapin** [comment]
I didn’t realize `rustup run` existed. This is exactly what we need, thanks!

**Comment by SimonSapin** [comment]
Ah, `rustup run` doesn’t automatically install missing toolchains, though. So that doesn’t work for this use case.
