### ISSUE TITLE
toolchain 'nightly-x86_64-unknown-linux-gnu' does not contain component 'wasm32-unknown-unknown' for target 'x86_64-unknown-linux-gnu'

### ISSUE THREAD

**Issue by TomasHubelbauer** [rust-lang/rustup#1296]
I have installed RustUp from scratch on OpenSUSE Leap 42 (using WSL) carrying out the following commands:

- `curl https://sh.rustup.rs -sSf | sh`
- Default installation options (triple `x86_64-unknown-linux-gnu`, toolchain `stable`)
- `source $HOME/.cargo/env`
- `rustup update`
- `rustup toolchain install nightly-x86_64-unknown-linux-gnu`
- `rustup component add wasm32-unknown-unknown --toolchain nightly`

It gives me *toolchain 'nightly-x86_64-unknown-linux-gnu' does not contain component 'wasm32-unknown-unknown' for target 'x86_64-unknown-linux-gnu'*.

I am not sure what I did wrong, but I can see I have both stable and nightly installed using `rustup toolchain list`:

```
stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu
```

What could be the problem here? I should also mention I did the same on Windows and it worked.

**Comment by Diggsey** [comment]
Are you sure you are on a new enough nightly? This target was *only just* released, so it's quite possible you pre-empted it. I just ran `rustup update` locally and the target is there.

**Comment by TomasHubelbauer** [comment]
I ran `rustup update` again and it says this:

```
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: checking for self-updates

   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.22.1 (05e2e1c41 2017-11-22)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.23.0-nightly (827cb0d61 2017-11-26)
```

I ran `rustc +nightly --target wasm32-unknown-unknown -O add.rs --crate-type=cdylib` and it didn't work:

`can't find crate for std` *the `wasm32-unknown-unknown` target may not be installed*

I am able to reproduce the same error on Ubuntu (it originally happened there so I installed OpenSUSE to double check) - like I said before, on Windows this works without a problem.

**Comment by Diggsey** [comment]
Ah, the command is `rustup target add wasm32-unknown-unknown --toolchain nightly`, not `rustup component add wasm32-unknown-unknown --toolchain nightly`.

**Comment by TomasHubelbauer** [comment]
I am using [this article](https://www.hellorust.com/demos/add/index.html), will ping the author afterwards.

I did `rustup target add wasm32-unknown-unknown` and it says *toolchain 'stable-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target 'wasm32-unknown-unknown'*. I would install the component manually but something tells me I am not supposed to install the components by hand and the target installation should take care of that?

**Comment by Diggsey** [comment]
You'll need to add `--toolchain nightly` if nightly is not currently active.
