### ISSUE TITLE
rustup update nightly on macOS rustc does not exist

### ISSUE THREAD

**Issue by messense** [rust-lang/rustup#1297]
```bash
$ rustup update nightly
info: syncing channel updates for 'nightly-x86_64-apple-darwin'

  nightly-x86_64-apple-darwin unchanged - (rustc does not exist)
$ rustup --version
rustup 1.7.0 (813f7b7a8 2017-10-30)
```

Is nightly build for macOS down? I have yesterday's nightly installed before running `rustup update nightly` then `rustup` removed it while it can't find a newer one to install(I lost that logs on my terminal).

**Comment by lorepozo** [comment]
Until this gets resolved, you can use yesterday's nightly which has rustc for darwin:

```sh
$ rustup install nightly-2017-11-28
```

**Comment by kennytm** [comment]
This is caused by rust-lang/rust#46391. Should be fixed tomorrow.
