### ISSUE TITLE
VSCode + RLS install is a mess

### ISSUE THREAD

**Issue by freedaun** [rust-lang/rustup#1301]
0. I have a fresh Windows 10. FRESH. 
1. Installed VSCode, so rustup will know it can do its integration thing. 
2. I installed Rust with Rustup, which prompted me to install the MS C++ Build Tools, so before continuing I:
3. downloaded and installed 5.6GB worth of C++ Build tools. Says it Installed. But I have to take its word for it? :(
4. Aborted and reran Rustup and installed Rust, per default. 
5. Entered VSCode and opened a Rust project. Nothing happened ;) Isn't RLS is supposedly installed by default per recent release notes??
6. Typed Rust in VSCode extensions and found Rust 0.4.2. Installed it. Supposedly it features RLS integration. But nothing confirms that. 
7. Installed Rust (rls). VSCode begins talking to me, offering to install RLS. 
8. It requires nightly. Please do install. Many messages and confirmations (do whatever you think you need) and RLS is NOT installed as the end-result. 

OBS: I don't see the usual C++ debug profile, nor the dialog prompting me to select

WTF? 
- Please provide a guaranteed install sequence (or a deterministic installation like modern distros do)! 
- Please remove out of date docs or old repos (https://github.com/editor-rs/vscode-rust/blob/master/doc/main.md, https://github.com/rust-lang-nursery/rls-vscode). Including:
- Is manual install (https://github.com/rust-lang-nursery/rls) still relevant?? The instructions fail on step 3 (" does not contain component 'rls-preview'"). No longer a preview?? "rls" is also unknown, and that terminates my efforts.

I think all of this amounts to the same thing, see title. Sorry.

**Comment by sbwtw** [comment]
Same problem, I have update nightly toolchain to `nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.24.0-nightly (cfba0d446 2017-12-05)` and NO `rls` or `rls-preview` in component list

**Comment by McGittyHub** [comment]
Same it just disappeared

**Comment by dvdplm** [comment]
Same for rustfmt-preview. I think there's some kind of upstream problem causing some components to be skipped with the nightly builds. I've been using `nightly-2017-12-01` which insofar I know is the last build to include both rls and rustfmt. :/

**Comment by alexheretic** [comment]
Releases of additional tools are referenced to be built and included in nightly rust releases. If the additional tool's, ie _rls-preview's_, latest release does not build with latest nightly-rust that tool will be missing. This is an unfortunate fact of nightly life, Rls is fragile to rustc changes and nightly updates can include changes to the compiler.

The long solution is the stabilization of Rls meaning normal development will take place on stable-rust. Until then we have to handle potential nightly absences of Rls.

* **If your nightly install is missing Rls**, try installing a previous one, ie `nightly-2017-12-01`. The atom plugin will prompt you to do this, and I assume vscode is the same.
* **If you have a working nightly and want to update** it's possible to check if the latest nightly has Rls and this should be coming to rustup (see https://github.com/rust-lang-nursery/rustup.rs/issues/1277).
  
  Until that's in rustup you can use a script, like:
  ```bash
  #!/usr/bin/env bash
  # Update rust nightly as long as rls is included
  if curl https://static.rust-lang.org/dist/channel-rust-nightly.toml 2>/dev/null | grep -q 'rls-preview' 
  then
    rustup update nightly
  else
    echo 'latest nightly is missing rls' >&2
    exit 1
  fi
  ```

**Comment by jankeromnes** [comment]
See also https://github.com/rust-lang-nursery/rls/issues/611#issuecomment-348731464

**Comment by FuujSama** [comment]
When I do what's suggested and include:

"rust-client.channel": "nightly-2017-12-01" in my VScode settings it starts giving me the warning "RLS could not set RUST_SRC_PATH for Racer because it could not read the Rust sysroot." as it installs the toolchain and RLS. Then it tries to run RLS five time and crashes.

**Comment by elliottneilclark** [comment]
This gets even worse if you want to use clippy. I haven't found any nightly that is usable if I want to use clippy, fmt, and rls.

**Comment by DanielJoyce** [comment]
Its all still a hot mess even after two years. Why is this so dysfunctional?

**Comment by benmarten** [comment]
```
rustup component add rls                                                                 11:27:00
error: toolchain 'stable-x86_64-apple-darwin' does not contain component 'rls' for target 'x86_64-apple-darwin'
```

What's going on, is RLS deprecated or sth?

**Comment by Diggsey** [comment]
AFAIK, the only rustup-related issue here was that it would allow you to upgrade to a nightly rustc which was built without the RLS. This has been fixed.

@elliottneilclark 
Clippy in general does not work well with rustup because it dynamically links to the compiler DLLs, and that is incompatible with toolchain-switching. The solution here will be to distribute clippy as a compiler component, like the RLS and rustfmt. Until then, clippy will break on every compiler update and will have to be reinstalled.

@DanielJoyce 
Please open an issue if you have a specific problem. I know many people, including myself have been using rustup, rust and RLS without issue for some time now.
