### ISSUE TITLE
missing latest tag

### ISSUE THREAD

**Issue by alexheretic** [rust-lang/rustup#1302]
Latest tag is `1.6.0`, it would be good to tag 813f7b7a88b4d1bcb1a174828e2aaffbfdc3db75 as `1.7.0` to allow this version to be packaged / referenced externally.

**Comment by alanhdu** [comment]
It looks like `1.7.0` has been tagged, although now we need the `1.8.0` tag for 9b1b54a0a02f8324d19750423dc2d4b7899f298c 😆.

**Comment by alexheretic** [comment]
Ah, maybe there using a auto tagger that looks for the last commit where the next commit is a greater version. That means anyone that uses the tags will be one version behind though, which isn't ideal...

**Comment by alexcrichton** [comment]
Yes sorry I just forgot to tag 1.7.0

There's a bug with 1.8.0 (https://github.com/rust-lang-nursery/rustup.rs/issues/1305) so it won't be released just yet.
