### ISSUE TITLE
target uninstall gives incorrect warning about component not installed

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rustup#1306]
```
mqudsi@ZBook /m/c/U/M/g/tcpproxy> rustup target remove asmjs-unknown-emscripten
info: removing component 'rust-std' for 'asmjs-unknown-emscripten'
warning: during uninstall component rust-std-asmjs-unknown-emscripten was not found
```

Indeed, previously using `rustup component list` never did list `asmjs-unknown-emscripten`, but I requested the removal of the target, not the component.  Is there even a component by that name? I don't have any components that match my targets for any toolchain/target.

**Comment by Diggsey** [comment]
Dup of #1091
