### ISSUE TITLE
`rustup target list` output needs an alternative to color

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rustup#1308]
Due to presumably the same bug as https://github.com/rust-lang/rust/issues/45728, rustup does not emit color under a correctly-configured tmux (though it will if tmux is misconfigured, as most are), but that's not the issue I'm reporting.

The problem is that the output of `rustup target list` relies on color to distinguish between installed and uninstalled targets. If color is omitted, the only information discernable from the output is which target is installed _and_ the default, other targets that are installed are displayed the same as targets that aren't.

**Comment by amar-laksh** [comment]
Output without colour (gnome-terminal):
![screenshot from 2018-01-02 10-56-32](https://user-images.githubusercontent.com/12481356/34474938-132668ce-efac-11e7-9434-ddbfe349040b.png)

xterm:
![screenshot from 2018-01-02 11-00-39](https://user-images.githubusercontent.com/12481356/34474958-4dfa5654-efac-11e7-8c54-6afc382de355.png)

I think this is easy enough to distinguish especially with the default and installed rendered in **bold text**.

**Comment by mqudsi** [comment]
That just substitutes one meta property of the text for another. Not all terminals have bold support, copying and pasting loses that bold, etc.

**Comment by amar-laksh** [comment]
Yeah but again what can we do? Any suggestions? BTW even the linux ttys support bold text.

**Comment by mqudsi** [comment]
```
Installed:
  * abc (default)
  * def
Available:
  * foo
  * bar
```

**Comment by mqudsi** [comment]
Note that this has already been improved. There was no `(installed)` at the time I filed this bug.

**Comment by amar-laksh** [comment]
You should probably close the issue then.
