### ISSUE TITLE
Configurable installation directory for binaries

### ISSUE THREAD

**Issue by mzabaluev** [rust-lang/rustup#1317]
As described in rust-lang-nursery/docker-rust#17, `$CARGO_HOME/bin` may be a poor choice of installation directory for binaries inside a container, because users of the container image may want to bind-mount the entire `$CARGO_HOME` to a host directory to preserve Cargo caches and authentication secrets between container runs. The installation location should be configurable, either with an environment variable or via `$RUSTUP_HOME/settings.toml`.

**Comment by sbrl** [comment]
I second this. I'd like to install rustup, but I don't currently feel I can because I can't suitably control where rustup puts things.

**Comment by mzabaluev** [comment]
One complication is that rustup also manages `$CARGO_HOME`: it tries to delete it on uninstall.
I'm not sure what the behavior should be when the binary install directory has been configured to be somewhere else.

**Comment by Diggsey** [comment]
There's already a long-term issue for configurable directories (#247)

The specific motivation in this ticket is not particularly compelling: cargo is the tool which defines `$CARGO_HOME/bin` as the place to put binaries. If users don't want to cache binaries they should not bind that path to the host.
