### ISSUE TITLE
rustup update doesn't provide any notification that it's taken control of duplicate tools

### ISSUE THREAD

**Issue by varkor** [rust-lang/rustup#1318]
If `rustfmt` and `cargo-fmt` have already been installed by Cargo, `rustup update` will print something like:
```
warning: tool `rustfmt` is already installed, remove it from `~/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
```
After doing this, `rustup update` provides no notification to the user that this has been successful (e.g. `info: moving component 'rustfmt'`), which can be a little confusing, as it seems no action has taken place, even though it was successful. It'd be nice if there was an info message for this case!

**Comment by hongxuchen** [comment]
similar issue, however running `cargo-fmt`/`rustfmt` tells me that:

```
error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not have the binary `cargo-fmt`
```
```
error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not have the binary `rustfmt`
```

**Comment by bitshifter** [comment]
@HongxuChen  I got it working by doing:

```
rustup override set nightly
rustup component add rustfmt-preview
cargo fmt
```

It seems that the stable version doesn't include `cargo-fmt`.

**Comment by hongxuchen** [comment]
@bitshifter thanks, working now!

**Comment by amar-laksh** [comment]
Hey @bitshifter ! Could you do us a solid and close the issue if there's no problem now? 👍

**Comment by varkor** [comment]
@amar-laksh: the issue they're talking about it separate from the one described by this issue, which has not been fixed.

**Comment by Diggsey** [comment]
Closing as dup of #1352 - situation definitely needs improving here.
