### ISSUE TITLE
SunOS/Solaris/Illumos support

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rustup#1320]
Ay could we get support for building Rust binaries targeting the Solaris/Illumos kernel?

Developers interested in experimenting with building Solaris/Illumos applications can install [DilOS](http://www.dilos.org/), either directly onto hardware with the ISO, or with a Vagrant [VM](https://app.vagrantup.com/mcandre/boxes/dilos).

Another Solaris/Illumos distribution using the pkgin NetBSD package manager, SmartOS, has an experimental rust package. Maybe we could get a rustup working based on the SmartOS work?

https://internals.rust-lang.org/t/building-rustc-on-solaris/3599/2

**Comment by Diggsey** [comment]
You should open an issue on `rust-lang/rust` for new target requests.

**Comment by UgnilJoZ** [comment]
Meanwhile, rustc supports `x86_64-sun-solaris`, but rustup does not.
OpenIndiana has rustc 1.32, which is quite old, so any rustup support would be nice.

**Comment by kinnison** [comment]
@UgnilJoZ At this time, there is no official rust support for rustc/cargo for that target and so `rustup` cannot support it.  If you look on the forge <https://forge.rust-lang.org/release/platform-support.html> then you can see it's tier2 and std only.
