### ISSUE TITLE
Could not create link from `rustup.exe` to `rustc.exe`

### ISSUE THREAD

**Issue by aeb-dev** [rust-lang/rustup#1325]
## **Error**:
undefinederror: toolchain 'stable-x86_64-pc-windows-gnu' does not have the binary `rust-gdb.exe`

## **What I have tried so far:**
*Steps:*
1 - installed MSYS2 -> http://www.msys2.org/
2 - installed rust-lang with stable_x86_64-pc-windows-gnu and  -> https://www.rust-lang.org/en-US/install.html
3 - installed nightly with rls as stated here -> https://github.com/rust-lang-nursery/rls
4 - installed vscode extension vscode-rust -> https://github.com/editor-rs/vscode-rust
5 - installed native debug -> https://github.com/WebFreak001/code-debug

I might have missed some points, it has been a while.

## **Useful information**
I can use rustup or cargo commands from command line.
I can use gdb from command line.
I can use vscode extension(native debugger) for debugging with **gdppath** variable set to **gdb**
Both toolchains have lib\rustlib\etc python files.

What I can not use is **rust-gdb** from command line or vscode which gives the error above. 

My vscode settings and error are shown below when I hit debug.

![image](https://user-images.githubusercontent.com/11612804/34487032-94e16a1c-efe3-11e7-9bf6-c3a3d75b46ac.PNG)

Also when I use **rustup update** I get the following error I do not know if they are related.
![image2](https://user-images.githubusercontent.com/11612804/34487876-4131a87e-efe7-11e7-9e84-19a91aa17815.jpg)

I have been trying to work out this issue for a while so I give up

**Comment by hortinstein** [comment]
We're you able to ever get this working?

**Comment by aeb-dev** [comment]
Yes it was working once but I have not checked it since I posted this issue here.

**Comment by Diggsey** [comment]
@MrMuMu the first issue is an upstream problem - if `rust-gdb` is missing from a toolchain you should open an issue on `rust-lang/rust`.

The second issue with creating a link is potentially a rustup problem, are you able to reliably reproduce it?

**Comment by aeb-dev** [comment]
Closing since it has been a while
