### ISSUE TITLE
`rustup` or `rustup -h` doesn't show `install` as a subcommand

### ISSUE THREAD

**Issue by rbalicki2** [rust-lang/rustup#1335]
I must be missing something. But I come back to rustup every few months and find myself needing to google this :)

**Comment by Arnavion** [comment]
It's an alias for `rustup toolchain install`, so you can see it in `rustup toolchain --help`. Per [the commit that introduced it,](https://github.com/rust-lang-nursery/rustup.rs/commit/26fc2d7f6dd0ed0efcdf246ac21e573aa363dacf) hiding it from top-level `--help` is intentional.
