### ISSUE TITLE
Prints error in fish command line

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/rustup#1338]
When fish is trying to autocomplete cargo subcommands, if you have no toolchains installed, an error is printed in the middle of your command: "no default toolchain configured." This appears right where the user is typing out their command.

rustup should never print anything to the user like during fish's autocomplete. I don't know enough to about either codebase to investigate further.

**Comment by kbknapp** [comment]
@withoutboats I tried to reproduce this but I coudn't get it to happen. Which subcommand were you completing that caused this? I was thinking maybe it was an issue with the fish completion script, but I can't seem to make it happen.

I tried on a fresh `rustup` and fresh `fish` install using the `$ rustup completions fish` script.

**Comment by withoutboats** [comment]
I just had a similar thing happen with another tool asking if I wanted to install the package through dnf, so I think this is actually a regression in the version of fish I have and nothing to do with rustup. Thanks for looking at it!
