### ISSUE TITLE
rustup update <toolchain> ignore <toolchain> and proceeds to update everything.

### ISSUE THREAD

**Issue by ishanjain28** [rust-lang/rustup#1342]
Operating System: Arch Linux x64
Rustup version: 1.9.0 (57fc3c087 2018-01-04)

I run `rustup update stable-x86_64-unknown-linux-gnu` to update only one toolchain but it ignores the `<toolchain>` argument and proceeds to download(And maybe even update? I have not downloaded all toolchains to verify this) all installed toolchains.

**Comment by Diggsey** [comment]
I can't reproduce this on 1.11.0, please open a new issue referencing this one if it re-occurs.
