### ISSUE TITLE
rustup asks to take over tools even when the tools don't exist in the freshly updated nightly

### ISSUE THREAD

**Issue by daboross** [rust-lang/rustup#1345]
Hi, just noting this as a usability error.

When I run `rustup update`, even if the newly installed update doesn't have rustfmt, rustup will report:

```
warning: tool `rustfmt` is already installed, remove it from `/home/daboross/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
warning: tool `cargo-fmt` is already installed, remove it from `/home/daboross/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
```

I'll run `cargo uninstall rustfmt-nightly`, then `rustup update`, then try `cargo fmt`, and... "error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not have the binary `cargo-fmt`".

It would be helpful if rustup would only complain about already installed tools if the tools exist in _at least one toolchain I have installed_.

**Comment by torkleyy** [comment]
I think you need to do `rustup component add rustfmt-preview` to have rustup install it for you.

**Comment by Diggsey** [comment]
Dup of #1352
