### ISSUE TITLE
rustup run strips `--` from command line

### ISSUE THREAD

**Issue by stoklund** [rust-lang/rustup#1350]
Is this intentional?

```
$ /bin/echo foo -- bar
foo -- bar
$ rustup run stable /bin/echo foo -- bar
foo bar
```

It means I can't use `rustup run` to invoke `bindgen <args> -- <clang-args>` in an environment where dyld can find the required libraries.

```
$ rustup --version
rustup 1.10.0 (c6a8f7c60 2018-01-25)
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D47
```

**Comment by shingtaklam1324** [comment]
```zsh
$ rustup run stable /bin/echo 'foo -- bar'
foo -- bar
```

This may not be what you want but I'm not sure how this would be fixed as it will need to distinguish the flags for rustup and for echo

**Comment by Diggsey** [comment]
Does `rustup run stable -- /bin/echo foo -- bar` not work?

**Comment by kinnison** [comment]
The example given in the post on 28 May 2018 should have been sufficient.  I'm closing this issue as it has had no movement in over a year.
