### ISSUE TITLE
misleading warning if rustfmt is not handled by rustup

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rustup#1352]
I installed rustfmt-nightly via ````cargo install rustfmt-nightly````.
When doing ````rustup update````, I get a warning
````
warning: tool `rustfmt` is already installed, remove it from `/home/matthias/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
warning: tool `cargo-fmt` is already installed, remove it from `/home/matthias/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
````
which sounds like ````cargo uninstall rustfmt-nightly ; rustup update```` will automatically reinstall rustfmt via rustup however this does not seem to be the case.
 Apparently I have to manually activate it via ````rustup component add --toolchain nightly rustfmt-preview````.
Can we improve this warning message somehow, it's quite a bit misleading in my opinion. :/

**Comment by indygreg** [comment]
I just ran into this and was about to file the same bug. Here's the output from my terminal for context:

```
$ rustup update
...
info: downloading self-update

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.23.0 (766bd11c8 2018-01-01)
      beta-x86_64-unknown-linux-gnu updated - rustc 1.24.0-beta.11 (03f456d3c 2018-02-03)
   nightly-x86_64-unknown-linux-gnu updated - rustc 1.25.0-nightly (b8398d947 2018-02-11)

warning: tool `rustfmt` is already installed, remove it from `/home/gps/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
warning: tool `cargo-fmt` is already installed, remove it from `/home/gps/.cargo/bin`, then run `rustup update` to have rustup manage this tool.

$ cargo uninstall rustfmt
    Removing /home/gps/.cargo/bin/cargo-fmt
    Removing /home/gps/.cargo/bin/rustfmt

$ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'beta-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: checking for self-updates

   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.23.0 (766bd11c8 2018-01-01)
     beta-x86_64-unknown-linux-gnu unchanged - rustc 1.24.0-beta.11 (03f456d3c 2018-02-03)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.25.0-nightly (b8398d947 2018-02-11)
```

At this point I was scratching my head as to how to actually install `rustfmt` and `cargo-fmt` with `rustup`. I'm still not sure to be honest :/

**Comment by daboross** [comment]
I'm pretty sure `rustup` will just want to own `rustfmt` and `cargo-fmt` whether or not it actually has binaries to back them with. 

```sh
rustup update
rustup component add rustfmt-preview
```

works for me to install it most of the time (sometimes nightly versions don't have rustup at all..)

---

Regardless of that, it would be nice if `rustup` did not emit this warning when no toolchain has "rustfmt-preview" installed. If there's no chance that it can provide `rustfmt`/`cargo-fmt`, it should not complain about not being able to own those binaries.

**Comment by richardwhiuk** [comment]
This warning implies that it should just be removed - but surely a user should use `cargo uninstall rustfmt` instead?

**Comment by daboross** [comment]
If `rustfmt` was installed with cargo and you do want to replace it with the `rustup one, that's the right solution. Changing the message seems like it would be a different issue, though.

Ideally `rustup` shouldn't ask the user to remove it at all if none of the `rustup` toolchains have `rustfmt` installed in the first place.

**Comment by zoechi** [comment]
Just following the suggestion
```
warning: tool `rustfmt` is already installed, remove it from `/home/matthias/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
warning: tool `cargo-fmt` is already installed, remove it from `/home/matthias/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
```
seems to have fixed it.

**Comment by kinnison** [comment]
These days you'd get a good suggestion to add the component after following the recommendation to allow `rustup` to install its proxies so I think this is closeable.  Do others agree?

**Comment by rbtcollins** [comment]
Yes.

**Comment by kinnison** [comment]
Thank you @rbtcollins If anyone here thinks there's still a problem to be resolved, then a fresh issue which shows the *full* flow that isn't good enough, and suggests an improvement, would be best.  Please don't continue on this issue specifically.
