### ISSUE TITLE
Please add 1.11.0 tag

### ISSUE THREAD

**Issue by ynakao** [rust-lang/rustup#1356]
Please add 1.11.0 tag at 745cf43 to download the tarball easily.

**Comment by alexcrichton** [comment]
Done!

**Comment by ynakao** [comment]
Thanks! But does the tag be added to the right commit?
I think it should be at e751ff9 instead of c6a8f7c (already 1.10.0 tagged).

**Comment by alexcrichton** [comment]
Er oops, sorry about that! Forgot to do `git fetch`...
