### ISSUE TITLE
rustup show panics

### ISSUE THREAD

**Issue by tinywombat765** [rust-lang/rustup#1357]
`rustup show` panics with error:
`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:335:20`

Not sure why this is happening.  
I'm on void linux.

**Comment by tinywombat765** [comment]
I figured out this was because no default toolchain was set.

**Comment by hbobenicio** [comment]
Maybe this unwrap could at least be replaced with an `.expect("Default toolchain is not defined.")` or `.expect("No toolchain is defined")` to provide better info on this then.

**Comment by Jess3Jane** [comment]
I think this was fixed in 1.16 if i'm reading the changelog correctly

**Comment by tinywombat765** [comment]
@Jess3Jane Do you mean 1.6?

**Comment by eevee** [comment]
FYI, this is still happening with 1.16.0.
