### ISSUE TITLE
Rustup might get tricked by http caches

### ISSUE THREAD

**Issue by t-botz** [rust-lang/rustup#1358]
Right now I am running behind a company proxy which loves caching.
As of today, 16th Feb 2018,  Rust 1.24.0 has been release and heree is the output of my rustup update:

```console
$ rustup update
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: update not yet available, sorry! try again later
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: checking for self-updates

   stable-x86_64-apple-darwin unchanged - rustc 1.22.1 (05e2e1c41 2017-11-22)
  nightly-x86_64-apple-darwin unchanged - rustc 1.25.0-nightly (b5392f545 2018-01-08)
```
Obviously the company proxy is caching files. This behavior from the proxy is expected since it has been asked for the same files everytime (e.g. GET https://static.rust-lang.org/dist/channel-rust-stable.toml) and nor the client (rustup) nor the server dare sending a Cache-Control or expire header and thus the proxy is free to use its default "cache for unlimited time" behaviour.

The solution is simple, always send a `Cache-control: max-age=0, no-store, no-cache, must-revalidate` header, either as part of the request (rustup side) to invalidate the cache , or as part of the response (cloudfront) to avoid caching in the first place, or both.

**Comment by t-botz** [comment]
@alexcrichton Would that be possible to add those headers on cloudfront side? I'll do a PR to also do it client side.
All the files containing "stable", "nightly" or "beta" needs it

**Comment by alexcrichton** [comment]
@thibaultdelor hm I'm not acutally sure where these would be applied... How do headers get set in S3/Cloudfront? All the uploads currently happen as part of [this script](https://github.com/rust-lang/rust-central-station/blob/master/promote-release/src/main.rs) so the fix would probably go somewhere around there I think?

**Comment by t-botz** [comment]
Let me investigate. I dont have a S3/Cloudfront on my own right now but I'll try to set that up and do 
some testing.
