### ISSUE TITLE
Removing toolchains

### ISSUE THREAD

**Issue by KasMA1990** [rust-lang/rustup#1362]
I couldn't find any nice way of removing a toolchain once I'm done with it. For example, if I just downloaded a nightly version to play around with some unstable API, but it's not something I want to keep using going forward, so I'd like to just delete the nightly toolchain again.

Is this possible as-is, and I just missed it?

**Comment by t-botz** [comment]
I think you are looking for :
`rustup toolchain uninstall XXX`

**Comment by KasMA1990** [comment]
Gotcha, thanks! I wasn't aware the subcommands had their own help pages, which is why I couldn't find it.

**Comment by t-botz** [comment]
No worries, please close this issue
