### ISSUE TITLE
Wrong shebang

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rustup#1368]
The Rustup shell script is not fully POSIX compliant, but rather uses bashisms like `local`-scoped variables. When users attempt to run the rustup install script on different UNIX systems, they often get errors about missing `local` files/directories.

To fix this, either set the shebang to `#!/bin/bash`, or rewrite the script to avoid bashisms (checkbashisms can assist this process).

**Comment by Diggsey** [comment]
Fixed by #1269
