### ISSUE TITLE
Main web-page contains link to the page with web-miner

### ISSUE THREAD

**Issue by boozook** [rust-lang/rustup#1369]
Tha [main](https://rustup.rs) page contains the link to the [page](https://client00.chat.mibbit.com/?server=irc.mozilla.org&channel=%23rust-beginners) and that page contains web-crypto-miner and it's terrible.

I think that we should not encourage this madness and to correct the link to universal url-schema format ([e.g.](https://www.mirc.com/mirclink.html)) to something like this: <a href="irc://irc.mozilla.org:6697/rust-beginners">irc://irc.mozilla.org:6697/rust-beginners</a> .

![screen shot 2018-03-05 at 20 14 31](https://user-images.githubusercontent.com/888526/36989391-a6e51ef2-20b2-11e8-8731-877983cf1a39.png)

**Comment by Diggsey** [comment]
Looks like it's one of the ads on mibbit that is doing the crypto mining? I don't see that when I view the page. The problem is that an IRC link is often not very beginner friendly...

**Comment by boozook** [comment]
So maybe another [IRC web-client app](https://duckduckgo.com/?q=IRC+web-client&ia=web)?

>The problem is that an IRC link is often not very beginner friendly...

I think developers/programmers is not stupid :)

And IRC is not "beginner friendly" originally.
