### ISSUE TITLE
mktemp: too few X's in template 'rustup'

### ISSUE THREAD

**Issue by naftulikay** [rust-lang/rustup#1377]
As visible from [this Docker Hub build log](https://hub.docker.com/r/naftulikay/circleci-lambda-rust/builds/b2quu7btj8md9zlbf36fd59/), there is a strange issue that occurs when running `rustup` in a Docker container on Docker Hub infrastructure:

```
mktemp: too few X's in template ‘rustup’
rustup: command failed: mktemp -d -t rustup
```

What's especially interesting is that I can build the container locally without any issues, this issue only seems to show up on Docker Hub. 

Here are relevant parts of my Dockerfile:

```
FROM lambci/lambda:build-python3.6
# ...
# install rustup
RUN curl https://sh.rustup.rs -sSf | sudo -u ${RUST_USER} sh -s -- -y && \
  ${RUST_HOME}/.cargo/bin/rustup completions bash | tee /etc/bash_completion.d/rust >/dev/null && \
  chmod 0755 /etc/bash_completion.d/rust && \
  rsync -a ${RUST_HOME}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/man/man1/ /usr/local/share/man/man1/
```

I am trying to reproduce this locally.

**Comment by Diggsey** [comment]
Dup of #791

**Comment by naftulikay** [comment]
@Diggsey so there's no fix within rustup?

**Comment by Diggsey** [comment]
Rustup needs a place to write temporary files - the error message is slightly misleading, the non-BSD-compatible version of `mktemp` is only called if `mktemp -d` has already failed, and that failure is the real problem here.

**Comment by naftulikay** [comment]
Thank you for providing some insight here. So I should evaluate why the `mktemp -d` call is failing?

**Comment by Diggsey** [comment]
Yes
