### ISSUE TITLE
Suggest fix for users with certificate issues

### ISSUE THREAD

**Issue by sophiajt** [rust-lang/rustup#1378]
Can we detect certificate issues and give users suggestions on how to fix them?

Here's one example: https://twitter.com/purijatin7/status/974689948790960128?s=19

**Comment by kinnison** [comment]
I'm not entirely sure that we know for any given platform what to recommend.  If you have some concrete recommendations on what to do here I'd appreciate it, otherwise I think we'll just close this effectively "don't know how to fix" :D
