### ISSUE TITLE
Failed to install rust s390 tool chain on linux

### ISSUE THREAD

**Issue by amber-zhang** [rust-lang/rustup#1382]
After installed rust s390 on linux, rustc can't be run.

ibmadmin@Amber-Ubuntu:~$ curl https://sh.rustup.rs -sSf | sh
info: downloading installer

Welcome to Rust!

This will download and install the official compiler for the Rust programming 
language, and its package manager, Cargo.

It will add the cargo, rustc, rustup and other commands to Cargo's bin 
directory, located at:

  /home/ibmadmin/.cargo/bin

This path will then be added to your PATH environment variable by modifying the
profile file located at:

  /home/ibmadmin/.profile

You can uninstall at any time with rustup self uninstall and these changes will
be reverted.

Current installation options:

   default host triple: x86_64-unknown-linux-gnu
     default toolchain: stable
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
2

I'm going to ask you the value of each these installation options.
You may simply press the Enter key to leave unchanged.

Default host triple?
s390x-unknown-linux-gnu

Default toolchain? (stable/beta/nightly/none)
stable

Modify PATH variable? (y/n)
y

Current installation options:

   default host triple: s390x-unknown-linux-gnu
     default toolchain: stable
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation

info: syncing channel updates for 'stable-s390x-unknown-linux-gnu'
info: latest update on 2018-03-01, rust version 1.24.1 (d3ae9a9e0 2018-02-27)
info: downloading component 'rustc'
 46.0 MiB /  46.0 MiB (100 %)   3.1 MiB/s ETA:   0 s                
info: downloading component 'rust-std'
 59.8 MiB /  59.8 MiB (100 %)   3.1 MiB/s ETA:   0 s                
info: downloading component 'cargo'
  3.2 MiB /   3.2 MiB (100 %)   3.1 MiB/s ETA:   0 s                
info: downloading component 'rust-docs'
  4.6 MiB /   4.6 MiB (100 %)   3.1 MiB/s ETA:   0 s                
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
info: default toolchain set to 'stable'

  stable installed - (error reading rustc version)

Rust is installed now. Great!

To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH 
environment variable. Next time you log in this will be done automatically.

To configure your current shell run source $HOME/.cargo/env

ibmadmin@Amber-Ubuntu:~$ source $HOME/.cargo/env

ibmadmin@Amber-Ubuntu:~$ rustup show
Default host: s390x-unknown-linux-gnu

stable-s390x-unknown-linux-gnu (default)
(error reading rustc version)
ibmadmin@Amber-Ubuntu:~$ rustc
/home/ibmadmin/.rustup/toolchains/stable-s390x-unknown-linux-gnu/bin/rustc: 5: /home/ibmadmin/.rustup/toolchains/stable-s390x-unknown-linux-gnu/bin/rustc: Syntax error: "|" unexpected

**Comment by Diggsey** [comment]
You cannot use `s390x-unknown-linux-gnu` as a host triple if you're on an x86_64 machine. You should probably be adding `s390x-unknown-linux-gnu` as a target instead, via `rustup target add` after installing the toolchain for your `x86_64` host.
