### ISSUE TITLE
MSVC requirements are misrepresented

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rustup#1384]
See this:

![screenshot](https://i.imgur.com/73FMEEL.png)

The first mention says "2013 or later", but the second says "2015", and the third says "2013 or 2015."

Additionally, the first link is now incorrect; https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017 is the correct build tool link.

**Comment by Diggsey** [comment]
The intended meaning is that "2013 or later is required", but that if you're installing the build tools now it makes sense to install the newest ones (now 2017).

**Comment by Diggsey** [comment]
Dup of #1363
