### ISSUE TITLE
Rust-init.exe not working (Windows 10, 64 Bit)

### ISSUE THREAD

**Issue by Ronaldho80** [rust-lang/rustup#1386]
Dear all,

the current version (2018-04-05) rust-init.exe is not installing rustup on my Windows 10 VM 64 Bit / MSYS2 / GNU:
```
Current installation options:

   default host triple: gnu
     default toolchain: nightly
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
1

thread 'main' panicked at '', src\libcore\option.rs:874:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```

**Comment by abelsromero** [comment]
Problems also on Windows 8.1.
Not sure this is for the same reason but I had also problems updating the toolchains so I uninstalled rustup.
Now I cannot install it, rust-init.exe just fails with no information.

**Comment by chippers** [comment]
Windows 10 here too.  Running from explorer windows gives a "can't run on your PC" window.

![explorer_2018-04-14_15-44-19](https://user-images.githubusercontent.com/3301043/38773131-e6bfc272-3ffa-11e8-9c8f-5b65237e7e4d.png)


Running from git bash I get:
```
$ ./rustup-init.exe
bash: ./rustup-init.exe: cannot execute binary file: Exec format error
```

Grabbing it from archive.org at https://web.archive.org/web/20171228233143/https://win.rustup.rs/ gives an installer that works.

The rustup-init.exe that got downloaded today was 424 KB.  The one from archive.org was 13,314 KB so something significant has changed but I don't know anything about the project to check.

**Comment by ericmdantas** [comment]
Also happening on Windows 7.

The link https://web.archive.org/web/20171228233143/https://win.rustup.rs/ did work, though.

**Comment by Diggsey** [comment]
Looks like these are separate issues: @Ronaldho80 please post the backtrace you get when run with `RUST_BACKTRACE=1`.

Everyone else, please open a separate issue if you're still having problems and you're not getting the error `thread 'main' panicked at '', src\libcore\option.rs:874:4`.

**Comment by Jethril** [comment]
While having the same error, i get this using `RUST_BACKTRACE=1` :
```
Current installation options:

   default host triple: gnu
     default toolchain: stable
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
1

thread 'main' panicked at '', src\libcore\option.rs:874:4
stack backtrace:

```
(Windows 10 64 bits / GNU toolchain)

Is there any workaround to re-install rust without having this issue?

**Comment by mati865** [comment]
It happens when `rustup` config is broken.
In my case what worked is:
```
rustup set default-host x86_64-pc-windows-gnu
rustup default nightly-gnu
```

**Comment by xahon** [comment]
@mati865 Thanks. You helped me a lot. I tried hard to install rust on windows 10 until saw you comment

**Comment by kinnison** [comment]
I think this is either resolved or else no longer a problem due to user reinstallation.  It looks like a bad host triple 'gnu' rather than a full a triple, which broke the toolchain install, however that should no longer happen.  As such I'm going to close this issue.  If you encounter something similar with a modern rustup then please open a fresh issue for discussion.
