### ISSUE TITLE
Provide a "book" version

### ISSUE THREAD

**Issue by archer884** [rust-lang/rustup#1392]
Just read a conversation on discord where a user following along with the Rust book was pretty confused by a difference in behavior between the compiler in use in the book and the compiler installed on his system. That made me wonder about the difficulty/value associated with providing a "book" version via rustup. You know...
```
$ curl https://sh.rustup.rs -sSf | sh --book
```
...or something.

That said, I'm not even clear if this is the right place to be talking about this. It might make more sense to just change the code snippet in the book to request a specific version of the compiler, although I guess you can't pull the same stunt with Windows...

Anyway, just a thought. Mostly I thought I'd bring it up because Rust can be a fairly fast-moving target in comparison with other, more conservative languages.

**Comment by joshtriplett** [comment]
@archer884 If something in the book *failed* to work with current Rust, that sounds like a serious problem; could you please provide some more information or a link to an issue?

**Comment by archer884** [comment]
That was four months ago, dude. >.>
