### ISSUE TITLE
Check formatting on CI

### ISSUE THREAD

**Issue by cyplo** [rust-lang/rustup#1393]
While the code now conforms to the default rules of rustfmt it can be easy for it to diverge, as there is no feedback if someone introduces a change that is not formatted properly.
A CI build job that fails when formatting is off could be useful.

See discussion in #1390 for more background - in short it is not easy to specify a version of rustfmt that we can rely on.

**Comment by tesuji** [comment]
@kinnison This should be closed .

**Comment by kinnison** [comment]
Indeed it should, well spotted.

We have been checking formatting as part of CI for several months now.
