### ISSUE TITLE
After fresh install, fmt doesn't work properly

### ISSUE THREAD

**Issue by binary132** [rust-lang/rustup#1396]
Ubuntu 18.04 / x64

I nuked my .cargo path and reinstalled via rustup.rs.  I was then not able to use rustfmt, nor add it to my toolchains by full name (`rustfmt-preview-x86_64-unknown-linux-gnu`).  `cargo fmt` complained about an outdated rustfmt version.

On `rustup update`, I got a warning that rustfmt and cargo-fmt were in my .cargo/bin path and should be removed, so I manually removed those binaries with `rm`.  After this, `rustup update` did not add the binaries as I expected.

I was able to add the toolchains by name without the full path (`rustfmt-preview`) and it didn't work after that until I performed `rustup update`, at which point the binaries were linked into the cargo bin path.

**Comment by kinnison** [comment]
I believe we do a better job of handling the recreation of proxies, and with profiles we install the formatters by default.  As such, I'm closing this, but if you have similar issues still then I'd appreciate a fresh issue describing what you do and what you'd like to see happen.
