### ISSUE TITLE
cargo build --all does not obey rust-toolchain file

### ISSUE THREAD

**Issue by rukai** [rust-lang/rustup#1399]
I create a repo containing two crates one with a nightly rust-toolchain file and one without.
If I run the following in the root directory of the repo:
```
rustup default stable
cargo build --all
```
Then it attempts to build the nightly crate using the stable compiler despite the rust-toolchain file.
`cargo test --all` does the same.

**Comment by Diggsey** [comment]
This is an artifact of the way responsibility is divided between rustup and cargo. Rustup has no knowledge of workspaces, and will never turn one `cargo` invocation into multiple calls.

I don't think this is something we'll ever support - all projects within a workspace are intended to be built with the same version of the compiler.

**Comment by rukai** [comment]
In case this is useful for anyone who stumbles upon this.
The solution I ended up with was to move the rust-toolchain file to the root folder of the repo, this way it applies to every crate in the repo, and the repo as a whole. While not ideal, this allows `cargo test --all` to work

**Comment by gnzlbg** [comment]
@Diggsey I think `cargo` should warn or error when this happens and that this should be re-opened to track that.
