### ISSUE TITLE
Update stalls at syncing channel updates

### ISSUE THREAD

**Issue by jneumann** [rust-lang/rustup#1400]
I'm running into what seems like a networking issue, but it is only happening with Rustup. When I try to install a version of rust or update my current version of rust, the process stalls at "syncing channel updates for...". Most recently, I uninstalled Rustup and tried to reinstall rustup, but the process is stuck at the same step.

When I ran the command with _--verbose_, the file it was trying to download was the *.toml.sha256 file, which I can manually download via curl without issue.

**Comment by jneumann** [comment]
This seems to be a duplicate of #1328, for which no solution was posted.

**Comment by jneumann** [comment]
I narrowed it down to an issue with my ISP's DNS. Unfortunately, I don't know enough about how the Internet works to narrow it down further. If somebody else sees this issue, I'd be curious how to go about debugging it effectively.

**Comment by iruizr7** [comment]
For another people facing this:

This is due to the new `reqwest` backend added to rustup. In my own experience `reqwest` struggles with some not-very-common networking scenarios, like `search -` being present in `resolv.conf` and the like. 

So, the solution is just to instruct rustup to use battle-proven `curl` backend by setting a environment variable:

```shell
export RUSTUP_USE_CURL=1
rustup update
# Or just executing the online oneliner present at https://rustup.rs/, which was my case
```

**Comment by pedroapero** [comment]
> For another people facing this:
> 
> This is due to the new `reqwest` backend added to rustup. In my own experience `reqwest` struggles with some not-very-common networking scenarios, like `search -` being present in `resolv.conf` and the like.
> 
> So, the solution is just to instruct rustup to use battle-proven `curl` backend by setting a environment variable:
> 
> ```shell
> export RUSTUP_USE_CURL=1
> rustup update
> # Or just executing the online oneliner present at https://rustup.rs/, which was my case
> ```

Worked for me also for installation in a container:
```
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | RUSTUP_USE_CURL=1 sh -s -- -y
```
