### ISSUE TITLE
Make debugging rustc easier

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rustup#1402]
It would be nice to be able to say `rustc +toolchainname +gdb ...` and have rustup call `gdb --args rustc` (with similar support for lldb and rr record). Right now it's annoying to debug rustc directly since you have to set up all the correct environment vars as well.

**Comment by Diggsey** [comment]
Can't you do something like `rustup run nightly gdb rustc ...`?

**Comment by kinnison** [comment]
@Manishearth Is this still an issue, or is `rustup run nightly ...` sufficient?

**Comment by Manishearth** [comment]
It is!
