### ISSUE TITLE
Add support for watchOS and tvOS targets

### ISSUE THREAD

**Issue by chrisballinger** [rust-lang/rustup#1405]
Not sure if this is the right place to track this, but I was experimenting with creating a [template](https://github.com/chrisballinger/rust-framework-template) for packaging Rust libraries for macOS/iOS/watchOS/tvOS, and noticed that rustup targets for watchOS and tvOS were missing. I'm guessing there isn't much demand for these targets, but for the sake of completeness perhaps they could be added. They both require bitcode support, but it looks like that's finally resolved in the recent nightlies.

* armv7k-apple-watchos
* i386-apple-watchos
* aarch64-apple-tvos
* x86_64-apple-tvos

Could someone point me in the right direction for what would need to be done to add these targets and contribute them upstream?

Thanks!

**Comment by Diggsey** [comment]
It looks like these targets are not currently built upstream:
https://github.com/rust-lang/rust/issues/48862

**Comment by simlay** [comment]
I added tvOS upstream. Adding watchOS upstream involves knowing some attributes about the watchOS architecture. If anyone knows what to put in [these fields](https://github.com/rust-lang/rust/blob/38114ff16e7856f98b2b4be7ab4cd29b38bed59a/src/librustc_target/spec/aarch64_apple_tvos.rs#L6) it would require the new target parameters, dealing with the `SDKROOT` stuff in the [apple_sdk_base](https://github.com/rust-lang/rust/blob/38114ff16e7856f98b2b4be7ab4cd29b38bed59a/src/librustc_target/spec/apple_sdk_base.rs#L46) file, and then adding a field to the [AppleOS enum](https://github.com/rust-lang/rust/blob/38114ff16e7856f98b2b4be7ab4cd29b38bed59a/src/librustc_target/spec/apple_sdk_base.rs#L21).

**Comment by chrisballinger** [comment]
@simlay Awesome! I know that watchOS still supports 32-bit for Series 1-3, and 64-bit for Series 4-5, and that the 64-bit arch uses 32-bit pointers.

**Comment by HindrikStegenga** [comment]
@simlay Does that mean I can somehow get Rust code to compile on tvOS with std support? And if so, could you tell me how or where I can find on how to proceed?
