### ISSUE TITLE
rustup show: add flag to show only active toolchain

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rustup#1406]
I often want to know which toolchain is active for a certain directory (and which directory has the override). Having `rustup show` first print a few dozen lines of installed toolchains is rather annoying in that situation.

It would be nice to have a flag which would cause `rustup show` to only print the active toolchain. (For me it would even be preferable to make that the default behavior, since the list of installed toolchains is easily available via `rustup toolchain list`).

**Comment by das-sein** [comment]
@Diggsey I think this is resolved by `rustup show active-toolchain`, right?

**Comment by dwijnand** [comment]
Possibly resolved by #1633 (using `rustup default` instead)?

**Comment by TimNN** [comment]
> @Diggsey I think this is resolved by `rustup show active-toolchain`, right?

This does not quite address my original issue: It shows the active toolchain, but not _**why**_ it is active (e.g. which directory the override is coming from, or that the default is active).



> Possibly resolved by #1633 (using `rustup default` instead)?

I don't have a build with that patch, but from the name of the command, I don't believe that this will resolve my issue: I'm interested in the _active_ toolchain, not the _default_ one.

**Comment by dwijnand** [comment]
Good point.

**Comment by das-sein** [comment]
@Diggsey I think I figured out what you mean. The `rustup show` command outputs the reason for the override for any override you have set, but `rustup show active-toolchain` didn't do that. I've started a PR with the more standard behavior. Let me know how I did.
