### ISSUE TITLE
Running a command against multiple toolchains

### ISSUE THREAD

**Issue by dwijnand** [rust-lang/rustup#1413]
(Originally reported downstream in cargo: https://github.com/rust-lang/cargo/issues/5414)

Sometimes (for example within Cargo's codebase) you have code and/or tests that behave differently according to the toolchain used.

In such cases there's no convenient way to run a command, such as `test`, against multiple toolchains.

The workaround I've used is to call cargo twice in the shell, with the toolchain argument change, e.g:

```bash
CFG_DISABLE_CROSS_TESTS=1 cargo test run::run_example \
  && CFG_DISABLE_CROSS_TESTS=1 cargo +nightly test run::run_example
```

I've no idea what that could be, maybe something like:

```bash
CFG_DISABLE_CROSS_TESTS=1 cargo +stable/+nightly test run::run_example
```

**Comment by Diggsey** [comment]
I think this is quite a niche feature with an easy workaround, so I'm not inclined to add it to rustup: this kind of thing is exactly what shells are designed for.
