### ISSUE TITLE
Binaries compiled on Raspberry Pi with arm-unknown-linux-musleabihf fail on the same device

### ISSUE THREAD

**Issue by michaelherger** [rust-lang/rustup#1415]
I'm build [librespot](https://github.com/librespot-org/librespot) binaries on my Raspberry Pi running Raspbian. Up until Rust 1.21 I was able to use arm-unknown-linux-musleabihf as a target. Anything after that would create invalid binaries. The resulting executable is not executable after all. They can't be run on the same Raspbian system.

I tested 1.22.1 and 1.24.0.

**Comment by Diggsey** [comment]
This sounds like an issue with the compiler, please report to rust-lang/rust

**Comment by michaelherger** [comment]
https://github.com/rust-lang/rust/issues/51112
