### ISSUE TITLE
rustup activates the wrong date of rust

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rustup#1417]
I want to install rust, formerly nightly, v1.27.0, dated 2018-05-16. However, when I instruct rustup to do this, 1.27.0-nightly dated 2018-05-15 is active instead, which breaks clippy v0.0.201:

```console
$ rustup update nightly-2018-05-16
$ rustup default nightly-2018-05-16

$ rustup show
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2018-05-16-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-2018-05-16-x86_64-unknown-linux-gnu (default)
rustc 1.27.0-nightly (f0fdaba04 2018-05-15)

$ rustc --version
rustc 1.27.0-nightly (f0fdaba04 2018-05-15)
```

I'm curious if rustup is somehow failing to activate the right dated version, or if the release itself features conflicting timestamps in its packaging? I just don't know.

In any case, as a workaround, I am downgrading clippy further, from v0.0.201 to v0.0.200, which is then compatible with rust 1.27.0-nightly 2018-05-15 AKA 2018-05-16, or really any 1.27.0-nightly on or after 2018-05-13.

**Comment by Diggsey** [comment]
Rustup installs the correct version, but unfortunately `rustc --version` reports the *date of the last commit*, not the *release date*.

**Comment by mcandre** [comment]
👍 Ah, gotcha. Could these different dates be unified somehow?

**Comment by Diggsey** [comment]
@mcandre https://github.com/rust-lang/rust/issues/36773
