### ISSUE TITLE
SSL certificate verify failed when using reqwest backend

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/rustup#1424]
When using `RUSTUP_USE_REQWEST=1 rustup update`, I'm seeing this error that prevents updating:

```
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256'
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-beta.toml.sha256'
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-nightly.toml.sha256'
error: could not download file from 'https://static.rust-lang.org/rustup/release-stable.toml'
info: caused by: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1269
```

I don't have an exact date, but it seemed start happening around the Rust 1.26 release. Versions of software:

- `rustup -v`: `rustup 1.11.0 (e75ff9f8 2018-02-13)`
- `openssl version`: `1.0.2g 1 Mar 2016`

**Comment by Diggsey** [comment]
@seanmonstar looking at the code, the reqwest backend doesn't do anything special, so presumably this is a bug in reqwest? You seem better placed (as someone who can reproduce the issue, and the developer of reqwest) to diagnose this issue than anyone!

Have you tried updating your CA certificates?

**Comment by seanmonstar** [comment]
Indeed, I can definitely debug this!

So, first thing I did was to build the `examples/simple.rs` in the reqwest repo, changed to try to download `https://static.rust-lang.org/rustup/release-stable.toml`, and... it works just fine! So, I'm wondering if it is do to the `rustup 1.11.0` binary having an older version of `native-tls` than what I'm getting when building now, and if that is the reason or not.

Is there logs or something for the 1.11.0 build that would tell what versions of crate were used?

**Comment by Diggsey** [comment]
There are tags in the git repo, so here's the lock file for that point in time:

https://github.com/rust-lang-nursery/rustup.rs/blob/1.11.0/Cargo.lock#L567

Looks like `native-tls` was on version `0.1.5`

**Comment by kinnison** [comment]
We've been using reqwest by default for quite a while now without major issue (thanks Sean!) so I think this is closeable.  if you disagree, then shout and I'll reopen.
