### ISSUE TITLE
Install a specific commit

### ISSUE THREAD

**Issue by nrc** [rust-lang/rustup#1429]
It would be great to be able to install a specific commit of Rust as well as nightly releases. We have artefacts for every build so this should be possible; in fact, @kennytm has a script which does exactly this: https://github.com/kennytm/rustup-toolchain-install-master

**Comment by nrc** [comment]
One motivation is to make it easier to test tools when a broken tool is blocking nightly releases

**Comment by Diggsey** [comment]
@nrc how does this work? Is there actually a manifest that is built?

**Comment by nrc** [comment]
I assume we build everything necessary for every PR (so this would only work for PR commits, not every commit). If not it should be easy to have the Rust infra make the manifest

**Comment by anp** [comment]
I'm interested in making this happen to ease management of [lolbench](https://github.com/anp/lolbench). I started a conversation over at https://github.com/rust-lang/rust-central-station/issues/82 about getting the manifest info that will make this a straightforward change to rustup.

**Comment by dtolnay** [comment]
- Duplicate of #977

**Comment by thekief** [comment]
@nrc is that issue still being considered? I have a use case that requires me to have, e.g. older nightly toolchains installed. 
For example, trying to get 1.69.0 basically results in a manual binary search, deducting which date contains the most recent build of it.

**Comment by rami3l** [comment]
Closing as duplicate of #977.
