### ISSUE TITLE
Broken link in rustup-init.exe

### ISSUE THREAD

**Issue by Draphar** [rust-lang/rustup#1431]
I downloaded rustup-init.exe for Windows today, without having Visual C++ Build Tools installed it showed this text (among something more):

```
The easiest way to acquire the build tools is by installing Microsoft Visual 
C++ Build Tools 2015 which provides just the Visual C++ build tools:

  http://landinghub.visualstudio.com/visual-cpp-build-tools
```

However, the website look like this
![screenshot_1](https://user-images.githubusercontent.com/26834125/41195678-a5a63dc0-6c32-11e8-9378-f7bf50b5a296.png)
So apparently there are no build tools.

**Comment by Diggsey** [comment]
Dup of #1363 already fixed pending release in #1428
