### ISSUE TITLE
[feature]: set the default toolchain with rust-toolchain

### ISSUE THREAD

**Issue by csmoe** [rust-lang/rustup#1433]
`rustup default` complains this currently:
```
error: The following required arguments were not provided:
    <toolchain>
```
but it will be better to tell `rustup default` to:
```
if rust-toolchain.exsits_in_project_root {
    set_default
else {
    err: please create rust-toolcain file OR add <toolchain> arg
}
```

**Comment by Diggsey** [comment]
`rustup default` sets the *default* toolchain, ie. the toolchain to use as a fallback when one is not configured via an override or via `rust-toolchain`. If you wish to see what the currently active toolchain is, you can use `rustup show`.

Is the feature request that `rustup default` with no arguments should set the toolchain to whatever is the currently active toolchain?

**Comment by csmoe** [comment]
@Diggsey 
> Is the feature request that rustup default with no arguments should set the toolchain to whatever is the currently active toolchain?

yes, I want `rustup default` without args to set the toolchain activated by `rust-toolchain`(if the file exsits in current path).

**Comment by joshtriplett** [comment]
That seems like an excessively magic behavior to me. What's the use case for this, given that rust-toolchain will always cause rustup to use that toolchain in your current path?

**Comment by csmoe** [comment]
@joshtriplett I have to admit that I misunderstood how `rustup` works.
