### ISSUE TITLE
failed to update nightly

### ISSUE THREAD

**Issue by cosmtrek** [rust-lang/rustup#1442]
![screen shot 2018-06-22 at 12 06 43](https://user-images.githubusercontent.com/8832222/41757462-cc43b12e-7614-11e8-95cd-3c4fcdf0efaa.png)

or do I miss anything?

**Comment by pravic** [comment]
#1442 was first, but #1443 has better title and textual description.

**Comment by Diggsey** [comment]
Dup of #1443
