### ISSUE TITLE
Error: failed to parse URL (can't install nightly)

### ISSUE THREAD

**Issue by atoav** [rust-lang/rustup#1443]
I did a fresh (default) install with rustup init.exe, but no matter what any attempted nightly install (this also includes `rustup update nightly`) fails.  

```
rustup install nightly
info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
info: latest update on 2018-06-22, rust version 1.28.0-nightly (662c70a59 2018-06-21)
info: downloading component 'rustc'
error: failed to parse url: 1.28.0-nightly (662c70a59 2018-06-21)/2018-06-22/rustc-nightly-x86_64-pc-windows-msvc.tar.xz
info: caused by: relative URL without a base
```

Outputs of where and --version
```
λ where rustup
C:\Users\forelle\.cargo\bin\rustup.exe

λ rustup --version
rustup 1.11.0 (e751ff9f8 2018-02-13)
```

**Comment by robertDurst** [comment]
Wanted to add on here, to bring more/different info to help solve this.

I am running Mac OS 10.13.4 and had previously updated my stable from `1.26.2` --> `1.27.0`. 

Then I decided to update nightly so I ran `rustup install` and received the following error message:

```shell
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: latest update on 2018-06-22, rust version 1.28.0-nightly (662c70a59 2018-06-21)
info: downloading component 'rustc'
error: failed to parse url: 1.28.0-nightly (662c70a59 2018-06-21)/2018-06-22/rustc-nightly-x86_64-apple-darwin.tar.xz
info: caused by: relative URL without a base
 ```

Also, I opened a PR on the `wasm_bindgen` repo and travis there [failed as well](https://travis-ci.org/rustwasm/wasm-bindgen/builds/395322541?utm_source=github_status&utm_medium=notification).

**Comment by mati865** [comment]
It's Rust build system issue and should be tracked in main repo: https://github.com/rust-lang/rust/issues/51699

**Comment by kinnison** [comment]
This was a bug in Rust's generation of the channel manifest.
