### ISSUE TITLE
Rustup didn't install the latest version of Rust by default

### ISSUE THREAD

**Issue by yerke** [rust-lang/rustup#1445]
I just installed rust running `curl https://sh.rustup.rs -sSf | sh` as suggested by https://www.rust-lang.org/en-US/install.html . It installed 1.25 stable instead of 1.27 stable (latest stable at the time of writing this issue). I don't think it should be the default behavior.
I had to do `rustup update` to update to 1.27.

**Comment by nodakai** [comment]
I recently had a similar experience with the `beta` channel but I'm not sure what exactly happened to me. I really wish `rustup` collected logs on how it interacted with the server by default.

**Comment by Diggsey** [comment]
@yerke you must have already installed rustup previously, when 1.25 was the latest stable. When you installed it again it simply reused your existing installation. It does print out a notice but it's not as visible as it could be. Dup of #1079
