### ISSUE TITLE
Add `--prefix` option to set instalation directory

### ISSUE THREAD

**Issue by jockerz** [rust-lang/rustup#1448]
Having installation directory option is a kind of joy.
For me, i'd like to put _non-apt_ packages installed on `/usr/local` or `/opt` on my ubuntu laptop.
For some, maybe got their __home__ partition already full.

For this issues, having installation directory option will help.

Possible command enhancement: 
```
curl` https://sh.rustup.rs -sSf | sh -s -- --prefix /usr/local/rust
```

**Comment by nodakai** [comment]
Try setting two environment variables `RUSTUP_HOME` and `CARGO_HOME` and run the installer again.

`RUSTUP_HOME` will accomodate the actual installations of the toolchains whereas the `rustup` trampoline executables will be installed under `$CARGO_HOME/bin`

* https://github.com/rust-lang-nursery/rustup.rs#choosing-where-to-install

I guess the README needs some visual illustrations on how they work.

**Comment by Diggsey** [comment]
Closing this because:
- There is already a way to customise the installation directory, via `RUSTUP_HOME` and `CARGO_HOME`
- A `--prefix` option is tricky because rustup would not know where to find itself after installation.

**Comment by jockerz** [comment]
@Diggsey, @nodakai: thank you and sorry for late reply

Set the RUSTUP_HOME and CARGO_HOME work as expected.
