### ISSUE TITLE
Doesn't print in colour and messes up re-printing in the same line

### ISSUE THREAD

**Issue by ghost** [rust-lang/rustup#1451]
When I update Rust, it looks like this:
![capture](https://user-images.githubusercontent.com/23280582/42092286-0221907a-7bc6-11e8-8e11-946e2b076d58.PNG)
I'm using Windows 10 Home Single Language, Version 1803.
I use Hyper as my terminal emulator (I just love its UI). It auto-updates, but I don't think the version of Hyper is relevant because it has done this for every update I've done.
Right now, I have `rustup 1.11.0 (e751ff9f8 2018-02-13)`.

Using powershell doesn't print in colour but re-printing on the same line works.

**Comment by pmarcelll** [comment]
The color issue is probably https://github.com/zeit/hyper/issues/2038.

**Comment by pmarcelll** [comment]
I investigated a bit, this line is responsible for clearing the line:

https://github.com/rust-lang-nursery/rustup.rs/blob/bb6f65f08ba3e8a6619a033b65611be0f0023e73/src/rustup-cli/download_tracker.rs#L163

It looks like this is a bug in `term`, or a bug in `hyper`. It's also worth mentioning, that the `Result` from the `carriage_return()` method is completely ignored here, so it might be possible to retrieve an error message from this method.

**Comment by pmarcelll** [comment]
Changing the line in question to `unwrap()` yields:
```
?[1minfo: ?[0msyncing channel updates for 'stable-x86_64-pc-windows-msvc'
?[1minfo: ?[0mlatest update on 2018-06-21, rust version 1.27.0 (3eda71b00 2018-06-19)
?[1minfo: ?[0mdownloading component 'rustc'
Total:   6.9 MiB Speed:   0 B/s                thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotSupported', libcore\result.rs:945:5
```

So [`carriage_return()`](https://github.com/Stebalien/term/blob/c01b2a7fbf2a9e1854ce02f5721c2a03364f1221/src/win.rs#L270) does something that is not supported in `hyper`. Other terminals work correctly, so this is either a missing feature in `hyper`, or `term` needs a workaround (because regular `\r` works).

**Comment by joshtriplett** [comment]
Since this issue lies either in `hyper` or in `term` (or both), and apparently not in rustup, could you please report it on one of those two crates instead?
