### ISSUE TITLE
OpenBSD 6.3 not recognized

### ISSUE THREAD

**Issue by bugabinga** [rust-lang/rustup#1452]
navigator.platform:
OpenBSD amd64
navigator.appVersion:
5.0 (X11)

**Comment by nodakai** [comment]
https://forge.rust-lang.org/platform-support.html

> Tier 3 platforms are those which the Rust codebase has support for, but which are not built or tested automatically, and may not work. **Official builds are not available.**

> 64-bit OpenBSD

(emphasis mine)

Rustup is basically a tool to download and install official Rust binaries, so our issue isn't just about whether or not the installer can recognize OpenBSD.

Possibly related topics:

* Rustup can download binaries from a non-standard URL configured via the `$RUSTUP_DIST_SERVER` environment variable (see README.md)

* Nowadays Rust can be installed on several major BSD variants using the `pkg` package manager rust-lang/rust-www#1101

* Shell script for building `beta` and `nightly` Rust on OpenBSD using the `pkg`-provided version https://github.com/semarie/build-rust
  - Comes with a nice write-up on technical challenges in making them available for Rustup

**Comment by bugabinga** [comment]
Thanks for summarizing the issue!

I followed the instructions on the [website](https://rustup.rs/), that appear for people using OpenBSD.
And although I am roughly aware of the points you listed, I assume you are interested in the data point ;).
Closing this now, as there is nothing really to do until OpenBSD gets bumped in Tiers.
