### ISSUE TITLE
Instructions provided by rustup-init.exe don't lead to a working install anymore

### ISSUE THREAD

**Issue by cswinter** [rust-lang/rustup#1454]
The Windows installer suggests downloading the Visual C++ Build Tools 2015 from https://landinghub.visualstudio.com/visual-cpp-build-tools which gives a 404.
A quick google didn't manage to turn up any working links to the standalone installer.

**Comment by cswinter** [comment]
Hmm https://www.visualstudio.com/downloads/ refers me to https://visualstudio.microsoft.com/vs/older-downloads/ for older versions. Clicking on the download button on that page requires me to log in to a microsoft account after which I am greeted by this page:

![image](https://user-images.githubusercontent.com/12845088/42136410-9ea0edc0-7d0f-11e8-9d07-72e59fe98a05.png)

The old downloads don't seem to have an option for the community edition which might be why.

**Comment by cswinter** [comment]
Further googling turned up this page https://www.microsoft.com/en-us/download/details.aspx?id=48159 which allows you to download "Microsoft Build Tools 2015"

**Comment by cswinter** [comment]
Compiling with cargo now spews out massive `error: linking with `link.exe` failed: exit code: 1` errors so presumably that doesn't actually install the right thing :/

**Comment by cswinter** [comment]
For reference:
error: linking with `link.exe` failed: exit code: 1
  |
  = note: "link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\cleme\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.build_script_build0.rcgu.o" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.build_script_build1.rcgu.o" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.build_script_build10.rcgu.o" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.build_script_build11.rcgu.o" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.build_script_build12.rcgu.o" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.build_script_build13.rcgu.o" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.build_script_build14.rcgu.o" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.build_script_build15.rcgu.o" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.build_script_build2.rcgu.o" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.build_script_build3.rcgu.o" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.build_script_build4.rcgu.o" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.build_script_build5.rcgu.o" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.build_script_build6.rcgu.o" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.build_script_build7.rcgu.o" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.build_script_build8.rcgu.o" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.build_script_build9.rcgu.o" "/OUT:C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.exe" "C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\build\\heapsize-1b72f00bbd2c86b4\\build_script_build-1b72f00bbd2c86b4.crate.allocator.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\cleme\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\cleme\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\cleme\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:C:\\Users\\cleme\\src\\LocustDB\\target\\debug\\deps" "/LIBPATH:C:\\Users\\cleme\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\cleme\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-26ec27827ae0ca62.rlib" "C:\\Users\\cleme\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-e34d54f3f9fdb6ac.rlib" "C:\\Users\\cleme\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-419a8101e2d3fa6d.rlib" "C:\\Users\\cleme\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-c0a4078a0099457d.rlib" "C:\\Users\\cleme\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc_system-d5549d68e4c6523f.rlib" "C:\\Users\\cleme\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-73a63b968e0bb534.rlib" "C:\\Users\\cleme\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-eb374a3dfd2a7a7f.rlib" "C:\\Users\\cleme\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-fe8341acd189dfc1.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "shell32.lib" "msvcrt.lib"
  = note: /usr/bin/link: extra operand ‘/LIBPATH:C:\\Users\\cleme\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib’
          Try '/usr/bin/link --help' for more information.

**Comment by cswinter** [comment]
I managed to get things working by getting the microsoft-visual-cpp-build-tools from chocolatey: https://chocolatey.org/packages/microsoft-visual-cpp-build-tools
This does require you to also install chocolatey first (and maybe Python).

**Comment by mattico** [comment]
Thanks, Microsoft, for breaking your URLs.

It seems hard to find a reliable URL to point to for the 2015 build tools, so we could probably start recommending the 2017 ones:

https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017

Though who knows how long that URL will survive.

**Comment by mattico** [comment]
There's also this URL: https://go.microsoft.com/fwlink/?linkid=840931. I'm not a Microsofter but I believe `go.microsoft.com` is their system to provide permalinks which redirect to the correct destination for their given content. Hopefully if they change the Visual Studio landing page again they'll update that redirect accordingly.

**Comment by Diggsey** [comment]
Should be fixed in 1.12
