### ISSUE TITLE
Config per project

### ISSUE THREAD

**Issue by GildedHonour** [rust-lang/rustup#1459]
Is there a special config file which will change rustup per project where I'm currently in? Stable <-> nightly. 

Similar to `.ruby-version` which changes the version of ruby when I `cd ` to a project

**Comment by Diggsey** [comment]
There are two ways to specify per-project overrides:

1) https://github.com/rust-lang-nursery/rustup.rs#directory-overrides
2) https://github.com/rust-lang-nursery/rustup.rs#the-toolchain-file

**Comment by philippludwig** [comment]
The actual answer to the question is:  `rustup override set nightly`

The links don’t point to the specific documentation anymore.

**Comment by kinnison** [comment]
If you're going to add comments to old closed issues, please actually refer to the right thing.  The equivalent of the `.ruby-version` is the `rust-toolchain` file which is now documented here: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

**Comment by philippludwig** [comment]
@kinnison I added the comment because this is issue the first result on Google when you search on how to set the toolchain per project.
