### ISSUE TITLE
Add 1.13.0 release tag

### ISSUE THREAD

**Issue by ynakao** [rust-lang/rustup#1460]
Please add ~1.12.0~ 1.13.0 release tag at ~573895a~ ea9259c or d9690a8 ? to make linux distribution maintainers update rustup package easily.

**Comment by K900** [comment]
Same, but for 1.13.0

**Comment by ynakao** [comment]
According to the latest update, I edited the issue title and comment. Thanks @K900 for the notification.

**Comment by K900** [comment]
@alexcrichton Sorry for pinging you directly, but this seems like a quick fix (just add a tag), and many downstream distributions will benefit from it a lot :)

**Comment by alexcrichton** [comment]
Done now!
