### ISSUE TITLE
rustup update hang 

### ISSUE THREAD

**Issue by Geobert** [rust-lang/rustup#1464]
On my corporate laptop, rust-docs takes a very long time to install but the process manage to complete.
The long time is due to bad SSD + encryption + McAfee anti virus I think.

The issue is that rustup doesn't end after the display of the toolchains version at the end of the update process. Had to kill it, and if I run `rustup update` again, everything is up to date.

So no big deal, but strange nonetheless. Looks like a timeout of somekind.

Windows 7 64 bits, powershell 5

**Comment by Diggsey** [comment]
Making docs optional is an existing feature request, which is blocked on the ability to have optional-but-default components. Other than that, this sounds like an issue which is out of our control.

If there's a different pattern of file access we can use which is less likely to cause your antivirus to lock up, then I would consider accepting a PR.

**Comment by leonardo-m** [comment]
Why was this issue closed?

**Comment by Diggsey** [comment]
There are already several issues covering making docs optional/slow docs installation/etc. There's nothing actionable in this ticket that isn't covered by others - antiviruses make file access even slower than it is to begin with, particularly non-microsoft ones, that's just their inherent trade off.

**Comment by leonardo-m** [comment]
At the end of the updating done by Rustup it hangs. The CPU and disk usages are both zero. I don't know what's happening but it's not copying files, nor scanning them. And I've kept the shell open for hours with no changes.

**Comment by johnthagen** [comment]
@leonardo-m The OP cited Windows 7 and Powershell 5. For the sake of comparison, are you also using this configuration or some other version of Windows and/or shell?

In Windows 10 / `cmd`, `rust-docs` takes a very long time to install, but there is always CPU/disk activity for me and it will finally complete (doesn't hang forever).

**Comment by leonardo-m** [comment]
I am using Windows 8.1, a regular shell, and I am installing the x86_64-pc-windows-gnu. The CPU/disk activity ends in a minute (I have a SSD) and then it hangs.

**Comment by leonardo-m** [comment]
Now the problem is solved for real in the last Nighties.

**Comment by Geobert** [comment]
I don't think rustup is tied to Rust nightly. I just had the issue this morning updating to Rust 1.33.
with `rustup 1.16.0 (beab5ac2b 2018-12-06)`
