### ISSUE TITLE
[Feature] Query rustup for the active toolchain's root directory

### ISSUE THREAD

**Issue by purpleposeidon** [rust-lang/rustup#1466]
Often I need to set `LD_LIBRARY_PATH`, for using tools like `valgrind`, `perf` and `renderdoc`. I can use something like this:
```
RUST_LIBS="$(dirname $(rustup which rustc))/../lib/"
```

But it'd be nice to have a more direct way. Perhaps a new subcommand in rustup, `rustup root`? AFAICT there's nothing in rustup that's about "query the properties of whatever the active toolchain is".

Alternatives:
1. Symlink the toolchain libs into `target/$profile/dep`
2. A shell script in `$RUST_ROOT/bin/`.

**Comment by Diggsey** [comment]
`rustc --print sysroot`
