### ISSUE TITLE
Rustup installs very old nightly toolchain for msvc

### ISSUE THREAD

**Issue by CasualX** [rust-lang/rustup#1475]
When I run `rustup install nightly` I get a very very old nightly:

    info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
    info: latest update on 2017-05-08, rust version 1.19.0-nightly (d985625b3 2017-05-07)

That can't be right, what I am I doing wrong and how do I install a toolchain that tracks the nightly channel for `x86_64-pc-windows-msvc`?

Rustup version `rustup -V`:

    rustup 1.13.0 (ea9259c1b 2018-07-16)

Already installed toolchains `rustup toolchain list`:

    stable-x86_64-pc-windows-msvc (default)

**Comment by CasualX** [comment]
I found the issue, I still had RUSTUP_DIST_SERVER set to the dev server when downloading the stable-1.28.0 prerelease.

The [command suggested here on internals](https://internals.rust-lang.org/t/help-test-the-1-28-0-prerelease/8097) doesn't work on Windows, so I manually set the env var with `SET RUSTUP_DIST_SERVER=https://dev-static.rust-lang.org` and ran `rustup update stable` separately.

I considered that this might impact me in the near future but I assumed things would be fine and I didn't restart my cmd nor used a separate cmd window so the env var stayed around.

Some off-hand suggestions:

Make the command offered to try the prerelease also work out of the box on Windows where the env var doesn't stick around, or otherwise warn Windows users.

When the env var is set make rustup print extra information to the console informing the user that they're using a non-standard configuration.

Keep the dev server more up to date so that there's less of a difference between it and the default configuration.

Thanks!

**Comment by kinnison** [comment]
I don't really think this is the fault of `rustup` so I'm going to close this.  If you still think this needs better documentation then perhaps a better place might be to discuss with the release team about how they announce pre-releases?
