### ISSUE TITLE
rustup toolchain: print the path the the toolchain

### ISSUE THREAD

**Issue by vext01** [rust-lang/rustup#1479]
On my system I have:
```
$ rustup toolchain list
stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
stage1
```

One question I might ask is: "where are these toolchains on the filesystem"? Especially for the manually linked (using `rustup toolchain link`) toolchain `stage1`.

How about `rustup toolchain list -v` prints the toolchains with their paths?

Thanks!

**Comment by kinnison** [comment]
I think that should be possible.  I'm prepared to mentor someone who wants to add this functionality.

**Comment by BeniCheni** [comment]
Friendly note that I’ve tried #1988 for this issue. Looking forward to review feedback. Thanks.
