### ISSUE TITLE
Track missing components

### ISSUE THREAD

**Issue by nrc** [rust-lang/rustup#1487]
So that if a component is missing and the user tries to add it, Rustup can explain. Ideally it could also suggest the last release with the component.

**Comment by nrc** [comment]
I think this should be fixed by https://github.com/rust-lang/rust/pull/53715

I wish it were easier to test this

**Comment by nrc** [comment]
> it could also suggest the last release with the component

this part is not done, and I'm not sure how to implement it

**Comment by sunjay** [comment]
It would also be really helpful if rustup could ask whether or not you want to continue when upgrading would remove a component you previously had installed. If asking for more input would break stuff, we could also error out when an installation would uninstall a component and have an extra --force flag or something to push the update through anyway.

**Comment by kinnison** [comment]
I think that current behaviour, especially with profiles and nightly backtracking, solves the intent of this issue.
