### ISSUE TITLE
Valgrind compat

### ISSUE THREAD

**Issue by shanemikel** [rust-lang/rustup#1494]
The rust toolchain installed with rustup on my Ubuntu linux platform doesn't seem to be compatible with valgrind.  I've tried various things like using #![feature(alloc_system)], to no avail.

one of the answers mentioned in rust-lang/rust#28224 is to build jemalloc with --enable-valgrind

**Comment by joshtriplett** [comment]
This is a bug in rust, not in rustup. The planned switch to the system allocator should fix it, and in the interim, you should be able to switch to the system allocator yourself by using:

```
use std::alloc::System;

#[global_allocator]
static A: System = System;
```
