### ISSUE TITLE
rustup component add rust-std-<target> should either work or provide a better message.

### ISSUE THREAD

**Issue by vi** [rust-lang/rustup#1500]
```
$ rustup component list
...
rust-std-x86_64-unknown-freebsd
...

$ rustup component add rust-std-x86_64-unknown-freebsd
error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not contain component 'rust-std-x86_64-unknown-freebsd' for target 'x86_64-unknown-linux-gnu'
```

It is error that one can't copy and paste from `component list` to `component add` (or remove).

Options:

1. Allow installation of targets with `component add`, like with `target add`;
2. Don't list uninstallable/unremovable components with `component list`;
3. Show specific error message, hinting to use `target` subcommand.

**Comment by kinnison** [comment]
I believe this was fixed with #2088
