### ISSUE TITLE
"Unable to run interactively" in MSYS2/MinGW despite being called with "-y"

### ISSUE THREAD

**Issue by LigH-de** [rust-lang/rustup#1503]
The [media-autobuild suite](https://github.com/jb-alvarado/media-autobuild_suite/) tries to install rust into a MSYS2/MinGW cross-compiling environment before compiling ripgrep and rav1e (if enabled), besides ffmpeg and other A/V tools.

This fails despite calling the script with the `-y` parameter:
```
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
bash -c curl https://sh.rustup.rs -sSf | sh -s -- -v -y --no-modify-path --default-host=i686-pc-windows-gnu --default-toolchain=stable
info: downloading installer
rustup: Unable to run interactively. Run with -y to accept defaults, --help for additional options
```

See also: https://github.com/jb-alvarado/media-autobuild_suite/issues/915

**Comment by Selur** [comment]
same happens when only rav1e is marked to be build  [logs.zip](https://0x0.st/swkI.zip)

**Comment by LigH-de** [comment]
Solved in the linked issue by @schmidthubert and @wiiaboo – "subshell in a shell problem plus $CARCH should be $MSYSTEM_CARCH" for the media-autobuild_suite helper script.
