### ISSUE TITLE
rls-preview and clippy-preview can't be installed

### ISSUE THREAD

**Issue by Neurrone** [rust-lang/rustup#1506]
I've seen `rustup update` fail on nightly because `rls-preview` couldn't be downloaded. After uninstalling and updating nightly, I can't install `rls-preview` anymore. Then it works again a few days later, and now I can't install it again.

```
error: component 'clippy-preview' for 'x86_64-pc-windows-msvc' is unavailable for download
error: component 'rls-preview' for 'x86_64-pc-windows-msvc' is unavailable for download
```

I'm not sure if the same thing happens periodically with clippy, since this is the first time I'm trying to install it.

**Comment by mati865** [comment]
Nightly components get broken from time to time. You can see their status [here](https://rust-lang-nursery.github.io/rust-toolstate/) or [here](https://mexus.github.io/rustup-components-history/x86_64-unknown-linux-gnu.html).

**Comment by Neurrone** [comment]
Thanks @mati865.
