### ISSUE TITLE
Difference between static.rust-lang.org/rustup.sh and sh.rustup.rs

### ISSUE THREAD

**Issue by konstin** [rust-lang/rustup#1507]
Currently, there are two rustup scripts used in the wild: https://static.rust-lang.org/rustup.sh and https://sh.rustup.rs. Both install rustup, but have different command line options. It would be great if there was some explanation on what the first script is and why one should use the first or second one.

**Comment by kinnison** [comment]
@rust-lang/release Does this remain the case, or is the `rustup-init.sh` copied over during the release to be present at the top level too?

**Comment by emilyalbini** [comment]
I don't think it's still copied. We can start doing that again without any issue though.

**Comment by emilyalbini** [comment]
The file has been updated. @kinnison will work on adding the update command to our release process.

**Comment by konstin** [comment]
So the resolution is that those two scripts should be identical, currently aren't, but will be in the future? Is there any documentation about this?

**Comment by kinnison** [comment]
@konstin The `/rustup.sh` script *was* the old shell implementation of Rustup, it's *now* the same as `rustup-init.sh` -- with #2124 we've ensured the next release will also keep them in-sync.  We're likely to start using `https://static.rust-lang.org/rustup.sh` as the canonical installation URL at some point in the near future too.  At that point, that URL will be properly documented once more :D.
