### ISSUE TITLE
`rustup-init` fails when it is a relative symlink.

### ISSUE THREAD

**Issue by reitermarkus** [rust-lang/rustup#1512]
When installing `rustup-init` 0.14.0 with Homebrew, it fails because it is a relative symlink.

Environment:

```bash
$ which rustup-init
/usr/local/bin/rustup-init
$ readlink /usr/local/bin/rustup-init
../Cellar/rustup-init/1.14.0/bin/rustup-init
```

```
CARGO_HOME=~/.config/cargo
RUSTUP_HOME=~/.config/rustup
```

Here is what happens:

```bash
$ rm -rf ~/.config/rustup/ ~/.config/cargo/
$ rustup-init -y --no-modify-path
error: failed to set permissions for '~/.config/cargo/bin/rustup'
info: caused by: No such file or directory (os error 2)
```

After this, `rustup` is a symlink pointing to the same target as the original symlink, which is wrong.

```bash
$ readlink ~/.config/cargo/bin/rustup
../Cellar/rustup-init/1.14.0/bin/rustup-init
```

If I run the command again, it now tries to symlink from the wrong symlink again.

```bash
$ rustup-init -y --no-modify-path
error: could not create link from '../Cellar/rustup-init/1.14.0/bin/rustup-init' to '~/.config/cargo/bin/rustup'
info: caused by: File exists (os error 17)
```

This is probably an error in `utils::current_exe()` since it doesn't resolve the path correctly (or at all).

**Comment by hoebat** [comment]
I'm getting the same issue. is there a way to fix it?

**Comment by hoebat** [comment]
I'm getting this:

```
 /usr/local/Cellar/rustup-init/1.14.0/bin/rustup-init -y
error: could not copy file from '/usr/local/Cellar/rustup-init/1.14.0/bin/rustup-init' to '/Users/chris/.cargo/bin/rustup'
info: caused by: No such file or directory (os error 2)
```

**Comment by MikeChongCan** [comment]
```bash
Current installation options:

   default host triple: x86_64-apple-darwin
     default toolchain: stable
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>1

error: failed to set permissions for '/Users/[my_user]/.cargo/bin/rustup'
info: caused by: No such file or directory (os error 2)
```
Same issue. How to fix it?

Version:
```shell
brew uninstall rustup
Uninstalling /usr/local/Cellar/rustup-init/1.14.0... (6 files, 8.0MB)
```

**Comment by jjlorenzo** [comment]
It works for me if I execute the original file `/usr/local/Cellar/rustup-init/1.14.0/bin/rustup-init` instead of the symlink. Hope it helps

**Comment by hoebat** [comment]
@jjlorenzo: It doesn't work for me.

**Comment by jjlorenzo** [comment]
did you remove `~/.cargo` first ?

**Comment by hoebat** [comment]
yeah. when I do that it gives a `file does not exist` error but still creates the link.

**Comment by ghost** [comment]
Can confirm, running rustup-init with the fully qualified path fixed the issue:
`rm -rf ~/.cargo & /usr/local/Cellar/rustup-init/1.14.0/bin/rustup-init`

**Comment by reitermarkus** [comment]
> running rustup-init with the fully qualified path fixed the issue

That doesn't fix the issue, it works around it.

**Comment by JoseAlban** [comment]
I reckon it's creating a symlink based on invalid assumption, eg:
`/Users/my.user/.cargo/bin/rustup@ -> ../Cellar/rustup-init/1.14.0/bin/rustup-init`
Absolute of `../Cellar/rustup-init/1.14.0/bin/rustup-init` should've been `/usr/local/Cellar/rustup-init/1.14.0/bin/rustup-init`, but it's been interpreted as `/Users/my.user/.cargo/Cellar/rustup-init/1.14.0/bin/rustup-init` .

**Comment by reitermarkus** [comment]
It shouldn't even follow the symlink in this case, since the end result should be `$CARGO_HOME/bin/rustup` pointing to `$(brew --prefix)/bin/rustup-init`, not to `$(brew --prefix) /Cellar/rustup-init/1.14.0/bin/rustup-init`.

**Comment by apetresc** [comment]
I'm not sure what has changed between 2018 and now, but I can confirm definitively that the issue has returned. When using `rustup-init` from Homebrew, you end up with a symlink like:

```bash
$ ls -alh ~/.cargo/bin/rustup 
lrwxr-xr-x@ 1 apetresc  staff    29B  7 Aug 19:17 /Users/apetresc/.cargo/bin/rustup -> /opt/homebrew/bin/rustup-init
```

Which, if it belongs to a different user, fails with:

```
 $ rustup-init

Welcome to Rust!

This will download and install the official compiler for the Rust
programming language, and its package manager, Cargo.

Rustup metadata and toolchains will be installed into the Rustup
home directory, located at:

  /Users/apetresc/.rustup

This can be modified with the RUSTUP_HOME environment variable.

The Cargo home directory is located at:

  /Users/apetresc/.cargo

This can be modified with the CARGO_HOME environment variable.

The cargo, rustc, rustup and other commands will be added to
Cargo's bin directory, located at:

  /Users/apetresc/.cargo/bin

This path will then be added to your PATH environment variable by
modifying the profile files located at:

  /Users/apetresc/.profile
  /Users/apetresc/.zshenv

You can uninstall at any time with rustup self uninstall and
these changes will be reverted.

Current installation options:


   default host triple: aarch64-apple-darwin
     default toolchain: stable (default)
               profile: default
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>

error: failed to set permissions for '/Users/apetresc/.cargo/bin/rustup': Operation not permitted (os error 1)
```

The old workaround of invoking rustup-init from the absolute path in `/opt/homebrew/Cellar` continues to work. Just thought I'd let you know about this regression, thanks :)
