### ISSUE TITLE
1.14 isn't published

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rustup#1513]
```cmd
C:\Users\cad97>rustup --version
rustup 1.13.0 (ea9259c1b 2018-07-16)

C:\Users\cad97>rustup self update
info: checking for self-updates

C:\Users\cad97>rustup --version
rustup 1.13.0 (ea9259c1b 2018-07-16)
```

This means I don't have access to the #304 fix (#1472) and my toolchain state is corrupted (but hopefully should be able to remove the dead toolchains with the fix).

**Comment by ghost** [comment]
It looks like the latest on Linux is also 1.13.0. There also isn't a tag for 1.14.0 so I guess it was never published at all.

**Comment by CAD97** [comment]
https://github.com/rust-lang-nursery/rustup.rs/releases/tag/1.14.0

**Comment by alexcrichton** [comment]
Sorry for the confusion here, 1.14.0 isn't published or ready for release yet. Tests are still failing on OSX on CI which we need to sort through.

**Comment by alexcrichton** [comment]
Ok, this is published now.
