### ISSUE TITLE
rustup.rs does not check if linker is installed

### ISSUE THREAD

**Issue by csildev** [rust-lang/rustup#1522]
When a rust program is compiled through cargo it tries to link using cc, however, rustup does not check if cc is installed before installing rust meaning that the user has to figure out why all their compilations are failing with long linker errors.

**Comment by tgross35** [comment]
It would be good to check the versions work too

**Comment by 0xPoe** [comment]
Rustup is the installer for Rust Programing Language. So maybe it is not a good idea to pre-check the linker before installing it. A lot of users don't need to use cc to compile their projects.
