### ISSUE TITLE
Installer error: [7] Couldn't connect to server

### ISSUE THREAD

**Issue by sshplendid** [rust-lang/rustup#1529]
=============================================================
Current installation options:

   default host triple: x86_64-pc-windows-msvc
     default toolchain: stable
  modify PATH variable: yes

info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256' to 'C:\Users\shun.shin\.rustup\tmp\ypo2o6drnv0be_it_file'
info: caused by: error during download
info: caused by: [7] Couldn't connect to server

=============================================================

Hi!
I have an issue with installation rustup.
I've tried to install rustup, but received some error messages.

I've tried via CMD, PowerShell, mingw.

PC Environment
Windows 7
proxy exists,
not trusted certificate. (need to disable SSL verify)

I also tried to register cert as follows, got same error.
https://github.com/rust-lang-nursery/rustup.rs/issues/581

thanks for reading!

**Comment by ghost** [comment]
first I try use the cmd.exe to execute the rustup-init,but fail,somehow I open the poewershell and `cd` to the location and execute it ,and it was work well as follow 
```
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
320.1 KiB / 320.1 KiB (100 %)  55.2 KiB/s ETA:   0 s
info: latest update on 2018-10-25, rust version 1.30.0 (da5f414c2 2018-10-24)
info: downloading component 'rustc'
 53.4 MiB /  53.4 MiB (100 %) 624.7 KiB/s ETA:   0 s
info: downloading component 'rust-std'
 46.7 MiB /  46.7 MiB (100 %) 178.2 KiB/s ETA:   0 s
info: downloading component 'cargo'
  1.1 MiB /   2.7 MiB ( 41 %) 277.1 KiB/s ETA:   6 s
```
thanks  for advice !

**Comment by sshplendid** [comment]
The situation has been occured in the office, which has proxy and self-trusted certificate.
I think that certificate is a problem.
I need to know the way avoiding **ssl-verify** in **rustup installer**.
like avoiding ssl-verify in git as follows
```git
git config http.sslVerify false
```

**Comment by sshplendid** [comment]
The problem solved. I installed rustup with `RUSTUP_USE_REQWEST` variable.

```bash
# mingw bash
RUSTUP_USE_REQWEST=1 && rustup.sh
```
