### ISSUE TITLE
Confusing install error message when nightly/beta releases are missing

### ISSUE THREAD

**Issue by jfirebaugh** [rust-lang/rustup#1539]
I wanted to install the beta channel in order to test Rust 2018, but I ran into https://github.com/rust-lang/rust/issues/55817. It was difficult to figure out what was happening; I was quite confused by the rustup output:

```
$ rustup install beta
info: syncing channel updates for 'beta-x86_64-apple-darwin'
info: latest update on 2018-11-09, rust version 1.31.0-beta.5 (bf00632e3 2018-11-08)

  beta-x86_64-apple-darwin unchanged - (toolchain not installed)
```

I thought I must be using the wrong rustup commands, and spent a lot of time trying different things before concluding that it was _not_ user error.

Could rustup have better error diagnostics for this case? It's come up a few times now: https://github.com/rust-lang/rust/issues/55817, https://github.com/rust-lang/rust/issues/46391, https://github.com/rust-lang/rust/issues/46396.

**Comment by kinnison** [comment]
I believe that this won't happen on beta any more thanks to process changes; but I wonder if there's a way we can reproduce this now.  Does anyone know if we have the beta manifests from the past?

**Comment by kinnison** [comment]
There has been no movement on this, nor any reproduction of it. I'm going to close the issue.  If something like this comes up in the future, we can open a fresh issue to discuss.
