### ISSUE TITLE
Allow using using windows-gnu target without rust-mingw component

### ISSUE THREAD

**Issue by mati865** [rust-lang/rustup#1543]
It would fix https://github.com/rust-lang/rust/issues/47048

TL;DR
`rust-mingw` contains set of libraries compiled with specific versions of GCC and mingw-w64 and have higher priority then system libraries. This causes mismatch between headers and libraries when host toolchain is different than one used by Rust.

Removing it isn't possible now:
```
rustup : error: component 'rust-mingw' for target 'x86_64-pc-windows-gnu' is required for toolchain 'stable-x86_64-pc-windows-gnu' and cannot be removed
```

To fix this issue 2 things are necessary:
- [x] ability to remove `rust-mingw` component
- [ ] option to install windows-gnu without `rust-mingw` component

**Comment by crlf0710** [comment]
This alone won't be enough. We'll need to point the linker to use the correct `crt2.o` and `dllcrt2.o` file too...

**Comment by crlf0710** [comment]
https://github.com/rust-lang/rust/issues/53454

**Comment by mati865** [comment]
Linker should inherit host cc library paths but it's not related to rustup
repo.

niedz., 9 gru 2018, 08:31: CrLF0710 <notifications@github.com> napisał(a):
