### ISSUE TITLE
Gracefully handle renamed components when updating toolchains

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rustup#1546]
In some local testing when we rename a component (for example from `rls-preview` to `rls`) then if the component is previously installed whenever you update it'll uninstall `rls-preview` but fail to install `rls` shortly afterwards.

This is likely a local regression in rustup from some time ago, but it's unsure where just yet!

Once this is fixed and propagated enough in rustup then we can switch the actual names in the released manifests from `rls-preview` to `rls` and such.

**Comment by alexcrichton** [comment]
cc @nrc

**Comment by kinnison** [comment]
Does this need to remain open or was it resolved by #1549 ?  If it's not resolved then what remains to-do?

**Comment by kinnison** [comment]
I'm assuming this is all done.
