### ISSUE TITLE
rustup v1.15 does not show up on Windows

### ISSUE THREAD

**Issue by nayato** [rust-lang/rustup#1560]
As a result using `rustup component add clippy` and rustfmt as outlined in Rust 1.31 release don't work and "-preview" components have to be used.

**Comment by nrc** [comment]
cc https://github.com/rust-lang/rustup.rs/pull/1561 (will also need distributing)

**Comment by ashthespy** [comment]
Head up, still having the issue with `rustup v1.16.0`
```
C:\Users\Ash> rustup self update
info: checking for self-updates
info: downloading self-update
info: rustup updated successfully to 1.16.0
C:\Users\Ash> rustup component add clippy
error: toolchain 'stable-x86_64-pc-windows-msvc' does not contain component 'clippy' for target 'x86_64-pc-windows-msvc'
```

Edit: Never mind, I guess this fix will land only in `v1.17.0`
Cross ref: https://github.com/rust-lang/rust-clippy/issues/3503

**Comment by CryZe** [comment]
Yeah, it's still missing for me too.

**Comment by alexcrichton** [comment]
This is fixed now, so let's continue discussion of clippy on https://github.com/rust-lang/rust-clippy/issues/3503
