### ISSUE TITLE
Component renames are not working on Travis

### ISSUE THREAD

**Issue by nrc** [rust-lang/rustup#1567]
This is probably something to do with the order of self update, update, etc.,. but I can't figure out exactly what.

e.g., https://travis-ci.org/rust-lang/www.rust-lang.org/builds/466170909?utm_source=github_status&utm_medium=notification

**Comment by kinnison** [comment]
Does this still hold after the merge of #1601 ?

**Comment by kinnison** [comment]
I believe this was a component rename related issue so I'm going to close it now.

**Comment by kinnison** [comment]
(specifically that nightly had done the rename wrongly)
