### ISSUE TITLE
1.14.0 and 1.15.0 won't run on Ubuntu 16.04 LTS powerpc 32-bit

### ISSUE THREAD

**Issue by pusateri** [rust-lang/rustup#1571]
Releases 1.14.0 and 1.15.0 require glibc 2.25. Ubuntu 16.04 LTS powerpc (the last powerpc release available) only has glibc 2.23. rustup 1.13.0 runs fine.

**Comment by nagisa** [comment]
Same is true for the PowerPC64 and fedora releases from just a year ago.

**Comment by mati865** [comment]
https://github.com/rust-lang/rustup.rs/pull/1536 bumped minimal GLIBC to [2.27](https://packages.ubuntu.com/bionic-updates/libc6-dev-powerpc-cross)

**Comment by kinnison** [comment]
Hi, we recently switched to using the `rust-lang/rust` dockers as generated by the compiler build system.  Could you check with the latest `rustup` and close the issue if it's resolved?

Thanks,

D.

**Comment by pusateri** [comment]
I just tested Gentoo Linux and the latest version of rustup installed ok and works great.
This is rustup 1.18.3 using glibc 2.27 on Gentoo 2.6 with architecture powerpc64-unknown-linux-gnu.
I will see if I can check Ubuntu 16.04 LTS.

**Comment by kinnison** [comment]
Thanks, if Ubuntu works then I'll close the issue.

**Comment by pusateri** [comment]
You can close it now. I'm away for a few weeks and when I return, if I'm still having trouble, I can re-open it.

**Comment by kinnison** [comment]
Okay, thank you @pusateri
