### ISSUE TITLE
If current directory is not available rustup will panic

### ISSUE THREAD

**Issue by TheRadioGuy** [rust-lang/rustup#1573]
**Steps to reproduce**

1. Mount Flash Drive

2. `cd /mount_flashdrive_directory` 

3. Unmount flash drive

4. `rustup doc`

```
[duckerman@duckerman 304B6FD6303A17A5]$ rustup doc
error: could not locate working directory
info: caused by: Input/output error (os error 5)
```

**Comment by eminence** [comment]
Instead of mounting file systems, a slightly easier way to reproduce this is to simply remove your current working directory:

    achin@bigbox ~/tmp/01 $ rmdir `pwd`
    achin@bigbox ~/tmp/01 $ ls
    achin@bigbox ~/tmp/01 $ rustup doc
    error: could not locate working directory
    info: caused by: No such file or directory (os error 2)

**Comment by kinnison** [comment]
Importantly this is (a) not a panic and (b) quite a clear error message.

What are you hoping that rustup would do @DuckerMan ?

**Comment by TheRadioGuy** [comment]
I think rustup should open docs because it doesn't open it now.
Rustup docs doesn't depend on working directory.

**Comment by kinnison** [comment]
Because the CWD is unavailable, `rustup` is unable to determine if a toolchain override exists.  Since the documentation is toolchain specific, this *is* a situation in which `rustup` cannot really do anything objectively correct other than to error out.  What would you expect it to do?

**Comment by eminence** [comment]
Unfortunately the behavior here as regressed slightly.

Previously, rustup gave an error that said `could not locate working directory`, which is pretty clear.  But now that part of the message is gone:

```
achin@bigbox:~/tmp/16$ ls `pwd`
ls: cannot access '/home/achin/tmp/16': No such file or directory

achin@bigbox:~/tmp/16$ rustup doc
error: No such file or directory (os error 2)
```

**Comment by kinnison** [comment]
You're right, interesting.  I shall see what happened there.  Thanks.

**Comment by kinnison** [comment]
We regressed when we added cleanup support.  I've inserted an explicit check and improved the error message slightly:

```console
$ rustup doc
error: Unable to proceed. Could not locate working directory.
error: caused by: No such file or directory (os error 2)
```

**Comment by eminence** [comment]
LGTM
