### ISSUE TITLE
Windows MVSC link in README.md does not work

### ISSUE THREAD

**Issue by TheRadioGuy** [rust-lang/rustup#1577]
This [link](https://www.rust-lang.org/downloads.html#win-foot) (279 line in README.md) does not work

**Comment by rbtcollins** [comment]
I think https://github.com/rust-lang/rustup.rs/commit/0a08a66f2cc69ce9ab04ef6d334ace20a7bed1d8 fixed this.

**Comment by kinnison** [comment]
I believe you're right, I'm closing this.  If @DuckerMan thinks the new link is still bad, a fresh issue would be appropriate.
