### ISSUE TITLE
"rustup update" only updates host toolchains

### ISSUE THREAD

**Issue by richard-w** [rust-lang/rustup#1581]
Not a duplicate of #989.

### Situation

I have installed rust nightly and stable for 3 different targets:
* i686-unknown-linux-gnu (installed)
* x86_64-unknown-linux-gnu (default)
* x86_64-unknown-linux-musl (installed)

So I have 6 toolchains in total. I need to update them all sometimes. I'd like to use "rustup update" to do that.

### Expected behaviour

All 6 installed toolchains are updated when "rustup update" is issued. This expectation is consistent with the output of "rustup update --help":

> With no toolchain specified, the `update` command updates each of
> the installed toolchains from the official release channels, then
> updates rustup itself.

### Actual behaviour

Only the nightly and stable for the default target are updated. I have to update the other 4 manually.

**Comment by kinnison** [comment]
Hi Richard,

I've been trying to reproduce this issue and I don't seem to be able to.  Could you please confirm for me the version of rustup you have installed and the result of running `rustup update` assuming there are no updates to be downloaded.  For example, I currently have on my x86_64 Debian install:

```
somniloquy(git)(🦀🏠)% rustup update                                             
info: syncing channel updates for 'stable-i686-unknown-linux-gnu'
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: checking for self-updates

    stable-i686-unknown-linux-gnu unchanged - rustc 1.32.0 (9fda7c223 2019-01-16)
  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.32.0 (9fda7c223 2019-01-16)

somniloquy(git)(🦀🏠)% rustup --version                                          
rustup 1.16.0 (beab5ac2b 2018-12-06)
somniloquy(git)(🦀🏠)%
```

**Comment by richard-w** [comment]
Last rustup update worked as expected. I forgot to write down the version when I ran into these issues - sorry.
