### ISSUE TITLE
MIPS rustup depends on a too-new glibc

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rustup#1584]
```
root@debian:~# curl https://sh.rustup.rs -sSf | sh
info: downloading installer
/tmp/tmp.0SjgknXIdh/rustup-init: /lib/mips-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/tmp.0SjgknXIdh/rustup-init)
```

on my ~2 year old jessie-based MIPS VM.

**Comment by mati865** [comment]
https://github.com/rust-lang/rustup.rs/pull/1536 bumped minimal GLIBC to [2.27](https://packages.ubuntu.com/bionic-updates/libc6-dev-mips-cross)

**Comment by kinnison** [comment]
Is this still an issue?  I think we tweaked our builders a bit more since last year.
