### ISSUE TITLE
rust-std for thumbv7neon targets unavailable for download

### ISSUE THREAD

**Issue by hsivonen** [rust-lang/rustup#1586]
# Steps to reproduce

```sh
rustup default nightly
rustup update
rustup target add thumbv7neon-unknown-linux-gnueabihf
```

Then:
```sh
rustc --print target-list | grep thumbv7neon-unknown-linux-gnueabihf
```

# Actual results

First:

`error: component 'rust-std' for target 'thumbv7neon-unknown-linux-gnueabihf' is unavailable for download`

Then:
`thumbv7neon-unknown-linux-gnueabihf`

# Expected results

Expected the `rust-std` component for the `thumbv7neon-unknown-linux-gnueabihf` and `thumbv7neon-linux-androideabi` [targets](https://github.com/rust-lang/rust/pull/56947) to be available.

**Comment by alexcrichton** [comment]
It looks like the [PR adding support](https://github.com/rust-lang/rust/pull/56947/files) added `thumbv7neon-linux-androideabi` as a distribution target (actually added it to be built in a container), and `rustup target add thumbv7neon-linux-androideabi --toolchain nightly` works for me. The same PR didn't, however, configure any containers to build `thumbv7neon-unknown-linux-gnueabihf`, so nothing is building that target to be distributed (explaining the lack of a target in rustup)

**Comment by hsivonen** [comment]
> `rustup target add thumbv7neon-linux-androideabi --toolchain nightly` works for me

Works for me, too. No idea why I thought otherwise earlier today.

**Comment by hsivonen** [comment]
I filed an [issue on the `rust` repo](https://github.com/rust-lang/rust/issues/57030) about the container configuration.

**Comment by kinnison** [comment]
I think this is not a bug in rustup so I'm going to close it.  If I've misunderstood the situation please let me know.
