### ISSUE TITLE
Nightly (1.33.0-nightly) fails on OS X 10.14.1

### ISSUE THREAD

**Issue by d4ncer** [rust-lang/rustup#1590]
I've been trying to install the nightly to set up [Racer](https://github.com/racer-rust/racer), and I keep getting an error when trying to install `rust-std`: 

```
rustup update nightly
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: latest update on 2018-12-25, rust version 1.33.0-nightly (f960f377f 2018-12-24)
info: downloading component 'rustc'
 78.4 MiB /  78.4 MiB (100 %)   1.8 MiB/s ETA:   0 s
info: downloading component 'rust-std'
 63.5 MiB /  63.5 MiB (100 %)   2.0 MiB/s ETA:   0 s
info: downloading component 'cargo'
  3.4 MiB /   3.4 MiB (100 %)   1.4 MiB/s ETA:   0 s
info: downloading component 'rust-docs'
  8.6 MiB /   8.6 MiB (100 %)   2.1 MiB/s ETA:   0 s
info: installing component 'rustc'
info: installing component 'rust-std'
info: rolling back changes

error: failed to install component: 'rust-std-x86_64-apple-darwin', detected conflict: '"lib/rustlib/x86_64-apple-darwin/lib/libLLVM.dylib"'
```

**Things I've tried:**
- I assumed that it was due to some old install that was not blown away correctly so I tried searching for this conflicting file to no avail. 
- I've blown away `~/.rustup` & `~/.cargo` numerous times, and re-installed.

Not sure if I've even diagnosed the issue correctly, and I can't seem to run the `install` / `update` commands with any increased level of verbosity to drill deeper. 

Any help would be most appreciated.

**Comment by RobbieMcKinstry** [comment]
+1, exactly the same use case

**Comment by lambda-fairy** [comment]
I can reproduce this on Arch Linux x64.

```
 ~ ) rustup install nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2018-12-25, rust version 1.33.0-nightly (f960f377f 2018-12-24)
info: downloading component 'rustc'
 82.5 MiB /  82.5 MiB (100 %)   5.9 MiB/s ETA:   0 s                
info: downloading component 'rust-std'
 71.5 MiB /  71.5 MiB (100 %)   6.0 MiB/s ETA:   0 s                
info: downloading component 'cargo'
info: downloading component 'rust-docs'
  8.5 MiB /   8.5 MiB (100 %)   6.1 MiB/s ETA:   0 s                
info: installing component 'rustc'
info: installing component 'rust-std'
info: rolling back changes
error: failed to install component: 'rust-std-x86_64-unknown-linux-gnu', detected conflict: '"lib/rustlib/x86_64-unknown-linux-gnu/lib/libLLVM-8svn.so"'
```

(By the way, Merry Christmas to anyone reading this thread!)

**Comment by caelunshun** [comment]
I'm having this problem as well on Ubuntu 18.04.

**Comment by flaviut** [comment]
As a workaround, `rustup toolchain add nightly-2018-12-23` works just fine.

**Comment by d4ncer** [comment]
Good to know, thanks @flaviut!

**Comment by Arnavion** [comment]
https://github.com/rust-lang/rust/issues/57111

**Comment by jbg** [comment]
probably the same underlying issue as https://github.com/rust-lang/rustup.rs/issues/1592?

**Comment by MasterDeflate** [comment]
> As a workaround, `rustup toolchain add nightly-2018-12-23` works just fine.

I still have the same issue with installing.
1) I did rustup toolchain add nightly-2018-12-23
2) After i run rustup toolchain install nightly-x86_64-unknown-linux-gnu

```
# rustup toolchain install nightly-x86_64-unknown-linux-gnu
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2018-12-25, rust version 1.33.0-nightly (f960f377f 2018-12-24)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: rolling back changes
error: failed to install component: 'rust-std-x86_64-unknown-linux-gnu', detected conflict: '"lib/rustlib/x86_64-unknown-linux-gnu/lib/libLLVM-8svn.so"'
```

**Comment by MasterDeflate** [comment]
Nothing work for me :(

**Comment by MasterDeflate** [comment]
I tried and this:
1) Removed rustup
2) Installed Custome - > nightly-2018-12-23
3) After it finish i tried to install this and i recive same :(

rustup target add x86_64-unknown-linux-musl
rustup toolchain install nightly-x86_64-unknown-linux-gnu

`
error: failed to install component: 'rust-std-x86_64-unknown-linux-gnu', detected conflict: '"lib/rustlib/x86_64-unknown-linux-gnu/lib/libLLVM-8svn.so"'
``

**Comment by jbg** [comment]
surely `rustup toolchain install nightly-x86_64-unknown-linux-gnu` is just installing the latest nightly again, whereas to avoid the bug you should be installing 2018-12-23

**Comment by lambda-fairy** [comment]
rust-lang/rust#57111 has been fixed and released in the latest nightly. Can we close this?

**Comment by d4ncer** [comment]
Yup, happy to close 👍 Thanks all!
