### ISSUE TITLE
Misleading error message when a component is not found

### ISSUE THREAD

**Issue by Yatekii** [rust-lang/rustup#1596]
When one tries to install a component on a a toolchain which does not have that component, you get a message like this:

```
error: component 'rls' for target 'x86_64-unknown-linux-gnu' is unavailable for download
```

This message implies that the component does not exist for your architecture. But it in fact means it's not available for the currently selected toolchain, which is not mentioned in the error message.
For example in my case I had the toolchain of my PWD overridden to nightly and this `rls` was not found. The error message suggested that `rls` is not available for my architecture. But in fact it was available; just for stable.

This can be very missleading as for example in my case I knew that the component existed for my architecture and I though that something completely different went wrong. Maybe my net or the likes.

In my opinion it is absolutely never enough to imply something in error messages (as in this case it is implied that the current toolchain is meant) because unfamiliar users, which get confronted with error messages like this the most, are not aware of the implications.

There is an easy fix to this: Add the complete name of the toolchain to this error message and all is good.

**Comment by fbruetting** [comment]
I also have the same issue, and adding the complete name of the toolchain doesn’t fix this. Any suggestions?

```
rustup update nightly-x86_64-unknown-linux-gnu
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2019-02-16, rust version 1.34.0-nightly (a9410cd1a 2019-02-15)
error: component 'rls' for target 'x86_64-unknown-linux-gnu' is unavailable for download
```

// OK, uninstalling and reinstalling nightly helped.
