### ISSUE TITLE
Describe component management in readme

### ISSUE THREAD

**Issue by bergus** [rust-lang/rustup#1598]
Hi,
the [readme](https://github.com/rust-lang/rustup.rs/blob/master/README.md) is a wonderful and easily understandable resource. However I cannot find any information in it about
* what components are
* how they relate to toolchains (and whether they are switched together)
* when components are downloaded and when they are installed
* what components are "included" by default
* how to add/remove/list/update/... components
* what happens when a component is not available (e.g. when they [failed to build in the nightly](https://mexus.github.io/rustup-components-history/) that you happen to use)

Also I wish the readme would include documentation on the CLI. Surely the `rustup -h` is not all there is?

**Comment by bergus** [comment]
PS: By chance I just came across `rustup component -h`. It wasn't obvious that each of the subcommands had a separate help to it :-/

**Comment by kinnison** [comment]
There is a lot more documentation these days, I'd like to think things are good enough, though not everything you listed is explicitly there in the docs, more is than was.

If this kind of documentation is still lacking in your opinion, please could you open a fresh issue detailing what you suggest is missing and which parts of the new book-form documentation the content should go in?

Thanks,

D.
