### ISSUE TITLE
Suggestion: Add a feature to specify additional components to install when installing a toolchain

### ISSUE THREAD

**Issue by JameeKim** [rust-lang/rustup#1602]
I hope I'm not suggesting a feature that is either already present or duplicate of another open issue.

## Background
Recently I was having a problem with updating the nightly toolchain bc of the absence of `rls` and `clippy` components in the newer versions. So today I decided to look for the most recent version of nightly that have all the components I need, and use that version until the newest version has the components. But it bothered me that I had to repeat the process of installing a version with `rustup toolchain install <toolchain>`, waiting for the download and installation to finish, checking if the toolchain has the components by `rustup component list --toolchain <toolchain>`, then uninstalling the toolchain with `rustup toolchain remove <toolchain>` if it does not have the things I want. Then it came to my mind that this can be improved with an addition of a feature to `rustup`.

## Suggestion
Add a feature to specify additional components to install alongside the default ones when using `rustup toolchain install <toolchain>`. A more specific idea that came to my mind was to add a flag (somthing like `--components comp1 comp2 comp3`) to the command. If at least one of the specified components is absent in the toolchain, the installation should be aborted, just like when updating an installed toolchain.

## Benefits
I think this feature will reduce the process of "type command to install a toolchain -> wait for it to finish -> type command to install additional components -> wait for it to finish" to "type command to install a toolchain and the components needed -> wait for it to finish".

## Extra
If this feature is already present, then it should be mentioned in the output of `rustup toolchain help install`.

**Comment by RalfJung** [comment]
This is subsumed by https://github.com/rust-lang/rustup.rs/issues/1501.

**Comment by kinnison** [comment]
I believe this is covered by Rustup 1.20, if the functionality in `rustup toolchain install` is insufficient for this, please open a fresh issue.
