### ISSUE TITLE
Cannot install nightly-x86_64-pc-windows-msvc'

### ISSUE THREAD

**Issue by anta40** [rust-lang/rustup#1608]
Just installed Rust on my 64-bit Windows 10 laptop.
> $ rustup show
> Default host: x86_64-pc-windows-msvc
> 
> stable-x86_64-pc-windows-msvc (default)
> rustc 1.31.1 (b6c32da9b 2018-12-18)

My rustup version is
> $ rustup version
> rustup 1.16.0 (beab5ac2b 2018-12-06)

Now I want to switch the toolchain to msvc 64 nightly.
> $ rustup default nightly
> info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
> 299.6 KiB / 299.6 KiB (100 %) 240.0 KiB/s ETA:   0 s
> info: latest update on 2019-01-10, rust version 1.33.0-nightly (6ecad3383 2019-01-09)
> info: downloading component 'rustc'
> error: failed to parse url: nightly/2019-01-10/rustc-nightly-x86_64-pc-windows-msvc.tar.xz
> info: caused by: relative URL without a base

It fails, unfortunately.

**Comment by ehuss** [comment]
Thanks for the report! This should be fixed by https://github.com/rust-lang/rust/pull/57484.

**Comment by emilyalbini** [comment]
Sorry for the trouble caused by this! Let's track the issue on rust-lang/rust#57488.
