### ISSUE TITLE
rustc accesses ../lib../lib../lib unnecessarily on Strace output

### ISSUE THREAD

**Issue by autolyticus** [rust-lang/rustup#1612]
#### rustup version
```
> rustup --version
rustup 1.16.0
```
#### rustc version
```
> rustc --version --verbose
rustc 1.33.0-nightly (b43986184 2019-01-11)
binary: rustc
commit-hash: b43986184b8f4e0d633e8ae1704f0e19aec30cb2
commit-date: 2019-01-11
host: x86_64-unknown-linux-gnu
release: 1.33.0-nightly
LLVM version: 8.0
```
OS: Arch Linux x86_64. All packages up to date.

I've installed the official Arch Linux community rustup package. I wanted to look at what files the rustc binary from `/usr/bin/rustc` which is a symlink to `/usr/bin/rustup`.
```
strace -e openat rustc --help
```
Here is the (trimmed) output
```
openat(AT_FDCWD, "/usr/lib/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/../lib/tls/haswell/x86_64/librustc_platform_intrinsics-9f7a2f2927662cff.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/../lib/tls/haswell/librustc_platform_intrinsics-9f7a2f2927662cff.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/../lib/tls/x86_64/librustc_platform_intrinsics-9f7a2f2927662cff.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/../lib/tls/librustc_platform_intrinsics-9f7a2f2927662cff.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/../lib/haswell/x86_64/librustc_platform_intrinsics-9f7a2f2927662cff.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/../lib/haswell/librustc_platform_intrinsics-9f7a2f2927662cff.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/../lib/x86_64/librustc_platform_intrinsics-9f7a2f2927662cff.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/../lib/librustc_platform_intrinsics-9f7a2f2927662cff.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/../lib/libfmt_macros-c8133dd0ac64d3b1.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/../lib/librustc_fs_util-bb59114dc34912a5.so", O_RDONLY|O_CLOEXEC) = 3
```
As you can see, for these files there are unnecessary directory traversals which do incur a runtime cost  and is just plain inefficient.

This isn't high priority by any means but it is something that seems to have some impact on performance based on quick benchmarks.

**Comment by kinnison** [comment]
This is a side-effect of the rust compiler being compiled with an RPATH of `$ORIGIN/../lib` and the relevant shared objects similarly.  This is not an issue with rustup per-se and certainly not our place to "correct" it.

Given this is related to the compiler, surely any performance issue with this will be tiny noise compared with how long it takes to actually compile something?

**Comment by autolyticus** [comment]
@kinnison Thank you for the insight on what is actually causing this issue.

I do agree that this is of perhaps trivial significance. But this is a small inefficiency that is executed every single time the `rustc` command is invoked which does add up quite quickly at the scale that rust is used.

It occurs to me that any inefficiencies, no matter how trivial, should be fixed within program memory itself instead of burdening the filesystem unnecessarily. 

Of course, I might be thinking too much about optimising things that do not need to be optimised as they aren't being bottlenecks, so please feel free to close this issue.

Cheers!

**Comment by kinnison** [comment]
As you say, this is of trivial significance.  The total amount of CPU cycles spent dealing with the extra `../lib` handling is almost certainly on the order of milliseconds a day for a system which spends its entire time invoking rustc to do useful work.  Unfortunately I can't close this issue directly myself, so I'd appreciate it if you would do so.  From a hygiene point of view, it likely makes sense to file an issue against the rust repository itself to suggest reconsidering the RPATH in the shared objects, which would reduce the redirection substantially.

**Comment by autolyticus** [comment]
@kinnison Thank you. I am closing this issue.
