### ISSUE TITLE
Improve error message for no space left to upgrade

### ISSUE THREAD

**Issue by estebank** [rust-lang/rustup#1617]
Moved from https://github.com/rust-lang/rust/issues/57759

> I got this: error: `failed to extract package`. Verbose gave no additional info.

CC @mitchtbaum

**Comment by Nodraak** [comment]
Might be related to #330

**Comment by pickfire** [comment]
I believe this is solved? At least the message now shows possibly insufficient space.

**Comment by kinnison** [comment]
Yeah, agreed, thanks @pickfire
