### ISSUE TITLE
Query RUSTUP_HOME

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rustup#1627]
Is there a way to query the rustup home from rustup ? Right now I am checking if the RUSTUP_HOME variable is defined, and using that if its the case, and otherwise using `${HOME}/.rustup`, but I'd prefer if there was a `rustup --home` command that would just print whatever `rustup` is using.

**Comment by kinnison** [comment]
Not an entirely implausible thing to want, I'll ponder what the nicest way to have that incorporated would be.  Thanks for the suggestion.

**Comment by fisherdarling** [comment]
@kinnison I'd like to try and tackle this! 

I'm thinking I'll need to add an `.arg` in the [cli()](https://github.com/rust-lang/rustup.rs/blob/master/src/cli/rustup_mode.rs#L106) function. Then if that arg is present, print what we think the path is and return early from `rustup_mode::main()`?

**Comment by kinnison** [comment]
I think I'd probably prefer a patch which added the RUSTUP_HOME to the output of `rustup show` and added `rustup show home` akin to `rustup show active-toolchain`.

Do you think you could do that instead?

**Comment by fisherdarling** [comment]
So something like:
```
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home: /home/fisher/.rustup

...
```
And
```
$ rustup show home
/home/fisher/.rustup
```
?

I can try that!

**Comment by kinnison** [comment]
@fisherdarling Yep that kind of thing indeed.
