### ISSUE TITLE
Feature request: "rustup update nightly" to the last version which has all necessary components.

### ISSUE THREAD

**Issue by vi** [rust-lang/rustup#1628]
Instead of failing or forcing, just use not-so-up-to-date version.

Additinoal feature request: `rustup update nightly --date=2019-01-29` to update nightly to a specific version while keeping it as "nigthly", not as a separate toolchain. Should also allow downgrades.

**Comment by kinnison** [comment]
I like this idea and will give it further thought.  It's a little awkward to walk the dates right now, but the latter half of your request is plausible at least.

**Comment by Nemo157** [comment]
The latter half is very similar to my suggestion for [updatable toolchain aliases](https://github.com/rust-lang/rustup.rs/issues/1556), just being able to override the `nightly` toolchain with an alias pointing at a dated nightly.

**Comment by joshlf** [comment]
+1 this would be amazing. It would make a huge difference to my daily workflow.

**Comment by RalfJung** [comment]
(Please stick to one feature request per issue.)

The first request sounds related to https://github.com/rust-lang/rustup.rs/issues/1501.

**Comment by jonhoo** [comment]
I just submitted https://github.com/rust-lang/rustup.rs/pull/1997, which adds this feature.
