### ISSUE TITLE
`rustup default` with no arguments should print the current default

### ISSUE THREAD

**Issue by nrc** [rust-lang/rustup#1632]

**Comment by dwijnand** [comment]
Is that in addition to updating nightly and stable, or in alternative?

**Comment by dwijnand** [comment]
(Cheeky note: had you merged #1625 and used the template I wouldn't've needed to ask, probably =D)

**Comment by das-sein** [comment]
I figured the default behavior is desirable, so in my pull request I let it be.

**Comment by nrc** [comment]
I'm an idiot, I meant `rustup default`, not `rustup update`, sorry for the confusion.

**Comment by dwijnand** [comment]
Fixed by https://github.com/rust-lang/rustup.rs/pull/1633

**Comment by tesuji** [comment]
Close it?
