### ISSUE TITLE
I tried installing rust using rustup but after install rustc isn't working.

### ISSUE THREAD

**Issue by asamolion** [rust-lang/rustup#1669]
**timeout reading rustc version**
I've installed the rust toolchain using 

`curl https://sh.rustup.rs -sSf | sh`

However after installation I get this message

`timeout reading rustc version` 

and the rustc compiler doesn't work at all. It simple halts in a blank screen while doing nothing.

![image](https://user-images.githubusercontent.com/14261053/53234677-e7f1b700-36b1-11e9-9076-03a53a1e1c14.png)

**Steps**
1. Install the toolchain using rustup.
2. simply type `rustc --version`
3. Nothing happens. No version is printed

**Notes**
OS: Linux Mint 19.1

Output of `rustup --version`: Not showing
Output of `rustup show`:
```
Default host: x86_64-unknown-linux-gnu

stable-x86_64-unknown-linux-gnu (default)
(timeout reading rustc version)
```

**Comment by ehuss** [comment]
Do you have an anti-virus installed (such as ESET)? I have seen similar things happen.

It might be helpful to post a stack trace of rustc when it is hung (attach to the process with gdb).

You may get more help posting on https://github.com/rust-lang/rust/issues since I don't think this is an installation issue.

**Comment by asamolion** [comment]
@ehuss 
As a matter of fact, I do have ESET installed. However, it is not running while I am trying to run this.

**Comment by ehuss** [comment]
Ah, in that case it is probably rust-lang/rust#56736.  I suspect it's still finding the `libesets_pac.so` shared library even if it is not "on".  There's some more information in that issue about what's going on.

**Comment by asamolion** [comment]
Okay, so here is how I solved the problem.

I opened the file `/etc/ld.so.preload` and deleted the line containing `libesetspac.so`. So now the `/etc/ld.so.preload` file is empty but my Rust programs are compiling correctly.

Thanks @ehuss.
