### ISSUE TITLE
Check for component included without installing toolchain?

### ISSUE THREAD

**Issue by brackleian** [rust-lang/rustup#1676]
I guess this is a feature request rather than a bug; it may already be doable but I can't find out how.

Is it possible to check for a given component being included in a given toolchain, without actually downloading the whole toolchain? E.g. I'm using 'rls', which is in some nightly builds but not all. To get the latest, I have to work backwards from today's date. Installing the whole toolchain takes significant time, after which I have to uninstall it if it wasn't the right one.

Perhaps a textual list of included components could be stored on the toolchain host alongside each build; I don't mind having to query it with wget.

**Comment by ehuss** [comment]
I'm not sure if this will help for your case, but you can check https://rust-lang-nursery.github.io/rust-toolstate/ or https://mexus.github.io/rustup-components-history/ to find when the last working build was.

**Comment by norru** [comment]
Hello, 

I think it would be useful to have a look at the discussion at https://github.com/rust-lang/rls/issues/1221. There have been reports of users finding the current `rustup` behaviour not friendly in this use case, with a couple of suggestions of how this could be easily solved.

Here's an excerpt from that conversation, hope it helps:

> 
> 
>     we do expect RLS to be sometimes unavailable on the nightly channel
> 
> This user experience is not good. IMHO it would be better if either rustup only downloaded nightlies with all components I have installed or if rustup told me I'm "up-to-date". But failing is really quite bad.
> @alexheretic
> Member
> alexheretic commented on Jan 8 •
> 
>     This user experience is not good. IMHO it would be better if either rustup only downloaded nightlies with all components I have installed or if rustup told me I'm "up-to-date". But failing is really quite bad.
> 
> When the latest nightly is missing components you have installed, rustup will fail the update and tell you this, is that what you're talking about? This protects rustup users from RLS, etc disappearing and it's quite useful.
> 
> If that's working for you, do you just disagree with the message and exit code? If you have bugs/ideas for rustup I'd suggest raising an issue or looking over the discussion in rust-lang/rustup.rs.




>     rustup does the former and if it were to do the second it would be lying (it would be telling you you're up to date when you aren't).
> 
> Currently rustup does nothing as far as I understood. Does it actually download the latest possible version? In that case I was simply confused by the error message.
> 
>     rustup update --with-existing-components would have to figure out which components I have installed in nightly, figure out which ones are available in the latest N nightlies, detect, say nightly-2019-01-01 matches the criteria, then "transparently" sync the nightly "head" to that version.
> 
> This sounds like the least surprising behavior for rustup update. This is what cargo update would do with my project for example. Find the latest possible working configuration and update to that.

**Comment by norru** [comment]
+@NickeZ @alexheretic @Xanewok @petar-dambovaliev

**Comment by kinnison** [comment]
This is a feature request, certainly.  I *think* that @nrc's profiles stuff (https://github.com/rust-lang/rustup.rs/pull/1673) might be a step toward a good mechanism for this.

**Comment by RalfJung** [comment]
This is subsumed by https://github.com/rust-lang/rustup.rs/issues/1501.

**Comment by jonhoo** [comment]
The underlying issue you're experiencing should be fixed by https://github.com/rust-lang/rustup.rs/pull/1997 :)
