### ISSUE TITLE
Expose clippy-driver as an executable

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rustup#1678]
We're working on moving cargo-clippy into cargo (https://github.com/rust-lang/rust-clippy/issues/3837). As a part of this, `clippy-driver` will need to be exposed by rustup.

Can clippy-driver be exposed into the bin folder as a shim? It's fine if it has a different name or something

**Comment by kinnison** [comment]
We can add proxies sure, all we'll need is some indication of if it'll be a "normal" proxy or if you'll need something special.  If it's normal, then just give us the name you want and we can add it.

If you do that pretty soon, we might even be able to get it into 1.17.0 which we'd like to release soon (and will then be entering a larger refactoring effort which will make 1.18.0 a longer way off).

**Comment by Manishearth** [comment]
Just needs to be clippy-driver. Users should probably not invoke this themselves so feel free to give it another name, but just clippy-driver is fine.

**Comment by kinnison** [comment]
See https://github.com/rust-lang/rustup.rs/pull/1679
