### ISSUE TITLE
RUSTUP_UPDATE_ROOT not set by default

### ISSUE THREAD

**Issue by Delet0r** [rust-lang/rustup#1684]
The rust install script (https://sh.rustup.rs) when executed fails with the error:
```
sh: 18: RUSTUP_UPDATE_ROOT: parameter not set
(23) Failed writing body
```

I tried it on two different ubuntu setup by executing `curl https://sh.rustup.rs -sSf | sh`. When I set the value manually it worked but as far as I understand it this variable should have been set with a default with a default value.

**Comment by thallada** [comment]
It looks like the script was just updated to fix this.

![screen shot 2019-03-06 at 10 17 38 am](https://user-images.githubusercontent.com/1505923/53891813-1f892900-3ff9-11e9-8f01-1c42624885e6.png)

**Comment by scealiontach** [comment]
problem introduced in https://github.com/rust-lang/rustup.rs/pull/1495

The script now contains a potential contradiction if the user has not set a RUSTUP_UPDATE_ROOT.  The set makes use of unbound variables an error, and then there is a check for if the variable is empty.  This would be fine if the user had set RUSTUP_UPDATE_ROOT to an empty value, but breaks if they haven't set it at all.  I have to believe that is quite common.
`
set -u

if [ -z "$RUSTUP_UPDATE_ROOT" ]; then
    RUSTUP_UPDATE_ROOT="https://static.rust-lang.org/rustup"
fi
`

**Comment by dwijnand** [comment]
See #1683

**Comment by kinnison** [comment]
All I'll say is that it was nearing midnight when I tested 1.17.0's installer, and I clearly tested 1.16.0's instead because I'm super-clever like that.  Mea culpa.

**Comment by dwijnand** [comment]
I'll bankroll the use of a brand-new version number.  No stress.

**Comment by kinnison** [comment]
We have a fix live which is fine for now, so unless other issues are spotted with 1.17.0 which we weren't aware of, I figure we'll leave this be.  @Delet0r are you okay for this issue to be closed?

**Comment by Delet0r** [comment]
Shure :D, thanks alot.
