### ISSUE TITLE
Check rustup-init.sh with Shellcheck

### ISSUE THREAD

**Issue by dwijnand** [rust-lang/rustup#1685]
We should verify `rustup-init.sh` with https://github.com/koalaman/shellcheck

Here's a simple Travis CI setup:

```yaml
script:
  - shellcheck --version
  - shellcheck rustup-init.sh || travis_terminate 1
```

**Comment by kinnison** [comment]
So I think this will be useful to have, yes.  But even if code is syntactically valid, it might sploof, so we'd still want to try running it too.  This could be a good catch of the mistake we had here though.
