### ISSUE TITLE
Make git tag to match those releases in CHANGELOG.md

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rustup#1687]
Those tags including:

* 1.11.0
* 1.10.0
* 1.9.0
* 1.8.0
* 1.7.0
* 1.6.0
* 1.5.0

Use this script to reproduce the list:
```bash
grep '# ' CHANGELOG.md | awk '{print $2}'| while IFS= read -r tag; do
  if ! git rev-parse "$tag" >/dev/null 2>&1; then
    echo "$tag"
  fi
done
```

**Comment by kinnison** [comment]
@nrc Do you think this looks sane?  If so, do you want to make and push the historic tags?

**Comment by dwijnand** [comment]
Those tags exist already: https://github.com/rust-lang/rustup.rs/tags

Any reason (or guess) as to why @lzutao wouldn't have them locally?

**Comment by tesuji** [comment]
Oh, seems like I don't have these tags locally. Thanks for your helps.

I would close this PR.
