### ISSUE TITLE
Add man proxy to rustup for viewing rust-toolchain manpages

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rustup#1690]
**Describe the problem you are trying to solve**

I cannot directly use `man cargo`, `man rustc`, etc.

**Describe the solution you'd like**

The new command might be: `rustup man` (which is somewhat similar to `rustup completions`).

As @kinnison suggest, we could use the `man` proxy of `rustup`. This command could alter 
the `MANPATH` to point to appropriate `rust-toolchain`'s manpages and open them with 
system `man` program.

Some examples:

Command                         | Meaning
--------                        | -------
`rustup man cargo`              | Display manpages of `cargo`
`rustup man cargo-new`          | Display manpages of `cargo new`
`rustup +nightly man rustc`     | Display manpages of nightly `rustc`
`rustup man install`            | Symlink-install manpages to `~/.local/share/man/man1`

**Comment by kinnison** [comment]
I fear we'd have to add a `man` proxy to rustup which altered the environment to include an appropriate MANPATH and then ran the system version of `man`.  I don't see how any other approach would work given we have to find which manpages to display based on `rust-toolchain` and friends.

**Comment by tesuji** [comment]
Closed in #616.
