### ISSUE TITLE
Rustup updates need to be validated with the RLS VSCode extension

### ISSUE THREAD

**Issue by ojhunt** [rust-lang/rustup#1694]
If you install rustup-1.17.0 the RLS extension ceases to work

**Steps**
1. Install the latest Rustup
2. Launch vscode
3. Edit a rust file

**Possible Solution(s)**
The problem is caused by an API breakage - the addition of "(default)" to the name of the current default toolchain. The RLS extension is going to change their parsing, so that they'll work again, but there should not have been a point where the two packages were incompatible, given that they're from the same org.

The fix should be to have the release checklist include making sure that the rest of the rust ecosystem is not broken by a release.

**Comment by dwijnand** [comment]
Parsing unstructured CLI output like that is just fragile and I disagree the solution is to take on the responsibility of downstream tools.

I'm happy RLS is unbreaking themselves, but I don't think there's a bug in Rustup.

Perhaps the RLS team can open a feature request for the information they require?

An alternative is the RLS team contributing a test that captures the behaviour required, with added documentation, such that any future changes have a chance of avoiding to re-break RLS.

**Comment by kinnison** [comment]
As Dale says, this is not an API with any kind of guarantee from `rustup` -- Over all I think we need to organise a plumbing layer for Rustup consumers, but shorter-term, tests from the RLS team (or even just a document/issue describing their use of rustup and thus what they depend on in terms of our output) would be useful.  I've noted on the PR discussing the release process that validating against `rls-vscode` is important for future releases.

**Comment by dwijnand** [comment]
@Xanewok (apologise, I couldn't find a GitHub team to ping for RLS-things) has this issue come up on your radar?  We feel this (essentially) isn't a bug in Rustup and are inclined to close it, but let us know if you'd like to pursue other of the two options mentioned.

**Comment by Xanewok** [comment]
No worries, thanks for letting me know! Right now I agree that we:
1) are using unstable CLI output so we don't expect it to follow any stability guarantees and should unbreak stuff ourselves
2) we need tests in `rls-vscode` (we have... none atm, which is rather depressing - I imagine having a regression test suite to be used with `rustup` is definitely something we should have and is feasible for us to do)

As to what to do in terms of direction, I think it might make sense for us to both contribute to tests and document behaviour ourselves here and create a test suite of our own (which we need anyway)
So I'd say - close away!
