### ISSUE TITLE
Rustup-Init displays ETA with lots of decimal places

### ISSUE THREAD

**Issue by nikonthethird** [rust-lang/rustup#1696]
**Problem**

I installed Rust 1.33 using Rustup-Init.exe on Windows 10 (in a Powershell window), and the ETA while installing displayed many decimal places that can be seen below. (See the last line of the picture).

![Rustup_Time](https://user-images.githubusercontent.com/15893812/54058784-3006f280-41f7-11e9-9b6c-fa82294a945a.png)

**Steps**

1. Download Rustup-Init
2. Install Rust
3. Look at the ETA during installation

**Notes**

Output of `rustup-init --version`: rustup-init 1.17.0 (069c88ed6 2019-03-05)

**Comment by kinnison** [comment]
Interesting, I thought we'd merged some code to improve matters here.  Thank you for this report.

**Comment by kinnison** [comment]
@Manishearth Could this be related to the work you did for #1547  ?

**Comment by Manishearth** [comment]
Yeah some of the things there need to be casted to integers. I'll make a patch.

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rustup.rs/pull/1699
