### ISSUE TITLE
Extremely slow download speeds on update in US

### ISSUE THREAD

**Issue by tensor-programming** [rust-lang/rustup#1702]
**Problem**
Running Rustup Update updates the toolchains as expected but the speed with which it fetches the files is absurdly slow.  For rustc, I am seeing 8mb/s where as for rust-docs I am getting speeds like 17KiB/s.  This pattern repeats for all of the toolchains installed on my machine (both stable and nightly msvc and gnu. 

As a side note, it also seems to ignore installing RLS.   

**Steps**

1. be on windows 10
2. run rustup update

**Notes**

Output of `rustup --version`: rustup 1.17.0 (069c88ed6 2019-03-05)
Output of `rustup show`: 
```
Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-gnu
nightly-x86_64-pc-windows-msvc (default)

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-pc-windows-msvc

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
```

I've seen these kinds of issues for people in the EU or in other countries outside of the US, but never seen them for people in the US.  Nor have I seen this kind of inconsistency.  I am on a home network and  there are no proxies or vpns involved.

**Comment by kinnison** [comment]
If this persists then it might be an indication that there's something squiffy with the S3 bucket we're in at a guess.  @alexcrichton any idea what might cause this pattern of access speeds?

**Comment by tensor-programming** [comment]
I reinstalled Rustup and the toolchains and ran update and heres what I noticed:

Specifically for Rust-docs the speed is terribly slow.  Everything else seems to be at least above 2.5MiBs.  

```
 10.2 MiB /  10.3 MiB (100 %) 267.2 KiB/s ETA:   0 s                 56.35823567708334 s
```
```
 10.2 MiB /  10.3 MiB (100 %) 294.4 KiB/s ETA:   0 s                n 56.04960123697917 s
```

As you can see on both nightly toolchains the rust-docs download took almost a minute with speed at 250KiBs and at lowest 15KiBs.  Could it be that Rust-Docs just has more files and something on the windows 10 filesystem can't handle the large amount of files?  Or is it something on the S3 bucket's side.

**Comment by kinnison** [comment]
Ooh I think I know what's going on - we use the same UI when unpacking components as we do when downloading them now.  This means that you get progress information for unpacking components which previously used to say nothing.  I imagine this is that since you're on Windows, the unpack of rust-docs is painful - this is a problem we're aware of, though we've yet to determine the right fix.

It's that rust-docs has many many small files, which is why it's slower at unpacking.

You can check that the progress indicator is for unpacking vs. downloading by looking at the line directly above it.  `downloading component...` vs `installing component...`

If it's just that unpacking is slow, then this issue can be closed since it's not download speeds, and we already have #1540 for that.

**Comment by tensor-programming** [comment]
Alright, so basically the download speed is being adjusted because its unpacking an archive and its not actually the download speed that is dropping but the installation process.  

Thank you for clearing that up.

**Comment by rosspeili** [comment]
Disabling windows defender or at least whitelisting rust folders will boost to normal waiting times. Still slow cause tens of thousands of tiny files, but at least windows won't be trying to police all of them one by one which ads 90%+ to the waiting time.

Relevant messages could be helpful in the rustup-init setup process.

**Comment by rami3l** [comment]
> Disabling windows defender or at least whitelisting rust folders will boost to normal waiting times. Still slow cause tens of thousands of tiny files, but at least windows won't be trying to police all of them one by one which ads 90%+ to the waiting time.
> 
> Relevant messages could be helpful in the rustup-init setup process.

@rosspeili Thanks for sharing! Actually we have already dedicated a whole section of our release notes to this issue: https://blog.rust-lang.org/2026/03/12/Rustup-1.29.0/#caveats
