### ISSUE TITLE
Mystery of the disappearing --prefix option

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rustup#1703]
Snapcraft Rust plugin has been using `--prefix` option, which isn't supported by the current rustup, and all Rust builds in Ubuntu Snaps became broken: 

https://bugs.launchpad.net/snapcraft/+bug/1809259

and builds on build.snapcraft.io:

https://github.com/canonical-websites/build.snapcraft.io/issues/1203

Snapcraft is taking a while to recover from that.

Please consider keeping options for backwards compatibility forever, even as no-ops.

**Comment by kinnison** [comment]
I'm somewhat confused by your statement here.  As far as I can tell, neither rustup-init.sh nor rustup-init in setup mode have supported a `--prefix` commandline argument.

Could you help me narrow down what happened, when, and where, by telling me what used to work, with what version of rustup, and when it stopped working.  I'll then try and see if we can ensure that this kind of thing doesn't hit you in the future.

As a side note, we are intending to define some stable cmdline API for scripting to use, but this will be a long term project and not anything soon.

**Comment by kornelski** [comment]
Snapcraft runs:

    /root/parts/…/rust/rustup.sh --prefix=/root/parts/…/rust --disable-sudo --save --channel=stable

I presume it must have worked a few months ago, since Snapcraft Rust support has been released with this.

**Comment by kinnison** [comment]
Can you find out what that script is and where it comes from?  Those flags are not those of rustup-init.sh or rustup-init.

**Comment by kornelski** [comment]
The script seems to be downloaded from https://sh.rustup.rs

https://github.com/snapcore/snapcraft/blob/8eee6c131e89feae428d335085e8d47866bd8030/snapcraft/plugins/rust.py#L51

**Comment by kornelski** [comment]
Sorry for the confusion. I assumed that when it broke in December, that was due to a new rustup release.

But indeed I don't see any related change, and I can only find very very old posts mentioning the `--prefix` and `--channel` options. 

Could they be from the previous shell-based rustup? I don't know why it broke recently though. Maybe some forgotten files got updated or old caches flushed? 

I'm not sure, but given that it's not an intentional recent rustup change, it's probably best for Snapcraft to push forward with update on their side.
