### ISSUE TITLE
Update Reqwest in order to avoid Crash with proxy URLs containing `^`

### ISSUE THREAD

**Issue by mmacedoeu** [rust-lang/rustup#1710]
**Problem**

Some urls on proxy env vars cause rustup-init to panic

**Steps**

1. setup proxy env vars with url encoded special chars
2.
3.

**Possible Solution(s)**

Update reqwest to newer version see https://github.com/seanmonstar/reqwest/issues/442

**Notes**

**Comment by gnanasekar-somanathan** [comment]
Facing same problem behind proxy when installing rustup
thread 'reqwest-internal-sync-runtime' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', src/libcore/result.rs:997:5

Any workarounds?

**Comment by kinnison** [comment]
So based on the referenced bug in reqwest, I think we need to update our lock file for a newer http version.  I'll look at this ASAP.  Short-term you could set RUSTUP_USE_CURL=1 in your environment to push rustup back to using libcurl.

**Comment by pkking** [comment]
Is there a windows binary contain this fix? I download latest rustup from website still meet this problem

**Comment by kinnison** [comment]
@pkking I'm afraid we don't do `nightly` or similar for `rustup` itself.  We are looking to cut a new release of `rustup` fairly soon (within a week or two) which will contain the fix.  Until then you would have to build your own copy (which isn't too hard to do) if you wanted the fix.
