### ISSUE TITLE
Support HTTP over TLS 1.3 on rustup.rs

### ISSUE THREAD

**Issue by sanmai-NL** [rust-lang/rustup#1717]
The maximum TLS version supported is currently 1.2. TLS 1.3 delivers [security and performance benefits](https://casecurity.org/2018/04/10/tls-1-3-includes-improvements-to-security-and-performance/).

In terms of security, the distribution mechanism's security currently depends on TLS. Only with TLS 1.3 and the appropriate certificate practical downgrade attacks can be prevented. https://www.nccgroup.trust/uk/about-us/newsroom-and-events/blogs/2019/february/downgrade-attack-on-tls-1.3-and-vulnerabilities-in-major-tls-libraries/

**Comment by kinnison** [comment]
The rustup website is managed on EC2 - do you happen to know if TLS1.3 is supported by AWS?

**Comment by sanmai-NL** [comment]
@kinnison: I don't know. I have understood [AWS uses the s2n](https://aws.amazon.com/blogs/security/s2n-is-now-handling-100-percent-of-of-ssl-traffic-for-amazon-s3/) implementation for TLS and the s2n maintainership is actively working on TLS 1.3 support (https://github.com/awslabs/s2n/issues/388).

**Comment by kinnison** [comment]
I've re-checked and cloudfront currently still don't support TLS1.3

**Comment by BryanQuigley** [comment]
AFAICT TLS1.3 support is working now.

**Comment by sanmai-NL** [comment]
Do we enforce TLS 1.3 though?

**Comment by kinnison** [comment]
> Do we enforce TLS 1.3 though?

Right now it would not be appropriate to do so because of corporate proxies etc.  We will use 1.3 if it's available by preference.  I imagine if a system configured openssl to require 1.3 we'd honour that (I think we read the system openssl.cnf)

**Comment by kinnison** [comment]
There may be some work to do in `rustup-init.sh` to look for support in system curl/wget though actually.  I'll open an issue for that.

**Comment by kinnison** [comment]
I've filed #2581 to continue the work
