### ISSUE TITLE
rustup shows timings on windows like "5.1334958959 mins"

### ISSUE THREAD

**Issue by mark-summerfield** [rust-lang/rustup#1720]
**Problem**

When doing an update it shows times like this:
 1.9 MiB /   8.5 MiB ( 22 %)  52.8 KiB/s ETA: 2.1394449869791665 min 8.36669921875 s

Surely this should be more like "2min 8sec"?

**Steps**

rustup update stable on Windows 7-64

**Possible Solution(s)**

**Notes**

Output of `rustup --version`: rustup 1.17.0 (069c88ed6 2019-03-05)
Output of `rustup show`:
V:\>rustup show
Default host: x86_64-pc-windows-msvc

stable-x86_64-pc-windows-msvc (default)
rustc 1.33.0 (2aa4c46cf 2019-02-28)

**Comment by kinnison** [comment]
Fixed in #1699
