### ISSUE TITLE
The "rustup fix --edition" command claims project is not under VCS

### ISSUE THREAD

**Issue by patriksvensson** [rust-lang/rustup#1721]
**Problem**

I wanted to update an old project to the 2018 edition (on Windows), so I ran `rustup fix --edition`. However, even though my project is under source control, it says it's not:

```
Patrik@SPECTRE-3 [C:\Users\Patrik\Source\Git\cake-build\cakeup] [master ≡]
> cargo fix --edition
error: no VCS found for this package and `cargo fix` can potentially perform destructive changes; if you'd like to suppress this error pass `--allow-no-vcs`
```

Of course I can use the `--allow-no-vcs` flag, so it's not really a problem but wanted to report this anyway.

**Steps**

1. Update the toolchain by running `rustup update`
2. Clone `git@github.com:cake-build/cakeup.git`
3. Run `rustup fix --edition`

**Notes**

Output of `rustup --version`: 

```
rustup 1.17.0 (069c88ed6 2019-03-05)
```

Output of `rustup show`:

```
Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.33.0 (2aa4c46cf 2019-02-28)
```

**Comment by kinnison** [comment]
I think this should be filed against `cargo` since `fix` is not a `rustup` subcommand.

**Comment by patriksvensson** [comment]
@kinnison You're absolutely right. I was a bit tired when I wrote the issue. Thanks! 👍
