### ISSUE TITLE
Rustup display lots of decimal places for ETA when installing components

### ISSUE THREAD

**Issue by toothbrush7777777** [rust-lang/rustup#1731]
**Problem**

I ran `rustup self update && rustup update nightly` and the ETA when _installing_ components shows lots and lots of decimal places.

**Steps**

1. Run `rustup update nightly` in latest version of rustup
2. Check displayed ETA when installing components:
    ```
    info: installing component 'rust-docs'
     10.2 MiB /  10.2 MiB (100 %) 288.0 KiB/s ETA:   5.682814825148810 min 40.968889508928584 s
    ```

**Possible Solution(s)**

#1699 

**Notes**

Output of `rustup --version`: `rustup 1.17.0 (069c88ed6 2019-03-05)`
Output of `rustup show`:
```
Default host: x86_64-pc-windows-gnu

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu
nightly-x86_64-pc-windows-gnu (default)

active toolchain
----------------

nightly-x86_64-pc-windows-gnu (default)
(timeout reading rustc version)


```

**Comment by kinnison** [comment]
This is a known issue whose fix is, as you have noted, already merged.  I'm unclear as to what you hope to achieve with this bug report.

**Comment by toothbrush7777777** [comment]
I didn't know that fixed this issue; I thought it was specific to the other issue. I can close this issue if you verify that it indeed fixes the issue.

**Comment by kinnison** [comment]
It's the same code which is used to report progress in both cases.  Sorry, I realise that wasn't necessarily obvious to you.

**Comment by toothbrush7777777** [comment]
@kinnison Thanks for clarifying.
