### ISSUE TITLE
Remove header license

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rustup#1732]
Related https://github.com/rust-lang/rust/pull/57108.

**Comment by kinnison** [comment]
I don't understand why this is desirable considering the shell script is acquirable independently of rustup itself.

**Comment by tesuji** [comment]
No, I just saw header license in rustup-init.sh. Looks like I am wrong. In that case, I will change the issue name.

**Comment by kinnison** [comment]
Given https://github.com/rust-lang/rustup.rs/pull/1733#issuecomment-478718234 I think @nrc is in favour of this change anyway, so I'll remove my mild objection.

**Comment by tesuji** [comment]
Closed on #1733.
