### ISSUE TITLE
Support 'optional' components

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rustup#1735]
When using Nightly Rust, some components (e.g. Clippy) may be temporarily unavailable due to recent compiler changes. If the latest nightly doesn't happen to have Clippy available, running `rustup update nightly` gives me this error:

```
error: component 'clippy' for target 'x86_64-unknown-linux-gnu' is unavailable for download
```

This requires me to:
1. Run `rustup component remove clippy`
2. Re-run `rustup update nightly`
3. The next time I want to use Clippy, run `rustup component add clippy`

It would be nice to be able to mark components like Clippy as 'optional' - it's nice to have them available, but I still want to update even if they're not.

When running `rustup update`, any options components would be downloaded if available. If an optional component is currently unavailable, a warning would be printed, but the update would continue.

**Comment by nrc** [comment]
You can use `rustup update --force` to do this, you might need to `rustup self update` to get this ability.

**Comment by kinnison** [comment]
Now, a `rustup update` will backtrack in time for `nightly` trying to help you update, but we still don't have a concept of a "desired but not currently installed component".  Is what is in 1.20 sufficient or do you still want something closer to how you described here?
