### ISSUE TITLE
rustup show fails on terminal without color

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rustup#1738]
**Problem**

When I run `rustup show` inside an Emacs shell, I get the message `error: color not supported by the terminal`. Some other rustup commands, like `rustup install`, work. I haven't tried the commands exhaustively.

**Possible Solution(s)**

`rustup show | cat` works.

**Notes**

Output of `rustup --version`:
`rustup 1.17.0 (069c88ed6 2019-03-05)`

Output of `rustup show`:
`error: color not supported by the terminal`

**Comment by tesuji** [comment]
Could you try these workarounds?
- [How to make Emacs terminal colors the same as Emacs GUI colors?][1]
- [Use colors specified in terminal emulator for emacs][2]

[1]: https://stackoverflow.com/questions/63950/how-to-make-emacs-terminal-colors-the-same-as-emacs-gui-colors
[2]: https://emacs.stackexchange.com/questions/21354/use-colors-specified-in-terminal-emulator-for-emacs

**Comment by kinnison** [comment]
Also could you please tell me the value of TERM for your terminal in emacs?

**Comment by tspiteri** [comment]
Those workarounds are for running Emacs inside a terminal, not using a window system.

The issue is with running `rustup show` inside a shell inside Emacs, and I get the same error whether I'm running Emacs inside a terminal or using the window system.

I can reproduce the issue if I `export TERM=dumb` in a normal terminal. `rustup update` and `rustup show | cat` work, but `rustup show` fails.

**Comment by tspiteri** [comment]
@kinnison Inside the shell in Emacs, `TERM=dumb`.

**Comment by kinnison** [comment]
Thanks @tspiteri I've confirmed I can reproduce with `env TERM=dumb rustup show` in my normal terminal so I'll see what I can do to find a fix.
