### ISSUE TITLE
rustup 1.17 complains about not being installed in CARGO_HOME

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rustup#1742]
On `rustup 1.16.0` it was possible to override `CARGO_HOME` to change Cargo's cache directory, since `rustup 1.17.0` this has stopped working and `rustup` complains about not being installed under the overridden `CARGO_HOME` directory:

```console
> docker run --rm -e 'CARGO_HOME=target/cargo' nemo157/rustup@sha256:cc47026867f4dade98fdaa6aa385732ad3feaf04cb56c3b9a363be70c196c1e0 sh -c 'rustup --version && rustup update stable && cargo +stable --version'
rustup 1.16.0 (beab5ac2b 2018-12-06)
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2019-02-28, rust version 1.33.0 (2aa4c46cf 2019-02-28)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'

  stable-x86_64-unknown-linux-gnu installed - rustc 1.33.0 (2aa4c46cf 2019-02-28)

cargo 1.33.0 (f099fe94b 2019-02-12)
```

```console
> docker run --rm -e 'CARGO_HOME=target/cargo' nemo157/rustup@sha256:0d85c5b353b6674357db5b302e43a67c9705b7095f8128a7e59264e532644878 sh -c 'rustup --version && rustup update stable && cargo +stable --version'
rustup 1.17.0 (069c88ed6 2019-03-05)
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2019-02-28, rust version 1.33.0 (2aa4c46cf 2019-02-28)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'

error: rustup is not installed at '/target/cargo'
  stable-x86_64-unknown-linux-gnu installed - rustc 1.33.0 (2aa4c46cf 2019-02-28)
```

**Comment by kinnison** [comment]
Interesting.  Are you able to bisect between 1.16.0 and 1.17.0 to find the commit which causes this to occur?  I am not really au-fait with docker so don't know how I'd do that myself.

**Comment by Nemo157** [comment]
These were just the docker images I’ve been using in CI so was the easiest way to test without affecting my system, I only have these two versions of rustup installed in them.

I can probably give bisecting a go later today.

**Comment by kinnison** [comment]
Thank you.

**Comment by Nemo157** [comment]
I found some time to do it earlier, first failing commit is 9f532de4d33330a35d4164a7d2faad68a6b7addb

```
commit 9f532de4d33330a35d4164a7d2faad68a6b7addb
Author: Nick Cameron <nrc@ncameron.org>
Date:   Thu Dec 6 14:15:19 2018 -0500

    self update after updating a single toolchain
```

which makes sense, the other issues I noticed related to this error message were from running `rustup self update`.

It looks like this can be suppressed with `--no-self-update`, but that doesn't appear to be mentioned in `rustup update --help`.

**Comment by kinnison** [comment]
Interesting, thank you.

The --no-self-update option is indeed deliberately hidden, perhaps @nrc can explain why?

**Comment by nrc** [comment]
> The --no-self-update option is indeed deliberately hidden, perhaps @nrc can explain why?

I cannot. I think it should be documented.

**Comment by kinnison** [comment]
> I cannot. I think it should be documented.

OK, thanks, I'll see if I can get to that if you don't before me.

@Nemo157 would that be sufficient for you, or do you think there's a better error we might give in this circumstance?

**Comment by Nemo157** [comment]
That seems fine. You could consider adding some context to the error message so that users know it's self-update related, but this seems like a niche enough use-case.

I think the real fix would be decoupling the environment variables that determine where rustup is installed and where cargo caches the registry & crates, but seeing as [RFC1615](https://github.com/rust-lang/rfcs/pull/1615) has been stuck for almost 3 years and it's somewhat related, I don't see that happening anytime soon.

**Comment by kinnison** [comment]
OK thanks, I'll assign this to myself to remind me to get some documentation around `--no-self-update` done, but I'm not sure it's worth complicating the error path there.  As you say, the decoupling has been, erm, on-pause :D
