### ISSUE TITLE
Replace deprecated dependent crates

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rustup#1755]
**Describe the problem you are trying to solve**

I suggest to replace deprecated (abandoned) dependent crates like:

- [x] ~`markdown` => `pulldown_cmark`~
  Rationale: rustup currently needs to iterate through `markdown::Block`
  to print content to std{out,err} approriately. But `pulldown_cmark`
  doesn't provide equivalent methods (only `push_html` and `write_html`).

- [x] ~`ole32-sys` => `winapi`~
  Rationale: I remove `ole32-sys` from `Cargo.toml` and rustup build fine.

- [x] ~`time` => `chrono`~
  Rationale: `chrono` currently use `time` as dependency itself.

**Describe the solution you'd like**

Just try to replace them. Build and fix cycle :) .

**Notes**

Nothing here.

**Comment by kinnison** [comment]
This sounds emminently sensible and I look forward to reviewing PRs for each in turn :D
