### ISSUE TITLE
rustup-init.exe doesn't work if file-name is changed to a name including special-signs like '+'

### ISSUE THREAD

**Issue by crp-dev-outlook** [rust-lang/rustup#1757]

**Comment by kinnison** [comment]
Hi @crp-dev-outlook,

Thank you for your bug report.  Can you please provide me with an example workflow which you are trying to achieve where `rustup-init.exe` then fails to work?  We use the name of the binary as a way to disambiguate which command is actually being run (`rustup-init.exe` *is* `rustup.exe` etc).

Thanks,

D.

**Comment by crp-dev-outlook** [comment]
Ooops, sry - seems i missed to paste the message ...

Essentially as the title says, effectively going easy by downloading the rustup-init.exe as correctly identified for Windows 10 LTSC 2019 | Windows 10 Professional 1903 | Windows Server Standard 2016 [all: amd64 | X86_64] from https://rustup.rs/ ;

I always 'save as' to rewrite the file-name by the schema:
`
+Manufacturer_Name-Product_Name+Product_Version-Product_Branch+-OriginalName_and.FileEnding
`

First i thought it was due to the length of the FileName and the fact that i was saving it some levels too deep in the Folder-Hierarchy (NTFS-Limitation ~253 Byte for FileName and including FolderNames some ~1000 chars max as far as i can remember right now.

So i tested it in the root of a volume, but the Installer ( https://win.rustup.rs/x86_64/rustup-init.exe ) just didn't want to execute.

Then i left the original filename untouched and voilà, it just did what it was intended to do. To counter-check for sure that the executable is not affected by the char-|byte- -limit of ntfs i buried it kneedeep, but it executed fine.

So it is definitely the fact i added the [ + ] plus-sign to the file-name.

I already know that this can happen under circumstances where the executable does not make use of the windows internal utf-16 filename specification, but instead parsing as ansi or utf-8, whereas characters like the plus-sign (although fine by ntfs) effectively become interpreted in a regex-like manner. Sorry its a hazy memoryblob i have on that exact problem; i ran into it once when i was coding under Python 2.6 .. i think it was ...

However, if my assumption is correct, then either

a) advise explicitly, that renaming the rustup-init.exe using characters like + ( plus-sign) is not wise ...

b) double-check the executable internally uses utf-16 under Windows, so it doesn't hiccup on such transformed filename

c) if intended to handle anything classical ANSI-C-compatible, flatten filename-parsing by double stringifying-down.

As i said: easiest and for sure most beneficial variant to handle this special case is by simply leaving a note that using +-sign in editing the rustup-init.exe is a 'baaaad baaaaaad baaaaaad ting'.

As a sidenote: If 'my+plus+ified+filename+for+rustup-init.exe' is stored on a UDF Rev 2.01 or on a ReFS formatted volume, it executes just fine. That was what lead me to remember that there was that internal vs external and utf-8 vs utf-16 handling whatever thingy, bubbling up my mind.

Sorry. Hope (my fuzzy wording) helps. Just do yourself a favor: Just state the use of +sign in filename is bullsh ... uh .. bad science.

If you persist to handle this niche-case also as well as possible, just leave a comment, with what you need to be tested or informed about and i will surely find some time to dig out what exactly goes wrong.

Yay ...

**Comment by kinnison** [comment]
I understand what you tried to do, but certainly it's not a supported mechanism for rustup because we rely on the filename being *exactly* `rustup-init.exe` in order to detect we're in installer mode.
