### ISSUE TITLE
ETA precision is unneeded and complicated.

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rustup#1761]
**Describe the problem you are trying to solve**

This is what you get to stare at when updating Rust on Windows:

```
info: installing component 'rust-docs'
  2.8 MiB /  10.2 MiB ( 27 %)  19.2 KiB/s ETA: 6.610965304904514 min 36.65791829427087 s
```

**Describe the solution you'd like**

**15** decimals of precision gets us down to [femtoseconds](https://en.wikipedia.org/wiki/Femtosecond), an utterly unneeded specificity.

Additionally, reporting the precision on the minutes **and** the seconds is redundant.

By nature, this calculation is an estimate and doesn't need this amount of precision. Round up to a comparatively large timeslice (5, 10 seconds) and omit the decimals on minutes:

```
info: installing component 'rust-docs'
  2.8 MiB /  10.2 MiB ( 27 %)  19.2 KiB/s ETA: 6m 40s
```

This hopefully have the nice side effect of preventing it from bouncing around a lot as well.

**Comment by nrc** [comment]
Dup of #1696, closed by #1699
