### ISSUE TITLE
 toolchain slimming options

### ISSUE THREAD

**Issue by softprops** [rust-lang/rustup#1771]
**Describe the problem you are trying to solve**

**Describe the solution you'd like**

I'd like a way to opt out of any default component that isn't essential for build and test to install the smallest possible toolchain. 

I believe rustup installs more than that including vendored copies of multiple books and other documentation with no way to opt out

**Notes**

I have docker containers that install rust with rustup for cases solely targeting building and testing. I would like these build containers to be as small as possible.

**Comment by kinnison** [comment]
This kind of functionality is that intended by the _profiles_ concept being developed by @nrc.

**Comment by lnicola** [comment]
Duplicate of https://github.com/rust-lang/rustup.rs/issues/998.

**Comment by softprops** [comment]
@lnicola I subscribed to the other issue which has more momentum and commentary. I'll close this in favor of that
