### ISSUE TITLE
Bash syntax errors reported when loading cargo shell completions

### ISSUE THREAD

**Issue by jimmycuadra** [rust-lang/rustup#1799]
**Problem**

The cargo command completion shell script produces syntax errors when loaded:

```
-bash: /redacted/.rustup/toolchains/stable-x86_64-apple-darwin/etc/bash_completion.d/cargo: line 82: syntax error in conditional expression: unexpected token `('
-bash: /redacted/.rustup/toolchains/stable-x86_64-apple-darwin/etc/bash_completion.d/cargo: line 82: syntax error near `@(t'
-bash: /redacted/.rustup/toolchains/stable-x86_64-apple-darwin/etc/bash_completion.d/cargo: line 82: `		if [[ "${cmd}" = @(test|bench) ]]; then'
```

**Steps**

1. Install latest rustup. I'm using rustup 1.18.0 (8603e2c56 2019-04-22).
2. Run `source $(rustc --print sysroot)/etc/bash_completion.d/cargo` in a shell.
3. Observe output.

**Possible Solution(s)**

**Notes**

Output of `bash --version`:
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.

Output of `rustup --version`: rustup 1.18.0 (8603e2c56 2019-04-22)

**Comment by kinnison** [comment]
Hi, the completions come from Cargo rather than rustup itself, this is probably better filed against `rust-lang/cargo`

**Comment by rbtcollins** [comment]
Fixed in https://github.com/rust-lang/cargo/pull/6905
