### ISSUE TITLE
Shift away from `term` crate

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rustup#1818]
The `term` crate is unmaintained.  cf. https://github.com/Stebalien/term/issues/93

It is recommended we shift to `termcolor` (https://crates.io/crates/termcolor)

Whatever the move is toward, it ought to be away from an unmaintained and troublesome crate.

**Comment by kinnison** [comment]
Doing this may solve #1800

**Comment by jens1o** [comment]
I'd like to take this. :)

**Comment by kinnison** [comment]
@jens1o Cool, thank you, if you want to discuss things, you should come onto the Rustup discord on https://discord.gg/cKdYFVz and we can talk.

**Comment by omang777** [comment]
I like this.

**Comment by pickfire** [comment]
I believe this is solved?

**Comment by kinnison** [comment]
> I believe this is solved?

@pickfire At this time we're still using `term` because we had issues with other options

**Comment by Rudi3** [comment]
I'm not sure what exactly you need, but what about https://github.com/crossterm-rs/crossterm?

**Comment by kinnison** [comment]
That looks potentially good, though I was thinking more about a crate which integrates progress bars and messages.

**Comment by Rudi3** [comment]
I see, what about https://github.com/mitsuhiko/indicatif then?

**Comment by kinnison** [comment]
Yeah something like Indicatif would be good.  It'll be quite a bit of work to rearrange all the output to go properly via that, but it would potentially allow some cleanup.

**Comment by aloucks** [comment]
What was the issue with `termcolor`? Isn't that what cargo uses?

**Comment by kinnison** [comment]
I don't recall what prevented `termcolor` from being suitable, likely something to do with how we currently (hackily) do progress bars.
