### ISSUE TITLE
workaround can be fixed

### ISSUE THREAD

**Issue by ghost** [rust-lang/rustup#1852]
https://github.com/rust-lang/rustup.rs/blob/master/src/lib.rs#L54 is naming an issue which is the reason for some workaround.

the [issue](https://github.com/rust-lang-nursery/error-chain/issues/254) is now fixed, therefore the workaround can be removed ;)

**Comment by kinnison** [comment]
This looks to be fairly easy to do:

- [ ] remove the workaround
- [ ] update error-chain version
- [ ] verify everything is okay incl. with clippy

I'm prepared to help anyone along who wants to do this.
