### ISSUE TITLE
Complete, or spurious `.partial` file can cause repeated failure to download

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rustup#1854]
If a `.partial` file is actually complete, then any attempt to continue the download will fail because the byte-range request will be out-of-range.  There is then no recovery method within `rustup` instead the user ends up having to delete the `.partial` file and try again.

In #1243 this has been discussed, and there's at least one person for whom the partial file was corrupt, and one for whom it was complete, so we need to handle both of those cases.

**Comment by Glamhoth** [comment]
I'm taking a look at this.
