### ISSUE TITLE
Replace link to #rust-beginners IRC on home page

### ISSUE THREAD

**Issue by sunjay** [rust-lang/rustup#1859]
Now that the [IRC Sunset](https://blog.rust-lang.org/2019/04/26/Mozilla-IRC-Sunset-and-the-Rust-Channel.html) has been announced, we should consider replacing the "Ask on #rust-beginners" link with something else. I wanted to open a separate issue from #1372 because this is a bit more urgent now that the IRC channels are going to be shutdown. 

Note that I'm not opening this to argue about the benefits/drawbacks of IRC. The channel is not going to be there anymore at some point and we need to make sure beginners have a way to get unstuck. That's all. 

I think we should replace it with two links:

- To the Rust discord and its beginners channel
- To the Rust users forum

This gives people two avenues to get help instead of one and largely deals with anyone who wouldn't like to join the discord server.

**Comment by kinnison** [comment]
This sounds emminently sensible.  Is there any chance you could provide a PR to this effect?

**Comment by sunjay** [comment]
@kinnison see #1860. :)
