### ISSUE TITLE
Can't update to stable 1.35 (Windows + McAffee/Symantec)

### ISSUE THREAD

**Issue by Geobert** [rust-lang/rustup#1870]
**Problem**
`rustup update stable` fails on Windows 7 laptop with this kind of errors:
```
λ  rustup update stable
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: latest update on 2019-05-23, rust version 1.35.0 (3c235d560 2019-05-20)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: downloading component 'rust-std' for 'i686-pc-windows-msvc'
info: downloading component 'rust-analysis'
info: downloading component 'rust-src'
info: downloading component 'rls'
info: downloading component 'rustfmt'
info: downloading component 'clippy'
info: removing component 'rustc'
info: removing component 'rust-std'
info: removing component 'cargo'
info: removing component 'rust-docs'
info: removing component 'rust-std' for 'i686-pc-windows-msvc'
info: removing component 'rust-analysis'
info: removing component 'rust-src'
info: removing component 'rls'
info: removing component 'rustfmt'
info: removing component 'clippy'
info: installing component 'rustc'
 60.0 MiB /  60.0 MiB (100 %)  13.9 MiB/s in 14s ETA:  0s
info: installing component 'rust-std'
 53.1 MiB /  53.1 MiB (100 %)  12.9 MiB/s in  4s ETA:  0s
info: installing component 'cargo'
info: installing component 'rust-docs'
 10.3 MiB /  10.3 MiB (100 %) 401.6 KiB/s in  1m 52s ETA:  0s
info: rolling back changes
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\wxp7x5fu66ro7uib_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\b
in'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\87cu99tuet1_8jof_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\s
hare'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\njl5zjh1vv3u_f_7_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\s
hare/doc'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\a3v9c1_ge4tpn6v3_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\l
ib/rustlib/x86_64-pc-windows-msvc'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\uy_fswm9q7qled_a_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\s
hare/doc/rust'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\yxll7wcaprlw_mik_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\e
tc'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\9gl9lc_8pixiiqfg_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\e
tc/bash_completion.d'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\6t7busnax3m2avbn_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\s
hare/doc/cargo'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\gc1cknvnskm_ezk0_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\s
hare/man'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\uflb3gpv_u26533g_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\s
hare/man/man1'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\73ibcu537omueytr_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\s
hare/zsh'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\ya9cygapnd82_h1o_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\s
hare/zsh/site-functions'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\i18s9gd8apyvbyxy_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\l
ib/rustlib/x86_64-pc-windows-msvc/lib'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\d5iyjok_t9ii2dy__dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\l
ib/rustlib/etc'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\idx95puxu1rf43da_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\l
ib/rustlib/x86_64-pc-windows-msvc/bin'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\29v99sp5j0d5_ik0_dir\bk' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\l
ib/rustlib/x86_64-pc-windows-msvc/codegen-backends'
error: could not rename component file from 'C:\Users\Geobomatic\.rustup\tmp\zb5dkerufltfrz7z_dir\rust-docs\share/doc/rust/html' to 'C:\Users\Geobomatic\.rustup\toolchains\stab
le-x86_64-pc-windows-msvc\share/doc/rust/html'
info: caused by: Access is denied. (os error 5)
```
**Steps**
1. run `rustup update stable`

**Notes**
This laptop is crap (corporate machine) and has McAffee anti virus + disk encryption installed.

With previous rustup, it was slow but it worked.

Output of `rustup --version`:
rustup 1.18.3 (435397f48 2019-05-22)
Output of `rustup show`:
Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

stable-i686-pc-windows-msvc
stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

i686-pc-windows-msvc
x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.34.2 (6c2484dc3 2019-05-13)

**Comment by neelakantankk** [comment]
I have the same issue. The renaming seems to fail because the file separator is incorrect ('/' instead of '\').

**Comment by rbtcollins** [comment]
Hi, so all the errors about renaming from 'bk' are rollback errors - they are victims, not causes.
This `could not rename component file from ''C:\Users\Geobomatic\.rustup\tmp\zb5dkerufltfrz7z_dir\rust-docs\share/doc/rust/html' to 'C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'` is the actual error.
The source file name and destination etc all look normal (see #1647 for the weirdness).

I don't see in your output the file handle closing tracking we added for Defender; possibly McAfee quarantines with different logic. We have a join() there, so we can be sure that the CloseHandle calls have all been submitted to the OS and completed. That means that the unpacking process completed.

We changed from making a whole new copy of the docs at the end of the unpack to moving the docs at the end of the unpack process. 

So here is hypothesis one: we go to move() the file, the file is open in McAfee doing its scan, and as such the rename, which involves opening the file on Windows, cannot take place.
  Workaround number one for this would be to detect an access denied on such a rename and retry with a visual indicator. If a full scan has to complete for this to proceed, then this may take some time.

I think its worth noting that an on-demand scan of a full disk could race with a regular unpack and rename *anyway* to cause the unpack-then-rename operation to fail: we don't do anything to prevent other processes operating in the temporary directory, and so adding in some resiliency in these code paths, due to Windows file system semantics, makes a lot of sense to me, as in this model this is just a long-tail failure mode, which our increased performance has uncovered.

@Geobert if this is reproducible, could you please get a trace, e.g. with ProcessMonitor, or WPA or some similar tool, and confirm what is going on? Don't filter for rustup.exe - filter for all file activity in your `.rustup\tmp` directory. If something else is going on this would let us actually prepare a patch to fix it for you.

If it is not reproducible, then we can prepare a patch regardless and see if this reoccurs with some cautious settings.

If, after gathering traces etc, you still cannot update, you could try rustup toolchain uninstall stable; rustup toolchain install stable - but since the problem appears to be a race condition I don't expect better results.

Other things that are more likely to work:
- add an exclusion to mcafee temporarily
- use an older rustup temporarily until we can issue a build that addresses this situation for you

@neelakantankkno, thats not it. See #1647

**Comment by rbtcollins** [comment]
rustup 1.18.0 did the move rather than copy thing, but was *much* slower at extraction - about 4x slower. So this reinforces the race condition hypothesis. @neelakantankk do you also have McAfee ?

**Comment by neelakantankk** [comment]
No, there's only Symantec Endpoint Protection running on this.

**Comment by rbtcollins** [comment]
Workaround:

Download https://static.rust-lang.org/rustup/archive/1.18.0/x86_64-pc-windows-msvc/rustup-init.exe
Run it with --no-self-update

This will run the previous release that does not have the major performance improvements.

**Comment by rbtcollins** [comment]
@neelakantankk what OS ?

**Comment by neelakantankk** [comment]
Windows 10. Toolschain's stable-x86_64-pc-windows-gnu

**Comment by Geobert** [comment]
Thank you for your answer!

It's reproductible, I have generated the traces, what am I looking for?

**Comment by rbtcollins** [comment]
@Geobert Some process must have a handle open on C:\Users\Geobomatic\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html at the time the Access Denied error is returned to rustup. 

*or*, some file within that path similarly, and then the error won't occur on the CreateFile call to open for the rename, but on the ContentDisposition setting, if I remember correctly. - its late here, but you get the idea of what we're looking for I hope.

If that process is rustup itself, its a bug in the new threading code - unlikely but possible I guess? Maybe some thing with mcafee interaction - we'll have to dig.

If that process is not rustup, lets start with what it is and try to either confirm or reject the hypothesis that its mcafee interfering with our IO.

**Comment by Geobert** [comment]
![image](https://user-images.githubusercontent.com/72570/58326349-7cd88d80-7e24-11e9-9861-f93aab1f9287.png)

McAffee is definitively guilty.

Worth noticing that when recapturing traces (Process Monitor crashed) the update went through. I had to update my i686 toolchain to reproduce again (I thought it was systematic at first as I got it 3/3 and then the 4th passes)

EDIT: Note that I've hidden SearchProtocolHost.exe in the traces

**Comment by rbtcollins** [comment]
I've put a release build of rustup with a possible fix for this at https://s3-ap-southeast-2.amazonaws.com/rbtcollins-experiments/rustup/rustup.exe It should have md5 hash 6fb8c3b34904b26f8e2771bc18185435

If anyone is still experiencing this, please try downloading that build and running it (e.g. .\rustup.exe toolchain update stable). It has a retry and backoff mechanism added around the failing rename.

We cannot merge that until https://github.com/jimmycuadra/retry/pull/20 goes through review/fixup/merge/release, so this will be a workaround for a bit.

**Comment by rbtcollins** [comment]
Thanks @Geobert that definitely confirms the hypothesis and I hope my patch will work around it acceptably; if you have time to do some uninstall +_ reinstalls of nightly using it that would be great - that should be enough to trigger (or not) the race.

**Comment by Geobert** [comment]
I'll test your patch monday first thing as it's on my corporate machine :) Thanks for your work!

**Comment by rbtcollins** [comment]
The candidate fix is merged to master but we still need testing - please do confirm that my test binary fixes the problem. Thank you!

**Comment by kinnison** [comment]
I didn't mean to close this so I'll reopen it until we get an Okay from the OP.

**Comment by Geobert** [comment]
Hi all, I tried twice and it passes twice! Looks good to me! Well done!

**Comment by Geobert** [comment]
Is this supposed to be live? I encounter the issue yesterday while upgrading to 1.37, and then I tried the experimental build above (I kept it) to succeed the update.
EDIT: `rustup --version` gives `rustup 1.18.3 (435397f48 2019-05-22)`

**Comment by refaelsh** [comment]
I have the same problem. Corporate laptop with McAfee that can not be turn off. I need this release in order to start learning rust. Please hurry :-)

**Comment by xiaoaiwhc** [comment]
Same problem. McAfee can't be disabled on my work laptop. It's a big pain when running rustup-update every time.

**Comment by LatteAno** [comment]
Same here. Is there some W/A to try, until there is a fix?

Here's my output:

```
c:\Users\LatteAno\Downloads>rustup install stable
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: latest update on 2019-08-15, rust version 1.37.0 (eae3437df 2019-08-13)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
 60.4 MiB /  60.4 MiB (100 %)  11.6 MiB/s in  5s ETA:  0s
info: installing component 'rust-std'
 56.1 MiB /  56.1 MiB (100 %)  13.7 MiB/s in  4s ETA:  0s
info: installing component 'cargo'
info: installing component 'rust-docs'
 11.3 MiB /  11.3 MiB (100 %) 609.6 KiB/s in 16s ETA:  0s
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: retrying renaming 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: rolling back changes
error: could not rename component file from 'C:\Users\LatteAno\.rustup\tmp\j8py6fkxtxyx4g50_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: caused by: permission denied

c:\Users\LatteAno\Downloads>
```

**Comment by kinnison** [comment]
The latest release should be a bit better, but if McAfee is really being a pain, there's not a lot we can do short-term.

**Comment by Geobert** [comment]
try the build from this comment above: https://github.com/rust-lang/rustup.rs/issues/1870#issuecomment-495840454

**Comment by LatteAno** [comment]
@Geobert and @rbtcollins - [this build](https://github.com/rust-lang/rustup.rs/issues/1870#issuecomment-495840454) doesn't seem to work:

```
C:\Users\LatteAno\Downloads>rustup.exe install stable
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: latest update on 2019-08-15, rust version 1.37.0 (eae3437df 2019-08-13)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
 60.4 MiB /  60.4 MiB (100 %)  11.1 MiB/s in  5s ETA:  0s
info: installing component 'rust-std'
 56.1 MiB /  56.1 MiB (100 %)  11.0 MiB/s in  5s ETA:  0s
info: installing component 'cargo'
info: installing component 'rust-docs'
 11.3 MiB /  11.3 MiB (100 %) 593.6 KiB/s in 50s ETA:  0s
info: rolling back changes
error: could not rename component file from 'C:\Users\LatteAno\.rustup\tmp\blh65tzcm3dwm4wg_dir\rust-docs\share/doc/rust/html' to 'C:\Users\LatteAno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\share/doc/rust/html'
info: caused by: permission denied

C:\Users\LatteAno\Downloads>
```

**Comment by thesobercoder** [comment]
@rbtcollins You're dirty patch version worked on my corporate box. Thanks!
