### ISSUE TITLE
Cannot remove component, but it appears to be there

### ISSUE THREAD

**Issue by cdown** [rust-lang/rustup#1871]
**Problem**

Since rustfmt is now on stable, I wanted to remove it from my nightly toolchain, but despite it appearing in `rustup component list`, it appears not removable (however `clippy` was removed fine in a similar manner):

```
% rustup component list --toolchain nightly | grep rustfmt
rustfmt-x86_64-unknown-linux-gnu
% rustup component remove rustfmt --toolchain nightly                         
error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not contain component 'rustfmt' for target 'x86_64-unknown-linux-gnu'; did you mean 'rust-std'?
```

Using the full name `rustfmt-x86_64-unknown-linux-gnu` also doesn't work with the same message.

**Steps**

Unsure. I've not wanted to mess with the installation too much for fear of losing the repro.

**Notes**

Output of `rustup --version`: `rustup 1.18.3 (2019-05-23)`
Output of `rustup show`:

```
% rustup show
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2018-10-07-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.35.0 (3c235d560 2019-05-20)
```

**Comment by kinnison** [comment]
If the component were installed it'd have `(installed)` after it in the component list.

**Comment by cdown** [comment]
Oh! So this is my misunderstanding then, I thought `rustup component list` only listed installed components. I'll make sure to pass `--installed`. Sorry for the noise! :-)
