### ISSUE TITLE
Errors while compiling objc_exception v0.1.1

### ISSUE THREAD

**Issue by mdadduzio** [rust-lang/rustup#1908]
Hi,

I'm a total noob in the rust/cargo world and no matter how I try to build pathfinder 3, I always get stuck at objc_exception v0.1.1 (please see text dump below). Am I missing something or there's a bug?

Thanks

    Updating crates.io index
    Updating git repository `https://github.com/linebender/skribo.git`
  Downloaded sdl2 v0.32.2
  Downloaded font-kit v0.2.0
  Downloaded log v0.4.6
  Downloaded fixedbitset v0.1.9
  Downloaded image v0.21.1
  Downloaded sdl2-sys v0.32.6
  Downloaded block v0.1.6
  Downloaded harfbuzz-sys v0.3.2
  Downloaded clap v2.33.0
  Downloaded jni v0.11.0
  Downloaded metal v0.14.0
  Downloaded gl v0.6.5
  Downloaded pretty_env_logger v0.3.0
  Downloaded libc v0.2.54
  Downloaded rayon v1.0.3
  Downloaded byteorder v1.3.1
  Downloaded foreign-types v0.3.2
  Downloaded glutin v0.21.0
  Downloaded nfd v0.0.4
  Downloaded arrayvec v0.4.10
  Downloaded smallvec v0.6.9
  Downloaded hashbrown v0.1.8
  Downloaded cocoa v0.18.4
  Downloaded objc v0.2.6
  Downloaded crossbeam-channel v0.3.8
  Downloaded log v0.3.9
  Downloaded euclid v0.19.8
  Downloaded harfbuzz v0.3.1
  Downloaded color-backtrace v0.1.3
  Downloaded image v0.19.0
  Downloaded lyon_path v0.12.0
  Downloaded lazy_static v1.3.0
  Downloaded serde v1.0.91
  Downloaded unicode-normalization v0.1.8
  Downloaded jemallocator v0.1.9
  Downloaded core-foundation v0.6.4
  Downloaded bitflags v1.0.4
  Downloaded egl v0.2.7
  Downloaded serde_json v1.0.39
  Downloaded usvg v0.7.0
  Downloaded serde_derive v1.0.91
  Downloaded freetype v0.4.1
  Downloaded euclid_macros v0.1.0
  Downloaded cfg-if v0.1.7
  Downloaded num-iter v0.1.37
  Downloaded png v0.14.1
  Downloaded num v0.1.42
  Downloaded core-graphics v0.17.3
  Downloaded objc_id v0.1.1
  Downloaded glutin_egl_sys v0.1.3
  Downloaded winit v0.19.1
  Downloaded error-chain v0.12.1
  Downloaded strsim v0.8.0
  Downloaded unicode-width v0.1.5
  Downloaded chrono v0.4.6
  Downloaded crossbeam-utils v0.6.5
  Downloaded scoped_threadpool v0.1.9
  Downloaded dirs v1.0.5
  Downloaded nodrop v0.1.13
  Downloaded lyon_geom v0.12.4
  Downloaded rayon-core v1.4.1
  Downloaded pkg-config v0.3.14
  Downloaded objc-foundation v0.1.1
  Downloaded glutin_glx_sys v0.1.5
  Downloaded cesu8 v1.1.0
  Downloaded jni-sys v0.3.0
  Downloaded term v0.5.2
  Downloaded gcc v0.3.55
  Downloaded png v0.12.0
  Downloaded float-ord v0.2.0
  Downloaded scopeguard v0.3.3
  Downloaded num-rational v0.2.1
  Downloaded foreign-types-shared v0.1.1
  Downloaded objc_exception v0.1.1
  Downloaded khronos v0.1.2
  Downloaded ansi_term v0.11.0
  Downloaded env_logger v0.6.1
  Downloaded jpeg-decoder v0.1.15
  Downloaded memmap v0.6.2
  Downloaded walkdir v2.2.7
  Downloaded crossbeam-deque v0.2.0
  Downloaded cmake v0.1.39
  Downloaded derivative v1.0.2
  Downloaded osmesa-sys v0.1.2
  Downloaded vec_map v0.8.1
  Downloaded jemalloc-sys v0.1.8
  Downloaded rand v0.6.5
  Downloaded textwrap v0.11.0
  Downloaded lzw v0.10.0
  Downloaded gif v0.10.1
  Downloaded num-rational v0.1.42
  Downloaded servo-fontconfig v0.4.0
  Downloaded gl_generator v0.6.1
  Downloaded core-foundation-sys v0.6.2
  Downloaded combine v3.8.1
  Downloaded rustc_version v0.2.3
  Downloaded wayland-client v0.21.12
  Downloaded libloading v0.5.0
  Downloaded atty v0.2.11
  Downloaded either v1.5.2
  Downloaded backtrace v0.3.15
  Downloaded parking_lot v0.7.1
  Downloaded num-derive v0.2.5
  Downloaded num-traits v0.2.6
  Downloaded quote v0.6.12
  Downloaded servo-freetype-sys v4.0.5
  Downloaded cc v1.0.36
  Downloaded crossbeam-utils v0.2.2
  Downloaded inflate v0.4.5
  Downloaded num-integer v0.1.39
  Downloaded rand_core v0.4.0
  Downloaded rand_isaac v0.1.1
  Downloaded wayland-sys v0.21.12
  Downloaded wayland-scanner v0.21.12
  Downloaded backtrace-sys v0.1.28
  Downloaded version_check v0.1.5
  Downloaded memmap v0.7.0
  Downloaded svgdom v0.17.0
  Downloaded time v0.1.42
  Downloaded humantime v1.2.0
  Downloaded khronos_api v2.2.0
  Downloaded rand_chacha v0.1.1
  Downloaded rand_jitter v0.1.4
  Downloaded rand_pcg v0.1.2
  Downloaded crossbeam-epoch v0.3.1
  Downloaded servo-fontconfig-sys v4.0.7
  Downloaded x11-dl v2.18.3
  Downloaded downcast-rs v1.0.4
  Downloaded harfbuzz_rs v1.0.0
  Downloaded fs_extra v1.1.0
  Downloaded libflate v0.1.22
  Downloaded malloc_buf v0.0.6
  Downloaded xml-rs v0.7.0
  Downloaded deflate v0.7.19
  Downloaded rand_xorshift v0.1.1
  Downloaded gl_generator v0.11.0
  Downloaded libc v0.1.12
  Downloaded rustc-demangle v0.1.14
  Downloaded rctree v0.3.2
  Downloaded unicode-vo v0.1.0
  Downloaded proc-macro2 v0.4.30
  Downloaded itoa v0.4.4
  Downloaded rand_os v0.1.3
  Downloaded shared_library v0.1.9
  Downloaded memchr v2.2.0
  Downloaded kurbo v0.2.3
  Downloaded regex v1.1.6
  Downloaded same-file v1.0.4
  Downloaded rand_hc v0.1.0
  Downloaded percent-encoding v1.0.1
  Downloaded base64 v0.10.1
  Downloaded unicode-script v0.3.0
  Downloaded semver v0.9.0
  Downloaded nix v0.13.0
  Downloaded unreachable v1.0.0
  Downloaded termcolor v1.0.4
  Downloaded syn v0.15.34
  Downloaded ascii v0.9.1
  Downloaded ryu v0.2.8
  Downloaded wayland-commons v0.21.12
  Downloaded data-url v0.1.0
  Downloaded smithay-client-toolkit v0.4.5
  Downloaded unicode-bidi v0.3.4
  Downloaded color_quant v1.0.1
  Downloaded num_cpus v1.10.0
  Downloaded autocfg v0.1.2
  Downloaded unicode-xid v0.1.0
  Downloaded khronos_api v3.1.0
  Downloaded xml-rs v0.8.0
  Downloaded matches v0.1.8
  Downloaded roxmltree v0.6.1
  Downloaded regex-syntax v0.6.6
  Downloaded thread_local v0.3.6
  Downloaded rand_core v0.3.1
  Downloaded parking_lot_core v0.4.0
  Downloaded simplecss v0.1.0
  Downloaded svgtypes v0.4.4
  Downloaded semver-parser v0.7.0
  Downloaded memoffset v0.2.1
  Downloaded crc32fast v1.2.0
  Downloaded quick-error v1.2.2
  Downloaded lock_api v0.1.5
  Downloaded wayland-protocols v0.21.12
  Downloaded ttf-parser v0.1.0
  Downloaded dlib v0.4.1
  Downloaded expat-sys v2.1.6
  Downloaded andrew v0.2.1
  Downloaded adler32 v1.0.3
  Downloaded utf8-ranges v1.0.2
  Downloaded slab v0.4.2
  Downloaded owning_ref v0.4.0
  Downloaded void v1.0.2
  Downloaded aho-corasick v0.7.3
  Downloaded phf v0.7.24
  Downloaded line_drawing v0.7.0
  Downloaded xmlparser v0.9.0
  Downloaded float-cmp v0.5.0
  Downloaded ucd-util v0.1.3
  Downloaded rusttype v0.7.6
  Downloaded stable_deref_trait v1.1.1
  Downloaded xdg v2.2.0
  Downloaded phf_shared v0.7.24
  Downloaded approx v0.3.2
  Downloaded stb_truetype v0.2.6
  Downloaded siphasher v0.2.3
  Downloaded ordered-float v1.0.2
   Compiling proc-macro2 v0.4.30
   Compiling num-traits v0.2.6
   Compiling semver-parser v0.7.0
   Compiling unicode-xid v0.1.0
   Compiling cc v1.0.36
   Compiling num-integer v0.1.39
   Compiling syn v0.15.34
   Compiling byteorder v1.3.1
   Compiling pkg-config v0.3.14
   Compiling arrayvec v0.4.10
   Compiling libc v0.2.54
   Compiling num-iter v0.1.37
   Compiling nix v0.13.0
   Compiling adler32 v1.0.3
   Compiling cfg-if v0.1.7
   Compiling khronos_api v2.2.0
   Compiling xml-rs v0.8.0
   Compiling num-rational v0.2.1
   Compiling serde v1.0.91
   Compiling gcc v0.3.55
   Compiling autocfg v0.1.2
   Compiling nodrop v0.1.13
   Compiling rand_core v0.4.0
   Compiling memoffset v0.2.1
   Compiling ryu v0.2.8
   Compiling bitflags v1.0.4
   Compiling core-foundation-sys v0.6.2
   Compiling scopeguard v0.3.3
   Compiling siphasher v0.2.3
   Compiling lazy_static v1.3.0
   Compiling void v1.0.2
   Compiling khronos_api v3.1.0
   Compiling crc32fast v1.2.0
   Compiling lzw v0.10.0
   Compiling memchr v2.2.0
   Compiling smallvec v0.6.9
   Compiling rayon-core v1.4.1
   Compiling rayon v1.0.3
   Compiling foreign-types-shared v0.1.1
   Compiling itoa v0.4.4
   Compiling stable_deref_trait v1.1.1
   Compiling float-cmp v0.5.0
   Compiling downcast-rs v1.0.4
   Compiling same-file v1.0.4
   Compiling xmlparser v0.9.0
   Compiling xdg v2.2.0
   Compiling regex v1.1.6
   Compiling fs_extra v1.1.0
   Compiling matches v0.1.8
   Compiling either v1.5.2
   Compiling simplecss v0.1.0
   Compiling float-ord v0.2.0
   Compiling ucd-util v0.1.3
   Compiling version_check v0.1.5
   Compiling slab v0.4.2
   Compiling rustc-demangle v0.1.14
   Compiling rctree v0.3.2
   Compiling block v0.1.6
   Compiling ttf-parser v0.1.0
   Compiling quick-error v1.2.2
   Compiling fixedbitset v0.1.9
   Compiling unicode-width v0.1.5
   Compiling num-derive v0.2.5
   Compiling unicode-vo v0.1.0
   Compiling unicode-script v0.3.0
   Compiling utf8-ranges v1.0.2
   Compiling percent-encoding v1.0.1
   Compiling libc v0.1.12
   Compiling termcolor v1.0.4
   Compiling ansi_term v0.11.0
   Compiling strsim v0.8.0
   Compiling vec_map v0.8.1
   Compiling ascii v0.9.1
   Compiling sdl2 v0.32.2
   Compiling color_quant v1.0.1
   Compiling cesu8 v1.1.0
   Compiling scoped_threadpool v0.1.9
   Compiling jni-sys v0.3.0
   Compiling crossbeam-utils v0.2.2
   Compiling log v0.4.6
   Compiling sdl2-sys v0.32.6
   Compiling semver v0.9.0
   Compiling inflate v0.4.5
   Compiling xml-rs v0.7.0
   Compiling servo-fontconfig-sys v4.0.7
   Compiling x11-dl v2.18.3
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.5
   Compiling backtrace v0.3.15
   Compiling thread_local v0.3.6
   Compiling crossbeam-utils v0.6.5
   Compiling unreachable v1.0.0
   Compiling phf_shared v0.7.24
   Compiling unicode-normalization v0.1.8
   Compiling foreign-types v0.3.2
   Compiling owning_ref v0.4.0
   Compiling walkdir v2.2.7
   Compiling libloading v0.5.0
   Compiling cmake v0.1.39
   Compiling backtrace-sys v0.1.28
   Compiling data-url v0.1.0
   Compiling unicode-bidi v0.3.4
   Compiling objc_exception v0.1.1
   Compiling nfd v0.0.4
   Compiling jemalloc-sys v0.1.8
   Compiling regex-syntax v0.6.6
   Compiling humantime v1.2.0
   Compiling textwrap v0.11.0
   Compiling roxmltree v0.6.1
   Compiling error-chain v0.12.1
   Compiling khronos v0.1.2
   Compiling gif v0.10.1
   Compiling log v0.3.9
   Compiling rand_isaac v0.1.1
   Compiling rand_xorshift v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rustc_version v0.2.3
   Compiling phf v0.7.24
   Compiling lock_api v0.1.5
   Compiling crossbeam-channel v0.3.8
   Compiling expat-sys v2.1.6
   Compiling servo-freetype-sys v4.0.5
   Compiling harfbuzz-sys v0.3.2
error: failed to run custom build command for `objc_exception v0.1.1`

Caused by:
  process didn't exit successfully: `/home/oem/pathfinder/target/debug/build/objc_exception-67ad5672858f02f9/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-o" "/home/oem/pathfinder/target/debug/build/objc_exception-789a713535eeceb4/out/extern/exception.o" "-c" "extern/exception.m"
cargo:warning=cc: error trying to exec 'cc1obj': execvp: No such file or directory
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-o" "/home/oem/pathfinder/target/debug/build/objc_exception-789a713535eeceb4/out/extern/exception.o" "-c" "extern/exception.m" with args "cc" did not execute successfully (status code exit code: 1).

', /home/oem/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:1672:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by kinnison** [comment]
Hi @mdadduzio 

While this isn't quite the right place to look for help with this sort of thing (Reddit's `/r/rust` or the users forum might be better) I'll see what I can do.

Given the lack of `cc1obj` my guess is that you're missing the objective-C compiler in your installation.  Depending on your Linux distro the package name will differ, but on my computer it's called `gobjc`

I've no idea whether installing that will be sufficient, but it might get you a bit closer.

**Comment by mdadduzio** [comment]
Hi @kinnison ,

thanks very much for your help, I guess you are right and I'll try to install the objective-C compiler (I had no clue from the error messages, now, thanks to your hint, they look more meaningful).
I'm sorry I posted this here, I didn't know it could be the wrong place.
I'll follow your advice and, if can't still sort it out, post a bit more detailed question in the user forum (I don't know where it is, but I'll search for it).

Thank again very much, I'm closing the thread :-)
Mario
