### ISSUE TITLE
toolchain url is printed out with a trailing `.`, so you go to the wrong place

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rustup#1924]
So I ask cargo to give me miri, it says rustup does miri.

I ask rustup to give me miri and it's not available on this particular day so I get the standard message

```
D:\dev\beryllium>rustup component add miri
error: component 'miri' for target 'x86_64-pc-windows-msvc' is unavailable for download for channel 'nightly'
If you require these components, please install and use the latest successful build version,
which you can find at https://rust-lang-nursery.github.io/rust-toolstate.
```

However, I'm in visual studio code so I just ctrl+click that URL to open a browser tab and it'll take me right to the page.

Except, that the `.` on the end of the sentence is detected as being a valid URL character so it gets pulled in to the URL when you use it in visual studio code ctrl+click, so you go to a 404 page.

It's less grammatical in a sense, but can we have that little `.` removed from the message?

**Comment by kinnison** [comment]
This was fixed in #1872 which was merged a little after 1.18.3

We are looking to make a release as soon as our CI problems on Windows are resolved to roll up all our fixes since 1.18.3.  This will be resolved at that point.

Thanks,

D.
