### ISSUE TITLE
Document how to install a default rust toolchain when installing rustup

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rustup#1927]
I'm doing `curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly` but this does not install a nightly toolchain and makes it the default. 

It would be nice if you could document the preferred way of installing rust toolchains for the first time via the CLI non-interactively.

**Comment by kinnison** [comment]
That's odd, I'd have expected that to work -- can you confirm what it does for you?

**Comment by gnzlbg** [comment]
It works. For some reason the PATH wasn't being properly exported, so doing a `rustc --version` afterwards was reporting the `/usr/local` one. Shall I close this ? I would have found it reassuring if this command or similar would be present in the readme.

**Comment by kinnison** [comment]
If you'd like to create a patch for README to resolve this issue then I'd be pleased to review it.  Otherwise this is somewhat of a niche feature with respect to most of our users and so I feel it's well enough understood if you download the script and look at its help.
