### ISSUE TITLE
CLI switch to disable download progress output

### ISSUE THREAD

**Issue by benaryorg** [rust-lang/rustup#1928]
### Describe the problem you are trying to solve

I want to add a new toolchain in a Docker container and suppress the download progress, since that messes with my terminal rather hard.
This applies to every other non-interactive download.

### Describe the solution you'd like

A CLI switch (`-s`/`--silent`: *curl* style, `-q`/`--quiet`: *wget* style) which disables output meant for a terminal.

### Notes

It is possible to workaround this by just piping the output anywhere (`| cat` at the end works fine):

https://github.com/rust-lang/rustup.rs/blob/2ece700231f8a1778647981df94052e5b27cbedf/src/cli/download_tracker.rs#L73

That workaround isn't viable if you have e.g. a *Dockerfile* with `execvp()`-like statements to avoid running in a shell (for the doom it shall bring upon thee).

**Comment by kinnison** [comment]
This ought to be a reasonable intermediate project for someone to undertake.  I am prepared to mentor someone to do the work.

**Comment by PicoJr** [comment]
Here is what I've written so far: <https://github.com/PicoJr/rustup.rs/tree/feat-1928>

Should I submit a PR?

Note: It's my first time contributing to rustup and I'm a rust beginner.

Help appreciated =)

## TODO?

- [ ] write unit test for the `--silent` option
- [ ] add `--quiet` alias

## Unit Tests

I ran `cargo test`, some tests failed with message "error: self-update is disabled for this build of rustup".

**Comment by kinnison** [comment]
My preference is for `--quiet` rather than `--silent` but it looks like you're on your way to a solution.

The error message you mention suggests that you've managed to end up with the no-self-update feature enabled, or else you've got some unusual environment variables set such as `SNAP`.

**Comment by PicoJr** [comment]
Ok, I'll rename the option to `--quiet`.

**Comment by PicoJr** [comment]
I've submitted a PR: #1945

**Comment by pickfire** [comment]
This issue should be solved.
