### ISSUE TITLE
Unable to remove non-native std component

### ISSUE THREAD

**Issue by saghm** [rust-lang/rustup#1941]
**Problem**

When I try to remove a `std` component of a non-native architecture (originally installed for cross-compilation purposes), I get an error saying that the component isn't installed.

Output of `rustup component list --installed`:
```
cargo-x86_64-unknown-linux-gnu
clippy-x86_64-unknown-linux-gnu
rls-x86_64-unknown-linux-gnu
rust-analysis-x86_64-unknown-linux-gnu
rust-docs-x86_64-unknown-linux-gnu
rust-src
rust-std-aarch64-unknown-linux-gnu
rust-std-powerpc-unknown-linux-gnu
rust-std-powerpc64-unknown-linux-gnu
rust-std-s390x-unknown-linux-gnu
rust-std-x86_64-unknown-linux-gnu
rustc-x86_64-unknown-linux-gnu
```

Output of `rustup component remove rust-std-aarch64-unknown-linux-gnu`:
```
error: toolchain 'stable-x86_64-unknown-linux-gnu' does not contain component 'rust-std-aarch64-unknown-linux-gnu' for target 'x86_64-unknown-linux-gnu'
```

Output of `rustup component remove rust-std-aarch64-unknown-linux-gnu --target aarch64-unknown-linux-gnu`:
```
error: toolchain 'stable-x86_64-unknown-linux-gnu' does not contain component 'rust-std-aarch64-unknown-linux-gnu' for target 'aarch64-unknown-linux-gnu'
```

**Steps**
(I haven't had a chance to try this on a fresh rustup installation, so it's possible this won't reproduce the issue)

1. Install the stable toolchain

```
rustup default stable
```

2. Add a `std` component for a non-native architecture (e.g. `rust-std-aarch64-unknown-linux-gnu` on a `x86_64-unknown-linux-gnu` system)

```
rustup component add rust-std-aarch64-unknown-linux-gnu
```

3. Try to remove the component that was just installed

```
rustup component remove rust-std-aarch64-unknown-linux-gnu
```

**Possible Solution(s)**

My uninformed guess is that `rustup component remove` checks that the architecture of the component matches the architecture of the toolchain and exits with an error if it doesn't. While this would be a useful sanity check in most cases (e.g. to ensure that attempting to remove `rls-aarch64-unknown-linux-gnu` doesn't remove `rls` from a `x86_64-unknown-linux-gnu` toolchain), it doesn't make sense for `std` components, as they need to be installed for the system's native toolchain to be able to cross compile.

**Notes**

Caveat: I have rustup installed through the package in the Arch Linux repositories. If we can't reproduce this on upstream rustup, I'll contact the maintainer to try to debug it.

Output of `rustup --version`: rustup 1.18.3 (2019-05-23)
Output of `rustup show`:
```
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

aarch64-unknown-linux-gnu
powerpc-unknown-linux-gnu
powerpc64-unknown-linux-gnu
s390x-unknown-linux-gnu
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.36.0 (a53f9df32 2019-07-03)
```

**Comment by kinnison** [comment]
The `rust-std` for other architectures are treated semi-specially.  They are generally managed via `rustup target` rather than `rustup component`  i.e. `rustup component add rust-std-aarch64-unknown-linux-gnu` should have been `rustup target add aarch64-unknown-linux-gnu`.

I'm not sure if we should make sure we can manage these with `rustup component` entirely; or if we should prevent the use of `rustup component` in the cases where it accidentally works right now.

**Comment by saghm** [comment]
Thanks for the clarification! `rustup target remove aarch64-unknown-linux-gnu` works for me, so my issue is now resolved (although feel free to repurpose this as a tracking issue for any work done on `rustup component` with regards to targets). I'll make sure to use `rustup target` for adding and removing targets in the future!
