### ISSUE TITLE
Logical toolchains per minor release

### ISSUE THREAD

**Issue by mathstuf** [rust-lang/rustup#1942]
**Describe the problem you are trying to solve**

Keeping multiple versions of the toolchain around while updating minor releases easily.

**Describe the solution you'd like**

I'd like to be able to do `rustup toolchain install 1.34` at the release of 1.34.0 and for `rustup update` to get 1.34.2 after it has released. Right now, I have to keep an eye out for minor updates and manually replace the toolchains I have downloaded.

**Comment by kinnison** [comment]
This is an interesting idea, though it would nominally require some extra channel data to be held on `static.rust-lang.org`.  We'll certainly consider it.

**Comment by mathstuf** [comment]
Duplicate of #794.
