### ISSUE TITLE
clippy and rustfmt unavailable on recent Tier 2 builds

### ISSUE THREAD

**Issue by asomers** [rust-lang/rustup#1943]
**Problem**
Recent nightly builds are missing the clippy and rustfmt components for all Tier 2 architectures.  They've been missing since at least july-3-2019, and probably earlier.
https://rust-lang.github.io/rustup-components-history/x86_64-unknown-freebsd.html

**Steps**
1. `rustup update nightly` on a system that already has clippy and rustfmt installed for the nightly toolchain

Output of `rustup --version`:
```
> rustup --version
rustup 1.16.0 (beab5ac2b 2018-12-06)
```
Output of `rustup show`:
```
> rustup show
Default host: x86_64-unknown-freebsd

installed toolchains
--------------------

stable-x86_64-unknown-freebsd (default)
beta-x86_64-unknown-freebsd
nightly-2018-02-09-x86_64-unknown-freebsd
nightly-2018-02-25-x86_64-unknown-freebsd
nightly-2018-06-01-x86_64-unknown-freebsd
nightly-2018-09-06-x86_64-unknown-freebsd
nightly-2018-09-12-x86_64-unknown-freebsd
nightly-2018-09-13-x86_64-unknown-freebsd
nightly-2018-09-14-x86_64-unknown-freebsd
nightly-2018-09-15-x86_64-unknown-freebsd
nightly-2018-09-18-x86_64-unknown-freebsd
nightly-2018-10-01-x86_64-unknown-freebsd
nightly-2018-10-15-x86_64-unknown-freebsd
nightly-2018-11-28-x86_64-unknown-freebsd
nightly-2019-04-21-x86_64-unknown-freebsd
nightly-2019-04-26-x86_64-unknown-freebsd
nightly-2019-04-28-x86_64-unknown-freebsd
nightly-2019-04-30-x86_64-unknown-freebsd
nightly-x86_64-unknown-freebsd
stage1
1.20.0-x86_64-unknown-freebsd
1.25.0-x86_64-unknown-freebsd
1.31.0-x86_64-unknown-freebsd
1.32.0-x86_64-unknown-freebsd
1.35.0-x86_64-unknown-freebsd

active toolchain
----------------

stable-x86_64-unknown-freebsd (default)
rustc 1.33.0 (2aa4c46cf 2019-02-28)
```

**Comment by rbtcollins** [comment]
Hi, this really isn't a rustup issue - rustup deals with installing what has been built, not with getting it built - you'll need to talk with the clippy and rustfmt teams about their builds - I don't think we can directly help you here

**Comment by kinnison** [comment]
This is not a direct thing we can deal with -- we have ongoing work which will ameliorate, though not solve, this situation.

As Robert says, `rustup` is only able to offer access to that which has been built.  Sadly Tier 2 platforms lack sufficient support within the teams to promote to Tier 1, but even Tier 1 sometimes doesn't have clippy/rustfmt/whatever in nightly.

**Comment by asomers** [comment]
Sorry for the spam.  Issue reopened at https://github.com/rust-lang/rust/issues/62558 .
