### ISSUE TITLE
Incorrect detection on Debian/Buster

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rustup#1946]
I set about installing `rustup` onto a Debian/buster system and saw the following:

```shell
somniloquy% curl https://sh.rustup.rs/ | sh                                    
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10652  100 10652    0     0  60522      0 --:--:-- --:--:-- --:--:-- 60522
info: downloading installer
Warning: Detected OS X platform older than 10.13
Warning: Not forcing TLS v1.2, this is potentially less secure

Welcome to Rust!

This will download and install the official compiler for the Rust programming 
language, and its package manager, Cargo.
…
```

Seems we're incorrectly identifying Debian as OS-X somehow?

**Comment by Rudi3** [comment]
Is it possible that you have an alias or similar to `sw_vers`?
What is the output of `command -v sw_vers`? (https://github.com/rust-lang/rustup.rs/blob/9864b0b95e98ccdbe5bde3c5bded2dd95b9d18ad/rustup-init.sh#L410)
To eliminate that, actually using the `_arch` variable from `get_architecture` to check for darwin may work. I can't test this on darwin, but I might do a PR to fix that soon.

**Comment by kinnison** [comment]
> Is it possible that you have an alias or similar to `sw_vers`?

Looks like I had somehow gained a fake `sw_vers` on my path, possibly for testing something meant for Darwin.  This bug is not a bug.  Well spotted.
