### ISSUE TITLE
Nightly unavailable on FreeBSD: clippy, rustfmt and rls

### ISSUE THREAD

**Issue by dancrossnyc** [rust-lang/rustup#1949]
Apologies if this isn't the correct place to post this issue....

I haven't been able to update nightly on FreeBSD for a while due to the unavailability of rustfmt, clippy and rls: it'd be awesome if miri built, as well. :-) It's been about two months since the last successful update. I'm not sure if some automated process somewhere needs a nudge? Thanks!

**Comment by cjburkey01** [comment]
Same for Windows

**Comment by kinnison** [comment]
Nightly makes no guarantees about all the components or indeed architectures being available in any given nightly release.  If you're having problems with particular platforms or components, then looking to see if those component/platform teams could use help is the best thing you can do.  There's nothing `rustup` itself can do to make it more likely that these components are available nightly-to-nightly.  Sorry.

**Comment by iquiw** [comment]
The problem seems to exist in Rust v1.37 on FreeBSD and NetBSD. Should I open new issue?

**Comment by iquiw** [comment]
```console
vagrant@freebsd:~ % rustup component list --toolchain 1.36.0 | grep rls
rls-x86_64-unknown-freebsd
```
```console
vagrant@freebsd:~ % rustup component list --toolchain 1.37.0 | grep rls
vagrant@freebsd:~ %
```

**Comment by kinnison** [comment]
@iquiw If you want to open an issue on *rust* not here on *rustup* then sure.  This kind of component issue is not rustup's domain of concern since those platforms are not tier one and thus there's no guarantee they'll be available anyway.

**Comment by iquiw** [comment]
@kinnison OK, thanks.

I have another problem about `rustup` itself. Its latest version is still 1.11.0 on NetBSD. I will open a new issue.

**Comment by iquiw** [comment]
For the record, the original issue seems already reported.

https://github.com/rust-lang/rust/issues/62558
