### ISSUE TITLE
Don't show backtrace for errors when RUST_BACKTRACE is set

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rustup#1956]
**Describe the problem you are trying to solve**

I have `RUST_BACKTRACE` set globally, because I always want to get backtraces when for example rustc or my own program panics. However I don't need any backtraces for simple errors, like for running `rustup component add rls --toolchain nightly` when rls is not available for the latest nightly.

**Describe the solution you'd like**

Don't show baktraces for erros when `RUST_BACKTRACE` is set. Maybe use `RUSTUP_BACKTRACE` instead or `RUST_LOG=err`.

**Notes**

**Comment by kinnison** [comment]
AIUI, `RUST_BACKTRACE=1` is something handled by the standard library and not something we can directly control.  If I'm wrong, I'd love to see a patch to do this.

**Comment by bjorn3** [comment]
These errors are printed in

https://github.com/rust-lang/rustup.rs/blob/c104e3b6b9de4a092dd132efcc08263d5a62b8d6/src/cli/common.rs#L522-L551

I just noticed that those backtraces are shown too when `-v` is passed. Should I make that the only trigger for backtraces? Or should I add one of the env vars I mentioned in the issue description as trigger too?

**Comment by kinnison** [comment]
Oh right you mean non-panic traces. Sorry, I was confused.  Yeah, you could make `show_backtrace()` conditional on something like `RUSTUP_BACKTRACE=1` if you want.  Be sure to update the README and/or CONTRIBUTING guide appropriately too though.

**Comment by rbtcollins** [comment]
I'd really rather not muck with this in this context.... developing on rustup right now is precisely like developing on every other bit of rust, but if lots of things get written in rust should we expect bugs filed on ls, and find and so on, saying that they shouldn't use RUST_BACKTRACE as their give-a-backtrace variable?

Basically I see this as an ecosystem problem. Either its appropriate to use a single variable, in which case great, or its not, in which case noone should be using RUST_BACKTRACE, and we should *all* change.

**Comment by rbtcollins** [comment]
(Thats my purely selfish perspective). Now - for meeting your needs - how about a variable to suppress rustup backtraces entirely, like RUSTUP_NO_BACKTRACE=1, which you could set and forget, and we could even much with the stdlib if needed to force it to not do traces etc.

**Comment by bjorn3** [comment]
> how about a variable to suppress rustup backtraces entirely

+1
