### ISSUE TITLE
Use rust-toolchain file to specify 32 or 64 bit

### ISSUE THREAD

**Issue by Adarma** [rust-lang/rustup#1959]
**Describe the problem you are trying to solve**

I am using Windows 7 x64, but need to compile a dll for hooking 32bit applications.
I installed the `stable-i686-pc-windows-msvc` toolchain for this.
To use it, I run `cargo +stable-i686-pc-windows-msvc run`.
It works.

The problem is that after some time, I returned to this code and spent a good while trying to figure out why the dll was no longer working. I was running `cargo run` as usual for other projects, having forgotten that this was a special case requiring the toolchain to be specified. It was compiling a 64bit dll which can't be used to hook 32bit applications.

After some unnecessary debugging, I remembered I needed to specify the toolcahin and then had to look up how to do it again. I thought there must be a way to define the toolchain.

I discovered that a `rust-toolchain` file could be used and version controlled, but unfortunately it can't specify compiling to 32bit on a 64bit machine, only the release channel.

My concern is that in future I will go through this all again.

**Describe the solution you'd like**

Provide a way to define the toolchain to be used by `cargo run` in one of

- cargo.toml
- rust-toolchain
- some other file

**Comment by kinnison** [comment]
The toolchain specification is more meant for the host.  Better to use the native host toolchain but target the other architecture if you can.  For example, by setting in `.cargo/config`

```toml
[build]
target = "i686-pc-windows-msvc"
```

Is there a good reason this is not what you want to do?

**Comment by Adarma** [comment]
I was not aware of `.cargo/config`.
Wouldn't that setting be for the whole system, and not just for one project?

**Comment by kinnison** [comment]
Aha, I meant to set it in the project directory.  Just like you would have `rust-toolchain`.  So `...path/to/project/.cargo/config` instead of `...path/to/project/rust-toolchain`

**Comment by Adarma** [comment]
I added the config file as you described, but I get the following error:

```
> cargo run
   Compiling winapi v0.3.7
error[E0463]: can't find crate for `core`
  |
  = note: the `i686-pc-windows-msvc` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `winapi`.

To learn more, run the command again with --verbose.
```

It says the target *may* not be installed.
I think it is:

```
> rustup show
Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

stable-i686-pc-windows-msvc
stable-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.36.0 (a53f9df32 2019-07-03)
```

Since `cargo +stable-i686-pc-windows-msvc run` works, I tried adding the `stable-` prefix, changing the config to:

```
[build]
target = "stable-i686-pc-windows-msvc"
```

I then get this error:

```
> cargo run
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --target stable-i686-pc-windows-msvc --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro` (exit code: 1)
--- stderr
error: Error loading target specification: Could not find specification for target "stable-i686-pc-windows-msvc"
  |
  = help: Use `--print target-list` for a list of built-in targets
```

I don't fully understand the target triple stuff and which bits can or should be implied.
Can you spot what is wrong?

**Comment by kinnison** [comment]
You need to add the i686 target to your x86_64 toolchain with: `rustup target add i686-pc-windows-msvc`  The cross-build targets have to be added individually to the toolchain being used.

**Comment by Adarma** [comment]
Ah, thanks. It is working now.
I was mixing up toolchains and targets.
 I guess I don't need the 'stable-i686-pc-windows-msvc' toolchain installed by doing it this way.

**Comment by kinnison** [comment]
Indeed, glad things are working for you.  I'm going to close this issue now because what you originally asked for doesn't make sense for `rust-toolchain` since we don't want to control the toolchain itself but rather the build target.

**Comment by 0xNullByte** [comment]
**thank you a lot , it's work with me by following this steps :**

1.   - `` rustup target add i686-pc-windows-msvc ``
2. - `` cargo run --target=i686-pc-windows-msvc ``
3.  - and i got folder name : ``hello_world\target\i686-pc-windows-msvc\debug\hello_world.exe`` * 32bit *

**Comment by brandonros** [comment]
```toml
[toolchain]
channel = "nightly"
targets = ["i686-pc-windows-msvc"]
```

why doesn't this work in rust-toolchain.toml?

```
cargo build
   Compiling nexustk-rs v0.0.1 (C:\Users\Brandon\Desktop\nexustk-logger)
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> src/lib.rs:52:70
   |
52 |     let client_cryptOutgoingPacket: FnCryptOutgoingPacket = unsafe { std::mem::transmute(0x00576660) }; // 2022-06-07: 752 client
   |                                                                      ^^^^^^^^^^^^^^^^^^^
   |
   = note: source type: `i32` (32 bits)
   = note: target type: `unsafe extern "thiscall" fn(*const std::ffi::c_void, *const u8, u16)` (64 bits)

error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> src/lib.rs:56:70
   |
56 |     let client_cryptIncomingPacket: FnCryptIncomingPacket = unsafe { std::mem::transmute(0x00578b20) }; // 2022-06-07: 752 client
   |                                                                      ^^^^^^^^^^^^^^^^^^^
   |
   = note: source type: `i32` (32 bits)
   = note: target type: `unsafe extern "stdcall" fn(*const u8, usize, *const u8, usize) -> usize` (64 bits)

error[E0570]: `"thiscall"` is not a supported ABI for the current target
  --> src/lib.rs:10:1
   |
10 | / static_detour! {
11 | |   static CryptIncomingPacketHook: unsafe extern "stdcall" fn(*const u8, usize, *const u8, usize) -> usize;
12 | |   static CryptOutgoingPacketHook: unsafe extern "thiscall" fn(*const c_void, *const u8, u16);
13 | | }
   | |_^
   |
   = note: this error originates in the macro `static_detour` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0512, E0570.
For more information about an error, try `rustc --explain E0512`.
error: could not compile `nexustk-rs` due to 3 previous errors
```
