### ISSUE TITLE
Running `cargo test` for Rustup requires a lot of space

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rustup#1960]
**Problem**
Running `cargo test` requires at least 10GB of disk space. (Don't know how much exactly, as I ran out of space)

**Steps**

1. Run `cargo test`
2. Notice that the `target` dir is more than `10GB` big.

**Notes**
```bash
$ git rev-parse HEAD
b9c6a69a2d605f26b64b4fadb9d074f29a16dba6
```

**Comment by rbtcollins** [comment]
I think we're leaking test dirs.
```
ls target/tests
rustup05JLyA
...
rustup-custom5pRCJu
...
rustup-distif002T
...
rustup-emptyR6UrNb
...
rustup-home0fCojb
...
```

far in excess of our test parallelism.

$ du -lsh target
162G    target
$ du -sh target
29G     target

**Comment by kinnison** [comment]
Yes, we leak dirs in `target/tests` but removing that is quite permissible between runs.  I think what we're leaking is the dist trees of the fake servers.

For reference though, my `target` dir is only 6G and my `target/tests` is only 48M, so something odd is happening for you two perhaps?

**Comment by kinnison** [comment]
I can't speak to the space usage in `~/.cargo` but `target/` now maxes out around 3.75G which is hopefully good enough.

**Comment by bjorn3** [comment]
3.75GB is still a lot, but it is much better.

**Comment by kinnison** [comment]
It's a lot, but not beyond the pale.  I'm going to close this now, since it's no longer > 100G :D
