### ISSUE TITLE
rustup-init no longer updates nightly installations.

### ISSUE THREAD

**Issue by BanzaiMan** [rust-lang/rustup#1964]
**Problem**

rustup-init no longer updates nightly installations.

**Steps**

1. Run `curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -x -s -- --default-toolchain=nightly -y`
2. Set up `$PATH`: `source $HOME/.cargo/env`
3. Confirm that the version is reasonable: `rustc --version`
4. Wait a day (so that a new nightly build is available).
5. Run `curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -x -s -- --default-toolchain=nightly -y` again
6. We expect the installation to be updated, but it is not. What you see is:
<details>
<pre>
info: updating existing rustup installation
Rust is installed now. Great!

To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH 
environment variable. Next time you log in this will be done automatically.
</pre>
</details>

This appears to have started some time around June 25. I've given more details, if anyone is interested, in https://travis-ci.community/t/ci-using-one-month-old-version-of-rust-nightly/4502/5?u=banzaiman

**Possible Solution(s)**

**Notes**

Output of `rustup --version`:

```sh-session
$ rustc --version
rustc 1.38.0-nightly (b0e40bfba 2019-08-02)
```
Output of `rustup show`:
```sh-session
$ rustup show
Default host: x86_64-unknown-linux-gnu

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.38.0-nightly (b0e40bfba 2019-08-02)
```

**Comment by kinnison** [comment]
That is exactly what I'd expect to see.  Rustup-init will detect the existing toolchain and will not update it.  You'll note it *did* update rustup itself, but not the channels.

I'd expect that you probably want to add a `rustup update` to the end of your installation command.

**Comment by BanzaiMan** [comment]
@kinnison So, the previous behavior was wrong?

**Comment by 95th** [comment]
@kinnison Is there any update on this issue please?

**Comment by tesuji** [comment]
I think Daniel answered the question. What else do you expect by the way?

**Comment by kinnison** [comment]
The previous behaviour?  If you mean Travis' previous behaviour then it was working as intended all along.  I believe Travis now caches the `RUSTUP_HOME` which means that you will need to explicitly do a `rustup update` at the end of the install.
