### ISSUE TITLE
Can't install lldb-preview on macOS

### ISSUE THREAD

**Issue by ncihnegn** [rust-lang/rustup#1968]
**Problem**

lldb-preview component has been missing for a while.
**Steps**

1. rustup component add lldb-preview
2.
3.

**Possible Solution(s)**

**Notes**

Output of `rustup --version`:
Output of `rustup show`:

**Comment by srinivasreddy** [comment]
I have done it successfully, not sure what is happening on your system.
```
~ rustup component add lldb-preview

info: downloading component 'lldb-preview'
 10.0 MiB /  10.0 MiB (100 %)   3.1 MiB/s in  3s ETA:  0s
info: installing component 'lldb-preview'
```

```
➜  ~ uname -a
Darwin Srinivass-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```

**Comment by mati865** [comment]
`lldb-preview` is no longer available in nightly builds.

**Comment by kinnison** [comment]
This is not an issue in `rustup`
