### ISSUE TITLE
[feature] Allow to ignore rust-toolchain file

### ISSUE THREAD

**Issue by DoumanAsh** [rust-lang/rustup#1969]
**Describe the problem you are trying to solve**
I want to avoid needless downloads of toolchains

**Describe the solution you'd like**
Having any way to specify option to ignore `rust-toolchain` file

**Comment by kinnison** [comment]
You can override the `rust-toolchain` file with a directory override `rustup override set --path $somepath $toolchain` or by means of the `RUSTUP_TOOLCHAIN` environment variable.  What more do you want?

**Comment by DoumanAsh** [comment]
Can I set `RUSTUP_TOOLCHAIN` so that it would always use default one in my installation?

**Comment by kinnison** [comment]
You can set it to whatever toolchain you want, so long as it's in your environment then it will override all but an explicit toolchain invocation e.g. of the form `cargo +sometoolchain build`

You can see all about the override ordering in https://github.com/rust-lang/rustup.rs#override-precedence

**Comment by DoumanAsh** [comment]
Yeah which would mean that I would need to change it each time I need to change default toolchain in rustup, which may not be always easy to remember

**Comment by kinnison** [comment]
If you wanted a mechanism to correct this behaviour for yourself, what would the ideal solution look like to you? (i.e. how would you *use* such an override?)

**Comment by DoumanAsh** [comment]
I guess ideally I'd like to be able to set `default` which would default toolchain set in rustup.

The one returned by `rustup default` and marked with suffix `(default)`

From what I can see in source code, currently it expects only channel or concrete version.
I'm not sure how well it would fit to add `default` option

**Comment by kinnison** [comment]
So you'd like rustup to recognise some special toolchain token (e.g. `default`) to mean the default toolchain which rustup would have otherwise picked, were no override present?

**Comment by DoumanAsh** [comment]
I guess, though it does sound kinda hacky to be honest.
I just wish there would be a way to disable overrides globally, but the way it looks with current override way it is just not possible without doing some magical `default` channel

**Comment by kinnison** [comment]
This issue is about a situation which Rustup is really not designed to support.  I'm going to close this issue but if you have further ideas for a viable UX for this, please reopen it, or file a fresh one as a feature request.
