### ISSUE TITLE
x86_64-unknown-linux-musl rustup-init links to dead page

### ISSUE THREAD

**Issue by TimDiekmann** [rust-lang/rustup#1981]
**Problem**
Downloading `rustup-init` for `x86_64-unknown-linux-musl` results in a [dead link](https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-musl/rustup-init).

**Steps**
1. Go to [rustup.rs](https://rustup.rs/)
2. click on [other installation options](https://github.com/rust-lang/rustup.rs/#other-installation-methods)
3. Try to download [x86_64-unknown-linux-musl](https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-musl/rustup-init)

**Comment by tesuji** [comment]
`x86_64-unknown-linux-musl` build file was merged recently but it is not released yet.
But @kinnison will cut a release soon, I believe.

**Comment by kinnison** [comment]
@TimDiekmann the MUSL release is not yet official I think.  That link is, irritatingly, a little over-eager :-D

As @lzutao says, I hope to cut a release soon, so it ought to be fixed then.

**Comment by kinnison** [comment]
Assigned to myself so I remember to update after the release

**Comment by TimDiekmann** [comment]
Seems to work now with the new release, thanks!
