### ISSUE TITLE
how to install  1.35 version cargo

### ISSUE THREAD

**Issue by xjxty20140321** [rust-lang/rustup#1985]
how to install  1.35 version cargo

**Comment by xjxty20140321** [comment]
After installation by method "curl https://sh.rustup.rs -sSf | sh", the cargo version is 1.37.How can I install 1.35 cargo

**Comment by kinnison** [comment]
If you want rust 1.35 then you can `rustup install 1.35.0` and that will give you an installation of that toolchain.  You can then do `cargo +1.35.0 build` or similar.

**Comment by xjxty20140321** [comment]
problem was solved ,Thank you for answering my question.
