### ISSUE TITLE
Downloaded rustup-init traps

### ISSUE THREAD

**Issue by nabijaczleweli** [rust-lang/rustup#1989]
**Problem**
When running `rustup-init.sh`, the script downloads `rustup-init`, then traps on execution

![Screen shot](https://user-images.githubusercontent.com/6709544/64618203-192c9d00-d3e0-11e9-9e96-b0086d9c82fd.png)

**Steps**

1. Download the script from `http://sh.rustup.rs/` to `rustup-init.sh`
2. `chmod +x rustup-init.sh`
3. `./rustup-init.sh`

**Possible Solution(s)**

**Notes**

The script says it's a "rustup-init 1.19.0 (a1f78334e 2019-09-07)"

The machine in question is a [Toshiba Satellite 1200-S121](http://cdgenp01.csd.toshiba.com/content/product/pdf_files/detailed_specs/satellite_1200s121.pdf)

**Comment by kinnison** [comment]
That is quite an old laptop (2002 era CPU) and I fear it's possible that Rust expects newer CPU features than that can provide.  I'm not sure where there'd be a list of what features Rust compilers expect these days when we target 'i686' but I do know that the binary works on newer CPUs in 32bit mode, so I don't think it's a corrupt binary.

Were you able to run rust binaries before on that system?

**Comment by shepmaster** [comment]
> that Rust expects newer CPU features than that can provide

@nabijaczleweli are you able to run the current version of Firefox on that machine? That might be a good test for whether it's possible to target that CPU at all.

**Comment by nabijaczleweli** [comment]
I compiled and built a crate on a VM with the same disk image as the laptop, yielding this:
![http trap](https://user-images.githubusercontent.com/6709544/64635005-e9d95880-d3fe-11e9-96ea-a2e72a6a4c8b.png)

Running `firefox/firefox` from the "firefox-69.0.tar.bz2" file I obtained after clicking the "Linux 32-bit" link on the download page:
![firefox abort](https://user-images.githubusercontent.com/6709544/64635159-518fa380-d3ff-11e9-97ac-619a5bae2e67.png)

Does that mean that Rust just doesn't support this platform?

**Comment by nabijaczleweli** [comment]
Also here's the `lscpu` output for reference:
![lscpu](https://user-images.githubusercontent.com/6709544/64635915-ed6ddf00-d400-11e9-8877-822bfc35984a.png)

**Comment by kinnison** [comment]
I imagine that at least some of our sub-crates might expect SSE2 to be available.  Regular expressions might use those instructions; ditto anything to do with SSL.  I'm not convinced we could usefully build `rustup` for such an old CPU; but if you can find a way, I'd be happy to help you with any rustup-specific issues.

**Comment by 15632628358** [comment]
eweretr


------------------ 原始邮件 ------------------
发件人: "Daniel Silverstone"<notifications@github.com>;
发送时间: 2019年9月11日(星期三) 下午3:39
收件人: "rust-lang/rustup.rs"<rustup.rs@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [rust-lang/rustup.rs] Downloaded rustup-init traps (#1989)




I imagine that at least some of our sub-crates might expect SSE2 to be available.  Regular expressions might use those instructions; ditto anything to do with SSL.  I'm not convinced we could usefully build rustup for such an old CPU; but if you can find a way, I'd be happy to help you with any rustup-specific issues.

**Comment by kinnison** [comment]
On the basis that this is a limitation of Rust vs. the older CPU in question in this issue, I'm going to close this.  If Rust (and our dependencies) gains support for coping with these CPUs in the future, we'll gain support in Rustup automatically.
