### ISSUE TITLE
Removing previous version of component message does not appear when updating

### ISSUE THREAD

**Issue by thedrow** [rust-lang/rustup#1993]
**Problem**

#1283 introduced a new message that is printed to the screen whenever we replace a component with a new one.

However, when running `rustup update` the `info: removing component` message still appears instead of `info: removing old component`.

Strangely enough, the [relevant tests pass](https://github.com/rust-lang/rustup.rs/pull/1639/files#diff-5bc536e3b333bb85e5fb398d8c29ec63R52). 

**Steps**

1. rustup update

**Possible Solution(s)**

It is possible that the patch in #1639 has overlooked some minor detail.
We should inspect it and see what we missed.

**Notes**

Output of `rustup --version`: rustup 1.19.0 (2af131cf9 2019-09-08)
Output of `rustup show`:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/omer/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2019-04-12-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.39.0-nightly (eb48d6bde 2019-09-12)
```

**Comment by kinnison** [comment]
I agree that this is irritating, If anyone wants to work on this, I'd be happy to mentor either via this issue or on our Discord.  If you want to take on the work, please ensure you state such on this issue so that others don't also try and take it on.

**Comment by BeniCheni** [comment]
Friendly note that I'm interested in looking into this issue. Just joined Discord.

Gone through the details in this issue & its related previous issue & PR to get started. Will ask in #wg-rustup channel, if any further question.
