### ISSUE TITLE
Could not update stable from 1.26 to 1.37

### ISSUE THREAD

**Issue by drager** [rust-lang/rustup#1999]
**Problem**
Running `rustup update` fails with the following error:

```
error: could not rename component file from '/home/drager/.rustup/tmp/f48vy8ldtsqya7e9_dir/bk' to '/home/drager/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/man'
error: could not rename component file from '/home/drager/.rustup/tmp/q5yd5jzxjxb8lfch_dir/bk' to '/home/drager/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/etc'
error: could not rename component file from '/home/drager/.rustup/tmp/g132dwcck9azh797_dir/bk' to '/home/drager/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/zsh'
error: failed to install component: 'rust-src', detected conflict: '"lib/rustlib/src/rust/src/build_helper/Cargo.toml"'
```

**Steps**
1. Run `rustup update`

**Notes**
OS: Ubuntu 18.04
Output of `rustup --version`: `rustup 1.19.0 (2af131cf9 2019-09-08)`
Output of `rustup show`:

Default host: x86_64-unknown-linux-gnu
rustup home:  /home/drager/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
beta-x86_64-unknown-linux-gnu
nightly-2017-11-07-x86_64-unknown-linux-gnu
nightly-2017-11-08-x86_64-unknown-linux-gnu
nightly-2017-11-30-x86_64-unknown-linux-gnu
nightly-2017-12-01-x86_64-unknown-linux-gnu
nightly-2017-12-23-x86_64-unknown-linux-gnu
nightly-2018-04-18-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.26.0 (a77568041 2018-05-07)

**Comment by kinnison** [comment]
I have attempted to replicate this and failed.  This leads me to believe this is an instance of rustup losing some or all of the component file manifests for the old version.  Removing the toolchain and reinstalling the channel will solve this, though it's not ideal.

**Comment by drager** [comment]
Yeah, removed the channel and added it again worked. Thanks!
