### ISSUE TITLE
rustup should also skip the day which is no release when updating nightly

### ISSUE THREAD

**Issue by DanSnow** [rust-lang/rustup#2001]
**Problem**
I'm using version `rustup 1.19.0+16 (279e802a0 2019-09-17)`.
With `clippy` installed,  `rustup update nightly` should do backtrace and found a viable version at `2019-09-13`.  But as showing in [`componets history`](https://rust-lang.github.io/rustup-components-history/), there is no release at `2019-09-17`. Then `rustup` fail with  `componet unavailable`.

![image](https://user-images.githubusercontent.com/5575082/65115382-587b6f00-da1a-11e9-9f64-531e355d1a56.png)

**Steps**

1. Clone and install from current master (279e802a0ad4a9eafd89b3740c87d7f58642439d)
2. Run `rustup update nightly`

**Possible Solution(s)**
 
I have add a `dbg!` and it show me this when check `2019-09-17`:

```plain
[src/dist/dist.rs:623] &e = Error(
    Msg(
        "no release found for \'nightly-2019-09-17\'",
    ),
    State {
        next_error: None,
        backtrace: InternalBacktrace {
            backtrace: None,
        },
    },
)
```

I think we should add a specific error for `no release` and also skip it when doing backtrace.

**Notes**

Output of `rustup --version`: `rustup 1.19.0+16 (279e802a0 2019-09-17)`
Output of `rustup show`:

**Comment by kinnison** [comment]
Hmm, we *thought* this would be coped with but clearly it's not.  @jonhoo Do you think, given we have a recent nightly which is missing, that you can solve this?

**Comment by jonhoo** [comment]
Good catch! Fixed in https://github.com/rust-lang/rustup.rs/pull/2002
