### ISSUE TITLE
Support selecting additional components (and targets) at install time

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rustup#2005]
When installing a toolchain, it might be nice to select additional components to install such that they will be immediately available.

For example, editors might auto-install toolchains if needed, and request `rls` `rust-analyzer` `rust-src` etc. without having to override the chosen profile from the user.

In addition, if you know you're going to need a particular target, it'd be nice to preinstall with that too (e.g. if I download some embedded code and know I'll need the `thumbv6m-none-eabi` target)

Perhaps something like:

`rustup toolchain install nightly -c rls -c clippy -t thumbv6m-none-eabi`

**Comment by jonhoo** [comment]
Note to self to re-enable `clippy` in https://github.com/crate-ci/azure-pipelines/pull/59 once this lands.

**Comment by kinnison** [comment]
This has landed and is in 1.20
