### ISSUE TITLE
BitTorrent support

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/rustup#2006]
**Describe the problem you are trying to solve**

Bandwidth is expensive and rustup can't saturate my links. I'd like to see BitTorrent support to be able to take full advantage of my links.

**Describe the solution you'd like**

BitTorrent makes everything cheaper and better.

**Notes**

**Comment by kinnison** [comment]
Thank you for your suggestion.  This was raised as part of #1798 so please take further discussion of bittorrent as a distribution mechanism to there.
