### ISSUE TITLE
Missing components for channel stable

### ISSUE THREAD

**Issue by dallenng** [rust-lang/rustup#2007]
**Problem**

I switched to rustup git to test the profile feature and already had stable and nightly toolchains. I removed both toolchains, then set profile to complete and when I try to install stable toolchain I get this error:
```
error: some components unavailable for download for channel stable: 'lldb-preview', 'miri'
If you require these components, please install and use the latest successful build version,
which you can find at <https://rust-lang.github.io/rustup-components-history>.

After determining the correct date, install it with a command such as:

    rustup toolchain install nightly-2018-12-27

Then you can use the toolchain with commands such as:

    cargo +nightly-2018-12-27 build
```

**Steps**

1. Install rustup from git
2. Uninstall stable toolchain
3. Set profile to complete
4. Install stable toolchain

**Possible Solution(s)**

I think the problem is that the components available for the stable toolchain are not the same as the ones available for nightly

**Notes**

Output of `rustup --version`: rustup 1.19.0+19 (6f93cdc00 2019-09-18)
Output of `rustup show`:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/dallenng/.rustup

(error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed, not a directory: '/home/dallenng/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu')
```

**Comment by kinnison** [comment]
The profile content is supplied by the channel manifest.  This is set in https://github.com/rust-lang/rust/blob/528379121ceb5fca5382b4337be7ac064890ec8c/src/tools/build-manifest/src/main.rs#L414 which looks like it probably has always been a static selection.  Sadly I fear not everything in that collection may be appropriate for all channels at all times.

**Comment by kinnison** [comment]
That code appears to have originated in this commit: https://github.com/rust-lang/rust/commit/4103e5b34bcd5fff13afe79494d6955d7996c804 which means @nrc was at least originally responsible for the component choice there.  We may need to consider if regenerating old manifests to clean up profiles will become worthwhile.

**Comment by nrc** [comment]
The complete profile just uses everything available. A stop-gap solution might be to limit complete profile to nightly.

**Comment by kinnison** [comment]
> The complete profile just uses everything available. A stop-gap solution might be to limit complete profile to nightly.

Is the `complete` profile likely to ever work on nightly more than in the few days leading up to a beta ?  If not, it might make more sense to choose a subset, or else when generating a *stable* manifest, make sure we filter the profiles based on at least one platform actually having the stuff available?

**Comment by Mazwak** [comment]
I have this problem with latest release (1.20.1).

Uninstall stable, set profile to complete.
Try to install stable, and it fails.

```
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: latest update on 2019-09-26, rust version 1.38.0 (625451e37 2019-09-23)
error: some components unavailable for download for channel stable: 'lldb-preview', 'miri'
```

**Comment by mati865** [comment]
To expand comment above, `lldb-preview` is not available for any platform and `miri` is only available for nightly builds. This is very unlikely to change in foreseeable future.

**Comment by kinnison** [comment]
You may need to uninstall the toolchain, upgrade to 1.20.2 (just released) and reinstall the toolchain.  You can use --force to cause it to skip components it can't find, but `complete` is definitely not useful for stable.

**Comment by kinnison** [comment]
I consider this issue closed as far as `rustup` is concerned.  There's potential reason to open an issue on `rust-lang/rust` about the `complete` profile contents, but that's not `rustup`'s decision.
