### ISSUE TITLE
Rustup update stable doesn't work

### ISSUE THREAD

**Issue by tensor-programming** [rust-lang/rustup#2032]
**Problem**

Using `rustup install stable` didn't work for me on MSVC.  Latest version that I had was 1.37 and couldn't update to 1.38.  Executing the command produced: 
```
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
stable-x86_64-pc-windows-msvc unchanged - rustc 1.37.0 (eae3437df 2019-08-13)
`info: checking for self-updates`
``` 
On the other hand both nightly and beta worked fine. 

Also should mention that stable gnu update worked perfectly fine on WSL. 

Ultimately, had to resolve the problem by uninstalling stable and reinstalling it via `rustup uninstall stable` and `rustup install stable`

**Steps**

1. `rustup update stable` on MSVC

**Comment by kinnison** [comment]
That is fascinating but I am unable to reproduce it.  Did you keep a copy of the toolchain which wouldn't update?

**Comment by tensor-programming** [comment]
I did some research and found that the problem had something to do with the insider update that proceeded it.  Not only was Rustup failing, my installation of Go failed, Elixir IEX wouldn't work, and a bunch of other CLI tools just didn't work.  I assume this situation would be unique to my machine.  Just for future reference, I was able to resolve the problem with a reinstall.

**Comment by joseluisq** [comment]
Because I have faced the same issue on Mac trying to upgrade (again) to the latest (v1.47.0), reinstalling Rust solved the issue.
So I will just let here the link for newcomers https://www.rust-lang.org/tools/install
