### ISSUE TITLE
Completions don't do target auto-discovery

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [rust-lang/rustup#2033]
### To reproduce
1. Install Rust using rustup.
2. Configure bash completions:
    ```bash
    mkdir -p ~/.local/share/bash-completion/completions
    rustup completions bash >> ~/.local/share/bash-completion/completions/rustup
    rustup completions bash cargo >> ~/.local/share/bash-completion/completions/cargo
    ```
3. Relogin.
4. ```bash
    cargo new --lib autotargets_completions
    cd autotargets_completions/
    mkdir src/bin
    touch src/bin/hello.rs
    ```
5. In the bash command prompt, enter `cargo run --bin ` and press `Tab`.

### Expected result
Completion `cargo run --bin hello` should be suggested.

### Actual result
No completion was suggested.

### Version info

```
$ rustup --version
rustup 1.18.3 (435397f48 2019-05-22)

$ rustup show
Default host: x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.39.0-nightly (2b8116dce 2019-09-08)

$ cargo --version --verbose
cargo 1.39.0-nightly (fe0e5a48b 2019-09-04)
release: 1.39.0
commit-hash: fe0e5a48b75da2b405c8ce1ba2674e174ae11d5d
commit-date: 2019-09-04
```

**Comment by kinnison** [comment]
The cargo completions are provided by Cargo, not by us.  You probably need to file an issue there.
