### ISSUE TITLE
`N iops / N iops (100%) M iops/s` makes no sense

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rustup#2041]
Installing rustup I saw this very curious line pop up:

> 2 iops /   2 iops (100 %)   1 iops/s in  1s ETA:  0s    

but it makes no sense whatsoever as “iops” is already an unit of operations per second. So paraphrased:

> 2 I/O operations per second out of 2 I/O operations per second, 1 I/O operations per second per second in 1 second.

The units should be fixed up to represent actual whatever being counted here.

**Comment by kinnison** [comment]
In this instance, iops is "I/O Operations" not "I/Os per second" though I concede that there's the potential for confusion.

**Comment by Rudi3** [comment]
[Wikipedia](https://en.wikipedia.org/wiki/IOPS) is not the best source, but `IOPS` usually stand for "Input/output operations per second".

And if I didn't miss anything, you could get something like `Kiiops/s`. Which would be "Kibi-i/o operations per second (squared)". :rofl:

I'm not sure what the non-rate unit for `IOPS` would be though (couldn't find anything on that, really)... In my PR, I went for IO-ops.

**Comment by kinnison** [comment]
Fair enough, that seems OK to me.  Disambiguation here is key :D

**Comment by Rudi3** [comment]
But honestly, I've never enountered `iops` on rustup.
@nagisa could you tell me which command you ran?

**Comment by nagisa** [comment]
I ran the `rustup` installation command from the website. It showed up briefly when unpacking one of the packages on a slower machine (a mips64 based router manufactured who knows when).

**Comment by Rudi3** [comment]
@nagisa I see. I tried `env RUSTUP_IO_THREADS=4` `-60` used in https://github.com/rust-lang/rustup.rs/pull/1876#issuecomment-499885408, without success...
Could you maybe test my pr branch and see if the output is now correct (if you want to)?

**Comment by kinnison** [comment]
You're unlikely to see the iops message unless you have slow IO -- e.g. an NFS mounted homedir, or Windows.
