### ISSUE TITLE
failed to install rustup with minimal profile

### ISSUE THREAD

**Issue by softprops** [rust-lang/rustup#2049]
**Problem**

I would like to be able to use the new minimal profile rustup feature. I tried the latest rustup-init with `--profile minimal` arguments but this yields argument error
 

**Steps**

1. run the following command `curl https://raw.githubusercontent.com/rust-lang/rustup.rs/2ce2428f36dc5432a4eeb722a392a13b3631efd4/rustup-init.sh -sSf |  sh -s -- -y --default-toolchain 1.38.0 --profile minimal`

yields the following error

```
info: downloading installer
error: Found argument '--profile' which wasn't expected, or isn't valid in this context

USAGE:
    rustup-init --default-toolchain <default-toolchain> -y
For more information try --help
```

2. run the following to view help `curl https://raw.githubusercontent.com/rust-lang/rustup.rs/2ce2428f36dc5432a4eeb722a392a13b3631efd4/rustup-init.sh -sSf |  sh -s -- --help`

this outputs information about the `profile` option which doesn't seem available

```sh
rustup-init 1.19.0 (a1f78334e 2019-09-07)
The installer for rustup

USAGE:
    rustup-init [FLAGS] [OPTIONS]

FLAGS:
    -v, --verbose           Enable verbose output
    -q, --quiet             Disable progress output
    -y                      Disable confirmation prompt.
        --no-modify-path    Don't configure the PATH environment variable
    -h, --help              Prints help information
    -V, --version           Prints version information

OPTIONS:
        --default-host <default-host>              Choose a default host triple
        --default-toolchain <default-toolchain>    Choose a default toolchain to install
        --default-toolchain none                   Do not install any toolchains
        --profile [minimal|default|complete]       Choose a profile
    -c, --component <components>...                Component name to also install
    -t, --target <targets>...                      Target name to also install
```

How does one use the new feature?

**Possible Solution(s)**

**Notes**

Output of `rustup --version`:

n/a this is the initial rustup installation 

Output of `rustup show`:

n/a this is the initial rustup installation

**Comment by kinnison** [comment]
This feature is not yet released.

**Comment by softprops** [comment]
Is there an eta on when to expect the next release?

**Comment by kinnison** [comment]
I hope to make the release within the week.

**Comment by softprops** [comment]
Awesome! Thank you folks for the hard work on this. I can't wait
