### ISSUE TITLE
[Feature Request] Downgrading nightly toolchains

### ISSUE THREAD

**Issue by elichai** [rust-lang/rustup#2067]
As talked on Discord with @kinnison 
I think an interesting usecase is to be able to *downgrade* your nightly feature to one that supports specific toolchains.
i.e. 
`rustup toolchain install nightly --downgrade -c rustc -c rust-std -c cargo -c rustfmt -c clippy -c rls -c rust-analysis -c miri`

This can make adding new components to your local toolchain easier (then tools like miri could add this to their docs and you won't need to uninstall latest nightly before installing this).

Another thing that this made me think of, maybe a way to *aggregate* components? 
For example, I install `rustup toolchain install nightly -c cargo` and now I want to add miri support so by doing something like `rustup toolchain install nightly --downgrade --add -c miri` It will now find me a toolchain with both clippy and miri.

**Comment by kinnison** [comment]
I wonder if @jonhoo might have input on this?

**Comment by jonhoo** [comment]
`--downgrade` sounds to me like an option on `component add`, not on install. So you'd do:
```console
$ rustup component add --allow-downgrade miri
```

**Comment by kinnison** [comment]
UX aside, it's all the same pathway internally, so it'd go via your backtracking code @jonhoo :D  I was more interested in what you thought about a bool to obviate the "stop at current version" check we currently have.

**Comment by jonhoo** [comment]
I guess it seems okay to downgrade if the user explicitly asks for it :man_shrugging:

**Comment by Rantanen** [comment]
Travis provides Rust environments for Nightly with:
```yaml
language: rust
rust:
    - nightly
```
This is great, unless you happen to require specific components for your builds. If you do, you'll need to uninstall the existing Rust version to be able to ensure rustup can install something that fulfills your requirements.

This is from Intercom's current `.travis.yml`:

```yaml
    - rustup component add clippy rustfmt
    - if( ! cargo clippy -V || ! cargo fmt --version ); then rustup uninstall nightly && rustup toolchain install nightly -c clippy -c rustfmt; fi
```

`--allow-downgrade` would simplify this a lot!

**Comment by payload** [comment]
I'll look into it during RustFest, coordination through rust-lang discord #wg-rustup

**Comment by RalfJung** [comment]
The PR mentions "rustup toolchain install --allow-downgrade", but what about "rustup component add --allow-downgrade" that was also mentioned above -- should a new issue be opened for that?

**Comment by kinnison** [comment]
@RalfJung It might make sense to create an issue around that, yes.

The functionality is available via `rustup toolchain install $already_installed_channel -c added_component_name` but the `rustup component add` pathway is a bit different and harder to get this feature into right now, hence it's missing from the CLI for 1.21.0

**Comment by RalfJung** [comment]
New issue opened: https://github.com/rust-lang/rustup/issues/2146
