### ISSUE TITLE
rustup target add should be no op if added target is the same as default-host

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rustup#2092]

**Comment by kinnison** [comment]
As far as I can tell, it is.  Could you please follow up with an explanation of what you see and why it's wrong?

**Comment by tesuji** [comment]
Thanks for confirming. It's my mistake when reading error message.
So 
https://github.com/rust-lang/rustup.rs/blob/bbb4160e7a90d713f2ef6ac1635774f85eb2ffc7/appveyor.yml#L81-L82
and 
https://github.com/rust-lang/rustup.rs/blob/bbb4160e7a90d713f2ef6ac1635774f85eb2ffc7/.travis.yml#L119
is needless?

**Comment by kinnison** [comment]
Yeah, in theory it's completely safe for those to be unconditional.

**Comment by tesuji** [comment]
Thanks. I opened #2093 to remove those.
