### ISSUE TITLE
Add a way to synchronize components to those in a profile

### ISSUE THREAD

**Issue by nertpinx** [rust-lang/rustup#2103]
**Describe the problem you are trying to solve**

When selecting or changing a profile it would be helpful to have a way to "synchronize" the list of installed components to those that are part of the profile.  That means than when selecting a (for example) default profile with the new switch two things would happen:
- components that are installed, but are not part of the selected profile would be uninstalled
- components that are not installed, but are part of the selected profile would be installed

**Describe the solution you'd like**

Either having a way to do this when selecting a profile, e.g.:
`rustup set profile --synchronize ...`
or make updating a toolchain with selected profile do this automatically:
`rustup toolchain update --profile ...`

**Notes**

I am willing to work on this and implement it (very slowly, during my limited free time), but I am not certain how to approach some parts of the code.

**Comment by kinnison** [comment]
Profiles are currently only meant to be used at fresh toolchain installation time.  The first of your suggestions I'd council against, but the second is not entirely unpossible.  It'd require some careful threading through the code though because component removal is only done explicitly currently, rather than as part of an update process.

**Comment by nertpinx** [comment]
@kinnison For example with an extra parameter which would control this behaviour (i.e. would make it explicit)?

**Comment by kinnison** [comment]
It's more that the toolchain install/update process is given: 1. an optional profile, 2. a set of explicit components to add, 3. a set of explicit components to subtract.  Then if the profile was given in 1, 2 is augmented with the set of components in that profile.  Finally the current set of components (empty on fresh install) is synchronised by removing the explicit-delete and then adding the explicit add sets.  To make it "synchronise" to a profile would require additional work to ensure that 3 above is augmented too at just the right moment. (Possible, but not trivial).

Further you then need to decide -- the profile causes rust-std to be installed for the toolchain host, but there might be other targets installed too -- should synchronising the profile cause those extra targets to be removed?

**Comment by mzabaluev** [comment]
It would be useful in the [GitHub toolchain action](https://github.com/actions-rs/toolchain) if it were possible to remove the components not meeting the new profile (or explicitly mentioned by `--component`) on update. See https://github.com/actions-rs/toolchain/issues/27

**Comment by nertpinx** [comment]
I tried toying with this in the meantime, but for someone who is not skilled with that codebase at all and has other work to do this was too much. Then I figured that for the usual user (e.g. me) when trying to synchronize components to a profile or switching a profile it is just easier to remove everything, install with the wanted profile and then iron out the edges. And it is something you do once per toolchain/computer/user, so after around 9 iterations I was done and if someone else (not really in an automated way, but rather a manual one) needs this, then I figure they'd to just that.

**Comment by mzabaluev** [comment]
@nertpinx A full reinstall every once in a while may be good for most users, but in GitHub CI each invocation of the toolchain action ends up spending seconds of billed time and a lot of unnecessary network traffic on the rustup CDN updating components that the workflow does not necessarily need. Removing the delta between the pre-installed components and the requested profile requires intrinsic knowledge on what constitutes a rustup profile; I'm not sure the GitHub action developers should depend on rustup being stable about this.

**Comment by nertpinx** [comment]
@mzabaluev I definitely get that, that's why I said it applies only for users wanting to do what I did, manually. I'm not saying this is not usable, clearly for your use-case this would be a huge improvement.

**Comment by nertpinx** [comment]
So just to update on my status I must say that for my use-case it is probably not worth pursuing after I spent some time thinking about it. But thanks very much for the proactive approach, I very much appreciate that. Unless @mzabaluev is interested in keeping this I'm fine with closing this to remove clutter from the queue of issues.

**Comment by kinnison** [comment]
I think it's a little too confusing for people, since "synchronising" might mean removing stuff, installing other stuff, etc.  I'll close this for now.

If in the future someone has a good idea for a coherent approach to this, we can have a fresh issue to discuss it.
