### ISSUE TITLE
rustup toolchain install stable-x86_64-pc-windows-gnu failed

### ISSUE THREAD

**Issue by laurencechan** [rust-lang/rustup#2104]
**Problem**
when I try to debug my rust code in clion, I got this error:
![image](https://user-images.githubusercontent.com/17173306/68000777-5bfe4900-fc9c-11e9-9e94-7a1bd8ffe8ce.png)

so I use this command to install GNU toolchain in windows 10 , and I got this error msg:
```
C:\Users\c00450331>rustup toolchain install stable-x86_64-pc-windows-gnu
info: syncing channel updates for 'stable-x86_64-pc-windows-gnu'
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256' to 'C:\Users\c00450331\.rustup\tmp\ood_3yr8lkwcwnyd_file'
error: caused by: failed to make network request
error: caused by: https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256: error trying to connect: 以一种访问权限不允许的方式做了一个访问套接字的尝试。 (os error 10013)
error: caused by: 以一种访问权限不允许的方式做了一个访问套接字的尝试。 (os error 10013)
```

**Notes**

Output of `rustup --version`:
`rustup 1.20.2 (13979c968 2019-10-16)`

Output of `rustup show`:
```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\c00450331\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-2019-09-05-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.37.0 (eae3437df 2019-08-13)
```

**Comment by kinnison** [comment]
"os error 10013" is a Windows code for socket permission denied.  It seems like perhaps your antivirus or firewall is preventing `rustup` from downloading things?

**Comment by rbtcollins** [comment]
@laurencechan hi - we need more information from you to help you. We will close this bug shortly if no more information is supplied.
