### ISSUE TITLE
Inform what version rustup was updated from

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rustup#2110]
Currently `rustup update` outputs:
```console
% rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2019-11-04, rust version 1.40.0-nightly (b520af6fd 2019-11-03)
[REDACTED]
  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.38.0 (625451e37 2019-09-23)
   nightly-x86_64-unknown-linux-gnu updated - rustc 1.40.0-nightly (b520af6fd 2019-11-03)
```

It would be nice if rustup could print out which version it was updated from:
```console
% rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2019-11-04, rust version 1.40.0-nightly (b520af6fd 2019-11-03)
[REDACTED]
  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.38.0 (625451e37 2019-09-23)
   nightly-x86_64-unknown-linux-gnu updated - rustc 1.40.0-nightly (b520af6fd 2019-11-03) from rustc 1.40.0-nightly (aa69777ea 2019-10-29)
```

## Meta
rustup -V: rustup 1.20.1 :: 1.20.0+14 (4eadfff3d 2019-10-15)

**Comment by chansuke** [comment]
Hi, I would like to take this issue

**Comment by kinnison** [comment]
Hi @chansuke,

I'm sorry it took so long to respond.  Thank you for being interested in this enhancement request.  You should pop along to our discord: https://discord.gg/cKdYFVz (`#wg-rustup`) and we can discuss how you go about this, if you're not confident to go ahead without guidance.

Thanks again, and welcome to Rustup.

D.

**Comment by chansuke** [comment]
@kinnison Thank you. I will check discord channel.

**Comment by payload** [comment]
Hi @chansuke. Are you still working on this issue?

**Comment by joshtriplett** [comment]
Minor nit on formatting: please make the "from" version less prominent (e.g. parenthetical), so that it's easier to quickly scan the line for the version and distinguish the old and new versions.
