### ISSUE TITLE
unable to update for missing 'clippy', 'lldb-preview', 'miri'

### ISSUE THREAD

**Issue by itfunly** [rust-lang/rustup#2113]
**Problem**

Try to install rls use rustup update report error: unavailable for download

**Steps**

1. execute` rustup update` report:
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
373.0 KiB / 373.0 KiB (100 %)  41.6 KiB/s in 10s ETA:  0s
info: latest update on 2019-11-07, rust version 1.39.0 (4560ea788 2019-11-04)
error: component 'rust-src' for target 'x86_64-pc-windows-msvc' is unavailable for download for channel stable
info: checking for self-updates

  stable-x86_64-pc-windows-msvc update failed - rustc 1.38.0 (625451e37 2019-09-23)

2. try to execute `rustup update nightly`
error: some components unavailable for download for channel nightly: 'clippy', 'lldb-preview', 'miri'

3. use ` rustup component list` dose not containes  'clippy', 'lldb-preview', 'miri'
cargo-x86_64-pc-windows-msvc (installed)
clippy-x86_64-pc-windows-msvc (installed)
llvm-tools-preview-x86_64-pc-windows-msvc (installed)
rls-x86_64-pc-windows-msvc (installed)
rust-analysis-x86_64-pc-windows-msvc (installed)
rust-docs-x86_64-pc-windows-msvc (installed)
rust-src
rust-std-aarch64-apple-ios
rust-std-aarch64-fuchsia
rust-std-aarch64-linux-android
rust-std-aarch64-pc-windows-msvc
rust-std-aarch64-unknown-linux-gnu
rust-std-aarch64-unknown-linux-musl
rust-std-arm-linux-androideabi
rust-std-arm-unknown-linux-gnueabi
rust-std-arm-unknown-linux-gnueabihf
rust-std-arm-unknown-linux-musleabi
rust-std-arm-unknown-linux-musleabihf
rust-std-armebv7r-none-eabi
rust-std-armebv7r-none-eabihf
rust-std-armv5te-unknown-linux-gnueabi
rust-std-armv5te-unknown-linux-musleabi
rust-std-armv7-apple-ios
rust-std-armv7-linux-androideabi
rust-std-armv7-unknown-linux-gnueabi
rust-std-armv7-unknown-linux-gnueabihf
rust-std-armv7-unknown-linux-musleabi
rust-std-armv7-unknown-linux-musleabihf
rust-std-armv7r-none-eabi
rust-std-armv7r-none-eabihf
rust-std-armv7s-apple-ios
rust-std-asmjs-unknown-emscripten
rust-std-i386-apple-ios
rust-std-i586-pc-windows-msvc
rust-std-i586-unknown-linux-gnu
rust-std-i586-unknown-linux-musl
rust-std-i686-apple-darwin
rust-std-i686-linux-android
rust-std-i686-pc-windows-gnu
rust-std-i686-pc-windows-msvc
rust-std-i686-unknown-freebsd
rust-std-i686-unknown-linux-gnu
rust-std-i686-unknown-linux-musl
rust-std-mips-unknown-linux-gnu
rust-std-mips-unknown-linux-musl
rust-std-mips64-unknown-linux-gnuabi64
rust-std-mips64el-unknown-linux-gnuabi64
rust-std-mipsel-unknown-linux-gnu
rust-std-mipsel-unknown-linux-musl
rust-std-nvptx64-nvidia-cuda
rust-std-powerpc-unknown-linux-gnu
rust-std-powerpc64-unknown-linux-gnu
rust-std-powerpc64le-unknown-linux-gnu
rust-std-riscv32i-unknown-none-elf
rust-std-riscv32imac-unknown-none-elf
rust-std-riscv32imc-unknown-none-elf
rust-std-riscv64gc-unknown-none-elf
rust-std-riscv64imac-unknown-none-elf
rust-std-s390x-unknown-linux-gnu
rust-std-sparc64-unknown-linux-gnu
rust-std-sparcv9-sun-solaris
rust-std-thumbv6m-none-eabi
rust-std-thumbv7em-none-eabi
rust-std-thumbv7em-none-eabihf
rust-std-thumbv7m-none-eabi
rust-std-thumbv7neon-linux-androideabi
rust-std-thumbv7neon-unknown-linux-gnueabihf
rust-std-thumbv8m.base-none-eabi
rust-std-thumbv8m.main-none-eabi
rust-std-thumbv8m.main-none-eabihf
rust-std-wasm32-unknown-emscripten
rust-std-wasm32-unknown-unknown
rust-std-wasm32-wasi
rust-std-x86_64-apple-darwin
rust-std-x86_64-apple-ios
rust-std-x86_64-fortanix-unknown-sgx
rust-std-x86_64-fuchsia
rust-std-x86_64-linux-android
rust-std-x86_64-pc-windows-gnu
rust-std-x86_64-pc-windows-msvc (installed)
rust-std-x86_64-rumprun-netbsd
rust-std-x86_64-sun-solaris
rust-std-x86_64-unknown-cloudabi
rust-std-x86_64-unknown-freebsd
rust-std-x86_64-unknown-linux-gnu
rust-std-x86_64-unknown-linux-gnux32
rust-std-x86_64-unknown-linux-musl
rust-std-x86_64-unknown-netbsd
rustc-x86_64-pc-windows-msvc (installed)
rustfmt-x86_64-pc-windows-msvc (installed)

4.  `rustup show profile`
complete

**Possible Solution(s)**

**Notes**

Output of `rustup --version`:
 rustup -V
rustup 1.20.2 (13979c968 2019-10-16)

Output of `rustup show`:
 rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\ItFunly\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.38.0 (625451e37 2019-09-23)

**Comment by itfunly** [comment]
vs code install rls as :
> Executing task: rustup component add rust-analysis --toolchain stable-x86_64-pc-windows-msvc <

info: component 'rust-analysis' for target 'x86_64-pc-windows-msvc' is up to date
error: component 'rust-src' for target 'x86_64-pc-windows-msvc' is unavailable for download for channel stable
exit code: 1


> Executing task: rustup component add rust-src --toolchain stable-x86_64-pc-windows-msvc <

error: component 'rust-src' for target 'x86_64-pc-windows-msvc' is unavailable for download for channel stable
exit code: 1

**Comment by kinnison** [comment]
This is a bug in how profiles work in 1.20 when installing the `complete` profile.  If you `rustup component uninstall rust-src` and then `rustup component install rust-src` it'll be fixed.

**Comment by itfunly** [comment]
@kinnison yes, you are right.

**Comment by kinnison** [comment]
Cool, I'm glad that worked for you.  I'll endeavour to ensure that the next rustup release can cope with the snafu :D

**Comment by kinnison** [comment]
I believe that #2115 ought to fix this.
