### ISSUE TITLE
Bundle cheat sheet with "rustup docs"

### ISSUE THREAD

**Issue by ralfbiedert** [rust-lang/rustup#2118]
**Describe the problem you are trying to solve**
In the repo of the Rust Language Cheat Sheet, [an issue has been opened ](https://github.com/ralfbiedert/cheats.rs/issues/75) that the content of the site [cheats.rs](https://cheats.rs) should be bundled and be accessible via `rustup docs`.

The underlying problem to solve would be:

- The cheat sheet would always be available offline (e.g., on flights)
- A concise outline of the language would be shipped by default 

**Describe the solution you'd like**

I'm open for suggestions here. 

The site itself is mostly single page, with a few 3rd party fonts loaded (which I intend to fix anyway). All other resources are embedded as data URLs.

The bundling process of `rustup` (not sure how that works ) could then just take a snapshot of the site and ship it.

It could then be linked from the site that currently opens when typing `rustup docs`.

**Comment by kinnison** [comment]
The documentation that `rustup doc` launches is found in the `rust-docs` component, rather than being bundled by `rustup` itself.  It would require the core team probably to agree to add stuff to that.  if you do, then we can teach `rustup doc` a new flag to open the cheat sheet specifically.

**Comment by ralfbiedert** [comment]
Closing since upstream request was closed.
