### ISSUE TITLE
The `complete` profile really should warn the user

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rustup#2136]
We have a lot of people who want to install `complete` despite it really being for Rust developers rather than those who develop *with* Rust.

As a stop-gap, since removing `complete` would be a bit of a pain, it'd be useful if `rustup` could warn whenever `complete` is used to install a toolchain.  That'd be fairly lightweight and could mitigate a lot of issues which might otherwise be raised.

This should be a very easy first issue for someone, and I'd be happy to mentor them on #wg-rustup on our discord.

**Comment by kinnison** [comment]
If you wish to take on this work, please state so on this issue, and then find me on Discord to discuss it.  That way we won't have multiple people trying to solve the same thing at the same time.  Thanks.

**Comment by kinnison** [comment]
In addition, https://github.com/rust-lang/rustup#profiles misrepresents the `complete` profile a little as being of use for general developers.  We probably need to fix that as part of any PR to resolve this issue.

**Comment by Stupremee** [comment]
I can take care of that. @kinnison I can ping you in discord

**Comment by Stupremee** [comment]
I guess this can be closed now

**Comment by kinnison** [comment]
Closed in #2138

**Comment by svend** [comment]
I found https://github.com/rust-lang/rustup#profiles confusing. I picked the complete profile, since I wanted IDE support out of the box.

> The complete profile includes all the components available through rustup, including miri and IDE integration tools (rls and rust-analysis).
