### ISSUE TITLE
the download procedure of rustup seems flawed

### ISSUE THREAD

**Issue by elmarstellnberger** [rust-lang/rustup#2139]
I have problems obtaining a genuinely verified version of rust. When I try to run rustup with tails/tor it always hangs. There seems to be no way to make it interrupt and re-issue stalled downloads (that should be done automatically after a timeout). It is the same for the latest nightly builds as well as specific versions like nightly-2019-11-04.

https://trac.torproject.org/projects/tor/ticket/32577

  As it is always intransparent what a download tool does I wanna suggest you to issue releases downloadable as .tar.bz2 for which a SHA512SUMS and eventually a SHA512SUMS.signed is available - as it is the default for distributions like Debian. However signing is no panacea. To make signing secure you would have to store your key offline and prevent unauthored physical access; see: https://www.elstel.org/software/GnuPG-usage.html.en. Hardly anyone does. Downloading SHA512SUMS anonymously via tor is the best we can currently do as usually surveillance spoofs only a small percentage of all downloads in order not to become discovered.

**Comment by kinnison** [comment]
Your proposed approach isn't quite what we're hoping to achieve.  We're tracking our work toward a more trustable `rustup` approach at #2027 and we hope to announce stuff toward the end of Q1 next year.  In the meantime, you are able to GPG verify channel manifests yourself, and accept that they contain SHA256sums of the files which are subsequently downloaded as part of a toolchain channel.  The next release of `rustup` will be doing that silently (you can see with `--verbose` after 1.21 is released) but that is insufficient as a trust model, so we're not making any assertions on that for now.

I appreciate your input, but would prefer to continue tracking this on the issues we already have, so I'm going to close this issue.  It'll be linked to #2027 automatically by my mentioning it.

Thanks, and if you want to discuss stuff more, you're welcome to come along to our Discord channel or to post apposite things on the related issues.

D.
