### ISSUE TITLE
Cleanup needed in toolchain parsing

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rustup#2142]
We fixed a future-shock problem in #2132 which left open a need to commit a neatness in the codebase.  @Diggsey explained it nicely in https://github.com/rust-lang/rustup/pull/2132#discussion_r347174250 and I feel it'd make a good newcomer issue to introduce someone to working in the `rustup` codebase.

Basic goal for this is to encode the semantics from the comment mentioned in the PR as properly tested code which is reused by the two functions which currently use the regular expression which was factored out in the PR.

If you're interested in helping with this, please signal on the issue and pop along to our #wg-rustup channel on the Rust-lang discord server if you want to discuss the matter.

**Comment by pastly** [comment]
I would like to help with this issue. I made a discord account but can't figure out how to join #wg-rustup.

Never mind. Had to read the words on the page 🤦‍♂

**Comment by kinnison** [comment]
Hi @pastly 

Happy new year!  Are you still interested and able to make progress on this issue?  I've not seen you around on the Discord in a while.  If you've lost interest or run out of time/energy then that's fine, but I'd like to free this up for someone else to approach if you have.  Either way if you could let me know then I'd appreciate it.

Thanks,

Daniel.

**Comment by pastly** [comment]
It was not okay for me to go complete radio silence. I'm sorry about that.

Long story short is that I did take a stab at it, it didn't work, I'm unsurprisingly busy, and I think it's in your best interest to open it up for someone else.

If time frees up and this is still open, I'll try asking for help next time.

Thanks for rustup. I use it all the time :)

**Comment by kinnison** [comment]
@pastly Thanks for the update, hopefully someone else will have time to look, otherwise I'll be happy to see you come back to it when you're less busy.

**Comment by LeSeulArtichaut** [comment]
Hey, I'm someone else who has time to look :D
I just submitted a PR (#2231) to try to close this. I hope it was what you were expecting. If not please contact me back, by pinging me here or over Discord (you'll easely find me, I don't think many people are named "TheOnlyArtichoke", since I'm the only one).
