### ISSUE TITLE
Release version 1.21.0?

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rustup#2144]
Hi! I’d like to use https://github.com/rust-lang/rustup/pull/2075 which was merged after the current version 1.20.2 was released. Is something missing before a new version can be released? Can I help?

**Comment by kinnison** [comment]
We have a milestone to track 1.21.0 work which you can find at https://github.com/rust-lang/rustup/milestone/2

more generally, we're attempting to do milestones for releases from now on, so your first port of call for "what is left before X release" is to look for a milestone :-D

Helping would just be looking to see what's on the milestone but seems to lack progress and then talking to us on Discord about that.

Right now I think code review of https://github.com/rust-lang/rustup/pull/2141 is the only thing which is blocking, the other issue is in progress.

**Comment by SimonSapin** [comment]
Good to know, thanks!
