### ISSUE TITLE
Demote deprecation warning to verbose info

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rustup#2149]
After a lot of discussion with reddit and friends, it seems that deprecating `rustup install` and `rustup uninstall` would have consequences I'd not considered (printed books) and as such it'd be unpleasantly surprising for new users to be told the book they bought was wrong.

As such, we should demote the [deprecation warning code](https://github.com/rust-lang/rustup/blob/master/src/cli/rustup_mode.rs#L30) from `warn!()` to `verbose!()` and make it clear that the reason for the message is that until true alias support is added, these may not function quite as the `toolchain XXX` commands would.

Long-term we want to replace the deprecated subcommands with true aliases so that this can't be a problem again in the future.

**Comment by kinnison** [comment]
If you'd like to tackle this, please indicate so on the issue and find me on the Rustup discord channel if you want to chat about it.

**Comment by jaronsummers** [comment]
The printed book use case is largely handled by just replacing the existing code with a message that says to use `rustup toolchain install` instead, isn't it? That code would be simple enough that it wouldn't be buggy, nor would it be a duplication of the `rustup toolchain install` code.

**Comment by kinnison** [comment]
@jaronsummers This issue was raised precisely because people were worried about such a deprecation message causing undue concern to newcomers.
