### ISSUE TITLE
Index and list all available toolchains

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#215]
`rustup toolchain list` should also tell you which toolchains are available. Getting this information correctly will require either indexing it on the backend or having every client index the archives themselves.

Related to https://github.com/rust-lang-nursery/multirust-rs/issues/192

**Comment by nodakai** [comment]
I wish to have something like `--json` for as many subcommands as possible. It can be any machine-readable formats, not necessarily JSON

**Comment by oconnor663** [comment]
Is there a place we can see the available toolchains in the browser right now?

**Comment by Diggsey** [comment]
@oconnor663 Not in a user-friendly way, but you can find the toml manifests here: https://static.rust-lang.org/dist/index.html

**Comment by oconnor663** [comment]
@Diggsey thanks, that's what I needed.

**Comment by totalknowledge** [comment]
rustup toolchain list 
gives me a list of the installed toolchains, not the available ones.

**Comment by mqudsi** [comment]
I believe `rustup target list` provides this information.

**Comment by theronic** [comment]
Yes, please. The only reason I'll ever run `rustup toolchain list` is because I'm missing one that I expected to have.

**Comment by keysmashes** [comment]
> https://static.rust-lang.org/dist/index.html

This appears to not exist any more (the last Internet Archive snapshot was on 11-11-2018) – is there a replacement?

**Comment by packysauce** [comment]
if you're like me, you probably want `rustup target list`, because that shows the available target triples, eg x86_64-unknown-linux-musl

**Comment by mqudsi** [comment]
Just ran into this while doing my usual google search for a list of toolchains. If you're using fish as your shell, it has dynamic completions for `rustup`, including a list of targets and toolchains, that are automatically available when performing an operation like `rustup toolchain add <TAB>`.

**Comment by jrb467** [comment]
For those still looking for a list, after some searching I found this: https://rust-lang.github.io/rustup-components-history/

**Comment by fadeevab** [comment]
@jrb467 @packysauce Thank you, good men! And `rustup target list` does the thing!

**Comment by kinnison** [comment]
The full toolchain channel list would be enormous (since there are lots of nightly toolchains etc).  I don't think this kind of feature belongs in rustup.  If there's a strong reason to support attempting to enumerate available toolchain channels then please open a fresh issue to discuss it, and we can bring in some of the infra/release team to help us work out what we could do.

**Comment by n-insaidoo** [comment]
> For those still looking for a list, after some searching I found this: https://rust-lang.github.io/rustup-components-history/

Any toolchain that only has cargo (or the minimum components required to run cargo)?

**Comment by gdennie** [comment]
`rustup` is incomplete if you does not provide a list or at least a search feature: a kitchen should have an observable pantry.

**Comment by droundy** [comment]
I would love to have a list that at least included a stable name for each of the current channels.  I'm wanting to set my rust-toolchain to a prerelease of 1.74 but can't see a possible way to identify what value (if any) will be accepted.

**Comment by rbtcollins** [comment]
I'm going to lock this bug now - the last two comments have clearly not read the rest of the context.

For anyone else coming here: rustup would love this feature, but the data to support it is not generated by the rustup code base; it is the channel metadata and the related API that need to facilitate this feature.
