### ISSUE TITLE
No rust-src component for x86_64-unknown-linux-musl

### ISSUE THREAD

**Issue by Noodlez1232** [rust-lang/rustup#2156]
**Problem**
The current stable channel is missing a `rust-src` component for the target tuple `x86_64-unknown-linux-musl`.

**Steps**
1. Install rustup using the installer found on [rustup.rs](https://rustup.rs)
2. Set up the stable toolchain using `rustup toolchain add stable`
3. Attempt to install the rust-src component using `rustup component add rust-src`

**Output**
The output of the command is as follows:
```
error: component 'rust-src' for target 'x86_64-unknown-linux-musl' is unavailable for download for channel stable
```

**Notes**

The host system is running Void Linux, but rustup was not installed using the package manager. The same issue occurs with the rustup included in Void's packages.

Output of `rustup --version`: `rustup 1.20.2 (2019-10-16)`

Output of `rustup show`:
```
Default host: x86_64-unknown-linux-musl
rustup home:  /home/nathaniel/.rustup

stable-x86_64-unknown-linux-musl (default)
rustc 1.39.0 (4560ea788 2019-11-04)
```

**Comment by kinnison** [comment]
`rust-src` is target-independent which suggests you may have stumbled across a bug in 1.20 which is fixed ready for release in 1.21.  You've almost certainly installed the `complete` profile which is not really meant for normal users.  If you `rustup component remove rust-src ; rustup component add rust-src` then that should fix it.

Please let me know if it doesn't.

**Comment by Noodlez1232** [comment]
Okay, Thank you! That worked. I'll keep that in mind whenever I install rustup from now on.

**Comment by kinnison** [comment]
Once 1.21 is out, it'll self-heal when it detects this mistake :D
