### ISSUE TITLE
Can't install stable toolchain

### ISSUE THREAD

**Issue by leshow** [rust-lang/rustup#2161]
**Problem**
rustup fails to install the stable toolchain

**Steps**
1. install rustup
2. set complete profile (I think this is necessary)
3. install stable

```
❯ rustup install stable
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2019-11-07, rust version 1.39.0 (4560ea788 2019-11-04)
error: some components unavailable for download for channel stable: 'lldb-preview', 'miri'
If you require these components, please install and use the latest successful build version,
which you can find at <https://rust-lang.github.io/rustup-components-history>.

After determining the correct date, install it with a command such as:

    rustup toolchain install nightly-2018-12-27

Then you can use the toolchain with commands such as:

    cargo +nightly-2018-12-27 build
 ```

The help information points to the nightly, but I'm not trying to install nightly. And you'd think that these components would be available for stable?

I'm not the only one to experience this apparently. I asked on the rust discord and another user had this problem yesterday as well.  They were on windows, I'm on linux.

Is it not possible to use the complete profile on stable?

If I try to remove `lldb-preview` and `miri` I get:
```
❯ rustup component remove lldb-preview miri
error: toolchain 'stable-x86_64-unknown-linux-gnu' is not installed
error: caused by: not a directory: '/home/leshow/.rustup/toolchains/stable-x86_64-unknown-linux-gnu'
```

edit: I think I must have run `component add lldb-preview miri` at some point. I nuked the rustup dir and I was able to install stable again.

**Comment by kinnison** [comment]
The `complete` profile is not meant for normal users and will likely never work on `stable` unless the definition of the profile is changed by the team in charge of the compiler releases.  If you want to install as much as possible of the `complete` profile then use the `--force` option so that it skips missing components.  Otherwise I recommend the use of the `default` profile instead.
