### ISSUE TITLE
 It may be useful to print the previous version of the compiler when upgrading

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#217]
[Source](https://internals.rust-lang.org/t/beta-testing-rustup-rs/3316/47?u=brson).

**Comment by das-sein** [comment]
@Diggsey @brson Is this resolved? Updating lists the components being uninstalled which should list the previous version of the compiler. If https://github.com/rust-lang/rustup.rs/pull/1639 lands, this could become more obvious to users.

**Comment by kinnison** [comment]
This is now a thing which has been released:

```
  nightly-x86_64-unknown-linux-gnu updated - rustc 1.50.0-nightly (f4db9ffb2 2020-12-02) (from rustc 1.50.0-nightly (f4db9ffb2 2020-12-02))
```
