### ISSUE TITLE
How to solve curl: (35) Unsupported SSL protocol version during rust installation

### ISSUE THREAD

**Issue by Malixxa** [rust-lang/rustup#2170]
**Problem**
I am trying to install rust via the following command:
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
on my macbook pro (macOS 10.14.16) and always get the following error:
`curl: (35) Unsupported SSL protocol version`

I did reinstall OpenSSL via homebrew but it is still not working.

Any ideas?

**Comment by kinnison** [comment]
It's possible that cURL on your mac does not support tlsv1.2.  Mac OS older than 10.13 does not support support it.

**Comment by Malixxa** [comment]
Thank you @kinnison Any idea how and where I could check this? Since I am running 10.14 it should be installed…

**Comment by Malixxa** [comment]
Tried the following
`curl https://google.com/ --tlsv1.2 --verbose  `
and this is the output
```
* Hostname was NOT found in DNS cache
*   Trying 216.58.215.238...
* Connected to google.com (216.58.215.238) port 443 (#0)
* Unsupported SSL protocol version
* Closing connection 0
curl: (35) Unsupported SSL protocol version
```

Running
`> $ curl https://google.com/ --verbose`
Results in 
`SL connection using TLSv1.0 / AES128-SHA`

And running
`> $ curl --proto '=https' -sSf https://sh.rustup.rs | sh`
Results in 
`curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version`

I am Kinda lost, since I am running the latest cURL version
`Warning: curl 7.67.0 already installed`and also updated `Open SSL`

How and where can I update TLS? Or do I need to update the cURL settings?

**Comment by Malixxa** [comment]
So I have some news. Updated my LAMP stack and aliased curl to the newer version. Now this is outputted when trying to install rust:
```
info: downloading installer
curl: (35) Unsupported SSL protocol version
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/x86_64-apple-darwin/rustup-init /var/folders/jh/lpm74mln3nzgfx3l94p9kq780000gn/T/tmp.D0H2xvvv/rustup-init```

**Comment by Malixxa** [comment]
Fixed! I had a wrong Path for my PHP in the .zshrc :/
