### ISSUE TITLE
Use structopt to cleanup CLI parsing?

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rustup#2177]

**Comment by kinnison** [comment]
I'd rather wait for clap 3.0 to find out what is being offered there.

**Comment by tesuji** [comment]
That's fair. But an open tickets with block-upstream label doesn't hurt.

**Comment by kinnison** [comment]
It would potentially encourage a newcomer to invest effort in something I do not wish to suggest we'd immediately accept.  These kinds of discussions belong on the discord more than a github issue.

**Comment by tesuji** [comment]
Alright then.
