### ISSUE TITLE
Rustup fails to download on systems that prefer ipv6.

### ISSUE THREAD

**Issue by apokaliptis** [rust-lang/rustup#2178]
**Problem**
rustup-init.sh fails to download and install on systems that use ipv6 by default. I'm Pengwin in WSL on Windows 10.

**Steps**
1. Execute `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

**Possible Solution(s)**
Explicitly use ipv4 on every call to download from rust servers, or at least add a note that users may need to disable ipv6 to download from rust.rs servers.

**Notes**
I was able to download rustup-init.sh by executing, `curl -4 --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh`. I then added to every curl and wget command the `-4`. This allowed me to get further in the download process, but guess this script downloads another script(s) to handle the rest which would also need to be updated.

**Comment by kinnison** [comment]
I'm sorry that you've had such issues.  `rustup.rs` and `sh.rustup.rs` are cloudfronted S3 buckets.  I am quite able to access them over IPv6 from my systems which suggests that perhaps your IPv6 setup is either missing some routes, or else from where you are, access to S3 buckets over IPv6 are not as reliable as you might hope.

Could you please look at whether you have routing or connectivity issues toward `2600:9000:21b3:8e00:0:9a61:7540:93a1` (which is the IP I seem to get for `sh.rustup.rs`)

**Comment by apokaliptis** [comment]
Sorry, I guess I don't have IPv6 in my area. This must be an issue with either WSL or more likely Pengwin trying to use IPv6 instead of IPv4. I'm going to test Ubuntu WSL to see if I have the same issue there. Thanks for looking into this, @kinnison!

**Comment by apokaliptis** [comment]
The same issue persists on Ubuntu on Windows. If I try to use `curl`, `wget`, `ping`, etc. to access `sh.rustup.rs`, they fail to resolve the address unless I explicitly use IPv4 (`-4` flag) in the command. I do not have this issue if I try to access `rustup.rs` (without the `sh.`). Windows itself has no issue resolving `sh.rustup.rs`. Running `invoke-webrequest sh.rustup.rs` in PowerShell has no issues and putting that url in the browser automatically downloads the script.

In case anybody runs into this same issue, I'll post an update here if I find a solution.

**Comment by kinnison** [comment]
I wonder what your `/etc/gai.conf` looks like in your WSL.  Does it have any non-commented non-empty lines in it?

**Comment by apokaliptis** [comment]
Sorry for the late response. All lines were commented out in `/etc/gai.conf`. In the file it says, "For sites which prefer IPv4 connections change the last line to `precedence ::ffff:0:0/96  100`", which I did but it still doesn't work. Also, I found out my WSL isn't able to resolve static.rust-lang.org either.

**Comment by kinnison** [comment]
If you're failing to do name resolution etc, then I wonder if your WSL setup is somehow otherwise broken.  You say you're able to do arbitrary other ipv6 from it though?

**Comment by rbtcollins** [comment]
ping @apokaliptis ? will close this in a bit if you have lost interest in digging into this.

In addition to @kinnison's question, what version of WSL do you have?

**Comment by rbtcollins** [comment]
Closing as it has had no futher feedback.
