### ISSUE TITLE
Replace time crate with `std::time` primitives

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rustup#2181]
`Rustup` currently uses both `time` v0.1 and `std::time` to represent a Duration. 

```console
% git grep '\btime::'
download/src/lib.rs:135:    use std::time::Duration;
download/src/lib.rs:256:    use std::time::Duration;
src/cli/download_tracker.rs:11:use time::precise_time_s;
src/cli/self_update.rs:924:    use std::time::Duration;
src/diskio/mod.rs:64:use time::precise_time_s;
src/diskio/threaded.rs:137:            sleep(std::time::Duration::from_millis(100));
src/toolchain.rs:23:use std::time::Duration;
tests/cli-self-upd.rs:287:    use std::time::Duration;
tests/mock/clitools.rs:454:                    std::thread::sleep(std::time::Duration::from_millis(250));
```

But with the evolve of `std::time`, it might be enough to only use `std::time` for those tasks.

The hard part is rewriting the `Duration` struct in:
https://github.com/rust-lang/rustup/blob/d6366cba52b00f517fa7f10f375cb91d40e02dc9/src/cli/download_tracker.rs#L223-L225
with custom Display implementation for `std::time::Duration`.

**Comment by kinnison** [comment]
What will this do, where in the codebase are you suggesting changes, etc?  This is a very poor issue and would be impossible for a new contributor to understand if they'd be able to do this.

**Comment by tesuji** [comment]
Sorry, it was a poor issue. I hope I make the issue description better now.
