### ISSUE TITLE
Why Rustup prefer windows-gnu toolchain over windows-msvc on Travis Windows build?

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rustup#2187]
**Problem: Can we make rustup prefer windows-msvc by default (not with any flags)?**

When using rustup on Travis Windows build environment, rustup prefer windows-gnu
toolchain over windows-msvc [1]. Although that environment contains `vctools` [2].

[1]: https://travis-ci.com/rust-lang/rust-clippy/jobs/272814784#L54
[2]: https://docs.travis-ci.com/user/reference/windows/#pre-installed-chocolatey-packages

**Comment by tesuji** [comment]
Forgot to tell. I use rustup-init.sh to to install Rustup. Maybe this is the reason.
```bash
curl -sSL https://sh.rustup.rs | sh -s -- -y --default-toolchain=nightly --profile=minimal
```

**Comment by kinnison** [comment]
if you use the shell script you'll get the GNU variant by default.  If you use https://win.rustup.rs/ you'll get the msvc variant.

You should *always* set the host and toolchain you want for CI in case your host system changes type or defaults change in rustup

**Comment by tesuji** [comment]
Thanks. I think I should custom the script.
Closed as non fix.
