### ISSUE TITLE
rustup.sh fails on /bin/sh on openindiana with local: not found

### ISSUE THREAD

**Issue by exorcist365** [rust-lang/rustup#2189]
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
sh[378]: local: not found [No such file or directory]
sh[170]: local: not found [No such file or directory]
rustup: unrecognized OS type: SunOS

**Comment by emilyalbini** [comment]
Transferred the issue.

**Comment by kinnison** [comment]
Hi @JoanM1lev thanks for contacting us.

At this time, Illumos is tier 2 and only `std` is built.  As such, `rustup` can't be used on that platform.  You can use Linux or another OS and cross-build for that target, but not build natively as far as I understand.

**Comment by kinnison** [comment]
Oh in addition, if `sh` on Illumos isn't POSIX then that'd explain why it failed on `local` and friends.

**Comment by rbtcollins** [comment]
We'd be happy with patches to detect a POSIX sh on openindiana and invoke it appropriately, though that won't help with the lack of built components etc. I've tagged this help wanted to indicate that the rustup team themselves are not going to get to this (while Ilumos is tier 2 anyhow).

**Comment by jclulow** [comment]
NB: As of the latest release of `rustup`, I believe the script now correctly detects the `ksh93` shell that doesn't support `local` and suggests to the user they should use `bash` instead:

```
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup does not work with this ksh93 version; please try bash!
```
