### ISSUE TITLE
Warn when a rustup-init argument is ignored/changed

### ISSUE THREAD

**Issue by flaviojs** [rust-lang/rustup#2194]
**Describe the problem you are trying to solve**

This is a followup to #2188.
Since `rustup-init` shouldn't be used to set up cross-compiling with mingw, at the very least it should warn when an argument is ignored/changed.

Without a warning I would think that everything is setup as expected.
This leads to wasting a lot of time trying to figure out what is wrong when a problem arises.

**Describe the solution you'd like**

I'm not sure what the stated reasons should be but I would like a warning with enough information.

Examples:
 * for --default-toolchain=1.36.0-x86_64-pc-windows-gnu
    ```
    default toolchain changed to 1.36.0-x86_64-unknown-linux-gnu: reason
    ```
 * for --default-toolchain=1.36.0 --target=x86_64-pc-windows-gnu
    ```
    target x86_64-pc-windows-gnu was ignored: reason
    ```

Maybe something else would be appropriate but this is all I can think of without knowledge of the internals.

**Comment by kinnison** [comment]
In the former mode, `rustup-init` will, as instructed, download and install the mingw toolchain and set it as the default.

If you're doing that on Linux, then it'll result in a toolchain which will likely only run if you have wine set up properly, but if you do, then it'll work just fine most likely.

In the latter mode, `rustup-init` will add the target you specify as part of the install...

```console
rustuptest@somniloquy:~$ sh rustup-init.sh --default-toolchain=1.36.0 --target=x86_64-pc-windows-gnu -y
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: syncing channel updates for '1.36.0-x86_64-unknown-linux-gnu'
info: latest update on 2019-07-04, rust version 1.36.0 (a53f9df32 2019-07-03)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std' for 'x86_64-pc-windows-gnu'
 60.3 MiB /  60.3 MiB (100 %)  24.7 MiB/s in  2s ETA:  0s
info: downloading component 'rust-std'
 61.3 MiB /  61.3 MiB (100 %)  24.1 MiB/s in  2s ETA:  0s
info: downloading component 'rustc'
 91.1 MiB /  91.1 MiB (100 %)  13.9 MiB/s in  7s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
 11.0 MiB /  11.0 MiB (100 %)   8.3 MiB/s in  1s ETA:  0s
info: installing component 'rust-std' for 'x86_64-pc-windows-gnu'
 60.3 MiB /  60.3 MiB (100 %)  18.0 MiB/s in  3s ETA:  0s
info: installing component 'rust-std'
 61.3 MiB /  61.3 MiB (100 %)  16.4 MiB/s in  3s ETA:  0s
info: installing component 'rustc'
 91.1 MiB /  91.1 MiB (100 %)  14.1 MiB/s in  6s ETA:  0s
info: installing component 'rustfmt'
info: default toolchain set to '1.36.0'

  1.36.0 installed - rustc 1.36.0 (a53f9df32 2019-07-03)
...
rustuptest@somniloquy:~$ 
```

None of the arguments you passed to rustup-init in your two examples were ignored or changed.  I'm not sure what you're asking for here.

The only useful warning I can see might be in the *first* case, it might be helpful to have something along the lines of:

```
warning: Default toolchain host does not match system host or rustup build.  It may not run.
warning: Did you mean --target=whatever-target-was-in-that-toolchain
```

Is that the sort of thing you're after?

**Comment by flaviojs** [comment]
That sort of warning would certainly help.
It would be the first thing to try if I got a problem.

----

I tried the later mode once again and got the same error: https://github.com/flaviojs/tmp-ja2-stracciatella/runs/382024157

In your case it started downloading right away.
In my case it only downloaded when `rustup show` was executed.
No idea why it's different.

**Comment by kinnison** [comment]
The critical difference in what you linked is https://github.com/flaviojs/tmp-ja2-stracciatella/runs/382024157#step:4:268 -- you're overriding the toolchain with `rust-toolchain`

In addition you're using a system which already has Rust installed so if you look at when you run `rustup-init` you'll see that it didn't actually install that toolchain at that point.

As a result, the `rustup show` installed the toolchain because of the override, but at that point you couldn't have specified the additional target because there's no way to do that with the `rust-toolchain` file.

Unfortunately that's a side-effect of the fact that github-actions default systems include a preinstalled (not-up-to-date) stable toolchain for Rust.

**Comment by flaviojs** [comment]
So `rustup-init` ignored `--default-toolchain=1.36.0 --target=x86_64-pc-windows-gnu` because rustup was already installed?

Then I would like a warning for that, maybe:
```
warning: rustup is already installed, ignoring arguments --default-toolchain=1.36.0 --target=x86_64-pc-windows-gnu
```

**Comment by kinnison** [comment]
Hmm, I wonder if the right answer is that if those arguments are passed and we're already installed, we should actually try and honour them.  I think this is related to https://github.com/rust-lang/rustup/blob/master/src/cli/self_update.rs#L749 and already carries a FIXME so perhaps we need to work through that.

**Comment by kinnison** [comment]
I've whipped up a patch which I am currently testing and then will need to write some more test cases but I might get a PR up either tonight or tomorrow morning for your consideration.

**Comment by flaviojs** [comment]
Hmm, the reason I didn't think much about stuff being installed with `rustup show` was because I've used programs that only download components when needed. I just assumed it was the same (that it was initialized correctly and downloaded on demand).

There should be a message saying that it's installing because the overridden toolchain isn't present/set up. Should I open a new issue for that?

**Comment by kinnison** [comment]
I think that it might be reasonable to emit an info: at that point yes.  Please feel free to file an issue with suggested wording for that.
