### ISSUE TITLE
Website: show whole shell command at once

### ISSUE THREAD

**Issue by birkenfeld** [rust-lang/rustup#2207]
Since the TLS related options were added, the main https://rustup.rs/ page shows only a fraction of the shell command (see below).

Even copying the command is getting cumbersome with this, and it would be nice to see the whole thing I'm supposed to run...

![image](https://user-images.githubusercontent.com/144359/72685220-5587ac80-3ae8-11ea-9a20-5ded37fcdc11.png)

**Comment by kinnison** [comment]
I'd love it if someone would contribute an HTML/CSS update to fix this.

**Comment by birkenfeld** [comment]
I'm no good at modern CSS, unfortunately.
