### ISSUE TITLE
fresh installs on linux currently installing 1.40.0

### ISSUE THREAD

**Issue by ghost** [rust-lang/rustup#2222]
**Problem**

Fresh installs on linux using the command
`curl https://sh.rustup.rs/ -sSf | sh -s -- -y --default-toolchain stable`
are currently installing rust 1.40.0 instead of 1.41.0

**Steps**

1. Have a linux machine with no rust
2. run `curl https://sh.rustup.rs/ -sSf | sh -s -- -y --default-toolchain stable`
3. installed rust will be 1.40.0

**Possible Solution(s)**

**Comment by rbtcollins** [comment]
Can we get the transcript from that please?

**Comment by kinnison** [comment]
My guess is that this is on a CI system where 1.40 is already installed.  If so, then #2201 will resolve that in the next release of rustup.

**Comment by ghost** [comment]
@kinnison yes, that is the issue. I tried modifying my scripts to run rustup update, but ran into a weird wall where MacOS wasn't picking up the PATH changes. I'll just wait for the next release. Thanks!

**Comment by kinnison** [comment]
If it's helpful @ZoeyR you can look at Rustup's github workflows for ideas on how to manage this in the meantime.
