### ISSUE TITLE
rustup not on $PATH after installing

### ISSUE THREAD

**Issue by ZacBlanco** [rust-lang/rustup#2226]
**Problem**

I am running Ubuntu Server 18.04 + the `ubuntu-desktop` package. After using the script at `https://rustup.rs` the toolchains are installed properly, but not immediately accessible on my `$PATH`.

**Steps**

1. Run the rustup installation command at `https://rustup.rs`
2. Select option 1 (default install)
3. Close terminal and re-open a new terminal (`gnome-terminal` is what I use)
4. Run `rustup` or `cargo` and the executable is not found 

**Possible Solution(s)**

I noticed that the path to `~/.cargo/bin` is added to `~/.profile`, `~/.bash_profile`, but not `~/.bashrc`

When opening the gnome terminal is seems that it only respects the `~/.bashrc` - once I added it to that file I was able to start new terminals with `cargo` and `rustup` without modifying `$PATH`.

I am more than happy to contribute a PR which adds `~/.cargo/bin` to the `~/.bashrc` as well - but I wanted to discuss what the proper solution should be before creating a PR.

**Notes**

Output of `rustup --version`: 
```
rustup 1.21.1 (7832b2ebe 2019-12-20)
```
Output of `rustup show`:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/zac/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.41.0 (5e1a79984 2020-01-27)
```

**Comment by rbtcollins** [comment]
The issue is that you haven't actually started a new login shell. Run bash --login and you should be fine, or follow the instructions printed by rustup for using rustup before new logins take place.

We have to use `~/.bash_profile` to operate correctly when invoked in scripts and non-interactive contexts, but this does have the behaviour you have observed. We could perhaps add sections to both places, but we'd want to guard against having the same entry in path twice.

<details>
<summary>Here is the bash man page section on invocation:</summary>

```
INVOCATION
       A login shell is one whose first character of argument zero is a -, or one started with the --login option.

       An interactive shell is one started without non-option arguments (unless -s is specified) and without the -c option whose standard in‐
       put and error are both connected to terminals (as determined by isatty(3)), or one started with the -i option.  PS1 is set and $-  in‐
       cludes i if bash is interactive, allowing a shell script or a startup file to test this state.

       The  following paragraphs describe how bash executes its startup files.  If any of the files exist but cannot be read, bash reports an
       error.  Tildes are expanded in filenames as described below under Tilde Expansion in the EXPANSION section.

       When bash is invoked as an interactive login shell, or as a non-interactive shell with the --login option, it first reads and executes
       commands  from  the file /etc/profile, if that file exists.  After reading that file, it looks for ~/.bash_profile, ~/.bash_login, and
       ~/.profile, in that order, and reads and executes commands from the first one that exists and is readable.  The --noprofile option may
       be used when the shell is started to inhibit this behavior.

       When  an  interactive  login  shell exits, or a non-interactive login shell executes the exit builtin command, bash reads and executes
       commands from the file ~/.bash_logout, if it exists.

       When an interactive shell that is not a login shell is started, bash reads and executes commands from /etc/bash.bashrc and  ~/.bashrc,
       if these files exist.  This may be inhibited by using the --norc option.  The --rcfile file option will force bash to read and execute
       commands from file instead of /etc/bash.bashrc and ~/.bashrc.
```

</details>

**Comment by ZacBlanco** [comment]
I'm aware it's because I'm not using a login shell - but by default the `gnome-terminal` GUI starts all shells _without_ the `--login` option within the Ubuntu desktop. 

I think the preferred behavior would have people not needing to re-configure their terminal application to get the binaries on the path. From a user's perspective it's just not as friendly.

I can see arguments for not including the addition to `~/.bashrc`. If we don't want to add it there, then maybe add a note in the installer output that  says something like "the bash shell should be started with the `--login` option, or else it won't automatically be added to the PATH"?

**Comment by ZacBlanco** [comment]
So after doing a full logout on the Ubuntu desktop, then logging back in everything works, even without the addition to `~/.bashrc` or changing the gnome-terminal settings

Is there anything we can do in the background to not perform a full logout in that case? I'm guessing not. I guess I just wish there was a way that "just works" without the user having to do anything after running the rustup installer other than that `source` command.

Edit: I'm going to close this issue because it  _does_ work after fully logging out, and then back in again. I just expected it to be more closing and re-opening a terminal window to get the change.

**Comment by rbtcollins** [comment]
I agree that its not as friendly; having code in both places would be needed I think; I don't think the gnome config is in any way wrong or erroneous.
