### ISSUE TITLE
README about profiles encourages use of `complete` which is a bad idea

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rustup#2228]
The `README.md` profiles section needs adjusting to not mislead people into thinking `complete` is a good idea for the general users because it'll almost never work.

This should be a relatively easy fix to make.

I'm happy to help someone through making this change.

**Comment by LeSeulArtichaut** [comment]
What about adding something like the following?
```markdown
This is likely to fail because of missing components. If you are unsure whether you need it or not, you should go with the `default` profile and manually add components when you need them.
```

**Comment by kinnison** [comment]
I think removing the emphasis on the IDE support is also necessary because otherwise it leads people to want to use `complete` when really `default` should be their goal.  IDEs auto-install missing components on-demand generally.

**Comment by rbtcollins** [comment]
I think it needs to be actively say that complete is a bad idea.

Something like "`complete` is a bad idea because every it includes every component ever included in the metadata, including many that do not currently build and as a result it will fail to install.".
