### ISSUE TITLE
rustc and cargo out of sync

### ISSUE THREAD

**Issue by JesterOrNot** [rust-lang/rustup#2251]
**Problem**
rustc version and cargo versions out of sync
They should be the same

**Steps**

1. Run 
```sh
rustup toolchain install 1.41.1 && .cargo/bin/rustup default 1.41.1 
```
2. Run `rustc --version`
3. Run `cargo --version`
4. See mismatch

**Notes**

Output of `rustup --version`:
```
rustc 1.41.1 (f3e1a954d 2020-02-24)
```
Output of `rustup show`:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/gitpod/.rustup

installed toolchains
--------------------

1.41.0-x86_64-unknown-linux-gnu
1.41.1-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

1.41.1-x86_64-unknown-linux-gnu (default)
rustc 1.41.1 (f3e1a954d 2020-02-24)
```
~

**Comment by jyn514** [comment]
@JesterOrNot I think this is intended behavior because there was no change to cargo in the `1.41.1` backport. See https://blog.rust-lang.org/2020/02/27/Rust-1.41.1.html.

**Comment by JesterOrNot** [comment]
Thanks!
