### ISSUE TITLE
Rephrase Security section of readme to avoid offending security conscious

### ISSUE THREAD

**Issue by programmerjake** [rust-lang/rustup#2262]
https://github.com/rust-lang/rustup/blob/1db9dc9d26682fc71eb05a0d1ae5d81ef3f1c4ac/README.md#L777-L779

I suggest replacing `the non-paranoid` with `most people`.

**Comment by programmerjake** [comment]
This should probably be high-priority.

**Comment by kinnison** [comment]
Given how old this wording is, I'm not sure that it's terribly offensive, however if you are unhappy with it then you're welcome to file a pull request to change the wording.  I don't object to "softening" it a little.
