### ISSUE TITLE
Can't install Rust 1.0 or 1.1 on macOS

### ISSUE THREAD

**Issue by nvzqz** [rust-lang/rustup#2263]
**Problem**
When I run `rustup install 1.0.0`, it fails with:

```
info: syncing channel updates for '1.0.0-x86_64-apple-darwin'
info: downloading component 'rust'
 88.3 MiB /  88.3 MiB (100 %) 675.2 KiB/s in  2m 18s ETA:  0s    
info: installing component 'rust'
info: rolling back changes
error: tar path './._rust-1.0.0-x86_64-apple-darwin' is not supported
```

I get a similar error with installing `rustup install 1.1.0`. However, `1.2.0` works.

**Steps**
1. Run macOS 10.15 (Catalina)
2. `rustup install 1.0.0`

**Possible Solution(s)**

**Notes**

Running `which tar` reports `/usr/bin/tar`, which is a symlink to `/usr/bin/bsdtar`. I don't think this is part of the problem, but worth knowing.

Output of `rustup --version`:

```
rustup 1.21.1 (7832b2ebe 2019-12-20)
```

Output of `rustup show`:

```
Default host: x86_64-apple-darwin
rustup home:  /Users/nvzqz/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
beta-x86_64-apple-darwin
nightly-x86_64-apple-darwin
1.20.0-x86_64-apple-darwin
1.25.0-x86_64-apple-darwin
1.29.0-x86_64-apple-darwin
1.31.0-x86_64-apple-darwin
1.32.0-x86_64-apple-darwin
1.33.0-x86_64-apple-darwin
1.34.0-x86_64-apple-darwin
1.36.0-x86_64-apple-darwin
1.37.0-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.41.0 (5e1a79984 2020-01-27)
```

**Comment by kinnison** [comment]
@rbtcollins I think this comes down to the tar path sanity checking we do during install, do you agree?

If so, what would we need to do to teach `rustup` to understand these valid, if unpleasant, toolchain tarballs?

**Comment by rbtcollins** [comment]
I think it is; I was pretty sure we didn't regress that, but I guess we did. Someone needs to expand this code appropriately:

```
       // Reject path components that are not normal (.|..|/| etc)
        for part in relpath.components() {
            match part {
                std::path::Component::Normal(_) => {}
                _ => return Err(ErrorKind::BadPath(relpath).into()),
            }
        }
```

**Comment by kinnison** [comment]
I'd guess that permitting `std::path::Component::CurDir` might be sufficient
