### ISSUE TITLE
Missing backslash in printed CARGO_HOME path on Windows

### ISSUE THREAD

**Issue by Simran-B** [rust-lang/rustup#2272]
**Problem**

I installed Rust using rustup under Windows 10 and noticed a missing backslash in the post install message which tells you the Cargo bin directory:

```
Rust is installed now. Great!

To get started you need Cargo's bin directory (%USERPROFILE%.cargo\bin) in your
PATH
environment variable. Future applications will automatically have the
correct environment, but you may need to restart your current shell.

Press the Enter key to continue.
```

It should be `%USERPROFILE%\.cargo\bin` with a backslash after `%USERPROFILE%` to be valid.

Note that it printed the following earlier:

```
It will add the cargo, rustc, rustup and other commands to
Cargo's bin directory, located at:

  C:\Users\Simran\.cargo\bin
```

And it added this to the PATH environment variable correctly.

**Steps**

1. [Download rustup-init.exe (64-bit)](https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe)
2. `1) Proceed with installation (default)`
3. Wait until installation completes and check the last block of messages

**Possible Solution(s)**

The message is coming from here:

_src\cli\self_update.rs_

```rust
macro_rules! post_install_msg_win {
    () => {
        r"# Rust is installed now. Great!

To get started you need Cargo's bin directory ({cargo_home}\\bin) in your `PATH`
environment variable. Future applications will automatically have the
correct environment, but you may need to restart your current shell.
"
    };
}
```

The backslash before `bin` (which shows correctly) is escaped, but the rest is coming from the variable `cargo_home`. Interestingly, a different variable is used for the other message, `cargo_home_bin`:

```rust
macro_rules! pre_install_msg_template {
…
It will add the `cargo`, `rustc`, `rustup` and other commands to
Cargo's bin directory, located at:

    {cargo_home_bin}
```

It could be used instead of `{cargo_home}\\bin` I guess, but with the env var `%USERPROFILE%` resolved. I'm not sure how else to fix the problem. The following looks alright using a raw string, removing the need for escaping the backslash:

```rust
fn canonical_cargo_home() -> Result<String> {
…
            path_str = String::from(r"%USERPROFILE%\.cargo");
```

Or does it need to be double-escaped to `r"%USERPROFILE%\\.cargo"` (non-raw `"%USERPROFILE%\\\\.cargo"` I suppose)?

**Notes**

Output of `rustup --version`: rustup 1.21.1 (7832b2ebe 2019-12-20)

Output of `rustup show`:

```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Simran\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.42.0 (b8cedc004 2020-03-09)
```

**Comment by kinnison** [comment]
Some work was put toward this, but failed to get things consistent it seems.  Time to do some more.  Anyone with a Windows system ought to be able to work on this.

**Comment by rbtcollins** [comment]
Anyone with a hypervisor can install a development VM from MS to get a windows dev environment too.

**Comment by Simran-B** [comment]
I'm on Windows and even fought with Windows containers under Windows in Docker recently, but I need to know in what way you think it _should_ be fixed. Should it display
- `%USERPROFILE%\.cargo\bin` or
- `C:\Users\Simran\.cargo\bin` (env vars expanded or not)?

The other question seems to be whether there is a bug in the code which processes the path string. It appears to remove the backslash from the input?

**Comment by rbtcollins** [comment]
I think it should show `%USERPROFILE%\.cargo\bin`

**Comment by Simran-B** [comment]
Thank you @lzutao for taking care of this! Looking at the diff, this was way more involved than I anticipated.

**Comment by ret394** [comment]
> rustup show



>     * C:\Users\Simran\.cargo\bin

same on ubuntu.

**Comment by tesuji** [comment]
What do you mean @ret394 ?
