### ISSUE TITLE
When I wanted to install rustup in win10, something wrong has occurred: error: component download failed for cargo-x86_64-pc-windows-msvc

### ISSUE THREAD

**Issue by MissDinosaur** [rust-lang/rustup#2273]

**Comment by MissDinosaur** [comment]
Here is the detail.
---------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/48971343/77818994-5a816180-7112-11ea-8643-84e165f12fef.png)

No matter how many times I try, the result is always the same. I am a beginner  to rust, so I need your help. Thank you really.

**Comment by rbtcollins** [comment]
This is typically caused by an antivirus program holding a lock on the file the installer is attempting to rename. What anti-virus / anti-malware software are you using? Could you add an exclusion for your homedir\.rustup temporarily to let rustup complete? (or turn it off while running rustup?).

**Comment by MissDinosaur** [comment]
I moved the rustup-init.exe file into C:\, which was advised by a senior developer in my team.  Fortunately, it worked well. I did not turn off the anti-malware software in my computer. Hope this can help other people who come with the same problem when installing Rust in win10.

**Comment by MissDinosaur** [comment]
> This is typically caused by an antivirus program holding a lock on the file the installer is attempting to rename. What anti-virus / anti-malware software are you using? Could you add an exclusion for your homedir.rustup temporarily to let rustup complete? (or turn it off while running rustup?).

Thank you very much anyway.

**Comment by Deartomy** [comment]
> I moved the rustup-init.exe file into C:, which was advised by a senior developer in my team. Fortunately, it worked well. I did not turn off the anti-malware software in my computer. Hope this can help other people who come with the same problem when installing Rust in win10.

thanks， I met the same problem， and follow your advice to fix it~~

**Comment by Week2019** [comment]
> 我将 rustup-init.exe 文件移到 C: 中，这是我团队中的一位高级开发人员建议的。幸运的是，它运作良好。我没有关闭计算机中的反恶意软件。希望这可以帮助其他在 win10 中安装 Rust 时遇到同样问题的人。

感谢，在更新1.5.6的时候，我也碰到同样的问题，在将rustup-init.exe移动到C盘后，问题得到了解决
