### ISSUE TITLE
rustup-init script cryptically broken on x32

### ISSUE THREAD

**Issue by nabijaczleweli** [rust-lang/rustup#2279]
**Problem**
```
nabijaczleweli@szarotka:~$ curl -SL https://sh.rustup.rs -orustup-init.sh
nabijaczleweli@szarotka:~$ chmod +x rustup-init.sh
nabijaczleweli@szarotka:~$ ./rustup-init.sh
info: downloading installer
./rustup-init.sh: line 372: /tmp/tmp.CaHu1vE1eo/rustup-init: No such file or directory
```

**Steps**
1. Be on an x32 machine
2. See above

**Notes**

Output of `rustup --version`: N/A
Output of `rustup show`: N/A

```
nabijaczleweli@szarotka:~$ uname -a
Linux szarotka 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux
nabijaczleweli@szarotka:~$ dpkg --print-architecture
x32
nabijaczleweli@szarotka:~$ dpkg-architecture | grep ^DEB_HOST
DEB_HOST_ARCH=x32
DEB_HOST_ARCH_ABI=x32
DEB_HOST_ARCH_BITS=32
DEB_HOST_ARCH_CPU=amd64
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_LIBC=gnu
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=x86_64
DEB_HOST_GNU_SYSTEM=linux-gnux32
DEB_HOST_GNU_TYPE=x86_64-linux-gnux32
DEB_HOST_MULTIARCH=x86_64-linux-gnux32
nabijaczleweli@szarotka:~$ gcc -dumpmachine
x86_64-linux-gnux32
```

I added `echo "$_arch"` after the `assert_nz` check and got
```
nabijaczleweli@szarotka:~$ ./rustup-init.sh -v
i686-unknown-linux-gnu
info: downloading installer
./rustup-init.sh: line 373: /tmp/tmp.hbNWqOlGKq/rustup-init: No such file or directory
```
which is definitely not right.

**Comment by arcuru** [comment]
In addition to that looking like the download silently failed, I think the expected arch version is [x86_64-unknown-linux-gnux32](https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnux32.html) and `rustup-init.sh` doesn't attempt to detect it, so that's at least one issue. I suspect it falls into [this branch](https://github.com/rust-lang/rustup/blob/5d9d98059273c60de52c2abe573d79cd3f623de4/rustup-init.sh#L304).

I'm not too familiar with how Rust handles the different Tiers of architecture support, but [this link](https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnux32.html) suggests the compiler isn't even built for x32. If you have multiarch support for x64 installed I'd suggest trying to install that toolchain directly.

**Comment by kinnison** [comment]
Certainly `x86_64 x32` is not supported by rustup at this time.  Perhaps we could detect this situation and offer the x86_64 x64 binary but we'd have to try and work out if that is even plausible.  Another option is to detect the `x32` ABI and say "nope" in an earlier and more friendly way.

@rbtcollins opinion?

**Comment by rbtcollins** [comment]
https://wiki.debian.org/X32Port is useful reading. As I read it there is no guarantee that the x86_64 binary would work - as @patricksjackson says, multiarch support for x64 would need to be present to permit downloading and running that instead.

I don't think we should second guess the user too much - that will then bite us if folk get builds working and we then have to choose between breaking backward compat behaviour or now honouring the users chosen arch.

I do think we should detect the failed download properly, which would make the failure less cryptic. And probably show the url we tried to download, to make diagnosis easier.

**Comment by nabijaczleweli** [comment]
The only amd64 packages I have is the kernel:
```
nabijaczleweli@szarotka:~$ dpkg -l *:amd64
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                            Version      Architecture Description
+++-===============================-============-============-===================================
ii  linux-image-5.4.0-4-amd64:amd64 5.4.19-1     amd64        Linux 5.4 for 64-bit PCs (signed)
ii  linux-image-amd64:amd64         5.4.19-1     amd64        Linux for 64-bit PCs (meta-package)
```

Tried to download for amd64, to no avail, since it tries to download for the same quad no matter what host I specify
```
nabijaczleweli@szarotka:~$ ./rustup-init.sh --default-host x86_64-unknown-linux-gnu
info: downloading installer
./rustup-init.sh: line 372: /tmp/tmp.f9FXOMUUlK/rustup-init: No such file or directory
```
Apparently the URL is https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init (getting there was a challenge, due to the high-quality 404 page, but that's a bug for a different repo) – and doesn't work, because I don't have `libc6` (and therefore the interpreter), which leads to a hilarious error message
```
nabijaczleweli@szarotka:~$ file rustup-init
rustup-init: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.9, with debug_info, not stripped
nabijaczleweli@szarotka:~$ ./rustup-init
-bash: ./rustup-init: No such file or directory
```

After installing `libc6:amd64`, this is even more cryptic
```
nabijaczleweli@szarotka:~$ ./rustup-init --default-host x86_64-unknown-linux-gnux32
error: Pre-checks for host and toolchain failed: Provided host 'x86_64-unknown-linux-gnux32' couldn't be converted to partial triple
If you are unsure of suitable values, the 'stable' toolchain is the default.
Valid host triples look something like: x86_64-unknown-linux-gnu
```
Since that's *definitely* a valid LLVM quad??

Thankfully I don't *need* to run Rust on that box and rewrote the utils I needed in C (if I did, I'd build for amd64, which is a little stinky but works, I guess?), but the installation process is, well…

**Comment by kinnison** [comment]
We're limited to the platforms which the Rust core team provide supportable build environments for.  We won't support gnux32 until/unless the compiler people do.  What we *can* do is improve the shell script so that it detects and reports this, and then attempts to DTRT to acquire something which might actually run.  Defining that heuristic is what we need to do next I think.

**Comment by rbtcollins** [comment]
I think it downloaded something that might run (when 64-bit multi-arch is installed), but the shell script is missing safeguards to not attempt it when muilti-arch isn't present, *and* rustup-init rejects the host triple.

I'm not sure that a DTRT heuristic is at all wise, as I said, I think it will become a footgun in future. Better to bail out and say clearly not supported - if someone wants to install a multi-arch rustup, we should provide a dedicated way to do that, and they should use that way.

**Comment by kinnison** [comment]
I think that's reasonable.  Should we generate a list of supported triples in the CI and amend the script to use that perhaps?
