### ISSUE TITLE
Copy button for Unix installation command on Rustup.rs

### ISSUE THREAD

**Issue by jazeved0** [rust-lang/rustup#2280]
**Describe the problem you are trying to solve**

On the main [rustup.rs](https://rustup.rs/) installation site, the Unix installation command is very long and copying it requires having to click and drag while scrolling or triple-clicking.

![unix command](https://i.imgur.com/1EOtAIG.png)

**Describe the solution you'd like**

Having a small button or intractable area that copies the command to the clipboard (and it provides feedback that it has done so) would make the installation process easier.

**Examples**

[Crates.io](https://crates.io/crates/lru) crate pages:
![lru](https://i.imgur.com/vFvES4M.png)

[Npm](https://www.npmjs.com/package/react) package pages:
![react](https://i.imgur.com/NtWsnfy.png[/img)

**Notes**

The fact that the crates.io team has already implemented this makes it seem like using/looking at their implementation would be worthwhile.

**Comment by kinnison** [comment]
I think this is a good idea.  If anyone wants to sort the HTML and JS out for us then that'd be good.  It's worth noting though that we're considering deprecating rustup.rs in favour of www.rust-lang.org and their style is wider -- https://www.rust-lang.org/tools/install
