### ISSUE TITLE
'X' is not installed for windows toolchains on unix hosts

### ISSUE THREAD

**Issue by justintim-es** [rust-lang/rustup#2283]
I get the following error
```
error: 'cargo' is not installed for the toolchain 'stable-x86_64-pc-windows-msvc'
To install, run `rustup component add cargo`
```
after running the command error stays the same

**Comment by Mark-Simulacrum** [comment]
I've transferred this issue over to the rustup repository, since that's likely where the bug is.

**Comment by kinnison** [comment]
Hi @noahsalvadordenjo sorry it has taken so long to get to you.

I'm guessing from your original issue that the system in question is a Windows box.  Is it running 64-bit windows?

Could you please give us the output of the following commands:

1. `rustup show`
2. `rustup component list`

Once you've done that, I may have further questions.

**Comment by justintim-es** [comment]
Im running an ubuntu terminal on google cloud.
```
rustup show
```
gives me
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/noahbergh/.rustup
installed toolchains
--------------------
stable-x86_64-pc-windows-msvc (default)
stable-x86_64-unknown-linux-gnu
active toolchain
----------------
stable-x86_64-pc-windows-msvc (default)
(rustc does not exist)
```
```
rustup component list
```
gives me
```
cargo-x86_64-pc-windows-msvc (installed)
clippy-x86_64-pc-windows-msvc (installed)
llvm-tools-preview-x86_64-pc-windows-msvc
rls-x86_64-pc-windows-msvc
rust-analysis-x86_64-pc-windows-msvc
rust-docs-x86_64-pc-windows-msvc (installed)
rust-src
rust-std-aarch64-apple-ios
rust-std-aarch64-fuchsia
rust-std-aarch64-linux-android
rust-std-aarch64-pc-windows-msvc
rust-std-aarch64-unknown-linux-gnu
rust-std-aarch64-unknown-linux-musl
rust-std-arm-linux-androideabi
rust-std-arm-unknown-linux-gnueabi
rust-std-arm-unknown-linux-gnueabihf
rust-std-arm-unknown-linux-musleabi
rust-std-arm-unknown-linux-musleabihf
rust-std-armebv7r-none-eabi
rust-std-armebv7r-none-eabihf
rust-std-armv5te-unknown-linux-gnueabi
rust-std-armv5te-unknown-linux-musleabi
rust-std-armv7-linux-androideabi
rust-std-armv7-unknown-linux-gnueabi
rust-std-armv7-unknown-linux-gnueabihf
rust-std-armv7-unknown-linux-musleabi
rust-std-armv7-unknown-linux-musleabihf
rust-std-armv7a-none-eabi
rust-std-armv7r-none-eabi
rust-std-armv7r-none-eabihf
rust-std-asmjs-unknown-emscripten
rust-std-i586-pc-windows-msvc
rust-std-i586-unknown-linux-gnu
rust-std-i586-unknown-linux-musl
rust-std-i686-linux-android
rust-std-i686-pc-windows-gnu
rust-std-i686-pc-windows-msvc
rust-std-i686-unknown-freebsd
rust-std-i686-unknown-linux-gnu
rust-std-i686-unknown-linux-musl
rust-std-mips-unknown-linux-gnu
rust-std-mips-unknown-linux-musl
rust-std-mips64-unknown-linux-gnuabi64
rust-std-mips64-unknown-linux-muslabi64
rust-std-mips64el-unknown-linux-gnuabi64
rust-std-mips64el-unknown-linux-muslabi64
rust-std-mipsel-unknown-linux-gnu
rust-std-mipsel-unknown-linux-musl
rust-std-nvptx64-nvidia-cuda
rust-std-powerpc-unknown-linux-gnu
rust-std-powerpc64-unknown-linux-gnu
rust-std-powerpc64le-unknown-linux-gnu
rust-std-riscv32i-unknown-none-elf
rust-std-riscv32imac-unknown-none-elf
rust-std-riscv32imc-unknown-none-elf
rust-std-riscv64gc-unknown-linux-gnu
rust-std-riscv64gc-unknown-none-elf
rust-std-riscv64imac-unknown-none-elf
rust-std-s390x-unknown-linux-gnu
rust-std-sparc64-unknown-linux-gnu
rust-std-sparcv9-sun-solaris
rust-std-thumbv6m-none-eabi
rust-std-thumbv7em-none-eabi
rust-std-thumbv7em-none-eabihf
rust-std-thumbv7m-none-eabi
rust-std-thumbv7neon-linux-androideabi
rust-std-thumbv7neon-unknown-linux-gnueabihf
rust-std-thumbv8m.base-none-eabi
rust-std-thumbv8m.main-none-eabi
rust-std-thumbv8m.main-none-eabihf
rust-std-wasm32-unknown-emscripten
rust-std-wasm32-unknown-unknown
rust-std-wasm32-wasi
rust-std-x86_64-apple-darwin
rust-std-x86_64-apple-ios
rust-std-x86_64-fortanix-unknown-sgx
rust-std-x86_64-fuchsia
rust-std-x86_64-linux-android
rust-std-x86_64-pc-windows-gnu
rust-std-x86_64-pc-windows-msvc (installed)
rust-std-x86_64-rumprun-netbsd
rust-std-x86_64-sun-solaris
rust-std-x86_64-unknown-cloudabi
rust-std-x86_64-unknown-freebsd
rust-std-x86_64-unknown-linux-gnu
rust-std-x86_64-unknown-linux-gnux32
rust-std-x86_64-unknown-linux-musl
rust-std-x86_64-unknown-netbsd
rust-std-x86_64-unknown-redox
rustc-x86_64-pc-windows-msvc (installed)
rustc-dev-aarch64-unknown-linux-gnu
rustc-dev-arm-unknown-linux-gnueabi
rustc-dev-arm-unknown-linux-gnueabihf
rustc-dev-armv7-unknown-linux-gnueabihf
rustc-dev-i686-pc-windows-gnu
rustc-dev-i686-pc-windows-msvc
rustc-dev-i686-unknown-linux-gnu
rustc-dev-mips-unknown-linux-gnu
rustc-dev-mips64-unknown-linux-gnuabi64
rustc-dev-mips64el-unknown-linux-gnuabi64
rustc-dev-mipsel-unknown-linux-gnu
rustc-dev-powerpc-unknown-linux-gnu
rustc-dev-powerpc64-unknown-linux-gnu
rustc-dev-powerpc64le-unknown-linux-gnu
rustc-dev-s390x-unknown-linux-gnu
rustc-dev-x86_64-apple-darwin
rustc-dev-x86_64-pc-windows-gnu
rustc-dev-x86_64-pc-windows-msvc
rustc-dev-x86_64-unknown-freebsd
rustc-dev-x86_64-unknown-linux-gnu
rustc-dev-x86_64-unknown-linux-musl
rustc-dev-x86_64-unknown-netbsd
rustfmt-x86_64-pc-windows-msvc (installed)
```

**Comment by kinnison** [comment]
Okay, so the error message is unhelpful -- the real reason you're having difficulty is that you're running on Ubuntu (Linux) and trying to run an msvc (Windows) toolchain.

`rustup default stable` ought to switch you back to the Linux hosted toolchain and then `rustup toolchain uninstall stable-x86_64-pc-windows-msvc` will remove the unusable Windows toolchain.

**Comment by justinmoon** [comment]
@kinnison Thanks for explaining. I'm getting the same error trying to use `stable-x86_64-pc-windows-gnu` on Windows Subsystem Linux. Am I correct to understand that this also won't work inside Linux?

If this is the case, it would be helpful if rustup would loudly report an error when I run the following in a Linux environment:

```
$ rustup install stable-x86_64-pc-windows-gnu
info: syncing channel updates for 'stable-x86_64-pc-windows-gnu'

  stable-x86_64-pc-windows-gnu unchanged - (rustc does not exist)

info: checking for self-updates
```

**Comment by kinnison** [comment]
The thing is that with the right stuff installed in Linux you *could* run that toolchain.  It's a fine line between "You're doing the wrong thing" being helpful and being really annoying to those who know they're doing the right thing.  A 'rustc exists but cannot be run' error might be useful in this situation though.

**Comment by SonnyX** [comment]
Somehow it downloads `.exe` files, which for some reason work in WSL(2).
rename these `.exe`'s to an extensionless version, and your cargo will work once again.
These are located in `$HOME/.rustup/toolchains/{whatever toolchain you're using}/bin/`

**Comment by kinnison** [comment]
In general I'd recommend not doing this though, because it'll end up being very slow/confusing as crossing between the two environments lots isn't sensible.

**Comment by SonnyX** [comment]
In that case, what is the solution, other than not using WSL?
Some of us have reasons why we want to compile using a linux host instead of using the windows host, even if its for compiling windows binaries/libraries.

**Comment by rbtcollins** [comment]
I think 'cargo is not installed' is turning up because the host (linux) doesn't know to search for executables with '.exe' in the name. So this bug (ignoring the translation layer questions it raises) is really about how we search for executables.

I think we could perhaps search for both extensionless and .exe extensions on all hosts, or we could look at adding metadata (perhaps on tar extraction).

**Comment by kinnison** [comment]
Extending rustup to search for binaries with a `.exe` suffix, on platforms where it wouldn't normally, would solve this; but I wonder if it'll work because `cargo` may end up then trying to run `rustc.exe` rather than `rustc` and if so, it may result in a failure to find the compiler because `rustup-init` won't have created proxies with the `.exe` suffix in `$CARGO_HOME/bin`

**Comment by rbtcollins** [comment]
yeah; I suspect we probably need to tie the set of proxies we create into the exe-style of the installed toolchains. And thats a sort of coupling not currently present in rustup. (or just install both exe endings on platforms that can run both, which will produce bug reports and user unhappiness of its own).

Personally, I'm inclined to say that folk can create symlinks themselves for the proxies they need, and they should explicitly use a cargo.exe proxy to run a cargo.exe binary.

**Comment by kinnison** [comment]
Given we now warn when users install a toolchain which doesn't match their host platform I'm going to close this issue since the original poster would have been warned when they installed the wrong kind of toolchain.  If we want to do more on this we can reopen or file a fresh targetted issue.
