### ISSUE TITLE
An error should be reported when rustup is invoked with unsupported arg0

### ISSUE THREAD

**Issue by G-M0N3Y-2503** [rust-lang/rustup#2286]
**Problem**
In a windows docker image I had `C:/rustup-init.exe` with a Unicode hyphen which [caused the executable name match](https://github.com/rust-lang/rustup/blob/master/src/cli/main.rs#L80) to always default to `Some(_)` whereas `n.starts_with("rustup-init")` should be true with the right encoding.

**Steps**
1. replace the hyphen in `rustup-init.exe` with a [unicode hyphen](https://www.fileformat.info/info/unicode/char/2010/index.htm)
2. `rustup-init.exe --help`
3. an error is shown.
    In my docker image, I had "error: no default toolchain configured"

**Possible Solution(s)**
Encode the `OsStr` with UTF-8 encoding. 

**Notes**
Ended up compiling and testing this bug with the `1.21.1` tag

**Comment by rbtcollins** [comment]
I'm pretty sure that unicode hyphen would not compare equal to the regular hyphen even after utf8 encoding - U+002D != U+2010 - this issue occurred because the file was renamed with a visual spoof, and this can happen with other characters in the name as well. I think the important thing is to communicate that folk should not rename the file if they want it to perform setup-mode, but perhaps we should start supporting the environment override that is currently a developer-only tool.

**Comment by kinnison** [comment]
I'm not at all sure we should do anything other than refuse to run if the executable name is incorrect.  We know the set of proxies we install for, and the other names we support, so we should probably just refuse to run if it's not right.

**Comment by rbtcollins** [comment]
Yeah, I think thats reasonable.

**Comment by G-M0N3Y-2503** [comment]
Sounds good to me, A more specific error would have saved me a decent chunk of time.

**Comment by lynoure** [comment]
If the list at the top of lib.rs is relevant to this, I could take a stab at the issue. Given that I'm new to Rust, and totally new to contributing to rust-lang, some mentoring will probably needed still.

**Comment by kinnison** [comment]
@Lynoure Welcome to Rust.  if you use Discord then you should join the rust-lang discord server and find us in `#wg-rustup` where we can help you in semi-realtime.  if you prefer to discuss via issues/PRs though then that's fine too.

The list in lib.rs is the proxy list yes.  I'm imagining that we want to check that arg0 matches one of the specialist names already handled in the main code (see `bin/rustup-init.rs`)  and then check for a valid proxy name before returning a suitable error message.  We have some code to do near-matching for component names which you might crib from to offer a suggestion of a close command name if you wanted to go above-and-beyond :D
