### ISSUE TITLE
shell completions for rustc other rust tools

### ISSUE THREAD

**Issue by kolokd** [rust-lang/rustup#2288]
provide command to auto generate shell completions for rustc and other rust tools

A formal framework for generating shell completions for rust tool chain binaries 

completions should be user friendly and discoverable.

currently completions are available for rustup and cargo.

**Comment by vired** [comment]
https://github.com/rust-lang/rustup/issues/387

**Comment by kinnison** [comment]
This is an interesting idea, though it will require collusion with the compiler team to ensure completions are provided in a consistent fashion in the components.

**Comment by lzutao** [comment]
There are no official bash/zsh completion scripts for rustc and its tools.
One could start by contributing and maintaining it in https://github.com/rust-lang/rust
I think.

**Comment by kolokd** [comment]
i am not interested anymore
