### ISSUE TITLE
Colors are broken on MSYS2 shell.

### ISSUE THREAD

**Issue by jamen** [rust-lang/rustup#2292]
**Problem**

Colors are broken in VSCode terminal with MSYS2 shell. For example, `rustup show` outputs this:

![image](https://user-images.githubusercontent.com/6251703/79995170-1dd82a00-8474-11ea-83a4-0cf203f7fac7.png)

But, Cargo's colors work fine:

![image](https://user-images.githubusercontent.com/6251703/79994348-1401f700-8473-11ea-80e1-0e71ebb3a382.png)

So this isn't an issue on my end afaik.

**Steps**

1. Use Windows, MSYS2, and VSCode terminal
2. Use the MSYS2 shell with
```json
    "terminal.integrated.shell.windows": "C:\\msys64\\msys2_shell.cmd",
    "terminal.integrated.shellArgs.windows": [
        "-defterm",
        "-no-start",
        "-use-full-path",
        "-mingw",
        "-here"
    ],
```
3. Run a command which outputs color like `rustup show`

**Possible Solution(s)**

Copy how Cargo is doing colors.

**Notes**

- Output of `rustup --version`: rustup 1.21.1 (7832b2ebe 2019-12-20)
- Output of `rustup show`: See above.
- Output of `echo $TERM`: xterm-256color

**Comment by kinnison** [comment]
This is a problem with how we interact with the terminal using `term` -- I'd like to replace that with something better but right now we're a bit stuck.

This is related to #1835 #1818  and #1826

**Comment by aloucks** [comment]
Color is broken in all MSYS terminals, not just when using VSCode.  

I thought that at one point color was just disabled, but now it shows garbled color codes:

![image](https://user-images.githubusercontent.com/221559/91496559-548ed880-e88a-11ea-95e8-31de23ceff9b.png)

**Comment by ForsakenHarmony** [comment]
I'm also running into this issue, fish from cygwin embedded in clion

The PR #2469 does not change the behaviour because in this case no env variable gets set

**Comment by aloucks** [comment]
> I'm also running into this issue, fish from cygwin embedded in clion
> 
> The PR #2469 does not change the behaviour because in this case no env variable gets set

I think running `rustup` with `winpty` will also fix the issue.
