### ISSUE TITLE
`rustup override set nightly` cannot be seen in `rustup toolchain list`

### ISSUE THREAD

**Issue by bestia-dev** [rust-lang/rustup#2295]
`rustup override set nightly` overrides the default toolchain for that directory only.  
But in `rustup toolchain list` this cannot be seen. There is only the old default:  
```
stable-x86_64-unknown-linux-gnu (default)   
nightly-x86_64-unknown-linux-gnu  
```
It would be informative to add something like (override):  
```
stable-x86_64-unknown-linux-gnu (default)   
nightly-x86_64-unknown-linux-gnu  (override)
```

**Comment by kinnison** [comment]
This is an interesting idea and should not be too hard to implement.  If you wanted to have a go at a PR, I'd be happy to discuss things with you.  You can find me on our Discord channel on the rust-lang server.  If you (or anyone else reading this) wants to take this on, comment on here so we know and don't duplicate work.
