### ISSUE TITLE
Rustup ignores 'rust-toolchain' when saved in UTF-16 on Windows.

### ISSUE THREAD

**Issue by aikixd** [rust-lang/rustup#2302]
Rustup ignores `rust-toolchain` when saved in UTF-16 on Windows.

To reporoduce:
1. Create `rust-toolchain` with `nigthly` and save as UTF-16 (BE/LE, doesn't matter)
2. Run `rustup show`

Active toolchain will be stable.

Saving the same file in UTF-8 solves the problem

Output of `rustup --version`:
`rustup 1.21.1 (7832b2ebe 2019-12-20)`

Output of `rustup show`:
```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\xxx\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (overridden by '\\?\C:\Dev\eezip\rust-toolchain')
rustc 1.44.0-nightly (3360cc3a0 2020-04-24)
```

**Comment by tesuji** [comment]
The problem is rustup assume the UTF-8 encoding of "rust-toolchain".
rustup has no idea how to detect other encodings.

**Comment by kinnison** [comment]
I think the fix here is to make it clear in documentation that `rust-toolchain` is to be a valid toolchain name, which for reference is actually limited to ASCII not the whole of UTF-8, though of course we read the file into a `String` so it has to be valid UTF-8.  AIUI, this means that notepad's propensity for inserting a BOM will also be a bad thing.  Though perhaps we might be able to catch that at least.
