### ISSUE TITLE
Add a hint to log out/in after installation to the README

### ISSUE THREAD

**Issue by jmaargh** [rust-lang/rustup#2317]
**Describe the problem you are trying to solve**

As discussed in #2226, on various flavours of Linux you need to do a log out/in cycle for the updates to `PATH` to take without having to re-source `.profile` in each terminal. However, the README simply states:

```
This directory will be in your $PATH environment variable, which means you can run them from the shell without further configuration. Open a new shell and type the following:
```

This makes it appear that some thing went wrong with your installation if (like me) you didn't pause to read the end of the installation output properly.

**Describe the solution you'd like**

A simple reference to needing to log out/in on Linux would be friendly I think. Even as a footnote or a FAQ.

**Comment by kinnison** [comment]
Upon completion of installation you receive the following message (with the cargo home interpolated in):

```
To get started you need Cargo's bin directory ({cargo_home}/bin) in your `PATH`
environment variable. Next time you log in this will be done
automatically.
```
Is this not clear enough?  Perhaps rewording here would be more useful than rewording in the README?  (I suppose both is acceptable, but the README is the least consumed document I imagine)

**Comment by jmaargh** [comment]
I appreciate that message (which I think is clear enough), but as I said

> ...if (like me) you didn't pause to read the end of the installation output properly.

On one level, this is my fault, but it's also (I think) understandable. I was installing a bunch of things quickly and it was just another long-running command with a bunch of output which completed successfully, so why would I bother reading the output? So when I pick back up and realise something appears to be wrong, I go to the documentation for the tool that should set this up (i.e, the `README`).

I figured out the issue pretty quickly, but I just thought that it might be a bit more complete to add something to this effect to the README (especially since the current wording in the README suggests that it should just be available in any new shell)

**Comment by kinnison** [comment]
Fair enough, I suppose I should have spotted that bit, so clearly I didn't read your report well enough.  Okay so we need an improvement to the message we already emit *AND* we need README updates to help with people who don't read it carefully enough.
