### ISSUE TITLE
install rust in chrome os/linux for access by vscode

### ISSUE THREAD

**Issue by ghost** [rust-lang/rustup#2321]
**Problem**

Installed rust in chrome os (linux) then installed vscode.
Installed vscode rust extension. Tried to use cargo in vscode
It reinstalled rust all over again.

I expected it to use the already installed version of rust and supporting tools.
none were accepted. and  i think starting rls failed.
**Steps**

1. install linux on chrome os
2. sudo curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
3. exit/login; rustc --version => received version info.
4. downloaded vscode for debian; right click on download; select install in linux
5. in external market installed rust; and rust(rls)
6. cntl+shift+p and selected cargo create new exicutable project; enter
7. went down hill from there on asking for tool chain etc. I had 
    already done this in linux terminal.  went on to reinstall rust again.

**Possible Solution(s)**

don't know - seems rust is designed to be installed under each
user.   Don't know which linux user vscode is using. 

Would like to see a clean process for installing rust under
vscode so that all works correctly as if not running in vscode
(toolchain, git repro, etc.. ) I know it is a new environment,
but more programmers (and students) are buying chromebooks
it would be nice to save them all a bit of pain and fustration.
**Notes**

Output of `rustup --version`:
rustup 1.21.1 (7832b2ebe 2019-12-20)

Output of `rustup show`:

stable-x86_64-unknown-linux-gnu (default)
rustc 1.43.0 (4fb7144ed 2020-04-20)

**Comment by kinnison** [comment]
So the problem here is that ChromeOS treats users very differently from how they are normally treated in Linux.  This is not something I can think of the correct solution for off the top of my head so I'm going to add some labels to encourage others to chime in with ideas.  If we have something solid and a useful way to detect chromeos then we can consider how to deploy that fix.

**Comment by rbtcollins** [comment]
If I understand correctly it all worked fine, if redundantly. No errors, no failures?
