### ISSUE TITLE
Panics during installation on WSL

### ISSUE THREAD

**Issue by shika-blyat** [rust-lang/rustup#2324]
To reproduce:
run: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
System information:
`shika-blyat@DESKTOP-F190IPO:~/.doom.d$ uname -a
Linux DESKTOP-F190IPO 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux`

Here's the traceback:
https://bin.drlazor.be/chroplagot

**Comment by kinnison** [comment]
This is essentially a dupe of #2323 #2319 and thus #2245 

Please follow on #2245 for an update when WSL is fixed.
