### ISSUE TITLE
Nudge WSL users to Windows Insider

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/rustup#2329]
There are a bunch of issues with people panicking on WSL1.
Fortunately, we can detect WSL users:
https://twitter.com/rbtcollins/status/1259961647696719872

This issue is fixed on Windows Insider, which is an "advance release".
https://twitter.com/svengroot_ms/status/1259718554846236674

It is not known when the Windows Insider fix will hit the general population. They're (understandably) not even willing to speculate on a very open-ended timetable. As this might be a problem for a while, it makes sense to add a nudge in `rustup-init.sh` for WSL users that detects them, pauses the installation to warn them that Rustup might fail to install and gently suggest they might want to use Windows Insider or WSL2, but allows them to continue anyways after reading that advisory and confirming.

**Comment by bruxisma** [comment]
Hi I ran into this earlier. I found that manually installing the `-musl` toolchain worked, and then allowed me to install the `-gnu` toolchain via `rustup install stable-gnu`

**Comment by workingjubilee** [comment]
absolutely wild.

**Comment by bruxisma** [comment]
Given that the twitter thread reference glibc changing behavior, and musl is *not* glibc it kind of makes sense, but that I'm then able to get an installed rustup to work and then change my default to `stable-gnu` is... yeah. Wild 😅

**Comment by workingjubilee** [comment]
NB: this was discovered to be Not A Fix, in fact, and Insider or WSL2 are the only solutions to-date.
https://twitter.com/slurpsmadrips/status/1260310342346792962
![Screenshot_2020-05-12 Izzy Muerte on Twitter workingjubilee Oh I was wrong musl has the same issue on occasion as well WELP](https://user-images.githubusercontent.com/46493976/81746214-ebaa5e80-945a-11ea-96fd-17c8bd79b2ae.png)

**Comment by kinnison** [comment]
We'd need to detect the combo of WSL1 *and* an unsuitable glibc.  WSL1 with Debian/Buster is likely just fine.

**Comment by rbtcollins** [comment]
Yup, the issue is nanosleep's changed implementation in glibc as of august? last year, when this first showed up in Arch. 

Pausing and pointing folk at Insiders is problematic I feel, because many Windows users in corporates settings will be unable to opt into Insiders at all, and also because in automated environments (CI), pausing for interactive use will break things.

I think if we want to fix the install we need to do a hermetic build sealing across libc rather than dynamically linking to libc as normal - this is unusual but not unprecedented, and would allow us to choose to build with a known compatible glibc. That won't fix rust for folk building things post install, but it should shift the problem along a step.

**Comment by kinnison** [comment]
I think there are other issues with static-linking the libc on glibc systems (the nsswitch breaks IIRC, making hostname resolution harder)

**Comment by kinnison** [comment]
Could we provide a replacement `nanosleep` implementation ourselves?

**Comment by workingjubilee** [comment]
Hm. Doesn't `-y` already skip such interactives, and is required for using the `curl | sh` install, and would be passed through? We just make sure the message respects `-y`.

I agree a more durable fix would be desirable but I proposed this variant because it has a minimal maintenance burden and an ideally fast implementation time.

**Comment by rbtcollins** [comment]
The absolute support burden today is tolerable; its the 2nd derivative that has me worried, but it is noisy; I think if you are enthusiastic about this and have energy to put into it that doing so is ok; Kinnison and I have expressed some considerations to bear in mind in whatever you come up with - for clarity:
- detect the broken glibc too (or some reasonable proxy for it), not just WSL1 on it's own
- make sure it works with -y

If the WU release happens in a reasonably timely manner we may not need it, but if it doesn't then when this is ready we can use it.

But I personally suspect there are much more long-term beneficial things in rustup to invest in - this seems fairly short-term tactical and likely to blow over.

**Comment by kinnison** [comment]
At this point we have a well oiled script for helping people with wsl2.  I'm going therefore to close this.
