### ISSUE TITLE
rustup exceeds 512MB on Beaglebone Black and gets OOM killed

### ISSUE THREAD

**Issue by buzmeg** [rust-lang/rustup#2340]
**Problem**
For some reason, rustup is using an excessive amount of RAM (>512MB) and getting killed off on my Beaglebone Black.

**Steps**
```# rustup install stable
info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
info: latest update on 2020-05-07, rust version 1.43.1 (8d69840ab 2020-05-04)
...
info: installing component 'rustc'
 53.7 MiB /  71.6 MiB ( 75 %)   2.3 MiB/s in 33s ETA:  7sKilled
```

```# uname -a
Linux beaglebone 4.19.94-ti-r42 #1buster SMP PREEMPT Tue Mar 31 19:38:29 UTC 2020 armv7l GNU/Linux
```

**Notes**

Output of `rustup --version`:
```
# rustup --version
rustup 1.21.1 (7832b2ebe 2019-12-20)
```

Output of `rustup show`:
```
# rustup show
Default host: armv7-unknown-linux-gnueabihf
rustup home:  /root/.rustup

stable-armv7-unknown-linux-gnueabihf (default)
(rustc does not exist)

```

**Comment by workingjubilee** [comment]
Can you show what memory usage is like right before and after you start to pull in rustc?

**Comment by buzmeg** [comment]
Effectively idle.  Only basic Linux things running on the OS.

```
top - 21:56:43 up 3 days, 17:20,  3 users,  load average: 0.00, 0.01, 0.11
Tasks:  92 total,   1 running,  91 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.3 us,  1.3 sy,  0.0 ni, 98.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :    483.4 total,     75.5 free,    135.3 used,    272.6 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.    338.3 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                     
20203 root      20   0    9432   2600   2020 R   1.0   0.5   0:00.97 top                                                                                                                                         

```

From my dmesg from when the OOM system killed it:
```
[62536.713309] Out of memory: Kill process 3704 (rustup-init) score 887 or sacrifice child
[62536.728120] Killed process 3704 (rustup-init) total-vm:462940kB, anon-rss:438800kB, file-rss:4kB, shmem-rss:0kB
[62599.807935] Out of memory: Kill process 3742 (rustup-init) score 887 or sacrifice child
[62599.837869] Killed process 3742 (rustup-init) total-vm:462896kB, anon-rss:438676kB, file-rss:4kB, shmem-rss:0kB
[62983.771800] Out of memory: Kill process 3845 (rustup) score 882 or sacrifice child
[62983.796887] Killed process 3845 (rustup) total-vm:463440kB, anon-rss:436472kB, file-rss:4kB, shmem-rss:0kB
[63044.057013] Out of memory: Kill process 3866 (rustup) score 876 or sacrifice child
[63044.071480] Killed process 3866 (rustup) total-vm:462896kB, anon-rss:433488kB, file-rss:4kB, shmem-rss:0kB
[87919.299398] Out of memory: Kill process 12744 (rustc) score 634 or sacrifice child
[87919.321253] Killed process 12744 (rustc) total-vm:579876kB, anon-rss:313676kB, file-rss:72kB, shmem-rss:0kB

```

rustup behaves pretty reasonably overall.  But, for some reason, there is a brief spike and then it calms down again.  If I enable about 2GB of swap, I can't even catch the spike and the rustup install completes.

The problem is that this system uses flash-based main filesystems.  Swap is a big-nono for flash longevity.

**Comment by rbtcollins** [comment]
This is likely fixed with master which probes for available memory using
the effective-memory crate. Does cargo work well on the beaglebone black?
Our tuning for the default memory footprint is predicated on the memory
needed to build hello world.

The memory spike is due to having to hold buffers for incomplete writes.

**Comment by buzmeg** [comment]
> Does cargo work well on the beaglebone black?

Define "well".

This is a 1GHz A8 with 512MB of RAM and microSD for storage.  So, it's not fast.  You can run the eMMC which is much faster, but I find that the ability to pop the uSD card out and manipulate it on a much bigger and faster Linux laptop is a useful ability.  

Once I got everything installed, it actually compiled the rust-analyzer VSCode extension.  Yes, it took 18 hours, but it actually compiled it and it ran.  That was quite remarkable, IMO.

However, my current usage is more along the lines where I am writing a USB gadget driver in Rust.  This is replacing a Python implementation.  Cargo and Rust work very nicely there.  I haven't seen any issues other than speed.  Crates just pull, compile and run.

It's all functional, but it sure won't win any speed competitions:
```
# cargo run
   Compiling daplink_daget_bulk_user v0.1.0 (/root/prudap/usbgadget/bulk_cmsis_dap_2_0_0/daplink_gadget_bulk_user)
<lots of stuff elided>
    Finished dev [unoptimized + debuginfo] target(s) in 14.56s
     Running `target/debug/daplink_daget_bulk_user`
```

This isn't "Hello, world."

```
# time cargo run
   Compiling hello v0.1.0 (/root/rust/hello)
    Finished dev [unoptimized + debuginfo] target(s) in 4.45s
     Running `target/debug/hello`
Hello, world!

```


However, to me, it's a lot easier than setting up a cross-compiling environment.  And, personal experience shows that I *always* wind up with strange, hard-to-track down bugs when I do cross compiling (this is not specific to Rust).

The biggest issue is that if you reference a crate that pulls in The Universe(tm) it takes quite a while to compile the first time.  After that, compilation is reasonable, but not speedy.

I suspect that if you really want to optimize cargo/rust compilation speeds, make your developers do some development on a Beaglebone Black or a Beaglebone AI, if you're feeling generous(that's a dual A15 1.5GHz with 1GB or RAM and 16GB of eMMC and Gigabit ethernet).  You'll uncover a lot of the bottlenecks as they're exacerbated on a smaller system like that.  (Do *NOT* use the Beaglebone Green's--they have some differences that make for frustration if you're not aware of them).  

Of course, your developers may want to throw the board through their monitor in frustration.  YMMV.  :)

Let me know when this hits stable and I'll reinstall from scratch to make sure the bug is gone.

**Comment by kinnison** [comment]
Since this is resolved with master, I'm going to close this issue.  @buzmeg You'll get the new rustup via `rustup update` or `rustup self update` when it is released, automatically.  Just either post here, or open a fresh issue if 1.22.0 still isn't right for you.

**Comment by buzmeg** [comment]
This seems to be fixed.  I just did a rustup on a Pocketbeagle and it simply worked.

**Comment by tosiara** [comment]
Nope, it does not work on 512MB board:
```
[ 1704.511934] Out of memory: 
Killed process 3386 (rustup-init) total-vm:822384kB, 
anon-rss:224124kB, file-rss:0kB, shmem-rss:896kB, UID:1101 
pgtables:860kB oom_score_adj:0
```

**Comment by rami3l** [comment]
Closing this in favor of #2919. The fix as it's currently implemented is definitely not complete. Will definitely investigate into this.
