### ISSUE TITLE
Poor line breaks on Windows

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rustup#2343]
Installing rustup today, I got this:

![image](https://user-images.githubusercontent.com/27786/82732485-1d30ee80-9cd3-11ea-967b-98959740a8dd.png)

as you can see, there's a `\n` after `PATH` that causes the output to be less than ideal.

**Comment by workingjubilee** [comment]
This has a PR open for it. #2336

**Comment by kinnison** [comment]
This was fixed in #2420
