### ISSUE TITLE
Rustup returns a invalid URL.

### ISSUE THREAD

**Issue by ghost** [rust-lang/rustup#2347]
**Problem**
When installing an invalid target but with channel, rustup prints a URL(https://forge.rust-lang.org/platform-support.html) but this URL is invalid because it is not exist.

This URL requires 404 Not Found.

**Steps**

1.Input 'rustup install nightly-aaa'
2.Copy the link printed
3.Browse

**Possible Solution(s)**

**Notes**

Output of `rustup --version`:
rustup 1.21.1 (7832b2ebe 2019-12-20)
Output of `rustup show`:
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/laurence/.rustup

installed toolchains
--------------------

nightly-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-musl

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.45.0-nightly (f93bb2a50 2020-05-25)

**Comment by runfalk** [comment]
I have the exact same issue. Tried to use https://rust-lang.github.io/rustup-components-history/aarch64-unknown-linux-musl.html as a workaround but apparently aarch64-unknown-linux-musl doesn't exist for stable.

**Comment by kinnison** [comment]
The URL is fixed in master and will 1.22.0 will contain the fix.  The forge is supposed to redirect the old URL but perhaps that is broken too.

**Comment by nabijaczleweli** [comment]
It's still blatantly in the README, on current `master`: https://github.com/rust-lang/rustup/blob/c805b2a977ed7decf0266a9e1d03f26c628ea807/README.md#cross-compilation

A git grep reveals a few other places as well:
![screenshot](https://user-images.githubusercontent.com/6709544/84945772-f30ef880-b0e7-11ea-88f4-67acb8fd4229.png)

**Comment by kinnison** [comment]
That grep output shows that all the URLs are correct, unless I've completely misunderstood your point.

**Comment by nabijaczleweli** [comment]
No, sorry, you're right, I must've been very confused when writing this, apologies!
