### ISSUE TITLE
Failure when attempting to install certain IOS targets

### ISSUE THREAD

**Issue by AKushWarrior** [rust-lang/rustup#2349]
**Problem**
`rustup target add` fails on MacOS when attempting to install the targets `armv7-apple-ios`, `armv7s-apple-ios`, and `i386-apple-ios`.

The given error message is 
```bash
error: component 'rust-std' for target 'armv7-apple-ios' is unavailable for download for channel beta
```

**Steps**
1. Install rust using `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
2. Use `rustup target add` with one of the above targets.

**Notes**
* This was done on a cold install as well as a used environment; the bug was the same both times.
* I tested on both the beta and stable channels; the result was the same.

Output of `rustup --version`: 
```bash
rustup 1.21.1 (7832b2ebe 2019-12-20)
```

Output of `rustup show`:
```bash
Default host: x86_64-apple-darwin
rustup home:  /Users/Aditya/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
beta-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-ios
aarch64-linux-android
armv7-linux-androideabi
i686-linux-android
x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin
rustc 1.43.1 (8d69840ab 2020-05-04)
```

**Comment by AKushWarrior** [comment]
Whoops, this is a feature, not a bug. These APIs were deprecated in 1.4.2, as Apple has also dropped support for 32-bit architectures.

My bad, closing this.

**Comment by dreampiggy** [comment]
See issue here.
Apple only drop the support of 32 bit from iOS 11.
But there are million users still use iOS 10 and below. This not sounds reasonable to drop the support.

**Comment by AKushWarrior** [comment]
@dreampiggy You should open a new issue on the main rust repository. This issue was just for the installation issue.
