### ISSUE TITLE
Gauging interest in evolving rustup.rs (the website)

### ISSUE THREAD

**Issue by softprops** [rust-lang/rustup#2353]
**Describe the problem you are trying to solve**

Maximize the use of rustup.rs (the landing page) in terms of a home for rustup documentation as well as welcoming new users to the toolchain.

**Describe the solution you'd like**

Rustup.rs is a drop zone for both new users and a home page for the tool itself. This is what users experience today

![Screenshot_20200531-072453](https://user-images.githubusercontent.com/2242/83351286-a0c09000-a310-11ea-8fa0-a20409958195.png)

It's a very good mvp that I'm sure met the goals needed when the tool was originally developed.

I believe there is room for improvement and an opportunity to be even more helpful to users 

First I'd like to gauge interest in comentic rebranding in addition to proving more information. It's always bugged me that the main installation step flows out of view and doesn't have a copy to clipboard functionality. I'd like to experiment with tightening up the ux

Separately year(s?) ago rust did away with the systems langauge marketing but rustup still holds onto that. I'd like to rephrase 

> rustup is an installer for
the systems programming language Rust

As

> Rustup is the installer for the Rust programming language

It's more concise and implies it's the official installer which I think we can call it that by now

I would also like to make it more informational, in particular for new users but also as a point of hyperlinkable reference for existing users. Today there is a link to component availability but doesn't actually say way a component, or other rustup nouns, are. I'd like to sketch out something a bit more informative. Some of this information exists but is scattered across 3 different websites!

* https://www.rust-lang.org/tools/install
* https://forge.rust-lang.org/infra/other-installation-methods.html
* https://rust-lang.github.io/rustup-components-history/

I think there's some room for consolidation here.

**Notes**

I'm looking for opportunities to help out that would improve the dx experience. Documentation and the presentation of these websites have always felt mvp in nature and don't evolve as the projects do. I'd like to help with that 

I wanted to open an issue to gauge interest before putting time into actually doing it

**Comment by kinnison** [comment]
It's much more likely we'll be retiring `rustup.rs` entirely, moving the main UX to `www.rust-lang.org`  So while it was really nice of you to consider this, it's not something we want to do.  Feel free to discuss ways to improve `www.rust-lang.org` on their repository though.

**Comment by softprops** [comment]
Glad I asked first!
