### ISSUE TITLE
issue trying to curl and what appears to be an expired cert on  https://sh.rustup.rs website 

### ISSUE THREAD

**Issue by banana-man-sam** [rust-lang/rustup#2361]
sudo  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

Above is the command im using with variations trying different tls versions, ignore cert etc just to get it to work with no luck. Ive done it on multiple other servers with no issues however im now running into problems. 

I get errors like the following (which ive also tried the suggestions)

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by emilyalbini** [comment]
Transferred this issue to the rustup repository.

**Comment by emilyalbini** [comment]
Thanks for reporting this @banana-man-sam!

What OS are you running? What's the curl version? Is the local certificate store up to date?

**Comment by kinnison** [comment]
The error `curl: (60) SSL certificate problem: unable to get local issuer certificate` suggests that this is a local issue to the client.  Most likely `curl` is unable to find the CA certificate bundle and so has no root-of-trust capability.

**Comment by banana-man-sam** [comment]
curl 7.52.1 , deb 9. After doing a few other upgrades i feel confident kinnison is probably correct. Thank you  everyone for the swift a good response/feedback !
