### ISSUE TITLE
'rustup toolchain install nightly-mips64el-unknown-linux-gnuabi64' failed due to file too big error

### ISSUE THREAD

**Issue by SuperHacker-liuan** [rust-lang/rustup#2362]
**Problem**
'rustup toolchain install nightly-mips64el-unknown-linux-gnuabi64' failed due to file too big error.

When I tried to install nightly-mips64el-unknown-linux-gnuabi64 toolchain via rustup, I got error raised. Console output was shown as follow:
```bash
$ rustup toolchain install nightly-mips64el-unknown-linux-gnuabi64
info: syncing channel updates for 'nightly-mips64el-unknown-linux-gnuabi64'
info: latest update on 2020-06-03, rust version 1.45.0-nightly (fe10f1a49 2020-06-02)
info: downloading component 'cargo'
  4.5 MiB /   4.5 MiB (100 %)   4.5 MiB/s in  1s ETA:  0s
info: downloading component 'clippy'
info: downloading component 'rust-std'
 14.3 MiB /  14.3 MiB (100 %)   4.7 MiB/s in  3s ETA:  0s
info: downloading component 'rustc'
 55.6 MiB /  55.6 MiB (100 %)   5.1 MiB/s in 11s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-std'
 14.3 MiB /  14.3 MiB (100 %)  13.6 MiB/s in  1s ETA:  0s
info: installing component 'rustc'
info: rolling back changes
error: File too big rustc-nightly-mips64el-unknown-linux-gnuabi64/rustc/lib/librustc_driver-9847b5345797fa9e.so 203010864

```

**Steps**

1. execute `rustup toolchain install nightly-mips64el-unknown-linux-gnuabi64`
2. get the error raised.

**Possible Solution(s)**
Maybe we should set a larger MAX_FILE_SIZE at https://github.com/rust-lang/rustup/blob/0602a72e7df9cbbda7b3292cdeccf65af04ed787/src/dist/component/package.rs#L299

**Notes**
Output of `rustup --version`: `rustup 1.21.1 (7832b2ebe 2019-12-20)`
Output of `rustup show`:
```bash
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/SuperHacker/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.43.1 (8d69840ab 2020-05-04)
```

Same issue also occured on a mips64el platform.

**Comment by rbtcollins** [comment]
blerg yes. Uhm, care to submit a patch?
