### ISSUE TITLE
rustup is aways 1.21.1 and can not update

### ISSUE THREAD

**Issue by lamei1224** [rust-lang/rustup#2366]

**Comment by lamei1224** [comment]
1.stable version is 1.44;nightly version is 1.45(default)
2.rustup self update ,its just a message about info
3.check the rustup version ,its still 1.21,but the rustc and cargo version is 1.45
4.how can i update the rustup version into the 1.37,or may be higher

**Comment by lamei1224** [comment]
i tried every update,but its not gona work.so somebody can help me,i can not update the rustup vesion

**Comment by kinnison** [comment]
Rustup is versioned independently of the Rust toolchain.  The current version of rustup **is** 1.21.1.  This will not stop you updating your Rust toolchains.

**Comment by Lawliet-Chan** [comment]
> Rustup is versioned independently of the Rust toolchain. The current version of rustup **is** 1.21.1. This will not stop you updating your Rust toolchains.

Hi, I had a question,  how can I change my rustup version. Mine is `rustup 1.22.1 (b01adbbc3 2020-07-08)`, and I want to change it back to` rustup 1.21.1 (7832b2ebe 2019-12-20)`

**Comment by kinnison** [comment]
@Lawliet-Chan If you did downgrade (which is possible though awkward) then the next time you updated, rustup would try to re-upgrade.  Why do you want to downgrade?
