### ISSUE TITLE
I am beginner for rust ,don't how to install correctly

### ISSUE THREAD

**Issue by WingDust** [rust-lang/rustup#2370]
**Problem**

I use ArchWSL for WSL2
and I want to developer rust in wsl
but when i run `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` and add to envrionment var
I run `cargo --version`
![image](https://user-images.githubusercontent.com/45911286/84120401-5e155b00-aa68-11ea-97b1-96296fa3848c.png)
and `rustup --version`
![image](https://user-images.githubusercontent.com/45911286/84120499-7a18fc80-aa68-11ea-97e4-4be69069bddf.png)
in [Rust-Install](https://www.rust-lang.org/zh-CN/learn/get-started) is too simple
i try to `rustup install stable ` 
but still this way
I don't want to next?
**Steps**

1.curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
2.add to environment var
3.rustup install stable

**Possible Solution(s)**

**Notes**

Output of `rustup --version`:1.21.1
Output of `rustup show`:

**Comment by kinnison** [comment]
Could you please provide the output of `rustup show` from within your WSL environment, and `wsl -l -v` from a powershell prompt?  Please use the text output, do not embed images if possible.

**Comment by WingDust** [comment]
`rust show` 
```
Default host :x86_64-unknown-linux-gnu
rustup home: ~/.rustup
no active toolchain
```
`wsl -l -v`

```
  NAME    STATE           VERSION
* Arch    Running         2
```
@kinnison

**Comment by kinnison** [comment]
Excellent, that's a good start.  Can you now please run `rustup toolchain install stable` and provide a similar copy of the output of that, and of `rustup show` afterwards?

**Comment by WingDust** [comment]
`rustup toolchain install stable`

and I try to run 
`echo 'export RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup' >> ~/.bash_profile` 
change resource to in China ,still error.
```
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
warning: Signature verification failed for 'https://mirrors.tuna.tsinghua.edu.cn/rustup/dist/channel-rust-stable.toml'
info: latest update on 2020-06-04, rust version 1.44.0 (49cae5576 2020-06-01)

  stable-x86_64-unknown-linux-gnu unchanged - (rustc does not exist)

info: checking for self-updates
error: could not download file from 'https://static.rust-lang.org/rustup/release-stable.toml' to '/tmp/rustup-updateE55ZXi/release-stable.toml'
error: caused by: error reading from socket
error: caused by: timed out
```
@kinnison

**Comment by kinnison** [comment]
Aah I see, you're in China.  I'm afraid I don't know the tricks in china.  I think @brson might be able to point you at some local support groups which can help.  We're working on improving matters for Chinese users of Rust, but I'm not sure what the current setup recommendations are.

**Comment by WingDust** [comment]
I try to use VPN reinstall rustup toochain , Now It's work

**Comment by WingDust** [comment]
I run `rustup toolchain install stabe-x86_64-unknown-linux-gnu` form check The Doc

**Comment by kinnison** [comment]
I'm glad things are working for you now.
