### ISSUE TITLE
Improve error messages for unsupported platforms.

### ISSUE THREAD

**Issue by ericonr** [rust-lang/rustup#2376]
**Describe the problem you are trying to solve**

Hey there! I'm messing around with the rustup package in Void Linux. One of the platforms that we ship binaries for is `armv6l-musl`, which roughly corresponds to the `arm-unknown-linux-musleabihf` target. However, trying to run `rustup-init` on such a device results in the following error message:

```
$ rustup-init
error: Pre-checks for host and toolchain failed: Provided host 'arm-unknown-linux-musleabihf' couldn't be converted to partial triple
If you are unsure of suitable values, the 'stable' toolchain is the default.
Valid host triples look something like: arm-unknown-linux-musleabihf
```

**Describe the solution you'd like**

The error here is simply that the Rust team doesn't ship compilers built for this architecture. This should be made clear, because the current error message is a bit cryptic.

**Notes**

#2168 has a similar error message for an unsupported platform.

**Comment by rbtcollins** [comment]
If you wanted to add a feature to the code in src/dist/dist.rs so that it can discriminate between unknown triples and known but not shipped triples, that would allow this to be clearer. Right now rustup doesn't know about mustabihf, and so this error is correct, as far as it goes.

**Comment by ericonr** [comment]
> Provided host 'arm-unknown-linux-musleabihf' couldn't be converted to partial triple

> Valid host triples look something like: arm-unknown-linux-musleabihf

It errors out saying the platform couldn't be converted to a partial triple (which implies that it's malformed or similar), and the "valid" example it gives is exactly the same thing (which makes it clear that the input wasn't malformed). Seeing that error message, it isn't obvious to me what the issue is. I can see the case for it being a distribution's job to check if rustup makes sense for all those platforms, but at the same time the error message should be clearer.

**Comment by rbtcollins** [comment]
I agree that what has shown up for you is confusing. Perhaps I've misdiagnosed. You can check with a debugger, or println! debugging.

https://github.com/rust-lang/rustup/blob/bb0fd7b5f56bf5afd030cc2a251bea0c973313ad/src/dist/dist.rs#L353 is the source of the error.

https://github.com/rust-lang/rustup/blob/bb0fd7b5f56bf5afd030cc2a251bea0c973313ad/src/cli/self_update.rs#L496 is the source of the recommendation for a valid value.

And if we follow from_host_or_build down to ground:
https://github.com/rust-lang/rustup/blob/bb0fd7b5f56bf5afd030cc2a251bea0c973313ad/src/dist/dist.rs#L271

from_host will try:
https://github.com/rust-lang/rustup/blob/bb0fd7b5f56bf5afd030cc2a251bea0c973313ad/src/dist/dist.rs#L189

But `armv6l` is not accounted for, so inner() will return None, and we fall back to from_build,

https://github.com/rust-lang/rustup/blob/bb0fd7b5f56bf5afd030cc2a251bea0c973313ad/src/dist/dist.rs#L185 - I think we pull that through via some build.rs glue, but nevertheless we should be hitting that fallback code - and that is where the value you are seeing is coming from in the suggestion for what a valid host would look like, I think.

**Comment by ericonr** [comment]
Ok, I can try debugging this later. Getting it to compile on an RPi will probably take too long, so I will have to do it with cross compilation.

To be honest, I don't think this issue is particularly relevant for this specific platform. Compiling Rust stuff on most armv6l devices will likely take an eternity. The main issue is the error message that's presented in the case of unknown / unsupported platforms.

**Comment by kinnison** [comment]
Perhaps a neat approach could be to have a trivial unit test which ensures we can parse the host as valid triple?  That way we'd catch these things in the test suite; and any distro *NOT* running the test suite in their packaging process needs to change their practice anyway because running the tests is important.
