### ISSUE TITLE
Add support for uwp Windows targets

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/rustup#2379]
**Problem**
Installing any `uwp-windows` target fails.

**Steps**:
```
$ rustup target install x86_64-uwp-windows-gnu
error: toolchain 'stable-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target 'x86_64-uwp-windows-gnu'; did you mean 'x86_64-pc-windows-gnu'?
```

**Possible Solution(s)**
Add support for `uwp` targets

**Notes**
The targets `aarch64-uwp-windows-msvc`, `i686-uwp-windows-gnu`, `i686-uwp-windows-msvc`, `x86_64-uwp-windows-gnu`, and `x86_64-uwp-windows-msvc` are supported in Rust as of release 1.38.0 [see https://github.com/rust-lang/rust/pull/60260]/

Output of `rustup --version`: rustup 1.21.1 (7832b2ebe 2019-12-20)
Output of `rustup show`: Default host: x86_64-unknown-linux-gnu
rustup home:  /home/susurrus/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
1.36.0-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

x86_64-apple-darwin
x86_64-pc-windows-gnu
x86_64-pc-windows-msvc
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl
x86_64-unknown-redox

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.44.0 (49cae5576 2020-06-01)

**Comment by kinnison** [comment]
The `uwp` targets are tier 3 and are not included in release channels - see https://forge.rust-lang.org/release/platform-support.html

At this time there's nothing for `rustup` to do.
