### ISSUE TITLE
Invalid url in "target not found" message

### ISSUE THREAD

**Issue by Stupremee** [rust-lang/rustup#2380]
**Problem**
If you try to install a rust toolchain with a custom target, and the target is invalid,
rustup will print an error and redirect you to the rust forge platform support page,
but the url rustup prints is invalid.

**Steps**
1. `rustup toolchain install nightly-foo`
2. Try to open url after `Perhaps check:`

**Possible Solution(s)**
Fix the url

**Notes**

Output of `rustup --version`: `rustup 1.21.1 (2020-06-09)`

**Comment by kinnison** [comment]
Dup of #2347
