### ISSUE TITLE
Platform support link dead

### ISSUE THREAD

**Issue by nabijaczleweli** [rust-lang/rustup#2381]
**Problem**
https://forge.rust-lang.org/platform-support.html, linked in some output messages and, according to GH search, four files, is 404.

**Steps**
1. Open https://forge.rust-lang.org/platform-support.html

**Possible Solution(s)**
Replace the link with wherever that lives nowadays, I guess?

**Notes**

Output of `rustup --version`: rustup 1.21.1 (7832b2ebe 2019-12-20)
Output of `rustup show`:
```
nabijaczleweli@tarta:~$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/nabijaczleweli/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2019-11-25-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.43.1 (8d69840ab 2020-05-04)
```

**Comment by kinnison** [comment]
This is a dup of #2347
