### ISSUE TITLE
Rustup downloads windows executables instead of linux executables

### ISSUE THREAD

**Issue by SonnyX** [rust-lang/rustup#2382]
**Problem**
When using the latest rustup on a WSL linux machine, rustup downloads windows executables instead of linux executables. This in turn will rustup think that rustc and the other tools are not installed, as the paths will be `rustc.exe`, `cargo.exe`, etc instead of `rustc`, `cargo`, etc

![afbeelding](https://user-images.githubusercontent.com/784475/84992675-80823500-b148-11ea-9c69-0dda39c8c73c.png)

**Steps**

1. Create a WSL1 distro (personally tested both ubuntu and Arch Linux)
2. Downgrade glibc to version 2.30.3
3. `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
4. select option 2
5. Set `x86_64-pc-windows-gnu` as the triplet
6. Use the default values throughout the rest of the installation process (by pressing enter)

**Possible Solution(s)**

**Notes**

Output of `rustup --version`:
rustup 1.21.1 (7832b2ebe 2019-12-20)

Output of `rustup show`:
```
Default host: x86_64-pc-windows-gnu
rustup home:  /root/.rustup
stable-x86_64-pc-windows-gnu (default)
(rustc does not exist)
```

**Comment by rbtcollins** [comment]
This isn't a bug, you specifically told it to in your step 5 that you wanted it to download windows binaries.

The host triple has to be the *host* that you are running on, not the *target* that you are going to build for. These concepts are separate.

Install rustup without customising it. Then run `rustup target add <toolchain>`. it will look like this:
```
rustup target add x86_64-pc-windows-gnu
info: downloading component 'rust-std' for 'x86_64-pc-windows-gnu'
info: installing component 'rust-std' for 'x86_64-pc-windows-gnu'
```

And after this, assuming you have the right cross compiler bits available to execute, you can target windows binaries.

**Comment by SonnyX** [comment]
I see, thank you. I did not realize this.
