### ISSUE TITLE
rustup-init.exe immediately crashing on windows 10: 2004

### ISSUE THREAD

**Issue by Jonathannsegal** [rust-lang/rustup#2388]
**Problem**
I am running into a problem where I try to open rustup-init.exe and the terminal opens for a second and then crashes. Rust is already installed just not rustup and I run the exe as administrator.

**Steps**

1. Download: https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe
2. Run rustup-init.exe as administrator on Windows 10: 2004
3.

**Notes**

WSL is installed but I dont think that should affect this.

**Comment by kinnison** [comment]
It's likely that rustup-init is telling you something that you're not getting to read before Windows closes the console window.  Open a command (or powershell) prompt window and run `rustup-init` from there.  You shouldn't need to run it as administrator.  It will likely tell you to uninstall rust first.

**Comment by Jonathannsegal** [comment]
@kinnison Thanks! That worked.
