### ISSUE TITLE
slackware ARM 14.2 not supported by rustup

### ISSUE THREAD

**Issue by YuGiOhJCJ** [rust-lang/rustup#2392]
**Problem**

Installing Rust using rustup is the recommended way.
However, it does not work on my machine:
```
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer
sh: line 372: /tmp/tmp.SUeYFJ/rustup-init: No such file or directory
```
I am on a Raspberry Pi 4 with Slackware ARM 14.2.
```
$ uname -a
Linux rpi4 5.4.47-v7l+ #1322 SMP Wed Jun 17 17:58:52 BST 2020 armv7l BCM2711 GNU/Linux
```
Current behavior: A rustup failure.
Expected behavior: A rustup success.

**Steps**

1. Type the command above
2. See that it is a failure

**Possible Solution(s)**

Editing the downloaded script.

**Notes**

Output of `rustup --version`:
```
$ rustup --version 
-bash: rustup: command not found
```
Output of `rustup show`:
```
$ rustup show 
-bash: rustup: command not found
```

**Comment by kinnison** [comment]
This implies that there's a problem wrt. the dynamic linker or another very low level part of your installation vs. what `rustup-init` is expecting.

The file it'll be downloading is likely to be <https://static.rust-lang.org/rustup/dist/armv7-unknown-linux-gnueabihf/rustup-init> so if you could fetch that and then run things like `ldd ./rustup-init` so we can see if it can find all the dynamic library deps, then that'd be helpful.

**Comment by YuGiOhJCJ** [comment]
```
$ wget -q https://static.rust-lang.org/rustup/dist/armv7-unknown-linux-gnueabihf/rustup-init
$ ldd ./rustup-init 
	not a dynamic executable
$ file ./rustup-init 
./rustup-init: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, not stripped
$ file /bin/ls
/bin/ls: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, stripped
$ rm rustup-init
$ wget -q https://static.rust-lang.org/rustup/dist/arm-unknown-linux-gnueabi/rustup-init
$ ldd ./rustup-init 
	linux-vdso.so.1 (0xbeff7000)
	libdl.so.2 => /lib/libdl.so.2 (0xb6707000)
	librt.so.1 => /lib/librt.so.1 (0xb66f0000)
	libpthread.so.0 => /lib/libpthread.so.0 (0xb66c6000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb669a000)
	libc.so.6 => /lib/libc.so.6 (0xb6538000)
	libm.so.6 => /lib/libm.so.6 (0xb6481000)
	/lib/ld-linux.so.3 (0xb6f74000)
$ file ./rustup-init 
rustup-init: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, not stripped
```
As you can see, my operating system is not a Hard Float one.
So, I hope rustup is not guessing that it is a Hard Float one and is not downloading https://static.rust-lang.org/rustup/dist/armv7-unknown-linux-gnueabihf/rustup-init because it will be a failure.
The rustup script has to download this file: https://static.rust-lang.org/rustup/dist/arm-unknown-linux-gnueabi/rustup-init
How to print the URL of the downloaded file to be sure of what happens please?

**Comment by kinnison** [comment]
There isn't currently a clean way to do that, but you can run `rustup-init.sh` with `sh -x rustup-init.sh` which will let you see the commands it runs, including the `curl` or `wget` it ends up with.

**Comment by YuGiOhJCJ** [comment]
Indeed:
```
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -x
[...]
+ curl --proto =https --tlsv1.2 --silent --show-error --fail --location https://static.rust-lang.org/rustup/dist/armv7-unknown-linux-gnueabihf/rustup-init --output /tmp/tmp.5IO6vR/rustup-init
[...]
```
It is downloading the wrong file for my platform.

Not sure how the script is guessing my platform but https://static.rust-lang.org/rustup/dist/arm-unknown-linux-gnueabi/rustup-init will work whereas https://static.rust-lang.org/rustup/dist/armv7-unknown-linux-gnueabihf/rustup-init will not work.

However, my platform is: armv7-unknown-linux-gnueabi and not arm-unknown-linux-gnueabi.
It means that even if it works (because it is compatible) with https://static.rust-lang.org/rustup/dist/arm-unknown-linux-gnueabi/rustup-init it would be better if it was https://static.rust-lang.org/rustup/dist/armv7-unknown-linux-gnueabi/rustup-init

But this last file is not available because armv7-unknown-linux-gnueabi is not well supported: https://forge.rust-lang.org/platform-support.html (available targets).
As you can see, this platform is in Tier 2 and only the standard library is compiled.
It means that rustc and cargo are not available.

I can run ```rustup-init``` and change the default platform but it will not work:
```
$ ./rustup-init
[...]
default host triple: armv7-unknown-linux-gnueabihf
default toolchain: stable
profile: default
modify PATH variable: yes
[...]
default host triple: armv7-unknown-linux-gnueabi
default toolchain: stable
profile: default
modify PATH variable: yes
[...]
error: target 'armv7-unknown-linux-gnueabi' not found in channel.  Perhaps check https://forge.rust-lang.org/platform-support.html for available targets
```
So, I have no choice but to use this alternative platform (not optimized for my platform):
```
$ ./rustup-init
[...]
default host triple: armv7-unknown-linux-gnueabihf
default toolchain: stable
profile: default
modify PATH variable: yes
[...]
default host triple: arm-unknown-linux-gnueabi
default toolchain: stable
profile: default
modify PATH variable: yes
[...]
Rust is installed now. Great!
[...]
```
By the way, Slackware ARM 14.2 is not the official operating system for the Raspberry Pi 4.
A lot of users will be on Raspberry Pi OS that is an armv7-unknown-linux-gnueabihf platform.
So, only few Raspberry Pi 4 users will have this problem.
However, if someone can fix that, it will be better.

Also, the Firefox build system guessed that my platform is armv7-unknown-linux-gnueabi and not arm-unknown-linux-gnueabi.
It means that Firefox will fail to be built even if I install Rust (arm-unknown-linux-gnueabi):
```
$ ./mach build
[...]
1:20.36 checking for rust host triplet... armv7-unknown-linux-gnueabi
1:20.49 ERROR: The rust compiler host (arm-unknown-linux-gnueabi) is not suitable for the configure host (armv7l-unknown-linux-gnueabi/armv7-unknown-linux-gnueabi).
1:20.73 *** Fix above errors and then restart with\
1:20.74                "./mach build"
1:20.74 client.mk:111: recipe for target 'configure' failed
1:20.74 gmake: *** [configure] Error 1
```
So, supporting the armv7-unknown-linux-gnueabi platform would be great for Rust and Firefox.
Meanwhile, as Rust is a mandatory dependency for Firefox and Rust does not support perfectly my platform, I am unable to build Firefox that is an essential application in my operating system.

**Comment by kinnison** [comment]
Okay, so while I might be confused as to why you're deliberately hobbling your hard-float capable device with a soft-float userland, we do need to detect and cope with this if possible in `rustup-init.sh`  Would you be prepared to get the script, run it under `sh -x` and watch how it makes the decision on what ABI to download, and then see if there's a tweak we can make to detect your unusual setup?

**Comment by YuGiOhJCJ** [comment]
I decided to use Slackware ARM 14.2 (soft-float) instead of Raspberry Pi OS (hard-float) because I prefer its design (stability and simplicity).
So, I am on Slackware ARM 14.2 with a Raspberry Pi 4 (a hard-float capable device).

Of course, it is frustrating to be on a soft-float operating system whereas my device is hard-float capable.
A hard-float operating system could improve performances on my device.
But I have no choice because Slackware ARM 14.2 is released soft-float.

To detect the platform I see a first way:
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/armv7l-unknown-linux-gnueabi/8.2.0/lto-wrapper
Target: armv7l-unknown-linux-gnueabi
Configured with: ../configure --prefix=/usr --libdir=/usr/lib --enable-languages=c,c++ --enable-multilib --enable-libstdcxx-dual-abi --with-default-libstdcxx-abi=gcc4-compatible
Thread model: posix
gcc version 8.2.0 (GCC)
$ gcc -v 2>&1 | grep Target
Target: armv7l-unknown-linux-gnueabi
$ gcc -v 2>&1 | grep Target | sed 's/Target: \(.*\)/\1/'
armv7l-unknown-linux-gnueabi
```
Drawback of this method: You suppose that ```gcc``` is installed in the operating system.
An other way to detect the platform is:
```
$ test -f /lib/ld-linux.so.3
$ echo $?
0
$ test -f /lib/ld-linux-armhf.so.3
$ echo $?
1
```
Drawback of this method: You suppose that the Filesystem Hierarchy Standard is respected by the operating system and that the file is named correctly and located at the good place.
Note: The presence and the content of the ```/etc/slackware-version``` file can help too:
```
$ test -f /etc/slackware-version
$ echo $?
0
$ cat /etc/slackware-version 
Slackware 14.2
```

So, you will check software instead of hardware.
That is probably the best thing to do.

However, as armv7l-unknown-linux-gnueabi is not perfectly supported by Rust, there is still a problem.
Indeed, downloading the unavailable https://static.rust-lang.org/rustup/dist/armv7-unknown-linux-gnueabi/rustup-init file will be a failure.

Note: the future release of Slackware ARM (15.0) will be hard-float: https://docs.slackware.com/slackwarearm:faq#rd_party_slackbuild_scripts

**Comment by kinnison** [comment]
Rustup can't really guarantee that gcc will be on the target, so `rustup-init.sh` tries to use things like `uname` and the like to determine what to do.  It seems odd to try and special-case it on the presence of a slackware version file too since that could exist in multiple different targets and doesn't indicate the architecture or ABI. 

At https://github.com/rust-lang/rustup/blob/master/rustup-init.sh#L332 we attempt to detect if the CPU lacks the NEON feature, but perhaps we should also add some detection logic there for the userland ABI akin to the `get_bitness` and `get_endianness` functions.  Ideas for how to detect based on that kind of logic would be gratefully received.  I've never encountered an armv7 system which wanted to be soft-float so I don't understand why slackware would do it, nor how to detect it.

**Comment by rbtcollins** [comment]
I think trying to detect a system that rustc doesn't support is premature: when rustc can build correctly on the platform and define a platform triple for it, we can follow suit and copy whatever logic has been applied there; asking rustup to lead is backwards.

**Comment by kinnison** [comment]
@rbtcollins Fundamentally I agree; however if the `arm-unknown-linux-gnueabi' build will run on that OS, we ought to be able to detect and fetch that perhaps?

**Comment by rbtcollins** [comment]
@kinnison perhaps I misunderstood this bit:

> As you can see, this platform is in Tier 2 and only the standard library is compiled.
> It means that rustc and cargo are not available.

^ ---

**Comment by YuGiOhJCJ** [comment]
> I've never encountered an armv7 system which wanted to be soft-float so I don't understand why slackware would do it, nor how to detect it.

To understand why Slackware ARM 14.2 is soft-float, the answer is in this FAQ: https://www.linuxquestions.org/questions/slackware-arm-108/slackware-arm-faq-soft-float-and-hard-float-4175512987/

> @rbtcollins Fundamentally I agree; however if the `arm-unknown-linux-gnueabi' build will run on that OS, we ought to be able to detect and fetch that perhaps?

I agree. We should do the best that we can. Even if ```arm-unknown-linux-gnueabi``` is not optimized for ```armv7l-unknown-linux-gnueabi``` at least it works. See, I can compile rust code:
```
$ cat main.rs 
fn main()
{
	println!("Hello, world!");
}
$ rustc main.rs
$ ./main 
Hello, world!
```

**Comment by rbtcollins** [comment]
> > 
> 
> To understand why Slackware ARM 14.2 is soft-float, the answer is in this FAQ: https://www.linuxquestions.org/questions/slackware-arm-108/slackware-arm-faq-soft-float-and-hard-float-4175512987/

That says that slackware current is hardfloat; any reason you don't just run current?

**Comment by YuGiOhJCJ** [comment]
> That says that slackware current is hardfloat; any reason you don't just run current?

In a previous message, I also said that:
```Note: the future release of Slackware ARM (15.0) will be hard-float: https://docs.slackware.com/slackwarearm:faq#rd_party_slackbuild_scripts```

Yes, there is a reason I don't run current: The stability.
The current version of Slackware ARM is unstable because it is not yet released.
It is a work in progress so use it at your own risk.
The last stable is Slackware ARM 14.2.

**Comment by rbtcollins** [comment]
If you want to work on this, you're welcome to do so, but I don't think any project members are likely to do so : it is incredibly niche - this isn't the best way to get good performance out of a pi, there are better alternatives, including the upcoming next release of slackware, and focusing on that would make more sense.

**Comment by rbtcollins** [comment]
@YuGiOhJCJ if you're not planning on working on this, I think we should just close it as the next release of slackware will remove all reason for this ticket.

**Comment by YuGiOhJCJ** [comment]
It is a problem that will occur with any soft float operating system installed on the RPi4.
It is not just specific to Slackware ARM 14.2.
However, I don't know if there are other well-known soft float operating systems.
So, in doubt, I prefer to close this ticket because I don't plan to work on this currently.
