### ISSUE TITLE
Style for the snippet displayed on rustup.rs is slightly broken

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rustup#2397]
**Problem**

Copy button won't show or work well, and style for the snippet is broken on some environment.

I'm not sure how often is the website updated but I assume that's related to #2326.

It looks like this to me (Incognito Chrome on Windows):

![image](https://user-images.githubusercontent.com/25030997/86728034-feaa6b00-c066-11ea-8ff1-8d308234cb71.png)

**Steps**

1. Visit https://rustup.rs.
2. See the command and what's happen.

**Comment by kinnison** [comment]
Drat, I thought we'd solved all the snafus with that when we merged #2326.  Thanks for spotting that.

@BeniCheni do you have time to try the different browsers out and see if you can fix things?  If not, I suggest we revert the change to the page until someone can rework whatever went wrong.  I'm not an HTML/CSS expert and it looks okay to me on my browser (firefox in Linux) so I'm not sure what to do.

**Comment by BeniCheni** [comment]
@kinnison, will take a look to either provide a fix or revert. Thanks for informing.

**Comment by BeniCheni** [comment]
@kinnison et al, tried [a fix PR](https://github.com/rust-lang/rustup/pull/2398). 🙏

**Comment by BeniCheni** [comment]
Note: the corrupted style of overflown text has been tested locally by this command in the PR:

https://github.com/rust-lang/rustup/pull/2398#issuecomment-655081818
