### ISSUE TITLE
Not work on Manjaro

### ISSUE THREAD

**Issue by murka** [rust-lang/rustup#2400]
I want to install (tried sudo) Rustup on Manjaro (x64), but I get error:
`shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory`
`info: downloading installer`
`error: No such file or directory (os error 2)`
later I install rustup by pacman and run rustup, but I get error again:
`error: Unable to proceed. Could not locate working directory.`
`error: caused by: No such file or directory (os error 2)`

**Comment by kinnison** [comment]
Hi @murka 

That looks very odd.  Is your CWD broken wherever you run that?  The `cannot access parent directories` and the `Could not locate working directory` suggests you're running the command from a directory which has been deleted.

**Comment by murka** [comment]
Hey, after rebooting the system everything worked fine, although this problem did not arise before.

**Comment by kinnison** [comment]
Sounds like an odd missing directory issue then, I'm going to close this.  I'm glad things are okay for you now.
