### ISSUE TITLE
Proxy support is broken in the recent version (rustup 1.22.0 (2d019878d 2020-07-02))

### ISSUE THREAD

**Issue by rohitjoshi** [rust-lang/rustup#2401]
**Problem**
Earlier I was able to install/update rust using rustup at my workplace where access is through the proxy.
Today, I was able to successfully update the rustup ( rustup self update ) but after that no longer able to update the toolchain.

See the detail comment : https://www.reddit.com/r/rust/comments/hmaddj/announcing_rustup_1220/fx7eeg2?utm_source=share&utm_medium=web2x

**Steps**

After updating the rustup to the latest version, try to install tool chain with proxy enabled.

**Possible Solution(s)**

**Notes**

Output of `rustup --version`: rustup 1.22.0 (2d019878d 2020-07-02)
Output of `rustup show`: Default host: x86_64-apple-darwin
rustup home:  /Users/xxx/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin
beta-x86_64-apple-darwin
nightly-2019-03-24-x86_64-apple-darwin
nightly-2019-04-03-x86_64-apple-darwin
nightly-x86_64-apple-darwin (default)

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.46.0-nightly (fd4b177aa 2020-06-08)

**Comment by kinnison** [comment]
Hi, I'm sorry you encountered this.  @inejge noticed this and provided an updated `env_proxy` and #2399 last night, and we're trying to get a release out ASAP.  I'll close this once 1.22.1 is out.

**Comment by alaric** [comment]
In case anyone is stuck with this, falling back to curl by setting `RUSTUP_USE_CURL=1` as a temporary workaround worked in my environment.

**Comment by rohitjoshi** [comment]
Thanks @alaric for the workaround.

**Comment by kinnison** [comment]
1.22.1 is out and should be fixed.
