### ISSUE TITLE
git tag for 1.22.1 is missing

### ISSUE THREAD

**Issue by jcgruenhage** [rust-lang/rustup#2406]
Hey, rustup maintainer for voidlinux here. I'd like to package the most current version, but since the tag is missing here in git, I can't. Can you please tag the release in git?

**Comment by kinnison** [comment]
My apologies.  Signed tag pushed.  For this kind of thing you can also ping me on the `#wg-rustup` channel on the rust-lang discord.

**Comment by jcgruenhage** [comment]
No worries. Most times I open discord, it's to tell people not to use discord, so if it's okay, I'd prefer to keep things like that on github, if that's okay?

**Comment by kinnison** [comment]
That's your prerogative, though you'd have had a faster response from me if you had :D  Hopefully I won't forget to push the tag next time.

**Comment by jcgruenhage** [comment]
Roughly an hour is good enough for me, but thanks for the offer anyway, and thanks for pushing the tag ^^
