### ISSUE TITLE
Rustup CLI displays "error" message with no text on run

### ISSUE THREAD

**Issue by leighmcculloch** [rust-lang/rustup#2425]
**Problem**
After installing rustup on a fresh system I see an error message when running the rustup command without any arguments. There is no meaningful error message. However, the tool appears to work as expected so the error being triggered does not appear to be critical.

<img width="416" alt="Screen Shot 2020-07-16 at 8 26 12 PM" src="https://user-images.githubusercontent.com/351529/87745383-9c5a1480-c7a2-11ea-9562-8d8025b0bf74.png">

**Steps**
1. `docker run -it debian:buster`
2. `apt update`
3. `apt install -y curl`
4. `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y`
5. `PATH=$PATH:$HOME/.cargo/bin`
6. `rustup`

**Possible Solution(s)**
I have not found a solution to this yet.

**Notes**

Output of `rustup --version`:
```
root@908b73dbcdbc:/# rustup --version
rustup 1.22.1 (b01adbbc3 2020-07-08)
```
Output of `rustup show`:
```
root@908b73dbcdbc:/# rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /root/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.45.0 (5c1f21c3b 2020-07-13)
```

**Comment by kinnison** [comment]
The error is that you have provided no subcommand to run, but the message is bad that it's not saying that.  This may be a side-effect of our recent work on making it possible to test rustup more effectively.  @rbtcollins what do you think?

**Comment by leighmcculloch** [comment]
>The error is that you have provided no subcommand to run

Displaying an error in this case is, I don't think, very useful. If I've provided no arguments to a tool that has subcommands, there's a good chance I'm looking for the help and rustup could just display the help/usage text without the error.

Some examples of other tools that do not error in this situation:
- `rustc`
- `cargo`
- `go`

**Comment by kinnison** [comment]
Hmm, yes, that behaviour is indeed what I'd expect.  https://github.com/rust-lang/rustup/blob/master/src/cli/rustup_mode.rs#L58 is where we process the CLI and I wonder what kind of error is returned from clap in this context.

**Comment by kinnison** [comment]
I've just checked.  Older versions of rustup would display the usage (without the `error:` prefix) and exit with a non-zero code, so the only behavioural difference here is the presence of the `error:` prefix.

**Comment by leighmcculloch** [comment]
I believe this is a bug because the `SubcommandRequiredElseHelp` is used further down of the line you linked to, and that option is intended to have the cli exit gracefully if no subcommand is provided. I've opened #2427 with a fix.

**Comment by kinnison** [comment]
Given we pass that argument it's more likely that the pathway within `clap` is broken than within `rustup` -- i.e. we should check why `clap` is not returning the kind of Err instance which causes us to go "aah this is usage information, print it out and return zero"

**Comment by leighmcculloch** [comment]
@kinnison I think `clap` is returning the right error, it is returning an error kind `MissingArgumentOrSubcommand`. I think the bug is rustup is not listening for that kind of error, which is what #2427 fixes.

See this code in `clap`:
https://github.com/clap-rs/clap/blob/e8d46f403671ebdd14f4f530f82f6ba6fe9c78cc/src/parse/parser.rs#L750-L756

**Comment by ymgsmz** [comment]
Same notice on Mac:
```bash
aspire@MacBook-Air ~ % rustup
error: rustup 1.22.1 (b01adbbc3 2020-07-08) 
The Rust toolchain installer

USAGE:
    rustup [FLAGS] [+toolchain] <SUBCOMMAND>

...
```
Overall, does it belong to installation issues, or is it just a bug?

**Comment by kinnison** [comment]
We're working on a change in #2427 which will hopefully resolve the problem, but it's stalled a little right now.  (I imagine real-life has gotten in the way)
