### ISSUE TITLE
Please do not completely remove ~/.rustup/tmp

### ISSUE THREAD

**Issue by ijackson** [rust-lang/rustup#2430]
**Problem**

Hi.

Because rustup's toolchains etc. are very large, I have them in a separate filesystem from my home directory.  (The separate filesystem is not backed up.)  I have made a symlink `~/.rustup/toolchains` into that directory.  Because rustup likes to rename things from its `~/.rustup/tmp` to `toolchains`, I have a symlink for `~/.rustup/tmp` too.

But each time rustup finishes, it not only deletes the contents of tmp - it deletes tmp itself too.  Then the next run makes a new tmp as a directory, but now it is on the wrong filesystem and rustup fails.

**Steps**

1. mv .rustup/toolchains /some/other/fs/
2. ln -s /some/other/fs/toolchains .rustup/
3. mkdir /some/other/fs/tmp
4. ln -s /some/other/fs/tmp .rustup/
5. rustup update
6. Observe the tmp symlink is gone
7. nontrivial rustup update => failure, cannot rename

`error: could not rename component file from '/home/rustcargo/.rustup/tmp/yk0his763iqoxjd2_file' to '/home/rustcargo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/components'`

**Possible Solution(s)**

I think the best fix would be to simply not delete `~/.rustup/tmp`.  (Regardless of whether it's a symlink or whatever.)

I don't want to move the whole of `~/.rustup` into the non-backed-up filesystem, because that includes the settings, which I would want to keep.

I tried working around the problem with a bind mount for `tmp` and rustup did this:
```
info: cleaning up downloads & tmp directories
thread 'main' panicked at 'Unable to clean up /home/rustcargo/.rustup/tmp: Os { code: 16, kind: Other, message: "Device or resource busy" }', src/utils/utils.rs:632:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Notes**

Output of `rustup --version`: `rustup 1.22.1 (b01adbbc3 2020-07-08)`
Output of `rustup show`:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/rustcargo/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

installed targets for active toolchain
--------------------------------------

arm-unknown-linux-gnueabihf
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.46.0-nightly (346aec9b0 2020-07-11)
```

**Comment by kinnison** [comment]
Hi,

Do you have a strong reason for wanting to keep the sub-parts of `.rustup` elsewhere rather than the entirety of `.rustup` ?  We could, with not much complexity, not remove `.rustup/tmp` but perhaps it may be easier for you to simply make all of `.rustup` be on your other filesystem? Then the toolchain hashes etc, will all be in one place, rather than spread across two filesystems.

Either way, it would be code around, or called from, https://github.com/rust-lang/rustup/blob/master/src/cli/rustup_mode.rs#L903 which would need amending.

**Comment by ijackson** [comment]
Hi.  Thanks for engaging with my use case.

As I said, `~/.rustup` has also `settings.toml`.  I think I want to keep that on the backed-up filesystem?  To be honest I'm not entirely sure but looking at it it seems like it has stuff that is changed manually (by calls to rustup) and also that I might edit directly.

The `downloads` subdirectory wants to be on the non-backed-up filesystem but it is ephemeral so only a transient size problem.  IWBNI that was handled the same way as `tmp`.  I don't know what `update-hashes` is.  If I restored from a backup (effedtively emptying `toolchains`) would I want to delete `update-hashes` too?

I think there might be other reasons I haven't thought of why someone might want to have bits of `~/.rustup` in different places.  Certainly this kind of use of symlinks is a very standard Unix sysadmin technique.

The alternative is a bunch of different configuration settings for each kind of directory; this has been the approach taken by XDG for the various desktoppy paths.  In practice I have fouind that system more awkward to work with as a sysadmin and it complicates the implementation considerably, since there have to be lots of config lookups.

If you like I could work up an MR to change this behaviour and then we could see how bad the code ends up?

Thanks for your attention.

**Comment by kinnison** [comment]
The size point is good, and in theory yes you want to keep settings.toml with everything else because directory overrides etc end up in there.  `update-hashes` belongs with the toolchains because they're the hashes of the channel manifests currently used by the requisite toolchain entries.  You'd want to keep those alongside the toolchains.

If you are prepared to have a go at a patch then that would be very nice of you and either I or @rbtcollins will do our best to review as soon as we can.

**Comment by rbtcollins** [comment]
I concur that keeping the inode intact is reasonable BTW. That may be important when we come to do locking as well.

**Comment by thomaseizinger** [comment]
> The alternative is a bunch of different configuration settings for each kind of directory; this has been the approach taken by XDG for the various desktoppy paths. In practice I have fouind that system more awkward to work with as a sysadmin and it complicates the implementation considerably, since there have to be lots of config lookups.

I am currently in the process of setting up a backup strategy for my home directory and when encountering `.rustup`, I immediately thought "pretty much all of this data is not worthwhile to backup". Are there any plans of relocating the non-essential files to `~/.cache` for example?

**Comment by ijackson** [comment]
>     The alternative is a bunch of different configuration settings
>     for each kind of directory; this has been the approach taken by
>     XDG for the various desktoppy paths. In practice I have fouind
>     that system more awkward to work with as a sysadmin and it
>     complicates the implementation considerably, since there have to
>     be lots of config lookups.

Yes.  I can see why the XDG folks came up with this but it's not a
great deal of fun from an implementation pov and to control an XDG
program is still fiddly.  So I'm not a fan of this approach.

> I am currently in the process of setting up a backup strategy for my
> home directory and when encountering .rustup, I immediately thought
> "pretty much all of this data is not worthwhile to backup". Are
> there any plans of relocating the non-essential files to ~/.cache
> for example?

Using ~/.cache/rustup/{download,tmp,cache} instead of ~/.rustup/cache
would be great.

I still think my proposal to avoid destroying links is correct.  I
have an MR to the remove-dir-all package (which is where Rustup gets
its directory removal implementation) to do this, but unfortunately it
has been stalled for nearly two months awaiting a decision from review:
  https://github.com/XAMPPRocky/remove_dir_all/pull/22

Ian.

-- 
Ian Jackson <ijackson@chiark.greenend.org.uk>   These opinions are my own.  

Pronouns: they/he.  If I emailed you from @fyvzl.net or @evade.org.uk,
that is a private address which bypasses my fierce spamfilter.
