### ISSUE TITLE
Cargo bin's not added to PATH in Zsh shell

### ISSUE THREAD

**Issue by inneroot** [rust-lang/rustup#2436]
I'm using zsh shell on my linux, and just like in [issue #535](https://github.com/rust-lang/rustup/issues/535) I had to manually add cargo bin's after installing rustup.

```
path+=('home/__username__/.cargo/bin') 
export PATH
```

I got solution from [stackoverflow](https://stackoverflow.com/questions/11530090/adding-a-new-entry-to-the-path-variable-in-zsh)

But seems i just should to run
`source $HOME/.cargo/env`

**Comment by yehudahs** [comment]
still happening on mac...

**Comment by furkanksl** [comment]
I am having same issue (Mac M1)

**Comment by iraizo** [comment]
> I am having same issue (Mac M1)

then add it to your `.zshrc` ...
