### ISSUE TITLE
How to install rust without documentation?

### ISSUE THREAD

**Issue by lordlycastle** [rust-lang/rustup#2444]
**Describe the problem you are trying to solve**

I installed rust (🥳) and noticed that it takes more space for the docs than the actual installation. I don't want to keep the docs as we have internet everywhere and no need keep a local copy. **It takes 330MB for docs and 300MB for lib.**

And there are probably many like me who don't use rust everyday and only installed it so they can use `cargo` tools. Is there a way to just install `cargo`? Is there a way to install binaries of tools in `cargo`; that way you don't need local compiler to just build tools.

So is it safe to delete `share/` folder in `toolchains/...stable`? Is there a way to install without documentation?

I know we live in a world were space is cheap but that doesn't mean we should just fill it random byte and never use it. Think of the African children who have to use Chromebooks with 64GB HDD space. For them even 300MB is difference between warning and errors.

**Describe the solution you'd like**

 - A way to install without local documentation. People don't want to waste space which is literally never used. It is like SSD tax for using rust.
 - A way to use `cargo` tools without needing `rust`. I wish to keep `cargo` as light as possible, I don't want to give any useless space which is never used.

**Notes**

See this screenshot of `/home/<user>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu`
<img width="1004" alt="SS 2020-07-30 at 04 53 30" src="https://user-images.githubusercontent.com/11729541/88875621-dfe06400-d221-11ea-9a32-8d40f4b23d27.png">

**Comment by kinnison** [comment]
As per https://github.com/rust-lang/rustup#profiles if you use the `minimal` profile you won't get the docs etc. installed by default.  You can also remove the `rust-docs` component from your current installation rather than reinstalling.

**Comment by iampi31415** [comment]
for others searching this is now at https://rust-lang.github.io/rustup/concepts/profiles.html
