### ISSUE TITLE
Multiple downloads of Rustc by Rustup

### ISSUE THREAD

**Issue by AMythicDev** [rust-lang/rustup#2445]
Day before yesterday, I was trying to update Rust with rustup, but interestingly I saw that rustup was downloading the rustc file multiple times. I had a very good internet connection and everything seemed to work fine. Finally it exited with an error saying it could it download Rustc . Here is the complete log
```
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2020-07-30, rust version 1.45.1 (c367798cf 2020-07-26)
info: downloading component 'rustc'
47.3 MiB /  47.3 MiB (100 %)   2.1 MiB/s in  1m  8s ETA:  0s
info: Retrying download for 'https://static.rust-lang.org/dist/2020-07-30/rustc-1.45.1-    x86_64-unknown-linux-gnu.tar.xz'
47.3 MiB /  47.3 MiB (100 %) 536.8 KiB/s in  1m 16s ETA:  0s
info: Retrying download for 'https://static.rust-lang.org/dist/2020-07-30/rustc-1.45.1-    x86_64-unknown-linux-gnu.tar.xz'
47.3 MiB /  47.3 MiB (100 %) 902.4 KiB/s in  1m 13s ETA:  0s
info: Retrying download for 'https://static.rust-lang.org/dist/2020-07-30/rustc-1.45.1-    x86_64-unknown-linux-gnu.tar.xz'
47.3 MiB /  47.3 MiB (100 %) 825.6 KiB/s in 58s ETA:  0s 
info: Retrying download for 'https://static.rust-lang.org/dist/2020-07-30/rustc-1.45.1-    x86_64-unknown-linux-gnu.tar.xz'
error: component download failed for rustc-x86_64-unknown-linux-gnu
error: caused by: could not download file
```

**Steps**
1. Run this command `rustup update stable`

**Notes**

I have seen this happen when I was trying to update to Rust 1.44 and 1.43. Lastly on yesterday, I was finally able to update to Rust 1.45

Output of `rustup --version`:
rustup 1.22.1 (b01adbbc3 2020-07-08)

Output of `rustup show`:
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/arijit/.rustup

installed targets for active toolchain
--------------------------------------

x86_64-apple-darwin
x86_64-pc-windows-gnu
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.45.1 (c367798cf 2020-07-26)

I have taken this information after the Rust 1.45 update

**Comment by kinnison** [comment]
This looks like a problem between whatever your ISP is, and AWS S3 storage.  Though it could be any number of things, that'd be my first suspicion.

**Comment by AMythicDev** [comment]
I don't think it is my ISP's problem since other things such as cargo and rust-std have no problems. Also when a add dependency to a project and cargo fetches it from crates.io, there seem to be no problem

**Comment by kinnison** [comment]
I think the rustc component is the largest of the components it would fetch.  Maybe that has some impact on your connection?

**Comment by rbtcollins** [comment]
It seems to be getting the complete file but retrying anyway so I suspect a
hash failure. We should increase the diagnostics we provide for the cause
of a retry.

**Comment by AMythicDev** [comment]
> We should increase the diagnostics we provide for the cause of a retry.

That might be a great idea. You should probably implement it by the next release so that everyone can inspect what the issue is

**Comment by rbtcollins** [comment]
If you'd like to put a patch forward for this, that would be helpful. So far, you're the only person reporting unexplainable unexpected retries, so this is a long-tail problem rather than a high frequency issue.

**Comment by AMythicDev** [comment]
Hey guys! Something weird happened today again, I was trying to update to Rust 1.45.2 which dropped yesterday, but the issue still occurs. Sorry but its now getting the hell out od mw because as a programmer for so many languages, I never have seen such a problem in other package managers for programming languages

**Comment by kinnison** [comment]
Hi,  I'm really sorry to hear it's still happening.  That you're the only person experiencing this suggests it's something to do with your PC, your network, your internet link, or your ISP.  More likely toward the start of that list than the end.  Do you have any unusual network proxies in play?  Anything which might be adjusting the files passing through (e.g. for virus checking)?  Is this at home where you have full control of your connection or at work where there might be corporate deep-packet-inspection / modification going on?  If you run with the verbose flag set, do you get any more information?

**Comment by AMythicDev** [comment]
I work at home and no I do not have any weird proixies in my network. I will trying running with the verbose flag again today

**Comment by AMythicDev** [comment]
Well I think I may have found out the issue. The issue happens when I use the Wi-Fi. But while I hook an ethernet to my PC the issue gets solved. Although the issue gets solved, but still I want everyone to look into it

**Comment by rbtcollins** [comment]
So - did you run with verbose mode? Did you get any extra output doing that? We would be delighted to have a patch from you adding more diagnostics, if you're interested in adding that to rustup.

**Comment by AMythicDev** [comment]
No I did'nt do that but how do I do that. I will rollback to an older version and I will try again with the verbose mode

**Comment by AMythicDev** [comment]
Ok. Can anyone tell me how to enable the verbose mode. Also I tried digging into the source code of rustup but I couldn't determine where the error occurs

**Comment by kinnison** [comment]
You can pass `--verbose` when running rustup.

**Comment by AMythicDev** [comment]
Yeah! I did run that before you gave answer but I could'nt find anything interesting in the verbose logs. It just simplt says
`Retrying download for...`

**Comment by kinnison** [comment]
How strange, I wonder if the wifi has some kind of packet squiffing facility which deliberately breaks the payload somehow.

**Comment by AMythicDev** [comment]
I use a portable phone hostspot. So I don't think it is such as problem. It is also encrypted with WPA2/PSK

**Comment by kinnison** [comment]
Hmm, I've seen some odd corruption issues in the past with unusual MTUs.  I've even managed to crash a router once when doing svn+ssh over a VPN, where any combination of svn+ssh or svn+vpn didn't break things.  In the end it turned out to be MTU related tickling some kind of bug in the connection tracker.  I wonder if this hotspot has similar issues.  Are you able to try with a different wifi?

**Comment by AMythicDev** [comment]
Sure. I will try out with a different one and post the results here.

**Comment by rbtcollins** [comment]
As I've mentioned I think the path forward is to improve our diagnostics when a retry occurs. This will require a code change.

**Comment by rbtcollins** [comment]
It may be that tshark or other sysadmin diagnostic tools can tell you what is going on on your machine, but that won't help us diagnose the problem rapidly for any other user that may encounter similar issues.

**Comment by AMythicDev** [comment]
Just for an update, I am going to buy a new router in 1-2 days, so maybe I may get a fix for the issue with that

**Comment by kinnison** [comment]
On the basis that we've had no updates, I intend to close this issue.  If @arijit79 is still encountering issues then we can reopen it.

**Comment by AMythicDev** [comment]
Hey guys, I know I wasn't active for some time. But I recently updated Rust 1.47.0 and I encountered the same issue. But I did notice something, the issue is related with the reqwest back-end. When I switched to the CURL back-end, everything kind a went smoothly. So I suspect that there is some issue with the request back-end

EDIT: Also if it is possible, can you  reopen the issue?

**Comment by kinnison** [comment]
@arijit79 Could you please do some investigation, see if you can reproduce the issue reliably, and if so, if you can reproduce it on any other system in your network?

**Comment by kinnison** [comment]
Also is there any kind of proxy involved? Either explicitly via environment variables, or implicitly via a router with transparent proxying?

**Comment by AMythicDev** [comment]
Thank you guys who have looked into this issue. Today I was updating the nightly compiler and everything worked file. No multiple downloads. Thank you once again
