### ISSUE TITLE
Can't install on Ubuntu-20.04

### ISSUE THREAD

**Issue by rediffusion** [rust-lang/rustup#2450]
Hello! 🙂

«Windows 10 2004» > _WSL 2_ > **Ubuntu**-20.04

**Problem**

📍 _Run this_:

![image](https://user-images.githubusercontent.com/30071027/89720103-55dd8b80-d9d7-11ea-97b8-412c11198a18.png)

> Welcome to Rust!
> 
> This will download and install the official compiler for the Rust
> programming language, and its package manager, Cargo.
> 
> Rustup metadata and toolchains will be installed into the Rustup
> home directory, located at:
> 
>   /home/nika/.rustup
> 
> This can be modified with the RUSTUP_HOME environment variable.
> 
> The Cargo home directory located at:
> 
>   /home/nika/.cargo
> 
> This can be modified with the CARGO_HOME environment variable.
> 
> The cargo, rustc, rustup and other commands will be added to
> Cargo's bin directory, located at:
> 
>   /home/nika/.cargo/bin
> 
> This path will then be added to your PATH environment variable by
> modifying the profile files located at:
> 
>   /home/nika/.profile
>   /home/nika/.zprofile
> 
> You can uninstall at any time with rustup self uninstall and
> these changes will be reverted.
> 
> Current installation options:
> 
> 
>    default host triple: x86_64-unknown-linux-gnu
>      default toolchain: stable (default)
>                profile: default
>   modify PATH variable: yes
> 
> 1) Proceed with installation (default)
> 2) Customize installation
> 3) Cancel installation
> >1
> 
> info: profile set to 'default'
> info: default host triple is x86_64-unknown-linux-gnu
> info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
> info: latest update on 2020-08-03, rust version 1.45.2 (d3fb005a3 2020-07-31)
> info: downloading component 'cargo'
>   5.0 MiB /   5.0 MiB (100 %)   2.2 MiB/s in  2s ETA:  0s
> info: downloading component 'clippy'
>   2.0 MiB /   2.0 MiB (100 %)   1.8 MiB/s in  1s ETA:  0s
> info: downloading component 'rust-docs'
>  12.2 MiB /  12.2 MiB (100 %)   2.3 MiB/s in  6s ETA:  0s
> info: downloading component 'rust-std'
>  15.9 MiB /  15.9 MiB (100 %)   2.4 MiB/s in  7s ETA:  0s
> info: downloading component 'rustc'
>  47.1 MiB /  47.1 MiB (100 %)   2.4 MiB/s in 21s ETA:  0s
> info: downloading component 'rustfmt'
>   3.4 MiB /   3.4 MiB (100 %)   2.2 MiB/s in  1s ETA:  0s
> info: installing component 'cargo'
> info: Defaulting to 500.0 MiB unpack ram
> thread 'main' panicked at 'assertion failed: `(left == right)`
>   left: `22`,
>  right: `4`', src/libstd/sys/unix/thread.rs:179:21
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread 'main' panicked at 'assertion failed: `(left == right)`
>   left: `22`,
>  right: `4`', src/libstd/sys/unix/thread.rs:179:21
> stack backtrace:
>    0:     0x7f8f800daffd - backtrace::backtrace::libunwind::trace::h812748238d609e46
>                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
>    1:     0x7f8f800daffd - backtrace::backtrace::trace_unsynchronized::h7c97e818aebf09c8
>                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
>    2:     0x7f8f800daffd - std::sys_common::backtrace::_print_fmt::h60d914263b0ccd71
>                                at src/libstd/sys_common/backtrace.rs:78
>    3:     0x7f8f800daffd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf78227137afc7565
>                                at src/libstd/sys_common/backtrace.rs:59
>    4:     0x7f8f7fd6524c - core::fmt::write::h543cdf60775f89bf
>                                at src/libcore/fmt/mod.rs:1069
>    5:     0x7f8f800da904 - std::io::Write::write_fmt::h0c7f3ce24c679426
>                                at src/libstd/io/mod.rs:1504
>    6:     0x7f8f800da105 - std::sys_common::backtrace::_print::h80e55e24be231368
>                                at src/libstd/sys_common/backtrace.rs:62
>    7:     0x7f8f800da105 - std::sys_common::backtrace::print::h3b197b9c1261c865
>                                at src/libstd/sys_common/backtrace.rs:49
>    8:     0x7f8f800da105 - std::panicking::default_hook::{{closure}}::ha6c807149ce20f8f
>                                at src/libstd/panicking.rs:198
>    9:     0x7f8f800d98f4 - std::panicking::default_hook::he49a9c12e358cc45
>                                at src/libstd/panicking.rs:218
>   10:     0x7f8f800d93b6 - std::panicking::rust_panic_with_hook::h93f74f5ef2f71f31
>                                at src/libstd/panicking.rs:515
>   11:     0x7f8f800d9198 - rust_begin_unwind
>                                at src/libstd/panicking.rs:419
>   12:     0x7f8f800d9140 - std::panicking::begin_panic_fmt::hfa6ef29ba81f400e
>                                at src/libstd/panicking.rs:373
>   13:     0x7f8f80011671 - <rustup::diskio::threaded::Threaded as rustup::diskio::Executor>::join::habf6ee901a47a8a4
>   14:     0x7f8f80010c78 - core::ptr::drop_in_place::h0b1b0dcb4b07c267
>   15:     0x7f8f7ff76c40 - core::ptr::drop_in_place::h09572fbec04e583f
>   16:     0x7f8f8002842e - rustup::dist::component::package::unpack_without_first_dir::h99f4b0c2cae349ff
>   17:     0x7f8f7ffe559f - rustup::dist::manifestation::Manifestation::update::hacf67fad3b44f03a
>   18:     0x7f8f7ffd563c - rustup::dist::dist::update_from_dist_::h1462627f9c58c494
>   19:     0x7f8f7ffd227a - rustup::install::InstallMethod::install::hbb6430b2dfaf5792
>   20:     0x7f8f7ffd0d21 - rustup::toolchain::DistributableToolchain::install_from_dist::h7b9bf9317c9aa2c5
>   21:     0x7f8f800c5aa2 - rustup::cli::self_update::install::h8ca0f61a773526a9
>   22:     0x7f8f800cbd3d - rustup::cli::setup_mode::main::h4d335e1871435d70
>   23:     0x7f8f7fcdf42a - rustup_init::main::h22da971c634937a2
>   24:     0x7f8f800f3e83 - std::rt::lang_start_internal::{{closure}}::{{closure}}::h4ed4ab1fb893cc93
>                                at src/libstd/rt.rs:52
>   25:     0x7f8f800f3e83 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1f01c818c00c4f70
>                                at src/libstd/sys_common/backtrace.rs:130
>   26:     0x7f8f7fce053f - main
>   27:     0x7f8f7f9670b3 - __libc_start_main
>   28:     0x7f8f7fcdb029 - <unknown>
> thread panicked while panicking. aborting.
> Illegal instruction (core dumped)

---

**Notes**

Output of `rustup --version`:
rustup 1.22.1 (b01adbbc3 2020-07-08)

Output of `rustup show`:
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/duglas/.rustup

no active toolchain

---

`cargo` 
error: no override and no default toolchain set

🆘 Please HELP! 
Best regards ✌️

**Comment by rediffusion** [comment]
OMFG, right now I [SOLVED] my problem. 👍

🔗 [source](https://github.com/rust-lang/rustup/issues/2245#issuecomment-656965108)

```
export RUSTUP_IO_THREADS=1
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

Chao-Chao!

**Comment by kinnison** [comment]
If you're encountering this error it's likely you're also using WSL1 without realising it.

**Comment by rediffusion** [comment]
@kinnison 

 No! I'm using WSL **2** I swear a GOD! 👼
