### ISSUE TITLE
[Tracking issue] Bump freebsd compiler after rust-lang/rust#75204

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rustup#2454]
Rust CI (which rustup uses its docker artifacts) is going to bump its freebsd toolchain to 11.4 .
After https://github.com/rust-lang/rust/pull/75204 landed, one has to upgrade the toolchain rustup used to build.
It should be simple by changing this file: ci/docker/x86_64-unknown-freebsd/Dockerfile

**Comment by kinnison** [comment]
This change in rust was merged 6 days ago.  We should therefore create a PR which has a commit to update the docker file; and then create a commit on top which resets the PR CI to just run freebsd builds so we can check it still works.  After that the top commit can be dropped and we can merge the dockerfile fix.

Does anyone feel up to doing this?
