### ISSUE TITLE
Insufficient test isolation for `/etc/rustup/settings.toml` files

### ISSUE THREAD

**Issue by rbtcollins** [rust-lang/rustup#2456]
**Problem**
When we added the fallback settings capability, we failed to make it properly isolated for testing :(. As such, an `/etc/rustup/settings.toml` file that specifies `stable` as the toolchain will cause `update` (soon to be `update_once` in cli-exact.rs to fail, because the default toolchain *will* be set before the initial update.

Since we need this to be per-test, we probably want to allow an env variable to override the path to it, then set that up in the mock test support glue.

**Comment by Lockna** [comment]
I would like to handle this issue :)
