### ISSUE TITLE
tried to update nightly but got skipping message

### ISSUE THREAD

**Issue by salpalvv** [rust-lang/rustup#2463]
**Problem**

```
info: latest update on 2020-08-12, rust version 1.47.0-nightly (e5e33ebd2 2020-08-11)
info: skipping nightly which is missing installed component 'rustfmt-preview'
info: syncing channel updates for 'nightly-2020-08-11-x86_64-pc-windows-msvc'
512.0 KiB / 512.0 KiB (100 %) 366.5 KiB/s in  1s ETA:  0s
info: latest update on 2020-08-11, rust version 1.47.0-nightly (770bd3d1d 2020-08-10)
info: skipping nightly which is missing installed component 'rustfmt-preview'
info: syncing channel updates for 'nightly-2020-08-10-x86_64-pc-windows-msvc'
503.7 KiB / 503.7 KiB (100 %) 368.0 KiB/s in  1s ETA:  0s
info: latest update on 2020-08-10, rust version 1.47.0-nightly (18f3be770 2020-08-09)
info: skipping nightly which is missing installed component 'rustfmt-preview'
```

Edit: I just uninstalled nightly and tried to reinstall and I'm still getting the skipping per #2417's suggestion. Now I am locked out of being able to do any work as I need nightly features but can't install nightly. 

Edit2: typed `rustfmt` just to see and it...downloaded latest nightly so, it looks like it's working again. I am no longer blocked but, confused and slightly annoyed. 

```
PS E:\rust\nina> rustup install nightly-2020-08-12
info: syncing channel updates for 'nightly-2020-08-12-x86_64-pc-windows-msvc'
512.0 KiB / 512.0 KiB (100 %) 367.1 KiB/s in  1s ETA:  0s
info: latest update on 2020-08-12, rust version 1.47.0-nightly (e5e33ebd2 2020-08-11)
error: component 'rustfmt' for target 'x86_64-pc-windows-msvc' is unavailable for download for channel nightly-2020-08-12
Sometimes not all components are available in any given nightly.
PS E:\rust\nina> rustfmt
info: latest update on 2020-08-12, rust version 1.47.0-nightly (e5e33ebd2 2020-08-11)
warning: Force-skipping unavailable component 'rustfmt-x86_64-pc-windows-msvc'
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: Defaulting to 500.0 MiB unpack ram
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
```
**Steps**

1. Tried to update nightly

**Notes**
Happened a week ago so don't know if I'm using the same versions then as now and I'm not apt to lock myself out of development again to figure out if I can reproduce it.

Output of `rustup --version`:
Output of `rustup show`:

**Comment by rbtcollins** [comment]
I'm not sure I understand the issue. Nightly doesn't build all components every day. They often fail. The "info: skipping nightly which is missing installed component xxx" message is telling you that a particular day of nightly doesn't have the components you want, and it repeats for each day that is probed until a day is found when all the components succeeded, when that day gets installed.

To avoid this behaviour, don't install nightly.

**Comment by salpalvv** [comment]
How do I update nightly and skip those components? 

Edit: I want to bring this back to being constructive. I had an issue that looked like it was on an issue already posted. I thought it was the right thing to do to post under it instead of making my own issue to avoid duplication. Obviously, I was confused, as I stated in the response. It took a week to tell me that was the wrong thing to do without a clear explanation ( I am confused so, I apologize for asking for clarification). Now you are telling me to not install nightly when my project uses nightly features, which I feel is unhelpful. 

So, really, this seems like user error. I want to make sure you know that I spent about an hour trying different `--help` commands looking for a way to solve this and googling the issue and the previous issues I have mentioned are the only ones that appeared. I also attempted to update nightly with the component, which failed but clearly missed any way to update without those components. So, maybe this is an indication that there could be a clearer explanation for what one can do to not install those components in the cli. I've had a generally seamless experience using `rustup` for years and this was the first issue I have encountered and I thought that reporting this issue was the right thing to do. I apologize for any anguish this has caused as I generally shy away from reporting anything.

Please let me know how to continue. I intended participating in this discussion to be fruitful and also give some personal user experience and I have failed.

**Comment by kinnison** [comment]
From `rustup update --help` you can use `--force` to force an update even if components are missing.  Note this will leave your nightly without the component in question and you'd have to reinstall the component when it becomes available yourself, `rustup` will not remember for yo.

**Comment by salpalvv** [comment]
`--force` didn't work for me. It was giving me the same "skip" messages.

**Comment by kinnison** [comment]
That's unexpected, so `rustup update --force nightly` did skips rather than forcing the install?

**Comment by salpalvv** [comment]
yeah but i can't recreate it now. it's just working, as it always has before i had this issue.
I'm just gonna close this since it may have just been something with my setup.
If it happens again, I'll attempt to document it better. 

Thanks for all the help.

**Comment by beppe9000** [comment]
is it possible to install a package from stable or beta if it is not available in nightly ?

**Comment by kinnison** [comment]
No, channels are integral.  Sorry.

**Comment by beppe9000** [comment]
ok thanks for clearing that
