### ISSUE TITLE
Give a better error message when a component is missing with a linked toolchain

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustup#2470]
**Describe the problem you are trying to solve**
If I try to use a component from a tool that is currently building with `x.py`, rustup currently gives the following error:

```
$ rustdoc +stage1
error: 'rustdoc' is not installed for the toolchain 'stage1'
To install, run `rustup component add rustc --toolchain stage1`
```
The second line is not helpful: when you run it it will always give an error.
```
$ rustup component add rustc --toolchain stage1
error: stage1 is a custom toolchain
```

**Describe the solution you'd like**

Instead it should suggest building the tool with x.py:
```
To install, run `x.py build src/tools/rustdoc`.
```

**Notes**

Ideally, rustup would know about compile stages and suggest `--stage 0` or `--stage 2` as necessary. However, if the user is using a local toolchain they should know about stages already, so it's ok to let them figure out for themselves which stage they want.

**Comment by kinnison** [comment]
We cannot guarantee that linked toolchains are constructed with `x.py` however I agree this is an unhelpful message when the linked toolchain cannot have components.  It should be moderately easy to detect that and issue a different form of the message which does not make the suggestion to install that component.

**Comment by kinnison** [comment]
Whoever tackles this should note there's both the `$proxyname +toolchainname...` approach and also `rustup run toolchainname command` which will need fixing up.  Note that both already deal with the situation where the component is not available in the given channel, so there ought to be code to hook in another case to.

**Comment by workingjubilee** [comment]
Rustup currently has no concept of x.py and stage0~stage2 and, given that those are frequently brought up as confusing, it probably should not acquire that knowledge. :^)

It would be one more place to have to sync the overall rustbuild strategy with!
