### ISSUE TITLE
Use non-LTO builds for non-stable branches

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rustup#2474]
This may improve CI time of rustup ~a lot~ by minutes.
Last attemps: https://github.com/rust-lang/rustup/pull/2300

**Comment by kinnison** [comment]
Will this potentially impact our ability to notice issues around the multithreaded portions of rustup?  I'd be okay with disabling it for non-stable builds of platforms we don't run the test suite on; but if we're running the test-suite then I feel we ought to do it against a similarly compiled binary to a release.

**Comment by tesuji** [comment]
> issues around the multithreaded portions of rustup

I've never heard of it but I am not sure. Although in that case it should be 
a compiler bug which is more serious than rustup issue.

> if we're running the test-suite then I feel we ought to do it against a similarly compiled binary to a release.

I don't have strong opinion to this. They're both fine but we should measure the build time first.

**Comment by kinnison** [comment]
At this time I'm not sure that the CI turnaround time is dominated by the link cost (which is effectively what disabling LTO will improve) though I won't object to someone doing some experiments to determine the difference.

**Comment by tesuji** [comment]
Block on #2482 .
