### ISSUE TITLE
Consider dropping "info: Defaulting to 500.0 MiB unpack ram" for rustup commands.

### ISSUE THREAD

**Issue by nealmcb** [rust-lang/rustup#2484]
**Describe the problem you are trying to solve**

When I run `rustup component add ...`, I get this line at the end:

    info: Defaulting to 500.0 MiB unpack ram

As discussed at [What does rustup mean by "Defaulting to 500\.0 MiB unpack ram"? \- help \- The Rust Programming Language Forum](https://users.rust-lang.org/t/what-does-rustup-mean-by-defaulting-to-500-0-mib-unpack-ram/48528/4), it appears that the message isn't of much value to the end user, and other values for the amount of RAM available for unpacking crates may not be very relevant.

**Describe the solution you'd like**

Either drop the message, saving users' cognitive load, or document why the message is useful to the end user, e.g. under what circumstances the user might want to change the RAM available for unpacking.

**Notes**

```
$ rustup --version
rustup 1.22.1 (b01adbbc3 2020-07-08)
```

**Comment by kinnison** [comment]
We chose to leave that message at `info` rather than demoting it to `verbose` or `debug` because we wanted it visible in logs if anyone reported an issue which might be related to unpack RAM.  We have had small system issues in the recent past, so I'd prefer to leave this message in for now.  Perhaps rewording it somehow might be useful.

**Comment by nealmcb** [comment]
Ahh, that's helpful.  I'd suggest we provide a string which produces useful hits when we search for it, and ideally also yields hints on how to adjust the value.  How about:

    info: Allocating 500 MiB of RAM for unpacking: $RUSTUP_UNPACK_RAM=524288000

**Comment by poliorcetics** [comment]
IIRC the environnement variable used to modify this is unstable, maybe it shouldn't be made visible in `info` logs.

**Comment by kinnison** [comment]
It is unstable, we don't want the message there to encourage people to change it, we want it there because when it matters we don't want to have to ask people to try again with it set to something.  Perhaps simply `info: Using up to XXX of RAM for unpacking components`.

**Comment by nealmcb** [comment]
It sounds like one goal is to use this to help debug issues, but most of the time you want people to ignore it.
But rust developers are curious, and want to understand things, and help when they can.

So I like `info: Using up to XXX of RAM for unpacking components` but would add a token to help people find out why they're being told this and to let people easily dig for more info. The environmental variable is one such token, but perhaps a better one would be a some sort of FAQ token or issue number (this one, or some previous issue tracking the underlying issues) or the like.

Or perhaps, now that this discussion and the users post on it is discoverable with the current text, it is its own token and we can stick with it ;)

**Comment by kinnison** [comment]
I get your point about wanting to make sure curious people are sated, but I'd rather just ensure that the text (which we *DO* want to keep at `info` for at least the near to medium term) is self-explanatory.  So if someone wants to PR for the new text we discussed above, and then ensure that the text is in the users forum thread too, that'd be awesome.

**Comment by camelid** [comment]
Before I saw this thread, I was thinking of suggesting changing it to:

```
info: defaulting to {500.0 MiB} buffer for unpacking download
```

But I think the one that was settled upon is a big improvement; I'll open a PR.

**Comment by nealmcb** [comment]
Thanks to @camelid for the fix. For the record (and the search engines), the default text is now:

    using up to 500.0 MiB of RAM to unpack components

and that is also noted now in the original forum thread.
