### ISSUE TITLE
Can't install nigtly toolchain

### ISSUE THREAD

**Issue by selassje** [rust-lang/rustup#2485]
rustup --version
rustup 1.22.1 (b01adbbc3 2020-07-08)

rustup toolchain install nightly
info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
info: latest update on 2020-09-12, rust version 1.48.0-nightly (99111606f 2020-09-11)

  nightly-x86_64-pc-windows-msvc unchanged - (toolchain not installed)

info: checking for self-updates

**Comment by ehuss** [comment]
This should be fixed in the next nightly via https://github.com/rust-lang/rust/pull/76639.
