### ISSUE TITLE
Double `error:` print

### ISSUE THREAD

**Issue by maxwase** [rust-lang/rustup#2492]
**Problem**
Double `error` word print when executing 2nd level unexpected subcommand
Expected 1 `error` word like in all other cases

![image](https://user-images.githubusercontent.com/23321756/93513375-6ebe5280-f92e-11ea-9d62-ccb89e975ec9.png)

**Steps**
1. Execute `rustup link unexpected_option` or `rustup toolchain unexpected_option` or ... (any wrong 2nd level subcommand)

**Notes**

Output of `rustup --version`: rustup 1.22.1 (b01adbbc3 2020-07-08)
Output of `rustup show`: 
```Default host: x86_64-unknown-linux-gnu
rustup home:  /home/max/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
1.41.0-x86_64-unknown-linux-gnu
1.42.0-x86_64-unknown-linux-gnu
1.45.0-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

thumbv6m-none-eabi
thumbv7m-none-eabi
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.46.0 (04488afe3 2020-08-24)
```

**Comment by kinnison** [comment]
I can confirm this issue still exists on master.  It should be fairly simple to fix.

**Comment by rbtcollins** [comment]
Looks like its been fixed
