### ISSUE TITLE
Missing std lib HTML docs

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/rustup#2494]
**Problem**

Maybe its a problem with my local setup, but I've been missing the HTML docs (in `.rustup/toolchains/nightly-x86_64-apple-darwin/share/doc/rust/html/index.html`) since the `2020-09-11` nightly. Running `rustup doc` gives the following error: 

```
error: couldn't open browser
error: caused by: command 'open' did not execute successfully; exit code: 1
command stderr:
The file /Users/thomas/.rustup/toolchains/nightly-x86_64-apple-darwin/share/doc/rust/html/index.html does not exist.
```

**Steps**

1. Update to a recent nightly, I'm using `rustc 1.48.0-nightly (f3c923a13 2020-09-17)`.
2. Run `rustup doc`.

**Notes**

Output of `rustup --version`: `rustup 1.22.1 (b01adbbc3 2020-07-08)`.
Output of `rustup show`:
```
Default host: x86_64-apple-darwin
rustup home:  /Users/thomas/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-2020-09-11-x86_64-apple-darwin
nightly-x86_64-apple-darwin

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.48.0-nightly (f3c923a13 2020-09-17)
```

**Comment by kinnison** [comment]
If you run `rustup +nightly component list --installed` is the `rust-docs` component listed?

**Comment by Thomasdezeeuw** [comment]
```
rustup +nightly component list --installed

cargo-x86_64-apple-darwin
clippy-x86_64-apple-darwin
miri-x86_64-apple-darwin
rls-x86_64-apple-darwin
rust-docs-x86_64-apple-darwin
rust-src
rust-std-x86_64-apple-darwin
rustc-x86_64-apple-darwin
rustfmt-x86_64-apple-darwin
```

**Comment by Thomasdezeeuw** [comment]
I see its missing `rust-docs`, but when I do `rustup component add rust-docs`, I get the following:

```
rustup component add rust-docs
info: component 'rust-docs' for target 'x86_64-apple-darwin' is up to date
```

**Comment by kinnison** [comment]
The `rust-docs` component is arch specific, which is why it's listed as `rust-docs-x86_64-apple-darwin` so that's good that it's installed, but worrisome that the location isn't working, hmm

Could you please go into your `.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib` directory and find the file: `manifest-rust-docs-x86_64-apple-darwin` and either attach it if it's big, or paste it in a comment if it's small?

Also, once you've done that, try to see if anything listed in that manifest is present on the filesystem.  Paths are relative to the toolchain directory (`.rustup/toolchains/nightly-...`)

**Comment by Thomasdezeeuw** [comment]
`manifest-rust-docs-x86_64-apple-darwin` contains:

```
dir:share/doc/rust/html
```

The directory (`~/.rustup/toolchains/nightly-x86_64-apple-darwin/share/doc/rust/html`) exists with the following files:

```
Permissions Size User   Date Modified Name
.rw-r--r--  1.4M thomas 18 Sep 10:57  error-index.html
.rw-r--r--   334 thomas 18 Sep 10:57  robots.txt
drwxr-xr-x     - thomas 18 Sep 10:57  rustc
```

But its missing the `std` directory which usually contains the docs for the std lib.

**Comment by kinnison** [comment]
Interesting. @Mark-Simulacrum Do you have any insight as to why this might be happening?  I think there've been changes to docs packages recently in master?

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/pull/76884 should fix this for macOS and a few other triples.

**Comment by Thomasdezeeuw** [comment]
Docs are available again, thanks @Mark-Simulacrum @kinnison.
