### ISSUE TITLE
File too big error installing nightly on Alpine Linux

### ISSUE THREAD

**Issue by svenski123** [rust-lang/rustup#2495]
**Problem**

Can't install nightly toolchain on alpine linux (x86_64-unknown-linux-musl).
rustc fails to install with a "File too big" error.

**Steps**

```
$ podman run --rm -it alpine
/ # apk add rustup
[...]
/ # rustup-init -y --default-toolchain nightly
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-musl
info: syncing channel updates for 'nightly-x86_64-unknown-linux-musl'
info: latest update on 2020-09-18, rust version 1.48.0-nightly (f3c923a13 2020-09-17)
[...]
info: installing component 'rustc'
  8.5 MiB /  76.4 MiB ( 11 %)   0 B/s in  1s ETA: Unknown                                                          19.7 MiB /  76.4 MiB ( 26 %)   8.5 MiB/s in  2s ETA:  6s                                                          23.5 MiB /  76.4 MiB ( 31 %)   9.8 MiB/s in  2s ETA:  5s
info: rolling back changes
error: File too big rustc-nightly-x86_64-unknown-linux-musl/rustc/lib/librustc_driver-88743cfd7934bc11.so 208539136
/ #
```
**Possible Solution(s)**

Seems similar to #2363.  
Perhaps the rustup-init package in Alpine Linux needs to be updated?

**Notes**

Output of `rustup-init --show`:
rustup-init 1.21.1 :: v20200428+640 (e0579bdf9 2020-05-08)

**Comment by rbtcollins** [comment]
Yep, thats an old rustup; get the alpine folk to update their rustup - generally speaking I wouldn't use packaged rustups - we don't maintain (most of) them, and they are by definition out of date.
