### ISSUE TITLE
Rustup won't install rust-src src files on nightly 1.48

### ISSUE THREAD

**Issue by zenMaya** [rust-lang/rustup#2497]
**Problem**

Rustup won't install rust-src src files. Library and Cargo.lock are present. But no src folder.
**Steps**

1. install rustup 1.22.1
2. install nightly toolchain
3. install rust-src component to that toolchain
4. the src file is missing from `~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust`

**Notes**
This is not present on stable toolchain
Output of `rustup --version`: 1.22.1 (2020-07-08)
Output of `rustup show`: rustc 1.48.0-nightly (0da580074 2020-09-22)

**Comment by ehuss** [comment]
This is expected, the `rust-src` component only includes the standard library. Is there something specific you are looking for?  The `rustc-dev` component recently added the compiler source.

**Comment by zenMaya** [comment]
My bad then. Probably out of date instructions on rust-analyzer side
