### ISSUE TITLE
Cargo on Raspberry Pi2* not using default toolchain

### ISSUE THREAD

**Issue by ukscone** [rust-lang/rustup#2500]
**Problem**

*only tested on Pi2, might be on other models too

Building a program [in this case Raspberry Pi example from https://github.com/PatrickLang/ssd1306/tree/raspi-example/examples/raspi ] fails with the error message
```
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7m-none-eabi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `void`.

To learn more, run the command again with --verbose.
```
if I build using 
`cargo build --target arm-unknown-linux-gnueabihf`

it works.

**Steps**
1. build on Raspberry Pi using "cargo build" build fails with error[E0463]
2. build on raspberry Pi using "cargo build --target arm-unknown-linux-gnueabihf" build works as expected

**Notes**
.
the default toolchain as listed by rustup is the correct arm-unknown-linux-gnueabihf
```
pi@raspberrypi:~/ssd1306/examples/raspi $ rustup show
Default host: arm-unknown-linux-gnueabihf
rustup home:  /home/pi/.rustup

stable-arm-unknown-linux-gnueabihf (default)
rustc 1.46.0 (04488afe3 2020-08-24)
pi@raspberrypi:~/ssd1306/examples/raspi $ 
```

```
pi@raspberrypi:~/ssd1306/examples/raspi $ rustup --version
rustup 1.22.1 (b01adbbc3 2020-07-08)
pi@raspberrypi:~/ssd1306/examples/raspi $ rustup show
Default host: arm-unknown-linux-gnueabihf
rustup home:  /home/pi/.rustup

stable-arm-unknown-linux-gnueabihf (default)
rustc 1.46.0 (04488afe3 2020-08-24)
pi@raspberrypi:~/ssd1306/examples/raspi $ cargo --version
cargo 1.46.0 (149022b1d 2020-07-17)
pi@raspberrypi:~/ssd1306/examples/raspi $ 
```

![Screenshot 2020-09-29 at 11 29 11 AM](https://user-images.githubusercontent.com/3171454/94580562-12213880-0248-11eb-857e-b3607e5bf0ee.png)
![Screenshot 2020-09-29 at 11 25 11 AM](https://user-images.githubusercontent.com/3171454/94580579-16e5ec80-0248-11eb-92f0-6350456a8bf9.png)
![Screenshot 2020-09-29 at 11 24 59 AM](https://user-images.githubusercontent.com/3171454/94580607-1ea59100-0248-11eb-84b5-d99a15c521bd.png)

**Comment by Michael-F-Bryan** [comment]
For a bit more context see [*Can’t find crate for `std` when building on a raspberry pi*](https://users.rust-lang.org/t/cant-find-crate-for-std-when-building-on-a-raspberry-pi/49425) on the user forums.

**Comment by rbtcollins** [comment]
Thank you for the bug, however we need to move it :). 

rustup installs *toolchains*. A toolchain can build rust for many different targets. toolchains themselves decide what the default target is, not rustup, at least as things are layered today.

toolchains describe where you can run the compiler; targets describe where the binary output by the compiler can be run.


So this is either a cargo or rustc behaviour that is causing the problem : rustup has successfully installed the right software for your use case, by default (as shown by your ability to use it when you add the --target option).

**Comment by rbtcollins** [comment]
Actually, I guess there might be multiple toolchains that can run, which might have different default targets; but irrespective of that possibility you are asserting that the description of the toolchain matches your ABI, so rustup has done its job; but the toolchain isn't defaulting to the target you expect it to.

**Comment by Nemo157** [comment]
The linked example has a `.cargo/config` overriding the default target: https://github.com/PatrickLang/ssd1306/blob/raspi-example/.cargo/config#L29

**Comment by rbtcollins** [comment]
So its a self inflicted injury then? Perhaps cargo needs to emit a user visible sign that such a config is being used? Make this definitely something to move to Cargo though :)

**Comment by kinnison** [comment]
@rust-lang/cargo Is there an issue we can link this to, or do one of you want to take this issue over and move it?

**Comment by ukscone** [comment]
> The linked example has a `.cargo/config` overriding the default target: https://github.com/PatrickLang/ssd1306/blob/raspi-example/.cargo/config#L29

oh thank you. didn't spot that. that'd explain it

**Comment by ehuss** [comment]
That's a tricky one. Cargo doesn't have any knowledge about what targets are installed.  E0463 is too generic to trigger off of.  I unfortunately don't have any ideas on how to make the cause more discoverable.

**Comment by workingjubilee** [comment]
In strictly hardware terms, a Raspberry Pi 2 *should* be able to execute thumbv7m code, but 32-bit Raspberry Pi OS are aimed at the "ARM v6 with floating point unit" (in actual triples it is usually the unmarked "arm") target for maximum compatibility, so it would make sense for the target to not be installed by default when Rustup installs because Rustup tries to come with the targets that are appropriate for the given environment and not speculate on every target that is compatible with the given hardware.

Also I said "should" but that is with less-than-100% certainty.

**Comment by Nemo157** [comment]
@ehuss what about always emitting a small message at the start of compilation for each loaded config file:

![temp](https://user-images.githubusercontent.com/81079/94794264-e9ca4300-03db-11eb-9a3d-59f5db8a8a17.png)

**Comment by ehuss** [comment]
Cargo's output is already a little too verbose, so I think adding more messages to the default output is unlikely.

**Comment by rbtcollins** [comment]
Can we please move this bug at this point? Its clearly not rustup related ;)
