### ISSUE TITLE
rustup.rs "other installation options" link is broken

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rustup#2512]
<https://rustup.rs/> has a link in the footer to <https://github.com/rust-lang/rustup/#other-installation-methods>, but I think it should now be <https://rust-lang.github.io/rustup/installation/other.html>.

Sorry if this is the wrong repo, as I don't know where that's actually hosted.

**Comment by ehuss** [comment]
This has already been fixed via #2461, but I believe that the rustup.rs website is only updated when a release is made. I'm not sure if it is possible to update just the website (it looks like someone would need to manually run some aws commands).

**Comment by kinnison** [comment]
I asked before, and manual website updates are a pain apparently.  We'll get to a release hopefully soon, which will make the fix go live.

**Comment by kinnison** [comment]
Rustup 1.23.0 is now out.
