### ISSUE TITLE
Default choice when running rustup-init without build tools installed is to continue

### ISSUE THREAD

**Issue by creekorful** [rust-lang/rustup#2514]
**Describe the problem you are trying to solve**

Running `rustup-init.exe` on a computer without C++ build tools installed display an useful message explaining to the
user how to install the requirement, while indicating that this requirement may be ignored if the user want to target only GNU ABI, or if he know what he's doing.

The default action prompted is to continue the installation process anyway, and I think it may not be the best idea. A lot of users will just want to get started with rust and will likely need the build tools installed before installing the toolchain. The other scenario will happen less often.

I think the default choice should be to not continue the installation process to prevent mistakes, and letting people who *know what they are doing* choosing to continue the installation process anyway.

![Capture](https://user-images.githubusercontent.com/8199428/95487815-18748a80-0995-11eb-9e96-32c888567355.PNG)

**Describe the solution you'd like**

Changing the default action to **No** to prevent any mistakes.

**Notes**

I think this is an opinionated suggestion and may not be the best one, therefore it's rather an open question than an issue.

**Comment by kinnison** [comment]
As someone who is not a Windows dev by default, I do not know what the most common situation is for people.  I'd imagine anyone doing development on Windows will understand what to do here, but perhaps the default should be 'n' to improve chances people actually read the message before proceeding?

**Comment by creekorful** [comment]
Yea that was exactly my point, I have struggle to explain what I'm thinking but you're right!

**Comment by kinnison** [comment]
Okay, so if someone wants to take this on, the goal is to change the default for this prompt from `Y` to `N`.  Mentoring available if needed, but it should be a fairly straightforward change.

**Comment by creekorful** [comment]
I can manage the PR later today!

**Comment by creekorful** [comment]
I have opened the PR!

Cheers,
