### ISSUE TITLE
Migration to new way to set env var and path in GH Actions

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rustup#2515]
Deprecation announcement blog: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

New way: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files

An affected file: https://github.com/rust-lang/rustup/blob/243b453934929ea19f4172f626018531bab45ddd/ci/actions-templates/linux-builds-template.yaml#L82-L83

**Comment by tesuji** [comment]
Maybe fixed by #2513.

**Comment by kinnison** [comment]
This has been merged now.
