### ISSUE TITLE
Warn when downloading a toolchain for a different platform

### ISSUE THREAD

**Issue by mk12** [rust-lang/rustup#2520]
# Problem

I recently tried to cross compile a Windows binary from my MacBook.

After some research, I figured I needed to install a new toolchain:

```
$ rustup toolchain install stable-x86_64-pc-windows-msvc
...
  stable-x86_64-pc-windows-msvc installed - (rustc does not exist)
```

It apparently succeeded (exit status 0), but then when I try to build it can't find cargo:

```
$ cargo +stable-x86_64-pc-windows-msvc build
error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the 'stable-x86_64-pc-windows-msvc' toolchain
```

After more searching I realized this is giving me a toolchain for building _on_ Windows, i.e. cargo.exe. What I really want is to just have one toolchain for my Mac, but add a target _for_ Windows:

```
$ rustup target add x86_64-pc-windows-msvc
$ cargo build --target x86_64-pc-windows-msvc
```

(It still doesn't work because there are [more steps](https://v4.chriskrycho.com/2016/using-rust-for-scripting.html#fnref1) to get linking to work, but at least I'm on the right track now.)

# Request

It would have saved me an hour if rustup had printed something like:

```
warning: toolchain stable-x86_64-pc-windows-msvc cannot run on this platform; use `rustup target add` if you want to compile to a non-host target
```

**Comment by kinnison** [comment]
Unfortunately it's not entirely obvious which host toolchains will run sucessfully on any given system.  For example, I can run "natively" any of x86_64 linux, amd64 linux, i686 linux, x86_64 windows, and i686 windows binaries on my Linux laptop.

I suppose a warning when the toolchain build does not match the system host would be plausible, but it'd annoy people particularly who install i686 versions of the toolchain on their x86_64 systems.

Perhaps softening the wording to:

```
warning: toolchain stable-x86_64-pc-windows-msvc may not be able to run on this system.
warning: If you meant to build software to target that platform, perhaps try `rustup target add x86_64-pc-windows-msvc` instead?
```

What do you think?

**Comment by mk12** [comment]
(By running windows binaries natively on linux, do you mean using Wine?)

For sure, I just quickly typed out that warning message, assuming it would be given some more thought if this is implemented :) Your softer wording looks good to me, and would have solved my problem.

**Comment by kinnison** [comment]
Yes, with a bunch of bits and bobs, wine, qemu, etc. you can run a lot of non-native binaries as though they were native.

I'm glad the suggested rewording works for you.

If anyone wants to make this change, mentoring is available on #wg-rustup on our discord, or you can comment here.

**Comment by frbimo** [comment]
@kinnison  can i take this?

**Comment by kinnison** [comment]
@frbimo Of course, you're very welcome to do so.

**Comment by frbimo** [comment]
yuhuuu 1 contribution to rustup. thanks @kinnison . 
please help me to close this issue since i used the wrong command to link it.

**Comment by kinnison** [comment]
Rustup 1.23.0 is now out.
