### ISSUE TITLE
Can't find `/src/rust/src` after running `rust-src` 

### ISSUE THREAD

**Issue by scuellar** [rust-lang/rustup#2522]
**Problem**
After successfully running `rustup component add rust-src` the folder `[path]/.rustup/toolchains/[my-toolchain]/lib/rustlib/src/rust/src` doesn't exist.
From [this issue](https://github.com/rust-lang/rustup/issues/742), Im expecting the sources to be put in there but I can't find them.

The context here is that I want to install racer, which expects the source to be there but can't find it.

**Steps**
I'm following this [installation guide ](https://github.com/racer-rust/racer#installation) step by step using cargo. 

After running `rustup component add rust-src`, first time it succeeds, second time I get
`info: component 'rust-src' is up to date`
I can even run 
```
% rustup component list | grep rust-src      
rust-src (installed)
```

However if I run:
```
% echo `rustc --print sysroot`/lib/rustlib/src/rust/src
[path]/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src
% cd [path]/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src
cd: no such file or directory: [path]/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src
% cd [path]/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust
% ls
Cargo.lock	library
```

Where did it go?  
**Possible Solution(s)**
Looking back at [this issue](https://github.com/rust-lang/rustup/issues/742), could you provide a command to find the folder with the installed source?

**Notes**

Output of `rustup --version`: rustup 1.22.1 (b01adbbc3 2020-07-08)
Output of `rustup show`:
```
Default host: x86_64-apple-darwin
rustup home:  /Users/myname/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.47.0 (18bf6b4f0 2020-10-07)
```

**Comment by ehuss** [comment]
The directory was renamed to `library`.  Racer was updated in https://github.com/racer-rust/racer/pull/1130 to use the new directory, but it looks like the README was not updated.  Perhaps file an issue on the racer repo?

**Comment by scuellar** [comment]
Ah, thank you so much! Unfortunately there is so much outdated info out there I was sure it had to be at `src`.


Yeah and that fix is not on the most recent release. I'll try to send them a PR.

**Comment by kinnison** [comment]
Since this is a `racer` issue, I'm closing it.  Thanks @ehuss
