### ISSUE TITLE
Protocol "https" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by JonasVautherin** [rust-lang/rustup#2524]
**Problem**
When cross-compiling VLCKit for iOS (aarch64, though armv7 seems to work), I get the following error:

```
export TARGET_CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang && export TARGET_AR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar && export TARGET_CFLAGS="-mios-version-min=9.0 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk -Werror=partial-availability -fno-stack-check -I/Users/jones/Documents/px4/VLCKit/libvlc/vlc/build-iphoneos-arm64/contrib/arm64-iphoneos14.0/include -g -O2" && export RUSTFLAGS="-C lto -C panic=abort -C opt-level=z" && export RUSTUP_USE_HYPER=1 && . /Users/jones/Documents/px4/VLCKit/libvlc/vlc/contrib/bin/.cargo/env && RUSTUP_HOME=/Users/jones/Documents/px4/VLCKit/libvlc/vlc/contrib/bin/.rustup CARGO_HOME=/Users/jones/Documents/px4/VLCKit/libvlc/vlc/contrib/bin/.cargo cargo capi install --target=aarch64-apple-ios --prefix=/Users/jones/Documents/px4/VLCKit/libvlc/vlc/build-iphoneos-arm64/contrib/arm64-iphoneos14.0 --library-type staticlib --release --locked --no-default-features --features=asm
Error: CliError { error: Some(failed to download from `https://crates.io/api/v1/crates/time/0.1.44/download`

Caused by:
    [1] Unsupported protocol (Protocol "https" not supported or disabled in libcurl)), exit_code: 101 }
```

Which seems to be the same as reported in #1051.

As can be seen above, the command that fails is: `cargo capi install --target=aarch64-apple-ios --prefix=/Users/jones/Documents/px4/VLCKit/libvlc/vlc/build-iphoneos-arm64/contrib/arm64-iphoneos14.0 --library-type staticlib --release --locked --no-default-features --features=asm`

**Steps**

1. Clone VLCKit (https://code.videolan.org/videolan/VLCKit)
2. Run the script: `./compileAndBuildVLCKit.sh -a aarch64 -v`. May need some patches as reported in [my report here](https://code.videolan.org/videolan/VLCKit/-/issues/437).
3. Observe that the error happens

**Possible Solution(s)**
Related to #1051 

**Notes**

Running on macOS Catalina 10.15.7
Output of `rustup --version`: I don't have rustup on my system, I am running `cargo` (does it embed rustup?)
Output of `rustup show`: ^

In #1051, @malbarbo mentions using [this script](https://gist.github.com/malbarbo/44e4194434ac3bfe9c1f0e618f6099f0) to get some diagnostics. When I do, I get the following output:

```
% ./find-broken-rustup-init.sh 
aarch64-linux-android: Broken
aarch64-unknown-linux-gnu: Broken
arm-linux-androideabi: Broken
arm-unknown-linux-gnueabi: Broken
arm-unknown-linux-gnueabihf: Broken
armv7-linux-androideabi: Broken
armv7-unknown-linux-gnueabihf: Broken
i686-linux-android: Broken
i686-unknown-linux-gnu: Broken
x86_64-unknown-freebsd: Broken
x86_64-unknown-linux-gnu: Broken
x86_64-unknown-netbsd: Broken
```

**Comment by kinnison** [comment]
That script cannot be correct, since x86_64-unknown-linux-gnu is the platform I use, and it clearly works for me.  I wonder what it is trying to prove.

Regardless, the actual error you're reporting is in `cargo` not in `rustup` since `rustup` isn't involved in downloading crates.  I wonder if `cargo capi` is somehow doing something odd and re-executing cargo underneath itself using a bad sysroot or somesuch.

**Comment by JonasVautherin** [comment]
Right. I will ask on the cargo repo then. Sorry for the inconvenience :confused:.

**Comment by kinnison** [comment]
@JonasVautherin No problem, it's easy to confuse, for sure.  Good luck.  I hope you manage to get this resolved quickly.
