### ISSUE TITLE
Installation help message is printed when attempting to use uninstalled component for toolchains created with `toolchain link`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rustup#2531]
**Problem**
Currently if a component is not installed for a custom-linked toolchain, you will get an error message like this:

```
error: 'rustc' is not installed for the toolchain 'r2stage1'
To install, run `rustup component add rustc --toolchain r2stage1`
```

Yet that is not helpful since the toolchain is not an official toolchain that just doesn't have the component installed. Instead, the error should be something like:

```
error: 'rustc' is not installed for the toolchain 'r2stage1'
The toolchain 'r2stage' was created with `rustup toolchain link` so you will have to install the component yourself.
```

**Steps**
1. Link a toolchain; e.g.: `rustup toolchain link stage1 rust/build/x86_64-apple-darwin/stage1`
2. Delete a component (e.g. by running `./x.py clean` with the example in (1))
3. Try using the component: `rustc +r2stage1 foo.rs`

**Possible Solution(s)**
I suggest an error like this:

```
error: 'rustc' is not installed for the toolchain 'r2stage1'
The toolchain 'r2stage' was created with `rustup toolchain link` so you will have to install the component yourself.
```

**Notes**

Output of `rustup --version`: `rustup 1.22.1 (b01adbbc3 2020-07-08)`

**Comment by camelid** [comment]
(Sorry for the not super clear title -- I wasn't sure how to describe the issue)

**Comment by kinnison** [comment]
I think this is related to #2470 which was fixed in #2487 and so will be in the next release.

I'm tagging this as such so that you'll know when we make the next release.

**Comment by camelid** [comment]
Oh, great! Thanks @jyn514 :)

**Comment by kinnison** [comment]
Rustup 1.23.0 is now out.
