### ISSUE TITLE
rustup.rs website is out of date compared to master

### ISSUE THREAD

**Issue by holly-hacker** [rust-lang/rustup#2535]
The rustup.rs website seems to be out of date. 2 months ago, commit 17f4ee00ae7558210c7bd29b9b71d30bdd9e0235 fixed an outdated link for "other installation methods", but the website still contains the dead link.

**Comment by ehuss** [comment]
Unfortunately the website updates are tied to releases, so the fix has to wait for the next release (as discussed in #2512).

**Comment by holly-hacker** [comment]
Sorry, I didn't notice that this was a duplicate.
