### ISSUE TITLE
error: toolchain 'stable-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target 'x86_unknown-linux-musl'

### ISSUE THREAD

**Issue by jonee** [rust-lang/rustup#2537]
**Problem**

The command "rustup target add x86_unknown-linux-musl" gives an error output
error: toolchain 'stable-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target 'x86_unknown-linux-musl'; did you mean 'i586-unknown-linux-musl'?

Newly installed Debian 10 (kernel 4.19.0-12-amd64) and Ubuntu 20.04 (kernel 5.4.0-52-generic). 

**Steps**

1. new install of debian 10 or Ubuntu 20.04
2. curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh # choose default install
3. rustup target add x86_unknown-linux-musl
error: toolchain 'stable-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target 'x86_unknown-linux-musl'; did you mean 'i586-unknown-linux-musl'?

**Possible Solution(s)**

**Notes**

Output of `rustup --version`: rustup 1.22.1 (b01adbbc3 2020-07-08)

Output of `rustup show`: Default host: x86_64-unknown-linux-gnu
rustup home:  /home/jonee/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.47.0 (18bf6b4f0 2020-10-07)

**Comment by ehuss** [comment]
It looks like you have a typo, though it's not clear which target you actually want to install.  For the 64-bit target, it is `x86_64-unknown-linux-musl`, for 32-bit it is `i686-unknown-linux-musl`.  The list of available target names is published at https://doc.rust-lang.org/nightly/rustc/platform-support.html.

**Comment by jonee** [comment]
Thank you! You are right! I copied it over somewhere and would let the page owner know they have the typo. 

rustup target add x86_64-unknown-linux-musl
info: downloading component 'rust-std' for 'x86_64-unknown-linux-musl'
info: installing component 'rust-std' for 'x86_64-unknown-linux-musl'
info: Defaulting to 500.0 MiB unpack ram
 20.3 MiB /  20.3 MiB (100 %)  12.2 MiB/s in  1s ETA:  0s
