### ISSUE TITLE
"error: " is printed twice

### ISSUE THREAD

**Issue by camelid** [rust-lang/rustup#2541]
**Problem**
"error: " is printed twice:

```console
$ rustup toolchain list --installed
error: error: Found argument '--installed' which wasn't expected, or isn't valid in this context

USAGE:
    rustup toolchain list [FLAGS]

For more information try --help
```

**Steps**

1. Run `rustup toolchain list --installed`. Or just run it with any flag that doesn't make sense: `rustup --blah`

**Possible Solution(s)**

**Notes**

Output of `rustup --version`: `rustup 1.22.1 (b01adbbc3 2020-07-08)`

**Comment by camelid** [comment]
~~I think I have a fix.~~ Hmm, or not...

**Comment by kinnison** [comment]
I believe this is a dup of #2492 which was fixed in #2496.

**Comment by camelid** [comment]
Indeed, this is fixed on master.

**Comment by kinnison** [comment]
Rustup 1.23.0 is now out.
