### ISSUE TITLE
Trying to install 1.8.0 on freebsd succeeds without actually installing the toolchain

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustup#2547]
**Steps**

1. Beg, borrow, or steal a FreeBSD machine
2. Install rustup.
3. `rustup install 1.8.0`

```
info: sync channel updates ...
info: latest update on 2016-04-12, rust version 1.8.0 ...

  1.8.0-x86_64-unknown-freedbsd unchanged - (toolchain not installed)
```

**Possible Solution(s)**

Rustup should either install the toolchain or give an error that it's not available.

**Notes**

Output of `rustup --version`: 1.22.1
Output of `rustup show`: omitted because I can't get copy/paste to work in my VM.

**Comment by kinnison** [comment]
So freebsd is present in the channel though the rustc and cargo components are not available for that target in there.  What's odd is that *ought* to fail to install

**Comment by kinnison** [comment]
I can confirm this is replicatable on Linux:

```
dsilvers@listless:~/dev-git/rustup$ rustup install 1.8.0-x86_64-unknown-freebsd
warning: toolchain '1.8.0-x86_64-unknown-freebsd' may not be able to run on this system.
warning: If you meant to build software to target that platform, perhaps try `rustup target add x86_64-unknown-freebsd` instead?
info: syncing channel updates for '1.8.0-x86_64-unknown-freebsd'
info: latest update on 2016-04-12, rust version 1.8.0 (db2939409 2016-04-11)

  1.8.0-x86_64-unknown-freebsd unchanged - (toolchain not installed)

info: checking for self-updates
dsilvers@listless:~/dev-git/rustup$
```

I'll look into it

**Comment by kinnison** [comment]
Actually this appears to just be a case of crappy error message.  It didn't create a toolchain entry with no components, it just failed to install the toolchain and then exited zero which is somewhat confusing for scripts
