### ISSUE TITLE
Using clippy from a rustup linked toolchain doesn't work.

### ISSUE THREAD

**Issue by vext01** [rust-lang/rustup#2548]
Originally discussed [here](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Using.20clippy.20in.20rustup.20linked.20toolchain.3F).

Running `cargo clippy` when the project's toolchain has been overridden to a linked rustup toolchain doesn't work.

```
$ cargo clippy
error: 'cargo-clippy' is not installed for the toolchain 'yk-stage1'
To install, run `rustup component add clippy --toolchain yk-stage1`
$ rustup toolchain list -v
nightly-x86_64-unknown-linux-gnu (default)      /home/vext01/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu                                              
yk-stage1 (override)    /home/vext01/research/yorick/ykrustc/build/x86_64-unknown-linux-gnu/stage1                                                            
```

But running the tool manually with a library path set **does** work:
```
LD_LIBRARY_PATH=/home/vext01/research/yorick/ykrustc/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib \
    /home/vext01/research/yorick/ykrustc/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/cargo-clippy
```

**Comment by jyn514** [comment]
@vext01 I would expect this to be an x.py bug and not a rustup bug. Notice how the path with clippy is in `stage1-tools`, not `stage1`.

**Comment by jyn514** [comment]
See also https://github.com/rust-lang/rust/issues/78717 and https://github.com/rust-lang/rust/issues/76666.

**Comment by vext01** [comment]
I see. So shall we close this?

**Comment by vext01** [comment]
But wait.

To be clear, the error comes from running `cargo clippy` in a normal rust project (not the compiler) where the toolchain has been overridden. I don't think x.py is involved, is it?

**Comment by jyn514** [comment]
x.py needs to build clippy and put it in `stage1/bin` before rustup can use it. stage1-tools does not have a full toolchain.

**Comment by vext01** [comment]
Ah yes, gotcha. It's building *a* clippy, but I guess it aint in the right place :)

**Comment by kinnison** [comment]
I don't think this is an issue for rustup, so I'll close it.  If I've misunderstood, please ping me and I'll reopen it.
