### ISSUE TITLE
aarch64 macOS

### ISSUE THREAD

**Issue by chadbrewbaker** [rust-lang/rustup#2557]
```bash
curl https://sh.rustup.rs -sSf | sh
rustup: unknown CPU type: arm64
```

**Comment by est31** [comment]
There is support for it on master but no official release yet: #2521

CI uploads it to s3 per default but no idea how to access that.

**Comment by est31** [comment]
See also: #2413 

Also apparently they want to make a release soon: #2556

**Comment by chadbrewbaker** [comment]
I'll noodle on a PR to at least get passed that initial error.

**Comment by kinnison** [comment]
Is there a reason you think #2525 is insufficient for that?

**Comment by chadbrewbaker** [comment]
Ohh shiny. I'll run it and see.

**Comment by kinnison** [comment]
Rustup 1.23.0 is now out.
