### ISSUE TITLE
libgit2 1.0 is not provided by Arch

### ISSUE THREAD

**Issue by gtsiam** [rust-lang/rustup#2558]
**Problem**
Running any of the cargo binaries linking to `libgit2` fails with a link error. For example:
```
$ cargo add
/home/gtsiam/.cargo/bin/cargo-add: error while loading shared libraries: libgit2.so.1.0: cannot open shared object file: No such file or directory
```

**Steps**
1. Install rust through `rustup`
2. Run `cargo add`

**Possible Solution(s)**
Including a copy of `libgit2.so.1.0` with cargo (maybe statically linked?). I could grab a copy from the internet or compile it myself, but hey; what is rustup for. Alternatively update the cargo binaries, but I'm not sure how that would fare with other platforms.

**Notes**
I'm running a fully upgraded version of Arch. `libgit2` _is_ installed, but the version from pacman is incompatible (1.1 is provided, but 1.0 is required):
```
$ ldconfig -pv 2>/dev/null | grep libgit2.so
	libgit2.so.1.1 (libc6,x86-64) => /usr/lib/libgit2.so.1.1
	libgit2.so (libc6,x86-64) => /usr/lib/libgit2.so
```

Output of `rustup --version`:
```
rustup 1.22.1 (b01adbbc3 2020-07-08)
```

Output of `rustup show`:

```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/gtsiam/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

armv7-unknown-linux-gnueabihf
wasm32-wasi
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.47.0 (18bf6b4f0 2020-10-07)
```

**Comment by kinnison** [comment]
`cargo-add` is not one of the proxies provided by `rustup` which suggests you have previously built and installed `cargo-add` yourself and probably before arch upgraded from 1.0 to 1.1 of `libgit2`.  Simply run `cargo install --force cargo-add` to rebuild it.

If that turns out to not be the case, please respond here and I'll try and help further.

**Comment by gtsiam** [comment]
Oh, good to know. The force install fixed the errors.

Maybe this should be addressed by cargo? -- I'll look into it later some more.

In any case, thanks for the help.
