### ISSUE TITLE
Doesn't work on Artix Linux

### ISSUE THREAD

**Issue by ergpopler** [rust-lang/rustup#2559]
I did the command from rustup.rs.  It installs without error but it doesn't add cargo, or anything to do with Rust to the PATH.

Artix Linux using the Runit init system,
using ZSH.

Rustup edits the .profile and .zprofile files, but it should edit(or create if necessary) the .zshenv file according to [this](http://zsh.sourceforge.net/Intro/intro_3.html), which i can confirm DOES work.

**Comment by rbtcollins** [comment]
Once you start a new login session it should be in your PATH then. We have recently changed code in this area, but I can't remember if we did a release or not.

**Comment by kinnison** [comment]
I think the fixes for zsh will be in 1.23

**Comment by ergpopler** [comment]
> Once you start a new login session it should be in your PATH then. We have recently changed code in this area, but I can't remember if we did a release or not.

I relogged several times and it didn't work, i've logged out without restarting, and again no luck, it may be due to my login manager, that is why it should be added the the zshenv file and not the zprofile,

**Comment by kinnison** [comment]
Yeah, as I stated, I think the fixes will be in 1.23 which depending on when t-release have time, will hopefully be soon.

**Comment by ergpopler** [comment]
> Yeah, as I stated, I think the fixes will be in 1.23 which depending on when t-release have time, will hopefully be soon.

:)

**Comment by kinnison** [comment]
Rustup 1.23.0 is now out.
