### ISSUE TITLE
default host triple: x86_64-pc-windows-msvc

### ISSUE THREAD

**Issue by 89z** [rust-lang/rustup#2568]
If I download this:

https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe

I first get this scary screen:

~~~
Rust Visual C++ prerequisites

Rust requires the Microsoft C++ build tools for Visual Studio 2013 or
later, but they don't seem to be installed.

The easiest way to acquire the build tools is by installing Microsoft
Visual C++ Build Tools 2019 which provides just the Visual C++ build
tools:

  https://visualstudio.microsoft.com/visual-cpp-build-tools/

Please ensure the Windows 10 SDK and the English language pack components
are included when installing the Visual C++ Build Tools.

Alternately, you can install Visual Studio 2019, Visual Studio 2017,
Visual Studio 2015, or Visual Studio 2013 and during install select
the "C++ tools":

  https://visualstudio.microsoft.com/downloads/

Install the C++ build tools before proceeding.

If you will be targeting the GNU ABI or otherwise know what you are
doing then it is fine to continue installation without the build
tools, but otherwise, install the C++ build tools before proceeding.
~~~

This is confusing/upsetting, as I specifically downloaded the GNU version so
that **I dont** have to deal with anything regarding Visual Studio. So then I
continue and I get this:

~~~
Current installation options:

default host triple: x86_64-pc-windows-msvc
~~~

At this point I am scratching my head, as I am now confused what file I even
downloaded. Again, I downloaded this:

https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe

So if I have specifically chosen the GNU download, why is Rust trying to set my
environment as MSVC?

**Comment by kinnison** [comment]
Hi,

I appreciate this confusion however it's important to remember that the `-gnu` **build** of `rustup` is simply that - how we built `rustup` itself.  Rustup is designed to select the toolchain most likely to be appropriate for the **host** and the MSVC host toolchain is the better supported of the two and so it defaults to that.

We did discuss making the `-gnu` built `rustup-init` default to the `-gnu` toolchains but it was decided that this would potentially introduce confusion from those who were relying on it defaulting to the `-msvc` toolchains (i.e. it would be a backward-incompatible change) and we didn't want to introduce that confusion into the ecosystem.

We also considered stopping providing the `-gnu` built `rustup-init` at all, but also decided that to stop that might also be backward-incompatible at a time which it wasn't necessary to be.

Again, sorry for the confusion, but you simply need to switch the default toolchain to the `-gnu` one when prompted and all will be well.

**Comment by atrigent** [comment]
Hi @kinnison, can you explain what backward-compatibility issue there would be from not providing four different identically-functioning versions of the installer for the installer?

**Comment by 89z** [comment]
Because of this and other issues with RustUp, as a workaround I build my own Rust installer:

https://github.com/89z/sienna/tree/master/rust-installer

been using it a couple of months and works fine

**Comment by kinnison** [comment]
@atrigent People who download the specific variant they want for their host would be surprised if that variant vanished.  People who rely on the defaults for installation would be surprised if those changed.  This is why to either reduce to a single Windows installer, or to make each installer behave differently by default, would be a breaking change.

**Comment by 89z** [comment]
Closing this because I dont care anymore, and I have my own installer:

https://github.com/89z/sienna/tree/master/cmd/install-rust

**Comment by atrigent** [comment]
Sorry for commenting after this has been closed, but I do have additional questions.

@kinnison Ok, so I get that WOW64 can in some cases be disabled/uninstalled/unavailable, so I guess there's a very narrow need for the 64bit version of the installer. I think it should be made very clear that the two versions are functionally identical and that the 64bit version is only required in this very narrow case. Otherwise people will assume that it's an installer for the 64bit version, rather than a 64bit version of the installer.

But I do not see any conceivable reason for the different gnu and msvc versions of the installer to exist. Am I correct in assuming that there is no programmatic interface to the installer executable? If so, what observable difference can there possibly be between these different versions? Under what circumstances can the extra versions not be replaced by a redirect/symlink/etc?

**Comment by kinnison** [comment]
I am not entirely sure @atrigent whether or not replacing them all with one version and redirects/symlinks would be a reasonable approach. As a non-Windows user I'd expect there to be runtime differences in dependencies or similar which might need consideration, but I'm not an expert on that sort of stuff.  Certainly if we only had to build a single version that might be nicer to deal with long-term.  Are there differences in file access, or rules around networking which might apply if we were to only produce a 32bit version of Rustup?  Are there runtime dependency differences between the -gnu and -msvc variants which I'm unaware of and which might have similar considerations to be made?

@rbtcollins is likely to be the best person within the team to answer that, but I think he's busy this week so it may be a while before he can weigh in.

**Comment by rbtcollins** [comment]
They are both hermetic executables that only depend on system dlls, so we should be fine to ship either under any name we like. 

That said I'm pretty sure were going to eventually delete the gnu build - theres another bug talking about the longer term migration path and cleanup of this situation.
