### ISSUE TITLE
RustUp deleting Tar files after install

### ISSUE THREAD

**Issue by a8nJ** [rust-lang/rustup#2569]
I ran RustUp with `-v` to see what was going on, and I find this:

~~~
info: downloading component 'cargo'
verbose: creating Download Directory directory: 'C:\Users\Steven\.rustup\downloads'
verbose: downloading file from: 'https://static.rust-lang.org/dist/2020-11-19/cargo-1.48.0-x86_64-pc-windows-gnu.tar.xz'
verbose: downloading with reqwest
verbose: checksum passed
info: downloading component 'rust-mingw'
verbose: downloading file from: 'https://static.rust-lang.org/dist/2020-11-19/rust-mingw-1.48.0-x86_64-pc-windows-gnu.tar.xz'
verbose: downloading with reqwest
verbose: checksum passed
info: downloading component 'rust-std'
verbose: downloading file from: 'https://static.rust-lang.org/dist/2020-11-19/rust-std-1.48.0-x86_64-pc-windows-gnu.tar.xz'
verbose: downloading with reqwest
 20.3 MiB /  20.3 MiB (100 %)   8.5 MiB/s in  3s ETA:  0s
verbose: checksum passed
info: downloading component 'rustc'
verbose: downloading file from: 'https://static.rust-lang.org/dist/2020-11-19/rustc-1.48.0-x86_64-pc-windows-gnu.tar.xz'
verbose: downloading with reqwest
 67.0 MiB /  67.0 MiB (100 %)   8.1 MiB/s in  9s ETA:  0s
~~~

I was curious, so after everything done, I went to
`C:\Users\Steven\.rustup\downloads`, and the folder is empty. All told, those
files are 97 MB. So why is RustUp just deleting the files after finish? Wouldnt
it be better to keep the files, in case user want to reinstall?

**Comment by kinnison** [comment]
It's extremely rare that users will be downloading a toolchain only to delete it and redownload it.  As such, keeping those tarfiles around would be a waste of disk space.

**Comment by a8nJ** [comment]
Rust keeps files for every single package Ive ever used with Cargo, how is this different?

**Comment by kinnison** [comment]
> Rust keeps files for every single package Ive ever used with Cargo, how is this different?

In this instance, `rustup` has installed the toolchain and so reuse of those downloaded artifacts is incredibly unlikely.  When cargo caches a crate it's much more likely that cached crate will be reused.  Recompiling something (or compiling a new program) is much more likely than removing and reinstalling the same toolchain is.

**Comment by a8nJ** [comment]
As a workaround, I made my own Rust installer:

https://github.com/a8nJ/cove/tree/master/pac-rust

It gets the latest `cargo`, `rust-std` and `rustc` packages, downloads them to
the user cache directory, and extracts. It keeps the archives in case they are
needed.
