### ISSUE TITLE
Include rustup self-update status in `rustup check`

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rustup#2577]
**Describe the problem you are trying to solve**
When checking whether toolchain updates are available it would be useful to see that there is also a rustup update available.

**Describe the solution you'd like**
Include rustup's own version status in the output of `rustup check`

**Notes**

**Comment by kinnison** [comment]
To achieve this will require factoring the "checking for self-updates" part of the self_update process out into a separate function which can be called from the `rustup check` implementation.  It shouldn't be that complex to do and I'd be happy to mentor someone through the process.

**Comment by 0xPoe** [comment]
Can I work on this?

**Comment by kinnison** [comment]
Sure, we'd be grateful for the help.  If you want to discuss this, then please find me on our discord channel, or you can ask here if you want.
