### ISSUE TITLE
rustup is not creating $HOME/.cargo/env

### ISSUE THREAD

**Issue by frgomes** [rust-lang/rustup#2578]
I don't want `$HOME/.cargo/env` being sourced in my `$HOME/.profile` or my `$HOME/.bashrc`.
Still, it is convenient to have `$HOME/.cargo/env` generated since I will source this file anyway under certain circumstances.

However, `$HOME/.cargo/env` is not created when I perform the installation as shown below

```bash
$ curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path -y
```

Bug or feature?

Thanks a lot,

**Comment by kinnison** [comment]
Further to discussion on Discord, we think this might be failing to create the env file if it detects the presence of the sourcing lines in the RC files.  @workingjubilee ?

**Comment by frgomes** [comment]
Indeed. I confirm that if the sourcing instructions are already present on the RC files, the command below does not create the env file:

```bash
$ curl https://sh.rustup.rs -sSf | sh -s -- -y
```

**Comment by workingjubilee** [comment]
That is probably what is happening! I did not anticipate this use case. I will submit a patch.

@frgomes I don't **need** to know, but I would be most interested to hear what the "certain circumstances" are, to better understand this sort of desire in general in the future.

**Comment by frgomes** [comment]
(copying from Discord)

I employ multiple virtual environments for multiple distinct activities. 
https://www.pythonforbeginners.com/basics/how-to-use-python-virtualenv
The link above looks more complicated than it really is: in the end it is just something like "source a shell script containing definitions for environment variables and modifications to PATH only when I need those definitions and modifications", which avoids having a PATH containing 50 entries when I need only 4 or 5 when developing on a certain version of a certain programming language. In the case of Rust, I will be sourcing $HOME/.cargo/env only when I need Rust visible as a development tool. Nothing special, really.

**Comment by marmeladema** [comment]
I fully second this! In my case the issue I have is that in some continuous integration system, the `.bashrc` file is not writable by rustup because of some permission reasons so I need to rely on `--no-modify-path` but at the same time I want to manually call `source $HOME/.cargo/env` later on.

**Comment by marmeladema** [comment]
On a side note, when rustup is not creating the `$HOME/.cargo/env` file, it still shows the following message:
```
    To configure your current shell, run:
    source $HOME/.cargo/env
```
which is kind of confusing since the file does not exist.

**Comment by ndmitchell** [comment]
This broke my CI in exactly the same way as it did for @marmeladema. Is there a plan to roll out a fix quickly? If not, I'll adjust my CI to add the PATH by hand.

**Comment by kinnison** [comment]
I think I agree that it's a bug we're not writing the env file out on `--no-modify-path` - I'm working on a test (and from there a fix) right now.

**Comment by detly** [comment]
I got bitten by this too. Is there a way to work around this, perhaps by forcing the script at `https://sh.rustup.rs/` to download an older version?

**Comment by frgomes** [comment]
@detly :: The issue was already fixed but it was not released yet.

Meanwhile, you can simply reinstall Rust and copy the env file somewhere else so that you can source it yourself.
However, when you try to reinstall Rust, you may eventually find a problem: the env file may not be created.

This happens because rustup detects that your $HOME/.profile and $HOME/.bashrc have already been changed.
Simply edit your $HOME/.profile and $HOME/.bashrc and remove the line in the end which sources your env file at $HOME/.cargo/env.

Then run rustup once again like shown below and it should create $HOME/.cargo/env.

```bash
$ curl https://sh.rustup.rs -sSf | sh -s -- -y
```

Note: I have [a shell script which installs Rust and several cargo plugins](https://github.com/frgomes/bash-scripts/blob/feature/0057-overhaul_turn_functions_onto_shell_scripts/bin/install_rust) which circumvents this trouble.
I simply create $HOME/.cargo/env by hand via this bash function:

```bash
function __install_rust_rustup_issue_2578 {
cat << EOF > "$HOME"/.cargo/env
#!/bin/sh
# rustup shell setup
# affix colons on either side of \$PATH to simplify matching
case ":\${PATH}:" in
    *:"\$HOME/.cargo/bin":*)
        ;;
    *)
        # Prepending path in case a system-installed rustc must be overwritten
        export PATH="\$HOME/.cargo/bin:\$PATH"
        ;;
esac
EOF
}
```

**Comment by detly** [comment]
@frgomes Unfortunately I'm using rustup as part of a hosted, cross-compiling build system. It's not a manual process, so I can't apply your advice (thanks anyway though). For now I can just populate the file as part of the build process and remove that when the fix is released.

**Comment by kinnison** [comment]
The fix should now be live (1.23.1), please let me know if it's not working for you.

**Comment by marmeladema** [comment]
Thank you very much @kinnison. I can confirm it works at least for my use-case!

**Comment by kinnison** [comment]
@marmeladema You're very welcome.

**Comment by andy-preston** [comment]
As a work around, can I suggest containerisation?
I put my development environments into Docker containers to help eliminate this kind of invasive behaviour.
Nothing more annoying than tools that think they own your computer.
