### ISSUE TITLE
illumos rustup-init binary seems to be missing from the main server

### ISSUE THREAD

**Issue by jclulow** [rust-lang/rustup#2580]
I believe the latest `rustup` version should support illumos systems, as my patch for that was integrated into the main branch a little while ago now.  Unfortunately it doesn't seem like the `rustup-init` binary has made it to the right place:

```
$ uname -so
SunOS illumos

$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash
info: downloading installer
curl: (22) The requested URL returned error: 404
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/x86_64-unknown-illumos/rustup-init /tmp/tmp.8JaGWv/rustup-init x86_64-unknown-illumos
```

It seems like I must have missed something in my change for that.  Is there some way we can get the binary built?  Is there a build error log I should be looking at?

Cheers.

**Comment by kinnison** [comment]
Irritatingly it looks like Illumos being built on `stable` was missed from this release (the workflow files missed it somehow).

I've ensured that won't happen in the future, and I'll see if there's a way we can get a build uploaded for 1.23.0.

**Comment by kinnison** [comment]
@pietroalbini If I push the updated workflow file to the `stable` branch so that it builds the illumos binary, can we get that pushed onto static.rlo?

**Comment by kinnison** [comment]
I'm looking at a potential need for a 1.23.1 to deal with a snafu in the macos builds which nobody spotted in the testing week, so I'll target this to there.

**Comment by jclulow** [comment]
Thanks for looking into it!

**Comment by kinnison** [comment]
This should now be live.
