### ISSUE TITLE
Update the platform support URL

### ISSUE THREAD

**Issue by emilyalbini** [rust-lang/rustup#2588]
[Rustup currently links to the platform support page when it can't install a target](https://github.com/rust-lang/rustup/blob/cc9ce760ec38880e495237d2d96b3fe3dde146d8/src/dist/manifest.rs#L382), but the URL moved.

The platform support page is now included in the "rustc book", which is shipped on doc.rust-lang.org riding the trains. It'd be nice to detect which channel the user is trying to install, and show the link to the proper URL:

```
https://doc.rust-lang.org/{channel}/rustc/platform-support.html
```

For >= 1.47.0 we can also directly use the version number instead of "stable" as the channel.

**Comment by kinnison** [comment]
We reference the forge in a number of places in the docs, and also from an error message generated deep inside our toml handling for channel manifests.  It's not clear how easy it'll be to fix it to include the requisite channel identifier, instead we may simply have to always reference `nightly` ?

**Comment by emilyalbini** [comment]
Always referencing nightly is fine. It would've been nicer to reference the proper one, but if that's too complex then it's definitely not worth it.

**Comment by kinnison** [comment]
I think to begin with always referencing nightly would be best.
