### ISSUE TITLE
Arm macbook installation ERROR

### ISSUE THREAD

**Issue by Yuzuki-N** [rust-lang/rustup#2600]
I am going to install rust on my m1 macbook air
but when i do this
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
this will be some error like this
```
target 'aarch64-apple-darwin' not found in channel.  Perhaps check https://forge.rust-lang.org/release/platform-support.html for available targets
```
i want to know how to correctly install rust-lang correctly

**Comment by kinnison** [comment]
This is not a bug in rustup, but rather that the aarch64 release of the toolchain has not yet reached stable.  Either wait until after the next release of rust which should include the aarch64 toolchain on stable, or else install the beta or nightly channel for now.

You can select the channel at the prompt during installation.
