### ISSUE TITLE
Installer detection of TLS 1.2 support fails for curl 7.73.0+

### ISSUE THREAD

**Issue by apnorton** [rust-lang/rustup#2603]
**Problem**
When installing rustup from the downloaded shell script with curl 7.73.0 on the system, the installer fails back to not enforcing TLSv1.2.  

**Example** (note: `./rustup-install.sh` is just the result of `curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -o rustup-install.sh` because I don't like piping to bash):
```
$ curl --version
curl 7.73.0 (x86_64-pc-linux-gnu) libcurl/7.73.0 OpenSSL/1.1.1h zlib/1.2.11 zstd/1.4.5 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-10-14
Protocols: dict file ftp ftps gopher http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
[apnorton@tao rust-book]$ ./rustup-install.sh 
info: downloading installer
Warning: Not enforcing strong cipher suites for TLS, this is potentially less secure
Warning: Not enforcing TLS v1.2, this is potentially less secure

Welcome to Rust!
<snip>
```

**Steps**
1. Install current version of curl
2. Attempt to install rustup with the current install script
3. Notice the warning

**Possible Solution(s)**
The problem is caused by this change to the `curl` help menu: https://github.com/curl/curl/pull/5680

Essentially, instead of `--tlsv1.2` being shown in the main curl help, it's now under `curl --help tls`; the same is true for other options.  This causes the check on line 547 here to fail:
```
545     if [ "$_backend_supported" = "yes" ]; then
546         # "unspecified" is for arch, allows for possibility old OS using macports, homebrew, etc.
547         if check_help_for "notspecified" "curl" "--tlsv1.2" "--ciphers" "--proto"; then
548             _args_supported="yes"
549         fi
550     fi
```

Instead of grepping through `curl --help`; now the script needs to grep through `curl --help all` (or possibly some subselection of categories). 

**Notes**

Output of `rustup --version`: n/a, as it's not installed yet.
Output of `rustup show`: n/a, as it's not installed yet.

**Comment by kawpii** [comment]
@kinnison @apnorton I am still seeing this problem, can you please reopen this?

```
❯ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer
Warning: Not enforcing strong cipher suites for TLS, this is potentially less secure
Warning: Not enforcing TLS v1.2, this is potentially less secure
```

```
❯ curl -V
curl 7.76.0
```

**Comment by kinnison** [comment]
@kaushalyap We've not released this fix yet, I am working through the last bits of work before I can.
