### ISSUE TITLE
CI fails on powerpc64-unknown-linux-gnu

### ISSUE THREAD

**Issue by est31** [rust-lang/rustup#2608]
Since merging of #2517, the master branch CI fails on powerpc64-unknown-linux-gnu. [Link to a failing build](https://github.com/rust-lang/rustup/runs/1542098778). Relevant excerpt from the log:

```
error: failed to run custom build command for `ring v0.16.17`

Caused by:
  process didn't exit successfully: `/checkout/target/release/build/ring-69b64e93d224eaca/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.17/build.rs:375:10
```

The failing line is [here](https://github.com/briansmith/ring/blob/f247250ee0b96770ac34e2c1fbf23e3f3efb0d84/build.rs#L375). It turns out that ring doesn't support the powerpc platform: https://github.com/briansmith/ring/issues/389

I think the best resolution would be to disable the builtin rustls support on the powerpc platform.

cc @kinnison

**Comment by kinnison** [comment]
Hmm, that's not ideal no.  Please do sort a PR for that if you can.

**Comment by est31** [comment]
> Please do sort a PR for that if you can.

@kinnison → #2609
