### ISSUE TITLE
Rust not installing

### ISSUE THREAD

**Issue by chriskout** [rust-lang/rustup#2618]
**Problem**
I am trying to install rust on a Linux environment (Kali 2020.4). When I run the install command an error appears. Weirdly enough I do get the rustup, cargo, and rustc bins but using the latter two commands does not work.

**Steps**
1. Run the Installer: ```curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh``` 
2. Get the error message: 
---
    info: downloading installer
    
    Welcome to Rust!
    
    This will download and install the official compiler for the Rust
    programming language, and its package manager, Cargo.
    
    Rustup metadata and toolchains will be installed into the Rustup
    home directory, located at:
    
      /home/kali/.rustup
    
    This can be modified with the RUSTUP_HOME environment variable.
    
    The Cargo home directory located at:
    
      /home/kali/.cargo
    
    This can be modified with the CARGO_HOME environment variable.
    
    The cargo, rustc, rustup and other commands will be added to
    Cargo's bin directory, located at:
    
      /home/kali/.cargo/bin
    
    This path will then be added to your PATH environment variable by
    modifying the profile files located at:
    
      /home/kali/.profile
      /home/kali/.bashrc
      /home/kali/.zshenv
    
    You can uninstall at any time with rustup self uninstall and
    these changes will be reverted.
    
    Current installation options:

       default host triple: x86_64-unknown-linux-gnu
         default toolchain: stable (default)
                   profile: default
      modify PATH variable: yes
    
    1) Proceed with installation (default)
    2) Customize installation
    3) Cancel installation
    >1
    
    info: profile set to 'default'
    info: default host triple is x86_64-unknown-linux-gnu
    info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
    info: latest update on 2020-11-19, rust version 1.48.0 (7eac88abb 2020-11-16)
    info: downloading component 'cargo'
    info: downloading component 'clippy'
    info: downloading component 'rust-docs'
     13.3 MiB /  13.3 MiB (100 %)   7.1 MiB/s in  1s ETA:  0s
    info: downloading component 'rust-std'
     22.0 MiB /  22.0 MiB (100 %)   7.3 MiB/s in  3s ETA:  0s
    error: component download failed for rust-std-x86_64-unknown-linux-gnu
    error: caused by: checksum failed
3. Run ```rustc --version``` and get error message: ```error: no override and no default toolchain set```. Running ```cargo --version``` gives the same issue. Rustup works fine. 

**Possible Solution(s)**
I have tried installing rust on three platforms. WSL2, Ubuntu, and Kali. Only WSL2 has worked without any problems. Kali and Ubuntu have had the same exact problems as described above. Could it be related to me using Virtual Box to run those two Linux Ditros? 

**Notes**

Output of `rustup --version`:  rustup 1.23.1 (3df2264a9 2020-11-30)

**Comment by chriskout** [comment]
Before anyone says to just use rustup to install a toolchain:

`rustup install nightly`:
---
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2020-12-23, rust version 1.50.0-nightly (bb1fbbf84 2020-12-22)
info: downloading component 'cargo'
info: downloading component 'clippy'
error: component download failed for clippy-x86_64-unknown-linux-gnu
error: caused by: checksum failed

**Comment by castlecardano** [comment]
I have the same issue

**Comment by kinnison** [comment]
@chriskout I apologise, this bug seems to have slipped under my radar and I've only just noticed it on an issue-sweep.

Are you still struggling, or have you found your answer?  the above looks remarkably like a broken web proxy or else perhaps running out of disk space awkwardly?

**Comment by rami3l** [comment]
As there are currently no further actions that can be taken from our side with respect to this issue, I'm closing it now as stale.

Please feel free to reopen if you have more information to provide.
