### ISSUE TITLE
Provide help if user attempts to install `1.0` through `1.8` since those need `1.0.0` through `1.8.0`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustup#2621]
**Problem**

`rustup install 1.0` should install 1.0.0, the same way that `rustup install 1.48` installs 1.48.0. Instead it gives an error.

**Steps**

1. `rustup install 1.0`

```
error: could not download nonexistent rust version `1.0-x86_64-unknown-linux-gnu`
error: caused by: could not download file from 'https://static.rust-lang.org/dist/rust-1.0-x86_64-unknown-linux-gnu.tar.gz.sha256' to '/home/joshua/.local/lib/rustup/tmp/6491fh929v2mgx7y_file'
error: caused by: http request returned an unsuccessful status code: 404
```

This looks like a problem on T-infra's side? But I'm not sure what's going wrong, so I'm dumping it on you instead :P

**Notes**

Output of `rustup --version`: rustup 1.23.1 (3df2264a9 2020-11-30)

**Comment by kinnison** [comment]
This is not rustup's fault.  We've not generated 1.x manifest links for toolchains before manifest version 2 came out.  If we were to do this, it would require retrogenerating v2 manifests for the older toolchains which while possible (and possibly desirable) would be rewriting history to some extent.

Either way this isn't rustup's problem.  I'll leave this open for now until someone involved in the 1.x manifest work can weigh in though.  Perhaps @pietroalbini or @carols10cents ?

**Comment by emilyalbini** [comment]
How hard would it be to just hardcode that there were no point releases for manifest v1 releases?

**Comment by kinnison** [comment]
rustup doesn't know for sure which releases are v1 or v2, it just tries v2 and falls back to v1 if it can't find it.  I suppose it could then try falling back to a v1 without the point release, but that starts to feel icky IMO.

**Comment by jyn514** [comment]
> I suppose it could then try falling back to a v1 without the point release, but that starts to feel icky IMO.

Would it make sense to do this, but only as a warning? "help: did you mean `rustup toolchain install 1.0.0`"?

**Comment by kinnison** [comment]
I think that would be acceptable.  Yes.  I'll retitle the issue.

if someone wishes to tackle this, it should be fairly easy to complete.

**Comment by carols10cents** [comment]
Hm, I think if I typed `rustup toolchain install 1.0` after being used to typing `rustup toolchain install 1.50` and rustup said `help: did you mean rustup toolchain install 1.0.0` I would be sad and angry.
