### ISSUE TITLE
Missing std lib HTML docs - architecture stable-aarch64-unknown-linux-gnu

### ISSUE THREAD

**Issue by emccreigh** [rust-lang/rustup#2624]
**Problem**
Exactly as reported in issue 2494, but for a different architecture.  On a Raspberry Pi 4B running the new-ish 64-bit Raspberry Pi OS, the command

  rustup docs

yields 

  error: couldn't open browser
  error: caused by: command 'xdg-open (internal)' did not execute successfully; exit code: 2
  command stderr:
  xdg-open: file '/home/pi/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/share/doc/rust/html/index.html' does not exist

That computer is headless, so the lack of a browser is expected.  The directory /home/pi/.rustup/toolchains/stable-aarch64-unknown-linux/gnu/share/doc/rust does exist, but it has no html subdirectory.

**Steps**
1. Install rustup: curl https://sh.rustup.rs -sSf | sh
2. Start a new shell so ${PATH} includes ~/.cargo/bin
3. Execute the command: rustup docs

**Notes**
I also tried the same steps on a Raspberry Pi 4B running the older 32-bit Raspbian OS, resulting in the same failure.  That architecture is called stable-armv7-unknown-linux-gnueabihf.

Output of `rustup --version`: rustup 1.23.1 (3df2264a9 2020-11-30)
Output of `rustup show`:
  Default host: aarch64-unknown-linux-gnu
  rustup home:  /home/pi/.rustup

  stable-aarch64-unknown-linux-gnu (default)
  rustc 1.48.0 (7eac88abb 2020-11-16)

**Comment by kinnison** [comment]
Can you confirm that the documentation component is installed?  (`rustup component list | grep rust-docs`)  If it is installed and the documentation is not present then it's likely an infrastructure related problem.  If it is not installed, then please install the `rust-docs` component (`rustup component add rust-docs`) and try again.

**Comment by emccreigh** [comment]
The documentation component is apparently not installed.  But when I give the command

  rustup component add rust-docs

I get the reply

error: toolchain 'stable-aarch64-unknown-linux-gnu' does not contain component 'rust-docs' for target 'aarch64-unknown-linux-gnu'; did you mean 'rustc-docs'?

... and I get a similar reply with the 32-bit version of Raspbian as well.

**Comment by kinnison** [comment]
That suggests that the docs are not building for that target for some reason.  @pietroalbini Given aarch64 linux is supposed to be tier one is this something which needs raising further?

**Comment by emilyalbini** [comment]
Documentation for `aarch64-unknown-linux-gnu` will be available from Rust 1.49.0 onwards, which is scheduled to be released tomorrow! 32-bit documentation will not be available, as we only produce it for Tier 1 targets.

**Comment by kinnison** [comment]
Thank you Pietro.

I'm going to close this issue then.
