### ISSUE TITLE
Document autoinstallation behaviour on overrides page of docs

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rustup#2639]
In some cases it can confuse a small but not insignificant number of people that the override files can cause autoinstallation of toolchains, and in other cases people are not sure *what* command to use to trigger this activity best.

We should document the autoinstallation behaviour as part of https://rust-lang.github.io/rustup/overrides.html and we should make recommendations about the "best" way to trigger it, for example so that CI providers can implement it.

**Comment by 0xPoe** [comment]
I am working on this.
