### ISSUE TITLE
i686-pc-windows-gnu target cant find mingw?

### ISSUE THREAD

**Issue by imeredith** [rust-lang/rustup#2640]
**Describe the problem you are trying to solve**

I'm trying to build a 32bit program on windows using stable-gnu toolchain and i686-pc-windows-gnu as the target, and got `linker i686-w64-mingw32-gcc not found`. After some digging I only see mingw installed for the 64bit target.

**Describe the solution you'd like**

Either the i686-pc-windows-gnu target should bundle mingw or some documentation around installing (there may already be this that im missing).

**Notes**
I have a 32bit dll I have to link to, which forces the use of the i686 target, and I also need to use winapi, which is messing up some struct data when using msvc for i686.

I've only been using rust for 2 days so its very possible I'm totally misunderstanding things

Thanks!

**Comment by rbtcollins** [comment]
You should almost certainly use msvc i686 target then, as the gnu toolchain
is the non-standard one in the Windows ecosystem, not the MSVC toolchain.
Unless its a gnu built .dll of course.

rustup doesn't install the C linker and runtime though (at least currently)
- thats up to you; so if you install it, you should be fine.

**Comment by imeredith** [comment]
Hmm I see, I'll open an issue on winapi and maybe they can help out with why im getting issues when compiling i686 then
