### ISSUE TITLE
non-workspace dependency rust-toolchain files may be used in some cases, causing Cargo/rustc version mismatches

### ISSUE THREAD

**Issue by sunshowers** [rust-lang/rustup#2647]
**Problem**
It looks like rustup's toolchain wrappers may pick up rust-toolchain files published by third-party dependencies in some situations. Specifically, this may happen if rustup's Cargo wrapper is bypassed but the rustc wrapper is used.

I originally ran into this with `env_logger 0.8.2`, which publishes [a `rust-toolchain` file](https://docs.rs/crate/env_logger/0.8.2/source/rust-toolchain) in its `crates.io` release.

**Steps**

1. `rustup toolchain uninstall 1.41.0` (this ensures that we get the output around installing 1.41, as seen below)
1. `git clone https://github.com/sunshowers/env-logger-test` (this is [a repo](https://github.com/sunshowers/env-logger-test) I prepared to demonstrate the issue)
2. `cd env-logger-test`
3. `eval $(rustup which cargo) build`

This fails with:

```
   Compiling env_logger v0.8.2
info: syncing channel updates for '1.41.0-x86_64-unknown-linux-gnu'
info: latest update on 2020-01-30, rust version 1.41.0 (5e1a79984 2020-01-27)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: using up to 500.0 MiB of RAM to unpack components
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
error: unknown codegen option: `embed-bitcode`

error: could not compile `env_logger`

To learn more, run the command again with --verbose.
```

which indicates that the newer version of Cargo is passing in an old flag that isn't supported in 1.41.

(Note that doing a regular cargo build followed by the command above results in a no-op, which may indicate a separate caching issue with Cargo).

The repo has a `rust-toolchain` file checked into it for convenience, but whether it exists or not the same behavior occurs.

**Possible Solution(s)**

Ignore the rust-toolchain file for non-workspace dependencies somehow. Not exactly sure how though...

Separately, `env_logger` can probably exclude the `rust-toolchain` file from its releases, working around the issue. https://github.com/env-logger-rs/env_logger/issues/190#issuecomment-771314974

**Notes**

Output of `rustup --version`:

```
rustup 1.23.1 (2020-12-03)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.49.0 (e1884a8e3 2020-12-29)`
```

Output of `rustup show`:

```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/rain/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2020-10-09-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
1.41.0-x86_64-unknown-linux-gnu
1.45.2-x86_64-unknown-linux-gnu
1.46.0-x86_64-unknown-linux-gnu
1.47.0-x86_64-unknown-linux-gnu
1.48.0-x86_64-unknown-linux-gnu
1.49.0-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

aarch64-unknown-linux-gnu
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.49.0 (e1884a8e3 2020-12-29)
```

Reported to env_logger as well: https://github.com/env-logger-rs/env_logger/issues/190

**Comment by ehuss** [comment]
Can you explain why cargo is being run with `eval`?  That circumvents rustup's normal mechanism for "locking" the toolchain to whatever is defined in the workspace, which allows this to happen.

**Comment by sunshowers** [comment]
Heh, so we were doing it because we want to run a nightly version of Cargo (for the v2 resolver) against a stable rustc :) the versions of both are locked.

But in https://github.com/env-logger-rs/env_logger/issues/190 there are a number of other reports about an issue which seems to be similar (at least this is the most likely explanation).

**Comment by ehuss** [comment]
Ah. I think the only option is to set the `RUSTUP_TOOLCHAIN` environment variable before launching cargo. That is how the toolchain becomes "sticky" once it is chosen by one of the overrides.  Rustup doesn't know anything about dependencies or cargo, and if you circumvent the initial wrapper, there is no information for it to know how to handle that differently.

**Comment by sunshowers** [comment]
That makes sense.

Do you think there's any point in trying to prevent `rust-toolchain` files from being read in third-party dependencies at all? Or maybe prevent that file from being published on crates.io? Not sure what you think about strategies like that.

**Comment by rbtcollins** [comment]
I don't understand this third-party dependency use case being described - its mentioned in your report, but not covered by your reproduction instructions.

**Comment by sunshowers** [comment]
Ah, to be clear what I mean by "third-party dependency" is a non-workspace dependency, e.g. `env_logger` in https://github.com/sunshowers/env-logger-test/blob/main/Cargo.toml#L7-L8. If you follow my instructions you'll see that the `rust-toolchain` file in the `env_logger` crates.io release gets picked up.

**Comment by kinnison** [comment]
I think there might be value in suggesting crates.io should either refuse or at least warn for `rust-toolchain` being present in a crate tarball; but I don't think we should be trying to insert protection into `rustup` to prevent this particularly unusual corner case.

the `RUSTUP_TOOLCHAIN` environment variable should be sufficient to solve your problem, and if it remains confusing for you, you could always set the PATH appropriately to bypass `rustup` and directly utilise the toolchains during your build.

**Comment by kinnison** [comment]
I continue to believe this is "not rustup's duty" for now.  I'm going to close this issue.  If you feel you have a viable use-case which isn't resolved by one of the existing supported interfaces such as partial toolchains or the environment variable overrides, then please speak up.  Also perhaps consider suggesting cargo should remove `rust-toolchain{,.toml}` when it unpacks a crate?
