### ISSUE TITLE
CARGO_HOME ignored in creating (the contents and location of) ~/.cargo/env

### ISSUE THREAD

**Issue by OJFord** [rust-lang/rustup#2656]
**Problem**

Rustup creates `$HOME/.cargo/env`:
```
#!/bin/sh
# rustup shell setup
# affix colons on either side of $PATH to simplify matching
case ":${PATH}:" in
    *:"$HOME/.cargo/bin":*)
        ;;
    *)
        # Prepending path in case a system-installed rustc needs to be overridden
        export PATH="$HOME/.cargo/bin:$PATH"
        ;;
esac
```

regardless of the value of `$CARGO_HOME`

**Steps**

1. `export CARGO_HOME="$HOME/other"`
2. `rustup-init -y --no-modify-path --default-toolchain=stable --component clippy rls` (I doubt much of that's relevant, but it's what I did, maybe `--no-modify-path` causes it to hit a funny code path though that  is the cause of this)
3. Observe output:
```
To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH
environment variable.

To configure your current shell, run:
source $HOME/.cargo/env
```
(which is true, that is where it's put the file)

**Possible Solution(s)**

The file should be located inside `$CARGO_HOME`'s value at the time rustup was run, and in the script either use it's own location, or the value of `$CARGO_HOME` at the time the script is run.

**Notes**

Output of `rustup --version`: rustup 1.23.1 (2020-12-03)
Output of `rustup show`:
```
Default host: x86_64-apple-darwin
rustup home:  /Users/ojf/.config/cargo/rustup

stable-x86_64-apple-darwin (default)
rustc 1.49.0 (e1884a8e3 2020-12-29)
```

**Comment by rbtcollins** [comment]
I've just tried to reproduce this and failed:
```
robertc@lifelesswks:/tmp/t$ export CARGO_HOME=$(pwd)/c
robertc@lifelesswks:/tmp/t$ export RUSTUP_HOME=$(pwd)/r
robertc@lifelesswks:/tmp/t$ RUSTUP_FORCE_ARG0=rustup-init rustup -y --no-modify-path --default-toolchain=stable --component clippy rls
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2020-12-31, rust version 1.49.0 (e1884a8e3 2020-12-29)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rls'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
 22.3 MiB /  22.3 MiB (100 %)  12.8 MiB/s in  1s ETA:  0s
info: downloading component 'rustc'
 55.7 MiB /  55.7 MiB (100 %)  13.3 MiB/s in  4s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: using up to 500.0 MiB of RAM to unpack components
info: installing component 'clippy'
info: installing component 'rls'
info: installing component 'rust-docs'
 13.8 MiB /  13.8 MiB (100 %)  12.6 MiB/s in  1s ETA:  0s
info: installing component 'rust-std'
 22.3 MiB /  22.3 MiB (100 %)  14.9 MiB/s in  1s ETA:  0s
info: installing component 'rustc'
 55.7 MiB /  55.7 MiB (100 %)  15.8 MiB/s in  3s ETA:  0s
info: installing component 'rustfmt'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu installed - rustc 1.49.0 (e1884a8e3 2020-12-29)


Rust is installed now. Great!

To get started you need Cargo's bin directory (/tmp/t/c/bin) in your PATH
environment variable.

To configure your current shell, run:
source /tmp/t/c/env
```

**Comment by kinnison** [comment]
I can also confirm that things seem to work for me.  What platform are you running on?  E.g. is `rustup-init` provided by something which might be overriding your environment such as nix?

For reference, what I tried:

```
somniloquy% export CARGO_HOME="/tmp/ch"                                          
somniloquy% ./rustup-init --no-modify-path -y                                    
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.50.0 (cb75ad5db 2021-02-10)


Rust is installed now. Great!

To get started you need Cargo's bin directory (/tmp/ch/bin) in your PATH
environment variable.

To configure your current shell, run:
source /tmp/ch/env
somniloquy% cat /tmp/ch/env                                                      
#!/bin/sh
# rustup shell setup
# affix colons on either side of $PATH to simplify matching
case ":${PATH}:" in
    *:"/tmp/ch/bin":*)
        ;;
    *)
        # Prepending path in case a system-installed rustc needs to be overridden
        export PATH="/tmp/ch/bin:$PATH"
        ;;
esac
somniloquy%                                                                      
```

**Comment by allanlaal** [comment]
tried with current master tip with custom `RUSTUP_HOME` and `CARGO_HOME`:

	export RUSTUP_HOME="/opt/rustup"
	export CARGO_HOME="/opt/cargo/"

used those before installing. install went great. it appended this to my shell rc files:
`. "/opt/cargo/env"`

both `rustup` and `cargo` run, but:

	$ rustup toolchain list
	no installed toolchains
	$ rustup show home
	/home/allan/.rustup


looking at the `cargo/env` file:

	#!/bin/sh
	# rustup shell setup
	# affix colons on either side of $PATH to simplify matching
	case ":${PATH}:" in
		*:"/opt/cargo/bin":*)
		    ;;
		*)
		    # Prepending path in case a system-installed rustc needs to be overridden
		    export PATH="/opt/cargo/bin:$PATH"
		    ;;
	esac


why doesnt it declare my custom  `RUSTUP_HOME` and `CARGO_HOME`? Isn't this the place to do it?

when I append the same env vars to my `.bashrc` or more appropriately to `cargo/env` I get:

	$ rustup toolchain list
	stable-x86_64-unknown-linux-gnu (default)
	$ rustup show home
	/opt/rustup

and now when I run `cargo run`, it no longer creates `~/.cargo` nor `~/.rustup` directories :)

**Comment by OJFord** [comment]
@kinnison Sorry I missed your question before, primarily I use Linux (Arch, so 5.13 or whatever's current) but looking at my OP seems I was using macOS when O noticed/reported it.

I can double-check on my usual system in the morning, but presumably it's the same since @allanlaal is reproducing on Linux.

**Comment by AlejSala** [comment]
**error message** 
```/Users/yyyyyy/.zshenv:.:1: no such file or directory: /Users/yyyyyy/.cargo/env```

I’m not using Rust. FYI. 
any tips? need help. my Z shell .zsh and .zshenv went missing in MacOS Terminal. any ideas on how to resolve? it was there and then poofff gone👻

**Comment by kinnison** [comment]
I believe this issue is "not reproducible" - there was a new issue created to discuss including the variables in the `env` file, so I'm closing this one for now.

**Comment by Fuseteam** [comment]
i ran into this issue
1.  set $CARGO_HOME to ~/.local/share/cargo
2. run `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

before installing
![image](https://user-images.githubusercontent.com/10421851/168475673-eae1d471-5076-4caa-a0c5-8787605a1298.png)
after installing
![image](https://user-images.githubusercontent.com/10421851/168477149-d4c243c1-c9af-411b-ac1f-0a9e190523b6.png)

**Comment by kinnison** [comment]
@Fuseteam had you *exported* those environment variables before you ran the installer?

**Comment by OJFord** [comment]
The snippet I included in the _OP_ was clearly wrong:
```
        export PATH="$HOME/.cargo/bin:$PATH"
 ```
 
but it seems to have since been fixed (it's `{cargo_bin}` and that seems to come from reading CARGO_HOME if set) but it's hard to trace down when on GitHub, as it's been moved about (with that change already in place) since.

**Comment by Fuseteam** [comment]
@kinnison pretty sure i did 🤔
the variable is set as you can see in the above screenshot, isn't? all other scripts appear to see it too
