### ISSUE TITLE
Consider `upgrade` as alias for `update`

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rustup#2660]
Some people are used to saying `upgrade` when wanting to update toolchains.  As such it might be nice to offer this as an alias of `rustup update` which could either be visible or hidden.

I am happy to mentor someone through this work.

**Comment by chansuke** [comment]
I'd like to tackle this issue.

**Comment by kinnison** [comment]
Hi @chansuke - sorry for taking so long to respond, I'd be happy to see you work on this.
