### ISSUE TITLE
The test `check_updates_some` may be accessing the internet

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rustup#2663]
**Problem**

When running the test `check_updates_some`, and therefore likely others which test these code pathways, the internet is accessed in order to check for `rustup` updates.

Likely this is missing a `RUSTUP_UPDATE_ROOT` or similar in the environment during the running of those tests since normally we force `--no-self-update` etc. on appropriate CLI calls.

**Steps**

1. turn off your wifi/internet connection
2. `cargo test --test cli-exact -- check_updates_some`
3. see if it goes badly, and if so, deal with the fix.

**Possible Solution(s)**

Likely we simply need to either add a `--no-self-update` type argument to `rustup check` or else we need to correctly set up a `RUSTUP_UPDATE_ROOT` or whatever environment variable is missing.

**Comment by alexwlchan** [comment]
I'm having a look at this, I think I see what's going on.

Briefly: this seems to affect three tests in this file:

```
test check_updates_with_update ... FAILED
test check_updates_none ... FAILED
test check_updates_some ... FAILED
```

There is a setup function in the tests which sets a value for `RUSTUP_UPDATE_ROOT` to be a local `file://` URL, which some tests in that file are using (e.g. `check_updates_self`, which passes without Internet):

https://github.com/rust-lang/rustup/blob/90c840180955f245047b4a7045e6e949d4076884/tests/mock/clitools.rs#L194-L213

I think the fix would be to use that setup function in these three tests, so I'm going to try that now. I'll open a PR if I get somewhere useful.

**Comment by kinnison** [comment]
That sounds sensible.
