### ISSUE TITLE
Release 1.24.0

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rustup#2677]
Release checklist:

* [x] Write changelog
* [ ] Write blog post and get the PR ready
* [ ] Ensure all issues for 'fixed-in-next-release' are known
* [ ] Prepare stable branch update
* [ ] Make release, merge back to master.

(It'd be nice to make a template if this turns out to be useful)

**Comment by chrisduerr** [comment]
The latest release is 1.24.2, pretty sure this is done?

**Comment by kinnison** [comment]
@chrisduerr Yep, thanks for the reminder, It took so long I lost track of this issue 😀
