### ISSUE TITLE
shell restarting message can be confusing

### ISSUE THREAD

**Issue by Gurkenglas** [rust-lang/rustup#2681]
**Describe the problem you are trying to solve**
rustup-init added `%USERPROFILE%\.cargo\bin` to `PATH` but said
```
To get started you need Cargo's bin directory (%USERPROFILE%\.cargo\bin) in
your PATH environment variable. Future applications will automatically
have the correct environment, but you may need to restart your current shell.
```
at the end, so I unnecessarily went to add it.

**Describe the solution you'd like**
That message should not appear if `%USERPROFILE%\.cargo\bin` is in `PATH` by the end.

**Comment by rbtcollins** [comment]
I'm not sure how to communicate the situation better than we have.

PATH isn't just the registry setting. It is also an ephemeral value in the process environment block of each process. And the cmd prompt that that message is shown in does not have the cargo bin directory in the PATH that is in the process environment block.

Restarting that shell will pickup the value from the registry, as the message says you need to do.

**Comment by Gurkenglas** [comment]
Ah, I see. I thought the sentence described the situation as it would be after I finish adding `%USERPROFILE%\.cargo\bin` to the registry setting.

`To get started you may need to restart your current shell. This would reload its PATH environment variable to include Cargo's bin directory (%USERPROFILE%\.cargo\bin).`

**Comment by rbtcollins** [comment]
I think thats a good improvement. Would you like to put a patch forward?

**Comment by 0xPoe** [comment]
@rbtcollins This issue seems to have been fixed and we should be able to close it now?

**Comment by kinnison** [comment]
Indeed, thank you @hi-rustin

This ought to be in the next release.
