### ISSUE TITLE
rustup show active-toolchain could be more detailed

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rustup#2685]
Right now `rustup show active-toolchain` shows this on my system:
````
nightly-x86_64-unknown-linux-gnu (default)
````

It would be nice to not only know the active channel but perhaps also show the actual compiler version and the corresponding hash? (perhaps through a `--verbose` flag?)
````
nightly-x86_64-unknown-linux-gnu (default) - 1.52.0-nightly (94736c434 2021-02-27)
````

**Comment by kinnison** [comment]
I concur that it would be helpful to know this information.  Are you in a position to offer a patch?  If you want help working out what to do, we're willing to assist either here or on the Discord channel for Rustup.

**Comment by urohit011** [comment]
Can I take this issue?

**Comment by kinnison** [comment]
@urohit011 We don't really operate a process of handing issues out per-se, now that you've expressed an interest here, that's enough.  If you want to discuss things, then #wg-rustup on the rust-lang discord is the best place to find us, or you can post here too.  Thanks for being interested in getting into `rustup` development.
