### ISSUE TITLE
Problem installing Rust on Raspberry pi 4

### ISSUE THREAD

**Issue by Iqwertz** [rust-lang/rustup#2690]
I am now trying to install rustup for hours on an rpi and it is really frustrating!
So when I install rust with the following command: 
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
`
The install script runs but at the end it says:
`
info: profile set to 'default'
info: default host triple is i686-unknown-linux-gnu
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-aarch64-unknown-linux-gnu'
info: default toolchain set to 'stable-aarch64-unknown-linux-gnu'

  stable-aarch64-unknown-linux-gnu unchanged - (error reading rustc version)

Rust is installed now. Great!

To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH
environment variable. Next time you log in this will be done
automatically.

To configure your current shell, run:
source $HOME/.cargo/env
`

And when I try to run a cargo or rustc command it just says:
`error: command failed: 'rustc'
error: caused by: No such file or directory (os error 2)
`
I already looked at similar issues from this repo, but non of the solutions helped! 
Any Ideas what I could try or what the problem is?

(My RPI is in 64bit mode! But when I use 32bit mode I have similar problems)

(Ps: In another Issue it was stated that I should edit the "settings.toml" but when I search for it with this Command: 
` find . -name "settings.toml" -exec chmod o+r '{}' \;
`
It responds with:

`
find: ‘./wireguard’: Keine Berechtigung
find: ‘./cups/ssl’: Keine Berechtigung
find: ‘./ssl/private’: Keine Berechtigung
find: ‘./polkit-1/localauthority’: Keine Berechtigung
find: ‘./openvpn/easy-rsa/pki’: Keine Berechtigung
`

Dont know what to do with it! (Keine Berechtigung is german and means no access!) I could have access as sudo user however
)

**Comment by kinnison** [comment]
There is a lot confusing here.  For example, the mention of `info: default host triple is i686-unknown-linux-gnu` which feels like you have a very confused `~/.rustup/settings.toml`

Could you try first properly uninstalling via `rustup self uninstall` and then ensuring that you don't have a `~/.cargo` or `~/.rustup` left behind.  Then try installation from scratch with the `curl` command.

**Comment by Iqwertz** [comment]
Yeah it is really weird I guess there was an collision with another programm! I know installed a new Image and it worked fine! Sorry for the inconvinience!
