### ISSUE TITLE
Clarify GNU vs MSVC for Windows

### ISSUE THREAD

**Issue by Livven** [rust-lang/rustup#2693]
**Describe the problem you are trying to solve**

[The book says](https://github.com/rust-lang/rustup/blob/master/doc/src/installation/other.md):

> On Windows, download and run the [rustup-init.exe built for `i686-pc-windows-gnu` target][setup]. In general, this is the build of `rustup` one should install on Windows. Despite being built against the GNU toolchain, _the Windows build of `rustup` will install Rust for the MSVC toolchain if it detects that MSVC is installed_.

However, the [official Rust download page](https://www.rust-lang.org/tools/install) links to the MSVC version of `rustup-init`, going against the recommendation from the book.

Additionally, I ran the GNU version of `rustup-init` in a clean `mcr.microsoft.com/windows:1809` Docker container, which does not have MSVC, as confirmed by the fact that `cargo build` tells me I am missing the linker, and yet I still get an MSVC toolchain by default.

So it seems that the book is wrong about the MSVC detection, or it does not work reliably.

**Describe the solution you'd like**

To me, it seems the correct solution would be to recommend the MSVC version of `rustup-init`, but in any case the recommendation from the book and official download link should probably be aligned.

**Notes**

See above.

**Comment by rbtcollins** [comment]
I believe the book to be out of date: we decided to recommend the MSVC built rustup a long time ago. See #1353
