### ISSUE TITLE
MD5SUM for 1.10

### ISSUE THREAD

**Issue by may1393** [rust-lang/rustup#2699]
MD5SUM for 1.10
```
82358affdd7ab94854c8ee73a180fc53  googletest-release-1.10.0.zip
ecd1fa65e7de707cd5c00bdac56022cd  googletest-release-1.10.0.tar.gz
```
MD5SUM for 1.8.1
```
ad6868782b5952b7476a7c1c72d5a714  googletest-release-1.8.1.zip
2e6fbeb6a91310a16efe181886c59596  googletest-release-1.8.1.tar.gz
```

__Originally posted by @kriegalex in https://github.com/google/googletest/issues/2981#issuecomment-672002778__

**Comment by rbtcollins** [comment]
Our downloads are described in channel files; they are hashed with detached hashes, and inside the channel file are hashes for the files referenced therein. https://forge.rust-lang.org/infra/channel-layout.html
