### ISSUE TITLE
Provide clearly visible hashes to download rustup-init

### ISSUE THREAD

**Issue by bk2204** [rust-lang/rustup#2711]
**Describe the problem you are trying to solve**

I would like to install Rust on my system without piping curl to sh, and I would like to verify the cryptographic integrity of software I run on my system before permitting it to execute.  I would also like to install Rust in a secure way inside my CI scripts such that I can verify that the code I am executing in my build scripts is the same code as I originally downloaded.

**Describe the solution you'd like**

I'd like to see a strong cryptographic hash (that is, SHA-256 or similar) hash on the website next to the download files for each platform.  Alternatively, an easy-to-download file providing `sha256sum` or `sha256sum --tag` output (or similar) could be easily  linked to next to the binaries that are downloaded, optionally with a strong cryptographic signature alongside (e.g., a detached OpenPGP signature using a strong cryptographic algorithm).

**Notes**

I realize that in many cases, this information is in the channel files, but those files are not linked to from the website and are not easily discoverable without intimate knowledge about where they're located, and as a result, practically nobody verifies hashes.  This information _is_ available for other software, such as Go and Git.

I should also point out that in many environments, cryptographically verifying the software used as part of a CI run or to bootstrap a development environment is a requirement, so not providing this in an easy-to-discover way impedes the installation and use of Rust in these environments.

The places I would have expected to see this data would be at https://rustup.rs/ or
https://rust-lang.github.io/rustup/installation/other.html.

**Comment by kinnison** [comment]
I think the right thing is to link to the sha256 files which are present alongside the installers on `https://rust-lang.github.io/rustup/installation/other.html`  The lines in question start at https://github.com/rust-lang/rustup/blame/master/doc/src/installation/other.md#L35

**Comment by bk2204** [comment]
Sure, that would definitely meet my needs.  I'll see if I can find some time in the near future to get to it if nobody picks it up first.

**Comment by 0xPoe** [comment]
I am working on this.
