### ISSUE TITLE
`rustup check` should also check for updates to rustup itself

### ISSUE THREAD

**Issue by ickk** [rust-lang/rustup#2712]
According to [the rustup documentation](https://rust-lang.github.io/rustup/basics.html?highlight=update#keeping-rustup-up-to-date), `rustup update` already automatically updates both the installed toolchains and rustup itself. It would be helpful if the corresponding command for *checking* for updates behaved the same.

Currently it is not clear if there is any way to see whether there is an update to rustup without manually navigating to the stable branch on in the git repository and inspecting the Cargo.toml file - the [rustup.rs](https://rustup.rs) website and [rust-lang.github.io/rustup/](https://rust-lang.github.io/rustup/) documentation don't specify version, which makes troubleshooting things like new features difficult.

**Comment by rbtcollins** [comment]
I think this is a reasonable feature request. Note that you can do rustup self update to just update rustup.

**Comment by ickk** [comment]
Whoops. Seems this was already added in #2615 but hasn't made it's way into a release yet. 

Comments regarding versions being listed on rustup.rs and in the documentation stand though.

**Comment by kinnison** [comment]
This is indeed fixed in the next release.

**Comment by kinnison** [comment]
1.24.1 has now been released and hopefully won't need to be withdrawn.
