### ISSUE TITLE
Installer gets killed during installation

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rustup#2717]
Please I am unable to install rust 1.51.0 on Ubuntu 20.10 (groovy).
What could be wrong?

```
eshikafe@eshikafe-vb:~$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer

Welcome to Rust!

This will download and install the official compiler for the Rust
programming language, and its package manager, Cargo.

Rustup metadata and toolchains will be installed into the Rustup
home directory, located at:

  /home/eshikafe/.rustup

This can be modified with the RUSTUP_HOME environment variable.

The Cargo home directory located at:

  /home/eshikafe/.cargo

This can be modified with the CARGO_HOME environment variable.

The cargo, rustc, rustup and other commands will be added to
Cargo's bin directory, located at:

  /home/eshikafe/.cargo/bin

This path will then be added to your PATH environment variable by
modifying the profile files located at:

  /home/eshikafe/.profile
  /home/eshikafe/.bashrc

You can uninstall at any time with rustup self uninstall and
these changes will be reverted.

Current installation options:


   default host triple: x86_64-unknown-linux-gnu
     default toolchain: stable (default)
               profile: default
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>1

info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2021-03-25, rust version 1.51.0 (2fd73fabe 2021-03-23)
info: downloading component 'cargo'
  6.0 MiB /   6.0 MiB (100 %)   3.4 MiB/s in  2s ETA:  0s
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 14.9 MiB /  14.9 MiB (100 %)   1.4 MiB/s in 17s ETA:  0s
info: downloading component 'rust-std'
 24.9 MiB /  24.9 MiB (100 %)   1.3 MiB/s in 23s ETA:  0s 
info: downloading component 'rustc'
 50.4 MiB /  50.4 MiB (100 %)   3.2 MiB/s in 19s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: using up to 500.0 MiB of RAM to unpack components
info: installing component 'clippy'
info: installing component 'rust-docs'
 14.9 MiB /  14.9 MiB (100 %)   3.1 MiB/s in  4s ETA:  0s
info: installing component 'rust-std'
 24.9 MiB /  24.9 MiB (100 %)   5.4 MiB/s in  5s ETA:  0s
info: installing component 'rustc'
 30.1 MiB /  50.4 MiB ( 60 %)   6.0 MiB/s in  5s ETA:  3sKilled
eshikafe@eshikafe-vb:~$ 
```
rustup is unable to install rustc. It gets **Killed** while installing rustc.

_Originally posted by @eshikafe in https://github.com/rust-lang/rustup/issues/2661#issuecomment-816181334_

**Comment by kinnison** [comment]
Hi @eshikafe

Are you able to tell me how much RAM that system has?  Is there any indication in the kernel's logs (visible via the `dmesg` command) which corresponds with you trying to install Rust?

That kind of message typically happens if you run out of RAM, or if there's something even more wrong with the system.

**Comment by eshikafe** [comment]
Thanks @kinnison for the hint. I increased my VM's RAM from 1G to 4G to resolve the issue.

**Comment by rbtcollins** [comment]
Should be fixed with 1.24.1

**Comment by foresterre** [comment]
I think this is the same issue, but I'm not 100% sure, my apologies if it isn't.


---

@rbtcollins It may potentially still be an issue

On the github CI which has 500MB allocated RAM, rustup seems to sometimes time out with Rustup 1.24.1 too:

<details>
<summary>Details</summary>

```
Run hecrj/setup-rust-action@v1
  with:
    rust-version: stable-x86_64-gnu
C:\Rust\.cargo\bin\rustup.exe self update
info: checking for self-updates
info: downloading self-update
  rustup updated - 1.24.1 (from 1.23.1)

C:\Rust\.cargo\bin\rustup.exe set profile minimal
info: profile set to 'minimal'
C:\Windows\system32\where.exe rustup.exe
C:\Rust\.cargo\bin\rustup.exe
C:\Rust\.cargo\bin\rustup.exe toolchain install stable-x86_64-gnu
error: DEPRECATED: future versions of rustup will require --force-non-host to install a non-host toolchain as the default.
warning: toolchain 'stable-x86_64-gnu' may not be able to run on this system.
warning: If you meant to build software to target that platform, perhaps try `rustup target add x86_64-gnu` instead?
info: syncing channel updates for 'stable-x86_64-pc-windows-gnu'
info: latest update on 2021-03-25, rust version 1.51.0 (2fd73fabe 2021-03-23)
info: downloading component 'cargo'
info: downloading component 'rust-mingw'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: using up to 500.0 MiB of RAM to unpack components
memory allocation of 16777216 bytes failed
Error: The process 'C:\Rust\.cargo\bin\rustup.exe' failed with exit code 3221226505
```

sources: https://github.com/foresterre/cargo-msrv/pull/71, https://github.com/foresterre/cargo-msrv/pull/71/checks?check_run_id=2492532628

16777216 bytes = 15.999985 Mebibyte (MiB) = 16.7772 megabytes (MB)

---

</details>

In [cargo-msrv](https://github.com/foresterre/cargo-msrv), I use rustup to install different toolchain versions as required, and I have been tracking down an issue where downloads through rustup fail to complete. This happened primarily on CI machines (so far, I assume because of limited memory). It doesn't always fail (e.g. https://github.com/foresterre/cargo-msrv/pull/72/checks?check_run_id=2493685655) , and so far, I've only observed failures on Windows machines.

I saw it once happen on a local Windows machine (with 32GB RAM), but can't reproduce it consistently (or even once anymore). 

I'm happy to further help tracking this down, but I'm not sure where to start. 

---

Edit: it seems like another issue, #2748 was opened which more completely describes my issue. As such, I marked this comment as off-topic.

**Comment by rbtcollins** [comment]
Fixed by 1.24.2 for sure.

**Comment by BnDLett** [comment]
Currently having this issue on my rpi zero 2 w, which has 512 MB of RAM. Currently plan on building and running on my rpi rather than just building on my local machine.

**Comment by aschaeffer** [comment]
> Currently having this issue on my rpi zero 2 w, which has 512 MB of RAM. Currently plan on building and running on my rpi rather than just building on my local machine.

I had the same issue. You can temporarily enable and increase the swap to install the rust toolchain:

https://gist.github.com/tstellanova/0a6d8a70acc58a0d5be13ebaa7c935d4?permalink_comment_id=4647130#gistcomment-4647130

It would be helpful if rustup would warn about insufficient memory.

**Comment by BnDLett** [comment]
Would absolutely be useful, yes.

**Comment by rami3l** [comment]
@rbtcollins Looks like #2707 hasn't completely addressed this issue?

**Comment by rami3l** [comment]
@BnDLett @aschaeffer I found some workarounds which might be helpful for you:

> For whomever finds this thread while trying to install on raspberry pi zero 2w, I had to `export RUSTUP_UNPACK_RAM=250000000` to get it to work

_Originally posted by @ixje in https://github.com/rust-lang/rustup/issues/2564#issuecomment-1327238533_

>  A bit of a necro, but I was able to install rustc on a 512MB RAM OrangePi (4 cores) by also setting `RUSTUP_IO_THREADS=1`.

_Originally posted by @mon in https://github.com/rust-lang/rustup/issues/2919#issuecomment-1336407023_

**Comment by rami3l** [comment]
Related to #2919.

**Comment by AndreasOM** [comment]
Just hit this today on an EC2 instance.

Workaround for reference:
Create a swap file. (dd, mkswap, swapon)

You have to `uninstall` and (re)`install` the toolchain, as it ends up in a very broken state.
