### ISSUE TITLE
System-Rust-override warning is too scary

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/rustup#2726]
If a user installs Rust from Rustup, they probably want to install Rust from Rustup. They should be clearly and explicitly cautioned about what is happening, but the message should not try to implicitly dissuade them from continuing, as many package managers are now delivering Rust for system dependencies. Instead, it should be relatively reassuring: Rust's stability promises mean that even if something goes awry, they _probably_ won't bork their installation, but they should understand there's a nonzero risk.

**Steps**

0. use a Debian-based distro, mostly
1. curl the rustup script and run it
2. get a spooky warning that makes me say "Oh no!"

**Possible Solution(s)**
In order of estimated practicality and/or expedience:

0. Tone down the messages.
1. Work out a configuration that somehow makes it so there's no need to warn because there's never a fear of overriding.
2. Get distros to stop delivering Rust compilers even as more and more dependencies use it.

Output of `rustup --version`:
```
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.53.0-nightly (7af1f55ae 2021-04-15)`
```

**Comment by workingjubilee** [comment]
This echoes the needs of https://github.com/rust-lang/rustup/issues/1490 so it is fine if it is closed as a duplicate, however the messaging is still really intense.

**Comment by kinnison** [comment]
I agree this is related #1490 but your point about the messaging is valid and could be resolved before we do anything more complex.  As such I'd love it if someone would propose some relacement messages whose tone is a little more cautionary rather than scary.

**Comment by rbtcollins** [comment]
I can concur with the scariness aspect, but I'd like to clarify something: what are distros doing that leads to rustc/cargo being installed as part of the distro for system dependencies? Unlike python rustc/cargo are only needed when building system components, so unless someone is developing system packages, they shouldn't need a distro packaged rustc/cargo, correct?

**Comment by facklambda** [comment]
Hello all,

Here's what I'm seeing when I reproduce: 

```bash
fack@penguin:~$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer
warning: it looks like you have an existing installation of Rust at:
warning: /usr/bin
warning: rustup should not be installed alongside Rust. Please uninstall your existing Rust first.
warning: Otherwise you may have confusion unless you are careful with your PATH
warning: If you are sure that you want both rustup and your already installed Rust
warning: then please reply `y' or `yes' or set RUSTUP_INIT_SKIP_PATH_CHECK to yes
warning: or pass `-y' to ignore all ignorable checks.
error: cannot install while Rust is installed

Continue? (y/N) 
```

Is there desire to dampen the severity of this line specifically? 

> warning: rustup should not be installed alongside Rust. Please uninstall your existing Rust first.

I think changing it to something more persuading like:

> warning: It is recommended that rustup be the primary Rust installation. 
> warning: It is not recommended to install rustup alongside Rust
> warning: Please consider uninstalling your existing Rust before proceeding.

I've broken these lines up for legibility purposes.

I can create a draft PR with these changes if folks like the verbiage.

**Comment by kinnison** [comment]
@facklambda I'd be very happy with your proposed rewording, sorry for taking so long to get back to you.  If you're still interested in producing a PR, please do.
