### ISSUE TITLE
Detect dead code better

### ISSUE THREAD

**Issue by rbtcollins** [rust-lang/rustup#2730]
We should stop using 'pub' and instead use 'crate' within rustup. Rustup has no exported API, but having pub functions results in dead types and functions not being detected. https://github.com/rust-lang/rust/pull/79061 is an example of this technique applied to rustdoc

**Comment by 0xPoe** [comment]
I am working on this.

**Comment by 0xPoe** [comment]
- [ ] After most of the cleanup is done, we should globally introduce #! [deny(unreachable_pub)].

**Comment by 0xPoe** [comment]
I think we can close it now. It's done.
