### ISSUE TITLE
Mysterious hangs on MacOS

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/rustup#2733]
In https://github.com/rust-lang/rustup/pull/1071, a mild timeout was added to wait a second if rustc on the Apple environment was feeling truculent. Since, this has raised to 10 seconds, an order of magnitude increase, but it has still not actually fixed the problem: https://github.com/rust-lang/rustup/pull/2731

Presumably, this is happening on `x86_64-apple-darwin`, but it might be happening as well on `aarch64-apple-darwin`. The source of this problem should be found and resolved. In the meantime, since no "wait time" seems to actually fix the problem, the wait time should probably be reduced to 1 second and failure should probably try to emit an added warning about the problem, if possible.

**Comment by kinnison** [comment]
I concur that this is worthwhile investigating.  I think comment mentioned older toolchains so it may be something we cannot necessarily reliably address, but if someone with a mac could take a look, reduce the timeout to say 1s, and see which toolchains reliably fail then we can investigate why.

**Comment by kinnison** [comment]
If someone wants to help with this, they'll need a mac specifically.

**Comment by 0xPoe** [comment]
I am working on this.

**Comment by 0xPoe** [comment]
I will test it tomorrow.

**Comment by 0xPoe** [comment]
I can reproduce it. I can try to investigate why it's timeout.

```sh
➜  rustup git:(master) ✗ ./home/bin/rustup install stable
info: syncing channel updates for 'stable-x86_64-apple-darwin'

  stable-x86_64-apple-darwin unchanged - rustc 1.51.0 (2fd73fabe 2021-03-23)

info: checking for self-updates
info: downloading self-update
➜  rustup git:(master) ✗ ./home/bin/rustup uninstall stable
info: uninstalling toolchain 'stable-x86_64-apple-darwin'
info: toolchain 'stable-x86_64-apple-darwin' uninstalled
➜  rustup git:(master) ✗ ./home/bin/rustup install stable 
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: latest update on 2021-03-25, rust version 1.51.0 (2fd73fabe 2021-03-23)
info: downloading component 'cargo'
  4.3 MiB /   4.3 MiB (100 %) 836.7 KiB/s in  5s ETA:  0s
info: downloading component 'clippy'
  1.8 MiB /   1.8 MiB (100 %) 907.0 KiB/s in  1s ETA:  0s
info: downloading component 'rust-docs'
 15.0 MiB /  15.0 MiB (100 %)   1.7 MiB/s in 10s ETA:  0s
info: downloading component 'rust-std'
 23.6 MiB /  23.6 MiB (100 %)   2.0 MiB/s in 15s ETA:  0s    
info: downloading component 'rustc'
 56.6 MiB /  56.6 MiB (100 %)   2.0 MiB/s in 30s ETA:  0s    
info: downloading component 'rustfmt'
  2.3 MiB /   2.3 MiB (100 %) 756.2 KiB/s in  3s ETA:  0s
info: installing component 'cargo'
info: using up to 500.0 MiB of RAM to unpack components
info: installing component 'clippy'
info: installing component 'rust-docs'
 15.0 MiB /  15.0 MiB (100 %)   4.4 MiB/s in  2s ETA:  0s
info: installing component 'rust-std'
 23.6 MiB /  23.6 MiB (100 %)   8.8 MiB/s in  4s ETA:  0s
info: installing component 'rustc'
 56.6 MiB /  56.6 MiB (100 %)   3.8 MiB/s in 13s ETA:  0s
info: installing component 'rustfmt'

  stable-x86_64-apple-darwin installed - (timeout reading rustc version)

info: checking for self-updates
info: downloading self-update
➜  rustup git:(master) ✗ 

```

**Comment by 0xPoe** [comment]
The show command does not timeout on my computer, only when installing.

**Comment by rami3l** [comment]
@workingjubilee @hi-rustin The timeout logic seems gone in the current codebase and I cannot reproduce this on my ARM64 Mac. Is this issue still relevant?

**Comment by workingjubilee** [comment]
I think it isn't.
