### ISSUE TITLE
latent file removal bug

### ISSUE THREAD

**Issue by rbtcollins** [rust-lang/rustup#2734]
I just noticed that `ensure_file_removed` doesn't have the retry logic that `remove_file` does (both in `utils.rs`: the difference between them is solely that a file-not-found error is ignored by ensure-file-removed; so we should apply the retry logic - in fact we should just layer `ensure_file_removed` on `remove_file`.

**Comment by joshrotenberg** [comment]
I'm gonna give this one a shot if that's cool.
