### ISSUE TITLE
Release process should include explicit beta test period

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rustup#2741]
We should update the release process to include an explicit beta testing process where the staged release is offered up to users to validate that no regressions have been introduced.  Since there are a lot of release process items tied to pushing to the `stable` branch, this will involve:

* Agreeing the subset of binaries which will be included in this beta process
* Designating a `beta` branch for this part of the release
* Providing for the `beta` branch to upload to `dev-static.rlo`
* Adjusting the release process to use the `beta` branch, and to report and request testing on `internals.rust-lang.org`
* Adjusting the release process to include how we move from a beta release to a stable release

There may be further changes also needed, but that's the bare minimum.

Once some thought has gone into this, we will likely need to consult with the release team.

**Comment by rami3l** [comment]
Since this has been the new norm since #3719, I think we can safely close this issue now.
