### ISSUE TITLE
rustup-init with rust-toolchain

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/rustup#2749]
**Describe the problem you are trying to solve**
With the introduction of the TOML version of `rust-toolchain`, there isn't an easy way to install the exact version and components without also first installing the default toolchain. Where as with the old one line version you could write `rustup-init --default-toolchain $(cat rust-toolchain)`.

**Describe the solution you'd like**
`rustup-init --from-file ./rust-toolchain` or something similar.

**Comment by rbtcollins** [comment]
Dup of #2686 with the mild tweak of permitting it during rustup-init.
