### ISSUE TITLE
rustup self update causes error on Mac

### ISSUE THREAD

**Issue by Gumichocopengin8** [rust-lang/rustup#2757]
**Problem**

I tried to update rustup itself, but when I run `rustup self update`, I got the following errors.

```
error: self-update is disabled for this build of rustup
error: you should probably use your system package manager to update rustup
```

I installed rust through Homebrew, so I run `brew upgrade`. Nothing helped tho.

**Steps**

1. install Rust through Homebrew
2. When new rustup version is. available, run `rustup self update`
3. You'll get the errors

**Possible Solution(s)**

**Notes**

Output of `rustup --version`: 1.23.1

**Comment by kinnison** [comment]
If you installed `rustup` through homebrew, then you will only get your updates via that channel.  We cannot control/override that.  You will need to contact the maintainer of homebrew's rustup package.
