### ISSUE TITLE
Update from 1.51.0 to 1.52.0 failed

### ISSUE THREAD

**Issue by Zerotask** [rust-lang/rustup#2761]
**Problem**
Update from 1.51.0 to 1.52.0 failed

**Steps**

1. opened PowerShell Core (Windows 10)
2. run `rustup update`

<details>
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: latest update on 2021-05-06, rust version 1.52.0 (88f19c6da 2021-05-03)
info: downloading component 'rls'
info: downloading component 'rust-src'
info: downloading component 'rust-analysis'
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 15.3 MiB /  15.3 MiB (100 %)  11.0 MiB/s in  1s ETA:  0s
info: downloading component 'rust-std'
 21.6 MiB /  21.6 MiB (100 %)  11.0 MiB/s in  2s ETA:  0s
info: downloading component 'rustc'
 59.3 MiB /  59.3 MiB (100 %)  10.7 MiB/s in  5s ETA:  0s
info: downloading component 'rustfmt'
info: removing previous version of component 'rls'
info: removing previous version of component 'rust-src'
info: removing previous version of component 'rust-analysis'
info: removing previous version of component 'cargo'
info: removing previous version of component 'clippy'
info: rolling back changes
error: failure removing component 'clippy-preview-x86_64-pc-windows-msvc', directory does not exist: '"bin/cargo-clippy.exe"'
info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
info: latest update on 2021-05-08, rust version 1.54.0-nightly (770792ff8 2021-05-07)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 16.2 MiB /  16.2 MiB (100 %)  11.0 MiB/s in  1s ETA:  0s
info: downloading component 'rust-std'
 22.9 MiB /  22.9 MiB (100 %)  11.0 MiB/s in  2s ETA:  0s
info: downloading component 'rustc'
 59.6 MiB /  59.6 MiB (100 %)  11.0 MiB/s in  5s ETA:  0s
info: downloading component 'rustfmt'
info: removing previous version of component 'cargo'
info: removing previous version of component 'clippy'
info: removing previous version of component 'rust-docs'
info: removing previous version of component 'rust-std'
info: removing previous version of component 'rustc'
info: removing previous version of component 'rustfmt'
info: installing component 'cargo'
info: using up to 500.0 MiB of RAM to unpack components
info: installing component 'clippy'
info: installing component 'rust-docs'
 16.2 MiB /  16.2 MiB (100 %)   2.8 MiB/s in  5s ETA:  0s
info: installing component 'rust-std'
 22.9 MiB /  22.9 MiB (100 %)  10.2 MiB/s in  2s ETA:  0s
info: installing component 'rustc'
 59.6 MiB /  59.6 MiB (100 %)  11.7 MiB/s in  5s ETA:  0s
info: installing component 'rustfmt'
info: checking for self-updates

  stable-x86_64-pc-windows-msvc update failed - rustc 1.51.0 (2fd73fabe 2021-03-23)
       nightly-x86_64-pc-windows-msvc updated - rustc 1.54.0-nightly (770792ff8 2021-05-07) (from rustc 1.53.0-nightly (42816d61e 2021-04-24))

info: cleaning up downloads & tmp directories
</details>

After it, I retried it with `rustup update stable` and got basically the same error
`error: failure removing component 'clippy-preview-x86_64-pc-windows-msvc', directory does not exist: '"bin/cargo-clippy.exe"'`

Before the update I often used `cargo clippy` without errors.

If I run `cargo clippy` now, I got the error:
`error: the 'cargo-clippy.exe' binary, normally provided by the 'clippy' component, is not applicable to the 'stable-x86_64-pc-windows-msvc' toolchain`

So something seems to be broken now.

The command `rustup component add clippy` says:

`info: component 'clippy' for target 'x86_64-pc-windows-msvc' is up to date`

And if I try to remove it via `rustup component remove clippy` it says:

`error: failure removing component 'clippy-preview-x86_64-pc-windows-msvc', directory does not exist: '"bin/cargo-clippy.exe"'`

In my home directory, there is a clippy binary:
**~\.cargo\bin\cargo-clippy.exe**

**Notes**

Output of `rustup --version`: rustup 1.24.1 (a01bd6b0d 2021-04-27)
Output of `rustup show`:
```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Patrick\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

**Comment by kinnison** [comment]
This could be caused by a corrupt toolchain installation.  The likely easiest way to fix this will be to `rustup toolchain remove stable` and then `rustup toolchain install stable` once more.  It is very important that you don't have any IDEs etc. open when you do this as they can interfere.

**Comment by Zerotask** [comment]
This worked, thanks.

**Comment by kinnison** [comment]
Excellent, sorry for the confusion.
