### ISSUE TITLE
The rust-toolchain.toml file works on Linux but not on Mac

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-lang/rustup#2766]
**Problem**

I just ran into an issue in GitHub Actions where running `rustup show` on Linux will correctly download the desired nightly Rust version and components while the Mac build continued using `stable` and later failed.

**Steps**

1. Add a `rust-toolchain.toml` to your repository
2. Set up GitHub CI to build your project on Mac and Linux
3. Push the changes to kick off a build
4. Wait for the Mac build to fail

You can see a full run [here](https://github.com/hotg-ai/rune/pull/142/checks?check_run_id=2556436555) using [this `rust-toolchain.toml` file](https://github.com/hotg-ai/rune/blob/8c2f7536c101c712749f535e0621db3b82ed74e3/rust-toolchain.toml).

**Notes**

```
Default host: x86_64-apple-darwin
rustup home:  /Users/runner/.rustup

stable-x86_64-apple-darwin (default)
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

**Comment by ehuss** [comment]
Are you sure you are running rustup 1.24?  The GitHub hosted runners are updated on different cycles. [macOS 10.15](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#rust-tools) is currently on 1.23.1 whereas [ubuntu 18](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md#rust-tools) is on 1.24.1.  macOS updates tend to lag quite a bit behind the others.

The link for the run is gone, as it looks like the action was maybe restarted.

**Comment by rbtcollins** [comment]
Yeah, 99.99% sure this is just an old rustup. Do a rustup self update and it should be better.

**Comment by ehuss** [comment]
> Do a rustup self update and it should be better.

Self-updates are disabled on GitHub hosted runners (and Azure if IIRC).

**Comment by rbtcollins** [comment]
Ah then install a fresh copy, or file a ticket wherever that action image is maintained

**Comment by Michael-F-Bryan** [comment]
@rbtcollins thanks, I re-installed `rustup` on the Mac build and it worked exactly intended.
