### ISSUE TITLE
--force-non-host warning is too broad

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rustup#2773]
**Problem**
`rustup update stable-msvc` (or other combinations like `nightly-gnu`) on Windows generates a warning:

```
error: DEPRECATED: future versions of rustup will require --force-non-host to install a non-host toolchain as the default.
warning: toolchain 'stable-msvc' may not be able to run on this system.
warning: If you meant to build software to target that platform, perhaps try `rustup target add msvc` instead?
```

**Possible Solution(s)**
Don't warn about installing msvc or gnu on windows.

**Notes**

Output of `rustup --version`: rustup 1.24.2 (755e2b07e 2021-05-12)
Output of `rustup show`:
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\User\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.52.0-nightly (fe1bf8e05 2021-02-23)

**Comment by rbtcollins** [comment]
Note that this occurs with the *release build* of rustup, not just the gnu build of rustup. I think this is a regression.

```
C:\Users\RobertCollins>rustup update stable-msvc
error: DEPRECATED: future versions of rustup will require --force-non-host to install a non-host toolchain as the default.
warning: toolchain 'stable-msvc' may not be able to run on this system.
warning: If you meant to build software to target that platform, perhaps try `rustup target add msvc` instead?
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.52.1 (9bc8c42bb 2021-05-09)

info: checking for self-updates
```
