### ISSUE TITLE
Rustup installation fails.

### ISSUE THREAD

**Issue by sinlesschip** [rust-lang/rustup#2775]
**Problem**
When installing rust the installation fails.
No internet connection problems.
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer
curl: (23) Failure writing output to destination
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init /tmp/tmp.Wa28tcK51q/rustup-init x86_64-unknown-linux-gnu
```

**Steps**
1. run `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

**Possible Solution(s)**
Unsure

**Notes**

Output of `rustup --version`: 
```
Command 'rustup' not found, but can be installed with:

sudo snap install rustup
```
Output of `rustup show`:
```
Command 'rustup' not found, but can be installed with:

sudo snap install rustup
```

**Comment by kinnison** [comment]
It looks like your `/tmp` is either unwritable or full.  Can you confirm if it is?

**Comment by sinlesschip** [comment]
Sorry I'm dumb, I don't how to do this. I'm not great with Linux.

**Comment by sinlesschip** [comment]
Okay, I've found in the properties through the GUI it says 182gb free space and all permissions are set to create and delete files.

**Comment by kinnison** [comment]
Don't worry, I'll do my best to help you out.  Your original report suggested that you have `snap` available to you.  If you would prefer, you could install `rustup` through `snap` which might be easier for you.  Try the following command sequence:

```shell
$ sudo snap install rustup
$ rustup toolchain install stable
$ rustup default stable
```

Hopefully that'll sort you out.

**Comment by sinlesschip** [comment]
Thanks for you help, I ran:
`$ sudo snap install rustup
`
and got this error:
```
error: This revision of snap "rustup" was published using classic confinement
       and thus may perform arbitrary system changes outside of the security
       sandbox that snaps are usually confined to, which may put your system at
       risk.

       If you understand and want to proceed repeat the command including
       --classic.
```
Is this safe to run with the `--classic` flag?

**Comment by kinnison** [comment]
Aah yes, I forgot you'd need `--classic` - this is so that the toolchains can actually find and build your code :D  It is expected to need `--classic` at this time.

**Comment by sinlesschip** [comment]
It worked! Hm I wonder why it wouldn't install with the original command off the docs. Anyways, thank you!

**Comment by LarsKue** [comment]
Hijacking this because it's the first thing that pops up when googling this error.

The real solution can be found [here](https://stackoverflow.com/a/74635806), which is that if you installed `curl` through `snap`, uninstall it and reinstall through `apt`.
