### ISSUE TITLE
For some reason I can't change to nightly

### ISSUE THREAD

**Issue by wijiler** [rust-lang/rustup#2778]
so I'm trying to use rocket but for some odd reason when I do rustup override set nightly it says it changed my version than i do rustc -V and it doesn't work

**Steps**

1.I don't know why this happened
2.
3.

**Notes**
Nightly 15.40.0
but when I do 
rustc --version or rustc -V
it says I'm on stable 14.48.0??!?!?!?!?!?

**Comment by kinnison** [comment]
The version numbers you're giving are very confused.  Current nightly is 1.54 and current stable is 1.52 so I'm not sure where 15.40 or 14.48 come from.

Can you confirm the output of:

* `which rustup`
* `which rustc`
* `rustup show`

**Comment by wijiler** [comment]
oh it's fixed now I had to restart for rust to work again

**Comment by wijiler** [comment]
im assuming it just didnt update the path

**Comment by wijiler** [comment]
untill the restart
