### ISSUE TITLE
bash: rustup: command not found

### ISSUE THREAD

**Issue by dark0ghost** [rust-lang/rustup#2794]
**Problem**
bash: rustup: command not found

**Steps**

1.curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
2. rustup update

OS: Parrot OS 4.11 x86_64 
Kernel: 5.10.0-6parrot1-amd64

**Comment by kinnison** [comment]
Did you run these commands one after another in the same terminal window?  If so, did you follow the instructions to add the PATH before you ran the second command?

If you had a fresh shell for the second command, can you confirm please which shell you are using?

**Comment by dark0ghost** [comment]
I did the commands sequentially.Variables set. Restart konsole no effect.
bash:
`GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
`

**Comment by kinnison** [comment]
Please check your `PATH` environment variable (`echo $PATH`) and your `.bashrc` `.bash_profile` `.bash_login` and `.profile` dotfiles (not all will be present) to see if they have been updated to source your `.cargo/env` file.

**Comment by dark0ghost** [comment]
path:
`/opt/swift/usr/bin:/opt/swift/usr/bin:/home/dark0ghost/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/home/dark0ghost/.sdkman/candidates/java/current/bin:/home/dark0ghost/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games/:/home/dark0ghost/.cargo/env
`
and in .bashrc & .profile there is a mention of cargo

**Comment by kinnison** [comment]
I'm fascinated as to how `/home/dark0ghost/.cargo/env` has ended up in your `PATH` variable.  It should be `/home/dark0ghost/.cargo/bin` being added by our scripts.  What is the mention of cargo in those files?

**Comment by dark0ghost** [comment]
.bashrc:
`PATH=/opt/swift/usr/bin:/home/dark0ghost/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/home/dark0ghost/.sdkman/candidates/java/current/bin:/home/dark0ghost/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
. "$HOME/.cargo/env" export PATH=/opt/swift/usr/bin:/opt/swift/usr/bin:/home/dark0ghost/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/home/dark0ghost/.sdkman/candidates/java/current/bin:/home/dark0ghost/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games/`
.profile:
`# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
. "$HOME/.cargo/env" `

**Comment by dark0ghost** [comment]
initially I put through "apt install" maybe there is a problem?

**Comment by kinnison** [comment]
Okay, the bashrc/profile changes look correct.  Can you please show me the content of `$HOME/.cargo/env` which should be a short script which adds `.../.cargo/bin` to your `PATH`.

(And I appreciate this is a bit of a long-shot, but could you also try rebooting [or at least logging out and back in] too) ?

**Comment by dark0ghost** [comment]
during this time the computer has been restarted many times
.cargo/env:
```bash
#!/bin/sh
# rustup shell setup
# affix colons on either side of $PATH to simplify matching
case ":${PATH}:" in
    *:"$HOME/.cargo/bin":*)
        ;;
    *)
        # Prepending path in case a system-installed rustc needs to be overridden
        export PATH="$HOME/.cargo/bin:$PATH"
        ;;
esac
```

**Comment by kinnison** [comment]
That looks entirely correct, so either something else is *removing* that path from your environment, or something else is broken.  If you run `source ~/.cargo/env` in your shell, does `rustup` etc. now work?

**Comment by dark0ghost** [comment]
I ran  
```bash
 source ~/.cargo/env
 ```
  ,  but nothing has changed. I write in $PATH:/.cargo/bin and and it helped. I guess it is something wrong in os

**Comment by kinnison** [comment]
I specifically said `source ~/.cargo/env` **NOT** `bash source ...`.  I think something is very very wrong with your OS if this is not working now.  Could you remind me which OS and version you are running?

**Comment by dark0ghost** [comment]
Parrot os 4.11

**Comment by kinnison** [comment]
Parrot is based on Debian so I wouldn't expect anything particularly strange.  Can you please run the following in sequence in the same terminal, and then paste the entire terminal output for me...

1. `env | grep "^PATH="`
2. `grep cargo ~/.bashrc`
2. `grep cargo ~/.profile`
3. `source ~/.cargo/.env`
4. `env | grep "^PATH="`

As an example, here's the output from me doing that:

```console
danielsilverstone@equanimity:~$ env | grep "^PATH="
PATH=/home/danielsilverstone/.nix-profile/bin:/home/danielsilverstone/.local/bin:/snap/bin:/home/danielsilverstone/goroot/current/bin:/home/danielsilverstone/.npm-global/bin:/usr/games:/home/danielsilverstone/.cargo/bin:/home/danielsilverstone/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
danielsilverstone@equanimity:~$ grep cargo ~/.bashrc
danielsilverstone@equanimity:~$ grep cargo ~/.profile
export PATH="$HOME/.cargo/bin:$PATH"
danielsilverstone@equanimity:~$ source ~/.cargo/env
danielsilverstone@equanimity:~$ env | grep "^PATH="
PATH=/home/danielsilverstone/.nix-profile/bin:/home/danielsilverstone/.local/bin:/snap/bin:/home/danielsilverstone/goroot/current/bin:/home/danielsilverstone/.npm-global/bin:/usr/games:/home/danielsilverstone/.cargo/bin:/home/danielsilverstone/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
danielsilverstone@equanimity:~$ 
```

**Comment by dark0ghost** [comment]
1) env | grep "^PATH=":
```bash
PATH=/opt/swift/usr/bin:/opt/swift/usr/bin:/home/dark0ghost/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/home/dark0ghost/.sdkman/candidates/java/current/bin:/home/dark0ghost/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games/
```
2) grep cargo ~/.bashrc :
```bash
. "$HOME/.cargo/env"
```
3)  grep cargo ~/.profile:
```bash
. "$HOME/.cargo/env"
```
4) source ~/.cargo/env and env | grep "^PATH=":
```bash
PATH=/home/dark0ghost/.cargo/bin:/opt/swift/usr/bin:/opt/swift/usr/bin:/home/dark0ghost/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/home/dark0ghost/.sdkman/candidates/java/current/bin:/home/dark0ghost/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games/
```

**Comment by dark0ghost** [comment]
> I specifically said `source ~/.cargo/env` **NOT** `bash source ...`. I think something is very very wrong with your OS if this is not working now. Could you remind me which OS and version you are running?

here I have not formatted correctly

**Comment by kinnison** [comment]
Okay thank you for doing that @dark0ghost -- it looks like your shell isn't reading either of `.bashrc` or `.profile` then, since sourcing the file yourself definitely adds the path in.  Unless some other part of your shell startup is then resetting the path, which would be unusual.  Can you confirm that you *are* using bash as your shell?  I know you said so in the first post, but since then you may have changed things.

**Comment by dark0ghost** [comment]
Yes, I use bash. Nothing has changed since the last time

**Comment by kinnison** [comment]
There's something odd going on then that your bash isn't reading either of those files, you're going to need to work out what rc file your shell reads when you open your terminal so that you can determine which of those files needs the `. ~/.cargo/env` line in it.  Once you've found that you can copy it from the `.bashrc` or `.profile` into that file and hopefully new terminals will have that automatically.  Until you've found that, you can source the file yourself as you have now seen.

Also, once you work out which file needed the line adding to it, please let us know so that we can add it to the set of files that our installer will automatically update.

**Comment by dark0ghost** [comment]
I decided to try to fix it, but nothing happened. decided to go through these steps one more time and finally added to $PATH. Also there was an update in packages today. I suspect the problem is resolved with help update .
$PATH now:
```bash
echo $PATH
/home/dark0ghost/.cargo/bin:/opt/swift/usr/bin:/opt/swift/usr/bin:/home/dark0ghost/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/home/dark0ghost/.sdkman/candidates/java/current/bin:/home/dark0ghost/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games/

```

**Comment by dark0ghost** [comment]
After reboot nothing works.
if in bash write source ~/.cargo/env - work, but after reboot - no. Only works fine if you overwrite the path manually. I copied the script to a .bashrc, but the system does not seem to see it

**Comment by kinnison** [comment]
I remain entirely confused as to what's going on for you.  have you managed to solve this yet yourself?  If so, could you please let me know what it was?

**Comment by dark0ghost** [comment]
I manually corrected it by adding in .bashrc ``` export PATH=$HOME/.cargo/bin:$PATH``` and source ~/.bashrc and all works

**Comment by kinnison** [comment]
OK thanks, I can't think what might have gone wrong, so I'm going to close this for now.  If someone has a similar problem we can either file a fresh issue or reopen this one as appropriate.

**Comment by Umuril** [comment]
I've just installed the last ParrotOS version (5.2 ATM) and installed rustup as website suggests:
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
Found the exact same issue.
Reading the top of .profile file mentions: 
```
# ~/.profile: executed by the command interpreter for login shells.
```
And:
```
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
```
The second is true, neither of those files exists.
The first one was my problem, according to this [StackOverflow question](https://askubuntu.com/questions/566399/why-isnt-profile-sourced-when-opening-a-terminal) the problem was my terminal not running a login shell.
In fact, there's a screenshot with a flag to enable "login shell" and that solved my problem with rustup.

I don't know the implications to have only the PATH changed by .profile which assumes a "login shell", which at least for ParrotOS, seems not be the default for MATE Terminal.

Just wanted to give a hint to dark0ghost and kinnison the ability to evaluate this as a bug to fix or just a problem on how ParrotOS handles default terminal settings. (In which case maybe i'll open an issue for them to evaluate the same)

**Comment by dark0ghost** [comment]
Thx, but in 4.11v i was used kde)

But it certainly won't be redundant
