### ISSUE TITLE
Clarify in which component and/or profile `rustdoc` is

### ISSUE THREAD

**Issue by ojeda** [rust-lang/rustup#2801]
**Describe the problem you are trying to solve**
It is not clear from https://github.com/rust-lang/rustup/blob/master/doc/src/concepts/components.md from which component `rustdoc` comes from, and therefore it is not clear that it is included in the minimal profile.

**Describe the solution you'd like**
Clarify in https://github.com/rust-lang/rustup/blob/master/doc/src/concepts/components.md from which component `rustdoc` comes from.

Perhaps also clarify in https://github.com/rust-lang/rustup/blob/master/doc/src/concepts/profiles.md that the components in the minimal profile also include other tools.

**Comment by jyn514** [comment]
`rustdoc` is in the `rustc` component. You cannot install rustc without also installing rustdoc.

**Comment by ojeda** [comment]
Yeah, exactly: that is not clear from the docs. It just says "`rustc` — The Rust compiler.", without mentioning `rustdoc`.

**Comment by rbtcollins** [comment]
closing in favour of that PR

**Comment by ojeda** [comment]
Hmm... an issue should not be closed until the PR is merged (and if referenced, GitHub will close it for you).

**Comment by rbtcollins** [comment]
for some reason I thought this came from the channels and thus was in the wrong repository, sorry.

**Comment by ojeda** [comment]
No problem at all :D
