### ISSUE TITLE
`rustup update` does NOT report when self-update is disabled

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rustup#2807]
**Problem**

As noted in #2757, `rustup` can't update itself when `rustup` is installed using a system package manager like homebrew. `rustup self update` reports an error in this case:

```
rustup self update
error: self-update is disabled for this build of rustup
error: you should probably use your system package manager to update rustup
```

`rustup update --help` (that is, without `self`) says:

```
rustup-update
Update Rust toolchains and rustup
...
DISCUSSION:
    With no toolchain specified, the `update` command updates each of
    the installed toolchains from the official release channels, then
    updates rustup itself.
```

I expected `rustup update` to report the same `self-update is disabled` error that `rustup self update` reported when `rustup update` tries to update `self`, but instead it silently fails to update `rustup`:

```
rustup update
info: syncing channel updates for 'stable-aarch64-apple-darwin'
info: syncing channel updates for 'beta-aarch64-apple-darwin'
  stable-aarch64-apple-darwin unchanged - rustc 1.53.0 (53cb7b09b 2021-06-17)
    beta-aarch64-apple-darwin unchanged - rustc 1.54.0-beta.1 (bf62f4de3 2021-06-23)
info: cleaning up downloads & tmp directories
```

Note the lack of `info: checking for self-updates`.

Someone who installed `rustup` through homebrew and has never run `rustup self update` would think that `rustup update` *was* updating `rustup` (they also wouldn't know that usually the output contains `info: checking for self-updates`), and would have trouble figuring out why `rustup` wasn't updating.

**Steps**

1. Install `rustup` with homebrew
2. Run `rustup update`
3. Observe no error message where there should be one and no `info: checking for self-updates` in the output

**Possible Solution(s)**

Show the same error for `rustup update` that `rustup self update` shows when self-update is disabled.

**Notes**

Output of `rustup --version`: rustup 1.24.3 (ce5817a94 2021-05-31)

**Comment by rbtcollins** [comment]
Does homebrew automatically update packages installed via it?

**Comment by 0xPoe** [comment]
> Does homebrew automatically update packages installed via it?

Yes, it will check itself and the installed software to see if it needs to be updated before installing the new software.

**Comment by kushaldas** [comment]
@carols10cents Please let me know if the following would be an ideal behavior in your mind:

```
$ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.54.0 (a178d0322 2021-07-26)

info: cleaning up downloads & tmp directories
info: self-update is disabled for this build of rustup
info: you should probably use your system package manager to update rustup
```

I would love to work on this issue as my first code contribution here :)

**Comment by kinnison** [comment]
I am unsure if we should use exactly the same message here since there's a difference between an explicit attempt to `self update` and this automatic operation.  Perhaps:

```
...
info: cleaning up downloads & tmp directories
info: self-update is disabled for this build of rustup
info: any updates to rustup will need to be fetched with your system package manager
```

Wording can be argued out later though once some code is in place.

**Comment by kushaldas** [comment]
> I am unsure if we should use exactly the same message here since there's a difference between an explicit attempt to `self update` and this automatic operation. Perhaps:
> 
> ```
> ...
> info: cleaning up downloads & tmp directories
> info: self-update is disabled for this build of rustup
> info: any updates to rustup will need to be fetched with your system package manager
> ```
> 
> Wording can be argued out later though once some code is in place.

Thank you, I will work on this tonight.
