### ISSUE TITLE
CI for FreeBSD

### ISSUE THREAD

**Issue by asomers** [rust-lang/rustup#2818]
**Describe the problem you are trying to solve**
rustup could use some continuous integration tests on FreeBSD.  If it had, then bug #2629 would've been caught immediately.

**Describe the solution you'd like**
CI for Rust on FreeBSD is pretty easy using Cirrus CI, much easier than with Github Actions.  If you follow the instructions at https://cirrus-ci.org/guide/quick-start/ and stop at "Post Installation", I can do the rest.

**Comment by kinnison** [comment]
This is being addressed in #2783

**Comment by Erk-** [comment]
This has been addressed in #2955

**Comment by rami3l** [comment]
This should've been closed by #2955, I believe. Thanks @Erk- for the notice!
