### ISSUE TITLE
Sha256 files includes the build directory path making automated verification more difficult

### ISSUE THREAD

**Issue by longtomjr** [rust-lang/rustup#2819]
**Describe the problem you are trying to solve**
When verifying the `*.sha256` files for the `rustup-init` downloads it is not possible to use a simple `sha256sum -c rustup-init.sha256 2>&1` out of the box. The reason is that the sha256 file includes the nested directories in the path like so `<hash> *target/x86_64-unknown-linux-gnu/release/rustup-init`.

**Describe the solution you'd like**
The solution here would be to publish the `*.sha256` files without the nested build directory in the path. There might be an alternative way to verify the hashes easily that I am not aware of, so providing instructions for that at https://rust-lang.github.io/rustup/installation/other.html will also be a solution. 

**Notes**
There is an old issue that touches on this: #294 (I decided to create a new issue since the old issue were closed)

Related: #2711, #2719

**Comment by kinnison** [comment]
The place to look to fix this for WIndows is:

https://github.com/rust-lang/rustup/blob/master/ci/prepare-deploy.ps1#L6

And for other targets is:

https://github.com/rust-lang/rustup/blob/master/ci/prepare-deploy.bash#L9-L13

Should be a fairly easy fix for someone.

**Comment by chansuke** [comment]
@longtomjr The result below can be helpful? Or should the file path be completely removed?
```
$ less target/"$TARGET"/release/rustup-init.sha256
<hash> *./rustup-init
```

**Comment by kinnison** [comment]
I don't think we'd want the "*./" no.

**Comment by sathwikmatsa** [comment]
I was able to put together a command to only have the basename in .sha256 file. However, I'm not sure how to verify it in CI or locally. Can we somehow access the build artifacts from PR builds?

**Comment by kinnison** [comment]
Sorry to have left this so long - yes, build artifacts should be available from PR builds, so long as the action does the right thing to say they should be.  Or you could just add an action step to generate the files, but emit them to stdout, and then look in the action logs, that might be easier.

**Comment by chorrell** [comment]
fwiw, this is my current workaround when scripting the rustup install in e.g. docker images:

```bash
curl -fsSLO --compressed "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
curl -fsSLO --compressed "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init.sha256"
echo "$(cat rustup-init.sha256 | cut -f1 -d" ") rustup-init" | sha256sum -c -
```

It strips out the build path to give sha256sum what it expects.

**Comment by rami3l** [comment]
I believe this has been addressed by https://github.com/rust-lang/rustup/pull/3730.
