### ISSUE TITLE
Colours

### ISSUE THREAD

**Issue by Milo123459** [rust-lang/rustup#2826]
**Describe the problem you are trying to solve**

Adding some colours
**Describe the solution you'd like**

Adding some colours to the commands
**Notes**

- [x] I'm willing to make a PR

Hey, I'm just asking. I was thinking maybe we should add some more colours to the rustup CLI. Maybe stable toolchains are green, nightly is red, etc. Let me know what you think. As seen above, I am happy to make a PR

**Comment by kinnison** [comment]
I feel like adding colours to the UI would be counterproductive.  We do have support for **bold** text in some of our output, but colours are not consistent across society.  For example:

* **Red** can mean any of love, passion, lust, danger, important, but also good luck, and happiness
* **Green** can mean any of nature, healing, youth, fertility, but also greed, sickness, jealousy, and inexperience.

I'd need to see a compelling argument to colourise `rustup`'s output.

**Comment by Milo123459** [comment]
It's pointless but the point is it's just to make it more readable. We can use any colours and even allow the user to customise it. I just wanted to implement it as it helps give some contrast.

**Comment by 0xPoe** [comment]
I think maybe the color to distinguish warnings from errors is valid (we already have it). But differentiating colors by channel would be weird and confusing with the colors of warnings and errors?

**Comment by kinnison** [comment]
I concur with @hi-rustin I'm also of the opinion there'd be confusion.  And @Milo123459 I think you hit the nail on the head when you say "it's pointless".  If there is a contrast issue at stake then perhaps we can use spacing to make things clearer.

**Comment by Milo123459** [comment]
Yea I guess.
