### ISSUE TITLE
installing rust on raspbian fails

### ISSUE THREAD

**Issue by 68CodingMonkeys** [rust-lang/rustup#2827]
Tried to install rust like documented in https://www.rust-lang.org/learn/get-started
(Hardware is a PI Model 4B with acutal raspbian buster)

cuser@node00:/Projekt/pd $ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer

Welcome to Rust!

This will download and install the official compiler for the Rust
programming language, and its package manager, Cargo.

Rustup metadata and toolchains will be installed into the Rustup
home directory, located at:

  /home/cuser/.rustup

This can be modified with the RUSTUP_HOME environment variable.

The Cargo home directory located at:

  /home/cuser/.cargo

This can be modified with the CARGO_HOME environment variable.

The cargo, rustc, rustup and other commands will be added to
Cargo's bin directory, located at:

  /home/cuser/.cargo/bin

This path will then be added to your PATH environment variable by
modifying the profile files located at:

  /home/cuser/.profile
  /home/cuser/.bashrc

You can uninstall at any time with rustup self uninstall and
these changes will be reverted.

Current installation options:

   default host triple: aarch64-unknown-linux-gnu
     default toolchain: stable (default)
               profile: default
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>2

I'm going to ask you the value of each of these installation options.
You may simply press the Enter key to leave unchanged.

Default host triple? [aarch64-unknown-linux-gnu]

Default toolchain? (stable/beta/nightly/none) [stable]
stable

Profile (which tools and data to install)? (minimal/default/complete) [default]
minimal

Modify PATH variable? (Y/n)
Y

Current installation options:

   default host triple: aarch64-unknown-linux-gnu
     default toolchain: stable
               profile: minimal
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>1

info: profile set to 'minimal'
info: setting default host triple to aarch64-unknown-linux-gnu
info: syncing channel updates for 'stable-aarch64-unknown-linux-gnu'
info: latest update on 2021-06-17, rust version 1.53.0 (53cb7b09b 2021-06-17)
info: downloading component 'cargo'
info: downloading component 'rust-std'
 26.2 MiB /  26.2 MiB (100 %)   6.9 MiB/s in  7s ETA:  0s
info: downloading component 'rustc'
 79.2 MiB /  79.2 MiB (100 %)   6.5 MiB/s in 21s ETA:  0s
info: installing component 'cargo'
  5.3 MiB /   5.3 MiB (100 %)   4.8 MiB/s in  1s ETA:  0s
info: installing component 'rust-std'
 26.2 MiB /  26.2 MiB (100 %)   3.8 MiB/s in 17s ETA:  0s
info: installing component 'rustc'
 79.2 MiB /  79.2 MiB (100 %)   4.1 MiB/s in 48s ETA:  0s
  9 IO-ops /   9 IO-ops (100 %)   0 IOPS in 11s ETA: Unknown
info: default toolchain set to 'stable-aarch64-unknown-linux-gnu'

  stable-aarch64-unknown-linux-gnu installed - (error reading rustc version)

Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source $HOME/.cargo/env
cuser@node00:/Projekt/pd $ uname -a
Linux node00 5.10.17-v8+ #1421 SMP PREEMPT Thu May 27 14:01:37 BST 2021 aarch64 GNU/Linux
cuser@node00:/Projekt/pd $ cat /boot/cmdline.txt 
console=serial0,115200 console=tty1 root=PARTUUID=4fede8e8-02 rootfstype=ext4 arm_64bit=0 elevator=deadline fsck.repair=yes rootwait 
cuser@node00:/Projekt/pd $ source $HOME/.cargo/env
cuser@node00:/Projekt/pd $ cargo --help
error: command failed: 'cargo': No such file or directory (os error 2)

**Comment by rbtcollins** [comment]
After the source, what is the value of `$PATH` ? And is there a cargo in `~/.cargo/bin/`?

**Comment by 68CodingMonkeys** [comment]
cuser@node00:/Projekt/pd $ echo $PATH
/home/cuser/bin:/home/cuser/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/home/cuser/bin

cuser@node00:/Projekt/pd $ which cargo
/home/cuser/.cargo/bin/cargo

cuser@node00:/Projekt/pd $ ls -l ~/.cargo/bin
total 163776
-rwxr-xr-x 12 cuser cluster 13974212 Jul 16 12:08 cargo
-rwxr-xr-x 12 cuser cluster 13974212 Jul 16 12:08 cargo-clippy
-rwxr-xr-x 12 cuser cluster 13974212 Jul 16 12:08 cargo-fmt
-rwxr-xr-x 12 cuser cluster 13974212 Jul 16 12:08 cargo-miri
-rwxr-xr-x 12 cuser cluster 13974212 Jul 16 12:08 clippy-driver
-rwxr-xr-x 12 cuser cluster 13974212 Jul 16 12:08 rls
-rwxr-xr-x 12 cuser cluster 13974212 Jul 16 12:08 rustc
-rwxr-xr-x 12 cuser cluster 13974212 Jul 16 12:08 rustdoc
-rwxr-xr-x 12 cuser cluster 13974212 Jul 16 12:08 rustfmt
-rwxr-xr-x 12 cuser cluster 13974212 Jul 16 12:08 rust-gdb
-rwxr-xr-x 12 cuser cluster 13974212 Jul 16 12:08 rust-lldb
-rwxr-xr-x 12 cuser cluster 13974212 Jul 16 12:08 rustup

cuser@node00:/Projekt/pd $ file /home/cuser/.cargo/bin/cargo
/home/cuser/.cargo/bin/cargo: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.101, with debug_info, not stripped

**Comment by kinnison** [comment]
My guess is that the install script got confused by a 64bit kernel and 32bit userland, fetched the 32bit rustup (correct) but that looked at your uname and chose to install aarch64 tooling (incorrect)

I suggest the following:

```shell
$ rustup toolchain uninstall stable
$ rustup set default-host armv7-unknown-linux-gnueabihf
$ rustup toolchain install stable --profile minimal
```
Hopefully that'll fix your immediate issue.  Subsequently we need to perhaps implicitly add an appropriate --default-host to the invocation if the userland mismatches the kernel.

**Comment by 68CodingMonkeys** [comment]
I tried this:

cuser@node00:/Projekt $ rustup toolchain uninstall stable
info: uninstalling toolchain 'stable-aarch64-unknown-linux-gnu'
info: toolchain 'stable-aarch64-unknown-linux-gnu' uninstalled
cuser@node00:/Projekt $ rustup set default-host armv7-unknown-linux-gnueabihf
cuser@node00:/Projekt $ rustup toolchain install stable --profile minimal
info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
info: latest update on 2021-06-17, rust version 1.53.0 (53cb7b09b 2021-06-17)
info: downloading component 'cargo'
info: downloading component 'rust-std'
 18.8 MiB /  18.8 MiB (100 %)   5.6 MiB/s in  4s ETA:  0s
info: downloading component 'rustc'
 84.0 MiB /  84.0 MiB (100 %)   5.5 MiB/s in 20s ETA:  0s
info: installing component 'cargo'
  5.5 MiB /   5.5 MiB (100 %)   5.0 MiB/s in  1s ETA:  0s
info: installing component 'rust-std'
 18.8 MiB /  18.8 MiB (100 %)   4.6 MiB/s in  4s ETA:  0s
info: installing component 'rustc'
 84.0 MiB /  84.0 MiB (100 %)   4.8 MiB/s in 20s ETA:  0s
  2 IO-ops /   2 IO-ops (100 %)   0 IOPS in  9s ETA: Unknown

  stable-armv7-unknown-linux-gnueabihf installed - rustc 1.53.0 (53cb7b09b 2021-06-17)

info: checking for self-updates
cuser@node00:/Projekt $ cargo --version
info: syncing channel updates for 'stable-aarch64-unknown-linux-gnu'
info: latest update on 2021-06-17, rust version 1.53.0 (53cb7b09b 2021-06-17)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: installing component 'rust-std'
info: installing component 'rustc'
error: command failed: 'cargo': No such file or directory (os error 2)

There seems to be always a way where rust can get mislead and install the wrong files.

**Comment by kinnison** [comment]
Aah it has cached the old default toolchain, you'll also need `rustup default stable-armv7-unknown-linux-gnueabihf` to switch that.

**Comment by 68CodingMonkeys** [comment]
This seems to work:

cuser@node00:/Projekt $ rustup default stable-armv7-unknown-linux-gnueabihf 
info: using existing install for 'stable-armv7-unknown-linux-gnueabihf'
info: default toolchain set to 'stable-armv7-unknown-linux-gnueabihf'

  stable-armv7-unknown-linux-gnueabihf unchanged - rustc 1.53.0 (53cb7b09b 2021-06-17)

cuser@node00:/Projekt $ cargo --version
cargo 1.53.0 (4369396ce 2021-04-27)

**Comment by kinnison** [comment]
I think this is resolved.  If not, please reopen and explain what's left to resolve.
