### ISSUE TITLE
The CC variable is never asked explicitly.

### ISSUE THREAD

**Issue by lhp22** [rust-lang/rustup#2830]
Hello there,

I've just tried to compile rustup from sources, because of some weird avaibility problems on Guix distribution. All the prerequisites were installed. I've had to set up the OPENSSL_DIR to '/gnu/store/xxx-openssl-1.1.1k'. And this was the right.

And I get this message (in ideas, didn't copy the message at this moment) : "Problem to find tool. Is 'cc' installed ?", and after this line, I was getting explanations about how to install libssl (no matter its name along the distros), and telling me to set up the 'OPENSSL_DIR', what I've had just done. (The error message had just changed, so I knew it was the correct setting.)

Indeed, what I just needed to do was to set up 'export CC=gcc', but that never was explicitly mentionned in the debug messages.

That sounds good to add 'Set up the environment variable CC to your C compiler' after the 'Is 'cc' installed ?'

Thanks for your work.

**Comment by jyn514** [comment]
@lhp22 you should report this to the openssl crate (https://github.com/sfackler/rust-openssl). Rustup doesn't control what messages its dependencies print in their build.rs.
