### ISSUE TITLE
error: toolchain 'nightly-x86_64-pc-windows-msvc' is not installed

### ISSUE THREAD

**Issue by Victor-Lazzarini** [rust-lang/rustup#2846]
Hello I´m quite new in rust but i want to run this **rustup component add rust-src --toolchain nightly
rustup target add wasm32-unknown-unknown --toolchain nightly** but it shows me this message 
: **error: toolchain 'nightly-x86_64-pc-windows-msvc' is not installed**
i would appreciate if u guys can help me
rust version : 1.24.3
****

**Comment by ehuss** [comment]
Before installing a component or target, you need to install the toolchain.  `rustup toolchain install nightly-x86_64-pc-windows-msvc` can be used to install the toolchain.  There is more information about how to use rustup in the [rustup book](https://rust-lang.github.io/rustup/index.html).

Questions like these are best asked on one of the forums, such as [urlo](https://users.rust-lang.org/).

**Comment by Victor-Lazzarini** [comment]
oh thanks it was that, sorry i know is too basic
