### ISSUE TITLE
Feature request: add User-Agent header to http requests

### ISSUE THREAD

**Issue by jiegec** [rust-lang/rustup#2860]
**Describe the problem you are trying to solve**

Hi rustup developers, currently the requests sent by rustup do not include `User-Agent` header. It should include something like `rustup/v1.24.3` or something.

The background is, we are mirroring rustup at https://mirrors.tuna.tsinghua.edu.cn/rustup and we are blocking requests without user-agent headers.

**Describe the solution you'd like**

Set `User-Agent` header in curl and reqwest backend.

**Notes**

**Comment by takkuumi** [comment]
same. rust-static is very slowly in china, i use tuna or ustc mirror, it's broken in last week.
