### ISSUE TITLE
[Asking for advice] How did you set up so that sh.rustup.rs points to the installer script (rustup-init.sh)?

### ISSUE THREAD

**Issue by Martinsos** [rust-lang/rustup#2866]
Hi,
I am author of https://github.com/wasp-lang/wasp and I am trying to set it up so that https://get.wasp-lang.dev points to our installer script (https://raw.githubusercontent.com/wasp-lang/wasp/master/waspc/tools/install.sh), however I am having trouble figuring how to get that working -> I managed to set it up for http://get.wasp-lang.dev (http, not https) via NameCheap URL Redirect but that is not a good solution due to no SSL, and the same method doesn't function for https.

I saw that you got https://sh.rustup.rs working well, so any insights into how to set this up would mean a lot!

Thanks.

**Comment by kinnison** [comment]
Sorry this took so long to get to - you should talk to the infrastructure team if you want to know how that stuff is done - they can be found on the rust-lang zulip instance  <https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra>

**Comment by Martinsos** [comment]
Awesome, thank you!
