### ISSUE TITLE
[WINDOWS] rustup installation fails because "not enough diskspace" while having hundreds of GBs free to use!

### ISSUE THREAD

**Issue by TheOnlyArtz** [rust-lang/rustup#2870]
Hey, I'm trying to install any channel using rustup and getting weird behavior 
```
PS D:\Users\xxx> & '.\rustup-init (1).exe' -y --default-toolchain nightly
info: profile set to 'default'
info: default host triple is i686-pc-windows-msvc
info: syncing channel updates for 'nightly-i686-pc-windows-msvc'
info: latest update on 2021-10-19, rust version 1.58.0-nightly (bd41e09da 2021-10-18)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 17.9 MiB /  17.9 MiB (100 %)   4.0 MiB/s in  4s ETA:  0s
info: downloading component 'rust-std'
 22.5 MiB /  22.5 MiB (100 %)   4.2 MiB/s in  5s ETA:  0s
info: downloading component 'rustc'
 64.5 MiB /  64.5 MiB (100 %)   4.0 MiB/s in 16s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
  5.7 MiB /  17.9 MiB ( 32 %) 171.2 KiB/s in  8s ETA:  1m 12s
info: rolling back changes
error: failed to extract package (perhaps you ran out of disk space?): Access is denied. (os error 5)

```

Output of `rustup --version`:
```
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
```
Output of `rustup show`:
```
Default host: i686-pc-windows-msvc
rustup home:  C:\Users\xxx\.rustup

no active toolchain
```
This is the capacity I work with:
![image](https://user-images.githubusercontent.com/30025874/137860152-1b4f0b89-c63b-4907-81db-407934674277.png)

**Comment by kinnison** [comment]
This feels like a virus scanner is getting in the way - the error is actually `Access Denied`

If you can pause the virus scanner during the toolchain install and then reenable it (and scan the newly installed toolchain) then it likely will work better.  Windows virus scanners are notoriously awful and break a *LOT* of IO.

**Comment by kinnison** [comment]
We think this is likely due to `rustup` simply being too good at IO and the virus scanner / whatever not being able to keep up.  I suggested on Discord that the OP tried `--profile minimal` to just get the toolchain installed and that worked, so for now this is resolved.

If anyone encounters similar in the future, please try the minimal profile first.
