### ISSUE TITLE
Just did a rustup self update + rustup update in a WSL 1 instance, no issues.

### ISSUE THREAD

**Issue by nazmul91977** [rust-lang/rustup#2871]
Just did a rustup self update + rustup update in a WSL 1 instance, no issues.

```
robertc@lifelesstr2:~$ rustup self update
info: checking for self-updates
info: downloading self-update
info: rustup updated successfully to 1.21.1
robertc@lifelesstr2:~$ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2020-02-27, rust version 1.41.1 (f3e1a954d 2020-02-24)
info: downloading component 'rustc'
 58.0 MiB /  58.0 MiB (100 %)  11.7 MiB/s in  5s ETA:  0s
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: downloading component 'rls'
info: downloading component 'rust-src'
info: downloading component 'rust-analysis'
info: downloading component 'clippy'
info: downloading component 'rustfmt'
info: removing previous version of component 'rustc'
info: removing previous version of component 'rust-std'
info: removing previous version of component 'cargo'
info: removing previous version of component 'rust-docs'
info: removing previous version of component 'rls'
info: removing previous version of component 'rust-src'
info: removing previous version of component 'rust-analysis'
info: removing previous version of component 'clippy'
info: removing previous version of component 'rustfmt'
info: installing component 'rustc'
 58.0 MiB /  58.0 MiB (100 %)  10.3 MiB/s in 10s ETA:  0s
info: installing component 'rust-std'
 17.7 MiB /  17.7 MiB (100 %)  12.5 MiB/s in  1s ETA:  0s
info: installing component 'cargo'
info: installing component 'rust-docs'
 12.0 MiB /  12.0 MiB (100 %) 459.2 KiB/s in 13s ETA:  0s
info: installing component 'rls'
info: installing component 'rust-src'
info: installing component 'rust-analysis'
info: installing component 'clippy'
info: installing component 'rustfmt'
info: checking for self-updates

  stable-x86_64-unknown-linux-gnu updated - rustc 1.41.1 (f3e1a954d 2020-02-24) (from rustc 1.34.1 (fc50f328b 2019-04-24))

info: cleaning up downloads & tmp directories
```

So I don't think this is WSL1 per se causing the problem. Is it reproducible?

_Originally posted by @rbtcollins in https://github.com/rust-lang/rustup/issues/2245#issuecomment-592806436_

**Comment by nazmul91977** [comment]
> Just did a rustup self update + rustup update in a WSL 1 instance, no issues.
> 
> ```
> robertc@lifelesstr2:~$ rustup self update
> info: checking for self-updates
> info: downloading self-update
> info: rustup updated successfully to 1.21.1
> robertc@lifelesstr2:~$ rustup update
> info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
> info: latest update on 2020-02-27, rust version 1.41.1 (f3e1a954d 2020-02-24)
> info: downloading component 'rustc'
>  58.0 MiB /  58.0 MiB (100 %)  11.7 MiB/s in  5s ETA:  0s
> info: downloading component 'rust-std'
> info: downloading component 'cargo'
> info: downloading component 'rust-docs'
> info: downloading component 'rls'
> info: downloading component 'rust-src'
> info: downloading component 'rust-analysis'
> info: downloading component 'clippy'
> info: downloading component 'rustfmt'
> info: removing previous version of component 'rustc'
> info: removing previous version of component 'rust-std'
> info: removing previous version of component 'cargo'
> info: removing previous version of component 'rust-docs'
> info: removing previous version of component 'rls'
> info: removing previous version of component 'rust-src'
> info: removing previous version of component 'rust-analysis'
> info: removing previous version of component 'clippy'
> info: removing previous version of component 'rustfmt'
> info: installing component 'rustc'
>  58.0 MiB /  58.0 MiB (100 %)  10.3 MiB/s in 10s ETA:  0s
> info: installing component 'rust-std'
>  17.7 MiB /  17.7 MiB (100 %)  12.5 MiB/s in  1s ETA:  0s
> info: installing component 'cargo'
> info: installing component 'rust-docs'
>  12.0 MiB /  12.0 MiB (100 %) 459.2 KiB/s in 13s ETA:  0s
> info: installing component 'rls'
> info: installing component 'rust-src'
> info: installing component 'rust-analysis'
> info: installing component 'clippy'
> info: installing component 'rustfmt'
> info: checking for self-updates
> 
>   stable-x86_64-unknown-linux-gnu updated - rustc 1.41.1 (f3e1a954d 2020-02-24) (from rustc 1.34.1 (fc50f328b 2019-04-24))
> 
> info: cleaning up downloads & tmp directories
> ```
> 
> So I don't think this is WSL1 per se causing the problem. Is it reproducible?
> 
> _Originally posted by @rbtcollins in [#2245 (comment)](https://github.com/rust-lang/rustup/issues/2245#issuecomment-592806436)_

**Comment by nazmul91977** [comment]
https://github.com/rust-lang/rustup/issues/2871#issue-1030212940

**Comment by rbtcollins** [comment]
Spam

**Comment by nazmul91977** [comment]
info: cleaning up downloads & tmp directories

**Comment by nazmul91977** [comment]
robertc@lifelesstr2:~$ rustup self update
