### ISSUE TITLE
PR Builds for macOS aarch64 failing due to xcode-select directory

### ISSUE THREAD

**Issue by wcarss** [rust-lang/rustup#2875]
**Problem**
Builds for macOS aarch64 are failing during the `aarch64-specific items` step, reporting the error `xcode-select: error: invalid developer directory '/Applications/Xcode_12.2.app/Contents/Developer/'`.

**Steps**

1. Open a PR with cosmetic changes (e.g. https://github.com/rust-lang/rustup/pull/2874)
2. It fails in the way described.

**Possible Solution(s)**
My guess is that the latest version of xcode may have changed, and the specified dir doesn't exist anymore. Googling the error brings up stackoverflows of other people experiencing similar issues and suggestions to set the directory to `/Library/Developer/CommandLineTools`.

**Notes**

rustup version and show not relevant for this issue

**Comment by wcarss** [comment]
~~I'll try putting up a PR with the directory I suggested.~~

Actually, going to try just removing the whole xcode-select line, since we might not need to specify using a beta compiler at all anymore. @shepmaster as the original author would likely have way better context!

**Comment by shepmaster** [comment]
> we might not need to specify using a beta compiler at all anymore

seems plausible to me!
