### ISSUE TITLE
Suggested source command fails when $HOME includes whitespace

### ISSUE THREAD

**Issue by ChaiTRex** [rust-lang/rustup#2881]
**Problem**

When following the instructions on https://rustup.rs/, the terminal output says that `source $HOME/.cargo/env` should be run to correct `$PATH` and so on in the current instance of the shell.

If `$HOME` has whitespace in it, this will fail. This is a minor problem when someone is at the terminal, but when rustup is used in an automated install of Rust and the automation script includes `source $HOME/.cargo/env` as instructed, the script will fail.

**Steps**

1. Have a system where `$HOME` has whitespace in it
2. Follow the instructions on https://rustup.rs/
3. At the end, see the message:

       To configure your current shell, run:  
       source $HOME/.cargo/env
4. Get an error when running the suggested command

**Possible Solution(s)**

Change the message to:

    To configure your current shell, run:
    source "$HOME/.cargo/env"

If this is not safe on all supported shells, then the message should differ per shell.

**Notes**

Output of `rustup --version`: `rustup 1.24.3 (ce5817a94 2021-05-31)`
Output of `rustup show`:

    Default host: x86_64-unknown-linux-gnu
    rustup home:  /home/user/.rustup
    
    installed toolchains
    --------------------
    
    stable-x86_64-unknown-linux-gnu (default)
    beta-x86_64-unknown-linux-gnu
    nightly-x86_64-unknown-linux-gnu
    
    active toolchain
    ----------------
    
    stable-x86_64-unknown-linux-gnu (default)
    rustc 1.56.0 (09c42c458 2021-10-18)

**Comment by kinnison** [comment]
So many pieces of software fail if `$HOME` (and/or usernames) contain spaces that I'm not too worried that we also have this problem.  We do set the source instruction properly in the RC file updates we write out (quote it, though it'll fail if someone tries to put double-quotes in the RUSTUP home etc.)

I think if someone has a space in their home directory path they'll know what to do in this instance.  If you really feel this needs to be fixed then please feel free to supply a PR to change the message.
