### ISSUE TITLE
Rustup --version is so slow

### ISSUE THREAD

**Issue by carlosala** [rust-lang/rustup#2892]
**Problem**

The command `rustup --version` is so slow (70ms, compared to 2ms of `rustup --help | head -n 1` that has the same output.
**Steps**

1. Run `rustup --version

**Notes**

Output of `rustup --version`: `rustup 1.24.3 (ce5817a94 2021-05-31)`
Output of `rustup show`:
```
Default host: x86_64-unknown-linux-gnu

stable-x86_64-unknown-linux-gnu (default)
rustc 1.56.1 (59eed8a2a 2021-11-01)
```

**Comment by kinnison** [comment]
In addition to telling you `rustup`'s version `rustup --version` also determines your current toolchain, loads and validates the manifest for that toolchain, and then runs the compiler to find the `rustc` version for that.  As such it's expected it will take longer.

Can you please explain *why* this "is so slow" and as such is a problem for you?

**Comment by carlosala** [comment]
There is a [zsh plugin](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/rustup) that uses the `rustup --version` command to automate the completions generation. Now we are going to use `rustup --help | head -n 1` to improve the time that takes zsh to open when using this plugin.
I just posted this issue to inform you, just because maybe this was a bug.
Thanks for the answer!

**Comment by kinnison** [comment]
@carlosala is there a reason you don't just use `rustup completions zsh` and source that into your shell?

**Comment by carlosala** [comment]
Yes! To automate the update of completions with newer versions of the command :)

**Comment by rbtcollins** [comment]
On Mon, 8 Nov 2021 at 19:21, Carlo Sala ***@***.***> wrote:

> Yes! To automate the update of completions with newer versions of the
> command :)
>
>
I don't understand what this means.

Does it mean detecting when rustup has been updated to refresh the
completions? Or something else?

If detecting when rustup has been updated, perhaps zsh should cache the
output of the completions command and just re-run it periodically, detect
changes on that and then update if appropriate. The completions command is
effectively static from rustup - so should be fast to generate.

**Comment by carlosala** [comment]
This means that the version is cached in a file, and if the version changes, reload the completions file. Doing this, we can have completion file personalized to the user's version of the tool.

I tried with hyperfine `rustup completions zsh` and `rustup completions zsh cargo` and it's really fast, just a couple of ms. It looks like, in this case, should be a better option to just rerun the completions generator on every init instead of compairing the version number of the tool.
