### ISSUE TITLE
Panic while cleaning up cached downloads

### ISSUE THREAD

**Issue by Alexendoo** [rust-lang/rustup#2894]
### Problem

```
info: syncing channel updates for 'nightly-2021-11-04-x86_64-pc-windows-msvc'
info: latest update on 2021-11-04, rust version 1.58.0-nightly (baba6687d 2021-11-03)
info: downloading component 'cargo'
info: downloading component 'llvm-tools-preview'
info: downloading component 'rust-src'
info: downloading component 'rust-std'
info: downloading component 'rustc'
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: cleaning up cached downloads

Caused by:
    The system cannot find the file specified. (os error 2)', download\src\lib.rs:130:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Steps

I got this panic when rustup automatically installed the toolchain from [this toolchain file](https://github.com/rust-lang/rust-clippy/blob/94517d397c3812d6b8064078a5b494b9f7a79df7/rust-toolchain)

```toml
[toolchain]
channel = "nightly-2021-11-04"
components = ["llvm-tools-preview", "rustc-dev", "rust-src"]
```

Unfortunately I can't reproduce it, I removed and tried installing it again but this time it succeeded

### Rustup version

```console
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.58.0-nightly (baba6687d 2021-11-03)`
```

### Installed toolchains

```console
installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-2021-01-29-x86_64-pc-windows-msvc
nightly-2021-10-21-x86_64-pc-windows-msvc
nightly-2021-11-04-x86_64-pc-windows-msvc
nightly-2021-11-07-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

nightly-2021-11-04-x86_64-pc-windows-msvc (overridden by '.....\clippy\rust-toolchain')
rustc 1.58.0-nightly (baba6687d 2021-11-03)
```

**Comment by kinnison** [comment]
My **guess** which it will be hard to confirm or refute after the fact is that you had two rustups running at once.  Perhaps you had an IDE open on the codebase?  Without a traceback we can't be certain, but that line is not great either way.  We could change the remove_file call there to combine in its error if it happens, though that'd still have failed the install, it would have been slightly less scary.

If you cannot reproduce this, then my guess stands.  If you'd like to submit a patch to ensure that both errors (the download error *and* the remove_file error) then I'd love to see it.

**Comment by Alexendoo** [comment]
I think you're right, I did have rust_analyzer running and it would have been shortly after a git pull that updated the toolchain file to a new nightly. I'll submit a PR to avoid the panic
