### ISSUE TITLE
`rustup which` can panic if asking about an uninstalled toolchain

### ISSUE THREAD

**Issue by rylev** [rust-lang/rustup#2903]
### Problem

`rustup which cargo --toolchain=$TOOLCHAIN` panics with cryptic message when the toolchain in question is not installed. 

### Steps

1. Ensure the nightly toolchain is *not* installled 
2. Run `rustup which cargo --toolchain=nightly`
3. A panic will occur `thread 'main' panicked at 'binary not found', src/cli/rustup_mode.rs:1053:6`

### Possible Solution(s)

Instead of panicking, a nicer error message could be displayed saying that the toolchain in question is not installed. 

### Rustup version

```console
rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
```

### Installed toolchains

```console
Default host: x86_64-apple-darwin
rustup home:  /Users/ryanlevick/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)

active toolchain
----------------

stable-x86_64-apple-darwin (default)
```

**Comment by 0xPoe** [comment]
Let me try to fix it.
