### ISSUE TITLE
rustup --version tries to install a toolchain

### ISSUE THREAD

**Issue by couchand** [rust-lang/rustup#2904]
### Problem

When in a directory with a `rust-toolchain` file, the command `rustup --version` tries to start installing the specified toolchain.  This seems quite surprising.

### Steps

1. Navigate to a folder with a `rust-toolchain` file.
2. `rustup uninstall` the specified toolchain
3. `rustup --version`

### Rustup version

```console
$ rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
```

### Installed toolchains

```console
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/couch/snap/rustup/common/rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2021-10-05-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.56.1 (59eed8a2a 2021-11-01)
```

**Comment by 0xPoe** [comment]
Duplicate of https://github.com/rust-lang/rustup/issues/1397
