### ISSUE TITLE
[ER] Better help for downloading with complete profile

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rustup#2907]
### Problem you are trying to solve

When I've done "rustup update" on a new computer I've received the warning:

```
warning: downloading with complete profile isn't recommended unless you are a developer of the rust language
```

### Solution you'd like

Rustc has spoiled me, I'm used to often receive error messages/warnings that tell me the problems and "help" to fix it. So I'd like that warning to use few more words to explain me how to download a smaller amount of stuff, assuming probably I'm not a rust lang dev :-)

**Comment by rbtcollins** [comment]
Please feel free to put forward a patch to the docs as a partial fix for bug #2661.

I'm closing this as a duplicate.
