### ISSUE TITLE
Support running rust-gdb as root

### ISSUE THREAD

**Issue by maxwell8888** [rust-lang/rustup#2911]
### Problem you are trying to solve

When developing in C, I debug a running program by attaching to it with `sudo gdb -p <pid>`. My understanding is you have to run gdb as root in order to attach to a process. However, I'm unable to do the same with rust-gdb. `sudo ~/.cargo/bin/rust-gdb -p <pid>` produces the error: `error: no override and no default toolchain set`.

### Solution you'd like

To be able to run rust-gdb as root user.

**Comment by rbtcollins** [comment]
The no override and no default toolchain set error is occuring because you're running rustup installed for your user, from the root user: rustup isn't installed for root.

Possibly we can detect this, but in the meantime, just installing rustup as root should get you sorted.

**Comment by kinnison** [comment]
Another option which, while not something sensibly documented in `rustup` since it's a property of the `rust-gdb` file which comes from the https://github.com/rust-lang/rust repo, would be to set `RUST_GDB='sudo gdb'` in your environment, e.g.:

```console
myproject$ env RUST_GDB="sudo gdb" rust-gdb target/debug/myproject
....
attach $PID
```

**Comment by maxwell8888** [comment]
@kinnison thanks for the suggestion, it does successfully open rust-gdb, but I don't think it's working correctly since there doesn't seem to be any pretty printing and when it starts there is the error:
```
Traceback (most recent call last):
  File "/home/max/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/etc/gdb_load_rust_pretty_printers.py", line 2, in <module>
    import gdb_lookup
ModuleNotFoundError: No module named 'gdb_lookup'
```
A user on reddit suggested running `sudo rustup install stable` as an alternative to reinstalling rustup as root. Is this a good work around?

**Comment by rbtcollins** [comment]
> A user on reddit suggested running `sudo rustup install stable` as an alternative to reinstalling rustup as root. Is this a good work around?

That is installing rustup as root.

rustup installs per-user.
