### ISSUE TITLE
Confusing error message when no default toolchain is set, and `rustup` is invoked as `rustc` or `cargo`

### ISSUE THREAD

**Issue by K900** [rust-lang/rustup#2915]
### Problem you are trying to solve

I'm a new user (not really, but bear with me) who just installed rustup from my distribution's repository, and don't have a toolchain selected yet. I try to run `cargo new` to create my first Rust project, and see `error: no override and no default toolchain set`. Confusion ensues.

### Solution you'd like

An error message that clearly says:
- this is an error in rustup
- the error is not unexpected
- how to resolve the error

I'd probably word it something like this:

```
rustup error: you are trying to run [$0], but have not selected a toolchain to use. Run `rustup default stable` to download the latest stable release of Rust and set it as your default toolchain, or create a `rust-toolchain.toml` file for your project. For more information, see [some link to the documentation].
```

**Comment by K900** [comment]
For a little more context, this is actually something a first time Rust user ran into over at #rust:matrix.org, in the context of building a Rust package for Arch Linux. The error log looked like this:

![image](https://user-images.githubusercontent.com/386765/144498538-1b518fb2-af05-48d2-a6ec-5d0be1e8b684.png)

The messages prefixed `==>` originate in `makepkg`, the package build tool, and the messages prefixed `error:` (except the Rustup one) originate in `paru`, a wrapper that automates downloading and building packages from the Arch User Repository (read: a big pile of crowdsourced build specs). The Rustup error is completely lost in the noise, and the user themselves attributed it to `paru` initially.

**Comment by rbtcollins** [comment]
I wonder if we can do better than a better message.

Like: we know when rustup is a distro built rustup. 

This gives us a few options:
- we could install rust just-in-time when (no rust version && no default && is-distro-rustup)
- we could go into rustup-init mode when (no rust version && no default && is-distro-rustup)

What do you think?

**Comment by K900** [comment]
Going into the interactive rustup-init mode is definitely not the best idea, because it's very possible that we're in some form of a headless environment, or something resembling a headless environment (e.g. a build script as mentioned above). Installing just in time might be a good option, but I feel like this is something that should be discussed with distro maintainers. Either way, I'd say we can improve the error first, even if it's a band-aid, and then work towards a better solution.

**Comment by rbtcollins** [comment]
We can certainly do things in parallel; I've done a review of the patch - broadly ok but I have some suggested tweaks.

I agree that interactive prompt is likely to be a messy situation. 

A third option:
* consult isatty, then if a tty go interactive otherwise just DWIM install stable [if not installed] and use it
