### ISSUE TITLE
Versions are not normalized / downloaded twice

### ISSUE THREAD

**Issue by crepererum** [rust-lang/rustup#2918]
### Problem

Rustup doesn't seem to notice that version `1.57` and `1.57.0` are (at least currently) the same version and downloads them twice. This is a bit wasteful when a project specifies the following `rust-toolchain.toml`:

```toml
[toolchain]
channel = "1.57"
```

and uses the `docker.io/library/rust:1.57` image during CI. The rust compiler will then be downloaded twice.

### Steps

```console
$ docker run --rm -it docker.io/library/rust:1.57
root@e8e8bf4ae86e:/# echo $RUST_VERSION
1.57.0
root@e8e8bf4ae86e:/# rustup install 1.57.0
info: syncing channel updates for '1.57.0-x86_64-unknown-linux-gnu'

  1.57.0-x86_64-unknown-linux-gnu unchanged - rustc 1.57.0 (f1edd0429 2021-11-29)

info: checking for self-updates
root@e8e8bf4ae86e:/# rustup install 1.57
info: syncing channel updates for '1.57-x86_64-unknown-linux-gnu'
info: latest update on 2021-12-02, rust version 1.57.0 (f1edd0429 2021-11-29)
info: downloading component 'cargo'
info: downloading component 'rust-std'
 24.9 MiB /  24.9 MiB (100 %)  20.4 MiB/s in  1s ETA:  0s
info: downloading component 'rustc'
 53.9 MiB /  53.9 MiB (100 %)  20.3 MiB/s in  2s ETA:  0s
info: installing component 'cargo'
info: installing component 'rust-std'
 24.9 MiB /  24.9 MiB (100 %)  16.4 MiB/s in  1s ETA:  0s
info: installing component 'rustc'
 53.9 MiB /  53.9 MiB (100 %)  19.6 MiB/s in  2s ETA:  0s

  1.57-x86_64-unknown-linux-gnu installed - rustc 1.57.0 (f1edd0429 2021-11-29)

info: checking for self-updates
root@e8e8bf4ae86e:/# rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.57.0 (f1edd0429 2021-11-29)`
```

Note that:

1. rustup knows that the image contains `1.57.0`
2. rustup seems to think that `1.57` is a different version and downloads it again
3. rustup actually shows the same exact version and hash (`rust version 1.57.0 (f1edd0429 2021-11-29)`) for both, so one could assume that it also knows that the versions are indeed identical
4. Docker image tag are normalized (e.g. `1.57` and `1.57.0` point to the same image with `RUST_VERSION=1.57.0`)

### Possible Solution(s)

rustup uses the exact version (`rust version 1.57.0 (f1edd0429 2021-11-29)`) to address toolchains? I don't really know the internals though.

### Rustup version

```console
rustup 1.24.3 (ce5817a94 2021-05-31)
```

### Installed toolchains

```console
Default host: x86_64-unknown-linux-gnu
rustup home:  /usr/local/rustup

installed toolchains
--------------------

1.57-x86_64-unknown-linux-gnu
1.57.0-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

1.57.0-x86_64-unknown-linux-gnu (default)
rustc 1.57.0 (f1edd0429 2021-11-29)
```

**Comment by rbtcollins** [comment]
Duplicate with #2611 I think
