### ISSUE TITLE
rust-docs for aarch64-apple-darwin

### ISSUE THREAD

**Issue by krionbsd** [rust-lang/rustup#2931]
### Problem you are trying to solve

It seems there are no rustup-docs available on aarch64-apple-darwin arch, it would be nice to add them

### Solution you'd like

Add rustup-docs for aarch64-apple-darwin stable and nightly

**Comment by ehuss** [comment]
I have posted https://github.com/rust-lang/rust/pull/92622 to fix this.

For now, you have a few options:

* Manually download via https://static.rust-lang.org/dist/rust-docs-nightly-aarch64-apple-darwin.tar.gz
* Use the docs from another target like x86_64-apple-darwin
* Use the online docs

**Comment by krionbsd** [comment]
thanks for fixing it @ehuss
