### ISSUE TITLE
Get the Rust version for a specific directory

### ISSUE THREAD

**Issue by TonalidadeHidrica** [rust-lang/rustup#2934]
### Problem you are trying to solve

If we run `rustc --version` for a directory when the version specified in e.g. `rust-toolchain` is not installed, `rustup` automatically downloads the version.

### Solution you'd like

It's better to have a way to obtain the Rust version that would be used for current working directory (or any other directory) without obtaining actual binary.

### Notes

This would be especially useful for shell extensions that shows the current Rust version.  The real-world examples are:

- [starship](https://github.com/starship/starship/blob/c1f2d345aac0b0241ea1b6d99977fea20fa3f5bb/src/modules/rust.rs#L59-L95), which re-implements the algorithm to resolve the Rust version in order to avoid running anything like `rustup` or `rustc`;
- [tide](https://github.com/IlanCosman/tide) plugin for fish shell, which has a feature to show the Rust version in the prompt, which triggers inevitable download when `cd`-ing to a working directory containing `rust-toolchain` specifying not-currently-installed toolchain

**Comment by rbtcollins** [comment]
rustc itself cannot be run without being downloaded - and the proxy doesn't know what version an arbitrary binary will output.

We could make `rustup show` work without downloading the toolchain, and there is an open feature request to enable that. Would that be sufficient?

**Comment by TonalidadeHidrica** [comment]
@rbtcollins Yes, making `rustup show` wor without downloading the toolchain will do.

**Comment by TonalidadeHidrica** [comment]
@rbtcollins Which specific ticket requests the feature?

**Comment by TonalidadeHidrica** [comment]
(After two years) I found the issue about this topic, #1397, and by luck it has been closed just three days ago.  So I think I can close the issue, horray!
