### ISSUE TITLE
Fix generation of rustup-setup.sha256 files

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#294]
These files have problems on both unix and windows. On Unix sha256sum is called from a different directory, so the `target/$triple/release` paths are coded into the file. These should be generated by `cd`-ing into the directory first.

On Windows, they are generated by a powershell script that creates files that can't be validated by sha256sum.

Probably easiest to just emit a little sha256sum exe in Rust to use for this since it's so surprisingly difficult to do across platforms.

**Comment by Diggsey** [comment]
@brson Is this still a thing?
