### ISSUE TITLE
Windows MSVC: automate installing Visual Studio components

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rustup#2947]
### Problem you are trying to solve

Using Rust for `msvc` toolchains  requires some components from Visual Studio to be installed: However, this requires the user to download the vs installer and select the correct components. This can be a source of friction for new users.

A good, regularly updated, install guide would help but it'd be great if rustup itself could ease the install process.

### Solution you'd like

I would suggest this workflow:

* If Visual Studio is not installed at all then offer to download and install the Community Edition with the required components.
* If Visual Studio is installed but is missing the required components, offer to install what is needed.

Alternatively rustup could just do the second bullet point. The user would have to manually install Visual Studio but rustup would be able to fix anything missed by the user. In any case, this might be a good first step if this feature request is accepted.

### Notes

Rustup already has logic to prompt the user to install Visual Studio if necessary.

The Visual Studio installer can be downloaded by using winget (if installed) or via `https://aka.ms/vs/17/release/vs_community.exe`.

The install can be [automated](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2022) using command line arguments. It can be run either with a GUI (where rustup can set the components to be installed by default) or in "quiet" mode without a GUI or user interaction. In the latter case, the [license terms](https://visualstudio.microsoft.com/license-terms/) would need to be linked by rustup itself.

If Visual Studio is installed but components are missing then [`vswhere`](https://github.com/Microsoft/vswhere#visual-studio-locator) can be used to find the existing installer, which in turn can be used to install missing components. Fortunately Visual Studio installs vswhere to a stable location so this should be easy to find. Alternatively there is a COM interface that can be used to query Visual Studio directly. This is what [cc-rs](https://github.com/alexcrichton/cc-rs) uses internally so perhaps features could be added to that crate to support this use case.

**Comment by kinnison** [comment]
This sounds like a very clever way to deal with this.  If you think you can drive this functionality forward then it would be nice to have; though I don't know how easily we'd be able to CI this.

**Comment by ChrisDenton** [comment]
A simple improvement to start with might be to update the instructions to tell the user how to run the Visual Studio Installer from the command line with the C++ workload pre-selected. For example:

Using winget:

```cmd
winget install --id Microsoft.VisualStudio.2022.Community --override "--add Microsoft.VisualStudio.Workload.NativeDesktop;includeRecommended --focusedUi --wait"
```

If winget is not available then powershell can be used:

```powershell
Invoke-WebRequest https://aka.ms/vs/17/release/vs_community.exe -OutFile "$env:TEMP\vs_community.exe"
&"$env:TEMP\vs_community.exe" install --add "Microsoft.VisualStudio.Workload.NativeDesktop;includeRecommended" --focusedUi
rm "$env:TEMP\vs_community.exe"
```

The availability of winget could be probed by rustup by attempting to run `winget --version`.

**Comment by kinnison** [comment]
Certainly sounds like an approach - kinda hard to test for me, but perhaps someone with experience spooling up windows VMs will be able to give this a go.  I'll be around here and on Discord if someone wishes to tackle this.

**Comment by ChrisDenton** [comment]
Ok, so based on feedback to #2954 the following issues were identified:

* The VS installer can sometimes return non-zero exit codes when the install completed successfully but there are warnings such as a reboot needing required. In this case rustup would unceremoniously exit. Fixed by #3004.
* Rust needs the VS English language pack to be installed in order to get the rustc linker output messages right. Fixed by #3006
* We should be more upfront about the Community edition license and force users to actively choose the option rather than have it be the default. This is to help prevent enterprise users from accidentally violating the license. Fixed by #3008.

**Comment by dalance** [comment]
I tried windows installation of rustup v1.25.0.
I expected BuildTools will be installed, but actually Visual Studio was installed.

How about usage of BuildTools installer?
I created https://github.com/rust-lang/rustup/pull/3030.

**Comment by ChrisDenton** [comment]
The problem is the licensing. See https://github.com/rust-lang/rustup/issues/2867

**Comment by dalance** [comment]
I understand it. Thanks.

**Comment by kinnison** [comment]
@ChrisDenton Do you believe this can now be closed?

**Comment by ChrisDenton** [comment]
Yep! If there are any problems it would make sense to track them as new issues.

**Comment by Menelion** [comment]
Sorry but I'm still proposed to install MSVC however I have MSVS 2022 Community. I tried all the possible versions of MSVC and Windows 10 SDK and still no dice, I'm presented with this infamous window. Any ideas please? 
![image](https://user-images.githubusercontent.com/595597/188521677-32e9f5f5-a7f3-4fd1-bcea-ead91db6ef37.png)
