### ISSUE TITLE
Rustup currently takes a `git` dependency

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rustup#2961]
### Problem

At the moment, `rustup` takes a `git` dependency on the `home` crate:

https://github.com/rust-lang/rustup/blob/f363bfe0b46670fbf86908d6622c313d0159b54d/Cargo.toml#L38

This makes it harder to build Rustup from source, especially in sandboxed build environments where Git dependencies aren't available.

### Steps

Err, look at `Cargo.toml`?

### Rustup version

```console
rustup 1.24.3 (ce5817a94 2021-05-31)
```

### Installed toolchains

```console
Not relevant.
```

**Comment by kinnison** [comment]
This is related to https://github.com/brson/home/pull/23 which still needs a good outcome for the community

**Comment by rami3l** [comment]
I'm closing this issue as outdated as the situation described above is no longer relevant.

Please feel free to reopen if this is not the case.

Have a nice day :)
