### ISSUE TITLE
error: error: 'sysinfo not supported on this platform' on freebsd

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rustup#2966]
### Problem

Using rustup to download a toolchain results in many warnings:

```
info: syncing channel updates for 'nightly-2022-03-15-x86_64-unknown-freebsd'
info: latest update on 2022-03-15, rust version 1.61.0-nightly (285fa7ecd 2022-03-14)
info: downloading component 'cargo'
info: downloading component 'llvm-tools-preview'
info: downloading component 'rust-src'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustc-dev'
info: installing component 'cargo'
error: error: 'sysinfo not supported on this platform'
info: installing component 'llvm-tools-preview'
error: error: 'sysinfo not supported on this platform'
error: error: 'sysinfo not supported on this platform'
info: installing component 'rust-std'
error: 'sysinfo not supported on this platform'
error: error: 'sysinfo not supported on this platform'
error: error: 'sysinfo not supported on this platform'
```

See eg https://cirrus-ci.com/task/5416630766272512?logs=prepare#L25

### Steps

1. create freebsd vm
2. `rustup toolchain install <some toolchain>`

### Possible Solution(s)

One of:

1. Drop this warning on unsupported platforms.
2. Replace "error: error: " with "warning: " and deduplicate the warning.

### Rustup version

```console
Latest from sh.rustup.rs
```

### Installed toolchains

```console
N/A
```

**Comment by dereckson** [comment]
I can repro:

$ uname -a
$ FreeBSD windriver.nasqueron.org 13.0-RELEASE-p8 FreeBSD 13.0-RELEASE-p8 #0: Tue Mar 15 09:36:28 UTC 2022     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

$ rustup component add rust-src
info: downloading component 'rust-src'
info: installing component 'rust-src'
error: error: 'sysinfo not supported on this platform'

**Comment by up2geek** [comment]
I have the same issue

**Comment by kinnison** [comment]
I believe this should be resolved when we make our next release.

**Comment by kinnison** [comment]
1.25 is now out
