### ISSUE TITLE
rustup binaries vary from readdir order

### ISSUE THREAD

**Issue by bmwiedemann** [rust-lang/rustup#2972]
### Problem

While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds), I found that
our `rustup` package varies from non-deterministic filesystem readdir order that influences the rustup binary machine code.

In the build system I can see variations in
liblzma_sys ...rlib
libzstd_sys ...rlib
rustup_init

### Steps

1. use `disorderfs --shuffle-dirents=yes` or a scratch ext4 filesystem to build rustup twice

### Possible Solution(s)

need to sort relevant source or .o file lists

### Notes

```diff
/usr/bin/rustup differs in assembler output
--- old /usr/bin/rustup (disasm)
+++ new /usr/bin/rustup (disasm)
@@ -1068357,1696 +1068357,126 @@
        jmp    <ZSTD_decompressStream + ofs>
        xchg   %ax,%ax

-ZSTDv07_defaultAllocFunction:
-       mov    %rsi,%rdi
-       jmp    <malloc@plt>
-       nopl   offset(%rax,%rax,1)
-...
+FSEv05_buildDTable:
```

### Rustup version

```console
rustup-1.24.3~0.tar.xz
```

### Installed toolchains

```console
openSUSE Tumbleweed 20220330
rust-1.59.0
```

**Comment by kinnison** [comment]
This is very likely out of our control - that looks like it's *code* which is differing, and that'd be up to the compiler not us.  You should try and discuss this with the `rust-lang/rust` people.

**Comment by kinnison** [comment]
If, after discussion with them, they believe it's the fault of something in `rustup` then please reopen this issue.

**Comment by bmwiedemann** [comment]
Meanwhile I found https://github.com/gyscos/zstd-rs/pull/162 helps and
[liblzma_sys.rlib needs a similar fix](https://github.com/alexcrichton/xz2-rs/issues/100).
So probably not a rust-lang issue.
