### ISSUE TITLE
Set the `default host triple`  of  `x86_64-pc-windows-gnu/rustup-init.exe` to ` x86_64-pc-windows-gnu` 

### ISSUE THREAD

**Issue by wangkirin** [rust-lang/rustup#2976]
### Problem you are trying to solve

Currently，when I use  [https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe](https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe) to  download the `rustup-init.exe`,  the default host triple is `x86_64-pc-windows-msvc`, see the images bellow
![image](https://user-images.githubusercontent.com/12807239/162692074-fb8c7a8c-56a6-42de-8135-c3baa009714c.png)

### Solution you'd like

I know rustup recommand the user to use `x86_64-pc-windows-msvc` version,  But I think if user download the `rustup-init.exe`
 from URL https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe directly , user have already told us they want to use the `x86_64-pc-windows-gnu`  version,  it's better to set the `default host triple`    to ` x86_64-pc-windows-gnu`  . :)

**Comment by rbtcollins** [comment]
I don't think that follows. In fact we are considering removing that binary, if I remember correctly, because of performance from it.

The goal of rustup isn't too have a binary for every possible end user configuration, but rather one for every host it might install on.

Windows...gnu is not a different host in any meaningful way.

Consider eg wasi as another example people might want, but doesn't make sense to encode at the 'this is what you download for rustup' level.

**Comment by wangkirin** [comment]
Hi Robert, Thank you for your expaniation!

> I don't think that follows. In fact we are considering removing that binary, if I remember correctly, because of performance from it.

Do you mean the team is planning to remove the windows version rustup-init?  I am interested about it

**Comment by kinnison** [comment]
No, we won't be removing Windows support for rustup - however we may remove the `-gnu` version of the installer since it's unnecessary.

**Comment by SergioGasquez** [comment]
Hello! Is there any update regarding removing the support of `x86_64-pc-windows-gnu` installer?

**Comment by rbtcollins** [comment]
No update, but since it has no impact on our users, I'm curious why you're asking?

**Comment by SergioGasquez** [comment]
I was doing some tests with `x86_64-pc-windows-gnu`, and expected to have a similar experience as with `msvc` where if you don't have the toolchain installed, `rustup` recognizes it and allows the user to install it. So, I was about to fill an issue for this request and found this one. 

Is there any chance that we could get that feature? Shall I open an issue?

**Comment by rami3l** [comment]
Closing this in favor of #1851.
