### ISSUE TITLE
cross-compiling from MacOS to Linux experience

### ISSUE THREAD

**Issue by Banyc** [rust-lang/rustup#2979]
### Problem you are trying to solve

I want to cross-compile project from MacOS to Linux. I did the following:

```
rustup target add x86_64-unknown-linux-gnu
```

Then,

```
cargo build --release --target=x86_64-unknown-linux-gnu

```

But here is the error:

```
  = note: clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
          ld: unknown option: --as-needed
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Solution you'd like

It would be great if the problem could be solve automatically at `rustup target add` stage.

**Comment by kinnison** [comment]
Unfortunately `rustup` cannot control your system provided toolchains.  We rely on the system to provide chunks of the final toolchain elements, such as linkers, so if your system linker cannot cross-compile to Linux then we can't help you.

It's possible that the Rust users forum will be able to guide you in setting up macos->linux cross compilation, but I'm afraid I wouldn't have the first clue where to start myself.

Good luck.
