### ISSUE TITLE
Apt support

### ISSUE THREAD

**Issue by machinexa2** [rust-lang/rustup#2990]
### Problem you are trying to solve

Rustup should be installed by `apt install rustup` which should automatically uninstall rustc cargo (apt remove rustc cargo)?

### Solution you'd like

Possible?

### Notes

Answer all my comments quesetions one by one

**Comment by machinexa2** [comment]
Does `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` install cargo?

**Comment by machinexa2** [comment]
If not apt install rustup should only remove rustc but cargo becomes obsolete for rustc or something like that so apt install rustup should install cargo ig

**Comment by machinexa2** [comment]
Lets say apt install rustup isn't possible. Then can I have something like ` curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs --dont-modify-path-variable | sh ` or arugments like that?

**Comment by machinexa2** [comment]
oh rustup does install cargo

**Comment by kinnison** [comment]
If you want your distribution to provide `rustup` as a package then we can look to provide help to someone who packages for that distribution.  We are not in the business of providing distro packages though.
