### ISSUE TITLE
rust-doc does not open documentation on browser

### ISSUE THREAD

**Issue by morarafrank** [rust-lang/rustup#2997]
### Problem

When I run rustup doc on ubuntu 22.04, I get the following error message on Firefox browser. 
The issue is that the same command opens the documentation without issues on Chrome.

Access to the file was denied.
The file at /home/morarafrank/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/index.html is not readable.
It may have been removed, moved, or file permissions may be preventing access.

### Rustup version

```console
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.61.0 (fe5b13d68 2022-05-18)`
```

### Installed toolchains

```console
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/morarafrank/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.61.0 (fe5b13d68 2022-05-18)
```

**Comment by ehuss** [comment]
Do you perhaps have Firefox installed from Snap?  Searching around, it looks like there is some kind of confinement system in Snap that prevents processes from accessing files.  It looks like there is some kind of [connections](https://snapcraft.io/docs/snap-confinement) configuration for it.

**Comment by rbtcollins** [comment]
Dupe of #2988 just for snappy.

At this point we have no plans to run an embedded HTML server, so I'm going to close this.

**Comment by morarafrank** [comment]
> Do you perhaps have Firefox installed from Snap? Searching around, it looks like there is some kind of confinement system in Snap that prevents processes from accessing files. It looks like there is some kind of [connections](https://snapcraft.io/docs/snap-confinement) configuration for it.

I've checked my browser and it has a strict snap configuration. how can i change it to say classic or devmode?

**Comment by ghost** [comment]
Getting the path using:
`rustup doc --path`

Outputs:
`/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/index.html`

---

Trying to open docs:
`xdg-open "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/index.html"`

Outputs error:
```
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
WSL Interopability is disabled. Please enable it before using WSL.
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
```
---

Fixed the problem using:
`sudo apt purge wslu`

**Comment by morarafrank** [comment]
> Getting the path using: `rustup doc --path`
> 
> Outputs: `/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/index.html`
> 
> Trying to open docs: `xdg-open "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/index.html"`
> 
> Outputs error:
> 
> ```
> grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
> WSL Interopability is disabled. Please enable it before using WSL.
> grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
> ```
> 
> Fixed the problem using: `sudo apt purge wslu`

this worked for me.
