### ISSUE TITLE
Run ‘source’ command automatically after a successfull installation 

### ISSUE THREAD

**Issue by J-ZhengLi** [rust-lang/rustup#2998]
### Problem you are trying to solve

currently everytime I do a freshly installed rustup on my machine via ssh, I have to manually input `source $HOME/.cargo/env`, could it be an automatic process? since it might be more convenient for more "lazy" people like me🤪. But if there are any drawbacks or security concern please let me know.

### Solution you'd like

Adding the ability to run `source $HOME/.cargo/env` after setup

**Comment by ehuss** [comment]
I do not believe this is possible.  Child processes cannot force their parent shell to set environment variables.

**Comment by rbtcollins** [comment]
We could re-invoke a new child shell, but given installing rustup is a once-per-machine task, I'm not sure the complexity that that will entail and generate is worth it. Scripted machines like containers and VMs can install rustup during the scripted install; actual machines is a 1/[2..4] years sort of thing.

**Comment by J-ZhengLi** [comment]
> I do not believe this is possible. Child processes cannot force their parent shell to set environment variables.

ohhh right...
