### ISSUE TITLE
stable-x86_64-apple-darwin update failed

### ISSUE THREAD

**Issue by surferjeff** [rust-lang/rustup#3001]
### Problem

jeff@MacBook-Pro ~ % rustup update
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: latest update on 2022-05-19, rust version 1.61.0 (fe5b13d68 2022-05-18)
info: downloading component 'rust-std' for 'wasm32-unknown-unknown'
 16.9 MiB /  16.9 MiB (100 %)  10.9 MiB/s in  1s ETA:  0s
info: downloading component 'rls'
info: downloading component 'rust-src'
info: downloading component 'rust-analysis'
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 19.6 MiB /  19.6 MiB (100 %)  10.9 MiB/s in  1s ETA:  0s
info: downloading component 'rust-std'
 25.5 MiB /  25.5 MiB (100 %)  10.9 MiB/s in  2s ETA:  0s
info: downloading component 'rustc'
 53.9 MiB /  53.9 MiB (100 %)  10.4 MiB/s in  5s ETA:  0s
info: downloading component 'rustfmt'
info: removing previous version of component 'rust-std' for 'wasm32-unknown-unknown'
info: removing previous version of component 'rls'
info: removing previous version of component 'rust-src'
info: removing previous version of component 'rust-analysis'
info: removing previous version of component 'cargo'
info: removing previous version of component 'clippy'
info: removing previous version of component 'rust-docs'
info: removing previous version of component 'rust-std'
info: removing previous version of component 'rustc'
info: removing previous version of component 'rustfmt'
info: installing component 'rust-std' for 'wasm32-unknown-unknown'
 16.9 MiB /  16.9 MiB (100 %)  12.6 MiB/s in  1s ETA:  0s
info: installing component 'rls'
info: installing component 'rust-src'
info: rolling back changes
error: could not rename component file from '/Users/jeff/.rustup/tmp/wu9ue953iarn2q14_dir/bk' to '/Users/jeff/.rustup/toolchains/stable-x86_64-apple-darwin/share'
error: could not rename component file from '/Users/jeff/.rustup/tmp/uvma04mfkdyilij9_dir/bk' to '/Users/jeff/.rustup/toolchains/stable-x86_64-apple-darwin/share/doc'
error: could not rename component file from '/Users/jeff/.rustup/tmp/ru7aoffmuodhhrca_dir/bk' to '/Users/jeff/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown'
error: could not create component directory: '/Users/jeff/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc'
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: checking for self-updates

  stable-x86_64-apple-darwin update failed - rustc 1.46.0 (04488afe3 2020-08-24)
     nightly-x86_64-apple-darwin unchanged - rustc 1.63.0-nightly (1fede1753 2022-05-28)

info: cleaning up downloads & tmp directories
jeff@MacBook-Pro ~ % ls /Users/jeff/.rustup/toolchains/stable-x86_64-apple-darwin/share
doc	man	zsh
jeff@MacBook-Pro ~ % cargo -V
cargo 1.46.0 (149022b1d 2020-07-17)
jeff@MacBook-Pro ~ % 

### Steps

Run rustup update

### Notes

Originally reported here:
https://github.com/rust-lang/rls/issues/1777

### Rustup version

```console
jeff@MacBook-Pro code % rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.46.0 (04488afe3 2020-08-24)`
jeff@MacBook-Pro code %
```

### Installed toolchains

```console
jeff@MacBook-Pro code % rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/jeff/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.46.0 (04488afe3 2020-08-24)

jeff@MacBook-Pro code %
```

**Comment by kinnison** [comment]
This kind of thing happens if Rustup's understanding of the installed toolchain gets out of sync with what is actually on the disk (e.g. if an IO error has corrupted a component file or similar).  The only "known fix" right now is to `rustup toolchain uninstall $toolchain && rustup toolchain install $toolchain`.

**Comment by 0xPoe** [comment]
> The only "known fix" right now is to `rustup toolchain uninstall $toolchain && rustup toolchain install $toolchain`.

@surferjeff Did you try this? Does it work?

**Comment by rami3l** [comment]
As there are currently no further actions that can be taken from our side with respect to this issue, I'm closing it now as stale.

Please feel free to reopen if you have more information to provide.

Have a nice day :)
