### ISSUE TITLE
Automatically setup env on fish shell

### ISSUE THREAD

**Issue by xrisk** [rust-lang/rustup#3021]
### Problem you are trying to solve

The installer currently sets up the .profile, .bash_profile and .zshenv files to source "$HOME/.cargo/env”. I would like something similar to be supported for the fish shell as well.

### Solution you'd like

Append a call to "$HOME/.cargo/env-fish” (for example) in the users config.fish

**Comment by johnmatthiggins** [comment]
I would really like to implement this. I was looking through the code base and I found this reference to [non-posix shells](https://github.com/rust-lang/rustup/blob/4c1289b2c3f3702783900934a38d7c5f912af787/src/cli/self_update/shell.rs#L72). Does a potential solution need to be discussed first or should I just take a swing at it?

**Comment by kinnison** [comment]
@johnmatthiggins If you think you can come up with a clean way to integrate for fish then please have a swing at it.  you can ask questions here, or on the #wg-rustup channel on the rust-lang discord and we'll be happy to help.

**Comment by kinnison** [comment]
There is another issue #478 about fish support, and a draft pr #2995 which you might be able to join forces on.

**Comment by rbtcollins** [comment]
Marking as duplicate with #478 - I don't think these are different enough to warrant different conversations
