### ISSUE TITLE
A local build opens the standard library document for undisclosed items

### ISSUE THREAD

**Issue by QingyaoLin** [rust-lang/rustup#3042]
### Problem you are trying to solve

In the past, I was through the online document web site: https://stdrs.dev/nightly/x86_64-pc-windows-gnu/std/, to find something I need to know the internal items (such as: [RawVec](https://stdrs.dev/nightly/x86_64-pc-windows-gnu/alloc/raw_vec/struct.RawVec.html)), but this is extremely inconvenient (I need to consider browser loading etc.), and far less convenient and fast than opening it locally (e.g. `rustup doc --std`),but `rustup doc` supports opening local documents that don't contain unpublished items.

### Solution you'd like

Provides options like `rustup doc --std --document-private-items` for opening Internal Docs locally

### Notes

Construction of reference online documentation: https://stdrs.dev/nightly/x86_64-pc-windows-gnu/alloc/index.html

**Comment by kinnison** [comment]
Rustup can only show documentation provided by the channels.  You would first need to agree with the release team about producing a component containing such documentation; and then once that was being published, you could then install that component with rustup; at that point we could look at providing such a flag to `rustup doc` to access it.

**Comment by QingyaoLin** [comment]
Is there a way to create one myself, and how do I contact the release team

**Comment by kinnison** [comment]
You can talk with the release team on the rust-lang zulip

**Comment by QingyaoLin** [comment]
Although I couldn't reach an agreement with the release team, I talked to them about how to build internal documentation locally. I think we can close this problem. Thank you so much for your help!
