### ISSUE TITLE
rustup 1.25.1: `rustc` can't find a shared object

### ISSUE THREAD

**Issue by brxken128** [rust-lang/rustup#3046]
### Problem

On a fresh install of HardenedBSD (FreeBSD with a few additional security patches), `rustup` is failing to even start. It uses the same package sources and such as FreeBSD, so I assume this issue is reproducible there as well. I can confirm this was working in previous versions of `rustup`.

Running `rustc` alone provides the error `ld-elf.so.1: Shared object "librustc_driver-ec2bf30055f68910.so" not found, required by "rustc"`.

Running `cargo build` provides the same message, but with `error: process didn't exit successfully: rustc -vV (exit status: 1)` also.

I've tried reinstalling `rustup`, and I've tried it as both root and non-root users. I have rebooted multiple times as well.

I have also tried installing `gcc` and even the `rust` package manually, but removed them as they made zero difference.

### Steps

1. Install FreeBSD/HardenedBSD
2. Install `curl`
3. Install `rustup` via `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
4. `rustc`

### Notes

I'm happy to provide any more information to help figure this out! Whether that's testing things, logs, etc.

This could be just down to user-error, and I sincerely apologise if so.

### Rustup version

```console
% rustup --version
rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `(error reading rustc version)`
```

### Installed toolchains

```console
% rustup show
Default host: x86_64-unknown-freebsd
rustup home:  /home/broken/.rustup

stable-x86_64-unknown-freebsd (default)
(error reading rustc version)
```

**Comment by rbtcollins** [comment]
Sounds like `rustup` itself is working? So this is the `rustc` and `cargo` installed *by* rustup is faulty.

Have a look at the rustc libraries with ldd or whatever the BSD equivalent is, and see if you can find anything odd.

Also try installing an older rust - if its a fault in the distribution, then a rust from whenever you had this working last should still work.

**Comment by brxken128** [comment]
> Sounds like `rustup` itself is working? So this is the `rustc` and `cargo` installed _by_ rustup is faulty.
> 
> Have a look at the rustc libraries with ldd or whatever the BSD equivalent is, and see if you can find anything odd.
> 
> Also try installing an older rust - if its a fault in the distribution, then a rust from whenever you had this working last should still work.

I'll give it a shot - it may have just been my install. I had a few other quirks with the system, so I ended up reinstalling from fresh and just restoring my backups. I have not yet tried to get `rustup` working, but if it does work I'll close this (and pin it down to an isolated issue on my end).

EDIT: It works fine on my fresh install, so I'll close this and put it down to an unknown issue on my end.
