### ISSUE TITLE
Rust is difficult to install on distros where /tmp is noexec.

### ISSUE THREAD

**Issue by EvanCarroll** [rust-lang/rustup#3056]
### Problem

The prescribed method to install Rust (from the [Rust install doc here is](https://www.rust-lang.org/tools/install)) is,

```sh
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

This plain doesn't work for me, and that's understandable.

```text
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

info: downloading installer
Cannot execute /tmp/tmp.cIvsb8taML/rustup-init (likely because of mounting /tmp as noexec).
Please copy the file to a location where you can execute binaries and run ./rustup-init.
```

It's right in the diagnosis too,

```text
$ mount | grep -i "/tmp"
/usr/tmpDSK on /tmp type ext4 (rw,nosuid,noexec,relatime,discard) 
```

However, if I download the same script using `-o rust-install.sh` to `curl`

```sh
curl --proto '=https' --tlsv1.2 -sSf -o rust-install.sh https://sh.rustup.rs
```

And then I try to run it (`sh ./rust-install.sh`) I would expect it to give me an argument to set the download directory. It accepts no arguments. Internally it just uses `mktemp`.

### Steps

1. `mount -o remount,noexec /tmp`
2. try to run install rust.

### Possible Solution(s)

Two good solutions would be,

1. allow the user to set the download directory as an argument
2. allow the user to set the path the downloader saves too as an argument.

### Notes

What I'm trying to do create a `cloud-init` script that installs rust nightly for my sandbox config. If I try to set up a sandbox on a machine with `noexec` on `/tmp`, what I have to do currently is parse out the location the downloader saved to from STDERR (in the above it's `/tmp/tmp.cIvsb8taML/rustup-init`) so I can copy it to a location that I can `chmod +x` it and then execute it. This is not ideal: it requires a lot more work to automate then _run this file with this argument_.

### Rustup version

```console
Not installed, fresh.
```

### Installed toolchains

```console
Not installed, fresh.
```

**Comment by rbtcollins** [comment]
You could just download the binary. The shell script only exists to infer things you already know in your automation.

**Comment by EvanCarroll** [comment]
That's a valid point. Since the CURL command that's ran is,

```sh
curl --retry 3 --proto =https --tlsv1.2 --ciphers TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384 --silent --show-error --fail --location https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init --output "$DIR/rustup-init"
```

I guess I can just assume it'll never change and fix the binary to,

* https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init

**Comment by kinnison** [comment]
Or you can acknowledge that the installer needs an exec-compatible temp dir and just set TMPDIR before running the installer.
