### ISSUE TITLE
Not recognizing rust-toolchain.toml 's `channel` value when `rustup override list`?

### ISSUE THREAD

**Issue by FumiyaShibusawa** [rust-lang/rustup#3057]
### Problem

Sorry if it's intentional or already been issued. I thought `rustup override list` respects `rust-toolchain.toml` setting, but it seems not.

With the `rust-toolchain.toml` setting like below,

```toml
[toolchain]
channel = "nightly-x86_64-apple-darwin"
```
`rustup override list` says `no overrides`. But `rustup toolchain list` shows overridden channel, and rustc's version points to nightly properly.
```
% rustup override list
no overrides
% rustup toolchain list
stable-x86_64-apple-darwin (default)
beta-x86_64-apple-darwin
nightly-x86_64-apple-darwin (override)
% rustc --version
rustc 1.64.0-nightly (affe0d3a0 2022-08-05)
```

I'm not sure if this behavior is expected or not, but I couldn't find any docs that mention on this at least.

### Steps

1. install nightly channel by `rustup toolchain install nightly`.

2. create `rust-toolchain.toml` file with the following setting in your working directory.
```toml
[toolchain]
channel = "nightly-x86_64-apple-darwin"
```

3. run `rustup override list` to see which channel overrides the default.

### Possible Solution(s)

As the command itself `rustup override list` shows, it might be natural to search for either `rust-toolchain.toml` or `rust-toolchain` file.

As the function `list_toolchains(cfg: &Cfg, verbose: bool)` which is located in src/cli/common.rs invokes `find_override(&self, path: &Path)` method to find those relevant files, the function `list_overrides(cfg: &Cfg)` could also utilize `find_override` as well. 

If this looks good, I'd like to work on this.

### Rustup version

```console
% rustup --version
rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.64.0-nightly (affe0d3a0 2022-08-05)`
```

### Installed toolchains

```console
% rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/fumiyashibusawa/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
beta-x86_64-apple-darwin
nightly-x86_64-apple-darwin

active toolchain
----------------

nightly-x86_64-apple-darwin (overridden by '/Users/fumiyashibusawa/workspace/private/rust/blog_os/rust-toolchain.toml')
rustc 1.64.0-nightly (affe0d3a0 2022-08-05)
```

**Comment by 0xPoe** [comment]
I tested it locally.
```toml
[toolchain]
channel = "nightly-2022-09-28"
```
```log
➜  foo git:(master) ✗ rustup override list
no overrides
```
```log
➜  foo git:(master) ✗ rustup toolchain list
stable-aarch64-apple-darwin
beta-aarch64-apple-darwin (default)
nightly-2021-07-28-aarch64-apple-darwin
nightly-2022-09-28-aarch64-apple-darwin (override)
nightly-aarch64-apple-darwin
1.59-aarch64-apple-darwin
1.60-aarch64-apple-darwin
1.62-aarch64-apple-darwin
```
You can see the override toolchain. (nightly-2022-09-28-aarch64-apple-darwin)

I also checked our override command help.
```log
➜  foo git:(master) ✗ rustup help override
rustup-override
Modify directory toolchain overrides

USAGE:
    rustup override <SUBCOMMAND>

FLAGS:
    -h, --help    Prints help information

SUBCOMMANDS:
    list     List directory toolchain overrides
```
As you can see it says `List directory toolchain overrides`. So I don't know does it is a good idea to show the `rust-toolchain[.toml]` as a directory toolchain override.

**Comment by FumiyaShibusawa** [comment]
After doing a little search after opening this issue, I just found `rustup override list` only looks for directory overrides (`[overrides]` in `settings.toml`), so as you said on help message, this should stick to directory overrides. Thank you!
