### ISSUE TITLE
Add rust-analyzer and related components to rustup book

### ISSUE THREAD

**Issue by TheButlah** [rust-lang/rustup#3062]
### Problem you are trying to solve

Recently, rust-analyzer became a rust toolchain component, and even more recently its proc macro server became a component. I do not know which component is which and what they are named, because they aren't listed in the [rustup book](https://rust-lang.github.io/rustup/)

### Solution you'd like

Please add all components related to rust analyzer to the rustup book

### Notes

I would do it myself, but I don't know what is what 😅

**Comment by ehuss** [comment]
The documentation will be added as part of #3022.

Can you point me to where the proc macro server became a component? My understanding is that it is part of the `rustc` component.

**Comment by TheButlah** [comment]
I would ask @fasterthanlime

**Comment by fasterthanlime** [comment]
> Can you point me to where the proc macro server became a component? My understanding is that it is part of the `rustc` component.

This is correct. It's shipped as part of the `rustc` component, under `libexec`.

I didn't have anything to do with the `rust-analyzer` component — it changed from a git submodule to a git subtree, but that makes no difference to rustup. It'll still lag behind until someone makes a sync PR to rust-lang/rust (like rustfmt, clippy etc)

**Comment by 0xPoe** [comment]
You can find the rust-analyzer docs in [the devel rustup book.](https://rust-lang.github.io/rustup/devel/concepts/components.html)

After release, it will be [in the rustup book.](https://rust-lang.github.io/rustup/)

**Comment by 0xPoe** [comment]
1.26.0 was released. The docs updated.
