### ISSUE TITLE
Add target riscv64-alpine-linux-musl

### ISSUE THREAD

**Issue by 6543** [rust-lang/rustup#3066]
currently I can not target riscv64 with musl

alpine has some patch that make it possible https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/community/rust
what has to be done to support it?

**Comment by ehuss** [comment]
Rustup isn't responsible for adding new targets. The process for adding a new target is detailed in https://doc.rust-lang.org/rustc/target-tier-policy.html. Roughly, it needs to follow all of those requirements, such as having designated target maintainers, and to open an [MCP](https://forge.rust-lang.org/compiler/mcp.html) where a compiler maintainer needs to review and approve it.

**Comment by 6543** [comment]
thanks for the info :)
