### ISSUE TITLE
nix + symlinked proxies is resulting in wrong argument evaluation

### ISSUE THREAD

**Issue by NilsIrl** [rust-lang/rustup#3072]
### Problem

Cannot use the `rustc` binary to call `rustup` even tho `rustc` is symlinked to rustup

### Steps

1. Have rustc symlink to rustup
2. run

```
$ (exec -a rustup rustc which rustc)
```

### Rustup version

```console
rustup 1.25.1 (1980-01-01)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.63.0 (4b91a6ea7 2022-08-08)`
```

### Installed toolchains

```console
Default host: aarch64-apple-darwin
rustup home:  /Users/nils/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.63.0 (4b91a6ea7 2022-08-08)
```

**Comment by 0xPoe** [comment]
Can I ask you what scenario requires you to use it in this way?

**Comment by NilsIrl** [comment]
I'm trying to build firefox / thunderbird using rustup installed using the nix package manager on MacOS.

Here are is some clarification on what my environment looks like (I'm really just pointing out that everything symlinks to rustup):

```
$ which rustc rustup                                                         
/Users/nils/.nix-profile/bin/rustc
/Users/nils/.nix-profile/bin/rustup
$ ls -althr $(which rustc rustup)
lrwxr-xr-x 1 root wheel 68 Jan  1  1970 /Users/nils/.nix-profile/bin/rustup -> /nix/store/c0j276cbb5jg36k7zf59iya18zfjs3d1-rustup-1.25.1/bin/rustup
lrwxr-xr-x 1 root wheel 67 Jan  1  1970 /Users/nils/.nix-profile/bin/rustc -> /nix/store/c0j276cbb5jg36k7zf59iya18zfjs3d1-rustup-1.25.1/bin/rustc
$ ls -alh /nix/store/c0j276cbb5jg36k7zf59iya18zfjs3d1-rustup-1.25.1/bin/rust{up,c}
lrwxr-xr-x 1 root nixbld   6 Jan  1  1970 /nix/store/c0j276cbb5jg36k7zf59iya18zfjs3d1-rustup-1.25.1/bin/rustc -> rustup
-r-xr-xr-x 1 root nixbld 533 Jan  1  1970 /nix/store/c0j276cbb5jg36k7zf59iya18zfjs3d1-rustup-1.25.1/bin/rustup
```

And `./mach build` to compile firefox / thunderbird, calls the rustc executable with arguments (starting from argument 0): ["rustup", "which", "rustc"]. Because rustc is symlinked to rustup, I would except this to work, but it doesn't.

**Comment by rbtcollins** [comment]
We use process().name() to determine the mode; (rustup-init.rs line 63).

Outside of tests, thats an instance of OSProcess::default(); 

Which is in src/currentprocess.rs - https://github.com/rust-lang/rustup/blob/84e4639e40b98adbe5cea0654310782206f96c93/src/currentprocess.rs#L197

And there is a blanket implementation over Box'd traits that determines the process name:

https://github.com/rust-lang/rustup/blob/84e4639e40b98adbe5cea0654310782206f96c93/src/currentprocess.rs#L113

which as you can see uses args().next()  (if RUSTUP_FORCE_ARG0 is not defined). and finally args() for OSProcess is here - https://github.com/rust-lang/rustup/blob/84e4639e40b98adbe5cea0654310782206f96c93/src/currentprocess/argsource.rs#L14 - so just env::args().

The summary of the bug is thus wrong: rustup *does* use the zeroth argument.

**Comment by rbtcollins** [comment]
I'm not sure whats up here, but even though rustup itself installs things with hardlinks, I don't see any reason why symlinks wouldn't work too.

Please get a strace of the process invocation, and perhaps modify your rustup around https://github.com/rust-lang/rustup/blob/84e4639e40b98adbe5cea0654310782206f96c93/src/bin/rustup-init.rs#L32 to dump env::args().collect::<Vec<_>>() to a file.

**Comment by 0xPoe** [comment]
I tested it on my mac. As @rbtcollins said it works.
```shell
exec -a rustup rustc show
```
```log
➜  rustup git:(master) ✗ ./test.sh
Default host: aarch64-apple-darwin
rustup home:  /Users/hi-rustin/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin
beta-aarch64-apple-darwin (default)
nightly-2021-07-28-aarch64-apple-darwin
nightly-aarch64-apple-darwin

active toolchain
----------------

beta-aarch64-apple-darwin (default)
rustc 1.65.0-beta.1 (2a65764f2 2022-09-19)
```

**Comment by NilsIrl** [comment]
@rbtcollins Yes, that is correct, sorry for the incorrect assumption.

After further investigation, the problem is due entirely to the nix package manager and its use of wrappers.

https://github.com/NixOS/nixpkgs/issues/150841
