### ISSUE TITLE
Having configuration on TLS min version

### ISSUE THREAD

**Issue by 1995parham** [rust-lang/rustup#3079]
### Problem you are trying to solve

I work in a network that only allows TLS v1.3 so is there any configuration similar to what we have on `cargo` for setting the tls version for installing and updating a toolchain?

### Solution you'd like

Having a configuration, for example as an env for setting tls version.

**Comment by 0xPoe** [comment]
Did you mean [this one](https://doc.rust-lang.org/cargo/reference/config.html#httpssl-version)?

**Comment by 1995parham** [comment]
Yes exactly.
