### ISSUE TITLE
Use-cases of disabling self-update?

### ISSUE THREAD

**Issue by amab8901** [rust-lang/rustup#3087]
### Problem you are trying to solve

I'm reading [this](https://rust-lang.github.io/rustup/basics.html#keeping-rust-up-to-date) section. It talks about how you can disable self-update of rustup. Why in the world would you want to disable that? Please explain to me and also add in the documentation

### Solution you'd like

add high-value use-cases of disabling self-update in rustup

**Comment by rbtcollins** [comment]
Thats up to the folk that requested the feature really. As documented already 'obtained from a third-party distributor who has disabled it (such as the Ubuntu snap store).'
