### ISSUE TITLE
winget upgrade for rustup is broken

### ISSUE THREAD

**Issue by remidebette** [rust-lang/rustup#3102]
### Problem

Hi, thank you for the nice tool.

I am installing rustup with winget, which is becoming the de facto tool for managing packages in Windows.

```powershell
❯ winget install --id Rustlang.Rustup
```

My issue is that to this date I cannot seamlessly use the upgrade function of winget due to rustup not been upgraded by the tool:

```powershell
❯ winget upgrade --id Rustlang.Rustup
This package's version number cannot be determined. To upgrade it anyway, add the argument --include-unknown to your previous command.
```
Adding the `--include-unknown` parameter is not a good solution because I am never not in a state where the system is 'up to date'

### Steps

You can see the main reason is that winget is unable to detect the current version of rustup:
```powershell
❯ winget upgrade --include-unknown
Name                                 Id                        Version Available Source
---------------------------------------------------------------------------------------
Rustup: the Rust toolchain installer Rustlang.Rustup           Unknown 1.25.1    winget
```

### Possible Solution(s)

**Expected Behavior:**
The actual version of the currently installed version should appear as so:
```powershell
❯ winget upgrade --include-unknown
Name                                 Id                        Version Available Source
---------------------------------------------------------------------------------------
Rustup: the Rust toolchain installer Rustlang.Rustup           1.25.1  1.25.1    winget
```

**Additional context:**
As explained here: https://github.com/microsoft/winget-cli/issues/1356
The version used by winget is simply the information provided from Control Panel
Apparently, all that is needed is to add a DisplayVersion key in the registry when installing.

See how the Control panel does not see the version:
![image](https://user-images.githubusercontent.com/16523229/199263784-e2c392ca-5464-4aad-9d0b-49287524027f.png)

Here is an example of a program with a version:
![image](https://user-images.githubusercontent.com/16523229/199259329-49293882-c439-48d5-a76a-6c71313d5ee2.png)

### Rustup version

```console
any version

currently I am using 1.25.1
```

### Installed toolchains

```console
Default host: x86_64-pc-windows-msvc

stable-x86_64-pc-windows-msvc (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

**Comment by fbstj** [comment]
microsoft/winget-pkgs#67393 is a corresponding issue in the repository

**Comment by remidebette** [comment]
So this should already be solved by https://github.com/rust-lang/rustup/pull/3047, provided the new version is correctly referenced in the winget registry?

Which version of rustup is expected to have the fix by the way?

**Comment by schlamar** [comment]
Not the current one, as this predates the fix 

```
>rustup --version
rustup 1.25.1 (bb60b1e89 2022-07-12)
```

So this should be fixed with the next rustup release I guess.

**Comment by 0xPoe** [comment]
> So this should be fixed with the next rustup release I guess.

Yes, I think it would be fixed in the next release. Fixed by https://github.com/rust-lang/rustup/pull/3047

**Comment by anarelion** [comment]
Also, we need to provide proper stable URLs for downloads: See microsoft/winget-pkgs#95599

**Comment by gotounix** [comment]
> > So this should be fixed with the next rustup release I guess.
> 
> Yes, I think it would be fixed in the next release. Fixed by #3047

@hi-rustin Is it not fixed in the next version 1.25.2 ?

**Comment by 0xPoe** [comment]
> @hi-rustin Is it not fixed in the next version 1.25.2 ?

It does not. Because `1.25.2` is just a quick fix for a security issue.

**Comment by 0xPoe** [comment]
1.26.0 was released. I suppose this issue should be fixed. I am going to close this issue and if you have more questions please feel free to comment.

**Comment by fbstj** [comment]
indeed v1.26.0 has worked for me
