### ISSUE TITLE
Inaccuracy during install when C++ 2019 not installed

### ISSUE THREAD

**Issue by luckynumberke7in** [rust-lang/rustup#3114]
### Problem you are trying to solve

I was attempting to install Rust using rustup (on win10), the install detected that I didn't have C++ 2019 installed and prompted me to download / install.

In these instructions it gives you 3 options ("Desktop development with C++", one I can't remember (tried to find again on gh), and the barebones "MSVC v142 VS 2019..." and "Windows 10 SDK"

When I selected the 1st option, I noticed none of the "barebones" versions were even selected in this installation version, C++ was giving me C++ 2022 and Windows 11 SDK.

This leads me to 2 questions I need clarification on (and should be implemented in Rustup -- which I would not mind doing! )

What version of C++ do I actually need to install Rust, 2019 still, or can I only install the newest release?

Also, probably not fully a Rust Q but what version SDK(s) should I use? Do I need the win 11 sdk for my app to work on win 11?

My default to be sure it worked was to select both sets, but this lead to over 10gb of installations, which, obviously I don't just want sitting on my machine.

### Solution you'd like

Essentially, update rustup guide for C++ and possibly clarify which version Rust specifically needs.

**Comment by rami3l** [comment]
Let's track this in #2912.
