### ISSUE TITLE
-bash: $RUST_INSTALLATION/env: No such file or directory

### ISSUE THREAD

**Issue by alitariq4589** [rust-lang/rustup#3119]
### Problem

I have installed rust from source on my two computers. Then I changed its path and added it to `PATH` variable. Right now whenever I open my server shell, I get following error every time:  

```
-bash: /home/alitariq/RUST_BUILD_JOB/env: No such file or directory
```  
My `CARGO_HOME` and `RUSTUP_HOME` enviroment variables are also set properly.

### Steps

1. Install rust from source
2. After installation change its path
3. Then you will start getting this prompt (hopefully).

### Possible Solution(s)

Whatever file contains the information regarding `env` environment variable, can be manipulated to get rid of this issue.

### Rustup version

```console
1.25.1
```

### Installed toolchains

```console
riscv64gc-unknown-linux-gnu
x86_64-unknown-linux-gnu
```

**Comment by bjorn3** [comment]
What exactly did you write in your bash configuration? The `env` script is created by rustup. If you don't use rustup, there will be no `env` script. You can modify your `PATH` to point to the `bin` directory in the rust installation instead.

**Comment by rbtcollins** [comment]
I want to know what '1. Install rust from source' means specifically. Building rustc and a toolchain? Building rustup? Running rustup-init.sh ?

**Comment by alitariq4589** [comment]
Hello everyone,
Sorry for not responding to earlier messages. It seems I am busy enough to follow up on this issue, so I am going to close this issue for now.

**Comment by rbtcollins** [comment]
Thanks @alitariq4589 if you have time later you can always come back :)

**Comment by alitariq4589** [comment]
@rbtcollins Sure. I understand
