### ISSUE TITLE
issue installing rustup 1.3 with m1 osx 13

### ISSUE THREAD

**Issue by AvidDabbler** [rust-lang/rustup#3120]
### Problem

I have searched open and closed issues and pull requests for duplicates, using these search terms:
        1.3
        tlsv1.3
        tls
        install
    I have checked the latest main branch to see if this has already been fixed, in this file:
        yes. I have looked [here](https://github.com/rust-lang/book/blob/main/src/ch01-01-installation.md#installing-rustup-on-linux-or-macos)

URL to the section(s) of the book with this problem:

    install script issue - https://github.com/rust-lang/book/blob/main/src/ch01-01-installation.md#installing-rustup-on-linux-or-macos

Description of the problem:

OS: OSX 13
Computer: MBP 2021 M1
Issue:
I just started the install for Rust and when I use 1.3 it produces are curl error. I tried updating curl with homebrew, but same result happened.

error: 

`curl: (4) A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.`

### Steps

1. on mac osx 13 m1 run `curl --proto '=https' --tlsv1.3 -sSf https://sh.rustup.rs | sh` in terminal

### Rustup version

```console
curl: (4) A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.
```

### Installed toolchains

```console
na - have not installed rustup yet
```

**Comment by delsauce** [comment]
I ran into this issue as well.  The install does proceed successfully with `--tlsv1.2.`.  Also running Mac OSX 13 on a Mini, M1 2020 version.

**Comment by sanmai-NL** [comment]
What version of curl are you using? You'd better upgrade to a secure version. See: https://everything.curl.dev/get/macos.

Just as with outdated versions of Bash or Python coming with macOS, you may need to update those tools.

**Comment by allthingsgo** [comment]
hello, I am trying to play with rust-lang on my old iMac desktop ( that only had 128G in total) ... but I have only around 1G space left... and during installation I ran into no space left issue... how BIG is rust-lang installation footprint? thanks for any info. - s.ye

**Comment by sanmai-NL** [comment]
That is not relevant for this issue, and is not an issue but a question. Please ask this on Rustup community fora.

**Comment by rami3l** [comment]
Closed by https://github.com/rust-lang/book/pull/3469.
