### ISSUE TITLE
rustup allows `rustup toolchain link none`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustup#3130]
### Problem

This is not *necessarily* a bug, but it seems very confusing.

```
; rustup default none
info: default toolchain unset
; rustup toolchain link none build/aarch64-unknown-linux-gnu/stage0
; cargo
error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
; cargo +none --version
cargo 1.67.0-beta.3 (f6e737b1e 2022-12-02)
```

### Steps

1. Clone rust-lang/rust and run `./x.py --help
2. Run `rustup toolchain link none build/aarch64-unknown-linux-gnu/stage0` (as appropriate for your host triple)
3. Run `cargo +none --version`

### Possible Solution(s)

I think disallowing `none` for a custom toolchain name would be easier to understand, something like the existing error for reserved channel names:
```
; rustup toolchain link stable build/aarch64-unknown-linux-gnu/stage0
error: invalid custom toolchain name: 'stable-aarch64-unknown-linux-gnu'
```

### Rustup version

```console
rustup 1.25.1 (bb60b1e89 2022-07-12)
```

### Installed toolchains

```console
> rustup show -v
Default host: aarch64-unknown-linux-gnu
rustup home:  /home/gh-jyn514/.local/lib/rustup

installed toolchains
--------------------

error: no default toolchain configured

```
(this seems like a second bug: I definitely have at least nightly installed.)

**Comment by ashutoshvarma** [comment]
@rustbot claim
@jyn514 If I understand right, setting `none` should not be allowed as custom toolchain name and should just simply throw an error?

**Comment by jyn514** [comment]
That's what I would expect, yes.
