### ISSUE TITLE
Error installing Rust

### ISSUE THREAD

**Issue by zx9r** [rust-lang/rustup#3135]
### Problem

> $ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> info: downloading installer
> curl: (23) Failure writing output to destination
> rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init /tmp/tmp.Ovyar546P7/rustup-init x86_64-unknown-linux-gnu
> 

Directory /tmp.Ovyar546P7 exists but it is empty

System is Ubuntu 22.04

### Steps

Enter the curl command as specified in the documentation

### Rustup version

```console
Trying to install yet
```

### Installed toolchains

```console
None
```

**Comment by Ekiben542** [comment]
Download the installer that is right for you and do the following
chmod +x rustup-init
sudo ./rustup-init

**Comment by rbtcollins** [comment]
See #2948
