### ISSUE TITLE
I cannot install Rust

### ISSUE THREAD

**Issue by Ekiben542** [rust-lang/rustup#3138]
### Problem

I cannot install Rust, what should I do?
Command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs/ | sh
Error: rustup-init.sh: 470: /tmp/tmp.Rkor48rS6O/rustup-init: not found
Architecture: armv7l

### Steps

1. run "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs/ | sh

### Rustup version

```console
I can't type commands because I haven't installed it.
```

### Installed toolchains

```console
I can't type commands because I haven't installed it.
```

**Comment by rbtcollins** [comment]
Please see #2948
