### ISSUE TITLE
"Error: could not amend bash profile" when using recommended `sh` install script

### ISSUE THREAD

**Issue by corneliusroemer** [rust-lang/rustup#3158]
### Problem

I am reopening issue #2040 as it seems to be a frequent problem for beginners following the website recommended install script when their home directory is not writable by the current user.

They get the following error, which can be confusing to beginners, see https://stackoverflow.com/questions/71986942/getting-error-could-not-amend-shell-profile-permission-denied-installing-rus/75124246#75124246

```
error: could not amend shell profile: '/Users/builder/.profile'
info: caused by: could not write rcfile file: '/Users/builder/.profile'
info: caused by: Permission denied (os error 13)
```

### Steps

Change permissions of the HOME directory to make it unwritable by the current user

1. Run `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
2. Observe result

### Possible Solution(s)

Check that the home directory is writable and report it to the user with clear actionable recommendations in https://github.com/rust-lang/rustup/blob/master/rustup-init.sh

**Comment by rbtcollins** [comment]
So this is fascinating. What is MacOSX doing that a terminal runs as a different user without write access to HOME?

I mean yes, patches appreciated to error more clearly in rustup-init, but I'd also like to understand what the interaction is thats leading to this situation

**Comment by ea7kir** [comment]
Is there any hope Rust will ever be my language of choice when it won't even install on macOS Monterey 12.6.6 ?  Please fix the install script and/or update the website accordingly.

drwxr-xr-x    2 mike  staff     64 Dec 10  2021 .profile

The script doesn't seem to know that .profile is a directory.

**Comment by rbtcollins** [comment]
@ea7kir I don't have a mac; I'm happy to review patches to the existing script, which you can get from the rustup repository. If you can figure out what is going on, we might even be able to help you fix it.

**Comment by rami3l** [comment]
Please feel free to reopen this if this is not the case, but I believe this problem has been addressed by https://github.com/rust-lang/rustup/pull/3712.
