### ISSUE TITLE
git tag missing for 1.25.2 release

### ISSUE THREAD

**Issue by alex** [rust-lang/rustup#3188]
### Problem

All other releases have a git tag, but the latest one does not.

### Steps

Look at https://github.com/rust-lang/rustup/tags

### Rustup version

```console
1.25.2
```

### Installed toolchains

```console
n/a
```

**Comment by graydon** [comment]
There's also no changelog entry. The only sign that 1.25.2 was released is that the SHA256s changed and there was a blog post.

**Comment by graydon** [comment]
Update: looks like https://github.com/rust-lang/rustup/pull/3190 has this material and is pending a merge. Thanks!

**Comment by 0xPoe** [comment]
> There's also no changelog entry. The only sign that 1.25.2 was released is that the SHA256s changed and there was a blog post.

Now we have the `v1.25.2` tag. Thank you all.
