### ISSUE TITLE
Rustup.rs needs some rust theming for credibility

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rustup#3191]
I hate to open a discussion that I know has the potential to turn into too much bikeshedding, but I think that there could be some improvements done here. Current site:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/13724985/216496656-92f91305-bee3-4791-b092-6a21008fc0db.png">

Barebones is great and not much is needed for the purpose of this site. However: there's no logo, no theme, no links to a "getting started" or usage guide, and imho looks a bit like the result of a modern website when you disable javascript. There just isn't anything that visually suggests "this is an official rust project", to match the text that literally says it.

I am not suggesting large changes, just enough to make it a bit more coherent with other official Rust websites.

To do so, I think rustup.rs could generally match rustdoc, mdbook, rust-lang.org, or foundation.rust-lang.org themes (why do they all have completely different themes...). I think rust-lang.org is the best bet here: https://www.rust-lang.org/tools/install as a basis. From there:

- Keep the fonts
- Slightly shrink the 8rem header
- (maybe) make the install box a large green div to parallel this page
- Keep the logo in the top left
- Add a link to the "getting started" guide so people have somewhere to go after installing

And that's it. No more questioning whether you're on the right website when you visit.

(I don't mind heading something up here if there's no strong opposition)

@rustbot label +website +enhancement

**Comment by rbtcollins** [comment]
By all means, make it nicer. Thanks!

**Comment by akhilesh-w** [comment]
the rust book itself takes you to https://www.rust-lang.org/tools/install, idk many people who use rustup.rs
![image](https://github.com/rust-lang/rustup/assets/77394282/7eed3fb9-5d94-4e1c-a6b0-cd2bd3fd43ce)
