### ISSUE TITLE
aarch64-apple-darwin .pkg file wants Rosetta

### ISSUE THREAD

**Issue by brianolson** [rust-lang/rustup#3197]
### Problem

I have a fresh M1 MacBook and haven't installed Rosetta (x86_64 emulator) and the "[other installation methods](https://forge.rust-lang.org/infra/other-installation-methods.html)" rust-1.67.0-aarch64-apple-darwin.pkg installer asks me to install Rosetta. This shouldn't be necessary, there's probably some stale metadata in pkg generation.

### Steps

1. download latest rust aarch64-apple-darwin pkg to an Apple-Silicon M1* Mac without Rosetta installed
2. double-click the pkg
3. Apple pkg installer asks if you want to install Rosetta

### Possible Solution(s)

redditor notes incorrect metadata
https://www.reddit.com/r/rust/comments/10vzswb/comment/j7kcs7h/?utm_source=share&utm_medium=web2x&context=3

### Rustup version

```console
rust aarch64-apple-darwin 1.67.0
```

### Installed toolchains

```console
rust aarch64-apple-darwin 1.67.0
```

**Comment by rbtcollins** [comment]
I'm not sure where 'other installation methods' are managed, but they aren't managed here in the rustup repo. I suggest moving this bug to the rust repo.

**Comment by brianolson** [comment]
I couldn't find a better repo which appears to have responsibility for packaging up binary rustc and cargo and all that.

**Comment by workingjubilee** [comment]
The standalone installers are produced from an installer built in the main rust-lang/rust repo. Thus the name.

**Comment by fenginsc** [comment]
Even if you use Rosetta, the installation will fail, can't believe no one has found this problem, hope it can be fixed soon.

**Comment by rami3l** [comment]
I'm closing this as out of scope: the .pkg installer is not maintained by the Rustup team, so we can do nothing about it...

I second @workingjubilee on this:

> The standalone installers are produced from an installer built in the main rust-lang/rust repo. Thus the name.
