### ISSUE TITLE
lalrpop incompatibility warning in builds

### ISSUE THREAD

**Issue by rbtcollins** [rust-lang/rustup#3213]
### Problem

lalrpop is throwing an error in builds; https://github.com/lalrpop/lalrpop/issues/701 covers this, and its being multiply re-filed (lalrpop might be abandoned).

Rustup depends on lalrpop indirectly via sequoia-openpgp; fixing the dependency thus means:
-  sequoia fixing it, 
- or switch opengpg implementation again, 
- or running a [patch] dependency to bring a local fix in.

This bug is to track the impact this could have on rustup beyond the existing noise. https://github.com/rust-lang/rust/issues/79813 is the tracking bug in rust for moving the behaviour from warning to something more.

### Steps

cargo build

### Rustup version

```console
n/a
```

### Installed toolchains

```console
n/a
```

**Comment by youknowone** [comment]
It will be fixed in the next release of `sequioia-openpgp` 

https://gitlab.com/sequoia-pgp/sequoia/-/merge_requests/1461

**Comment by 0xPoe** [comment]
We already remove this dependency, so I think we can close it now.
