### ISSUE TITLE
rust-1.51.0 compile error because rust-doc

### ISSUE THREAD

**Issue by jackssirs** [rust-lang/rustup#3218]
### Problem

when i compile rust-1.51.0  in a mock  environment ,the error messsage blow 
Rustbook (x86_64-unknown-linux-gnu) - rustc
Building stage0 tool fabricate (x86_64-unknown-linux-gnu)
   Compiling maybe-uninit v2.0.0
   Compiling cc v1.0.60
   Compiling scopeguard v1.1.0
   Compiling rayon-core v1.7.1
   Compiling pkg-config v0.3.18
   Compiling crc32fast v1.2.0
   Compiling adler v0.2.3
   Compiling yaml-rust v0.3.5
   Compiling either v1.6.0
   Compiling crossbeam-utils v0.7.2
   Compiling memoffset v0.5.5
   Compiling crossbeam-epoch v0.8.2
   Compiling rayon v1.3.1
   Compiling num_cpus v1.13.0
   Compiling xattr v0.2.2
   Compiling filetime v0.2.12
   Compiling miniz_oxide v0.4.0
   Compiling tar v0.4.29
   Compiling clap v2.33.3
   Compiling flate2 v1.0.16
   Compiling crossbeam-queue v0.2.3
   Compiling lzma-sys v0.1.16
   Compiling crossbeam-deque v0.7.3
   Compiling xz2 v0.1.6
   Compiling installer v0.0.0 (/builddir/build/BUILD/rustc-1.51.0-src/src/tools/rust-installer)
    Finished release [optimized + debuginfo] target(s) in 10.01s
Dist rust-docs-1.51.0-x86_64-unknown-linux-gnu
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `9223372035781033984`,
 right: `0`', library/std/src/sys/unix/kernel_copy.rs:589:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

command did not execute successfully: "/builddir/build/BUILD/rustc-1.51.0-src/build/x86_64-unknown-linux-gnu/stage0-tools-bin/fabricate" "generate" "--image-dir" "/builddir/build/BUILD/rustc-1.51.0-src/build/tmp/tarball/rust-docs/x86_64-unknown-linux-gnu/image" "--component-name=rust-docs" "--bulk-dirs" "share/doc/rust/html" "--rel-manifest-dir=rustlib" "--legacy-manifest-dirs=rustlib,cargo" "--product-name=Rust Documentation" "--success-message=rust-docs installed." "--package-name=rust-docs-1.51.0-x86_64-unknown-linux-gnu" "--non-installed-overlay" "/builddir/build/BUILD/rustc-1.51.0-src/build/tmp/tarball/rust-docs/x86_64-unknown-linux-gnu/overlay" "--output-dir" "/builddir/build/BUILD/rustc-1.51.0-src/build/dist" "--work-dir" "/builddir/build/BUILD/rustc-1.51.0-src/build/tmp/tarball/rust-docs/x86_64-unknown-linux-gnu"
expected success, got: exit code: 101

failed to run: /builddir/build/BUILD/rustc-1.51.0-src/build/bootstrap/debug/bootstrap install
Build completed unsuccessfully in 0:48:42
error: Bad exit status from /var/tmp/rpm-tmp.lvyTWH (%install)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.lvyTWH (%install)
Finish: rpmbuild rust-1.51.0-6.el8.src.rpm
Finish: build phase for rust-1.51.0-6.el8.src.rpm
ERROR: Exception(/home/lvf/rust-1.51.0-6.el8.src.rpm) Config(test) 74 minutes 47 seconds
INFO: Results and/or logs in: /var/lib/mock/test/result
ERROR: Command failed: 
 # /usr/bin/systemd-nspawn -q -M 3ae5c7a5ae364124841f3f3f22f75b83 -D /var/lib/mock/test/root -a --capability=cap_ipc_lock --bind=/tmp/mock-resolv.lbd8i3u4:/etc/resolv.conf --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=en_US.UTF-8 -u mockbuild bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/rust.spec

### Steps

1,mock -r mango-mock  --rebuild  /home/lvf/rust-1.51.0-6.ky10.src.rp
2, Dist rust-docs-1.51.0-x86_64-unknown-linux-gnu
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `9223372035781033984`,
 right: `0`', library/std/src/sys/unix/kernel_copy.rs:589:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
3,command did not execute successfully: "/builddir/build/BUILD/rustc-1.51.0-src/build/x86_64-unknown-linux-gnu/stage0-tools-bin/fabricate" "generate" "--image-dir" "/builddir/build/BUILD/rustc-1.51.0-src/build/tmp/tarball/rust-docs/x86_64-unknown-linux-gnu/image" "--component-name=rust-docs" "--bulk-dirs" "share/doc/rust/html" "--rel-manifest-dir=rustlib" "--legacy-manifest-dirs=rustlib,cargo" "--product-name=Rust Documentation" "--success-message=rust-docs installed." "--package-name=rust-docs-1.51.0-x86_64-unknown-linux-gnu" "--non-installed-overlay" "/builddir/build/BUILD/rustc-1.51.0-src/build/tmp/tarball/rust-docs/x86_64-unknown-linux-gnu/overlay" "--output-dir" "/builddir/build/BUILD/rustc-1.51.0-src/build/dist" "--work-dir" "/builddir/build/BUILD/rustc-1.51.0-src/build/tmp/tarball/rust-docs/x86_64-unknown-linux-gnu"
expected success, got: exit code: 101

failed to run: /builddir/build/BUILD/rustc-1.51.0-src/build/bootstrap/debug/bootstrap install
Build completed unsuccessfully in 0:48:42
error: Bad exit status from /var/tmp/rpm-tmp.lvyTWH (%install)

### Rustup version

```console
rustc-1.51.0-src
```

### Installed toolchains

```console
rustc-1.51.0-src
```

**Comment by 0xPoe** [comment]
I don't think this is a rustup problem. So I will close this issue. You can ask about it at https://users.rust-lang.org/. Thank you very much.

**Comment by Yan-WenKai** [comment]
> ### 问题
> 当我在模拟环境中编译 rust-1.51.0 时，错误 messsage blow Rustbook （x86_64-unknown-linux-gnu） - rustc 构建 stage0 工具制造 （x86_64-unknown-linux-gnu） 编译 maybe-uninit v2.0.0 编译 cc v1.0.60 编译 scopeguard v1.1.0 编译 rayon-core v1.7.1 编译 pkg-config v0.3.18 编译 crc32fast v1.2.0 编译 adler v0.2.3 编译 yaml-rustv0.3.5 编译 v1.6.0 编译 crossbeam-utils v0.7.2 编译 memoffset v0.5.5 编译 crossbeam-epoch v0.8.2 编译 rayon v1.3.1 编译 num_cpus v1.13.0 编译 xattr v0.2.2 编译文件时 v0.2.12 编译 miniz_oxide v0.4.0 编译 tar v0.4.29 编译 clap v2.33.3 编译 flate2 v1.0.16编译 crossbeam-queue v0.2.3 编译 lzma-sys v0.1.16 编译 crossbeam-deque v0.7.3 编译 xz2 v0.1.6 编译安装程序 v0.0.0 （/builddir/build/BUILD/rustc-1.51.0-src/src/tools/rust-installer） 10.01s 完成版本 [优化 + debuginfo] 目标 Dist rust-docs-1.51.0-x86_64-unknown-linux-gnu 线程“main”在“断言失败”时惊慌失措：左：，right： '， library/std/src/sys/unix/kernel_copy.rs：589：25 注意：使用环境变量运行以显示回溯跟踪`(left == right)``9223372035781033984``0``RUST_BACKTRACE=1`
> 
> 命令未成功执行： “/builddir/build/BUILD/rustc-1.51.0-src/build/x86_64-unknown-linux-gnu/stage0-tools-bin/fabricate” “generate” “--image-dir” “/builddir/BUILD/rustc-1.51.0-src/build/tmp/tarball/rust-docs/x86_64-unknown-linux-gnu/image” “--component-name=rust-docs” “--bulk-dirs” “share/doc/rust/html” “--rel-manifest-dir=rustlib” “--legacy-manifest-dirs=rustlib，cargo” “--product-name=Rust 文档” “--success-message=rust-docs安装。“--package-name=rust-docs-1.51.0-x86_64-unknown-linux-gnu” “--non-installed-overlay” “/builddir/build/BUILD/rustc-1.51.0-src/build/tmp/tarball/rust-docs/x86_64-unknown-linux-gnu/overlay” “--output-dir” “/builddir/build/BUILD/rustc-1.51.0-src/build/dist” “--work-dir” “/builddir/build/BUILD/rustc-1.51.0-src/build/tmp/tarball/rust-docs/x86_64-unknown-linux-gnu” 预期成功，得到： 退出代码：101
> 
> 无法运行：/builddir/build/BUILD/rustc-1.51.0-src/build/bootstrap/debug/bootstrap install 在 0：48：42 中构建未成功完成错误：/var/tmp/rpm-tmp.lvyTWH （%install） 的退出状态错误
> 
> RPM 构建错误：/var/tmp/rpm-tmp.lvyTWH 的退出状态错误 （%install） 完成：rpmbuild rust-1.51.0-6.el8.src.rpm 完成：rust-1.51.0-6.el8.src.rpm 的构建阶段 错误：异常（/home/lvf/rust-1.51.0-6.el8.src.rpm） 配置（测试） 74 分 47 秒 信息：结果和/或登录：/var/lib/mock/test/result 错误：命令失败：
> 
> # /usr/bin/systemd-nspawn -q -M 3ae5c7a5ae364124841f3f3f22f75b83 -D /var/lib/mock/test/root -a --capability=cap_ipc_lock --bind=/tmp/mock-resolv.lbd8i3u4：/etc/resolv.conf --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin：/bin：/usr/sbin：/sbin --setenv=PROMPT_COMMAND=printf “\033]0;\007” --setenv=PS1= \s-\v$ --setenv=LANG=en_US.UTF-8 -u mockbuild bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/rust.spec
> ### 步骤
> 1,mock -r mango-mock --rebuild /home/lvf/rust-1.51.0-6.ky10.src.rp 2, Dist rust-docs-1.51.0-x86_64-unknown-linux-gnu thread 'main' panicked at 'assertion failed: left: , right: ', library/std/src/sys/unix/kernel_copy.rs:589:25 note: run with environment variable to display a backtrace 3,command did not execute successfully: "/builddir/build/BUILD/rustc-1.51.0-src/build/x86_64-unknown-linux-gnu/stage0-tools-bin/fabricate" "generate" "--image-dir" "/builddir/build/BUILD/rustc-1.51.0-src/build/tmp/tarball/rust-docs/x86_64-unknown-linux-gnu/image" "--component-name=rust-docs" "--bulk-dirs" "share/doc/rust/html" "--rel-manifest-dir=rustlib" "--legacy-manifest-dirs=rustlib,cargo" "--product-name=Rust Documentation" "--success-message=rust-docs installed." "--package-name=rust-docs-1.51.0-x86_64-unknown-linux-gnu" "--non-installed-overlay" "/builddir/build/BUILD/rustc-1.51.0-src/build/tmp/tarball/rust-docs/x86_64-unknown-linux-gnu/overlay" "--output-dir" "/builddir/build/BUILD/rustc-1.51.0-src/build/dist" "--work-dir" "/builddir/build/BUILD/rustc-1.51.0-src/build/tmp/tarball/rust-docs/x86_64-unknown-linux-gnu" expected success, got: exit code: 101`(left == right)``9223372035781033984``0``RUST_BACKTRACE=1`
> 
> failed to run: /builddir/build/BUILD/rustc-1.51.0-src/build/bootstrap/debug/bootstrap install Build completed unsuccessfully in 0:48:42 error: Bad exit status from /var/tmp/rpm-tmp.lvyTWH (%install)
> 
> ### Possible Solution(s)
> _No response_
> 
> ### Notes
> _No response_
> 
> ### Rustup version
> ```
> rustc-1.51.0-src
> ```
> 
> ### Installed toolchains
> ```
> rustc-1.51.0-src
> ```

Hello, when compiling rust, I encountered a similar problem to yours. How did you solve it?
