### ISSUE TITLE
dup tools missing rust-analyzer in 1.25.2

### ISSUE THREAD

**Issue by Firstyear** [rust-lang/rustup#3229]
rust-analyzer has been added to dup tools in https://github.com/rust-lang/rustup/blame/master/src/lib.rs#L38 but appears to be missing in https://github.com/rust-lang/rustup/blob/stable/src/lib.rs which I presume is where releases are made from. Is there a reason not to provide rust-analyzer in stable as a proxyable tool?

**Comment by Firstyear** [comment]
(related, https://bugzilla.opensuse.org/show_bug.cgi?id=1208525 )

**Comment by 0xPoe** [comment]
Duplicate of https://github.com/rust-lang/rustup/issues/3062
We need to wait for a release. I hope we can make it recently.

**Comment by 0xPoe** [comment]
Thanks for reporting.
