### ISSUE TITLE
 Is it possible to relocate the ~/.rustup directory?

### ISSUE THREAD

**Issue by pwnwriter** [rust-lang/rustup#3248]
Hi,
I'm wondering if there is any way to relocate the `~/.rustup` directory to another location such as `~/.local/share/rustup`  instead of having it in the home directory. The reason I'm asking is that I prefer to keep my home directory clean and organized.

If this is not currently possible, would it be something that could be considered for a future release?

Thank you for your help and your work on Rust :)

**Comment by ChrisDenton** [comment]
I think currently this can only be done by setting the `RUSTUP_HOME` environment variable to the path you want. There's also `CARGO_HOME` for cargo.

**Comment by rbtcollins** [comment]
Yep, thats the answer. Many folk do relocate it. There isn't a config file to relocate it because the user config for rustup lives in RUSTUP_HOME. See https://rust-lang.github.io/rustup/installation/index.html
