### ISSUE TITLE
Install script tells me to source a `sh`-style env file when run in `fish`

### ISSUE THREAD

**Issue by lgarron** [rust-lang/rustup#3251]
### Problem

At the end of install, `rustup` helpfully tries to tell me:

```
To configure your current shell, run:
source "/Users/lgarron/.data/cargo/env"`
```

But my current shell is `fish`, and sourcing that file is going to be a bad time:

```
> source "/Users/lgarron/.data/cargo/env"
~/.data/cargo/env (line 4): 'case' builtin not inside of switch block
case ":${PATH}:" in
^~~^
from sourcing file ~/.data/cargo/env
source: Error while reading file '/Users/lgarron/.data/cargo/env'
```

### Steps

1. Open a [`fish`](https://fishshell.com/) terminal on the latest macOS.
2. Run the command from https://rustup.rs/ (`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`)

### Possible Solution(s)

1. Don't tell me that something will configure my current shell, if it in fact does not?
2. For maximum helpfulness, offer a `fish`-compatible env file that I can source.

### Rustup version

```console
> rustup --version
rustup 1.25.2 (17db695f1 2023-02-01)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.67.1 (d5a82bbd2 2023-02-07)
```
```


### Installed toolchains

```console
> rustup show
Default host: aarch64-apple-darwin
rustup home:  /Users/lgarron/.data/rustup

stable-aarch64-apple-darwin (default)
rustc 1.67.1 (d5a82bbd2 2023-02-07)
```
```

**Comment by rbtcollins** [comment]
It is an interesting idea to walk up the process tree / look for some indication that fish is in use and change our prompts. See also #478. That said, you are actually running the install in posix `sh`, not `fish` - thats what the curlsh pattern does. I'm going to duplicate all the fish bugs together.
