### ISSUE TITLE
Unable to install or use RUST properly without admin permissions

### ISSUE THREAD

**Issue by rkfx** [rust-lang/rustup#3267]
I'm on a school laptop while at school on which I do not have admin rights on. Due to this, I cannot install VSBT or any build tools like that. Rust is installable with scoop but unusable without the proper windows build tool

**Comment by rbtcollins** [comment]
You might be able to get the GNU linker toolchain working. You'll need to change your default target as documented https://rust-lang.github.io/rustup/installation/windows.html

I don't see a bug here, as we have documentation in place already, and no plans to take on shipping the low level toolchain ourselves. You might get more help at https://users.rust-lang.org/ , and if you do see an actionable bug for rustup, please do reopen this.
