### ISSUE TITLE
Documentation around libclang version is confusing 

### ISSUE THREAD

**Issue by cgmckeever** [rust-lang/rustup#3274]
### Problem

During installation, with libclang-3.9 installed, the installer errors with `libclang 3.9 or later is needed`

[The docs](https://rust-lang.github.io/rust-bindgen/requirements.html#installing-clang-39) (referenced as `installing-clang-39`) then state `It is required to use Clang 5.0 or greater` ... clarification of this in the installer output would make troubleshooting a bit more straightforward.

```
thread 'main' panicked at '`libclang` function not loaded: `clang_getTranslationUnitTargetInfo`. 
This crate requires that `libclang` 3.9 or later be installed on your system. 
For more information on how to accomplish this, see here: https://rust-lang.github.io/rust-bindgen/requirements.html#installing-clang-39', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.6.0/src/lib.rs:1735:1
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Steps

```
apt-get install fuse libfuse-dev cmake clang-3.9 libclang-3.9-dev pkg-config llvm-dev 
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
git clone --recurse-submodules https://github.com/awslabs/mountpoint-s3.git

export LIBCLANG_PATH=/usr/lib/x86_64-linux-gnu/
cd mountpoint-s3; cargo build --release
```

resolution
```
apt-get install libclang-5.0-dev 
```

### Possible Solution(s)

Update the installer output to properly reference the `libclang-5.0` dependency

### Rustup version

```console
rustup --version
rustup 1.25.2 (17db695f1 2023-02-01)
```
```


### Installed toolchains

```console
rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/ubuntu/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.68.0 (2c8cc3432 2023-03-06)
```
```

**Comment by ehuss** [comment]
This error appears to be coming from clang-sys. Can you move this issue over to their repository here: https://github.com/KyleMayes/clang-sys?  Or perhaps it is an issue for bindgen, whose issue track is at https://github.com/rust-lang/rust-bindgen.

This issue tracker is for rustup, the tool which handles installing the rust compiler.

**Comment by cgmckeever** [comment]
will do .. thanks for the guidance

**Comment by cgmckeever** [comment]
https://github.com/rust-lang/rust-bindgen/issues/2446
