### ISSUE TITLE
`rustup doc` command opens an instance of balenaEtcher 

### ISSUE THREAD

**Issue by dpensi** [rust-lang/rustup#3293]
### Problem

[Screencast from 03-29-2023 06:35:30 PM.webm](https://user-images.githubusercontent.com/2753588/228609257-d69f584d-0ff0-4fb1-9853-63d573f65c5d.webm)

If [balenaEtcher](https://www.balena.io/etcher)  is installed the command `rustup doc` opens an instance of it instead of opening the docs as shown in the video

### Steps

1. install [balenaEtcher](https://www.balena.io/etcher)
2. install rust following [this instructions](https://doc.rust-lang.org/book/ch01-01-installation.html), select the default installation (press 1 when prompted)
3. launch `rustup doc` 

### Notes

```shell
$ uname -a
Linux fedora 6.2.7-100.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Mar 17 16:53:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Rustup version

```console
rustup 1.25.2 (17db695f1 2023-02-01)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.68.2 (9eb3afe9e 2023-03-27)`
```

### Installed toolchains

```console
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/dpensier/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.68.2 (9eb3afe9e 2023-03-27)
```

**Comment by drulum** [comment]
I've just confirmed the problem using Debian Bullseye Gnome with Balena Etcher installed. I've checked that the default application for web is set to Firefox.

I get the same issue with:
`cargo doc --open`

**Comment by geoma76** [comment]
same here. Ubuntu 22.04 with installed Balena Etcher. Default app for web is Firefox.
rustc Version 1.73

I used 
`cargo doc --open`

**Comment by djc** [comment]
I'm guessing there is an issue with your mime types associations:

https://wiki.debian.org/MimeTypesSupport

Maybe have a look at what mime types Balena Etcher claims support for? I think it's pretty unlikely that this is a rustup bug, though. We use `opener::open_browser()` which just opens the app associated with .html files by default, and obeys the `BROWSER` environment variable (which I'm guessing Balena Etcher does not set).

**Comment by geoma76** [comment]
> I'm guessing there is an issue with your mime types associations:
> 
> https://wiki.debian.org/MimeTypesSupport
> 
> Maybe have a look at what mime types Balena Etcher claims support for? I think it's pretty unlikely that this is a rustup bug, though. We use `opener::open_browser()` which just opens the app associated with .html files by default, and obeys the `BROWSER` environment variable (which I'm guessing Balena Etcher does not set).

don't think so. 
For example 
`npm run dev` 
for nuxt or in general npm/node.js opens a Firefox tab without any issue on that system. Just checked it again a minute ago.
Double clicking on a .html file in the file explorer opens Firefox, too.
So I think my associations should be okay.

**Comment by geoma76** [comment]
okay, got it!
@djc : you were right! 
it WAS a missconfigured .html association. But only for local .html. And the configuration in the Gnome settings were still showing "Firefox" as the standard.
On a hunch I set the configuration to another browser, saved it and went back to "Firefox" -> cargo doc was working after that.
Then I re-opened balena etcher and voila: same problem again.
So definitely not a problem of rust...
Thanks for the push in the right direction!

**Comment by djc** [comment]
Basically, we'll execute `xdg-open ~/.rustup/toolchains/stable-aarch64-apple-darwin/share/doc/rust/html/index.html` (likely with a different target, of course) if `xdg-open` exists (which I'm guessing it does in your case?) or otherwise does [some other stuff](https://github.com/Seeker14491/opener/blob/master/opener/src/linux_and_more.rs#L78) with `sh -s`.

I'm going to close this for now, I don't think the problem is with rustup in this case.
