### ISSUE TITLE
Installation menu not provided when running "rustup-init.exe"

### ISSUE THREAD

**Issue by karageyou** [rust-lang/rustup#3314]
### Problem

The first time I attempted an install rustup-init.exe, an installation menu was provided, in which I selected the first option, I don't remember which one. I proceeded onwards until the final part of the installation, at which point, the installation stopped so i terminated it in task manager then restarted. I had to manually install the MSVC build tools. After that, I ran the installation again, then a window containing the following information showed up. 

`The Cargo home directory is located at:

  C:\Users\[Username]\.cargo

This can be modified with the CARGO_HOME environment variable.

The cargo, rustc, rustup and other commands will be added to
Cargo's bin directory, located at:

  C:\Users\[Username]\.cargo\bin
                                                                                                                        
The Cargo home directory is located at:

  C:\Users\[Username]\.cargo

This can be modified with the CARGO_HOME environment variable.

The cargo, rustc, rustup and other commands will be added to
Cargo's bin directory, located at:

  C:\Users\[Username]\.cargo\bin

This path will then be added to your PATH environment variable by
modifying the HKEY_CURRENT_USER/Environment/PATH registry key.

You can uninstall at any time with rustup self uninstall and
these changes will be reverted.`

I then pressed enter and the installation began without showing any menu, after which I was able to succesfully install rust. Everything is resolved as of now, however I was asked by people on the discord server to report this as a bug.

### Steps

1. Begin the installation
2. Cancel the installation near the end
3. Manually install MSVC build tools
4. Run rustup-init.exe 
5. Begin the installation again

### Rustup version

```console
1.25.2
```

### Installed toolchains

```console
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\[Username]\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.68.2 (9eb3afe9e 2023-03-27)

Note that this is after I solved the issue and completed the installation
```

**Comment by rbtcollins** [comment]
Which discord server?

I'm not sure I understand the bug - are you saying you were expecting to be prompted for the same information twice?

**Comment by rbtcollins** [comment]
Also - which discord, I don't see any discussion in https://discord.com/channels/442252698964721669/463480252723888159 about this

**Comment by rbtcollins** [comment]
Dup of #3043 we think
