### ISSUE TITLE
remove rls support

### ISSUE THREAD

**Issue by rbtcollins** [rust-lang/rustup#3316]
With rust-analyzer taking over, should we remove the rls specific tests, and/or the rls proxy?

**Comment by mattheww** [comment]
The `rls` proxy is something of an active nuisance.

In its default configuration in emacs 29, eglot knows that both rls and rust-analyzer exist, sees that both are available on PATH, and prompts the user rather than just choosing to run rust-analyzer.

**Comment by lnicola** [comment]
I'd blame that on eglot, it shouldn't be trying to run rls. Consider filing an issue there.

(That's not to say the RA proxy itself isn't annoying if you compile your own RA, but it's the best way we have to make rustup-managed RA work. But that's a completely different topic.)

**Comment by mattheww** [comment]
Eglot upstream removed the reference to `rls` from its default configuration some months ago, but of course it takes time for these things to filter through to users, and there may well be other clients out there in a similar position.

**Comment by rami3l** [comment]
I believe all work required in this repo has concluded in #3920. As such, I'm closing this issue as completed now. For further work, please refer to https://github.com/rust-lang/rust/pull/126856.
