### ISSUE TITLE
Check if `~/.cargo/bin` already on PATH

### ISSUE THREAD

**Issue by chriskrycho** [rust-lang/rustup#332]
During first setup, especially for users who have used multirust or rustup in the past, it's possible they'll already have `~/.cargo/bin` in their path configuration already. (It's already in my `.profile`, for example.) Instead of _always_ adding it to the end of the user's profiles, maybe check the `PATH` for it first?

**Comment by brson** [comment]
I think I like this idea, though it's a little clever and I'm wary of guessing the user's intent incorrectly. I guess we would check for whether PATH contains the substring ".cargo/bin" or ".cargo\bin".

This does seem like a niche case though - most people installing rustup should not have a preexisting install of Cargo from some other source.

There's also now an interactive option to opt out of modifying PATH for those that know they don't need it.
