### ISSUE TITLE
rustup-init 1.26.0 fails on OS X 10.9.5

### ISSUE THREAD

**Issue by RJVB** [rust-lang/rustup#3336]
### Problem

The newest version of rustup-init, v1.26.0 fails on Mac OS X 10.9.5 when installing rustc, because it was apparently built for a later SDK:

```
env RUSTUP_HOME=/tmp/.rustup CARGO_HOME=/tmp/.rustup/Cargo /opt/RustUp/install.sh --profile minimal --no-modify-path -y
info: downloading installer
/var/folders/j1/1439ppj08xj8h6006s6drbq00000gs/T/tmp.TBrH8nzaCI/rustup-init -> /tmp/rustup-init
info: profile set to 'minimal'
info: default host triple is x86_64-apple-darwin
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: latest update on 2023-04-20, rust version 1.69.0 (84c898d65 2023-04-16)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
 53.6 MiB /  53.6 MiB (100 %)  51.2 MiB/s in  1s ETA:  0s
info: installing component 'cargo'
dyld: lazy symbol binding failed: Symbol not found: _fdopendir$INODE64
  Referenced from: /var/folders/j1/1439ppj08xj8h6006s6drbq00000gs/T/tmp.tr7GX8fn5e/rustup-init
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _fdopendir$INODE64
  Referenced from: /var/folders/j1/1439ppj08xj8h6006s6drbq00000gs/T/tmp.tr7GX8fn5e/rustup-init
  Expected in: /usr/lib/libSystem.B.dylib

/opt/RustUp/install.sh: line 471:  4833 Trace/BPT trap: 5       "$@"
Exit 1

> /tmp/rustup-init --version
rustup-init 1.26.0 (5af9b9484 2023-04-05)
> /opt/RustUp/Cargo/bin/rustup --version
rustup 1.25.2 (fae52a197 2023-02-01)
```

(/opt/RustUp/install.sh is the install script I downloaded from rustup.rs to create my /opt/RustUp install)

### Steps

1. boot under OS X 10.9.5
2. run the install script as shown (or via the command given on rustup.rs)
3. observe the missing symbol error above

### Possible Solution(s)

Check your build host and MACOSX_DEPLOYMENT_TARGET or whatever options you use to determine the minimum supported OS.

### Notes

I see no information about minimum requires OS versions on rustup.rs so I assume that dropping support for a still relatively widely used OS is not intentional in a minor version update like this is.

### Rustup version

```console
rustup-init 1.26.0 (5af9b9484 2023-04-05)en
```

### Installed toolchains

```console
Not applicable, the install fails well before any toolchains get to be installed.
```

**Comment by 0xPoe** [comment]
We build it with GitHub Actions and use the latest macOS.

You can see more at: https://github.com/rust-lang/rustup/blob/stable/.github/workflows/macos-builds-on-all.yaml

**Comment by RJVB** [comment]
>We build it with GitHub Actions and use the latest macOS.

Well, apparently it's a miracle that it still ran on 10.9 until a few days ago, as I don't see anything in that script that defines a minimum required/supported OS version... :-/

**Comment by rbtcollins** [comment]
OS X 10.9 is unsupported : `Obsolete, unsupported as of September 2016` (from wikipedia). I think we'd accept patches to build it differently with support for older OS X versions, but can't really consider this a *bug* per se.

You can download an older release if you like, and run that as long as you like - until the channel format changes, you can still use older rustup to install newer rusts... until the rust toolchains themselves no longer run on 10.9.
