### ISSUE TITLE
Installer says "The application was unable to start correctly (0xc00000ba)" on 64-bit windows 10

### ISSUE THREAD

**Issue by rcorre** [rust-lang/rustup#3341]
### Problem

I downloaded rustup from https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe on 64-bit windows10. When running it, I see this dialog:

```
---------------------------
rustup-init (4).exe - Application Error
---------------------------
The application was unable to start correctly (0xc00000ba). Click OK to close the application. 
---------------------------
OK   
---------------------------
```

### Steps

1. Download https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe on 64-bit windows 10
2. Run the executable

### Rustup version

```console
Not installed yet
```

### Installed toolchains

```console
Not installed yet
```

**Comment by rcorre** [comment]
```
curl https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe -Lo /tmp/rustup.exe
```

Running this from a Git Bash prompt instead of trying to download it via a browser worked.

**Comment by ChrisDenton** [comment]
I can't reproduce this on my machine. `0xc00000ba` means `STATUS_FILE_IS_A_DIRECTORY` which is odd in this context so this does seem system specific for some reason, though I'm not sure why.

My first guess is that you downloaded it to your downloads folder and that somehow caused issues? Not sure. My other guess would be anti-virus or anti-malware software being overzealous and curl bypassing that.

**Comment by rcorre** [comment]
I did have to click through multiple layers of "Are you sure" dialogs before being able to run it. I'll close this since it seemed to be specific to me and I have a workaround. Thanks!
