### ISSUE TITLE
No `~/.cargo` directory

### ISSUE THREAD

**Issue by pvdrz** [rust-lang/rustup#3348]
### Problem

When running `rustup install toolchain stable` on a fresh installation, the usual `~/.cargo/bin` directory is not being created.

### Steps

1. Install rustup
2. Run `rustup install toolchain stable`

### Notes

Using `rustup run stable` works and the toolchain is being installed under the `~/.rustup/toolchains` directory.

### Rustup version

```console
rustup 1.26.0 (2023-05-04)
```

### Installed toolchains

```console
stable-x86_64-unknown-linux-gnu (default)
```

**Comment by dgunay** [comment]
Ran into this as well. Downgrading to 1.25.2 and running `rustup install stable` fixed it for me.

EDIT: command should be `rustup toolchain install stable`

**Comment by pvdrz** [comment]
Can confirm that downgrading to 1.25.2 works.

**Comment by 0xPoe** [comment]
> rustup install toolchain stable

I don't think rustup supports this command.

It should be `rustup install stable` or `rustup toolchain install stable`. Does it is a typo?

If I ran ` rustup install toolchain stable`, I will get an error: 
```log
➜  ~ rustup install toolchain stable
error: invalid toolchain name: 'toolchain'
```

**Comment by 0xPoe** [comment]
Could you please provide your OS information? Because I can not reproduce it.

**Comment by pvdrz** [comment]
hi @hi-rustin. My distro (arch btw) updated their `rustup` package recently and they did another build of 1.60 where this issue no longer happens. So probably this wasn't a problem of `rustup` itself but rather of the package build process somehow. I'm closing this issue now.
