### ISSUE TITLE
Please support a way to request "stable minus N" for some N

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rustup#3353]
### Problem you are trying to solve

Projects often specify their MSRV policy as "the last N stable versions" (e.g. the last 2, or the last 4).

To test that in CI, I'd love to have a syntax to install "stable minus 1" (the version before the current stable version), or similar.

### Solution you'd like

I don't have a preference about the syntax; anything unambiguous would be fine. Something like `stable-1` or `stable-2` would be unambiguous given what's currently supported, but some other syntax could work too.

**Comment by rami3l** [comment]
Indeed, I also want to have this in my workflow sometimes...
@rbtcollins what do you think about the syntax?

**Comment by rami3l** [comment]
cc #2291 
(I meant to say "closing as a duplicate" but I don't have the permission...)
