### ISSUE TITLE
`rustup doc` (and all available flags) will not allow me to read the docs

### ISSUE THREAD

**Issue by HarrisonHemstreet** [rust-lang/rustup#3369]
### Problem

When I run any of the following:
`rustup doc`
`rustup doc --std`
`rustup doc --book`
`rustup doc --cargo`
...
I then see my browser (I tried both firefox and brave) open up to this:
![image](https://github.com/rust-lang/rustup/assets/65803282/97d33a39-c184-4ff6-ad27-84d3d3523633)

I'm using Rust stable 1.69
I'm on Ubuntu 22.04

### Steps

0. use Rust stable 1.69 and Ubuntu 22.04
1. open a terminal
2. run: `rustup doc --std`
3. see that it opens up the correct file, but with the above error

### Possible Solution(s)

Based off of the error, it's probable the issue has to do with insufficient permissions. I know that in Docker, similar issues occur because Docker will often times execute commands using it's own user, and not the user's user. Similarly, rustup could be using a different user than my personal account to be opening up the files to read them. Maybe the issue is stemming from there?

### Notes

what's strange about this issue is that I've been able to open up the docs before. I haven't opened them up for a while, so maybe there was a bug introduced somewhere along the line between last year and today?

And btw, running `cargo doc --open` works great.

### Rustup version

```console
harry@nyx:~$ rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.69.0 (84c898d65 2023-04-16)`
harry@nyx:~$
```

### Installed toolchains

```console
harry@nyx:~$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/harry/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.69.0 (84c898d65 2023-04-16)
harry@nyx:~$
```

**Comment by rbtcollins** [comment]
Duplicate with #3112
