### ISSUE TITLE
Verification for existing command execution while `update`

### ISSUE THREAD

**Issue by NishantJoshi00** [rust-lang/rustup#3376]
### Problem

Executing the `cargo build` command on my stable toolchain, on a different terminal updated my stable toolchain with `rustup update stable`. This caused my build to panic with an error getting hold of `core` functions, which happened just after the `rust-std` update.

I have tried this on both my `macosx` and `windows` machine, attached a screenshot below (from `windows` machine):

![just a screenshot](https://github.com/rust-lang/rustup/assets/51093026/c1e6c7e6-94de-4d3f-bd20-7618b5be3db6)

### Steps

1. Required an outdated stable branch, and that branch being used for any compilation and execution
2. (In my case) Start compiling a project which might take a little longer than the update process
3.  parallelly update the stable branch while the compilation is underway.
4. This will break the compilation

### Possible Solution(s)

considering `cargo`, `rustc`, `rustfmt` are stateless functions, we can consider having a lock file, which gets created when the specific function is invoked, this lock file, however, will not prevent the executable from executing but will prevent any program, in this case, `rustup` to remove and/or update it, until the lock file is removed. 
To allow multiple executions, if anyone wants to use these executables, we can create `n` lock files for every pid that is using the program, and will only allow `rustup` to tamper with them if there is no lock file present.

### Notes

If possible I would like to work on solving this issue. Though the solution that I have might be a bit vague, any inputs on a different approach are welcome. In the mean time, I'll try to understand the internal workings of `rustup`.

### Rustup version

```console
rustup 1.26.0 (5af9b9484 2023-04-05)
```

### Installed toolchains

```console
Default host: x86_64-pc-windows-msvc
rustup home:  

stable-x86_64-pc-windows-msvc (default)
rustc 1.70.0 (90c541806 2023-05-31)
```

**Comment by 0xPoe** [comment]
Duplicate of https://github.com/rust-lang/rustup/issues/988

**Comment by rbtcollins** [comment]
@NishantJoshi00 please do discuss this in #988 - that bug is quite large, because its a complex topic, but it is the place where we are discussing what a solution looks like.
