### ISSUE TITLE
Windows 11 - Rustup says rust_src installed, but can't find it

### ISSUE THREAD

**Issue by sohang3112** [rust-lang/rustup#3383]
### Problem

I added component `rust-src`. `rust_src` should be installed in directory `$(rustc --print sysroot)/lib/rustlib/src/rust/src`, but `src` directory doesn't exist in `$(rustc --print sysroot)/lib/rustlib`.

`rustc --print syroot` shows path `C:\Program Files\Rust stable MSVC 1.67`, but it doesn't contain the expected folder structure:
```C:\Program Files\Rust stable MSVC 1.67\lib\rustlib
 - etc
 - x86_64-pc-windows-msvc
 ```

### Steps

- In Windows 11, added component `rust-src`:
```console
$ rustup component add rust-src
info: component 'rust-src' is up to date
```
- Check path of `rustc`:
 ```console
$ rustc --print sysroot
C:\Program Files\Rust stable MSVC 1.67
```
- Expected `src` folder inside `C:\Program Files\Rust stable MSVC 1.67\lib\rustlib`, but only `etc` and `x86_64-pc-windows-msvc` folders are present.

### Rustup version

```console
$ rustup --version
rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.62.0 (a8314ef7d 2022-06-27)
```

### Installed toolchains

```console
$ rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\SohangChopra\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.62.0 (a8314ef7d 2022-06-27)
```

**Comment by ehuss** [comment]
> `C:\Program Files\Rust stable MSVC 1.67`

It looks like Rust was installed with the standalone Rust installer. Rustup installs everything in `%USERPROFILE%\.rustup`. I would suggest uninstalling the standalone one in `C:\Program Files\Rust stable MSVC 1.67`, and make sure `%USERPROFILE%\.cargo\bin` is in your path.

**Comment by rbtcollins** [comment]
I think there is nothing to do here. Please do reopen if you disagree (e.g. if this isn't documented well enough). We already emit warnings during the install when rust is already installed.
