### ISSUE TITLE
unexpected behaviour when mktemp is called in sh.rustup.rs on Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by parallastra** [rust-lang/rustup#3386]
### Problem

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh fails unexpectedly with:
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init /tmp/tmp.7m9vrQHAWV/rustup-init x86_64-unknown-linux-gnu

### Steps

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

### Possible Solution(s)

workaround is to create a local ./tmp dir and set $TMPDIR=./tmp

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | TMPDIR=./tmp sh

### Rustup version

```console
rustup 1.26.0 (5af9b9484 2023-04-05)
```

### Installed toolchains

```console
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/username/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.70.0 (90c541806 2023-05-31)
```

**Comment by 0xPoe** [comment]
I can not reproduce this issue. If I run it I got an error:
```shell
@hi-rustin ➜ /workspaces/rustup (rustin-patch-termcolor) $ curl --proto '=https' --tlsv1.2 -sSf sh.rustup.rs | sh
curl: (1) Protocol "http" not supported or disabled in libcurl
```
My env: 
```shell
@hi-rustin ➜ /workspaces/rustup (rustin-patch-termcolor) $ uname -a
Linux codespaces-239c41 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

@hi-rustin ➜ /workspaces/rustup (rustin-patch-termcolor) $ curl -V
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```


Can you try `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`?

**Comment by parallastra** [comment]
That appears to be the same command used in the original report.
Can confirm that the unexpected behaviour remains unchanged

$ uname -a
Linux hostname 5.19.0-45-generic #46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20 x86_64 x86_64 x86_64 GNU/Linux

$ curl -V
curl 8.1.2 (x86_64-pc-linux-gnu) libcurl/8.1.2 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 zstd/1.4.4 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3 libgsasl/1.8.1
Release-Date: 2023-05-30
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer
curl: (23) Failure writing output to destination
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init /tmp/tmp.cw6auCMk8R/rustup-init x86_64-unknown-linux-gnu

**Comment by rbtcollins** [comment]
Duplicate of #2948
