### ISSUE TITLE
rustup-init.sh's solaris/illumos bail doesn't work properly

### ISSUE THREAD

**Issue by Noratrieb** [rust-lang/rustup#3388]
### Problem

I tried running rustup-init.sh with `sh` on a recent install of illumos. Looking at the source code, I expected it to error with a nice error message telling me to use bash instead: https://github.com/rust-lang/rustup/blob/ab81ee3c5ec3a41e9eaa35ae3108070adf751775/rustup-init.sh#L11-L16

Instead, I got random errors about `local` not working.

My `KSH_VERSION` is `Version jM 93+ 2012-08-01`.
`uname -a` is `SunOS illumos 5.11 illumos-676abcb77c i86pc i386 i86pc`

### Steps

1. install a recent install of illumos (I used openindiana `OI-hipster-gui-20230502`)
2. run rustup-init.sh

### Possible Solution(s)

It seems a like a more robust detection would be to check for `SunOS` in `uname`, but I'm not sure how well that works on Solaris and haven't tested it (but I would assume that Solaris has `SunOS` too since "SunOS" predates "Solaris").

Alternatively, also checking for my version may work too, that version is pretty old too so it seems unlikely to change frequently.

### Rustup version

```console
https://github.com/rust-lang/rustup/blob/ab81ee3c5ec3a41e9eaa35ae3108070adf751775/rustup-init.sh
```

### Installed toolchains

```console
none
```

**Comment by rbtcollins** [comment]
If you wanted to propose a fix that works on your machine that would be great.
