### ISSUE TITLE
Rustup not working on exFAT drive

### ISSUE THREAD

**Issue by JojoFR1** [rust-lang/rustup#3395]
### Problem

I'm on **Windows 11**, I don't have administration privilege, I'm not using the default path for space reason and my `D:/` Drive is an exFAT file system.

When I was installing the latest stable Rust compiler, I wanted it to be installed in `D:/` instead of the default path. I changed the value of `RUSTUP_HOME` and `CARHO_HOME` to a custom folder in `D:` but when I try installing the compiler it output an error of linking:

```
error: could not create link from 'D:\Tools\rust\bin\rustup.exe' to 'D:\Tools\rust\bin\rust-analyzer.exe'
```

In the folder their is only a `bin/rustup.exe`.

The only solution was to use the default value, wait for it to install then move it but it's not really practical and it's slow.

---

When using my method to install the compiler, I tried executing this command `rustup update` it tell me warnings and an error, then deleting `rustc.exe` which render Rust compiler unusable:

```
warning: tool `rust-analyzer` is already installed, remove it from `D:\Tools\rust\bin`, then run `rustup update` to have rustup manage this tool.
warning: tool `rustfmt` is already installed, remove it from `D:\Tools\rust\bin`, then run `rustup update` to have rustup manage this tool.
warning: tool `cargo-fmt` is already installed, remove it from `D:\Tools\rust\bin`, then run `rustup update` to have rustup manage this tool.
error: could not create link from 'D:\Tools\rust\bin\rustup.exe' to 'D:\Tools\rust\bin\rustc.exe'
```

---

This also seem to cause problem with cargo because when trying to install a dependency, in this case `time = "0.1.12"` in the documentation exemple, and running `cargo run` I get an error:

 ```
 error: failed to download `libc v0.2.147`

Caused by:
  unable to get packages from source

Caused by:
  failed to download replaced source registry `crates-io`

Caused by:
  failed to unpack package `libc v0.2.147`

Caused by:
  failed to unpack entry at `libc-0.2.147/.cargo_vcs_info.json`

Caused by:
  failed to unpack `D:\Tools\rust\registry\src\index.crates.io-6f17d22bba15001f\libc-0.2.147\.cargo_vcs_info.json`

Caused by:
  failed to set mtime for `D:\Tools\rust\registry\src\index.crates.io-6f17d22bba15001f\libc-0.2.147\.cargo_vcs_info.json`

Caused by:
  Incorrect parameter. (os error 87)
```

This is also the reason why I was trying to run `rustup update`.

### Steps

Compiler installation issue:
1. Have no installation of rust
2. Set the `CARGO_HOME` and `RUSTUP_HOME` to an external exFAT Drive
3. Run the rust installer with default option except for the toolchain (using GNU because I can't have MVSC compiler)

Compiler updating issue:
1. Have a working installation of rust in an external exFAT Drive
2. Try running `rustup update`

### Possible Solution(s)

The bug might occur because it requires Admin privilege (even tho I don't see why) or because it's an exFAT Drive

### Rustup version

```console
rustup 1.26.0 (5af9b9484 2023-04-05)
```

### Installed toolchains

```console
Default host: x86_64-pc-windows-msvc
rustup home:  D:\Tools\rust

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu (default)
stable-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-gnu (default)
rustc 1.70.0 (90c541806 2023-05-31)
```

**Comment by JojoFR1** [comment]
Small update cause this issue was moved from the rust repo, it seems like it can download without any problem a toolchain (was switching from MVSC to GNU), except it can't delete some tmp folders.

**Comment by JojoFR1** [comment]
Update 2: Apparently with some more research, rustup doesn't support exFAT file system, I will try to format my SSD. It's still kinda annoying but I understand, maybe add a notice if possible?

**Comment by ChrisDenton** [comment]
Ok, looking into it, the error originates in the [`hardlink_file`](https://github.com/rust-lang/rustup/blob/137a99be4f35a7ae04cf3278d765facf3f70f667/src/utils/utils.rs#L302) function. And the [error message is here](https://github.com/rust-lang/rustup/blob/137a99be4f35a7ae04cf3278d765facf3f70f667/src/errors.rs#L49-L50).

For Windows, a filesystem that does not support hard links should return an `io::Error` like this:

```rust
Os { code: 1, kind: Uncategorized, message: "Incorrect function." }
```

Rustup could handle that case by adding an extra note that suggests using NTFS or ReFS.

**Comment by JojoFR1** [comment]
It tells `Incorrect parameter` (did a quick translation from French to English so might not be exact)

Anyway I reformated my SSD to NTFS and it fixes everything, but a notice should be added I think, to avoid any confusion for other people.

**Comment by ChrisDenton** [comment]
Yeah, the actual message may vary depending on language and there are [a few different codes](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-) it could be depending on the OS version and driver (`1` and `87` are most likely I think).

But yes, my point is I think it should be possible to detect this situation and add a nice notice.

**Comment by JojoFR1** [comment]
Before closing this issues, because it's kinda fixed,  I would like to know if there's any plan on supporting exFAT file system? And how hard could it be to support it?

**Comment by workingjubilee** [comment]
In order to do its usual proxying antics and the like, rustup really requires some form of file to file linking. To support exFAT is to reimplement large amounts of filesystem logic.
