### ISSUE TITLE
Windows aarch64 is missing from Other Installation Methods

### ISSUE THREAD

**Issue by Alovchin91** [rust-lang/rustup#3406]
### Problem

A link to Windows aarch64 version of rustup-init.exe is missing from the [Other Installation Methods](https://forge.rust-lang.org/infra/other-installation-methods.html) page.

### Steps

1. Open [Other Installation Methods](https://forge.rust-lang.org/infra/other-installation-methods.html) page
2. Look for rustup-init.exe for Windows aarch64 (`aarch64-pc-windows-msvc`). It's not there.
3. Go to https://static.rust-lang.org/rustup/dist/aarch64-pc-windows-msvc/rustup-init.exe. It's there because [it is available](https://github.com/rust-lang/rustup/pull/3232).

### Possible Solution(s)

It looks like the list of available artifacts is populated from [this file](https://raw.githubusercontent.com/rust-lang/rustup.rs/stable/ci/cloudfront-invalidation.txt). I assume it's auto-generated, so the obvious solution is to make sure the `aarch64-pc-windows-msvc` artifacts gets in there.

### Notes

Please let me know the process of adding an artifact to that file. I will then open a PR with all the necessary changes.

### Rustup version

```console
1.26.0
```

### Installed toolchains

```console
N/A
```

**Comment by 0xPoe** [comment]
> It looks like the list of available artifacts is populated from [this file](https://raw.githubusercontent.com/rust-lang/rustup.rs/stable/ci/cloudfront-invalidation.txt). I assume it's auto-generated, so the obvious solution is to make sure the `aarch64-pc-windows-msvc` artifacts gets in there.

Probably it does not relate to this file. Because we also do not have `aarch64-apple-darwin` here. But we can find it on [Other Installation Methods](https://forge.rust-lang.org/infra/other-installation-methods.html) page. So maybe we only need to update that page.

**Comment by Alovchin91** [comment]
@hi-rustin Hmm, I see what you mean. [This page](https://rust-lang.github.io/rustup/installation/other.html) indeed simply contains links to the installers, but [this page](https://forge.rust-lang.org/infra/other-installation-methods.html) is apparently generated by [this script](https://github.com/rust-lang/rust-forge/blob/master/blacksmith/src/lib.rs), and it's actually also missing `aarch64-apple-darwin`. I'm gonna open some pull requests now 😅

**Comment by rbtcollins** [comment]
@Alovchin91 so it seems the changes are in different repos? Can we close this bug?

**Comment by Alovchin91** [comment]
Hi @rbtcollins,

Both files to be changed are in fact in this repo, and I also would like to investigate [this issue](https://github.com/rust-lang/rustup/issues/3334) first before adding links to the Windows aarch64 Rustup, so I’d appreciate it if this bug could stay open for a bit 😊 I’ll try to get there soon.

**Comment by rami3l** [comment]
Closed by #3854.

It might take a while before https://rustup.rs gets properly updated. For the moment being, please download the artifact directly from https://win.rustup.rs/aarch64.

**Comment by Snazzie** [comment]
still not on main site

**Comment by rami3l** [comment]
> still not on main site

@Snazzie This is expected, since this will be included as a part of the v1.28.0 release, as per the assigned milestone. Sorry for the inconvenience!
