### ISSUE TITLE
Explain what is "WSL" in your issue template

### ISSUE THREAD

**Issue by safinaskar** [rust-lang/rustup#3414]
### Problem

You have issue template for WSL problems `wsl_panic.yml`. Your template mentions "WSL 1". What is "WSL 1"? Unfortunately, this can mean two different things:
- WSL 1, as opposed to WSL 2. (WSL 1 did not contain real Linux kernel, but WSL 2 did)
- WSL 1.0.0 released in 2022
See this thread https://github.com/microsoft/WSL/discussions/9155#discussioncomment-4172347 for more details.
So, please, fix your template

### Steps

-

### Rustup version

```console
-
```

### Installed toolchains

```console
-
```

**Comment by rbtcollins** [comment]
In the template itself this is explained.

**Comment by safinaskar** [comment]
No, the template just says "WSL1"

**Comment by rbtcollins** [comment]
If you'd like to put up a patch changing .github/ISSUE_TEMPLATE, we can review it. I'm clearly not understanding your concern at the moment, and discussing the code itself may be easier.

**Comment by ChrisDenton** [comment]
WSL1 and WSL2 are well understood terms, imho. Microsoft's docs use them consistently and even the linked WSL repo uses them extensively in docs and labels.

The fact that the WSL application is now version 1.2.5 is some interesting trivia but I'm not convinced it's relevant to most people. At least I've not seen it cause problems yet. In any case I think it better to be consistent with Microsoft's docs.
