### ISSUE TITLE
Upstream a bug fix for platform detection on MacOS

### ISSUE THREAD

**Issue by davidanthoff** [rust-lang/rustup#3419]
The Julia programming language has a tool Juliaup which was not only heavily inspired by rustup, but I also copied the [rustup-init.sh](https://github.com/rust-lang/rustup/blob/master/rustup-init.sh) script as a starting point. First of all: thanks so much for an awesome project, the inspiration and the code, it made building Juliaup sooo much easier!

We recently fixed a pretty bizzar corner case bug with the shell script re platform detection, and I just thought I'd let you know in case you want to copy that over into your `rustup-init.sh` :) The PR is https://github.com/JuliaLang/juliaup/pull/701.

**Comment by StefanKarpinski** [comment]
Might be nice to factor some of the gnarly platform-detection functionality into a separate file that can be shared between the languages so that fixes are easier to share, but maybe would add too much overhead.

**Comment by rbtcollins** [comment]
This would be great to turn into a PR - thank you!

**Comment by rbtcollins** [comment]
@davidanthoff thank you for this - you might want to see our diff - we found additional corner cases in the approach in your patch.
