### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Draco-max** [rust-lang/rustup#3425]
navigator.platform:
Linux armv81
navigator.appVersion:
5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36

**Comment by rami3l** [comment]
Hi! I don't quite get what you mean by that... Are you posting something by accident? :)

**Comment by rbtcollins** [comment]
Please reopen if this was intended to be a bug report here.

**Comment by deeshazlanchong-eng** [comment]
Nj
