### ISSUE TITLE
Provide option to skip hardware detection for rustup-init.sh

### ISSUE THREAD

**Issue by russiandesman** [rust-lang/rustup#3428]
### Problem you are trying to solve

Having chrooted to mounted os image with qemu-arm-static in place
Trying to complete rust installation, as out-of-apt version is tooo old (cryptography dependency)
Detection of bitness and architecture performed based on procfs reading, which in chrooted environment point to host's procfs.
The detection fails.
Installer then tries to download some default binaries which is not what is needed.

### Solution you'd like

Provide an option to give architecture and bitness and whatever is needed as a command line option to installer script. OR provide packaged Rust via OS repos (ppa: for debian\ubuntu for example)

### Notes

```
# ./rustup.sh -y
head: error reading '/proc/self/exe': Bad file descriptor
head: failed to close '/proc/self/exe': Bad file descriptor
rustup: unknown platform bitness
rustup: command failed: grep ^Features /proc/cpuinfo
info: downloading installer
info: profile set to 'default'
info: default host triple is armv7-unknown-linux-gnueabihf
warning: Updating existing toolchain, profile choice will be ignored
......
```

**Comment by rbtcollins** [comment]
The entire point of rustup.sh is to perform platform detection. If you know the platform you want, you can just download `https://static.rust-lang.org/rustup/dist/$platform_triple/rustup-init` directly. I'm not sure what value adding in command line options to take those values and create the URL for you is worth.

**Comment by rbtcollins** [comment]
Another thought is that it is possible to write a correct cpuinfo file to proc in your chroot; e.g. something like https://bugs.launchpad.net/ubuntu/+source/qemu-kvm/+bug/529008/comments/8

I'm going to close this, though if you disagree with the analysis please do reopen it (I think you should have access to do that) and continue the discussion.
