### ISSUE TITLE
'Proceed with installation (default)' prompt is ambiguous

### ISSUE THREAD

**Issue by Pomax** [rust-lang/rustup#3429]
### Problem

After customizing the installation, rustup shows "Proceed with installation (default)" instead of "Proceed with installation (custom)" suggesting it is going to ignore what the user has done and run a default installation instead.

### Steps

1. run rustup
2. when presented with the three options, pick `2) Customize installation`
3. customize the installation
4. observe the label for `1)` after customizing and being back in the menu

### Possible Solution(s)

Change the phrasing to `1) Proceed with installation (custom)` after the user has customized the installation.

### Notes

This is a text bug, not a code bug.

### Rustup version

```console
Windows 10 x64:


>rustup-init --version
rustup-init 1.26.0 (5af9b9484 2023-04-05)
```
```


### Installed toolchains

```console
none, rustup hasn't installed anything yet.
```

**Comment by Pomax** [comment]
Also looks like your issue template is broken, because I typed `none, rustup hasn't installed anything yet.` in the toolchain textbox.

**Comment by kLiHz** [comment]
I think this `(default)` means - when you press `Enter`, this option, which is `1) Proceed with installation`, will be executed as **default**.

If you are willing to look several lines above this `1) Proceed with installation (default)`, you'll see `Current installation options:` with the install configuration you just configured printed below.

**Comment by kLiHz** [comment]
I don't think there's a need to change this. Or, it's better to

change the phrasing to `1) Proceed with custom installation (defalut)` after the user has customized the installation.

**Comment by Pomax** [comment]
This isn't about what we know it means, it's to make sure that the text reflects what is about to happen, and while "default" almost certainly refers to "we will run 1 if you hit enter instead of (1)", the fact the the same menu has `customize` means that normal people who are installing rust because they've decided to learn programming will not read it that way, because that's not what the word means in a context that also has the word custom/customize.

Just because it makes sense to you personally, doesn't mean it won't confuse others. Consider people who are new to this, for whom it's _most_ important that phrasing makes sense. For seasoned programmers, none of this will matter.

Another way to fix this would be to move `default` way up, to be the first thing in the sentence. The one place it _can't_ be is at the end =)

**Comment by kLiHz** [comment]
I have to say, that I once also thought the 'customise' menu option should take effect directly after I've made my customisation. I even entered it twice to make sure that I did entered it right. If I was smart enough to notice the text changes just above the menus, I wouldn't have to do those useless efforts.

So I'm not saying this current design is perfect. But to change the text after customisation has been made, will probably need code changes. So I'd suggest change the `(default)` to `(or just press Enter)`, or simply remove it.

I was saying it's not necessary, because I think most people would notice this 'customise' option won't do any actual installation, after more than one try, so they would think otherwise, or just press enter, which leads just to the installation phase. 😌

**Comment by Pomax** [comment]
Of course it'll need code changes, but not a huge one, and rust releases are frequent, with constant changes landing. That's literally how updates work =) 

The problem with "it's not necessary" is that it's the wrong way to look at the problem. Can it be improved? Absolutely. Is it an easy improvement? Possibly. So mark it as enhancement, and when someone gets to it, that's an improvement for everyone. The worst thing to suggest is "let's not do this because we don't need it". No one _needs_ improvements if things technically already work, but they sure make things better for everyone.

And if the workflow is "people have to try an option to discover it does nothing", then that's flat out bad behaviour, and is always worth fixing. People should never have to "just try things" in the hopes that they work, a good installer helps the user do what needs to be done.

**Comment by rbtcollins** [comment]
I think the cognitive insight here is valid and would welcome a patch to improve the situation.

**Comment by brettearle** [comment]
G'day
Fairly new to rust but would love to give this a shot. 
Can I take this on?

**Comment by djc** [comment]
@brettearle sure, feel free to ask questions or just submit a PR and we'll review it!

**Comment by brettearle** [comment]
are we happy with
        "1) Proceed with installation (default - just press enter)"

in pull request #3673

**Comment by GinoMan** [comment]
> are we happy with "1) Proceed with installation (default - just press enter)"
> 
> in pull request #3673

I've not yet looked at the code-base, and I'm a rust novice, but I imagine that you would want the text to change based on whether the installation is customized. The sentinel for that change should only trigger if they actually make a change not if they merely enter the customization menu. Then the code that produces the menu text should check for the sentinel and if it's set, modify the text to say something like...

"1) Proceed with customized installation (default menu option)"

If it's not, then the text should read...

"1) Proceed with default installation (default option)"

I think that's the most clear way to implement this feature without confusion. 

We could also highlight the word "customized" using terminal colors/bolding if available from the terminal but I'm not sure if that might require too much extra effort than just a simple formatting and reference to constants or macros.

**Comment by Pomax** [comment]
I think we're maybe crossing the streams here: I filed this issue because you _don't_ want the word `default` in the actual option itself, since it cannot tell the user unambiguously what behaviour it's referring to. It will never be obvious that it's talking about option 1 being the default behaviour when you press enter without a _lot_ more text.

So instead, you want the menu _option_ to show whether or not the installation itself will be the standard installation, or a customized installation (so you want those words, e.g. `Proceed with standard installation`, but change that to `Proceed with customized installation` after the user's customized the options) and then you want the menu _prompt_ to tell the user what the default action will be when they press enter, like any other unix/linux CLI utility. E.g. something like `Pick the option you want to run, or press enter to run (1): ` or even the less user-friendly but pretty universal unixy/linuxy `Pick your option [1]`

(although given that Rust can be installed on decidedly not-unixy/linuxy operating systems, I'd advocate some version of the former. A few more words at the prompt is the right place to be explicit about what's going to happen based on user input at the prompt)

**Comment by brettearle** [comment]
Ok. I see what you mean
Will update later tonight (my time so about 12 hours from now) 

So flow your looking for (just for me mental model)
- needs dynamic standard/custom choice prompt based on users current choice
- if custom is chosen highlight that "make a choice or enter to go with (1)

**Comment by brettearle** [comment]
Hey @Pomax please checkout 
[new commit](https://github.com/rust-lang/rustup/pull/3673/commits/2cdea96ec18e240fe9b29a967ea1507d2f7a3a60 )

**Comment by Pomax** [comment]
Cheers - will have a look on Monday!

**Comment by Pomax** [comment]
Looks good to me, and I see someone also gave an approval: nicely done!
