### ISSUE TITLE
cannot run rustc on Raspberry PI

### ISSUE THREAD

**Issue by maxcli** [rust-lang/rustup#3431]
### Problem

Using Raspberry PI 4 with Raspbian GNU/Linux ver 11
I installed Rustc  : curl https://sh.rustup.rs/ -sSf | sh
I have /home/pi/.cargo/bin  in my path

pi@rpi4:~ $ rustc –version
error: command failed: 'rustc': No such file or directory (os error 2) 

note : I  installed rustup  after I installed rust

Any suggestions ?

### Steps

curl https://sh.rustup.rs/ -sSf | sh
rustc –version

### Rustup version

```console
1.26.0 (5af9b9484 2023-04-05)
```

### Installed toolchains

```console
pi@rpi4:~ $ rustup show
Default host: aarch64-unknown-linux-gnu
rustup home:  /home/pi/.rustup

stable-aarch64-unknown-linux-gnu (default)
(error reading rustc version)
```

**Comment by kLiHz** [comment]
Since you've mentioned "I installed rustup after I installed rust", where is your previous rust installation located and how is it installed?

And there might be ambiguity in your issue: you said you `installed Rustc : curl https://sh.rustup.rs/ -sSf | sh`, however this command will actually download and run rustup.

**Comment by rami3l** [comment]
It might be better to first use `which rustc` to see whether you are calling the `rustc` that comes with `rustup`.
If you want to manage `rust` installations with your own system package manager (e.g. `apt`), you should probably NOT use `rustup`; otherwise, you might need to uninstall `rust` system-wide (e.g. `apt uninstall rust`).

**Comment by rbtcollins** [comment]
What is the output of `rustup show` ? And `echo $PATH` ?

**Comment by maxcli** [comment]
CHMOD shows execute. 
Is my path wrong?

=======================================
rustup shosw :
Default host: aarch64-unknown-linux-gnu
rustup home:  /home/pi/.rustup

stable-aarch64-unknown-linux-gnu (default)
(error reading rustc version) <===================why **_do I get a error ?_**

========== ===================
my path: 
pi@rpi4:~ $ echo "$PATH"
/home/pi/.local/bin:/home/pi/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/snap/bin

sudo find shows rustc in multiple locations :

/snap/rustup/1023/bin/rustc
/snap/bin/rustc
/home/pi/.cargo/bin/rustc
/home/pi/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/rustc
/home/pi/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/share/doc/rust/html/rustc

======================================

I initially installed rustc like this : 
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
==================================================
"which rustc" shows
/home/pi/.cargo/bin/rustc

**Comment by zedifen** [comment]
Can you try running `/home/pi/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/rustc` directly and see what happens?

And have you tried reinstalling rustup? Like, run `rustup self uninstall` then install rustup and the toolchain again by `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`.

**Comment by maxcli** [comment]
Hi Zedifen,

Same error when I run from other folder : 
/home/pi/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/rustc --version
-bash: /home/pi/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/rustc: No such file or directory

============================================================

I ran  : rustup self uninstall . 
Then  I tried to install -  it saw this message below. Should I set RUSTUP_INIT_SKIP_PATH_CHECK to yes  ?

 
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Aug 14 08:59:08 2023
pi@rpi4:~ $ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer
warning: it looks like you have an existing installation of Rust at:
warning: /snap/bin
warning: It is recommended that rustup be the primary Rust installation.
warning: Otherwise you may have confusion unless you are careful with your PATH
warning: If you are sure that you want both rustup and your already installed Rust
warning: then please reply `y' or `yes' or set RUSTUP_INIT_SKIP_PATH_CHECK to yes
warning: or pass `-y' to ignore all ignorable checks.
error: cannot install while Rust is installed

**Comment by zedifen** [comment]
Do you remember installing Rust via snap in the past? As the message suggests, if you're using rustup then I think it's better to only use rustup to avoid conflicts.

You can try `sudo snap list` to see which packages are installed and remove it using `sudo snap remove <package-name>`.

**Comment by maxcli** [comment]
ok, I ran sudo snap remove rustup , 
Then did install , and reboot. 
Now I see .cargo\in in my path
but rustc still has same error .

**Comment by rami3l** [comment]
> ok, I ran sudo snap remove rustup ,
> Then did install , and reboot.
> Now I see .cargo\in in my path
> but rustc still has same error .

This could mean that you have issues with your `/home/pi/.rustup/toolchains/stable-aarch64-unknown-linux-gnu` installation (probably permission-related ones, or you have a corrupted installation). I recommend uninstall the toolchain (`rustup toolchain uninstall stable`), install it again (`rustup default stable`) and see whether the output changes.

**Comment by zedifen** [comment]
Hi, @rami3l, it looks like they may already perform a reinstallation? Any idea of other reasons?

**Comment by rami3l** [comment]
@zedifen @maxcli 

The `(error reading rustc version)` happens when `rustc` can be executed (via a `rustup` subprocess) but there is not a single line of `stdout` output.
I believe this is because `/home/pi/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/rustc` gets executed but is somehow corrupted (or simply gets the wrong permission).

This is coherent with the original feedback, which is a single line of `stderr`:

```sh
error: command failed: 'rustc': No such file or directory (os error 2)
```

If I were you, I'll remove this `rustup` installation (together with `~/.cargo` and `~/.rustup`) and start over, as I said before.
However, if reinstalling cannot help, then I can only suggest recursively setting the permission of `/home/pi/.rustup` to something like `744`.

**Comment by zedifen** [comment]
I think `rustup self uninstall` does remove both *~/.cargo* and *~/.rustup*. @maxcli can you try calling `/home/pi/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/rustc` again and see what's the output?

Additionally, you can try using `file` or `ldd` on `/home/pi/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/rustc` and see what happens.

**Comment by maxcli** [comment]
I have a work around. Thanks for all your help.
I tried the install on a clean Raspberry pi, and it worked fine. 
pi@rpi3:~ $ rustc --version
rustc 1.71.1 (eb26296b5 2023-08-03)

**Comment by marcosfrenkel** [comment]
@maxcli what was your work around? I am facing the exact same error and after following this whole thread I still cannot figure it out

**Comment by zedifen** [comment]
Hi @marcosfrenkel it looks like they fixed the issue by doing a fresh install. For example you can try installing a fresh Raspberry OS and then run the rustup installation script again. 😊

**Comment by marcosfrenkel** [comment]
@zedifen Thanks for the reply! It wasn't fixed by that, but I found another solution. Basically you need to **not** do the default installation and select the arm version of rust for the pi. Here are more details: https://forums.raspberrypi.com/viewtopic.php?t=289963
