### ISSUE TITLE
Better handle `rustup show`/`rustup list`/`rustup toolchain show`/`rustup toolchain list`

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rustup#3432]
### Problem you are trying to solve

I always get the subcommands confused and type the wrong thing, I can't be the only one who does this

```sh
$ rustup list
error: Invalid value "list" for '<+toolchain>': "list" is not a valid subcommand, so it was interpreted as a toolchain name, but it is also invalid. To override the toolchain using the 'rustup +toolchain' syntax, make sure to prefix the toolchain override with a '+'

For more information try --help

$ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/tmgross/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin
stable-x86_64-unknown-linux-gnu
...

$ rustup toolchain show
error: Found argument 'show' which wasn't expected, or isn't valid in this context

USAGE:
    rustup toolchain <SUBCOMMAND>

For more information try --help

$ rustup toolchain list
stable-x86_64-apple-darwin
stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
...
```

### Solution you'd like

Either make "show" and "list" synonyms, or suggest the correct one when the wrong one is received.

`uninstall` and `remove` are in a similar situation (a `rm` alias that works for either would be nice too).

**Comment by rbtcollins** [comment]
Show and list do quite different things. I'm sorry that the `rustup` UI is confusing in this manner.

The UI started out quite adhoc but some time ago got organised into the current structure, which for many things has them in a hierarchy of `rustup` `TYPE` `VERB`. So `rustup toolchain uninstall` uninstalls a toolchain and `rustup self uninstall` uninstalls rustup itself.

`show` isn't organised in that structure, like `update` and `default` and a number of other parts of the UI. It might be nice to revisit the structure and carve out a unifying approach for these multi-object/multi-type operations

`show` is showing all the contextual information available to rustup - its configuration, installed toolchains, directory overrides and the like.

`toolchain list` is showing the list of installed toolchains.

So they have very different intents and uses. I don't think `rustup list` should perform a `show`; nor would `rustup toolchain show` make sense as a synonym for list. An in fact a `rustup toolchain show` could make sense as a way to get more information on a toolchain, so adding a subcommand that points you at `rustup toolchain list` today would perhaps set up some misleading expectations.

Regarding `toolchain uninstall` and `toolchain remove` - `uninstall` is the documented verb today, `toolchain remove` is a hidden synonym, and unlike `show` and `list` is close enough in meaning that that is fine.

We could add `toolchain rm` perhaps as another alias, I have no objection if you wanted to put up a PR for that.

With that said, I don't think there is any need for this open issue - such a PR can just reference the issue number, but there's no need to keep the issue around just in case someone decides to make the PR.
