### ISSUE TITLE
Launching `rustup` from `Command` does not return a colored output

### ISSUE THREAD

**Issue by Luni-4** [rust-lang/rustup#3433]
### Problem you are trying to solve

When I run this command:

```rust
Command::new("rustup")
        .args(["target", "add", target])
        .output()
        .expect("Failed to run rustup");
```

I cannot get a colored text as output. It does not happen when I run the same command directly from my terminal.

### Solution you'd like

Would it be possible to add a `--color` option even for the `rustup` installer? Thanks in advance!

**Comment by rami3l** [comment]
Most CLI apps detect whether they are running in a TTY environment and, if not, the output won't be colorized.

OTOH, it's definitely possible to force colorized output, but indeed this doesn't seem to be implemented in `rustup`.

`cargo` has `CARGO_TERM_COLOR=always` to do this, so I imagine a similar option can be added to `rustup`?

**Comment by rami3l** [comment]
It's definitely possible to force colorized output, though.
`cargo` has `CARGO_TERM_COLOR=always` to do this, so I imagine a similar option can be implemented in `rustup`.

**Comment by rami3l** [comment]
As a workaround: if you only want to run a subprocess with Rust while maintaining colored output, it's probably better not to capture the output and get the exit code only.

**Comment by rbtcollins** [comment]
I'm open to the idea of a variable forcing colorisation.

I would rather that we implemented a programmatic interface (something that doesn't exist at all today) and then pushed IDE integration and other wrapping code to use that and do their own UX.

**Comment by Luni-4** [comment]
Thanks a lot for implementing this feature! Could you please explain somewhere how to use that?

**Comment by rami3l** [comment]
@Luni-4 Just run with the environment variable `RUSTUP_TERM_COLOR=always`.
