### ISSUE TITLE
Document how to install (and use) `rustup` with `brew`

### ISSUE THREAD

**Issue by rami3l** [rust-lang/rustup#3460]
### Problem you are trying to solve

AFAIK, the topic of installing and using `rustup` along with homebrew (`brew`) is not covered anywhere in the public docs, but it is also a common source of confusion among macOS users wanting to learn about Rust (https://github.com/rust-lang/rustup/issues/3458, [^1]).

[^1]: https://users.rust-lang.org/t/compile-failed-with-target-aarch64-linux-android/92439/14

### Solution you'd like

I am looking forward to some doc improvements in this respect.

**Comment by ChrisDenton** [comment]
Does homebrew maybe have documentation that can be linked to?

**Comment by rami3l** [comment]
@ChrisDenton

It's possible to add a `def caveats` block in `rustup`'s homebrew manifest. For example, `openjdk` has the following:

```
For the system Java wrappers to find this JDK, symlink it with
    sudo ln -sfn $HOMEBREW_PREFIX/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
```

However, I'm afraid that this still lacks discoverability.

Also, the generation of the `rustup` link to the original `rustup-init` binary should not be restricted to one package manager, so I think probably this is better documented in the user guide or somewhere similar...

**Comment by rami3l** [comment]
I think I will probably do the following as well:

- [x] Add a similar message to `brew`'s `rustup-init` package's `caveats` section suggesting that people should run `rustup-init` at least once instead of staring at the empty output of `which rustup`.
- [ ] If #3466 gets merged: add a link to the corresponding section of the user guide to the `caveats`.
