### ISSUE TITLE
[Feature] add to Nushell's PATH as well

### ISSUE THREAD

**Issue by danimesq** [rust-lang/rustup#3472]
I believe Nushell (made in the very Rust) deserve this consideration, as Bash does already.

**Comment by rami3l** [comment]
Hi! Thanks a lot for filing this issue!

I agree that in the long run, it is definitely worthwhile adding integration of non-POSIX shells such as  `nu`, `fish` (#478, #2995, #3108), `tcsh` (#3413), `ion`, `pwsh`, etc., but unfortunately, non-POSIX shells have not been assessed for `rustup` integration yet.

Once the first PR is in place, I believe the rest will be much easier (currently the best effort so far seems to be #3108). Please stay tuned!

**Comment by oneplusiota** [comment]
I would love to take this issue. I'm new to open source so please correct me anywhere I'm not right?

**Comment by Fishrock123** [comment]
Now that `fish` is integrated it seem like it would be a good time to look at this again?

**Comment by rami3l** [comment]
@oneplusiota Would you like to work on this one?

**Comment by chicks-net** [comment]
I'm interested in tackling this.  Any concerns?

**Comment by rami3l** [comment]
> I'm interested in tackling this.  Any concerns?

Please go ahead and feel free to use #3108 as your reference :)

**Comment by chicks-net** [comment]
Thanks for the ok to get started.

I have been working on this.  There is no progress to show yet, but I think I can figure this out.
