### ISSUE TITLE
When `rustup update` fails, it doesn't return an exit code that indicate failure

### ISSUE THREAD

**Issue by dzamlo** [rust-lang/rustup#3476]
### Problem

When `rustup update` fails, it doesn't return an exit code that indicate failure but instead returns 0.

### Steps

1. Be in a situation where `rustup update` fails, for example by disabling your network connection
2. Run `rustup update`
3. The command returns the exit code 0, or success

### Possible Solution(s)

Return an exit code different than 0 in case of failure

### Rustup version

```console
rustup 1.26.0 (2023-05-04)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.72.0 (5680fa18f 2023-08-23)`
```

### Installed toolchains

```console
Not relevant
```

**Comment by rami3l** [comment]
Thanks for @roife's confirmation: this issue doesn't seem to be reproducible with the official prebuilt binary, so this could be a specificity of the `no-self-update` feature.

**Comment by rami3l** [comment]
As a matter of fact, the following line (L295):
https://github.com/rust-lang/rustup/blob/4149df64251e674058ebc6e5a6e6cc07b07938cd/src/cli/common.rs#L290-L296
... has muted all failures during the update, which is quite inappropriate.
