### ISSUE TITLE
Advertise immutable per-version URLs for artefact downloads

### ISSUE THREAD

**Issue by huonw** [rust-lang/rustup#3484]
### Problem you are trying to solve

I'm helping with https://github.com/pantsbuild/pants/pull/19868 which sets up a hermetic installation of Rust within the Pants build system. To do this, we're downloading `rustup-init`, verifying its length and hash, and then executing that to install the appropriate Rust components. This gives us a verified chain for the Rust toolchain (Pants checks it's got the right rustup binary via hash, and rustup checks it has got the right Rust binary internally).

However, it looks like the URLs on https://rust-lang.github.io/rustup/installation/other.html such as https://static.rust-lang.org/rustup/dist/aarch64-apple-darwin/rustup-init do not include a version identifier. From this, I am inferring that they are overwritten when a new version is published, and thus the hash will change, breaking any builds that attempt to download and verify.

### Solution you'd like

URLs that are immutable (always point to the same artefact, once created), in addition to the current ones that seem to be "latest".

This would let us pin builds to a particular version of Rustup, and upgrade on our own cycle as required.

### Notes

Maybe there's already immutable URLs available? If so, this is a documentation issue! I couldn't find it (nor could I find an existing issue about it, but I might've missed it)

**Comment by thejcannon** [comment]
I just found https://static.rust-lang.org/?prefix=rustup/archive/ so I think it may just be a documentation issue? :smile:

**Comment by rami3l** [comment]
@thejcannon Thanks for filing this issue! I'll definitely have a look at this after the `rustup` project maintainer bandwidth increase.

**Comment by rbtcollins** [comment]
I think documenting where the old releases are in our developer docs would be super helpful. I've had to figure this out myself from time to time.

**Comment by rami3l** [comment]
Claim.

**Comment by rami3l** [comment]
@rbtcollins Wouldn't it be better if I add those next to the [Manual Installation](https://rust-lang.github.io/rustup/devel/installation/other.html#manual-installation) section in the user guide instead?

---

@thejcannon I just found out that there _**is**_ a link in the section above, but it's at the very bottom and I didn't even know it existed! I'll make a PR to clarify things nonetheless.
