### ISSUE TITLE
[1.26.0] - unreleased

### ISSUE THREAD

**Issue by bestia-dev** [rust-lang/rustup#3485]
### Problem you are trying to solve

On the [Changelog](https://github.com/rust-lang/rustup/blob/master/CHANGELOG.md) page states

[1.26.0] - unreleased

But it IS released. When I ask on my system

```bash
rustup -v
```

I get

```bash
rustup 1.26.0 (5af9b9484 2023-04-05)
The Rust toolchain installer
```

### Solution you'd like

Correct the phrase "unreleased"

**Comment by rami3l** [comment]
@bestia-dev Thanks a lot for filing this issue!
