### ISSUE TITLE
aarch64 toolchain is selected when running rustup in an armv7 docker container on an aarch64 host

### ISSUE THREAD

**Issue by alex** [rust-lang/rustup#3487]
### Problem

When `rustup` is run in an armv7 docker container, which is running on an aarch64 host, it will select an aarch64 toolchain, instead of selecting an arm32 one.

### Steps

1. `sudo docker run --platform=linux/arm/v7 --rm -it ubuntu:jammy`
2. `apt update && apt install curl`
3. `curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable --profile minimal`

You will see:

```
root@967b67561059:/# curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable --profile minimal
info: downloading installer
info: profile set to 'minimal'
info: default host triple is aarch64-unknown-linux-gnu
info: syncing channel updates for 'stable-aarch64-unknown-linux-gnu'
```

However it should be selecting an arm32 host triple.

(Note that it'll also hang due to https://github.com/rust-lang/rustup/issues/3122, but that's a separate issue.)

### Rustup version

```console
rustup-init 1.26.0 (5af9b9484 2023-04-05)
```

### Installed toolchains

```console
n/a
```

**Comment by rami3l** [comment]
@alex Thanks a lot for your report!

This is a known issue and I'm willing to look into it when I have time to do so. Please refer to #3307 for further updates [^1] :)

[^1]: Would you be so kind to close this issue? Our main maintainer here has limited bandwidth these days and it would be so nice if you can do us a favor and close this issue as duplicate. Thanks again 🙏

**Comment by alex** [comment]
My apologies for not noticing this is a duplicate! Closing now.
