### ISSUE TITLE
https://www.facebook.com/profile.php?id=100009599046965&mibextid=ZbWKwL

### ISSUE THREAD

**Issue by shehab1994sh** [rust-lang/rustup#3496]

**Comment by rami3l** [comment]
@rbtcollins I believe we have encountered a spam here.

**Comment by shehab1994sh** [comment]
> @rbtcollinsأعتقد أننا واجهنا بريدًا عشوائيًا هنا.

من فضلك اذا انت تستطيع مساعدتي بمعرفه بريدي الالكتروني المسجل في معرف الفيس بوك هذا ساكون شاكرا لك
