### ISSUE TITLE
The test `toolchain_broken_symlink` is failing on Windows

### ISSUE THREAD

**Issue by majaha** [rust-lang/rustup#3516]
The test `suite::cli_misc::toolchain_broken_symlink` is failing on my Windows 10 machine.

I tested this on commit b5d74ac69307de29cee586c779bdb6b3aee7f7af

I ran `cargo test --features=test toolchain_broken_symlink` and got this output:

```
...
---- suite::cli_misc::toolchain_broken_symlink stdout ----
ran: rustup ["set", "default-host", "x86_64-pc-windows-msvc"]
inprocess: true
status: Some(0)
duration: 0.170s
stdout:
====

====

stderr:
====

====

ran: rustup ["set", "auto-self-update", "disable"]
inprocess: true
status: Some(0)
duration: 0.056s
stdout:
====

====

stderr:
====
info: auto-self-update mode set to 'disable'

====

thread 'suite::cli_misc::toolchain_broken_symlink' panicked at tests\suite\cli_misc.rs:680:35:
called `Result::unwrap()` on an `Err` value: Os { code: 1314, kind: Uncategorized, message: "A required privilege is not held by the client." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    suite::cli_misc::toolchain_broken_symlink

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 373 filtered out; finished in 1.71s

error: test failed, to rerun pass `--test test_bonanza`
```

**Comment by ChrisDenton** [comment]
You need to enable "Developer Mode" in the settings to allow creating of symlinks as a non-privileged user.

**Comment by majaha** [comment]
Ah, I thought it would be something like that.

Is it worth disabling this test on Windows? Or is it possible to detect that setting and suppress the failure?

**Comment by ChrisDenton** [comment]
It's important that this test is run in CI on a Windows host. It could perhaps pass the test if it's not in CI and creating a symlink returns `ERROR_PRIVILEGE_NOT_HELD` (aka error code `1314`).

**Comment by majaha** [comment]
That sounds like a good course of action to me.

**Comment by djc** [comment]
@majaha would you be able to submit a PR for this? IIRC we can detect CI environments by the existence of a `CI` environment variable.

**Comment by majaha** [comment]
I've had a deeper look into this and found that there's actually another underlying issue: rustup on windows doesn't use Window's symbolic links, it uses "directory junctions", which are somewhere between a hard link and a symbolic link, and usually don't need permissions. The test should be using those instead (and preferably using the same code-path as rustup itself uses to create them). I'll try to come up with a patch for that.

**Comment by majaha** [comment]
Okay, I've created a PR that fixes this over here: https://github.com/rust-lang/rustup/pull/3522
