### ISSUE TITLE
Suggest installing mingw when using windows-gnu abi

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rustup#3520]
### Problem you are trying to solve

Currently [the Windows docs say](https://rust-lang.github.io/rustup/installation/windows.html):

> No additional software installation is necessary for basic use of the GNU build.

While this is strictly true, the gnu libraries and tools shipped with Rust are intended to be minimal. Importantly, exactly what is shipped may change from version to version depending on internal implementation details. And even if something is bundled with Rust, it may potentially be stripped down for a single use case or else be an older version (or both).

### Solution you'd like

Make clear that the user may want to install [msys2](https://msys2.github.io/) with mingw tools, even if it's not strictly necessary.

**Comment by rami3l** [comment]
Claim.
