### ISSUE TITLE
`cargo clippy` appears to be using another toolchain than specified

### ISSUE THREAD

**Issue by marcbrevoort-cyberhive** [rust-lang/rustup#3525]
### Problem

Running `cargo clippy`, it reports
```
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-musl`
```
This target is already on my machine,
```
$ rustup target add x86_64-unknown-linux-musl
info: component 'rust-std' for target 'x86_64-unknown-linux-musl' is up to date
```
When running `--verbose`, it appears to be running clippy from the wrong toolchain:

```
     Running `/home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/clippy-driver
```
     
Sure enough, it is the `stable-x86_64-unknown-linux-gnu` toolchain that doesn't have `std` compiled:

```
toolchain 'stable-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target 'stable-x86_64-unknown-linux-gnu'
```

Listing the toolchains gives me (amongst others),
```
$ rustup toolchain list
stable-x86_64-unknown-linux-gnu (override)
stable-x86_64-unknown-linux-musl (default)
```

### Steps

1. Try running cargo clippy, 
2. observe lots of errors related to component `std` not having been compiled.

### Notes

I'm out of ideas troubleshooting this.

### Rustup version

```console
$ rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.73.0 (cc66ad468 2023-10-03)`
```

### Installed toolchains

```console
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/mrjb/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
stable-x86_64-unknown-linux-musl (default)
nightly-x86_64-unknown-linux-gnu
1.71.1-x86_64-unknown-linux-gnu
1.72.0-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

aarch64-unknown-linux-gnu
arm-unknown-linux-gnueabi
arm-unknown-linux-gnueabihf
arm-unknown-linux-musleabihf
armv7-unknown-linux-gnueabihf
i686-linux-android
x86_64-linux-android
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (directory override for '/home/mrjb/git/connect/main/cyberhive-meshvpn-client')
rustc 1.73.0 (cc66ad468 2023-10-03)
```

If, however, I try to change to musl for the active toolchain then I get

```console
$ rustup override set stable-x86_64-unknown-linux-musl
info: using existing install for 'stable-x86_64-unknown-linux-musl'
info: override toolchain for '/home/mrjb/git/connect/main/cyberhive-meshvpn-client' set to 'stable-x86_64-unknown-linux-musl'

  stable-x86_64-unknown-linux-musl unchanged - (error reading rustc version)

$ cargo clippy
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo)
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_Resume: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetIPInfo: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetDataRelBase: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetRegionStart: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_SetGR: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_FindEnclosingFunction: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetTextRelBase: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_DeleteException: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_RaiseException: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetIP: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_Backtrace: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetCFA: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetLanguageSpecificData: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_SetIP: symbol not found
```

**Comment by rami3l** [comment]
Hmmm, `rustup toolchain list` giving `stable-x86_64-unknown-linux-gnu (override)` means that `rustup` is invoking the `linux-gnu` build of clippy as expected (you manually overridden it to be so, the default has always been `linux-musl`), so it's probably not a `rustup` bug?

I see two things that might need to be corrected:
1. The [`E0463`](https://doc.rust-lang.org/error_codes/E0463.html). This IIRC is a `rustc` thing, and it seems to me that the instructions are wrong. Maybe another issue related to https://github.com/rust-lang/rust/issues/91600? I suggest that you report this issue under that.
2. The `libgcc_s_so.1` thing is probably https://github.com/rust-lang/rust/issues/108907. Would you mind telling us what OS you are using, and why you have both `linux-gnu` and `linux-musl` installed as **host** [^1]? There's probably something wrong with your environment setup...

[^1]:  If you're running Ubuntu for example, then you should install the `linux-gnu` **host** with the `linux-musl` **target** and cross-compile for that.

**Comment by marcbrevoort-cyberhive** [comment]
Trying this on ubuntu.
I only want to build with the musl toolchain (call it legacy reasons) but Cargo seems to disagree and insists on installing the gnu toolchain. Which leads me down the following path...

1. remove all toolchains except `stable-x86_64-unknown-linux-musl`.
```
$ rustup toolchain list
stable-x86_64-unknown-linux-musl (default)
$ cargo clippy
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
^C
```
Nope, didn't ask for that.
```
$ rustup target add x86_64-unknown-linux-musl
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
```
no, wait what?
```
$ rustup override set stable-x86_64-unknown-linux-musl
$ rustup toolchain list
stable-x86_64-unknown-linux-gnu
stable-x86_64-unknown-linux-musl (default) (override)
```
No, I don't want the gnu toolchain, go away!
```
$ rustup toolchain remove stable-x86_64-unknown-linux-gnu
$ rustup toolchain list
stable-x86_64-unknown-linux-musl (default) (override)
```

So now I arrive at a list containing just the toolchain I'd like to use... can we behave now?
```
$ cargo clippy
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo)
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_Resume: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetIPInfo: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetDataRelBase: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetRegionStart: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_SetGR: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_FindEnclosingFunction: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetTextRelBase: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_DeleteException: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_RaiseException: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetIP: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_Backtrace: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetCFA: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_GetLanguageSpecificData: symbol not found
Error relocating /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo: _Unwind_SetIP: symbol not found
```
Computer says no.

From https://github.com/rust-lang/rust/issues/108907: 
> it is not necessary to install a toolchain that differs from your host

But it is. If we have three targets (say Windows, Mac and Linux) then we want to be able to build code _for_ any target _from_ any target (or at a minimum, to run `cargo check`/`cargo clippy` for a given target in a pre-commit hook, as this will save slow CI roundtrips). If each target needs to be supported as cross compile anyway, then a host might as well cross compile for itself. This saves us implementing all our build scripts twice (once to build native, once as cross compile). That is, "Everything is a cross compile" is simply an application of DRY.

**Comment by rami3l** [comment]
@marcbrevoort-cyberhive Thanks for your clarification! I can see what you are facing right now.

> From [rust-lang/rust#108907](https://github.com/rust-lang/rust/issues/108907):
> 
> > it is not necessary to install a toolchain that differs from your host
> 
> But it is. If we have three targets (say Windows, Mac and Linux) then we want to be able to build code _for_ any target _from_ any target (or at a minimum, to run `cargo check`/`cargo clippy` for a given target in a pre-commit hook, as this will save slow CI roundtrips). If each target needs to be supported as cross compile anyway, then a host might as well cross compile for itself. This saves us implementing all our build scripts twice (once to build native, once as cross compile). That is, "Everything is a cross compile" is simply an application of DRY.

I see what you mean. However, it looks like you've gone into an XY problem. What you want might probably be adding new target triples under the current toolchain (in the case of Ubuntu, `linux-gnu`) using `rustup target add`, rather than installing other host toolchains (which is a completely different thing).

> If each target needs to be supported as cross compile anyway, then a host might as well cross compile for itself.

As a matter of fact, you can "cross compile" for the native target! Once you have added all the target triples that you need, you can always use the `--target=` option in `cargo`, regardless of whether that target is native to your platform or not, and the output paths are also very consistent.

For example, I have the following CI steps in my own project [`pacaptr`](https://github.com/rami3l/pacaptr/blob/8540ac12a6c9f5a828b36bb305bab6d3c8ab7b3f/.github/workflows/publish.yml#L55-L70):

```yml
# This step just installs the default toolchain
# and adds all the `targets` below that toolchain.
- name: Setup Rust
  uses: dtolnay/rust-toolchain@stable
  with:
    targets: '${{ matrix.target }}'

- name: Build
  run: >
    cargo build --verbose --bin=pacaptr --release --locked --target=${{
    matrix.target }}

- name: Upload artifacts
  uses: actions/upload-artifact@v3
  with:
    name: 'pacaptr-${{ matrix.target }}'
    # The path is in the same format even for native builds.
    path: 'target/${{ matrix.target }}/release/pacaptr*'
    retention-days: 1
```

... and for the `matrix` I've got 2 native and 4 cross targets actually, but we don't care anyway since they look the same:

```yml
matrix:
  include:
    - os: windows-latest
      target: x86_64-pc-windows-msvc
    - os: windows-latest
      target: aarch64-pc-windows-msvc
    - os: macos-latest
      target: x86_64-apple-darwin
    - os: macos-latest
      target: aarch64-apple-darwin
    - os: ubuntu-latest
      target: x86_64-unknown-linux-musl
    - os: ubuntu-latest
      target: aarch64-unknown-linux-musl
```

---

Below are some more clarifications that you might find useful:

> Trying this on ubuntu. I only want to build with the musl toolchain (call it legacy reasons) but Cargo seems to disagree and insists on installing the gnu toolchain.

`rustup` has the notion of default host target. Since you're using Ubuntu, it is `x86_64-unknown-linux-gnu` by default (which you could see when you ran `rustup-init`) and you didn't change it since, so we expect to have at least one toolchain with that triple in order not to break other things. You can use [`rustup set default-host`](https://rust-lang.github.io/rustup/installation/windows.html) to change this setting if you want.

> ```
> $ cargo clippy
> Error loading shared library libgcc_s.so.1: No such file or directory (needed by /home/mrjb/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo)
> ...
> ```

If you really want to use `linux-musl` in host mode on Ubuntu, this error might be an [indicator that you haven't installed `musl`](https://github.com/rust-lang/rust/issues/108907), which IIRC is a requirement to use it in host mode. It's **highly not recommended** though, since you should be fine in most cases with the `linux-gnu` toolchain with extra target triples, as stated above.

**Comment by marcbrevoort-cyberhive** [comment]
Hello @rami3l - Thanks for your elaborate reply. It will take some time to parse it fully but rest assured I will. I'll get back to you with how it went.

**Comment by marcbrevoort-cyberhive** [comment]
Okay, so the short version is that if I'm in a situation where clippy "can't find crate for `std`" and I don't mind the `gnu` toolchain being used for clippy, I can just

- `rustup default stable-x86_64-unknown-linux-gnu`
- `rustup override set stable-x86_64-unknown-linux-gnu`
- `remove .cargo/config.toml`

And voilá, all is hunkydory for at least native (non cross-compile) builds.

When I do subsequently do the following to force the `musl` target,

- `rustup toolchain remove stable-x86_64-unknown-linux-gnu`
- `rustup toolchain add stable-x86_64-unknown-linux-musl`
- `rustup target add stable-x86_64-unknown-linux-musl`
- `rustup override set stable-x86_64-unknown-linux-musl`
- `rustup default stable-x86_64-unknown-linux-musl`

then along the way I get some errors, notably error: toolchain 'stable-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target 'stable-x86_64-unknown-linux-musl', everything breaks down, and sure enough, toolchain stable-x86_64-unknown-linux-gnu reappears.

if however I go back to the `gnu` toolchain as above and do `cargo clippy --target=cargo clippy --target=x86_64-unknown-linux-musl` then clippy _does_ run, but doesn't have `std`; At this point however, since I know the std toolchain works and is default, I _can_ `rustup target add x86_64-unknown-linux-musl`, and it _will_ install component `rust-std`, after which 
`cargo clippy --target=x86_64-unknown-linux-musl` works as expected.

From there on, it's a matter of setting the target in `.cargo/config.toml` with
```
[build]
target="x86_64-unknown-linux-musl"
```
(which is normally something our builds scripts would do for us)
and everything then works with `musl` as intended.

Thank you for your help with this!
