### ISSUE TITLE
unable to run installation script on loongarch64

### ISSUE THREAD

**Issue by yangy996** [rust-lang/rustup#3533]
### Problem

script:
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
error:
info: downloading installer
curl: (22) The requested URL returned error: 404
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/loongarch64-unknown-linux-gnu/rustup-init /tmp/tmp.10YqW6d8XY/rustup-init loongarch64-unknown-linux-gnu

### Steps

unknown

### Rustup version

```console
unknown
```

### Installed toolchains

```console
unknown
```

**Comment by rami3l** [comment]
@yangy996 Hi! Thanks for filing this issue!

It's a known issue which has been addressed in https://github.com/rust-lang/rustup/pull/3405. Hopefully, this problem will be automatically resolved on the next release of Rustup.

**Comment by rami3l** [comment]
Waiting for https://github.com/rust-lang/rustup/issues/3501 to land.
