### ISSUE TITLE
Meta: Consider introducing GitHub Merge Queue to the repo

### ISSUE THREAD

**Issue by rami3l** [rust-lang/rustup#3567]
> Maybe it's time to introduce a "conclusion" CI action and a merge queue. We already have `automerge=true` configured in renovate, but since there's no "conclusion" configured in our branch protection settings, auto-merging will not work. OTOH once that's been added, renovate will automatically put semver-compatible updates into the merge queue (cf. https://github.com/renovatebot/renovate/issues/20569).

_Originally posted by @rami3l in https://github.com/rust-lang/rustup/issues/3565#issuecomment-1845309099_

--- 

## Tasks

- [x] Merge https://github.com/rust-lang/rustup/pull/3582.
- [x] Merge #3633.
- [x] Tell the mods to enable GHMQ and to point the branch protection rules to the newly-added `conclusion` job.

**Comment by djc** [comment]
Sounds good to me!

**Comment by rami3l** [comment]
@djc For the record, an example of the `conclusion` step can be found in [PyO3](https://github.com/PyO3/pyo3/blob/42601f3af94242b017402b763a495798a92da8f8/.github/workflows/ci.yml#L452-L472), however this will probably require moving all CI workflows into a single file (which should be done with a refactoring of `ci/actions-templates/gen-workflows.sh`), so this might take a while.

**Comment by rami3l** [comment]
~~New concern raised in https://github.com/rust-lang/rustup/pull/3582#issuecomment-1877287794.~~

Update: Addressed in #3627.

**Comment by rami3l** [comment]
GHMQ is now online with "rebase and merge" as the default action.

Thanks a lot for your help and support, @jdno and @djc!
