### ISSUE TITLE
Remove frequent single semver-compatible dependent Renovate PRs

### ISSUE THREAD

**Issue by djc** [rust-lang/rustup#3623]
### Problem

We have (I think weekly?) scheduled "Lockfile maintenance" PRs but in addition to that we have these update PRs for every single semver-compatible update. IMO these are just noise and are completely unnecessary when we have regular lockfile update PRs. I've been staring at https://docs.renovatebot.com/ but it's not that obvious to me how to do this (maybe by restricting `minor` updates?).

@rami3l since I think you have better context on Renovate, have you figured out how to do this?

### Steps

1. Get frequent notifications from Renovate PRs

### Rustup version

```console
N/A
```

### Installed toolchains

```console
N/A
```

**Comment by rami3l** [comment]
Claim.

**Comment by rami3l** [comment]
Reopening due to the concern raised in https://github.com/rust-lang/rustup/pull/3630#issuecomment-1877852288.
