### ISSUE TITLE
Support for more NetBSD architectures

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rustup#3628]
### Problem you are trying to solve

I'd like to be able to install Rust on alternate architecture NetBSD hosts, and cross-compile alternate architecture NetBSD Rust applications from different architecture hosts.

### Solution you'd like

Port rustup to the new i586-unknown-netbsd and mipsel-unknown-netbsd targets.

### Notes

Rust 1.75.0 added new i586-unknown-netbsd and mipsel-unknown-netbsd targets:

https://doc.rust-lang.org/nightly/releases.html#version-1750-2023-12-28

**Comment by djc** [comment]
I don't think there's any "porting" involved. What have you tried that doesn't work?

**Comment by mcandre** [comment]
Rustup only reports the x86_64 architecture for NetBSD:

```console
$ rustup target list | grep -i netbsd
x86_64-unknown-netbsd
```

**Comment by rami3l** [comment]
> Rustup only reports the x86_64 architecture for NetBSD:
> 
> ```
> $ rustup target list | grep -i netbsd
> x86_64-unknown-netbsd
> ```

@mcandre According to rustc's target policy, rustup will only distribute precompiled toolchain artifacts for targets of tier 2 or higher. The two new targets you've mentioned are of tier 3, so you won't find precompiled artifacts for them, but this does not mean that they are not supported. If you'd like, you can always manually build artifacts for those targets and use them with rustup.

See: https://doc.rust-lang.org/nightly/rustc/platform-support.html
