### ISSUE TITLE
rustup can only be named "rustup-init".

### ISSUE THREAD

**Issue by Enaium** [rust-lang/rustup#3634]
### Problem

PS C:\Users\Enaium\Downloads> .\download.exe
error: unknown proxy name: 'download'; valid proxy names are 'rustc', 'rustdoc', 'cargo', 'rust-lldb', 'rust-gdb', 'rust-gdbgui', 'rls', 'cargo-clippy', 'clippy-driver', 'cargo-miri', 'rust-analyzer', 'rustfmt', 'cargo-fmt'

### Steps

Rename the rustup file to "download" (browsers sometimes can't parse the download filename)

### Possible Solution(s)

rename to "rustup-init"

### Rustup version

```console
rustup-init 1.26.0 (5af9b9484 2023-04-05)
```

### Installed toolchains

```console
error: error: Found argument 'show' which wasn't expected, or isn't valid in this context
```

**Comment by rami3l** [comment]
@Enaium Hi! Looks like you've gained some first-hand knowledge of `rustup`'s internals! 🎊

`rustup` is a multicall binary whose functionality depends exactly on how it's named, so the error message you see is there to prevent it from being renamed to something else.

For more details, see: https://flameeyes.blog/2009/10/19/multicall-binaries

If you have further concerns, please don't hesitate to ask! :)
