### ISSUE TITLE
warning: spurious network error (3 tries remaining): [7] Couldn't connect to server (Failed to connect to 127.0.0.1 port 4780 after 0 ms: Couldn't connect to server)

### ISSUE THREAD

**Issue by Rock0007** [rust-lang/rustup#3646]
Hey @flodiebold I'm new to rust language, I have been facing the following issue from the beginning, I couldn't able to run my rust code. Please guide me to come out of this.
![image](https://github.com/rust-lang/rustup/assets/78554483/4a177832-ab17-48bd-bae6-03c5e912f0aa)

**Comment by rbtcollins** [comment]
You have some sort of proxy / redirect configuration in place - see the server address that is failing - localhost port 4780. Crates.io is not at your localhost, nor is https on port 4780.

Rustup clearly hasn't caused this; I suggest you seek assistance on https://users.rust-lang.org/

**Comment by Rock0007** [comment]
As it is working on my WSL Linux, but not on Powershell.

**Comment by rami3l** [comment]
@Rock0007 I'm locking the conversation as it's a duplicate of a previously-filed invalid issue (#3645).

Please note that if you create another issue about this topic, you will be banned for spamming, sorry!
