### ISSUE TITLE
i can't rustup update

### ISSUE THREAD

**Issue by ghost** [rust-lang/rustup#3660]
### Problem

```
C:\Windows\System32>rustup update
info: syncing channel updates for 'stable-i686-pc-windows-gnu'
info: syncing channel updates for 'stable-x86_64-pc-windows-gnu'
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: checking for self-update

     stable-i686-pc-windows-gnu unchanged - rustc 1.75.0 (82e1608df 2023-12-21)
   stable-x86_64-pc-windows-gnu unchanged - rustc 1.75.0 (82e1608df 2023-12-21)
  stable-x86_64-pc-windows-msvc unchanged - rustc 1.75.0 (82e1608df 2023-12-21)

info: cleaning up downloads & tmp directories
thread 'main' panicked at 'Unable to clean up C:\Users\Elia\.rustup\tmp: Os { code: 145, kind: DirectoryNotEmpty, message: "The directory isn't empty" }', src\utils\utils.rs:650:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

i can't even remove it manually, Windows 11

### Steps

rustup update

### Rustup version

```console
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.75.0 (82e1608df 2023-12-21)`
```

### Installed toolchains

```console
Default host: x86_64-pc-windows-gnu
rustup home:  C:\Users\Elia\.rustup

installed toolchains
--------------------

stable-i686-pc-windows-gnu
stable-x86_64-pc-windows-gnu (default)
stable-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-gnu (default)
rustc 1.75.0 (82e1608df 2023-12-21)
```

**Comment by rami3l** [comment]
@Heliox01 Thanks for filing this issue! Could you please delete `C:\Users\Elia\.rustup\tmp` and try again?

**Comment by ghost** [comment]
i forgot to put it, i tried manually and it said error:0x80070091 i tried to restart the pc same error,i tried to delete it in provisory mode but it didn't work

edit: i tried with rmdir /s /q C:\Users\Elia\.rustup\tmp too but it says that the directory isn't empty, and it says that the file is used by another process but there is no rust process related  running

**Comment by ghost** [comment]
i removed after using iobit unlocker on the locked file,iobit unlocker said it was alreasdy unlocked but i unlocked it anyway and then i was able to delete it

**Comment by rami3l** [comment]
Sorry for your bad experience so far! I think this could be another instance of #988.

**Comment by rami3l** [comment]
Closing for now as a duplicate of #988. If you have more questions, please don't hesitate to ask! :)
