### ISSUE TITLE
Say what ought to happen when running rustup doc.

### ISSUE THREAD

**Issue by MrTheSaw** [rust-lang/rustup#3663]
### Problem you are trying to solve

On macOS.

I ran \"rustup doc --book\" on my command line. It returned, and nothing appeared to happen. Something did happen, the site is open on my browser, but I use desktops, and it doesn't raise things quite correctly (not rust's problem).

```
    If you are new to Rust consider running `rustup doc --book` to
    learn Rust.
✔ ~/src/CatHerd [master|✚ 1…2]
14:01 $ rustup doc --book
✔ ~/src/CatHerd [master|✚ 1…2]
```

### Solution you'd like

if the thing had printed "Opening the Rust Book in your browser", I would have slid over there, and all would be good.

**Comment by rami3l** [comment]
@MrTheSaw Thanks a lot for filing this issue!

This is indeed a valid point of improvement, I'll put it onto our roadmap.

**Comment by brettearle** [comment]
Gday,
Can I give this a try?

**Comment by brettearle** [comment]
This is a PR for this, happy to change it up if required
#3674
