### ISSUE TITLE
windows-gnu: Allow installing rust-mingw as a target component

### ISSUE THREAD

**Issue by amyspark** [rust-lang/rustup#3665]
### Problem

Currently, attempting to install `rust-mingw` as a per-target component fails with an error that looks like this:

```
error: toolchain 'stable-x86_64-pc-windows-gnu' does not contain component 'rust-mingw' for target 'i686-pc-windows-gnu'
```

This seems to be because it's expecting to be deployed against the *host* and not the target. The practical consequence is that `rustc` cannot find this linker, thus all crates yielding a cdylib fail linking because of https://github.com/rust-lang/rust/issues/94269.

### Steps

1. Run `rustup component add --target i686-pc-windows-gnu rust-mingw` inside `stable-gnu` or `stable-msvc`.

### Possible Solution(s)

Make `rust-mingw` available as an extension so that it's installable per target.

### Rustup version

```console
rustup 1.26.0 (5af9b9484 2023-04-05)
```

### Installed toolchains

```console
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Amalia\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu (default)
stable-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

i686-pc-windows-gnu
x86_64-pc-windows-gnu

active toolchain
----------------

stable-x86_64-pc-windows-gnu (default)
rustc 1.76.0 (07dca489a 2024-02-04)
```

**Comment by rami3l** [comment]
Thanks a lot for filing this issue!

Looks like there is #607 which also (unfortunately) belongs to part of the lost context across several team member changes :|

**Comment by rami3l** [comment]
I'm closing this one in favor of #607 which I have put on deck. Thanks again!
