### ISSUE TITLE
Prefer using symlinks on Windows

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rustup#3677]
### Problem you are trying to solve

On Windows rustup currently uses junction points exclusively. https://github.com/rust-lang/rustup/blob/d55d41c8f23a6aac4db8b9d5f9ba257c341e5d08/src/utils/raw.rs#L136-L141

(note: that comment is wrong, user symlinks can be enabled by granting a single permission or more recently by enabling developer mode)

Junction points are always absolute which makes moving rustup (e.g. when setting up a [dev drive](https://learn.microsoft.com/en-us/windows/dev-drive/)) a more fraught process than it needs to be.

### Solution you'd like

Use [symlink_dir](https://doc.rust-lang.org/std/os/windows/fs/fn.symlink_dir.html) and only fallback to juncture points if that fails.

**Comment by djc** [comment]
Would you be able to contribute some code in this direction? I don't have any Windows systems available to me to test.

**Comment by ChrisDenton** [comment]
For sure! I just wanted to make sure there were no objections.
