### ISSUE TITLE
Log the `registry` used when run `rustup update/install` (and other commands use registry).

### ISSUE THREAD

**Issue by Shylock-Hg** [rust-lang/rustup#3680]
### Problem you are trying to solve

I want to know the registry current used.

### Solution you'd like

Log to screen directly.

**Comment by rami3l** [comment]
@Shylock-Hg Thanks for filing this issue! May I ask what registry you are referring to?

**Comment by Shylock-Hg** [comment]
> @Shylock-Hg Thanks for filing this issue! May I ask what registry you are referring to?

I'm not sure what `rustup` called it. But `rustup` support to set it by environment variable `RUSTUP_UPDATE_ROOT` and `RUSTUP_DIST_SERVER`, or just means mirror site?

**Comment by rami3l** [comment]
@Shylock-Hg Sounds like a reasonable request! I'll put it onto our roadmap.

This should also help the users to see if they are switched to the `dev` environment or not, so useful for beta-testing as well.

**Comment by Moon6688** [comment]
=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
