### ISSUE TITLE
WSL installation should suggest use of POSIX `.` instead of  `source`

### ISSUE THREAD

**Issue by JavaGuy147** [rust-lang/rustup#3682]
### Problem you are trying to solve

Noticed when installing via the WSL instructions `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` that at the end of installation, the user is prompted to `source` a file if they want the current shell to be ready for use.

### Solution you'd like

This should be inclusive of all possible shells and distros by suggesting the POSIX `.` alternative. `source` and `.` are roughly equivalent in the popular bash shell, but this is not guaranteed for other shells.

**Comment by rami3l** [comment]
@JavaGuy147 Thanks a lot for filing this issue! We have changed the prompt accordingly in the upcoming 1.27 version:

https://github.com/rust-lang/rustup/blob/4f29ff801d613c2742904d7c3272a93d23347577/src/cli/self_update.rs#L221-L227

Also, you are welcome to test the new version yourself: https://internals.rust-lang.org/t/seeking-beta-testers-for-rustup-1-27-0/20352

Have a nice day :)
