### ISSUE TITLE
cargo don't immediately available in bash script  

### ISSUE THREAD

**Issue by q2333gh** [rust-lang/rustup#3684]
### Problem you are trying to solve

```bash
#!/bin/bash
curl https://sh.rustup.rs -sSf | sh -s -- -y
source "$HOME/.cargo/env"
cargo check
```
running the script says: ` sh: 3: cargo: not found`  
Although we can mannually cun `source "$HOME/.cargo/env"` i will work.
  but its not good for script automation . such as set up a new dev machine require as a single script.

### Solution you'd like

by exec `curl https://sh.rustup.rs -sSf | sh -s -- -y`  and `source "$HOME/.cargo/env"`  inside script
cargo should work inside a bash script session.

**Comment by djc** [comment]
Modifying the shell's environment isn't something we should take lightly, and I think it's better to leave that as an explicit decision on the user's part.

**Comment by q2333gh** [comment]
Ok . then i ll leave the option to user

**Comment by smoelius** [comment]
![Screenshot from 2024-03-03 12-56-08](https://github.com/rust-lang/rustup/assets/35515885/cc0b193e-cd2a-420c-beea-a5d6a06abdd9)
@djc Can I ask why you did this? It must provide some benefit. Can I ask what that is?

**Comment by djc** [comment]
Fair question -- not sure I can explain it well, it might just be OCD about getting things in the proper state. I guess when you're searching for an issue it feels like it can be helpful to distinguish issues that actually led to actions/code changes vs issues that were not actionable/duplicates/etc.

**Comment by smoelius** [comment]
Thank you very much for the explanation!
