### ISSUE TITLE
Concurrent `rustup toolchain add` overwrite each others downloads

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rustup#3690]
### Problem

Running multiple instances of `rustup toolchain add X` causes redundant downloads and installation errors. 

This problem can happen when tests or CI tooling run concurrently tries to automatically install required versions of Rust.

```text
 error: component download failed for cargo-aarch64-apple-darwin

Caused by:
    could not rename downloaded file from '…/.rustup/downloads/fc9eb10567ad9b477180d40669c4e6f8edc48f54083689f4a0b4a49db1815b37.partial' to '…/.rustup/downloads/fc9eb10567ad9b477180d40669c4e6f8edc48f54083689f4a0b4a49db1815b37'
```

### Steps

```bash
rustup toolchain add 1.63 & rustup toolchain add 1.63 & rustup toolchain add 1.63
```

### Possible Solution(s)

There should be some global locking mechanism, or downloads/installs should at least use randomized temporary file names.

### Rustup version

```console
rustup 1.27.0 (c7b305727 2024-02-14)
```

### Installed toolchains

```console
not relevant
```

**Comment by kornelski** [comment]
Even when different versions are installed, they can fail due to apparently sharing some files?

```text
error: failed to install component: 'rust-std-aarch64-apple-darwin', detected conflict: 'lib/rustlib/aarch64-apple-darwin/lib/libprofiler_builtins-2b6411659b64a644.rlib'
```

**Comment by ChrisDenton** [comment]
See the pinned issue: https://github.com/rust-lang/rustup/issues/988
