### ISSUE TITLE
Rustup-init fails when `fish` is installed but without config files generated

### ISSUE THREAD

**Issue by 4310V343k** [rust-lang/rustup#3706]
### Problem

I launched a GitHub Codespace, ran `curl https://sh.rustup.rs -sSf | sh`, got `error: could not amend shell profile: '/home/codespace/.config/fish/conf.d/rustup.fish': could not write rcfile file: '/home/codespace/.config/fish/conf.d/rustup.fish': No such file or directory (os error 2)`

Even though `fish` is installed in the codespace, its config is not pre-generated and the default shell is `bash`.
As I understood after 5 minutes of scrolling the code, `rustup` [only checks if the shell's binary exists](https://github.com/rust-lang/rustup/blob/4d3281f3bdf8eac76c5998e664ff5db9d7fbf6e0/src/cli/self_update/shell.rs#L83C18-L83C18), not if the config files exist
This doesn't happen with other shells since their config files are typically located in the home folder

### Steps

1. Ensure `fish` is on PATH
2. Ensure fish's config directory doesn't exist
3. Run `rustup` with default settings (with `modify PATH variable`)

### Notes

Looks like conf.d directory is not created automatically even after running `fish`

### Rustup version

Rustup did not install, but
```console
@4310V343k ➜ /tmp/tmp.MNjnDjzYbe $ ./rustup-init -V
rustup-init 1.27.0 (bbb9276d2 2024-03-08)
```

### Installed toolchains

Rustup did not install

**Comment by rami3l** [comment]
@4310V343k Thanks for sharing with us your diagnosis!

This is indeed a bug with very clear cause, however I'm not sure how we should proceed with it.

Previously we do assume if you have a shell installed we should at least make Rust available in it just in case. Of course we can try to create the directory before writing the file (this looks coherent with what we do with other shells), but will this be too invasive?

cc @djc

**Comment by rami3l** [comment]
@4310V343k For the moment being, you may work around the problem by simply running something like `mkdir -p ~/.config/fish/conf.d/` to force the creation of the influenced directory.

**Comment by djc** [comment]
Seems alright to me to create `~/.config/fish/conf.d` on rustup install if the `fish` binary exists and the dir does not.

**Comment by rami3l** [comment]
@4310V343k Does our [new build](https://productionresultssa3.blob.core.windows.net/actions-results/22ee773a-1e8c-4f34-9a57-2100649b7e05/workflow-job-run-b38bb0c1-dbc2-56df-d36a-a88e1e104af2/artifacts/0076937a48d3f293a0da5f260c7f8d8761f2ea493e746096110b58d20caa7e94.zip?rscd=attachment%3B+filename%3D%22rustup-init-x86_64-unknown-linux-gnu.zip%22&se=2024-03-13T04%3A50%3A47Z&sig=ffEhcfH8GDnCSktGDM1O%2BmM5HaS3HJwXNtOJfLZ3VQw%3D&sp=r&spr=https&sr=b&st=2024-03-13T04%3A40%3A42Z&sv=2021-12-02) work for you?

**Comment by marekjd** [comment]
if you are running a debian build simply run this command: `mkdir -p /home/codespace/.config/fish/conf.d/` then rerun the installation command

**Comment by ryan-minato** [comment]
Because the above PR just missed the previous release, there is a short-term solution before the next release.
Adding `-s -- --no-modify-path` after `sh` can bypass this issue.

``` shell
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path
```

**Comment by rami3l** [comment]
@4310V343k @ryan-minato  [A new beta release is available](https://internals.rust-lang.org/t/seeking-beta-testers-for-rustup-v1-27-1/20730), would you mind trying it out?
