### ISSUE TITLE
Rustup 1.27.0 incompatible with older macOS

### ISSUE THREAD

**Issue by andersm** [rust-lang/rustup#3708]
### Problem

Trying to run `rustup self update` on macOS 10.14 fails with the error `dyld: cannot load 'rustup-init' (load command 0x80000034 is unknown)`.

Full output:
```
$ rustup self update
info: checking for self-update
info: downloading self-update
  rustup updated - (unknown) (from 1.26.0)

dyld: cannot load 'rustup-init' (load command 0x80000034 is unknown)
error: self-updated failed to replace rustup executable

$ uname -a
Darwin Caligari.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Jun 22 19:37:08 PDT 2021; root:xnu-4903.278.70~1/RELEASE_X86_64 x86_64
```

### Steps

1. Run `rustup self update`
2. There is no step 2.

### Rustup version

```console
rustup 1.26.0 (5af9b9484 2023-04-05)
```

### Installed toolchains

```console
Default host: x86_64-apple-darwin
rustup home:  /Users/anders/.rustup

stable-x86_64-apple-darwin (default)
rustc 1.76.0 (07dca489a 2024-02-04)
```

**Comment by ehuss** [comment]
Thanks for the report!

I believe rustup needs to be built with the environment variable `MACOSX_DEPLOYMENT_TARGET: 10.12`. See https://github.com/rust-lang/rust/issues/104570 for the details. Newer versions of Xcode technically don't support such an old version of macos, but I believe in this case it shouldn't be necessary to downgrade.

**Comment by djc** [comment]
@ehuss are you suggesting we/the project should build/release a different binary release for macOS, or that the OP builds their own?

**Comment by ehuss** [comment]
Yea, rustup itself needs to be built with that set, presumably in https://github.com/rust-lang/rustup/blob/master/ci/actions-templates/macos-builds-template.yaml.

You might also consider this for a point release since it is a tier-1 platform.

**Comment by rami3l** [comment]
~~@andersm Does our [new build](https://github.com/rust-lang/rustup/actions/runs/8258781556/artifacts/1320871566) work for you? (You might need to log into GitHub in order to download.)~~

The build above is outdated, please use https://github.com/rust-lang/rustup/issues/3708#issuecomment-2081263739 instead.

**Comment by andersm** [comment]
Yes, it seems to run fine.
```
$ rustup --version
rustup 1.27.0+7 (2eff946a6 2024-03-13)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.76.0 (07dca489a 2024-02-04)`
```

**Comment by rami3l** [comment]
> Yes, it seems to run fine.

@andersm Thanks for helping us out with the testing! We hope to be able to ship v1.27.1 soon, please stay tuned :)

**Comment by rami3l** [comment]
@djc Why closing this before merging #3710?

**Comment by djc** [comment]
Ahh, sorry, got confused between this and another issue.

**Comment by m6s** [comment]
Making my first steps with Rust this weekend. On macOS 10.14 :-D 
If this helps someone (until the fix is released), I had to download and run the previous version of rustup-init from [here](https://static.rust-lang.org/rustup/archive/1.26.0/x86_64-apple-darwin/rustup-init) and run it.

**Comment by dlight** [comment]
> > Yes, it seems to run fine.
> 
> @andersm Thanks for helping us out with the testing! We hope to be able to ship v1.27.1 soon, please stay tuned :)

Until 1.27.1 is out, is there a command to install rustup 1.26? (without building from source)

Maybe passing a parameter to the `curl .. | sh` command, or by downloading a compiled binary somewhere.

**Comment by rami3l** [comment]
> Until 1.27.1 is out, is there a command to install rustup 1.26? (without building from source)
> 
> Maybe passing a parameter to the `curl .. | sh` command, or by downloading a compiled binary somewhere.

@dlight See https://github.com/rust-lang/rustup/issues/3708#issuecomment-1993590209.

**Comment by correabuscar** [comment]
> @andersm Does our [new build](https://github.com/rust-lang/rustup/actions/runs/8258781556/artifacts/1320871566) work for you?

on Safari 14.1.2 (14611.3.10.1.7) (where I'm not logged into github) that url
`https://github.com/rust-lang/rustup/actions/runs/8258781556/artifacts/1320871566`
becomes this url which is the github 404 jedi page:
`https://github.com/rust-lang/rustup/suites/21660555872/artifacts/1320871566`

but this doesn't happen on Gentoo/Firefox where(both urls) it downloads `rustup-init-x86_64-apple-darwin.zip` from `https://productionresultssa15.blob.core.windows.net/actions-results/2e1c7bd4-9cca-4f82-b320-5d1c2621ff5d/workflow-job-run-674b002e-ce16-505c-5919-a83af9976394/artifacts/6d15c0fd93ce77be0ea094d34169c13b5f229fe8e1f0ae89ee2189119a323106.zip?rscd=attachment%3B+filename%3D%22rustup-init-x86_64-apple-darwin.zip%22&se=2024-04-18T05%3A41%3A45Z&sig=GIgnX%2Bqtt6fLQVoGaP4CUNMcyGR0pPyomKB5h%2BX3rA4%3D&sp=r&spr=https&sr=b&st=2024-04-18T05%3A31%3A40Z&sv=2021-12-02`

re-Uploaded here see if it works for me to download
[rustup-init-x86_64-apple-darwin.zip](https://github.com/rust-lang/rustup/files/15020418/rustup-init-x86_64-apple-darwin.zip)
sha256 `67ab0edd01be9f2d8fc05da2e17e8731ccd8e5a6d639bcaa2676157f45c48370  rustup-init-x86_64-apple-darwin.zip`

It works and installed nightly successfully, thanks!


Ok, the new way is:
```
RUSTUP_UPDATE_ROOT=https://dev-static.rust-lang.org/rustup rustup self update
```
or
```
export RUSTUP_UPDATE_ROOT=https://dev-static.rust-lang.org/rustup
rustup self update
```
or
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | RUSTUP_UPDATE_ROOT=https://dev-static.rust-lang.org/rustup sh
```
or
```
export RUSTUP_UPDATE_ROOT=https://dev-static.rust-lang.org/rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

**Comment by rami3l** [comment]
@correabuscar This is not a platform-related issue. Since recently GitHub has been moving stuff behind the login wall. As I see it, what you saw could very possibly be a consequence of this.

**Comment by rami3l** [comment]
@andersm @correabuscar @dlight [A new beta release is available](https://internals.rust-lang.org/t/seeking-beta-testers-for-rustup-v1-27-1/20730), would you mind trying it out?

**Comment by andersm** [comment]
@rami3l It seems to work.
```
$ rustup --version
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.77.2 (25ef9e3d8 2024-04-09)`
```

**Comment by WhiteMac** [comment]
The installer at rustup.rs should be updated with this fix. Today I got the same error `dyld: cannot load 'rustup-init' (load command 0x80000034 is unknown)` while attempting to install (as opposed to update) rustup on macOS 10.14.6 via:

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

**Comment by rami3l** [comment]
> The installer at rustup.rs should be updated with this fix. Today I got the same error `dyld: cannot load 'rustup-init' (load command 0x80000034 is unknown)` while attempting to install (as opposed to update) rustup on macOS 10.14.6 via:
> 
> 
> 
> ```
> 
> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> 
> ```

@WhiteMac Sorry, but the deployment part is out of the control of the Rustup team. That being said, we've contacted the right people, and according to them, you could expect a new stable release coming earlier next week, which should address this very concern. For the moment being, please try out https://github.com/rust-lang/rustup/issues/3708#issuecomment-2081263739.

**Comment by XionWin** [comment]
> @andersm Does our [new build](https://github.com/rust-lang/rustup/actions/runs/8258781556/artifacts/1320871566) work for you? (You might need to log into GitHub in order to download.)

Thanks rami3l, this scrpit is helpful for me.

**Comment by rami3l** [comment]
> > @andersm Does our [new build](https://github.com/rust-lang/rustup/actions/runs/8258781556/artifacts/1320871566) work for you? (You might need to log into GitHub in order to download.)
> 
> Thanks rami3l, this scrpit is helpful for me.

@XionWin Sorry, but that build is outdated, please use https://github.com/rust-lang/rustup/issues/3708#issuecomment-2081263739 instead.

**Comment by rami3l** [comment]
@WhiteMac @XionWin The stable release is now available, so I'm marking our previous discussions as outdated.
