### ISSUE TITLE
Replace `.` with `source` in `conf.d/rustup.fish`

### ISSUE THREAD

**Issue by rben01** [rust-lang/rustup#3714]
### Problem you are trying to solve

While fish shell technically supports `.` as an alias for [`source`](https://fishshell.com/docs/current/cmds/source.html), this is deprecated. However, after running `rustup-init`, the contents of `~/.config/fish/conf.d/rustup.fish` are `. "$HOME/.cargo/env.fish"`, which will (probably) eventually fail.

### Solution you'd like

During installation of rustup, it should use `source` instead of `.` when generating code for `fish` shell. The contents of `rustup.fish` should be `source "$HOME/.cargo/env.fish"`.

### Notes

Version: rustup 1.27.0 (2024-03-08)

Elsewhere, rustup seems aware of the impending change:

```
Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, you need to source
the corresponding env file under $HOME/.cargo.

This is usually done by running one of the following (note the leading DOT):
. "$HOME/.cargo/env"            # For sh/bash/zsh/ash/dash/pdksh
source "$HOME/.cargo/env.fish"  # For fish
```

**Comment by djc** [comment]
Makes sense -- would you be able to submit a PR for this?
