### ISSUE TITLE
Bugs in "component add" message

### ISSUE THREAD

**Issue by smoelius** [rust-lang/rustup#3721]
I think there may be a couple of bugs here:
https://github.com/rust-lang/rustup/blob/6e8769c768990c72678de0f6fe092030474ccbcf/src/toolchain/distributable.rs#L441-L445
- `selector` is not part of the format string, so `{toolchain}` won't get filled in.
- There appears to be a space missing between `{selector}` and `{component}` name.

**Comment by rami3l** [comment]
@smoelius Thanks a lot for filing this issue! Would you be so kind as to make a PR fixing this one?

**Comment by smoelius** [comment]
Fixing the bug itself looks not so hard.

Is there a test I could copy and modify to verify the fix? Or should I submit the fix without a test?

**Comment by rami3l** [comment]
> Is there a test I could copy and modify to verify the fix? Or should I submit the fix without a test?

@smoelius It depends on how you may reproduce this issue, and how stable that reproduction would be.

I guess it can be stably reproduced when you do `rls +nightly --version`. If that's correct, a quick search points to

https://github.com/rust-lang/rustup/blob/6e8769c768990c72678de0f6fe092030474ccbcf/tests/suite/cli_misc.rs#L529-L542

**Comment by smoelius** [comment]
In a fork at 6e8769c76 with no changes, `cargo test --features=test cli_self_upd::update_exact` produces this:
```
> rustup self update
out.ok: true
out.stdout (2 lines):
      rustup updated - 6e8769c76 (from 1.27.0)
    
    
out.stderr (2 lines):
    info: checking for self-update
    info: downloading self-update
    
expected.ok: true
expected.stdout (2 lines):
      rustup updated - 1.27.0 (from 1.27.0)
    
    
expected.stderr (2 lines):
    info: checking for self-update
    info: downloading self-update
    
[src/test/mock/clitools.rs:601:13] out.stdout == stdout = false
[src/test/mock/clitools.rs:602:13] out.stderr == stderr = true
thread 'suite::cli_self_upd::update_exact' panicked at tests/suite/cli_self_upd.rs:303:16:
```
The same command passes when run on the `rustup` repo.

Any idea what could be wrong?

**Comment by rami3l** [comment]
> Any idea what could be wrong?

@smoelius This is https://github.com/rust-lang/rustup/issues/1783.

I think you can safely ignore this test locally (in fact, I recommend running only the tests you added, and probably other relevant tests such as this `run_rls_when_not_installed()` thing, and leaving the rest to the CI). It depends on the git state (more specifically, `git depth`), as you can probably see right now. As long as everything is green on our own CI it should be fine.

Context: https://rust-lang.github.io/rustup/dev-guide/version-numbers.html

**Comment by smoelius** [comment]
Can I ask what would be considered the "right" way to fix the `update_exact` test?

**Comment by rami3l** [comment]
> Can I ask what would be considered the "right" way to fix the `update_exact` test?

@smoelius As I explained above, do a full clone of the repo with all the tags and this test will pass locally. It's just that it's not GitHub's default currently...
