### ISSUE TITLE
Unexplained print with partial valid rust-toolchain.toml

### ISSUE THREAD

**Issue by Matthew-Chidlow** [rust-lang/rustup#3732]
### Problem

When running commands like `rustup show` an unexplained message is printed to console:

> Official(ToolchainDesc { channel: "stable", date: None, target: TargetTriple("x86_64-pc-windows-msvc") }) [Official(ToolchainDesc { channel: "stable", date: None, target: TargetTriple("x86_64-pc-windows-gnu") }), Official(ToolchainDesc { channel: "stable", date: None, target: TargetTriple("x86_64-pc-windows-msvc") }), Official(ToolchainDesc { channel: 
"nightly", date: None, target: TargetTriple("x86_64-pc-windows-gnu") }), Official(ToolchainDesc { channel: "nightly", date: None, target: TargetTriple("x86_64-pc-windows-msvc") })]

This also happens when using cargo

### Steps

1. Create a rust project
2. Add a rust-toolchain.toml file
3. Put in the file something like:
>[toolchain]
channel = "stable-x86_64-pc-windows-msvc"

where the channel listed contains a host triple and is an installed toolchain

4. Try run almost any rustup or cargo command in the projects directory

### Possible Solution(s)

I think the print is here:
https://github.com/rust-lang/rustup/blob/1c612cf65439901200f89c0123dbdf9dcae5e539/src/config.rs#L594

Probably should print some more context

### Rustup version

```console
rustup 1.27.0 (bbb9276d2 2024-03-08)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
Official(ToolchainDesc { channel: "stable", date: None, target: TargetTriple("x86_64-pc-windows-msvc") }) [Official(ToolchainDesc { channel: "stable", date: None, target: TargetTriple("x86_64-pc-windows-gnu") }), Official(ToolchainDesc { channel: "stable", date: None, target: TargetTriple("x86_64-pc-windows-msvc") }), Official(ToolchainDesc { channel: 
"nightly", date: None, target: TargetTriple("x86_64-pc-windows-gnu") }), Official(ToolchainDesc { channel: "nightly", date: None, target: TargetTriple("x86_64-pc-windows-msvc") })]
info: The currently active `rustc` version is `rustc 1.77.0 (aedd173a2 2024-03-17)`
```

### Installed toolchains

```console
Default host: x86_64-pc-windows-gnu
rustup home:  C:\Users\Matthew\.rustup

Official(ToolchainDesc { channel: "stable", date: None, target: TargetTriple("x86_64-pc-windows-msvc") }) [Official(ToolchainDesc { channel: "stable", date: None, target: TargetTriple("x86_64-pc-windows-gnu") }), Official(ToolchainDesc { channel: "stable", date: None, target: TargetTriple("x86_64-pc-windows-msvc") }), Official(ToolchainDesc { channel: 
"nightly", date: None, target: TargetTriple("x86_64-pc-windows-gnu") }), Official(ToolchainDesc { channel: "nightly", date: None, target: TargetTriple("x86_64-pc-windows-msvc") })]
installed toolchains
--------------------

stable-x86_64-pc-windows-gnu (default)
stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-gnu
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (overridden by 'C:\Users\Matthew\RustroverProjects\fine_zoom_2\rust-toolchain.toml')
rustc 1.77.0 (aedd173a2 2024-03-17)
```

**Comment by rami3l** [comment]
@rbtcollins did you happen to forget deleting this after print debugging?

**Comment by djc** [comment]
Can probably just do a PR for this, seems highly likely that that is the case.
