### ISSUE TITLE
Unable to add wasm64-unknown-unknown

### ISSUE THREAD

**Issue by kavinask007** [rust-lang/rustup#3733]
### Problem

Unable to add wasm64-unknown-unknown even though  rustc --print=target-list shows wasm64-unknown-unknown available

### Steps

1.  **rustup target add wasm64-unknown-unknown** Gives the error : toolchain 'nightly-x86_64-unknown-linux-gnu' does not support target 'wasm64-unknown-unknown'; did you mean 'wasm32-unknown-unknown'?

### Rustup version

```console
❯ rustup --version
rustup 1.27.0 (bbb9276d2 2024-03-08)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.79.0-nightly (85e449a32 2024-03-22)`
```

### Installed toolchains

```console
❯ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/user/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.79.0-nightly (85e449a32 2024-03-22)
```

**Comment by djc** [comment]
This is a tier 3 target, which means there are no pre-built binaries for it. I think that would explain this behavior?

**Comment by kavinask007** [comment]
Ah yes !! that explains it . Thanks.
