### ISSUE TITLE
mac catalina cant use offical script install rust

### ISSUE THREAD

**Issue by AuroraPetard** [rust-lang/rustup#3745]
### Problem

 curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer
sh: line 570:  6993 Segmentation fault: 11  "$@"

what should i do now 

### Steps

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer
sh: line 570:  6993 Segmentation fault: 11  "$@"

### Rustup version

```console
rustc 1.77.0 (aedd173a2 2024-03-17)
```

### Installed toolchains

```console
no
```

**Comment by djc** [comment]
Duplicates #3708.
