### ISSUE TITLE
Does not decrment correctly 

### ISSUE THREAD

**Issue by rejjiesnow** [rust-lang/rustup#3746]
### Problem

<code>fn main() {
    println!("5!: {}", factorial(5));
    println!("4!: {}", factorial(4));
}

fn factorial(mut factorialToSum: u64) -> u64{
    let mut sum: u64 = 0;
    let mut step: u64 = 0;
    while factorialToSum > 1{
        step = factorialToSum * (factorialToSum - 1);
        sum = sum + step;
        factorialToSum = factorialToSum - 1;
    }
    sum
}</code>

<code>fn main() {
    let mut sum5: u64 = 0;
    let mut step5: u64 = 0;
    let mut factorialToSum5 = 5;

    while factorialToSum5 > 1{
        step5 = factorialToSum5 * (factorialToSum5 - 1);
        sum5 = sum5 + step5;
        factorialToSum5 = factorialToSum5 - 1;
    }
    println!("5!: {}", sum5);

    let mut sum4: u64 = 0;
    let mut step4: u64 = 0;
    let mut factorialToSum4 = 4;

    while factorialToSum4 > 1{
        step4 = factorialToSum4 * (factorialToSum4 - 1);
        sum4 = sum4 + step4;
        factorialToSum4 = factorialToSum4 - 1;
    }
    println!("4!: {}", sum4);
}</code>

here are two piece of code with the same problem, if you use a debugger you will find that factorialToSum will decrement twice with out assignment. both produce wrong factorial results

### Steps

1. not really sure like try to assaisgn something after doing an operation with it

### Possible Solution(s)

idk i dont write compilers

### Notes

hahahahahahahah i think im wrong

### Rustup version

```console
1.77.0 stable
```

### Installed toolchains

```console
installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.79.0-nightly (c9f8f3438 2024-03-27)
```

**Comment by djc** [comment]
This doesn't seem to have to do anything with rustup, which is a tool used to distribute Rust compiler toolchains. For your beginner Rust questions, consider going to https://users.rust-lang.org/.
