### ISSUE TITLE
The «Basic usage» section of the rustup book should talk about basic usage.

### ISSUE THREAD

**Issue by kindaro** [rust-lang/rustup#3768]
### Problem you are trying to solve

I want to refer to the _«[Basic usage]»_ section of the rustup book to install a Rust toolchain and start coding. It seems I should need to get `rustc`, `rustfmt`, `cargo`, `rust-analyzer` executables on my path, as well as have other less obvious things like documentation and source of the standard library somewhere in my file system, such that they can be somehow found. The rustup book does not 

[Basic usage]: https://rust-lang.github.io/rustup/basics.html

### Solution you'd like

It would be great if the book gave me a sequence of commands while showing their expected output. It should tell me which commands to run _(some basic choice for everything)_, and it should also tell me what will happen and how I can check that it worked.

I have gotten `rustc` on my path by running `rustup default stable`. Already the connexion is not obvious — this should be explained in the book. What other commands should I await to be put on the path out of the box? What do I need to install so that I get syntax highlighting? What other tools `rustup` offers that I should be aware of?

### Notes

I know this is all very obvious to a working Rust programmer. The curse of knowledge! Even having worked with Rust before _(maybe three years ago)_, I now have no idea how to set it up. This should be written somewhere.

**Comment by rami3l** [comment]
@kindaro Thanks for filing this issue!

It looks like what you wanted is mentioned in the [official tutorial (a.k.a. the Rust Book)](https://doc.rust-lang.org/stable/book/ch01-00-getting-started.html) instead of the Rustup Book.

The Rustup Book per se is about the usage of Rustup (and the main focus of which is, like you mentioned, keeping your Rust installations up to date), and we definitely don't want to cover too much about starting programming with Rust in general.

OTOH, if you have a specific idea to improve our docs, please feel free to send a PR and I'll be happy to review it!

**Comment by rami3l** [comment]
@kindaro May I know why you chose to click on the Rustup Book instead of the Rust Book?

The latter is in theory much more visible in general (like, we have a direct hyperlink towards Rust Book on [rust-lang.org](https://www.rust-lang.org/learn), and if I search `get started with Rust` the first results on DuckDuckGo would be the relevant chapter of the Rust Book, and a [`Getting Started`](https://www.rust-lang.org/learn/get-started) page that includes a short introduction plus a hyperlink to the Rust Book).

If you have entered the Rustup Book by mistake I think it would be nice to add a link back to the Rust Book. What do you think?

**Comment by kindaro** [comment]
But I am not starting to program in Rust. I have some experience with the language. For example, I built a [game] with Rust 3 years ago.

What I ask for is specifically a [how-to guide] that shows how to get a recommended Rust programming set-up with `rustup`. You already have a section titled _«Basic usage»_. It sounds like a how-to type of documentation should be found within. But it only talks about updates.

Note that I am specifically not looking for a tutorial. I can get a `rustc` one way or another. The point is to get a set-up according to the latest and best practices, within hours and not days of research. `rustup` particularly is an element of latest and best practices — this is why I am here.

> OTOH, if you have a specific idea to improve our docs, please feel free to send a PR and I'll be happy to review it!

I should like to do that, however recall the curse of knowledge I mentioned. When one does not know the topic, one cannot write about it because there are no answers. When one knows the topic, one cannot write about it because there are no questions. Education is a coöperative activity.

Imagine you were given a computer with an uncertain flavour of Linux running on it. You have a shell and an Internet connection. What would you do to get going with Rust on a professional level using this computer? What commands would you run and what would you expect to happen when you run them?

If you can give me some answers, I shall try them out, write up the outcome and put it to the documentation.

[how-to guide]: https://documentation.divio.com/how-to-guides.html
[game]: https://github.com/kindaro/snakes

**Comment by George-Miao** [comment]
Since you have experience with rust, you should know the orthodox way of managing a rust project is with `cargo`. In your case, `cargo new --bin/--lib` should be sufficient. `rustup` is a tool meant to manage toolchains include cargo and others, not used to setup or manage any specific project. 

If you happened to forget, just read the getting started guide. People do forget things and that's ok, just learn it again.

**Comment by George-Miao** [comment]
> It should tell me which commands to run _(some basic choice for everything)_, and it should also tell me what will happen and how I can check that it worked.

After getting `rustup` and `cargo`, just do `cargo new`. If it works, it works; if not, report the issue.

**Comment by kindaro** [comment]
Alright, let us talk specifics. I have ArchLinux at hand, `rustup` is available via in the standard way via `pacman`. Here is the list of files it installs that have `/bin/` in their path, and what version they think they are:

```
% pacman -Ql rustup | grep 'bin/.' | cut -d ' ' -f 2 | rev | cut -d '/' -f 1 | rev | while read executable; do echo -n "$executable\t"; "$executable" --version; done
cargo	cargo 1.77.2 (e52e36006 2024-03-26)
cargo-clippy	clippy 0.1.77 (25ef9e3 2024-04-09)
cargo-fmt	rustfmt 1.7.0-stable (25ef9e3 2024-04-09)
cargo-miri	error: the 'miri' component which provides the command 'cargo-miri' is not available for the 'stable-x86_64-unknown-linux-gnu' toolchain
clippy-driver	clippy 0.1.77 (25ef9e3 2024-04-09)
rust-gdb	GNU gdb (GDB) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
rust-lldb	lldb version 16.0.6
rustc	rustc 1.77.2 (25ef9e3d8 2024-04-09)
rustdoc	rustdoc 1.77.2 (25ef9e3d8 2024-04-09)
rustfmt	rustfmt 1.7.0-stable (25ef9e3 2024-04-09)
rustup	rustup 1.27.0 (2024-03-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.77.2 (25ef9e3d8 2024-04-09)`
rust-analyzer	zsh: command not found: rust-analyzer
```

* Does this look about right?
* Why is `cargo-miri` reporting an error?
* Why is `rust-analyzer` not in the path?

_(In particular, I should not need to install `cargo` separately, because it is provided by `rustup` out of the box.)_

However, this works because I already set everything up before. Let me remove `~/.rustup`, as if this wast a fresh installation, and see what happens.

```
% pacman -Ql rustup | grep 'bin/.' | cut -d ' ' -f 2 | rev | cut -d '/' -f 1 | rev | while read executable; do echo -n "$executable\t"; "$executable" --version; done
cargo	error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
cargo-clippy	error: rustup could not choose a version of cargo-clippy to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
cargo-fmt	error: rustup could not choose a version of cargo-fmt to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
cargo-miri	error: rustup could not choose a version of cargo-miri to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
clippy-driver	error: rustup could not choose a version of clippy-driver to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
rust-gdb	error: rustup could not choose a version of rust-gdb to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
rust-lldb	error: rustup could not choose a version of rust-lldb to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
rustc	error: rustup could not choose a version of rustc to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
rustdoc	error: rustup could not choose a version of rustdoc to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
rustfmt	error: rustup could not choose a version of rustfmt to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
rustup	rustup 1.27.0 (2024-03-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
rust-analyzer	zsh: command not found: rust-analyzer
```

Whoops.

Technically speaking, all of these executables other than `rustup` itself are symlinks to `rustup`, who will call appropriate real executables on my behalf. If I have no `~/.rustup`, there is nothing it can call.

**Comment by George-Miao** [comment]
If you are installing rustup provided by archlinux, refer to [arch wiki](https://wiki.archlinux.org/title/rust). They have detailed procedures. For the missing components, you may need to add them manually via `rustup component add`. What you see in the bin directory are merely [symlinks](https://gitlab.archlinux.org/archlinux/packaging/packages/rustup/-/blob/main/PKGBUILD?ref_type=heads#L38) back to `rustup` executable.

When you remove `~/.rustup`, you deleted the default toolchain config too, which is what you would expect after installing rustup for the first time. Follow the tutorial and set a default toolchian first.

**Comment by weihanglo** [comment]
> * Does this look about right?

This is covered in <https://rust-lang.github.io/rustup/installation/index.html#installation>. Also <https://www.rust-lang.org/tools/install>. So both the rustup book and official guide cover that. Rustup might be distributed and modified by different distros so there is no a expected set of binaries that rustup can guarantee the existence. The only one is `rustc` which is already mentioned.

> * Why is `cargo-miri` reporting an error?

This should be a separate issue. If the error message is not helpful, cut a ticket for that.

> * Why is `rust-analyzer` not in the path?

This might be out of scope of rustup book. Rustup can't hijack your `PATH` and provide a nicer message when a binary is not in your `PATH`. You need to do research by your self.

---

A normal (new) Rust user usually only needs to know `rustup update` and `cargo +<toolchain> build` and calls it a day. These topics are all covered well. If you intend to do verification of binaries installed in your system, that is another story.

**Comment by kindaro** [comment]
@George-Miao   Thank you for your hints but you misunderstand me. I do not need your help solving my problems, not now. I am offering help improving the documentation so that other people need not suffer as I suffered.

* * *

@weihanglo   Thank you but I do not think you understand me. I am a normal new Rust user _(unless you wish to suggest otherwise)_ and I have needs not covered by the links you offer, which is why I wish to help improve the documentation.

> This is covered in https://rust-lang.github.io/rustup/installation/index.html#installation. Also https://www.rust-lang.org/tools/install. So both the rustup book and official guide cover that. Rustup might be distributed and modified by different distros so there is no a expected set of binaries that rustup can guarantee the existence. The only one is `rustc` which is already mentioned.

This is exactly why I ask for a how-to guide that covers basic usage in detail. So that I can spot that my distribution is giving me a faulty `rustup` fork. All these executables should be in `~/.cargo/bin`, which is already on the path. Instead, they are in `/usr/bin` and `/usr/lib/rustup/bin/`, the latter of which is off the path. If I had a how-to guide to follow, I should have spotted that something is wrong right away.

For example, it would say:

> ### install `rust-analyzer`
>
> You will need to have the `rust-analyzer` executable on the path if you want your editor to offer fancy features.
>
> 1. You will not have the `rust-analyzer` executable anywhere on your system at first.
> 2. If you run `rustup component add rust-analyzer`, the executable `rust-analyzer` will appear  in `~/.rustup/toolchains/*/bin` and a symlink will be put to `~/.cargo/bin`. You must add either of these to your path. If your editor supports LSP, it must from then on offer fancy features.

This walks the reader through the basic usage of `rustup`. This is not a tutorial — this is a [how-to guide], it is satisfyingly technical. The existing documentation is either tutorials or explanations, they do not answer the need to know precisely what I can do and what I should expect to happen.

[how-to guide]: https://documentation.divio.com/how-to-guides.html

**Comment by rami3l** [comment]
> Imagine you were given a computer with an uncertain flavour of Linux running on it. You have a shell and an Internet connection. What would you do to get going with Rust on a professional level using this computer? What commands would you run and what would you expect to happen when you run them?

This is explained in https://doc.rust-lang.org/book/ch01-01-installation.html. Of course, the description is not comprehensive, but the notes showing up when you actually execute `rustup-init` should give you a clearer picture.

> All these executables should be in `~/.cargo/bin`, which is already on the path. Instead, they are in `/usr/bin` and `/usr/lib/rustup/bin/`, the latter of which is off the path. If I had a how-to guide to follow, I should have spotted that something is wrong right away.

The Rustup Project is responsible for the standard (as in directly supported by us) way of installing Rust via Rustup, that is, via https://rustup.rs and/or `rustup-init`. In your case, since you're using `pacman` instead, we cannot guarantee you the very same onboarding experience since part of that process is out of our control. (In this particular case, `pacman` directly installed `rustup` and skipped `rustup-init` altogether.) Quoting https://rust-lang.github.io/rustup/installation/other.html#using-a-package-manager:

> If you have encountered any problems installing rustup with a package manager, please contact the package maintainer(s) for further information.

As a matter of fact, if you had used the standard method, you will see the very message informing you of this fact even before your actual installation:

https://github.com/rust-lang/rustup/blob/49ddaae217a6cc27340fcaebd16f53f7be84f993/src/cli/self_update.rs#L151-L181

And if you have missed that, you can find basically the same info in https://rust-lang.github.io/rustup/concepts/index.html#how-rustup-works:

> `rustup` is a *toolchain multiplexer*. It installs and manages many Rust
> toolchains and presents them all through a single set of tools installed to
> `~/.cargo/bin`. The [`rustc`] and [`cargo`] executables installed in
> `~/.cargo/bin` are *[proxies]* that delegate to the real toolchain. `rustup`
> then provides mechanisms to easily change the active toolchain by
> reconfiguring the behavior of the proxies.
> 
> So when `rustup` is first installed, running `rustc` will run the proxy in
> `$HOME/.cargo/bin/rustc`, which in turn will run the stable compiler. If you
> later *change the default toolchain* to nightly with `rustup default nightly`,
> then that same proxy will run the `nightly` compiler instead.
> 
> [rbenv]: https://github.com/rbenv/rbenv
> [pyenv]: https://github.com/yyuu/pyenv
> [nvm]: https://github.com/creationix/nvm
> [`rustc`]: https://doc.rust-lang.org/rustc/
> [`cargo`]: https://doc.rust-lang.org/cargo/
> [proxies]: proxies.md

Again, all the info here applies to the standard distribution only. Installing Rustup via a third party like `pacman` is considered an advanced usage, and as such you need to refer to that third party first when in doubt, as mentioned by @George-Miao in https://github.com/rust-lang/rustup/issues/3768#issuecomment-2049963837. 


I'm closing this issue as out of scope now.
