### ISSUE TITLE
Provide different rustup instalation options on https://rustup.rs/ for security conscious users and administrators 

### ISSUE THREAD

**Issue by apps4uco** [rust-lang/rustup#3777]
### Problem you are trying to solve

Downloading a file from internet and piping it to the shell, should make most security conscious system administrators hesitant if not worried.

I.e: *curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh*

It requires having blind faith that rustup.rs has not been compromised and that there are no errors in the script.

However, it is understandable that this simple solution is the best for most people.

(also it does presuppose that curl is already installed)

### Solution you'd like

Id like to propose some additional instructions:

# Installation

There are several ways to install rustup, all perform the same installation, so choose the one that best suits your needs:

# Single line installer

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Multi line installer  

## Download the installer 

% curl -o installer.sh --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs

## Verify the integrity of the download

% sha256sum installer.sh 
7b826d2c84318cf44897da29225cb9bc0b4e859b05568b5979bf2cc264840d05  installer.sh

(The administrator has the chance to view the installer and verify that it is safe)

## Execute the installer 

% sh installer.sh

# Install rustup using your package manager

(Most users and administrators already trust their package manager)

% yum install rustup

% apt-get install rustup

etc...

% rustup upgrade

(or whatever command it should be for a complete install of stable rust)

**Comment by rami3l** [comment]
@apps4uco Thanks for filing this issue!

rustup.rs is designed to be a one-way street to avoid possible confusion for newcomers.

For advanced users, we already have a link at the bottom of that page pointing to https://rust-lang.github.io/rustup/installation/other.html, so you'll find other options if you don't like the default one.

That being said, I would like to underline that any third-party distribution (e.g. via `apt` or `pacman`) is out of our direct control (and they might have downstream code changes that we are not aware of), and that the Rustup Project is only responsible for the `rustup-init` distribution downloaded from our release server.

As a matter of fact, our `rustup-init.sh` does exactly that if you look closely, and if you're not comfortable with running our shell script, please feel free to download the precompiled `rustup-init` binary listed in the page above.

If you have further questions, please feel free to contact me :) Have a nice day!
