### ISSUE TITLE
Rust installing script incompatible with older macOS

### ISSUE THREAD

**Issue by XionWin** [rust-lang/rustup#3804]
### Verification

- [X] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [X] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

❯ `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
info: downloading installer
dyld: cannot load 'rustup-init' (load command 0x80000034 is unknown)
sh: line 570:   671 Abort trap: 6           "$@"
❯ `curl https://sh.rustup.rs -sSf | sh`
info: downloading installer
dyld: cannot load 'rustup-init' (load command 0x80000034 is unknown)
sh: line 570:   716 Abort trap: 6           "$@"

**my mac version  High Sierra 10.13.6**

### Steps

1. run the install script in the terminal
2. we can get the error prompt.

### Rustup version

```console
None
```

### Installed toolchains

```console
info: downloading installer
dyld: cannot load 'rustup-init' (load command 0x80000034 is unknown)
sh: line 570:   801 Abort trap: 6           "$@"
```

### OS version

```console
macOS 10.13.6 High Sierra
```

**Comment by djc** [comment]
See #3708.
