### ISSUE TITLE
Failures while downloading https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init

### ISSUE THREAD

**Issue by samruddhikhandale** [rust-lang/rustup#3809]
### Verification

- [x] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [x] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

The Dev Container Rust Feature makes use of the following command in order to install rust. However, it has started failing as the following `curl` command fails to download `rustup-init`

```
curl -sSL --proto '=https' --tlsv1.2 "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init" -o /tmp/rustup/target/x86_64-unknown-linux-gnu/release/rustup-init
```

### Steps

Run `curl -sSL --proto '=https' --tlsv1.2 "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init" -o /tmp/rustup/target/x86_64-unknown-linux-gnu/release/rustup-init`

### Rustup version

1.78.0

### Installed toolchains

NA

### OS version

Ubuntu

**Comment by rami3l** [comment]
@samruddhikhandale Thanks a lot for filing this issue! This change is intentional, see #3693.

Update: I've pinned #3693 to make it more visible. Closing this one...
