### ISSUE TITLE
`rustup update self` should suggest `rustup self update`

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rustup#3812]
### Problem you are trying to solve

A new-ish user got confused about the command for updating rustup itself and tried `rustup update self` which gave this error:

```
error: error: invalid value 'self' for '[toolchain]...': invalid toolchain name: 'self'

For more information, try '--help'.
: invalid toolchain name: 'self'
```

### Solution you'd like

Maybe something like:

```
note: use `rustup self update` to update rustup itself
```

### Notes

I'm also not sure why the ``: invalid toolchain name: 'self'`` is repeated at the end. That seems redundant.
```[tasklist]
### Tasks
- [ ] https://github.com/rust-lang/rustup/issues/3905
```

**Comment by rami3l** [comment]
@ChrisDenton Thanks a lot! Should be an easy fix.

**Comment by fbrv** [comment]
I'd like to give a shot

**Comment by rami3l** [comment]
> I'd like to give a shot

@fbrv Please, go ahead!

**Comment by fbrv** [comment]
@rami3l, @djc  I have something but before opening the PR I'm wondering how we want to show the message. Should we append, prepend or replace the message with the note?

**Comment by rami3l** [comment]
> @rami3l, @djc  I have something but before opening the PR I'm wondering how we want to show the message. Should we append, prepend or replace the message with the note?

@fbrv Following the [example of rustc error messages](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8f052287967ea0e3bd32e675d80ac645), it seems to me that any "smart guess" lines should come **after** the original error message.

Please note that there could be a toolchain named self, so it's important to show the line on error exclusively.

**Comment by rami3l** [comment]
Unfortunately, @fbrv just DM'd me and expressed their wish of backing out due to a personal incident. Thanks anyway for having offered to help!

**Comment by Xerxes-2** [comment]
Could I try this?

**Comment by rami3l** [comment]
> Could I try this?

@Xerxes-2 Yes, please!
