### ISSUE TITLE
#3827 has broken the ETA format when downloading/installing components

### ISSUE THREAD

**Issue by rami3l** [rust-lang/rustup#3828]
> @djc Just tried the latest build and this looks incorrect.
>
> <img width="918" alt="image" src="https://github.com/rust-lang/rustup/assets/33851577/0a41d31a-8ffc-4fab-8d79-100383114e61">

_Originally posted by @rami3l in https://github.com/rust-lang/rustup/issues/3827#issuecomment-2112434768_

This regression has been discovered in the following version:

```console
> rustup --version
rustup 1.27.1 :: 1.27.0+133 (eca50133c 2024-05-15)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.78.0 (9b00956e5 2024-04-29)`
```

**Comment by rami3l** [comment]
Suggestion: we should stick to the old format:

https://github.com/rust-lang/rustup/blob/9caf4fc77417c03aaf56aecee449e48d16485896/src/cli/download_tracker.rs#L188-L196

... which means there should be an `ETA: {}` somewhere.

My suggestion `write!(f, " ETA: {}", self.0.display()),` in https://github.com/rust-lang/rustup/pull/3827#discussion_r1601229010 should do exactly this.

**Comment by djc** [comment]
Why should we stick to the old format? I agree with #3826 that showing it after finishing is pointless.

**Comment by rami3l** [comment]
> Why should we stick to the old format? I agree with #3826 that showing it after finishing is pointless.

@djc Sorry, I meant stick to the old format when downloading. The expected result should be something like `in 1s ETA: Unknown`.

**Comment by rami3l** [comment]
For example if ETA is 3s, the current version will print `in 1s3s`, which is clearly not ideal.

**Comment by djc** [comment]
Ahh, no, I only applied half of your suggestion -- sorry, was too hasty; fix in #3829.

I was confused for a while by your screenshot showing "Unknown", but that seems unrelated.

**Comment by rami3l** [comment]
> Ahh, no, I only applied half of your suggestion -- sorry, was too hasty; fix in #3829.
> 
> I was confused for a while by your screenshot showing "Unknown", but that seems unrelated.

@djc Sorry, that `Unknown` is caused by a division-by-zero I believe. I probably won't be able to make a better screenshot: it all goes too fast on my machine :]

**Comment by djc** [comment]
All of this code looks pretty shitty and would like to use indicatif instead (#1835), but that'll have to wait for another day.

**Comment by rami3l** [comment]
> All of this code looks pretty shitty and would like to use indicatif instead (#1835), but that'll have to wait for another day.

@djc I'm also in favor of using the `console` suite (incl. `dialoguer` and `indicatif`). In #3803 however I tried my best not to introduce new dependencies 😅

**Comment by djc** [comment]
Yeah, one step at a time. async -> tracing -> indicatif.
