### ISSUE TITLE
rustup.exe hangs on windows and can't be killed

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#384]
> Another more severe issue is that rustup.exe process seem to be hanging and it cannot be killed from the Windows Task Manager. Due to this issue, I cannot remove the .cargo and .multirust directories and I have to_force_ reboote the PC to recover (using the power button).

[Source](https://internals.rust-lang.org/t/beta-testing-rustup-rs/3316/100?u=brson).

**Comment by brson** [comment]
@retep998 [suggested](https://internals.rust-lang.org/t/beta-testing-rustup-rs/3316/104?u=brson) it could be interaction with antivirus.

**Comment by maximih** [comment]
Not sure if this is of any help, but this is what I get when trying to kill it with `taskkill`:

```
$ tasklist.exe | grep -a rustup
rustup.exe                    1356 Console                    1      6▒480 K
rustup.exe                   11096 Console                    1      7▒072 K
```

```
C:\windows\system32>taskkill.exe /pid 1356 /f
ERROR: The process with PID 1356 could not be terminated.
Reason: There is no running instance of the task.
```

Regarding the antivirus, I cannot find a way to stop it as I am using a work PC and I don't have access to change the antivirus settings.

cc @retep998

**Comment by brunoqc** [comment]
I have a similar problem on a Win 7 64-bit virtual machine. No anti-virus.

I'm trying to build files from the host using virtualbox's shared folder feature.

**Comment by hh9527** [comment]
I was hit by this issue. But I found that manual coping the proxy binary will make it works.

```cmd
@echo off
setlocal
set dir=%~dp0
set files=cargo rustc rustdoc rust-gdb rust-lldb rls
for %%f in (%files%) do (
    del /q %dir%.\%%f.exe
    copy /y /b %dir%rustup.exe %dir%.\%%f.exe
)
endlocal
```

Run this .cmd file evertime after rustup updated.

**Comment by ChrisDenton** [comment]
It's been almost 6 years without any more reports or details. Should this be presumed fixed?

**Comment by 0xPoe** [comment]
> It's been almost 6 years without any more reports or details. Should this be presumed fixed?

Sounds good. I am going to close this issue now.
