### ISSUE TITLE
rustup fails with `fatal: libgcc_s.so.1: open failed: No such file or directory` on Sun 10

### ISSUE THREAD

**Issue by shanebishop** [rust-lang/rustup#3857]
### Verification

- [X] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [X] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

rustup fails on Sun 10.

There are multiple problems that occur:
1. The `/bin/sh` that comes with Sun 10 does not support `$(...)` syntax for subshells. This can be worked around by changing the shebang to `/bin/bash`, but then there are still the problems below.
2. Invocations of `uname` with `-o` fail with `/usr/bin/uname: illegal option -- o`.
3. Invocations of `grep` with `-q` fail with `grep: illegal option -- q`.
4. Most importantly, rustup fails with
```
ld.so.1: rustup-init: fatal: libgcc_s.so.1: open failed: No such file or directory
rustup.sh: line 521:  3578 Killed                  "$@"
```

### Steps

1. Download rustup 1.27.1
2. Change the shebang to `#/bin/bash` (to avoid issue 1 above)
3. SCP the rustup file with the new shebang to a Sun 10 machine
4. Run `chmod +x` on the script to give it executable permissions
5. Run the script

### Notes

I am aware that Sun 10 is not one of the platforms supported by Rust (Rust's support for Sun/Solaris starts with Sun 11). However, I would expect the rustup script to work on Sun 10, in order to allow people to use the script to download a Rust compiler for using [custom targets](https://doc.rust-lang.org/rustc/targets/custom.html) to build on the platform. (But maybe I am assuming too much - maybe there is no pre-built Sun 10 `rustc`.)

### Rustup version

```console
1.27.1
```

### Installed toolchains

The output of `rustup show` isn't meaningful (there are a bunch of errors).

### OS version

```console
Sun 10
```

**Comment by rami3l** [comment]
@shanebishop Thanks a lot for filing this issue!

As you've already found out, according to our current [target policy](https://doc.rust-lang.org/rustc/platform-support.html#tier-2-without-host-tools), Solaris 10 is not supported by the Rust project as a whole (i.e. neither as a host nor as a target), so even if Rustup happens to work, there will be no officially distributed `rustc` and other components, thus it's out of our project's scope to make it possible for a Solaris 10 machine to be used as a compilation host.

If you would like to run Rust programs on such a machine, I personally recommend using the "custom target" feature on a supported host platform, and then find a way to cross-compile for the target in question.

Thanks a lot for your comprehension, and have a nice day!

**Comment by shanebishop** [comment]
Thanks @rami3l.

In that case, are there instructions somewhere on how to build `rustc` from source?

**Comment by rami3l** [comment]
@shanebishop Here are some links that might be relevant to your custom target cross-compilation usage:

- https://docs.rust-embedded.org/embedonomicon/custom-target.html for defining a new custom target;
- https://doc.rust-lang.org/nightly/rustc/platform-support/mipsel-sony-psx.html for being able to use `std` and friends with `build-std`.

OTOH compiling `rustc` itself would be a more involved process, I suggest you make a new post on the Zulip server (https://rust-lang.zulipchat.com) if that's what you need.
