### ISSUE TITLE
Rust install through proxy and Artifactory : Bug on SSL certification

### ISSUE THREAD

**Issue by Pierremalle** [rust-lang/rustup#3870]
Hi everyone.
Not really a bug i'm facing but i'm kinda blocked. My company is using an Artifactory repository to mirror to Rust crates.
So i connected my rustup to this repo and it seems to work fine since it's searching on the good place.

However, i can't use rustup to install rust as the internal proxy of the company ruin all SSL certificate.
A senior dev told me the same happened with Conan and they just deactivate SSL check EVERYWHERE.

Is there, today, a way to deactivate it with rustup ?

Thanks a lot.

**Comment by djc** [comment]
Don't you get a company trust root for your internal proxy installed on your machine? That would probably still allow it to work.

**Comment by Pierremalle** [comment]
Sadly, i don't think so.
The senior who answered my question well precised that in another project, they put SSL check deactivation everywhere on a Conan similar problem, indicating that even senior dev don't have that type of help.
He insisted on the fact that i must deactivate it from the source which is rustup.

**Comment by djc** [comment]
I would first talk to your infrastructure/IT folks to see if you can get the internal trust root installed. Installing a compiler toolchain without authenticating it seems like an extremely bad idea.

**Comment by Pierremalle** [comment]
Well, that's what i also found on this topic :
https://github.com/rust-lang/rustup/pull/1624#issuecomment-494564596

i'll talk about it to my internship referent. It would be a good solution be will surely take a long time.

Thanks a lot, i'll consider this as close.
