### ISSUE TITLE
Reserve `RUSTUP_LOG` for `tracing` usages instead of `RUST_LOG`

### ISSUE THREAD

**Issue by rami3l** [rust-lang/rustup#3875]
### Problem you are trying to solve

@weihanglo has raised concerns regarding `RUST_LOG` adding Rustup's log lines to `cargo run` when `cargo` is a `rustup` shim.

Cargo has changed to using `CARGO_LOG` for `cargo`-internal log lines for clarity in https://github.com/rust-lang/cargo/pull/6918, and considering the special relationship between the two projects, I think it's reasonable for us to do the same.

### Solution you'd like

Reserve `RUSTUP_LOG` for `tracing` usages inside of Rustup instead of the default `RUST_LOG`.

**Comment by djc** [comment]
Yup, this makes sense to me.
