### ISSUE TITLE
`Segmentation fault` when running in a `linux/amd64` docker container on Apple Silicon macOS

### ISSUE THREAD

**Issue by staktrace** [rust-lang/rustup#3902]
### Verification

- [X] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [X] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

Running rustup inside a linux/amd64 docker container on an M3 macOS machine segfaults. Instead it should not segfault.

### Steps

On a Macbook Pro with a Apple M3 Max chip, running Sonoma 14.5 (23F79). I have docker installed, and start a docker container like so:

```
docker run --platform linux/amd64 -it ubuntu:22.04
```

Inside the docker container, I run the following:
```
cd
apt-get update
apt install -y curl
curl https://sh.rustup.rs -sSf | sh -s -- -y
```

The rustup command produces this output:
```
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2024-06-13, rust version 1.79.0 (129f3b996 2024-06-10)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
 63.8 MiB /  63.8 MiB (100 %)  56.2 MiB/s in  1s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
Segmentation fault
```

### Possible Solution(s)

Running the docker command with `--platform linux/aarch64` and intead of `--platform linux/amd64` allows the rustup command to succeed. However I need the amd64 docker build as I need to install other tools that are only precompiled for amd64.

### Rustup version

```console
rustup 1.27.1 (54dd3d00f 2024-04-24)
```

### Installed toolchains

```console
N/A since the toolchain installation is the problem
```

### OS version

```console
macOS Sonoma 14.5 (23F79)
```

**Comment by ehuss** [comment]
I believe this is the same as https://github.com/rust-lang/rust/issues/125430, which has some workarounds. I believe this may be a Docker issue, and I'm not sure how possible it would be for rustup to work around it.

**Comment by staktrace** [comment]
Ah, thanks. I'll close this issue as a dupe of https://github.com/rust-lang/rust/issues/125430 then.

**Comment by staktrace** [comment]
For the record, disabling Rosetta in the Docker Desktop options does also solve this problem, as mentioned in https://github.com/rust-lang/rust/issues/125430

**Comment by geraldstanje** [comment]
@staktrace i had the same issue in macbook pro m1 - disabling rosetta in the Docker Desktop also helped there.
do you plan to fix it also for not disabling rosetta in the Docker Desktop? what is the consequence of disabling rosetta - will the compile time for rust be slower because of that?

**Comment by staktrace** [comment]
@geraldstanje I don't plan on fixing it, no. Seems like a docker desktop bug. You'd have to ask docker folks.

**Comment by kylehassett** [comment]
For those looking for a solution right now, disable `Rosetta` in Docker Desktop's `General` settings.

**Comment by rami3l** [comment]
FYI this is a Docker issue and has nothing to do with this project per se. You'll need to update docker to fix it:

> I reproduced this bug on Docker Desktop 4.29.0 (145265). Updating to 4.32.0 (157355) resolved the issue. Rosetta is still enabled. 

 _https://github.com/rust-lang/rust/issues/125430#issuecomment-2249845738_
