### ISSUE TITLE
`rustc --version` should not trigger/initiate toolchain updates

### ISSUE THREAD

**Issue by rami3l** [rust-lang/rustup#3943]
Transferred from https://github.com/rust-lang/rust/issues/127649.

> I expect `rustc --version` to just output version information, like how `--version` would behave in any other application.
> 
> In my humble opinion, `rustc --version` should not be responsible for upgrading toolchains. The user should do that either explicitly or maybe when running `rustc` with any other flags for which it makes more sense for silent updates to be performed.
> 
> The `--version` argument should really just be a 'request' for version information and not trigger any other actions.
> 
> To be clear... I think it's ok to trigger silent updates for different calls to `rustc` with different arguments, but I believe `--version` should really only output the version (and maybe a hint that the current version is a mismatch by what is specified in `rust-toolchain.toml`).
> 
> Performing silent updates, and maybe even more actions, may even pose security risks to users that do not expect these actions to happen silently when running a command like `rustc --version`.

_Originally posted by @Doineann in https://github.com/rust-lang/rustup/issues/3635#issuecomment-2225382797_

**Comment by panekj** [comment]
When invoked via rustup proxy, it should not fail, it should show the resolved active rustc version (without downloading the toolchain), whichever that may be at the moment considering all override methods. Given that rustup already knows which toolchain version to pull, it shouldn't be impossible to present that info.

**Comment by rami3l** [comment]
> When invoked via rustup proxy, it should not fail, it should show the resolved active rustc version (without downloading the toolchain), whichever that may be at the moment considering all override methods. Given that rustup already knows which toolchain version to pull, it shouldn't be impossible to present that info.

@panekj I don't believe it can in general, as we have to take into account custom toolchains that are not distributed by (but linked against) rustup, as well as "moving targets" such as `stable` and `1.79`. This action should in no way access the internet.

**Comment by rami3l** [comment]
A note for myself:

https://github.com/rust-lang/rustup/blob/4207838d962204123f70705ff9f3e73c37b813df/src/cli/proxy_mode.rs#L35

... calls:

https://github.com/rust-lang/rustup/blob/4207838d962204123f70705ff9f3e73c37b813df/src/config.rs#L732

So modulo the tests this should be a simple change.
