### ISSUE TITLE
rustup update in traditional package installed operating systems

### ISSUE THREAD

**Issue by soloturn** [rust-lang/rustup#3956]
### Verification

- [X] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [X] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

most operating systems have a traditional way to update packages. rustup is queer to that approach, and defeats properly updating, am not sure why and how it does so. take example arch linux, normally super simple to configure, the [arch linux page for rust](https://wiki.archlinux.org/title/Rust) contains (1) native install (2) rustup install, (3) rustup via arch linux package (4) rustup via upstream installation script (5) rustup toolchain install via "usuage". a normal operating system update does NOT update rust, it needs separate love. while this love is deserved, it is painful. rust deserves to be updated just like the rest of the operating system. rust deserves to be properly installed without cluttering the whole home directory with garbage. this ticket is about *how* to do that.

### Steps

install rust via operating system package. description here:
https://wiki.archlinux.org/title/Rust

### Possible Solution(s)

use a simple directory structure, just like other programming languages, and leave the rest to operating system config via "PATH". no stable, unstable, beta etc channels at runtime, this is a distribution time concept. to give an example, java, on arch linux:

```
❯ ls -l /usr/bin/java
lrwxrwxrwx - root 19 Jan  2023 /usr/bin/java -> /usr/lib/jvm/default-runtime/bin/java

❯ ls -l /usr/lib/jvm/
lrwxrwxrwx - root  6 Apr 08:56 default -> java-21-openjdk
lrwxrwxrwx - root  6 Apr 08:56 default-runtime -> java-21-openjdk
drwxr-xr-x - root 25 Mai 02:52 java-8-openjdk
drwxr-xr-x - root 20 Jul 23:02 java-17-openjdk
drwxr-xr-x - root 20 Jul 23:02 java-21-openjdk
drwxr-xr-x - root 20 Jul 23:02 java-22-openjdk

❯ sudo archlinux-java set java-21-openjdk

```
for the whole machine the default distribution can be switched over via a command, which does a very simple 

symbolic link change. for a user, adjusting the PATH variable to one of the java directories is sufficient, java not involved at all. JAVA_HOME is NOT set.

for rust same could be possible. either have versioned directories, like `/usr/lib/rust/rust-1.79` or have it in channel structure, like `/usr/lib/rust/stable``/usr/lib/rust/beta`. adoptin one of the 2 means operating packages are easy to make and roll out. 

### Rustup version

```console
rustup 1.27.1 (2024-05-07)
```

### Installed toolchains

```console
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/st/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.79.0 (129f3b996 2024-06-10)
```

### OS version

```console
arch linux. rolling.
```

**Comment by djc** [comment]
Operating systems are free to have a custom mechanism to manage Rust toolchains, but I don't see how that's relevant to rustup, which is a tool to let users manage their "local" toolchains. As such, I'm confused what exactly you're arguing that we should do here.

**Comment by rami3l** [comment]
> rust deserves to be updated just like the rest of the operating system. rust deserves to be properly installed without cluttering the whole home directory with garbage.

@soloturn Rustup is here exactly to mitigate the problem with system-wide Rust installations: the Rust org has basically no control over when and what the OS vendors want to ship WRT Rust distributions, so we have to roll our own solution to make it easier for everyone to be on the same page.

As such, the way to get system-wide, up-to-date Rust toolchain installed AFAIK is to use a rolling distribution, which you are already on.

> `❯ sudo archlinux-java set java-21-openjdk`

It would be nice to have something like that for your particular distribution, however this is out of the scope of this project. I imagine you can figure out how `archlinux-java` works and roll your own `archlinux-rust` or something 🤔
