### ISSUE TITLE
rustup doc not opening in Arc Browser on Windows

### ISSUE THREAD

**Issue by gg-plato** [rust-lang/rustup#3992]
### Verification

- [X] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [X] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

Trying any `rustup doc` command in windows terminal does not open the default Arc browser, works if I change default browser for Edge.  No errors, just doesn't open. Not sure if its a rustup issue or Arc issue. Sorry if it's the latter.

![image](https://github.com/user-attachments/assets/90cfec93-df2f-4566-bb45-0aa3a8a36a90)

### Steps

1. Open Windows terminal on Win11
2. `rustup doc --book`
3. Nothing happens

### Rustup version

```console
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.80.1 (3f5fd8dd4 2024-08-06)`
```

### Installed toolchains

```console
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\plato\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
```

### OS version

```console
Edition	Windows 11 Home
Version	23H2
Installed on	‎26/‎06/‎2024
OS build	22631.4037
Experience	Windows Feature Experience Pack 1000.22700.1027.0
```

**Comment by djc** [comment]
rustup uses the opener crate for this. I suggest you open an issue against their [repo](https://github.com/Seeker14491/opener).

**Comment by rami3l** [comment]
Looking at https://github.com/Seeker14491/opener/issues/33#issuecomment-2327227037:

> It's an Arc Browser bug:
> 
> https://www.reddit.com/r/ArcBrowser/comments/1c16ls9/i_set_arc_browser_as_my_windows_default_browser/ https://www.reddit.com/r/ArcBrowser/comments/1f4jjxw/arc_doesnt_respond_to_shell_or_console_commands/
> 
> On Windows we're just using the standard `ShellExecuteW()` Windows API function, but Arc Browser isn't responding to it for some reason.

... it seems that there's not much we can do about this issue, sorry about that...
