### ISSUE TITLE
Command to tell whether download/install is necessary

### ISSUE THREAD

**Issue by smoelius** [rust-lang/rustup#4000]
I am looking for a command to tell me whether a toolchain would have to be downloaded/installed without actually downloading or installing anything.

Hypothetically:
```sh
$ rustup <args>
# exit code 0 => no installation necessary
# exit code 1 => installation necessary
```
Does such a command exist today?

Please note that I am aware of this issue and PR:
- https://github.com/rust-lang/rustup/issues/3635
- https://github.com/rust-lang/rustup/pull/3985

If I understand correctly, the latter suggests that such a command may be available soon.

**Comment by rami3l** [comment]
@smoelius Thanks for filing this issue! I think you're getting it right.

We don't have a specific command for this test, but starting from #3985, if the active toolchain is not installed, using it via any command will result in an error and a suggestion of actually installing it.

You may use `rustc --version` for this purpose, for example, as demonstrated in the PR's description.

Do you happen to have other concerns in this regard?

**Comment by smoelius** [comment]
@rami3l Thank you for your response.

> We don't have a specific command for this test, but starting from #3985, if the active toolchain is not installed, using it via any command will result in an error and a suggestion of actually installing it.

Just to be sure I understand, this functionality is not yet released, correct?

**Comment by rami3l** [comment]
@smoelius Not at the moment, but we do have plans to ship it soon. See #3998.

**Comment by smoelius** [comment]
Thanks very much for your help, @rami3l.
