### ISSUE TITLE
Rust debugger crashes with error "Library not loaded: @rpath/libunwind.1.dylib" on m1 mac

### ISSUE THREAD

**Issue by ghost** [rust-lang/rustup#4001]
### Verification

- [X] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [X] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

Rust debugger fails on launch on m1 mac with below error:
```
dyld[5414]: Library not loaded: @rpath/libunwind.1.dylib
  Referenced from: <9BAB5573-D404-3B2D-88F8-E74F562E5A78> /path/to/binary
  Reason: no LC_RPATH's found
Signal: SIGABRT (signal SIGABRT)
```

### Steps

1. Install rust on m1 mac
2. Try to attach lldb/rust-lldb to the generated binary
3. It fails with above error

### Possible Solution(s)

N/A

### Notes

I am new to rust lang (though have experience with C++ and lldb works fine for C++ programs) and installed rust a few days ago. So I am not sure if it's a regression from previous OS/Rust versions.

### Rustup version

```console
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.80.1 (3f5fd8dd4 2024-08-06)`
```

### Installed toolchains

```console
Default host: aarch64-apple-darwin
rustup home:  /Users/username/.rustup

stable-aarch64-apple-darwin (default)
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
```

### OS version

```console
macOS Sonoma 14.6.1
```

**Comment by djc** [comment]
Why do you think rustup is to blame?

**Comment by ghost** [comment]
sorry if it's the not the correct repo to raise this issue, I thought this might be an issue with rust toolchain setup. What repo would be correct to get help on this issue?

**Comment by djc** [comment]
You might want to just try rust-lang/rust for now.

**Comment by ghost** [comment]
Thanks!

**Comment by rami3l** [comment]
@djc Maybe you can try to transfer this issue to Rust via the bot? Like what @ChrisDenton has once done?

**Comment by djc** [comment]
> @djc Maybe you can try to transfer this issue to Rust via the bot? Like what @ChrisDenton has once done?

I tried that but I didn't seem to have permission.

**Comment by rami3l** [comment]
Oops, nice find. We should find some time to inform the admins.

**Comment by ghost** [comment]
Just for future reference, looks like there were multiple paths on which libunwind was present which was causing this confusion. I deleted the stale paths and it's working fine now.
