### ISSUE TITLE
`rustup doc` cannot open docs for `std::mem::MaybeUninit`

### ISSUE THREAD

**Issue by taylordotfish** [rust-lang/rustup#4002]
### Verification

- [X] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [X] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

I tried to open the documentation for [`std::mem::MaybeUninit`](https://doc.rust-lang.org/nightly/std/mem/union.MaybeUninit.html) with the following command:

```
rustup doc std::mem::MaybeUninit
```

but got the following error:

```
error: No document for 'std::mem::MaybeUninit'
```

### Steps

1. Make sure the `rust-docs` component is installed for the active toolchain.
2. Run `rustup doc std::mem::MaybeUninit` or `rustup doc core::mem::MaybeUninit`.

### Possible Solution(s)

I believe the issue occurs because `"union"` is missing from `keywords_mod` in [`cli::topical_doc::local_path`](https://github.com/rust-lang/rustup/blob/c91692a1bdbd91663dbc5fbb1f1bdd684e711f1c/src/cli/topical_doc.rs#L50).

I expect that adding it to that array would fix the issue, although some discussion may be warranted concerning where in the array it should be inserted.

### Rustup version

```console
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.82.0-nightly (5aea14073 2024-08-20)`
```

### Installed toolchains

```console
Default host: powerpc64le-unknown-linux-gnu
rustup home:  /home/tmp/.rustup

installed toolchains
--------------------

stable-powerpc64le-unknown-linux-gnu
nightly-powerpc64le-unknown-linux-gnu (default)

installed targets for active toolchain
--------------------------------------

powerpc64le-unknown-linux-gnu
wasm32-unknown-unknown

active toolchain
----------------

nightly-powerpc64le-unknown-linux-gnu (default)
rustc 1.82.0-nightly (5aea14073 2024-08-20)
```

### OS version

```console
Debian GNU/Linux ppc64el trixie
```

**Comment by djc** [comment]
> I believe the issue occurs because `"union"` is missing from `keywords_mod` in [`cli::topical_doc::local_path`](https://github.com/rust-lang/rustup/blob/c91692a1bdbd91663dbc5fbb1f1bdd684e711f1c/src/cli/topical_doc.rs#L50).
> 
> I expect that adding it to that array would fix the issue, although some discussion may be warranted concerning where in the array it should be inserted.

Thanks for reporting & investigating. Would you be able to send a PR so we can discuss the change you have in mind?
