### ISSUE TITLE
rustup didn't populate .cargo

### ISSUE THREAD

**Issue by ningcng** [rust-lang/rustup#4003]
### Verification

- [X] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [X] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

`rustup default nightly` installed the toolchain but didn't populate .cargo/. My .cargo/ was not created at all.

### Steps

1. rustup default nightly

### Rustup version

```console
rustup 1.27.1 (2024-04-24)
```

### Installed toolchains

```console
Default host: aarch64-apple-darwin
rustup home:  /Users/ningcng/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
```

### OS version

```console
Darwin Kernel Version 23.6.0
Sonoma 14.6.1
```

**Comment by rami3l** [comment]
@ningcng Thanks for filing this issue!

Did you install `rustup` via Homebrew? If so, that is the expected behavior from their side.

**Comment by ningcng** [comment]
Yes. I wish they didn't package rustup.
