### ISSUE TITLE
How to get aarch64-unknown-freebsd to work?

### ISSUE THREAD

**Issue by rudrabhoj** [rust-lang/rustup#4012]
### Problem you are trying to solve

I am experimenting with aarch64 FreeBSD install on cloud. What would be the best way to get rustup there? My dev machine is aarch64 macos.

### Solution you'd like

A way to cross compile it with required toolchains would be nice. Ideally from Macos.

**Comment by rami3l** [comment]
@rudrabhoj Thanks a lot for filing this issue!

I'm sorry for your inconvenience, but according to Rust's platform policy, FreeBSD on ARM64 is a [tier 3](https://doc.rust-lang.org/stable/rustc/platform-support.html?highlight=freebsd#tier-3) target right now, so even if Rustup compiles there, it wouldn't be able to download anything from the release server.

If you would like to cross compile Rust projects for that platform, you can refer to the suggestion in https://github.com/rust-lang/rustup/issues/4006#issuecomment-2312184176, which is from a similar case.

You can also try your luck with the distro-packaged Rust as listed [here](https://ports.freebsd.org/cgi/ports.cgi?query=^rust&stype=name), if you're okay without getting official Rust toolchain updates, but that's out of the scope of this project anyway.

If you have further questions, please let us know!
