### ISSUE TITLE
conflict on updating to today's nightly with `llvm-tools`

### ISSUE THREAD

**Issue by kaspar030** [rust-lang/rustup#4019]
### Verification

- [X] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [X] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

Can't update toolchain, fails with `error: failed to install component: 'rustc-x86_64-unknown-linux-gnu', detected conflict: 'lib/rustlib/x86_64-unknown-linux-gnu/bin/llc'`.

### Steps

1. have `llvm-tools` installed for nightly
2. run `rustup update`

### Rustup version

```console
❯ rustup --version
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.81.0 (eeb90cda1 2024-09-04)`
```

### Installed toolchains

```console
<details>


Default host: x86_64-unknown-linux-gnu
rustup home:  /home/kaspar/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2022-07-04-x86_64-unknown-linux-gnu
nightly-2022-10-22-x86_64-unknown-linux-gnu
nightly-2022-11-01-x86_64-unknown-linux-gnu
nightly-2022-11-22-x86_64-unknown-linux-gnu
nightly-2023-03-25-x86_64-unknown-linux-gnu
nightly-2023-05-18-x86_64-unknown-linux-gnu
nightly-2023-06-02-x86_64-unknown-linux-gnu
nightly-2023-06-28-x86_64-unknown-linux-gnu
nightly-2023-08-19-x86_64-unknown-linux-gnu
nightly-2023-10-02-x86_64-unknown-linux-gnu
nightly-2023-11-01-x86_64-unknown-linux-gnu
nightly-2024-03-11-x86_64-unknown-linux-gnu
nightly-2024-05-20-x86_64-unknown-linux-gnu
nightly-2024-05-31-x86_64-unknown-linux-gnu
nightly-2024-09-09-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
1.65.0-x86_64-unknown-linux-gnu
1.72.1-x86_64-unknown-linux-gnu
1.77.0-x86_64-unknown-linux-gnu
1.75-x86_64-unknown-linux-gnu
1.77-x86_64-unknown-linux-gnu
1.78-x86_64-unknown-linux-gnu
1.79-x86_64-unknown-linux-gnu
1.80-x86_64-unknown-linux-gnu
esp

installed targets for active toolchain
--------------------------------------

aarch64-linux-android
arm-unknown-linux-gnueabihf
arm-unknown-linux-musleabihf
armv7-linux-androideabi
armv7-unknown-linux-musleabihf
i686-linux-android
i686-unknown-linux-gnu
riscv32imac-unknown-none-elf
thumbv6m-none-eabi
thumbv7em-none-eabi
thumbv7em-none-eabihf
thumbv7m-none-eabi
wasm32-unknown-unknown
x86_64-apple-darwin
x86_64-linux-android
x86_64-pc-windows-gnu
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.81.0 (eeb90cda1 2024-09-04)

```
</details>
```


### OS version

```console
current arch, also happens on the github Ubuntu CI workers.
```

**Comment by djc** [comment]
I think this would be due to #988?

**Comment by larseggert** [comment]
We're seeing the same issue: https://github.com/mozilla/neqo/actions/runs/10844489766/job/30095214032#step:3:103

**Comment by kaspar030** [comment]
> I think this would be due to #988?

I don't think so, this started happening only recently on [my CI](https://github.com/kaspar030/laze/actions/runs/10844606763/job/30093856721?pr=518). By [pinning](https://github.com/kaspar030/laze/pull/519) an older nightly version, this seems to be fixed.

**Comment by djc** [comment]
Okay, can someone describe a reproduction scenario?

**Comment by kaspar030** [comment]
> Okay, can someone describe a reproduction scenario?

This "works" for me:

- start a docker container with `docker run -ti --rm ubuntu`
- inside docker container, run these commands:

```
$ apt-get update
$ apt-get install curl
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
$ . "$HOME/.cargo/env"
$ rustup toolchain install nightly
$ rustup +nightly component add llvm-tools

**Comment by djc** [comment]
Okay, great, thanks! I think this is an issue with the upstream toolchains. I opened [a Zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Conflicts.20in.20today's.20nightly.20llc.20component.3F) and am now looking at recent rust-lang/rust PRs to see if something there is relevant here.

**Comment by jclmnop** [comment]
+1

Our github runners (Ubuntu 22.04.4) are now experiencing this exact same issue with the latest nightly. Yesterday's version was fine.

**Comment by djc** [comment]
Okay, looks like this is getting fixed here:

- https://github.com/rust-lang/rust/pull/130292

rust-lang/rust bug is here:

- https://github.com/rust-lang/rust/issues/130291

**Comment by kaspar030** [comment]
Thanks a bunch!
