### ISSUE TITLE
Install with Visual Studio Build Tools instead of Visual Studio Community

### ISSUE THREAD

**Issue by AdreKiseque** [rust-lang/rustup#4038]
### Problem you are trying to solve

When Rustup doesn't detect the C linker tool things it needs, it prompts the user to install them through Visual Studio, launching the wizard primed to install the IDE with the necessary dependancies.

### Solution you'd like

Rustup should instead have the wizard install Build Tools for Visual Studio, which can provide the dependancies without the overhead of the full IDE.

**Comment by ChrisDenton** [comment]
Build tools requires the user (or organization) has a license for Community, Professional or Enterprise.

Installing Community is the only way to get a free license.

**Comment by djc** [comment]
I guess for those users who do have a license, it might be nice to offer the option?

**Comment by ChrisDenton** [comment]
Sure, it could be an option.

**Comment by AdreKiseque** [comment]
> Build tools requires the user (or organization) has a license for Community, Professional or Enterprise.
> 
> Installing Community is the only way to get a free license.

Oh, that's bizarre. It doesn't let you install Build Tools without first obtaining a license that's free and automatic with another installation? I'd have to take your word for it, since I've never encountered any sort of barrier but probably had the license associated with my account to have me covered. If it really is like that I suppose it explains the current state of things.

**Comment by ChrisDenton** [comment]
The barrier is "the license terms". This was [brought up in 2022](https://github.com/rust-lang/rustup/issues/2867) so it's still an issue unless Visual Studio's licensing has changed in this area.

**Comment by AdreKiseque** [comment]
I see. What an unfortunate inconvenience.
