### ISSUE TITLE
`rustup self uninstall` caused data loss

### ISSUE THREAD

**Issue by steelman** [rust-lang/rustup#4051]
### Verification

- [x] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [x] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

`rustup self uninstall` removed contents of my ~/bin directory leaving rust stuff behind

```
$ ls -l ~/bin                                                                                                                                                                                                      
total 203504                                                                                                                                                                                                     
-rwxr-xr-x 14 steelman steelman 14881096 Oct 16 09:23 cargo
-rwxr-xr-x 14 steelman steelman 14881096 Oct 16 09:23 cargo-clippy
-rwxr-xr-x 14 steelman steelman 14881096 Oct 16 09:23 cargo-fmt
-rwxr-xr-x 14 steelman steelman 14881096 Oct 16 09:23 cargo-miri
-rwxr-xr-x 14 steelman steelman 14881096 Oct 16 09:23 clippy-driver
-rwxr-xr-x 14 steelman steelman 14881096 Oct 16 09:23 rls
-rwxr-xr-x 14 steelman steelman 14881096 Oct 16 09:23 rust-analyzer
-rwxr-xr-x 14 steelman steelman 14881096 Oct 16 09:23 rust-gdb
-rwxr-xr-x 14 steelman steelman 14881096 Oct 16 09:23 rust-gdbgui
-rwxr-xr-x 14 steelman steelman 14881096 Oct 16 09:23 rust-lldb
-rwxr-xr-x 14 steelman steelman 14881096 Oct 16 09:23 rustc
-rwxr-xr-x 14 steelman steelman 14881096 Oct 16 09:23 rustdoc
-rwxr-xr-x 14 steelman steelman 14881096 Oct 16 09:23 rustfmt
-rwxr-xr-x 14 steelman steelman 14881096 Oct 16 09:23 rustup
```

If I remember correctly, at the time it happened (i.e. yesterday) after one of previous attempts to play with rust I had ~/.config/cargo/bin symlink pointing to ~/bin.

### Steps

1. create ~/.config/cargo/bin as a symilnk pointing to ~/bin (actually don't, use a different directory with some random contents)
2. install rust with `curl | sh`
3. run `rustup` self uninstall`

### Possible Solution(s)

Do something like `readlink -f` does to check if the real file is below ~/.config/cargo. Do not remove files rustup hasn't installed.

### Rustup version

rustup 1.27.1 (54dd3d00f 2024-04-24)

### Installed toolchains

no active toolchain

### OS version

Debian 12

EDIT: Duplicate of #1072

**Comment by djc** [comment]
Sorry you had a bad experience. Given that we already have an issue on file, I'll close this issue. I've added the original issue to the roadmap so we'll hopefully actually get it done sometime soonish.
