### ISSUE TITLE
`rustup-init.sh` is not working on GNU Guix

### ISSUE THREAD

**Issue by emfrom** [rust-lang/rustup#4058]
### Verification

- [x] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [x] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

The rustup-init.sh script does not download anything.

### Steps

Download rustup-init.sh (as instructed on rust lang website)

Script "downloads" but does not produce an output file

### Rustup version

(cant install)

### Installed toolchains

(cant install)

### OS version

GNU Guix/Linux 6.10.13

and GNU bash, version 5.1.16(1)-release (since we are talking about a shell script)

**Comment by djc** [comment]
Suggest at least posting a transcript of how it fails with `--verbose` enabled.

**Comment by emfrom** [comment]
Here goes,

```~/opt/Downloads
> ./rustup-init.sh --verbose


info: downloading installer
./rustup-init.sh: line 571: /tmp/tmp.TIwINzMO8r/rustup-init: No such file or directory

```

Here's an strace of the script as well.

[rustup-init.sh.strace.zip](https://github.com/user-attachments/files/17505525/rustup-init.sh.strace.zip)

**Comment by rami3l** [comment]
@emfrom This is a known issue as Guix makes different assumptions about ~~the `/tmp` directory~~ the filesystem structure than we do, similar to https://github.com/rust-lang/rustup/issues/2948.

> To clarify, rustup uses prebuilt binaries that won't work on GuixSD, so you'd need to run it in a shell with --fhs-container. Alternatively, you can use Nix [..]
_https://www.reddit.com/r/GUIX/s/L5qmPy83GC_

---

I was looking at this particular section of your log when I found the previous comment. Somehow "/tmp/tmp.FyKEMajnS3/rustup-init" was not pointing to the same thing in the first line and the last one:

```
faccessat2(AT_FDCWD, "/tmp/tmp.FyKEMajnS3/rustup-init", X_OK, AT_EACCESS) = 0
ioctl(0, TCGETS, {c_iflag=ICRNL|IXON|IUTF8, c_oflag=NL0|CR0|TAB0|BS0|VT0|FF0|OPOST|ONLCR, c_cflag=B38400|CS8|CREAD, c_lflag=ISIG|ICANON|ECHO|ECHOE|ECHOK|IEXTEN|ECHOCTL|ECHOKE, ...}) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_BLOCK, [INT TERM CHLD], [], 8) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f76c7138a10) = 3147
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigaction(SIGINT, {sa_handler=0x4482e0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f76c7179560}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f76c7179560}, 8) = 0
wait4(-1, ./rustup-init.sh: line 571: /tmp/tmp.FyKEMajnS3/rustup-init: No such file or directory
[{WIFEXITED(s) && WEXITSTATUS(s) == 127}], 0, NULL) = 3147
```

**Comment by emfrom** [comment]
After some debugging of the shell script I realized that the file actually is downloaded. However, it cant be executed. I downloaded the installer manually and it gives the same error.

execve reports that the file doesnt exist,even when it does. As follows:

```
~/opt/Downloads
> ldd rustup-init

        linux-vdso.so.1 (0x00007f0e70102000)
        libgcc_s.so.1 => /home/emfrom/.guix-profile/lib/libgcc_s.so.1 (0x00007f0e700cf000)
        librt.so.1 => /home/emfrom/.guix-profile/lib/librt.so.1 (0x00007f0e700ca000)
        libpthread.so.0 => /home/emfrom/.guix-profile/lib/libpthread.so.0 (0x00007f0e700c5000)
        libm.so.6 => /home/emfrom/.guix-profile/lib/libm.so.6 (0x00007f0e6ffe5000)
        libdl.so.2 => /home/emfrom/.guix-profile/lib/libdl.so.2 (0x00007f0e6ffe0000)
        libc.so.6 => /home/emfrom/.guix-profile/lib/libc.so.6 (0x00007f0e6f022000)
        /lib64/ld-linux-x86-64.so.2 => /gnu/store/zvlp3n8iwa1svxmwv4q22pv1pb1c9pjq-glibc-2.39/lib/ld-linux-x86-64.so.2 (0x00007f0e70104000)
```
The file is physcally there, I can do ldd / stat etc and so on.

However,
```
strace rustup-init

execve("./rustup-init", ["rustup-init"], 0x7fffe1d06c60 /* 106 vars */) = -1 ENOENT (No such file or directory)
strace: exec: No such file or directory
+++ exited with 1 +++

```
This is literally in the same place. I did some sanity checking on my other build environments and it only affects rust (that I've found so far.

Just to be sure I downloaded the latest stable tarball and every single executable in the tarball gives the same error.

**Comment by emfrom** [comment]
After further investigation, this is a guix problem.

**Comment by rami3l** [comment]
@emfrom Thanks for your time investigating this! Did you try the aforementioned `--fhs-container` trick though?

**Comment by emfrom** [comment]
The problem was that I had gotten some versioning out of sync for build-tools and libraries. I'm not quite sure how, it persisted across all reasonable manipulation of environments. In other words, the problem was a lot bigger than the rust chain even if it was almost only rust binaries that actively complained.

I suppose this implies a gold star for rust, somewhere, somehow. :)

**Comment by pjotrp** [comment]
I actually managed to run rustup inside a guix shell container using the `-F` switch. The steps are:

```sh
guix shell --share=$HOME/.cargo -C -N -F -L . impg-shell-rust-latest-git
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs |sh
. ~/.cargo/env
env LD_LIBRARY_PATH=$GUIX_ENVIRONMENT/lib CC=gcc cargo --version
  cargo 1.87.0 (99624be96 2025-05-06)
env LD_LIBRARY_PATH=$GUIX_ENVIRONMENT/lib CC=gcc cargo build
```

To make this shell I used a trivial build script that contains all dependencies that we require to build our rust software - that uses a SIMD C++ module:

```scheme
(define-public impg-shell-rust-latest-git
  "Shell version to use 'cargo build' from rustup bootstrap"
  (package
    (name "impg-shell-rust-latest-git")
    (version %version)
    (source (local-file %source-dir #:recursive? #t))
    (build-system trivial-build-system)
    (inputs
     (list gnutls lzip openssl pkg-config zlib xz
           binutils coreutils-minimal))
    (propagated-inputs
     (list curl bash grep
           cmake nss-certs openssl perl gnu-make-4.2
           coreutils-minimal which perl binutils gcc-toolchain pkg-config zlib))
    (arguments
     `(#:modules ((guix build utils))
       #:builder
       (begin
         (use-modules (guix build utils))
         (let ((target (string-append (assoc-ref %outputs "out") "/share")))
           (write target)
           (mkdir-p target)
           #t))))
    (home-page "https://github.com/impg")
    (synopsis
     "Build shell for Rust latest.")
    (description ".")
    (license license:expat)))
```

This can probably be simplified further ;).

The full guix.scm file with instructions can be found at

=> https://github.com/pjotrp/impg/blob/main/guix.scm
