### ISSUE TITLE
Cannot install toolchain if preceding option uses comma separated list as an argument

### ISSUE THREAD

**Issue by crawfxrd** [rust-lang/rustup#4073]
### Verification

- [x] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [x] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

```
Usage: rustup toolchain install [OPTIONS] <toolchain>...
```

If the option preceding `toolchain` uses a space to specify an argument, and the argument is a comma separated list, then rustup fails to determine the specified toolchain.

#### Actual

```
$ rustup toolchain install --component clippy,rustfmt nightly-2024-11-11
error: error: the following required arguments were not provided:
  <toolchain>...

Usage: rustup toolchain install --component <components>... <toolchain>...

For more information, try '--help'.
```

#### Expected

```
$ rustup toolchain install --component clippy,rustfmt nightly-2024-11-11
info: syncing channel updates for 'nightly-2024-11-11-x86_64-unknown-linux-gnu'
info: latest update on 2024-11-11, rust version 1.84.0-nightly (143ce0920 2024-11-10)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-std'
 26.6 MiB /  26.6 MiB (100 %)  21.8 MiB/s in  1s ETA:  0s
info: downloading component 'rustc'
 71.0 MiB /  71.0 MiB (100 %)  22.8 MiB/s in  3s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-std'
info: installing component 'rustc'
 71.0 MiB /  71.0 MiB (100 %)  29.6 MiB/s in  2s ETA:  0s
info: installing component 'rustfmt'

  nightly-2024-11-11-x86_64-unknown-linux-gnu installed - rustc 1.84.0-nightly (143ce0920 2024-11-10)

info: checking for self-update
```

### Steps

```
rustup toolchain install --component clippy,rustfmt nightly-2024-11-11
```

### Notes

Version 1.26.0 packaged for Debian Trixie works as expected.

Also works if `=` is used for the option arguments instead of a space: `--component=clippy,rustfmt`.

### Rustup version

```console
rustup 1.27.1 (54dd3d00f 2024-04-24)
```

### Installed toolchains

```console
Default host: x86_64-unknown-linux-gnu
rustup home:  /root/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2023-01-21-x86_64-unknown-linux-gnu
nightly-2024-05-11-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.82.0 (f6e511eec 2024-10-15)
```

### OS version

```console
debian:bookworm-20241016-slim
```

**Comment by 0xPoe** [comment]
I' ll take a look.

**Comment by rami3l** [comment]
@crawfxrd Thanks for the report!

@Rustin170506 Thank you for offering the help! Given that `rustup toolchain install --component=clippy,rustfmt beta` works as expected, I guess it's an upstream regression/breakage/misuse WRT the `clap` library...

**Comment by rami3l** [comment]
@crawfxrd Here is a minimal reproducer that you can run on https://play.rust-lang.org:

```rs
use clap::Parser;

#[derive(Debug, Default, Parser)] struct UpdateOpts {
    #[arg(num_args = 1..)] toolchain: Vec<String>,
    #[arg(short, long, value_delimiter = ',', num_args = 1..)] component: Vec<String>,
}

fn main() {
    dbg!(UpdateOpts::try_parse_from([
        "rustup-install",
        "--component=clippy,rustfmt",
        "beta"
    ]));
    dbg!(UpdateOpts::try_parse_from([
        "rustup-install",
        "--component",
        "clippy,rustfmt",
        "beta"
    ]));
}
```

... it gives:

```zig
[src/main.rs:9:5] UpdateOpts::try_parse_from(["rustup-install", "--component=clippy,rustfmt",
"beta"]) = Ok(
    UpdateOpts {
        toolchain: [
            "beta",
        ],
        component: [
            "clippy",
            "rustfmt",
        ],
    },
)
[src/main.rs:14:5] UpdateOpts::try_parse_from(["rustup-install", "--component", "clippy,rustfmt",
"beta"]) = Ok(
    UpdateOpts {
        toolchain: [],
        component: [
            "clippy",
            "rustfmt",
            "beta",
        ],
    },
)
```

... and I guess it's a good idea to ask @epage whether it's the desired effect and/or if anything has changed in that regard. We could have used the APIs wrong, maybe?

**Comment by rami3l** [comment]
To provide more context:
<details><summary>This is the corresponding code from v1.26.0:</summary>
<p>

https://github.com/rust-lang/rustup/blob/5af9b9484c1bb7a747700af5940ff9c479801dc8/src/cli/rustup_mode.rs#L394-L416
</p>

</details> 


<details><summary>... and that from v1.27.1:</summary>
<p>

https://github.com/rust-lang/rustup/blob/54dd3d00fd20e64dc522517a0d7be4285570a2f1/src/cli/rustup_mode.rs#L417-L438

</p>
</details>

<details><summary>... and finally, the same section from the bleeding-edge build:</summary>
<p>

https://github.com/rust-lang/rustup/blob/f10ada2aebc9f87254de4b2a846f0f49fbecc19e/src/cli/rustup_mode.rs#L337-L348

</p>
</details>


Note the use of `.num_args()` above, it looks suspicious at first, but might still be the right thing to do:

> As mentioned, in clap v4, `multiple_values` was replaced with [`num_args`](https://docs.rs/clap/latest/clap/struct.Arg.html#method.num_args).  You can do either `num_args(0..)` or `num_args(1..)` though I'd recommend looking over the docs for that function.
_https://github.com/clap-rs/clap/discussions/5120#discussioncomment-6968437_

**Comment by epage** [comment]
> I'd recommend looking over the docs for that function. https://github.com/clap-rs/clap/discussions/5120#discussioncomment-6968437

Key phrase :)

`num_args` controls how many elements of `std::env::args_os` can be captured.  When values are "attached" using `=`, we only accept one value.  When they are unattached, we will keep accepting values since there is no upper bound.  We provide a lot of cautions around this because of cases like this that will eat up positional arguments.  Most of the time what people want on options is not to use `num_args` but to use `ArgAction::Append` (which you get with `Vec`) and `value_delimiter`.

Historical context: clap v2 conflated flag "occurrences" with argument values as `multiple`.  To get behavior people wanted, they had to opt-in to behavior they don't want and then know how to work around it. In clap v3, we split `multiple` into `multiple_occurrences` (generally what people want, now `ArgAction::Append`) and `multiple_values` (rarely wanted, now `num_args(1..)`).

**Comment by rami3l** [comment]
> > I'd recommend looking over the docs for that function. [clap-rs/clap#5120 (reply in thread)](https://github.com/clap-rs/clap/discussions/5120#discussioncomment-6968437)
> 
> Key phrase :)
> 
> `num_args` controls how many elements of `std::env::args_os` can be captured. When values are "attached" using `=`, we only accept one value. When they are unattached, we will keep accepting values since there is no upper bound. We provide a lot of cautions around this because of cases like this that will eat up positional arguments. Most of the time what people want on options is not to use `num_args` but to use `ArgAction::Append` (which you get with `Vec`) and `value_delimiter`.
> 
> Historical context: clap v2 conflated flag "occurrences" with argument values as `multiple`. To get behavior people wanted, they had to opt-in to behavior they don't want and then know how to work around it. In clap v3, we split `multiple` into `multiple_occurrences` (generally what people want, now `ArgAction::Append`) and `multiple_values` (rarely wanted, now `num_args(1..)`).

@epage Thanks for the detailed explanation! Indeed, after removing `.num_args()`:

```rust
use clap::Parser;

#[derive(Debug, Default, Parser)] struct UpdateOpts {
    #[arg(num_args = 1..)] toolchain: Vec<String>,
    #[arg(short, long, value_delimiter = ',')] component: Vec<String>,
}

fn main() {
    dbg!(UpdateOpts::try_parse_from([
        "rustup-install",
        "--component=clippy,rustfmt",
        "beta"
    ]));
    dbg!(UpdateOpts::try_parse_from([
        "rustup-install",
        "--component",
        "clippy,rustfmt",
        "beta"
    ]));
    dbg!(UpdateOpts::try_parse_from([
        "rustup-install",
        "--component",
        "clippy",
        "--component",
        "rustfmt",
        "beta"
    ]));
}
```

... the output looks much better:

```zig
[src/main.rs:9:5] UpdateOpts::try_parse_from(["rustup-install", "--component=clippy,rustfmt",
"beta"]) = Ok(
    UpdateOpts {
        toolchain: [
            "beta",
        ],
        component: [
            "clippy",
            "rustfmt",
        ],
    },
)
[src/main.rs:14:5] UpdateOpts::try_parse_from(["rustup-install", "--component", "clippy,rustfmt",
"beta"]) = Ok(
    UpdateOpts {
        toolchain: [
            "beta",
        ],
        component: [
            "clippy",
            "rustfmt",
        ],
    },
)
[src/main.rs:20:5] UpdateOpts::try_parse_from(["rustup-install", "--component", "clippy",
"--component", "rustfmt", "beta"]) = Ok(
    UpdateOpts {
        toolchain: [
            "beta",
        ],
        component: [
            "clippy",
            "rustfmt",
        ],
    },
)
```

 I'll come up with a patch later today :)
