### ISSUE TITLE
Rustup installation fails on Fedora 41

### ISSUE THREAD

**Issue by nitin88** [rust-lang/rustup#4081]
### Verification

- [x] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [x] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

Hi,

With the latest Rustup (1.27.1) on Fedora 41, the installation fails 

```
❯ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer

Welcome to Rust!

This will download and install the official compiler for the Rust
programming language, and its package manager, Cargo.

Rustup metadata and toolchains will be installed into the Rustup
home directory, located at:

  /home/nigurr/.rustup

This can be modified with the RUSTUP_HOME environment variable.

The Cargo home directory is located at:

  /home/nigurr/.cargo

This can be modified with the CARGO_HOME environment variable.

The cargo, rustc, rustup and other commands will be added to
Cargo's bin directory, located at:

  /home/nigurr/.cargo/bin

This path will then be added to your PATH environment variable by
modifying the profile files located at:

  /home/nigurr/.profile
  /home/nigurr/.bash_profile
  /home/nigurr/.bashrc
  /home/nigurr/.zshenv

You can uninstall at any time with rustup self uninstall and
these changes will be reverted.

Current installation options:


   default host triple: x86_64-unknown-linux-gnu
     default toolchain: stable (default)
               profile: default
  modify PATH variable: yes

1) Proceed with standard installation (default - just press enter)
2) Customize installation
3) Cancel installation
>1

info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256' to '/home/nigurr/.rustup/tmp/5ndx2z5201pfrco3_file': failed to make network request: error sending request for url (https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256): client error (Connect): error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921: (unable to get local issuer certificate): error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:
```

Tested in 2 computers on F41 and same issue reproducable. 
By installing 1.26.0 from F40, I am able to successfully install it.

### Steps

Installation using `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` or `rustup-init`

### Rustup version

```console
1.27.1
```

### Installed toolchains

```console
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/nigurr/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.82.0 (f6e511eec 2024-10-15)
```

### OS version

```console
Fedora 41
```

**Comment by nitin88** [comment]
```
By installing 1.26.0 from F40, I am able to successfully install it
```

**Update:**
rustup-1.27.1-4.fc40.x86_64.rpm is also working fine except FC41 package which is built for Fedora 41

**Comment by rami3l** [comment]
@nitin88 Thanks for filing this issue!

This is very likely a download backend problem where it fails to get the certificate.

We have a potential fix ready for the next release, see https://github.com/rust-lang/rustup/issues/3806 for more info.

For the moment, you can try setting either `RUSTUP_USE_RUSTLS=1` or `RUSTUP_USE_CURL=1` (not both!) and see if it changes anything.

**Comment by rami3l** [comment]
As there are currently no further actions that can be taken from our side with respect to this issue, I'm closing it now as stale.

Please feel free to reopen if you have more information to provide.

Have a nice day :)
