### ISSUE TITLE
`rustup show active-toolchain` should provide the toolchain path

### ISSUE THREAD

**Issue by rami3l** [rust-lang/rustup#4129]
### Problem you are trying to solve

> Let me guess: you actually just want to get the active toolchain path with this snippet...
> 
> https://github.com/corrosion-rs/corrosion/blob/b88ec09915a6b12d1aaec7e451ecf0e41a831030/cmake/FindRust.cmake#L423-L428
> 
> ... however you might have tried the following options and concluded that neither is satisfactory:
> - `rustup show active-toolchain`. This seems like the most obvious option, however it is somehow not willing to give you the toolchain path...
> - `rustup toolchain list --verbose`. This does give you the toolchain paths, but you have to manually deduce what the active toolchain is :|

_https://github.com/corrosion-rs/corrosion/issues/590#issuecomment-2564138875_
            

### Solution you'd like

`rustup show active-toolchain` should provide the toolchain path, or optionally with `--verbose`.

**Comment by ChrisDenton** [comment]
I think maybe with `--verbose` would be better? I worry that people are parsing `rustup show active-toolchain` so changing it might break scripts, etc. Admittedly, if those scripts are just splitting on the first whitespace then it is less of an issue.

> `rustup toolchain list --verbose`. This does give you the toolchain paths, but you have to manually deduce what the active toolchain is :|

Maybe that should indicate the active toolchain as well.

**Comment by rami3l** [comment]
> > `rustup toolchain list --verbose`. This does give you the toolchain paths, but you have to manually deduce what the active toolchain is :|
> 
> Maybe that should indicate the active toolchain as well.

@ChrisDenton That's a description of the pre-v1.28 behavior. It's been fixed now.

**Comment by rami3l** [comment]
> I think maybe with `--verbose` would be better? I worry that people are parsing `rustup show active-toolchain` so changing it might break scripts, etc.

@ChrisDenton That compatibility, if it exists in the first place, is unfortunately already broken since https://github.com/rust-lang/rustup/pull/3225, so essentially this is a similar situation to #4045.
