### ISSUE TITLE
Can't update from 1.8 to 1.9 on Windows: could not remove multirust-bin

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rustup#426]
```
$ rustup update
info: syncing channel updates for 'stable-i686-pc-windows-gnu'
info: syncing channel updates for 'stable-i686-pc-windows-msvc'
info: syncing channel updates for 'stable-x86_64-pc-windows-gnu'
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: syncing channel updates for 'beta-x86_64-pc-windows-msvc'
info: syncing channel updates for 'nightly-i686-pc-windows-gnu'
info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
info: checking for self-updates
info: downloading self-update

      stable-i686-pc-windows-gnu unchanged - rustc 1.8.0 (db2939409 2016-04-11)
     stable-i686-pc-windows-msvc unchanged - rustc 1.8.0 (db2939409 2016-04-11)
    stable-x86_64-pc-windows-gnu unchanged - rustc 1.8.0 (db2939409 2016-04-11)
   stable-x86_64-pc-windows-msvc unchanged - rustc 1.8.0 (db2939409 2016-04-11)
     beta-x86_64-pc-windows-msvc unchanged - rustc 1.9.0-beta.2 (87cb73304 2016-05-04)
     nightly-i686-pc-windows-gnu unchanged - rustc 1.10.0-nightly (d91f8ab0f 2016-05-07)
  nightly-x86_64-pc-windows-msvc unchanged - rustc 1.10.0-nightly (d91f8ab0f 2016-05-07)


ale@ale-PC MINGW32 ~/rust2
$ error: could not remove 'multirust-bin' file: 'C:\Users\ale\.cargo\bin\multirust.exe'
info: caused by: Access is denied. (os error 5)
```

(note that it's giving me a second shell prompt and then that error is printing asynchronously)

**Comment by peschkaj** [comment]
FWIW, I successfully updated last night from Windows proper (no MinGW).

On Mon, May 9, 2016, 05:50 Alex Crichton <notifications@github.com> wrote:

> $ rustup update
> info: syncing channel updates for 'stable-i686-pc-windows-gnu'
> info: syncing channel updates for 'stable-i686-pc-windows-msvc'
> info: syncing channel updates for 'stable-x86_64-pc-windows-gnu'
> info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
> info: syncing channel updates for 'beta-x86_64-pc-windows-msvc'
> info: syncing channel updates for 'nightly-i686-pc-windows-gnu'
> info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
> info: checking for self-updates
> info: downloading self-update
>
>       stable-i686-pc-windows-gnu unchanged - rustc 1.8.0 (db2939409 2016-04-11)
>      stable-i686-pc-windows-msvc unchanged - rustc 1.8.0 (db2939409 2016-04-11)
>     stable-x86_64-pc-windows-gnu unchanged - rustc 1.8.0 (db2939409 2016-04-11)
>    stable-x86_64-pc-windows-msvc unchanged - rustc 1.8.0 (db2939409 2016-04-11)
>      beta-x86_64-pc-windows-msvc unchanged - rustc 1.9.0-beta.2 (87cb73304 2016-05-04)
>      nightly-i686-pc-windows-gnu unchanged - rustc 1.10.0-nightly (d91f8ab0f 2016-05-07)
>   nightly-x86_64-pc-windows-msvc unchanged - rustc 1.10.0-nightly (d91f8ab0f 2016-05-07)
>
>
> ale@ale-PC MINGW32 ~/rust2
> $ error: could not remove 'multirust-bin' file: 'C:\Users\ale\.cargo\bin\multirust.exe'
> info: caused by: Access is denied. (os error 5)
>
> (note that it's giving me a second shell prompt and then that error is
> printing asynchronously)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang-nursery/rustup.rs/issues/426>
>
-- 

Jeremiah Peschka

**Comment by brson** [comment]
I'm also seeing this and have a dead `rustup.exe` process in task manager, [similar to this issue](https://github.com/rust-lang-nursery/rustup.rs/issues/384).

**Comment by mati865** [comment]
Reproduced on CI https://ci.appveyor.com/project/brson/rustup-rs/build/1.0.1199/job/ir947ivv9i0s76ip

EDIT: Added missing link

**Comment by rbtcollins** [comment]
I'm going to close this - sorry that noone followed up, but I think multi-rust upgrades are proper buried by now.
