### ISSUE TITLE
Segfault on Linux 4.4.9 armv6l

### ISSUE THREAD

**Issue by mrhmouse** [rust-lang/rustup#439]
The following segfaults on my Raspberry Pi:

``` console
~$ curl https://sh.rustup.rs -sSfo rustup.sh
~$ chmod +x ./rustup.sh
~$ ./rustup.sh
info: downloading installer
./rustup.sh: line 220:   575 Segmentation fault      (core dumped) "$@"
rustup: command failed: /tmp/tmp.PpNF2ChKzq/rustup-init
```

This worked until attempting to run `rustup update` today. Unfortunately, I don't know the version of rustup that was being used previously.

**Comment by mrhmouse** [comment]
GitHub refuses to let me upload a zip file (suggesting I try a zip file instead...), so [here's](https://github.com/rust-lang-nursery/rustup.rs/files/259300/rustup.txt) the dumped core. I had to upload it as a zip file with the `txt` extension.

**Comment by brson** [comment]
Thank you for the report and the dump.

**Comment by flounders** [comment]
I've having a similar if not the same issue on Arch Linux Arm with Raspberry Pi Model 2 B (armv7l).

```
$ curl https://sh.rustup.rs -sSf | sh             
info: downloading installer
sh: line 225:   342 Segmentation fault      (core dumped) "$@"
rustup: command failed: /tmp/tmp.dVnwFS3Xew/rustup-init
```

**Comment by brson** [comment]
Perhaps this is related to missing NEON instructions. There was a [PR today](https://github.com/rust-lang-nursery/rustup.rs/pull/593) to install the armv6 toolchain if armv7 *without* NEON is detected.

**Comment by flounders** [comment]
I just tried running running rustup-init.sh from master a few minutes ago, and got pretty much the same error:

```
$ ./rustup-init.sh
info: downloading installer
./rustup-init.sh: line 238: 12686 Segmentation fault      (core dumped) "$@"
rustup: command failed: /tmp/tmp.ybqeQhziBv/rustup-init
```

**Comment by brson** [comment]
Thanks for checking @flounders.

**Comment by brson** [comment]
https://github.com/rust-lang-nursery/rustup.rs/pull/651 This PR updates the build machine toolchain from something ancient to the current stable compiler. Might fix things.

**Comment by yrnameer** [comment]
Both `arm` and `armv7` [nightlies](https://static.rust-lang.org/dist/index.html) segfault on my Rpi2. I don't think this is related to `rustup`.

**Comment by belstgut** [comment]
also have the same problem as op

`Linux rpi3 4.4.17-2-ARCH #1 SMP Tue Aug 16 19:17:53 MDT 2016 armv7l GNU/Linux`

**Comment by yrnameer** [comment]
Compiling from source also produces an unusable `rustc`. Errors are identical to that of rust-lang/rust#33928

**Comment by yrnameer** [comment]
Works fine on **Jessie Lite** btw, just tested out of curiosity. Is everyone here using **Arch Linux**?

**Comment by flounders** [comment]
I am using Arch Arm. I haven't been able to test anything recently as I just moved and don't have internet at my place, currently at work.

**Comment by mrhmouse** [comment]
I was on Arch Arm, but my SD card has died so I'm unable to test until I get a replacement.

**Comment by yrnameer** [comment]
Here's what eventually worked for me:
```
$ curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly
$ sudo patchelf --add-needed /usr/lib/libpthread.so.0 $(which rustc)
$ sudo patchelf --add-needed /usr/lib/libpthread.so.0 $(which cargo)
$ sudo patchelf --add-needed /lib/ld-linux-armhf.so.3 $(which cargo)

```

**Comment by enricostano** [comment]
> Works fine on Jessie Lite btw, just tested out of curiosity. Is everyone here using Arch Linux?

Linux alarmpi 4.4.17-2-ARCH #1 Tue Aug 16 19:37:06 MDT 2016 armv6l GNU/Linux

same problem here, the `patchelf` workaround works though.

**Comment by sizeak** [comment]
Same for me, patchelf fixed it for me too. 
Linux pie 4.4.23-1-ARCH #1 SMP Fri Sep 30 19:06:51 MDT 2016 armv7l GNU/Linux

**Comment by flounders** [comment]
Sorry for not testing this sooner. I tried what the ghost user suggested on Aug 22, and it works for me as well.

Linux alarmpi 4.4.39-1-ARCH #1 SMP Sun Dec 18 18:25:13 MST 2016 armv7l GNU/Linux

**Comment by kinnison** [comment]
Is this still an issue?
