### ISSUE TITLE
sh.rustup.sh script downloads hardfloat rustup-init on system with softfloat libraries

### ISSUE THREAD

**Issue by vi** [rust-lang/rustup#470]
On chrooted Debian running on Android device, sh.rustup.sh script downloads `https://static.rust-lang.org/rustup/dist/armv7-unknown-linux-gnueabihf/rustup-init` which requires interpreter `/lib/ld-linux-armhf.so.3`.

But on that system there is no `/lib/ld-linux-armhf.so.3`, there is just `/lib/ld-linux.so.3` instead.

Workaround: `ln -s ld-linux.so.3 /lib/ld-linux-armhf.so.3`. After that it has installed Rust (unusable).

Also manually copying respective files from host to `/lib/ld-linux-armhf.so.3` and `/lib/arm-linux-gnueabihf/*.so` Rust <s>works</s> fails to link (`hello.0.o uses VFP register arguments, hello does not`)

After `multirust add-target nightly arm-unknown-linux-gnueabi` I can build executables. But `build.rs` (therefore anything complexier) fails.

Final workaround:

```
cat > $HOME/rustct <<\EOF
#!/bin/sh
exec rustc --target arm-unknown-linux-gnueabi "$@"
EOF
echo export RUSTC=$HOME/rustct  >> $HOME/.profile
```

Expected: sh.rustup.sh downloads non-hardfloat rustup-init, which downloads non-hardfloat Rust (which builds non-hardfloat binaries and so on).

**Comment by alexcrichton** [comment]
Does the `arm-unknown-linux-gnueabi` target work for you? (as a rustup host)

**Comment by vi** [comment]
How do I check this? Shall I specify `arm-unknown-linux-gnueabi` explicitly to the `sh.rustup.sh` script somehow?

I was [trying to find more options for it](https://github.com/rust-lang-nursery/rustup.rs/issues/469), but it began downloading `arm-unknown-linux-gnueabihf` version without asking anything.

**Comment by alexcrichton** [comment]
You should be able to download directly from https://static.rust-lang.org/rustup/dist/arm-unknown-linux-gnueabi/rustup-init

**Comment by vi** [comment]
I'll try.

**Comment by vi** [comment]
It has installed nightly and working (with gnueabihf libraries moved out of way). I haven't tried stable.

**Comment by brson** [comment]
Good ideas about the error handling. rustup error handling needs a lot of improvements generally, but these platform detection issues are pretty much new territory for us (we've had an explosion of platform support recently).

If you can figure out how to modify the shell script to detect the correct float environment I'd be happy to take a patch.

Beefing up rustup error handling is one of my top priorities after I get back from upcoming vacation.

**Comment by kinnison** [comment]
Is the current `rustup-init.sh` any better for you?

**Comment by kinnison** [comment]
I'm going to assume it is.
