### ISSUE TITLE
PATH support doesn't work for fish shell

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#478]
It's a popular shell and doesn't read `.profile`. cc @nagisa cc https://github.com/rust-lang-nursery/rustup.rs/pull/468

**Comment by nagisa** [comment]
Many linuxes should be covered by putting the environment to both `~/.pam_environment` and `~/.profile`, though it is a bag of worms because either or both can be disabled, not run or configured to be in another, non-standard location (i.e. not `$HOME/.file`).

For OS X it seems like you’d want to also inform launchd about the updated path with `launchctl setenv PATH $PATH`.

Either way this goes, fixing https://github.com/rust-lang-nursery/rustup.rs/issues/473 is another thing that would fix a lot of the problem here.

**Comment by snheath** [comment]
FWIW OCaml's opam has a similar problem and handles it just by having a version of the add-stuff-to-PATH hook for each shell.  There's also the "eval (opam config env)" idiom which sets the appropriate environment variables to point to wherever opam thinks they need to point to, including PATH.

**Comment by ariasuni** [comment]
rustup create `env` with `export PATH="$HOME/.cargo/bin:$PATH"`. Why not create too a file `env.fish` (like opam) with `set -gx PATH "$HOME/.cargo/bin" $PATH;`?

**Comment by robey** [comment]
this still doesn't work. `~/.cargo/env` is completely wrong.

**Comment by icefoxen** [comment]
I think you can just drop the `set -gx ...` command in a file in `~/.config/fish/conf.d/`, see <http://fishshell.com/docs/current/index.html#initialization>

**Comment by chriswoollard** [comment]
I have had this issue a few times. It is easy to resolve.

Create a fish config file in the below directory, if it doesn't already exist.

`~/.config/fish/config.fish`

Then add the following line to the file.

`export PATH="$HOME/.cargo/bin:$PATH"`

Once you restart your terminal, the rust commands should work again.

**Comment by ndac-todoroki** [comment]
Exporting in a more fisher way
```fish
set PATH $HOME/.cargo/bin $PATH
```
in `~/.config/fish/config.fish` maybe better.

**Comment by mojotx** [comment]
An even more fishier way would be to use the fish_user_paths universal variable. 

Example:
`set -U fish_user_paths $HOME/.cargo/bin $fish_user_paths`

No need to mess with config files. A universal variable, once set, is permanently and persistently set across all fish shell sessions. The contents of that variable are automatically prepended to the $PATH environment variable.

**Comment by clearnote01** [comment]
Hi, any update with this, I think it's confusing that the script doesn't even at least mention this issue, nor is it mentioned with the documentation. I believe it's worthwhile to make change in the installation script to correctly handle for fish.

**Comment by kinnison** [comment]
Unfortunately nobody who works *on* `rustup` uses fish so we're not really in a position to know if anything we do would be right.  I've labelled this `E-mentor` because I'm prepared to assist someone who knows fish to prepare a PR, but I simply don't know the right things to do.  If you want to help solve this, I'm around either on this issue, or on the Rust discord in `#wg-rustup`

**Comment by nagisa** [comment]
As I commented above, we probably want to solve this is in a way that’s shell-independent. On linux that’d be `.pam_environment` and on macOS we’d use `launchctl`.

This will only become more relevant as people start experimenting and depending more with non-POSIX shells such as [nushell](https://github.com/nushell/nushell) or [powershell](https://github.com/powershell/powershell). We cannot possibly hope to handle all these different shells in a shell-specific manner.

**Comment by clearnote01** [comment]
Python `virtualenv` module does handle each shell in shell-specific manner. It has a similar problem to set environment variables for these different shells. For Unixy systems they have multiple versions of this `activate` script to support `fish` along with `csh` and `bash/zsh`.

At least for linux there are some problems with `~/.pam_environment`. Currently it doesn't seem to be read by WSL bash - [issue here](https://github.com/microsoft/WSL/issues/4782). 
  
Another, problem is that there seems to be a need to re-login after making changes in ~/.pam_environment, as per following:

> Suitable files for environment variable settings that should affect just a particular user (rather than the system as a whole) are ~/.pam_environment and ~/.profile. After having edited one of those files, you should re-login in order to initialize the variables.

https://help.ubuntu.com/community/EnvironmentVariables

**Comment by icefoxen** [comment]
@kinnison I use `fish` and am happy to try digging into Rustup if someone can point me in the right direction.

Realistically there seems to be only a small handful of non-POSIX shells people actually use, and once support is implemented it probably won't need much in the way of maintenance.

**Comment by kinnison** [comment]
@icefoxen Hi, I'm glad that you're interested in helping.  Just before the holidays, @clearnote01 (I believe) was looking into things, so it may be best to join forces with them.  If they've run out of energy for the work, perhaps you might help bring it over the line.

**Comment by lordlycastle** [comment]
So any progress? Also why not use `/etc/profile` which is read by shell independent?

**Comment by kinnison** [comment]
I believe @workingjubilee is looking at shell support so it's possible Fish may come later from their work.  We won't touch `/etc/profile` because that's global and `rustup` is a user-local installer.  Also, if `fish` reads `/etc/profile` why doesn't it also read `~/.profile` ?

**Comment by max-sixty** [comment]
FYI fish does not read any `profile` files

Source: https://github.com/fish-shell/fish-shell/issues/3665

**Comment by workingjubilee** [comment]
I recommend that because fish sessions are persisted that we detect fish during setup and direct the user to simply run the command which sets PATH appropriately, possibly after writing a fish script to make it easy.

**Comment by aadibajpai** [comment]
I would recommend simply running `set -Ua fish_user_paths $HOME/.cargo/bin` if on fish.¹ It persistently adds the cargo path to path and does not require modifying any file(s).

[1] https://github.com/fish-shell/fish-shell/issues/527#issue-10108069

**Comment by TylerYep** [comment]
I still had some issues even after trying `set -Ua fish_user_paths $HOME/.cargo/bin`, so instead I added the line `source $HOME/.cargo/env` to my `config.fish` file, which worked!

**Comment by aadibajpai** [comment]
fwiw, poetry installation which is also very similar to rustup does it like that as well https://github.com/python-poetry/poetry/blob/cc195f1dd086d1c4d12a3acc8d6766981ba431ac/get-poetry.py#L256

**Comment by jwillikers** [comment]
Rustup prefers to prepend it's bin directory to PATH in order to override any system `rustc`, so you would want to use `-p` instead of `-a` when setting `fish_user_paths` like so:

```sh
$ set -Up fish_user_paths ~/.cargo/bin
```

**Comment by mainrs** [comment]
For people stumbling across it later on. Newer fish versions have a new builtin command for appending to a path:

```console
fish_add_path <path>
```

This can be even called multiple times and will only append once to the path. Note that the builtin errors if the path doesn't exist.

**Comment by jhenninger** [comment]
> This can be even called multiple times and will only append once to the path.

It actually prepends to the path by default, which is even better. That is unless the given directory already exists in the path, in which case it is not moved to the front unless the `-m` switch is given.

**Comment by Ray-Eldath** [comment]
> An even more fishier way would be to use the fish_user_paths universal variable.
> 
> Example:
> `set -U fish_user_paths $HOME/.cargo/bin $fish_user_paths`
> 
> No need to mess with config files. A universal variable, once set, is permanently and persistently set across all fish shell sessions. The contents of that variable are automatically prepended to the $PATH environment variable.

Many thanks, this works! And I recommand use `fish_add_path $HOME/.cargo/bin`, it's easier and directly supported by fishshell. :wink:

**Comment by emadbaqeri** [comment]
> rustup create `env` with `export PATH="$HOME/.cargo/bin:$PATH"`. Why not simply also create a file `env.fish` (like opam) with `set -gx PATH "$HOME/.cargo/bin" $PATH;`?

As I'm using `ohmyfish` I have found the config for my terminal here `.config/fish/conf.d/omf.fish`.

**Comment by powerm1nt** [comment]
``export PATH="$HOME/.cargo/bin:$PATH"`` works fine :+1:

**Comment by wenwen12345** [comment]
> 即使在尝试之后我仍然遇到一些问题`set -Ua fish_user_paths $HOME/.cargo/bin`，所以我将这一行添加`source $HOME/.cargo/env`到我的`config.fish`文件中，这有效！

~/.cargo/env (line 4): 'case' builtin not inside of switch block
case ":${PATH}:" in
^
from sourcing file ~/.cargo/env
        called on line 6 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
        called during startup
source: Error while reading file '/Users/lw/.cargo/env'
It don't work

**Comment by wenwen12345** [comment]
I add the $HOME/.cargo/bin in my /etc/paths, it works.

**Comment by freakydude** [comment]
Create a new fish config file (or use an existing one). Here for example `pathvars` under:

`nano ~/.config/fish/conf.d/pathvars`

and add

```fish
if status --is-login
    set -gx PATH $PATH ~/.cargo/bin
end
```

login/logout

**Comment by lordlycastle** [comment]
Just want to say that’s not the most *fish*y of achieving that. You can use the `fish_user_path` variable or even easier use the utility function `fish_add_user_path`.  😌

**Comment by ehartford** [comment]
setting a path manually should be within the skillset of a fish user.  and if not - frankly, they should use bash.

**Comment by lordlycastle** [comment]
I don’t think people want this feature because it is too difficult to set the path var. 

It is the not knowing what to do to fix the issue. If they know they should add to path after install then it should tell the user about it. 

Things should be obvious so you can service all types of users and not gatekeep because it makes you feel like hackerman.

**Comment by Elmer-Almeida** [comment]
> For people stumbling across it later on. Newer fish versions have a new builtin command for appending to a path:
> 
> ```
> fish_add_path <path>
> ```
> 
> This can be even called multiple times and will only append once to the path. Note that the builtin errors if the path doesn't exist.

This worked for me! Thank you!

**Comment by re3factor** [comment]
Currently running into this issue, I've tried almost everything in this thread, anyone available to help?
![image](https://user-images.githubusercontent.com/26598892/168183408-0b4fca91-8ffd-4883-bb98-e13be42884fe.png)

**Comment by social-anthrax** [comment]
Very much necroing this issue, but I'm trying to figure out what would be the best approach to adding cargo to path. It seems like there are currently three possibilities; Using `fish_add_path`, `set -Up fish_user_paths` and adding the existing source file to `$__fish_config_dir/conf.d/`. While the first two are more to the spirit of fish, it makes it more difficult to remove it, and the last one feels like a hack. Any thoughts regarding what the proper way to approach this would be appreciated.

**Comment by DCNick3** [comment]
> Any thoughts regarding what the proper way to approach this would be appreciated.

I think that `fish_add_path` seems to be the best way for now, as it is shorted and idempotent (it checks is the path is already in the `PATH` yet)

**Comment by social-anthrax** [comment]
Reading through the thread again, the official advice from 2016 was source the env file from ~/.config/fish/conf.d/ from [fish shell issue 3170](https://github.com/fish-shell/fish-shell/issues/3170). This makes the removal significantly easier as we can just remove the cargo.fish file from conf.d

**Comment by re3factor** [comment]
@social-anthrax @DCNick3 Thank you both very much, sorry for the necro, I just realized I never sent my appreciation.

**Comment by iMonZ** [comment]
Any update here?

**Comment by salimp2009** [comment]
Just trying to use fish  I have rust, ghcup (for Haskell) that all have their binaries under $HOME
and i also have nix and it has bunch of nix related folders in the home directory none of those work properly if fish becomes default shell  unless I edit config.fish like this. I still need to figure out nix cause it is a little different config set.

`if status is-interactive
    # Commands to run in interactive sessions can go here
end

if status --is-login
     set -gx PATH "$HOME/.cargo/bin" $PATH;
     export PATH="$HOME/.cabal/bin:$PATH"
     export PATH="HOME/.ghcup/bin:$PATH"
end`

**Comment by SirMishaa** [comment]
Hello, 

For [fish 3.2.0](https://github.com/fish-shell/fish-shell/releases/tag/3.2.0) or upper, released in March 2021, the easiest way to add rust to path permanently is like that:

```bash
fish_add_path $HOME/.cargo/bin
```
It will automatically append the specified folder to ``fish_user_paths`` in ``$HOME/.config/fish/fish_variables``.
Documentation can be found here: https://fishshell.com/docs/current/cmds/fish_add_path.html

I hope it helps

---

Would a Rust team maintainer be interested in a pull request that checks the shell used and acts accordingly? 
Concretely, it's just a small condition in the source file to have the path added automatically (using ``fish_add_path``) when the user uses Fish as shell.

Please let me know.

**Comment by nikitavoloboev** [comment]
> ```shell
> fish_add_path $HOME/.cargo/bin
> ```

I added this to my fish config. However when I open a new terminal inside VSCode, I am getting this error:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/6391776/201447020-13227809-76ef-4f4d-92e3-f7e01ca9bad9.png">

```shell
~/.cargo/env (line 4): 'case' builtin not inside of switch block
case ":${PATH}:" in
^
from sourcing file ~/.cargo/env
        called on line 11 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
        called during startup
source: Error while reading file '/Users/nikiv/.cargo/env'
~/src/cli/ingestor main*
base ❯ 
```

Not sure how to fix.
