### ISSUE TITLE
Add release archives to CI.

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#479]
It's useful to be able to go back to old releases.

**Comment by Diggsey** [comment]
@brson I think we have these now right? Although I don't remember the URL, so we could probably do with documenting it somewhere...

**Comment by rami3l** [comment]
I'm closing this as completed, as our [user guide](https://github.com/rust-lang/rustup/blob/81a71647f4615d85267325b8dd8019a37e01f9fd/doc/user-guide/src/installation/other.md#manual-installation) already provides instructions on manually installing an old version of Rustup.
