### ISSUE TITLE
rustup-init windows -- provide more info regarding host triples

### ISSUE THREAD

**Issue by eminence** [rust-lang/rustup#547]
Running `rustup-init.exe` on Windows, and it says this:

```
Current installation options:

   default host triple: x86_64-pc-windows-msvc
     default toolchain: stable
  modify PATH variable: yes
```

Suggestion 1 -- The MSVC triple won't work on my machine, since it requires Visual Studio 2015 (which I don't have).   It probably would be nice if this was mentioned in the installer text

I then pressed `2` to customize the install options, knowing that I would need to select another host triple.  But I couldn't quite remember the spelling of the GNU version, so I had to look it up (which admitedly was not hard).  Suggestion 2 -- Include some more information on allowable (or suggested) host triples

**Comment by Diggsey** [comment]
@eminence It will only choose `msvc` if it detects `cl.exe`. Detection is done by the `gcc` crate, so if it detects it, it should work. It doesn't need to be that specific version of visual studio, it's 2015 or newer I believe. Which version do you have?

**Comment by eminence** [comment]
I do indeed have Visual Studio installed (and hence `cl.exe`), but not the right version -- I have Visual Studio 2008, 2010, and 2012.   This machine is my computer at Work, so I don't have the ability to install a new version of Visual Studio.

**Comment by rbtcollins** [comment]
We've changed this and now recommend MSVC by default and prompt folk to install the toolchain, because the MSVC hosted rustup is much faster; so this bug is obsolete. There may be other bugs as a consequence of course; do feel free to file them :).
