### ISSUE TITLE
Slow downloads in Western Europe

### ISSUE THREAD

**Issue by lorenz** [rust-lang/rustup#571]
I have 1Gbps Internet in Switzerland from a pretty good provider (Init7). I'm being routed to Cloudfront Frankfurt with about 15ms latency. But I'm only getting around 1.2MiB/s (10Mbps). Is that just Amazon being slow or can you do something about that?

**Comment by brson** [comment]
Offhand I don't know of anything else we can do to speed up delivery. We're using all available CDN endpoints.

**Comment by Tanjoodo** [comment]
I live in Jordan and while I don't have a fancy 1Gbps connection, the downloads are incredibly slow for me. We're talking <100KiB/s.

**Comment by lorenz** [comment]
@Tanjoodo I think I found out what's really happening (I regularly experience slowdowns from Amazon):
Amazon internally caches the data in their CloudFront PoPs, so if it's actually cached there I can get in the order of 200 to 800Mbps. As soon as I access something that is less downloaded (like some Docker images that are also served from CloudFront) the speed drops dramatically to a few Megabytes per second, probably because the CloudFront PoP is pulling down the content itself before serving it, which seems to be really slow.

Currently I am getting 500Mbps on the main Rust downloads (current stable x86_64) and around 10Mbps on the more obscure ones (like mips-unknown-linux-musl). The Jordan PoP is likely less well connected to the us-east S3 bucket (or they use unmodified TCP which limits available bandwidth by latency) and thus has even lower download rates. If you're getting less than 10Mbps (1MiB/s) on stable downloads, it's either an Amazon or a provider issue.

@brson You could probably try something like CloudFlare in front of S3, they seem to perform much better (at least here). [They apparently officially support that](https://support.cloudflare.com/hc/en-us/articles/200168926-How-do-I-use-CloudFlare-with-Amazon-s-S3-Service-). Maximum file size seems to be 512MiB, so that would work. (I'm not affiliated with CloudFlare, they just seem to be the fastest ones out there for me).

**Comment by alanhoff** [comment]
I'm also experiencing painfully slow downloads with a 120Mbps network (south of Brazil)

<img width="290" alt="screen shot 2018-03-08 at 14 54 23" src="https://user-images.githubusercontent.com/1044223/37167451-c166bf76-22e0-11e8-93b9-502867f83c31.png">

```
rustc --version; and cargo --version; and rustup --version; and uname -ra
rustc 1.26.0-nightly (bedbad611 2018-02-26)
cargo 0.26.0-nightly (1d6dfea44 2018-01-26)
rustup 1.11.0 (e751ff9f8 2018-02-13)
Darwin Alans-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64
```

**Comment by lorenz** [comment]
@alanhoff Basically there is nothing they can do other than switching their CDN provider. Amazon Cloudfront performs abysmally when the content is not cached at their edge node. I have a provider with a direct 10Gbps PNI to Amazon and a 1Gbps dedicated fiber to me and still get a few 100Kbps on files not commonly downloaded (the common ones are cached and fast).

**Comment by rami3l** [comment]
I'm closing this now, as the situation regarding the release server might have changed, and there seems to be no further actions to be taken on our side.

Please feel free to reopen if that isn't the case.
