### ISSUE TITLE
Modify CI so that release staging is not done on master

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#582]
Today, the master branch builds releases and pushes them to dev-static.rlo, which are later copied to static.rlo for the final release. Instead I'd prefer if master is just doing CI, and I have to push to e.g. the 'stable' or 'release' branch to trigger a build. Seems too error prone if there are problems during the release.

**Comment by kinnison** [comment]
Release staging has been done on the `stable` branch for several years now.
