### ISSUE TITLE
Figure out how to get static linkage for MSVCRT

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#660]
In order to get the MSI installers working we need to build with the MSVC toolchain and link statically to the CRT.

@alexcrichton without an upstream solution how can we solve this the hard way? I'm thinking something like:
- Modify gcc-rs to interpret some environment variable to mean pass /MT, in a fork if necessary
- Build our own i686-pc-windows-msvc toolchain while setting that environment variable
- Use that toolchain to build rustup, while setting the environment variable

cc https://github.com/rust-lang-nursery/rustup.rs/pull/635#issuecomment-239611678
cc https://github.com/rust-lang/rfcs/pull/1684
cc @Boddlnagg @retep998

**Comment by retep998** [comment]
The `libc` crate forces `msvcrt.lib` to be linked. Either it would have to be modified both for crates.io and the one used in std, or you'd have to set the linker to a wrapper program that strips any mentions of `msvcrt.lib` before forwarding it on to the actual linker.

**Comment by brson** [comment]
Maybe the linker wrapper is the easiest solution to all these. We can strip `msvcrt.lib` and convert `/MD` to `/MT`.

So we don't need to build a custom toolchain at all, right? Just fix the linker invocation? Is there just one invocation of link.exe globally here? This seems almost easy...

**Comment by retep998** [comment]
`/MD` and `/MT` are flags passed to `cl.exe` for C/C++ code, not `link.exe`.

**Comment by brson** [comment]
So that sounds like we do need a custom toolchain.

- Create a new `static-link.exe` project that strips the `msvcrt.lib`
- Modify gcc-rs to interpret some environment variable to mean pass /MT, in a fork if necessary
- Build our own i686-pc-windows-msvc toolchain while setting that environment variable
- Use that toolchain to build rustup, while setting the environment variable and the fake linker

**Comment by retep998** [comment]
@brson If you do use a linker wrapper, then there is no need to rebuild the Rust toolchain. There is no C/C++ code in `libstd` and friends that could be affected. There is in rustc itself but that has no effect on code built by rustc.

**Comment by Boddlnagg** [comment]
To pass /MT in gcc-rs I just used a local fork with a cargo override. A `[replace]` in Cargo.toml should be sufficient, right (in addition to the linker wrapper)?

**Comment by alexcrichton** [comment]
@brson I think custom linker shenanigans would work here, but having never done it I'm not 100% sure it'd actually work.

**Comment by brson** [comment]
> To pass /MT in gcc-rs I just used a local fork with a cargo override. A [replace] in Cargo.toml should be sufficient, right (in addition to the linker wrapper)?

I think so.

**Comment by retep998** [comment]
If this does turn out to work, then I can totally use this as an example to push along my RFC.

**Comment by retep998** [comment]
This can now be implemented fairly easily considering Rust now has a built in way to link to the static CRT. https://github.com/rust-lang/rust/issues/37406

**Comment by tesuji** [comment]
@kinnison I think this issue is resolved.

**Comment by kinnison** [comment]
Yep, thanks @lzutao
