### ISSUE TITLE
Reenable anti-sudo check

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#699]
Disabled because it's being miscompiled. https://github.com/rust-lang-nursery/rustup.rs/pull/698

**Comment by inejge** [comment]
Is there a known distro/nightly/rustup commit combination that produces a crashing `rustup-init` for 64-bit Linux? I tried with nightly-2016-08-21 and rustup pre-0.6.2 on CentOS 6, but couldn't get a segfault.

**Comment by kinnison** [comment]
This looks to have been reenabled in https://github.com/rust-lang/rustup/commit/e308c567c0274ec93cd2876030c2b5316e6be2fe
