### ISSUE TITLE
Wrong `default-host` leads to panic

### ISSUE THREAD

**Issue by Boddlnagg** [rust-lang/rustup#745]
Setting something like `rustup set default-host x64_86-msvc` (on Windows) leads to the following error on `rustup show` or `rustup install`:

```
thread 'main' panicked at 'host triple couldn't be converted to partial triple', ../src/libcore\option.rs:700
```

I think it shouldn't accept an invalid `default-host` in the first place ...

**Comment by lazpeng** [comment]
Also happens with the initial installation, selecting a custom install and passing an "invalid" triple such as "stable-x86_64-pc-windows-gnu" also leads to panic

**Comment by Bluejanis** [comment]
That wrong default host didnt even let me install rustup correctly.
I had to delete the directory and set it to gnu manually for it to work.

**Comment by kinnison** [comment]
Hi, I have begun looking at this since it does seem to continue to be a problem.  I've opened PR #1578 and I would welcome any advice on there of where to add the checks needed to *cleanly* report this early and usefully to the user.

**Comment by rbtcollins** [comment]
I believe https://github.com/rust-lang/rustup/pull/1578 fixed this; If a similar issue occurs again please open a new ticket.
