### ISSUE TITLE
How to upgrade to rust 1.15, why nightly channel never be updated?

### ISSUE THREAD

**Issue by ghost** [rust-lang/rustup#811]

**Comment by steveklabnik** [comment]
Could you provide some more information here? Rust 1.5 is quite old. The nightly channel should be updated.

**Comment by ghost** [comment]
Sorry typing error!

**Comment by Diggsey** [comment]
Dup of #810 which amusingly has the exact same typo in the title...

**Comment by liigo** [comment]
> which amusingly has the exact same typo in the title...

Thank you! Fixed (1.5 => 1.15). (I'm the author of #810 .)
