### ISSUE TITLE
missing man page for override

### ISSUE THREAD

**Issue by supr** [rust-lang/rustup#813]
When running
`rustup man override`

The file override.1 doesn't exist
`error: not a file: '/home/p/.multirust/toolchains/stable-x86_64-unknown-linux-gnu/share/man/man1/override.1'`

**Comment by pickfire** [comment]
@supr What are the expected error message?

**Comment by tesuji** [comment]
@kinnison What can we do with this?

**Comment by kinnison** [comment]
We now report "No manual entry for override" so that's fine, this is no longer an issue.
