### ISSUE TITLE
Updating via proxy is broken

### ISSUE THREAD

**Issue by IBUzPE9** [rust-lang/rustup#816]
```
$ rustup update
info: syncing channel updates for 'stable-i686-unknown-linux-gnu'
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256' to '/home/alex/.multirust/tmp/h9gv9l1ioc5sxyws_file
info: syncing channel updates for 'nightly-i686-unknown-linux-gnu'
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-nightly.toml.sha256' to '/home/alex/.multirust/tmp/kg598po8umhl2wyc_file
info: checking for self-updates
error: could not download file from 'https://static.rust-lang.org/rustup/release-stable.toml' to '/tmp/rustup-update.GOUjAy7RGqrP/release-stable.toml
info: caused by: error during download
info: caused by: [7] Couldn't connect to server (Unsupported proxy scheme for 'https://192.168.254.10:808/')
```

Everything worked fine before I updated `rustup` to latest version.

Xubuntu 14.04 32bit
rustup 0.6.5 (88ef618 2016-11-04)

**Comment by IBUzPE9** [comment]
Version 1.0.0 doesn't work. The error message remains the same.

**Comment by xiaoaiwhc** [comment]
If you are behind a proxy, you can try to set up the https_proxy variable in your environment.  For my windows 10, I use the setting:  
`set https_proxy=http://ip:port ( NOTES: not 'https' in the url) `
and it works.

**Comment by IBUzPE9** [comment]
Thanks. It works. 
I googled same issue with **curl** : https://github.com/curl/curl/issues/1015
Just out of curiosity, why is the https support removed everywhere?
