### ISSUE TITLE
(gdb) wrong path - rustbuild

### ISSUE THREAD

**Issue by jbolila** [rust-lang/rustup#821]
On Mac the result of this command:

```sh
rustup run nightly rustc -g --emit="obj,link" ex.rs && /usr/local/bin/gdb ex
```

doesn't map to the correct std source folder, instead of `/Users/jbolila/.multirust//toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcollections/vec.rs` in this example, is pointing to `/Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac` something that doesn't exists. 

```gdb
(gdb) s
collections::vec::{{impl}}::deref<i32> (self=0x7fff5fbfedb0)
    at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/obj/../src/libcollections/vec.rs:1478
1478	/Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/obj/../src/libcollections/vec.rs: No such file or directory.
```

Tested on rustup 0.6.5 (88ef618 2016-11-04)

**Comment by sbwdlihao** [comment]
Same problem

MacOS Sierra 10.12.3
GNU gdb (GDB) 7.12.1 （installed by brew)
rustup 1.0.0 (17b6d21 2016-12-15)

Debug program is hello_world from guide [Getting started](https://doc.rust-lang.org/book/getting-started.html)

1. gdb main -q
![image](https://cloud.githubusercontent.com/assets/5118170/22922316/34b063d6-f2d8-11e6-8074-f9d336a23d74.png)

2. l main
![image](https://cloud.githubusercontent.com/assets/5118170/22922334/50c5e83e-f2d8-11e6-9dad-50b79d414e00.png)

3. b 1
![image](https://cloud.githubusercontent.com/assets/5118170/22922352/63b46948-f2d8-11e6-8d4e-3135240c512d.png)

4. run
![image](https://cloud.githubusercontent.com/assets/5118170/22922376/7a2484ce-f2d8-11e6-8974-17998adac3a8.png)

5. n
![image](https://cloud.githubusercontent.com/assets/5118170/22922392/84362f80-f2d8-11e6-8fab-18e3edb9d706.png)

6. n
![image](https://cloud.githubusercontent.com/assets/5118170/22922409/9db630fe-f2d8-11e6-826b-76320671ecfa.png)

`panic_unwind::__rust_maybe_catch_panic ()
    at /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libpanic_unwind/lib.rs:106
106	/Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libpanic_unwind/lib.rs: No such file or directory.`

**Comment by Diggsey** [comment]
This is expected behaviour: the debug information is set when the standard library was compiled, so it can't know where you ended up installing it.

See https://sourceware.org/gdb/onlinedocs/gdb/Source-Path.html for how you can set up gdb to remap the paths appropriately.
