### ISSUE TITLE
directory does not exist: '"share/man/man1/rustdoc.1"'

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rustup#836]
I'm getting an error on update:

> \# rustup update nightly
> info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: rolling back changes
**error: failure removing component 'rustc-x86_64-unknown-linux-gnu', directory does not exist: '"share/man/man1/rustdoc.1"'**

rustup 0.6.5 (88ef618 2016-11-04)

Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

beta-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

beta-x86_64-unknown-linux-gnu (default)
rustc 1.14.0-beta.2 (e627a2e6e 2016-11-16)
Linux 4.4.0-042stab120.5 #1 SMP Tue Oct 25 22:31:12 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux. Ubuntu 16.04.1 LTS

**Comment by kinnison** [comment]
Closed in favour of #1480, please comment there if you have further information.
