### ISSUE TITLE
'rustup toolchain link' doesn't seem to work under MSYS2

### ISSUE THREAD

**Issue by japaric** [rust-lang/rustup#839]
```
$ rustup toolchain link stage1 build/x86_64-pc-windows-gnu/stage1

$ echo $?
0

$ rustup default stage1
info: no toolchain installed for 'stage1'

$ rustup toolchain list
nightly-x86_64-pc-windows-gnu (default)
stage1

$ rustup toolchain remove stage1
info: no toolchain installed for 'stage1'
```

I think this is because the toolchain subcommand has special logic on Windows because one can pick between two toolchains: mingw and msvc (I think the logic implicitly appends a triple to the toolchain or something like that). Perhaps, that special logic shouldn't be used for custom toolchains.

cc @brson

**Comment by Diggsey** [comment]
Dup of #488 - it's fixed on master there just hasn't been a release since.

**Comment by japaric** [comment]
Oh, OK. That's why I didn't find any open issue about this. Closing then.
