### ISSUE TITLE
Nightly Cargo tracking broken

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rustup#844]
We changed how Cargo's released, now we're not publishing manifests. Although this works for rust-packaging, it doesn't work for rustup. We need to figure out a solution. (can't believe I forgot about this)

**Comment by jchlapinski** [comment]
@alexcrichton could You please provide more background on why that was changed? Is there an ongoing change on the way Rust+Cargo will be released?

**Comment by Diggsey** [comment]
Yes, I was trying to find out earlier about the change and was frustrated by the lack of any information...

**Comment by tbu-** [comment]
Is there a way I can fix my local Cargo until this is resolved? I still have the one with https://github.com/rust-lang/cargo/issues/3340.

**Comment by jchlapinski** [comment]
> Is there a way I can fix my local Cargo until this is resolved? I still have the one with rust-lang/cargo#3340.

@tbu- Actually You can, as described here: https://github.com/rust-lang/cargo/issues/3340#issuecomment-263699137
For me on Ubuntu 16.04 I had to do:
```
> export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
```

**Comment by carols10cents** [comment]
@jchlapinski @Diggsey what information do you need? is there something you would do with that information?

**Comment by alexcrichton** [comment]
@jchlapinski @Diggsey the "information" here unfortunately is essentially "complete and total knowledge of Rust's release infrastructure". There has been quite a few bugs in the past few weeks either related to Cargo or distribution infrastructure, all of which are getting combined into a so-called perfect-storm of bugs to prevent Cargo from being fixed for quite some time.

I personally hope to fix this as soon as possible. There's a Mozilla work week in Hawaii right now so I don't have a ton of time, but when I get a chance I'll try to watch builds and such. My current attempt to fix this is https://github.com/rust-lang/rust-buildbot/commit/92a5919f803aaec8183c0101c877633de08df577, we'll find out in the morning if it worked.

**Comment by alexcrichton** [comment]
Note that this bug was mostly just a reminder to me/brson, there's not a lot actionable beyond that unfortunately.

**Comment by jchlapinski** [comment]
Ok, I can see now, that my previous question might seem somewhat hostile and critical, while I was just genuinely curious. I tought maybe there is on ongoing effort to integrate cargo with rust under a single versioning scheme, maybe even integrate it into the rust repo? It would make sense to me as it would ease the maintenance somewhat. I looked for a discussion on this and could not find any, hence I asked here.

@alexcrichton thanks for Your time explaining.
@carols10cents I was considering helping, as Alex mentioned that a solution was needed. What do You need _this_ information for?

Peace

**Comment by carols10cents** [comment]
> @carols10cents I was considering helping, as Alex mentioned that a solution was needed. What do You need this information for?

I wanted to see if you had a dependency on the internals of rust's release infrastructure, and to see if I could get you the actual information you needed without taking up any of Alex's time.

**Comment by Diggsey** [comment]
> the "information" here unfortunately is essentially "complete and total knowledge of Rust's release infrastructure"

> We changed how Cargo's released

Information relevant to the actual "change" would be sufficient, I don't know why you'd assume that I wanted a complete description of the infrastructure from scratch...

A description of what the fallout will look like for a rustup user would also be helpful.

I presume this change was implemented in a PR somewhere?

**Comment by carols10cents** [comment]
> A description of what the fallout will look like for a rustup user would also be helpful.

Once this issue is fixed, rustup users should not notice any change. The change is purely internal implementation.

**Comment by brson** [comment]
Looks like @alexcrichton is working on the fix https://github.com/rust-lang/rust-buildbot/commit/92a5919f803aaec8183c0101c877633de08df577

**Comment by alexcrichton** [comment]
Ok, fix looks like it's working:

```
$ cargo +nightly version
cargo 0.16.0-nightly (built 2016-12-06)
```

Closing this but I'll try to write something up about this at some point.

@Diggsey Cargo nightlies are now produced from Travis/AppVeyor, not buildbot, which basically just changed how everything is laid out.

**Comment by tbu-** [comment]
What do I need to do to receive this fix? Update rustup?

**Comment by lambda-fairy** [comment]
@tbu- Running `rustup update` works for me. As @carols10cents said above: the issue was completely server-side, and so you don't need to do anything specific to receive the fix.

**Comment by jchlapinski** [comment]
@lfairy after `rustup update` I still have:
```
> rustc --version
rustc 1.15.0-nightly (ebeee0e27 2016-12-04)
> cargo --version
cargo 0.16.0-nightly (3568be9 2016-11-26)
```

**Comment by jimmycuadra** [comment]
I still get `cargo 0.16.0-nightly (3568be9 2016-11-26)` on both macOS and Linux. Maybe we need to wait for tomorrow's nightly to pick up the changes.

**Comment by alexcrichton** [comment]
I believe I failed to bust caches this morning, should be good now.

**Comment by tbu-** [comment]
Works now, thanks!
