### ISSUE TITLE
cargo: exit on signal swallowed by rustup wrapper

### ISSUE THREAD

**Issue by birkenfeld** [rust-lang/rustup#845]
See https://github.com/rust-lang/cargo/issues/3367 - the difference:
```
$ cargo run
   Compiling rust-test v0.1.0 (file:///home/gbr/devel/rust-test)
    Finished debug [unoptimized + debuginfo] target(s) in 0.14 secs
     Running `target/debug/rust-test`
$ target/debug/rust-test
[1]    7789 segmentation fault  target/debug/rust-test
```
The exit on signal is hidden by rustup's cargo wrapper.

**Comment by brson** [comment]
Thanks for the report!

What's the right thing to do here? Does cargo without rustup treat the signal specially?

**Comment by KalitaAlexey** [comment]
It is a dupe of #806.
