### ISSUE TITLE
'rustup toolchain install stable-x86_64-pc-windows-gnu' failure

### ISSUE THREAD

**Issue by foresterre** [rust-lang/rustup#846]
Hello,

I am trying to install a rustup toolchain for windows, however, when trying to install such toolchain, rustup returns errors telling me its 'main' thread  panicked.

**Steps taken:**
1. Obtained rustup-init.exe from [rustup.rs](https://www.rustup.rs)
2. Installed rustup with customized installation:
  - Changed default host triple to `x86_64-pc-windows-gnu`
  - Used default toolchain `stable`
  - Said `yes` to modify PATH variable
3. Restarted powershell
4. Ran `rustup toolchain install stable-x86_64-pc-windows-gnu`
 

**Expected:**

Rustup to download and install the selected toolchain.

**Actual results (using : `$env:RUST_BACKTRACE=1`):**
```
PS D:\src> rustup toolchain install stable-x86_64-pc-windows-gnu
thread 'main' panicked at 'host triple couldn't be converted to partial triple', ../src/libcore\option.rs:700
```
or (which is directly copied from the documentation listed at ` rustup toolchain --help`)
```
PS D:\src> rustup toolchain install stable-x86_64-pc-windows-msvc
thread 'main' panicked at 'host triple couldn't be converted to partial triple', ../src/libcore\option.rs:700
```

**Platform:**
Windows version: `Windows 8.1 x86_64`
Rustup version: `rustup 0.6.5 (88ef618 2016-11-04)` obtained from `rustup-init.exe` downloaded from [rustup.rs](https://www.rustup.rs) on 2016-12-03.
Existing rust version (manually installed):
- `rustc 1.12.0 (3191fbae9 2016-09-23)` which also existed on the PATH.

Thank you in advance for helping to solve this issue.
If this issue already exists, or I am doing something (obvious) wrong, please accept my sincere excuse for such mistake.
I checked on existing issues with the following tags: `is:issue is:open install`, `is:issue is:open install windows`, `is:issue is:open install windows gnu`.

**Comment by brson** [comment]
Awesome bug report. Thank you @foresterre .

**Comment by brson** [comment]
OK, here's what I think happened. When you selected a default host, the value you entered was incorrect; rustup didn't validate it; now rustup is all broken.

If you type `rustup show` I bet it would show something like

```
$ rustup show
Default host: x86_4-unknownl-linux-gnu

thread 'main' panicked at 'host triple couldn't be converted to partial triple', ../src/libcore\option.rs:705
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

It can be repaired like

```
rustup set default-host x86_64-pc-windows-gnu
```

To fix this bug rustup-init needs to validate the triple passed on the command line, or entered through user input. Make sure it converts to a TargetTriple and back. There interactive input will take some new code for handling input errors.

**Comment by foresterre** [comment]
Awesome, it works now 😄. 
Thanks for your help!

(`rustup show` did not show any host at all (the result was empty)).
