### ISSUE TITLE
Re-running rustup-init deletes multirust directory instead of migrating it

### ISSUE THREAD

**Issue by xen0n** [rust-lang/rustup#848]
This is definitely caused by #830, although I haven't looked closely into the patch. This would affect those people who:

* blindly re-`rustup-init` when there's an update, or
* compile their own `rustup-init` in the meantime (although this group may be small).

Steps to repro (assuming you're already on `.rustup`):

```sh
# Backup your toolchains; they'll go away!
cp -r .rustup <some-backup-location>
# Revert to old dir layout
rm .multirust
mv .rustup .multirust
# Re-run `rustup-init`
/path/to/your/dev/rustup-init
# Just ^C after the installation begins
ls ~/.rustup
# Boom! the original toolchains and settings are gone.
```

This is likely due to the unconditional `create_rustup_home` which ultimately deleted the legacy rustup home during symlinking. We should perform the migration *before* proceeding with home creation.

**Comment by xen0n** [comment]
n.b. This is discovered on my MIPS64 box, where there's presently no other way to update `rustup`, apart from manually copying `rustup-init` over to the proxy binaries under `~/.cargo/bin` which is tedious.

**Comment by brson** [comment]
Thanks for the report. Looking into it.
