### ISSUE TITLE
Rustup fails with 404 on freebsd

### ISSUE THREAD

**Issue by casey** [rust-lang/rustup#849]
I got the following error:

```
$ curl https://sh.rustup.rs -sSf | sh
info: downloading installer
curl: (22) The requested URL returned error: 404 Not Found
rustup: command failed: curl -sSfL https://static.rust-lang.org/rustup/dist/i686-unknown-freebsd/rustup-init -o /tmp/tmp.ZOBiDUqb/rustup-init
```

It looks like https://static.rust-lang.org/rustup/dist/i686-unknown-freebsd/rustup-init doesn't exist

**Comment by brson** [comment]
rustup is trying to install the i686 FreeBSD build, which does not exist. If your machine is really a 64-bit machine though rustup-init.sh should attempt to install x86_64-unknown-freebsd, in which case there is a bug in rustup-init.sh.

rustup-init.sh should display a better error message for unsupported platforms.

**Comment by casey** [comment]
It's a 32 bit machine:

```
z: uname -a
FreeBSD z 11.0-RELEASE-p1 FreeBSD 11.0-RELEASE-p1 #0 r306420: Thu Sep 29 03:40:55 UTC 2016     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  i386
```

Is 32 bit freebsd unsupported?

**Comment by Diggsey** [comment]
32-bit freebsd is currently only a tier 3 platform, so binaries are not produced: https://forge.rust-lang.org/platform-support.html

**Comment by casey** [comment]
Would it be possible to print an explicit error message in this case, instead of a 404?

**Comment by mqudsi** [comment]
> Would it be possible to print an explicit error message in this case, instead of a 404?

Yes, please!

It would be even more helpful if the prompt said "use your OS' package manager to install rust instead" as the binaries (though not necessarily the latest ones at the time a new version is released) _are_ available via `pkg` on FreeBSD.
