### ISSUE TITLE
rustup-init segfault when using --no-modify-path

### ISSUE THREAD

**Issue by svenstaro** [rust-lang/rustup#856]
This is something I noticed while building the official rustup package for Arch Linux. The build script looks like this:

```
build() {
    cd "$srcdir/$pkgname.rs-${pkgver}"
    # cargo update
    cargo build --release --features no-self-update --bin rustup-init

    mkdir -p "$srcdir/tmp/.cargo"
    env -u CARGO_HOME "HOME=$srcdir/tmp" target/release/rustup-init -y --no-modify-path
}
```

It segfault at the last line with

```
/startdir/PKGBUILD: line 17:   764 Segmentation fault      (core dumped) env -u CARGO_HOME "HOME=$srcdir/tmp" target/release/rustup-init -y --no-modify-path
```

When I take away the `--no-modify-path` it doesn't segfault anymore.

This is only appears to happen on x86_64 and works fine on i686.

**Comment by brson** [comment]
Thanks for the report!

**Comment by brson** [comment]
I haven't been able to reproduce this on my Ubuntu system with the `rustc 1.14.0-nightly (cae6ab1c4 2016-11-05)` toolchain.

**Comment by xen0n** [comment]
Maybe provide a dump of `env` output *inside the PKGBUILD*? I do some Gentoo packaging and know that build recipes (*ebuilds* in Gentoo land) usually run in quite bizarre environments set up by the package manager. Pretty much the entirety of rustup CLI is test-covered so it's unlikely to be reproduced with ordinary use (and environments).

**Comment by svenstaro** [comment]
```
LANG=C
SUDO_GID=0
OLDPWD=/build/rustup/src
COMMAND_MODE=legacy
USERNAME=builduser
SUDO_COMMAND=/usr/bin/makepkg -s --noconfirm -L --holdver -i
CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong
USER=builduser
CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong
TEXTDOMAINDIR=/usr/share/locale
PWD=/build/rustup/src/rustup.rs-1.0.0
HOME=/build
TEXTDOMAIN=pacman-scripts
SUDO_USER=root
SUDO_UID=0
MAIL=/var/mail/builduser
CHOST=x86_64-pc-linux-gnu
SHELL=/bin/bash
TERM=xterm-256color
SHLVL=1
CPPFLAGS=-D_FORTIFY_SOURCE=2
LOGNAME=builduser
LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
MAKEFLAGS=-j13
_=/usr/bin/env
```

**Comment by xen0n** [comment]
Hmm... this is becoming interesting. Have you tried to extract a backtrace with `RUST_BACKTRACE=1`? Sorry I forgot to also request this information, as I previously was concerned with the envvars.

**Comment by N-006** [comment]
Build fine on Arch (x86_64) with rustc 1.13.0.
