### ISSUE TITLE
Travis: missing distribution-id for aws cloudfront invocation

### ISSUE THREAD

**Issue by xen0n** [rust-lang/rustup#862]
[Docs for `aws cloudfront create-invalidation`](http://docs.aws.amazon.com/cli/latest/reference/cloudfront/create-invalidation.html)

I've always been bugged by this while looking around the CI logs until realizing it's actually a FIXME. I have no experience with AWS (but have been using Linode for a while instead btw) hence don't know exactly what action to take for this. I read that the invalidation is important for release so maybe this is already manually taken care of?

**Comment by brson** [comment]
The release process has changed a bit since the ci invalidations were broken and it doesn't really matter whether we do them at the moment. We could just delete that code.

**Comment by xen0n** [comment]
Oh that's fine then. I'm closing the issue as the team is aware and it's not really a problem.

Thanks for the explanation!
