### ISSUE TITLE
Cannot add toolchain

### ISSUE THREAD

**Issue by tafia** [rust-lang/rustup#870]
I could not update my toolchain so I tried removing it then reinstalling it. It fails with the same error:

```
$ rustup toolchain add nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: downloading component 'rustc'
 51.7 MiB /  51.7 MiB (100 %)   6.5 MiB/s ETA:   0 s
info: downloading component 'rust-std'
 71.7 MiB /  71.7 MiB (100 %)   7.4 MiB/s ETA:   0 s
info: downloading component 'cargo'
error: component download failed for cargo-x86_64-unknown-linux-gnu
info: caused by: could not download file from 'https://s3.amazonaws.com/rust-lang-ci/cargo-builds/ddb5c328d67f046c929928f161d50eef1cbc3e81/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz' to '/home/aerdev01/.rustup/tmp/wq1kjv8rdq69_59t_file
info: caused by: error during download
info: caused by: [56] Failure when receiving data from the peer (Received HTTP code 407 from proxy after CONNECT)
```
I did a `rustup self update` before.
```
$ rustup -V
rustup 1.0.0 (17b6d21 2016-12-15)
$ uname -r
2.6.32-431.29.2.el6.x86_64
```

It used to work without any issue before (ie before rustup 1.0). I am working behind a corporate firewall. Setting HTTP_PROXY/HTTPS_PROXY environment variables used to be sufficient.

Any idea?

**Comment by tafia** [comment]
I get the same error from curl.
```
curl https://s3.amazonaws.com/rust-lang-ci/cargo-builds/ddb5c328d67f046c929928f161d50eef1cbc3e81/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz
```

I can do a 
```
rustup install nightly-2016-12-05-x86_64-unknown-linux-gnu
```
But I got the error when doing 
```
rustup install nightly-2016-12-06-x86_64-unknown-linux-gnu
```

I suppose our firewall is the culprit and the url has changed. 
If I'm right, as asking for firewall permission is not exactly simple in my company, I'd like to know if it is supposed to change again in the future?

**Comment by redtankd** [comment]
I got the same problem.

The download url for Cargo was changed from `static.rust-lang.org` to `s3.amazonaws.com`. So my mirror site for rustup hasn't worked .

**Comment by Diggsey** [comment]
AIUI, the issue is that the firewall was blocking access to the AWS url? I don't imagine it will change again any time soon :/
