### ISSUE TITLE
Documentation bug: unclear how to use pre-release versions of Rustup.

### ISSUE THREAD

**Issue by carlpaten** [rust-lang/rustup#871]
[This change](https://users.rust-lang.org/t/psa-rust-documentation-is-now-optional-and-opt-in-when-installing-via-rustup/8072/18) is something I'm super excited about, unfortunately it looks like it hasn't made it to the release version of rustup. I dug into the `README.md` file looking for a way to use the rustup nightly but didn't find anything.

**Comment by steveklabnik** [comment]
We talked about this on IRC, right? There is no "rustup nightly". Can this be closed?
