### ISSUE TITLE
Clarify help for update

### ISSUE THREAD

**Issue by johnthagen** [rust-lang/rustup#873]
It's mentioned in the [docs](https://github.com/rust-lang-nursery/rustup.rs#keeping-rustup-up-to-date), but when you run `rustup --help`:

```bash
...
update         Update Rust toolchains
...
```

`rustup update` also updates rustup itself. While I think this is a good idea, I was a little surprised by the action. `rustup update --help` does explains things well.

Could consider changing the top level help to something like:

```bash
update         Update Rust toolchains and rustup
```

Since you can also do `rustup self update`, maybe this could be confusing though.

**Comment by brson** [comment]
Hm, this is a little tricky because while `rustup update` updates rustup itself, `rustup update nightly` does not, so documenting the subcommand as "Update Rust toolchains and rustup" also seems a bit confusing.

Still, I think your suggestion is an improvement. Let's do it.

**Comment by johnthagen** [comment]
@brson PR created.
