### ISSUE TITLE
Clippy doesn't work with rustup 1.0 on Windows

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rustup#876]
Looks like the PATH / LD_LIBRARY_PATH issue is back, that used to happen here: https://github.com/rust-lang-nursery/rustup.rs/pull/402

If you run clippy with the latest rustup, you get this:

```
C:/Users/Christopher/.cargo/bin/cargo-clippy.exe: error while loading shared libraries: rustc_driver-36e125fb8252217f.dll: cannot open shared object file: No such file or directory
```

rustc 1.15.0-nightly (8f02c429a 2016-12-15)
rustup 1.0.0 (17b6d21 2016-12-15)
clippy 0.0.104

Could be caused by the .multirust -> .rustup change. If you put the full sysroot/bin path into your PATH, everything seems to work.

Clippy issue is over here: https://github.com/Manishearth/rust-clippy/issues/1395

**Comment by retep998** [comment]
This is https://github.com/rust-lang/cargo/issues/3394

**Comment by epage** [comment]
For anyone like me who is wondering which path is missing from PATH:
https://gist.github.com/epage/6a4c3397d9d2f12894a636799f41cd50

Thats for my windows toolchain but the idea should be similar for any other windows toolchains or affected platforms.

**Comment by rami3l** [comment]
Closing in favor of https://github.com/rust-lang/rust-clippy/issues/1395.
