### ISSUE TITLE
rustup-init URL for mips is 404

### ISSUE THREAD

**Issue by hsivonen** [rust-lang/rustup#881]
On big-endian 32-bit MIPS  (Debian Wheezy on QEMU from https://people.debian.org/~aurel32/qemu/mips/ ):

```
$ curl https://sh.rustup.rs -sSf | sh
info: downloading installer
curl: (22) The requested URL returned error: 404
rustup: command failed: curl -sSfL https://static.rust-lang.org/rustup/dist/mips-unknown-linux-gnu/rustup-init -o /tmp/tmp.HJlKuLW3Z8/rustup-init
```

**Comment by hsivonen** [comment]
CC @xen0n

**Comment by xen0n** [comment]
@hsivonen This is due to #797 not landing, mips support is actually complete. cc @brson

**Comment by xwafish** [comment]
mips64el still have the same issue, so Rust 1.15.1 which released at Feb 9,2017, does not support mips64el right?

> curl https://sh.rustup.rs -sSf | sh
info: downloading installer
curl: (22) The requested URL returned error: 404 Not Found
rustup: command failed: curl -sSfL https://static.rust-lang.org/rustup/dist/mips64el-unknown-linux-gnuabi64/rustup-init -o /tmp/tmp.jZ6IYwI0sA/rustup-init

thank you.

**Comment by xwafish** [comment]
https://www.rust-lang.org/en-US/other-installers.html
here have mip64 mipsel mips, but no mips64el :(
Why? I'd like a mips64el version, Tkanks very much

**Comment by xen0n** [comment]
@xwafish We most likely need to wait for a new release of rustup.

**Comment by xen0n** [comment]
Also the alternative installer page is actually missing `mips64el` by mistake, but IMO it's better fixed along with a new release. So let's just wait...

**Comment by xwafish** [comment]
thank you.
