### ISSUE TITLE
PATH to cargo/bin is in wrong file, should be in .bash_profile (CentOS)

### ISSUE THREAD

**Issue by e-oz** [rust-lang/rustup#883]
CentOS is default AWS EC2 version of Linux, please consider to add path into .bash_profile also, at least if this file exist.

**Comment by e-oz** [comment]
And cargo doesn't work at all (even if .bash_profile contains PATH to cargo), when invoked from cli, not shell. Previous installation, via https://static.rust-lang.org/rustup.sh , was working even from cli.

**Comment by theres-waldo** [comment]
I have the same issue on Debian - the statement to add `.cargo/bin` to the PATH is added to `.profile`, but I have a `.bash_profile`, so `.profile` is not used.

(For me, after moving the statement to `.bash_profile`, things _do_ work.)

**Comment by RandomInsano** [comment]
Same issue on OS X unfortunately. Assuming anywhere Bash is found. Not sure what the standard is here short of just telling users "fix it yourself", which the installer technically told me to do.

**Comment by theres-waldo** [comment]
The man page for bash says (emphasis mine):

> When bash is invoked as an interactive login shell [...] it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes commands from the **first one** that
>        exists and is readable.

So, for full compatibility, rustup could do something like:

  * If ~/.bash_profile exists, add the statement there
  * Otherwise, if ~/.bash_login exists, add the statement there
  * Otherwise, if ~/.profile exists, add the statement there
  * Otherwise, create one of these files (probably ~/.bash_profile) and add the statement there

**Comment by Diggsey** [comment]
@theres-waldo That assumes that the user is using bash, as opposed to another shell or a gui application.

We should:
- Add to `~/.profile` as we do now
- For each shell (bash, zsh, etc.) we decide to explicitly support
    - If that shell will not read `~/.profile` based on the files that exist
        - Add to the first existing file that the shell will read.

**Comment by RandomInsano** [comment]
> That assumes that the user is using bash

Exactly the problem... I think it's reasonable to warn users who aren't using Bash that some extra work needs to be done.

**Comment by johnthagen** [comment]
I just hit the same problem on a default install of Ubuntu 16.04 x64.

Seems like a pretty big usability hurdle for new people.

**Comment by nrc** [comment]
I also just hit this
