### ISSUE TITLE
Allow running previously downloaded installer after failed rustup

### ISSUE THREAD

**Issue by jdm** [rust-lang/rustup#884]
I've been having connection timeouts while using rustup all afternoon today, and each time I restart it it has to download the installer all over again. It would be nice if rustup were smart enough to cache artifacts and avoid downloading them again.

**Comment by canfoderiskii** [comment]
Yeah, it would be perfect if this feature is added. I often encounter the timeout problem. It's quite annoying.

**Comment by Diggsey** [comment]
Should have been fixed in #958
