### ISSUE TITLE
Allow rustup and rust-init to install package from local file?

### ISSUE THREAD

**Issue by canfoderiskii** [rust-lang/rustup#885]
I've been faced with some network problem and the direct download speed is very slow and a time-out  error can be easily seen. 
But I can use other downloading tools like "Internet Download Manager" to successfully fetch file from the link like this "https://static.rust-lang.org/dist/2016-12-21/rustc-1.14.0-x86_64-pc-windows-gnu.tar.gz".

I can see that when rustup or rust-init start downloading, it always creates a temp file in $HOME/.rustup/tmp. 

Is there any way to tell the rustup or rust-init not to create a new tmp file but use the .tar.gz file I just downloaded via other method? 
Is there any command line parameters for this feature? or is it possible to be added?

**Comment by louy2** [comment]
https://github.com/rust-lang-nursery/rustup.rs/blob/master/README.md#working-with-custom-toolchains-and-local-builds

You can decompress the archive to wherever and use the method cited above to link it into rustup. It just won't be recognized as from release channel.

**Comment by canfoderiskii** [comment]
@louy2 Thank you.  
1. But how can I specify the location of  `rust-std` package? I also downloaded the `rust-std-1.14.0-x86_64-pc-windows-gnu.tar.gz` seperately.
2. How to add the source code of `rust` in this way?

**Comment by louy2** [comment]
Oh, I just noticed that you only downloaded rustc. 

I downloaded my archive here: https://www.rust-lang.org/en-US/other-installers.html

It comes with rustc, cargo, rust-doc, rust-std, etc. 

You can also download source code at the above mentioned link.

**Comment by canfoderiskii** [comment]
@louy2 Thank you, I think the offline archive is best for me.
