### ISSUE TITLE
Make rustup-init install docs by default

### ISSUE THREAD

**Issue by illandan** [rust-lang/rustup#891]
Hi,

As a total beginner to rust, I installed `rustup` on the recommendation of folks from `#rust-beginners`. After installing it, `rustup` recommends that I run `rustup doc --book` if I'm totally new to rust. So, following that I ran into an error and found that docs were not installed. I had to do `rustup component add rust-docs` and I'm back in business :-)

Can we have rustup install docs for initial setup, at least for stable channels?

**Comment by steveklabnik** [comment]
I've had multiple people comment on IRC that the change to no-docs has been a problem for them; at least two were already in a situation where they no longer had the bandwidth to download the docs, but assumed that they'd be there.

**Comment by illandan** [comment]
@steveklabnik Right, I was not sure if others had faced such a problem, but filed an issue anyway. My point is, if `rustup-init` recommends that I do `rustup doc --book`, then should docs not already be available? So, we can either point people at some URL (removing `rustup-init`'s recommendation) or make docs bundled with initial install.  I think we can safely assume that people opting for nightly or other channels know what they are doing and can install docs separately if they need them.

**Comment by steveklabnik** [comment]
Yes, I'm agreeing with you.

**Comment by dgellow** [comment]
I had the same confusing first experience.
I install `rustup`, run `rustup help`, notice the note about `rustup doc --book`, run the command and ... nothing. No error, no fail state, nothing.

**Comment by re-mint** [comment]
I also had the same first experience, thinking that the installer must've failed somewhere.
If I hadn't found this thread, I wouldn't know what to do. Perhaps, the suggestion to read the Rust book should include the command to install it?

> If you are new to Rust consider running 'rustup component add rust-docs' and then 'rustup doc --book' to learn Rust.

**Comment by bmmoore** [comment]
This issue is rather aggravated by none of

    rustup doc --help
    rustup toolchain help
    rustup --help
    rustup toolchain list

mentioning a thing about how to install the docs, or whether they are installed.

**Comment by vn971** [comment]
@bmmoore totally agree. I've now spent a pack of minutes traversing the ~/.rustup file tree trying to find out the docs, to no success. Finally I google/searx out this issue, type in the command `rustup doc --book`... and nothing again.
This needs to be fixed IMO.

**Comment by frewsxcv** [comment]
I didn't have the `rust-docs` component installed, and I tried to run `rustup doc --book`. Upon running it, immediately returns with a `0` status.

```
rustup 0.6.5 (88ef618 2016-11-04)
```

After I installed the `rust-doc` component, it ran as expected. It'd be nice if there was a message indicating I should install that component.

**Comment by Diggsey** [comment]
This was changed back to make docs required.
