### ISSUE TITLE
Redundant copies of multi-call binaries on OS X

### ISSUE THREAD

**Issue by RandomInsano** [rust-lang/rustup#892]
I just installed Rust via rustup today (I like it quite a bit). I checked the binaries folder and noticed they were all the same (`diff` and `ls` show same contents and size) and then played around with deleting a few and symlinking them. It turns out each binary is a muti-call binary (BusyBox's term) so each one has the same functionality.

I'm just curious why they're all 4.5MB copies of each other instead of a single binary with symlinks to the rest. Here's my experimentation folder:

```
Mobile-029:bin edwin.amsler$ ls -hl
total 36752
lrwxr-xr-x  1 edwin.amsler  staff     5B 29 Dec 16:27 cargo -> rustc
-rwxr-xr-x  4 edwin.amsler  staff   4.5M 29 Dec 16:22 rust-gdb
-rwxr-xr-x  4 edwin.amsler  staff   4.5M 29 Dec 16:22 rust-lldb
-rwxr-xr-x  4 edwin.amsler  staff   4.5M 29 Dec 16:22 rustc
lrwxr-xr-x  1 edwin.amsler  staff     5B 29 Dec 16:26 rustdoc -> rustc
-rwxr-xr-x  4 edwin.amsler  staff   4.5M 29 Dec 16:22 rustup
```

Any reason why the install process made six copies of the same file? Is this intentional or a bug in the install process?

**Comment by Diggsey** [comment]
They are hard-links of the rustup binary, so no disk space is wasted. Symlinks require admin permissions to create on windows, and afaik provide no real advantage over hard-links in this case.

**Comment by RandomInsano** [comment]
Ah, alright.
