### ISSUE TITLE
Error in main during installation

### ISSUE THREAD

**Issue by mvaude** [rust-lang/rustup#899]
## Context

I am trying to install `rustup` on `NixOS` following the given command:
```
curl https://sh.rustup.rs -sSf | sh
```

## Problem

I got a `No such file or directory` error whereas I succeed to download `rust-init`.
It is misleading the right path:

```sh
$ curl https://sh.rustup.rs -sSf | sh
info: downloading installer
main: line 319: /tmp/tmp.Eoyb1b5X9v/rustup-init: No such file or directory
rustup: command failed: /tmp/tmp.Eoyb1b5X9v/rustup-init

$ ls /tmp/ | grep tmp
tmp.Cn4houR848
```

**Comment by kamarkiewicz** [comment]
`NixOS` has libraries in non-standard places; rustup-init executable has to be patched or recompiled on this system... Other solution I see is to precompile it with every release. How to patch: http://unix.stackexchange.com/a/252232

**Comment by Diggsey** [comment]
Unfortunately rustup doesn't work on nixos yet, see #673 for an issue tracking a possible solution.
