### ISSUE TITLE
Not finding std dll

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rustup#900]
So far I had no problems with "-C prefer-dynamic" (Windows 64 bit, GNU)
Recently I've switched to rustup, and now if I compile a program with "-C prefer-dynamic" it says it can't find
missing std-f652078ccb4a05c6.dll

I have solved the problem adding a path ...:\Users\Utente\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib

Perhaps this path should be added during rustup installation.

**Comment by retep998** [comment]
This is https://github.com/rust-lang/cargo/issues/3394

**Comment by leonardo-m** [comment]
OK, closed.
