### ISSUE TITLE
rustup doc should deal with absent doc instead of silently failing

### ISSUE THREAD

**Issue by toastedcornflakes** [rust-lang/rustup#901]
On a new install of rustup, running `rustup doc` fails silently if the documentation is not installed: the browser does not open, and there is no error message.

Would it be OK to add an error message, or to automatically run `rustup component add rust-docs` ?

This is tangentially related to #891 — if the doc is installed by default, this issue would be moot.

**Comment by dgellow** [comment]
@toastedcornflakes ah thank you for this issue! I was trying to understand why `rustup doc --book` doesn't seem to work.

**Comment by Zteve** [comment]
+1

**Comment by RalfJung** [comment]
It doesn't fail silently here, but it fails: When I do `rustup doc`, I get the following error:
```
Unable to run the command specified. The file or folder /home/r/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/index.html does not exist.
```

It is not at all obvious to me how to even install the docs. `rustup help doc` doesn't tell me. Seems like I will have to do some more googling...

**Comment by kinnison** [comment]
I'd appreciate input on whether or not #2116 is sufficient

**Comment by toastedcornflakes** [comment]
#2116 is what I had in mind when I raised this, thanks!

**Comment by kinnison** [comment]
Thank you.
