### ISSUE TITLE
Modify manifests so rust-docs are required again

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#903]
It seems that most people are comforted knowing docs are available by default, so I want to turn them back on, then add some more options to remove them.

This needs to be done in rust-buildbot.

re https://users.rust-lang.org/t/psa-rust-documentation-is-now-optional-and-opt-in-when-installing-via-rustup/8072/21

**Comment by bmmoore** [comment]
It's not just a question of comfort! Until the rustup bug about trying to open missing docs (symptoms as rust-lang-nursery/rustup.rs#959 or rust-lang-nursery/rustup.rs#901), and the now-incorrect --help text is fixed (rust-lang-nursery/rustup.rs#891) it's a big hit to usability too. Please don't leave this broken.

**Comment by brson** [comment]
Here's a patch https://github.com/rust-lang/rust/pull/40526
