### ISSUE TITLE
Modify live manifests so rust-docs are default-but-optional

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#906]
Once it's possible to define components that are optional and installed by default, do so for rust-docs. Modification to rust-buildbot.

cc https://github.com/rust-lang-nursery/rustup.rs/issues/905
cc https://users.rust-lang.org/t/psa-rust-documentation-is-now-optional-and-opt-in-when-installing-via-rustup/8072/20

**Comment by leonardo-m** [comment]
See some discussions:
https://users.rust-lang.org/t/rust-is-slow-semi-clickbait/21896/

**Comment by kinnison** [comment]
Does this remain desirable?  Modern channels are fine, and while there are some important users who install older toolchains, I don't think it's very common these days.

**Comment by thedavidmeister** [comment]
@kinnison is what desirable? installing the docs is suuuper slow on mac and windows CI builds (about 10 minutes and can even cause timeouts), even when it doesn't time out it is very expensive for no benefit

**Comment by kinnison** [comment]
@thedavidmeister Yes, so for modern CI you should be using `--profile minimal` to ensure you're not installing docs.  My point was "is that sufficient, or is it a problem that on older pre-profile channels it would still be slow" ?

**Comment by thedavidmeister** [comment]
oh right, i see what you're saying

i still need to test it out, i'm using nixos so i'll have to see how this interfaces with the mozilla overlays, but it sounds great

**Comment by kinnison** [comment]
@thedavidmeister Whenever you can, that'd be awesome.  Thank you.
