### ISSUE TITLE
Add a `--minimal` flag to `rustup-init`

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#907]
When passed, rustup installs only required components. This would be used for e.g. automation.

Depends on https://github.com/rust-lang-nursery/rustup.rs/issues/906

**Comment by brson** [comment]
cc https://users.rust-lang.org/t/psa-rust-documentation-is-now-optional-and-opt-in-when-installing-via-rustup/8072/20

**Comment by Rantanen** [comment]
_Since I just spent a while trying to figure this out and these issues are still dominating Google results, I'll update these with the current status._

Documentation _was_ opt-in in till early 2017 (like the URLO thread above states), but then they were made required again in March 2017, tracked by #903 in rustup.rs. While that issue wished for "some more options to remove them", that hasn't happened.. yet.

Fortunately #998 seems to have some recent activity towards allowing opt-out for the docs.

I'm guessing the profiles nrc references in #998 might also solve the use case for the '--minimal' flag for this issue.

**Comment by nrc** [comment]
#1541 include a minimal profile which will not install docs.

**Comment by ndrewxie** [comment]
Yeah. Docs takes absolutely forever to install on windows. Took 4 hours installing 1.30.0, and I ctrl + c'ed it after 3 hours installing 1.31.1

**Comment by steveklabnik** [comment]
Triage: this now exists as --profile=minimal, so I think it can be closed.

**Comment by kinnison** [comment]
@steveklabnik thanks for the triage.
