### ISSUE TITLE
Label more beginner friendly tasks

### ISSUE THREAD

**Issue by lpil** [rust-lang/rustup#909]
Hello! Inspired by [these tweets](https://twitter.com/jdub/status/817417833072103425) I thought it'd be nice to try and contribute to rustup, but was unable to determine if any of the issues were something I could manage. Would it be possible to label more beginner friendly issues, assuming there are any.

**Comment by brson** [comment]
Yes, I need to triage the issue tracker, put together a sensible roadmap. Thank you for the reminder.
