### ISSUE TITLE
rustup.sh --add-target=foo --prefix=~/foobar doesn't work due to ~

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rustup#918]
`--add-target` and `--list-targets` use `! -e "$_prefix/lib/rustlib/channel-manifest.toml"`, which apparently doesn't expand the `~` while all other commands do so. This means the prefix needs to be fully expanded by the user before passing it to rustup.sh

**Comment by Diggsey** [comment]
I think this is for the wrong rustup?
