### ISSUE TITLE
s3 are not stable in China, choose the mirror automatically, and also could restart the previous failed download point.

### ISSUE THREAD

**Issue by lygstate** [rust-lang/rustup#925]
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: downloading component 'rustc'
 28.2 MiB /  28.2 MiB (100 %) 230.4 KiB/s ETA:   0 s
info: downloading component 'rust-std'
 37.2 MiB /  37.2 MiB (100 %) 278.4 KiB/s ETA:   0 s
info: downloading component 'cargo'
error: component download failed for cargo-x86_64-pc-windows-msvc
info: caused by: could not download file from 'https://s3.amazonaws.com/rust-lang-ci/cargo-builds/298a0127f703d4c2500bb06d309488b92ef84ae1/cargo-nightly-x86_64-pc-windows-msvc.tar.gz' to 'C:\Users\lygstate\.rustup\tmp\5o9ax94dltezbfai_file
info: caused by: error during download
info: caused by: [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 30 seconds)

Press the Enter key to continue.

**Comment by fkysly** [comment]
+1

I also failed at 99%.

**Comment by brson** [comment]
This issue should be fixed now. The inclusion of s3 addresses was a bug. New addresses are on a CDN with exit nodes in Asia.

Download resume is the subject of https://github.com/rust-lang-nursery/rustup.rs/issues/889

Thanks for the report.
