### ISSUE TITLE
inability to handle multiprocess `target add` breaks rustup

### ISSUE THREAD

**Issue by hazel-ocean** [rust-lang/rustup#926]
Just found this last night while "saving myself some time" during a rustup installation. I wrote a short ruby script to install some architectures to a machine using the following script:

```ruby
architectures = %w{ <architectures here> }

architectures.each do |_arch|
    out = IO.popen("rustup target add #{_arch}")
    puts out
end
```

After spinning off a process to download each architecture and promptly failing I went to install each architecture synchronously with:

```ruby
architectures = %w{ <architectures here> }

architectures.each do |_arch|
    out = `rustup target add #{_arch}`
    puts out
end
```

and found that I could no longer install any targets, either with a script or as a `rustup target add $TARGET` from the shell. Deleting the `~/.rustup/tmp` directory to fix the issue didn't work. I ended up just deleting the `.rustup` directory and reinstalling targets synchronously.

Either a lock to prevent multiple occurrences of rustup operating within the same `.rustup` directory or a check for running rustup processes, each with and a subsequent fail wirg an appropriate error message would fix the issue.

**Comment by brson** [comment]
Thank you for the report @lewisinc!

Effectively the same problem as https://github.com/rust-lang-nursery/rustup.rs/issues/988.

rustup just has no notion of concurrent execution.
