### ISSUE TITLE
rust-gdb / rust-lldb are available on Windows while it wouldn't work?

### ISSUE THREAD

**Issue by DoumanAsh** [rust-lang/rustup#929]
I'm not sure from where are coming these tools (couldn't find source code)

But on my windows setup it is just:
```
error: infinite recursion detected
```

not much of error message considering i have no idea how it works :)

Should we actually have rust-gdb/rust-lldb on windows?
Should there be some meaningful error?
Where is source code for these binaries?

**Comment by fuszenecker** [comment]
Same problem here.

```
C:\Users\robert.fuszenecker>rust-lldb
error: infinite recursion detected
```

```
C:\Users\robert.fuszenecker>rustc --version
rustc 1.15.1 (021bd294c 2017-02-08)
```

**Comment by brson** [comment]
cc https://github.com/rust-lang-nursery/rustup.rs/issues/929

**Comment by brson** [comment]
This is a more general problem that proxies do not detect when the thing they are about to try to invoke doesn't exist.

A simple solution here will be to search PATH for the executable and fail if it can't be found.

**Comment by brson** [comment]
Er, cc https://github.com/rust-lang-nursery/rustup.rs/issues/937

**Comment by Diggsey** [comment]
This should be fixed (it should have a better error message now)

**Comment by Impally** [comment]
I installed rustup this weekend and off the base install I am getting an error:

> error: toolchain 'stable-x86_64-pc-windows-msvc' does not have the binary `rust-lldb.exe`

The binaries are installing to .cargo/bin but do nothing.  I tried moving the binary files to other folders but when doing so I just get the infinite recursion error.

rustc, cargo, and rustup all work fine, but rust-lldb and rust-gdb are busted on Windows still unless I am missing something.

**Comment by Diggsey** [comment]
@Impally the error message is correct - the windows toolchain doesn't have rust-lldb or rust-gdb.

**Comment by Impally** [comment]
@Diggsey Then why do I get the rust-lldb.exe in my .cargo/bin?  Rustup installed the directory and put them there, are they useless or do I need to do something else to make them work?

**Comment by Diggsey** [comment]
Those are just hard-links to the rustup binary - they are how when you run eg. `cargo build`, it is proxied to the correct toolchain (it first runs rustup, which sees it's being run as "cargo", figures out the active toolchain, and then runs the "cargo" binary from that toolchain.)

Rustup installs proxies for every possible binary that might exist in a toolchain - I'm unsure if it's possible to get rust-gdb or rust-llvm for the msvc toolchain. I had a brief look on https://github.com/rust-lang/rust for a related issue, but couldn't find anything. That's the main repository and it determines what actually goes into a toolchain, so it would be best to open an issue there if you think your toolchain should include these tools.

**Comment by bsed** [comment]
i have same error undefinederror: toolchain 'nightly-x86_64-pc-windows-msvc' does not have the binary `rust-gdb.exe`
