### ISSUE TITLE
Cannot download rust-init file in DragonflyBSD due to NotFound

### ISSUE THREAD

**Issue by kubo39** [rust-lang/rustup#930]
In my machine, it seems unable to download file:

```
$ uname -a
DragonFly  4.6-RELEASE DragonFly v4.6.1-RELEASE #3: Sun Oct 16 21:13:25 EDT 2016     root@www.shiningsilence.com:/usr/obj/home/justin/release/4_6/sys/X86_64_GENERIC  x86_64
$ curl https://sh.rustup.rs -sSf | sh
info: downloading installer
curl: (22) The requested URL returned error: 404
rustup: command failed: curl -sSfL https://static.rust-lang.org/rustup/dist/x86_64-unknown-dragonfly/rustup-init -o /tmp/tmp.A7RuCKEN/rustup-init
```

**Comment by kubo39** [comment]
oh.. I should check README, sorry for noise.

**Comment by cbcoutinho** [comment]
I am having the same problem as you, but I don't see the answer in the README - are dragonflybsd toolchains not available?

**Comment by mcandre** [comment]
DragonflyBSD features a basic Rust package in its ports tree, however, rustup does not appear to offer an edition for DragonflyBSD. This makes it difficult to install and update Rust nightly for DragonflyBSD host environments.
