### ISSUE TITLE
rustup create-proxy command

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#933]
Tools that dynamically link to the compiler, but aren't distributed by rustup don't work properly because of LD_LIBRARY_PATH. One simple workaround for this would be to allow users to create their own arbitrary proxies, e.g. `rustup proxy create rustw`.

cc https://github.com/nrc/rustw/issues/121 @nrc @jonathandturner

**Comment by Diggsey** [comment]
👍 This is essentially what I do manually to run the RLS with rustup to avoid messing about with environment variables. It works with no extra changes to rustup beyond simply creating the hardlink.

**Comment by kinnison** [comment]
For this to be properly managed, we'd need a list of additonal proxy names stored in the settings, and then manage those properly on self update etc.  Is this something that remains of interest/value?

**Comment by kinnison** [comment]
Given the lack of response, I'm closing this.
