### ISSUE TITLE
Add a component "analysis"

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rustup#935]
Hi.

Currently RLS is under development.
It uses analysis from https://static.rust-lang.org/dist/index.html
It would be cool if I could execute `rustup component add analysis`
and each time I do `rustup update` it would update analysis's files.

How hard is it to implement?

Thanks

**Comment by Arnavion** [comment]
If I'm reading this correctly, rustup can install anything that's listed in the channel manifest without needing any change. But the channel manifests currently don't list the analysis files.

**Comment by KalitaAlexey** [comment]
@Arnavion,
I am sorry, but I don't understand you.

Could you write what steps I should do to make rustup install analysis files please?

**Comment by Arnavion** [comment]
I'm saying you can't do anything in rustup to fix it. The list of components rustup can install comes from `multirust-channel-manifest.toml` and currently this file doesn't list the analysis files. So something probably needs to change in rust packaging to include the analysis files in this file.

Edit: [Here,](https://github.com/rust-lang/rust-buildbot/blob/003456a2a028bee40b41491b242351c2b309574c/master/build-rust-manifest.py#L330) I think.

Edit 2: [This commit](https://github.com/rust-lang/rust-buildbot/commit/f92708e72446abf35b5e98c020ffa50b8705014b) seems to have added support for it. Not sure why latest nightly's manifest doesn't have it still. Maybe next one will have it.

**Comment by KalitaAlexey** [comment]
@nrc,
Hi.
I have read Arnavion's comment, but I still don't get it.

**Comment by Arnavion** [comment]
2017-02-03's nightly's manifest contains `rust-analysis`, but it's associated with the wrong target - all the entries are associated with `x86_64-unknown-netbsd`. Once that's fixed, `rustup component add rust-analysis` will start working.

**Comment by KalitaAlexey** [comment]
@Arnavion,
That's cool.

**Comment by Arnavion** [comment]
@KalitaAlexey For now, you can do this:

1. `rustup update nightly` to get a nightly >= 2017-02-03
1. Find `~/.rustup/toolchains/nightly-$triple/lib/rustlib/multirust-channel-manifest.toml`
1. Find the line for `pkg = "rust-analysis"` inside the section for your triple. Eg: I'm on `x86_64-pc-windows-msvc` so I found the one in the section named `[[pkg.rust.target.x86_64-pc-windows-msvc.extensions]]`. Change it from `target = "x86_64-unknown-netbsd"` to `target = "$triple"`. Eg: I changed it to `target = "x86_64-pc-windows-msvc"`
1. `rustup component add rust-analysis`. Now you should have the JSON files unpacked to `~/.rustup/toolchains/nightly-$triple/lib/rustlib/$triple/analysis`

We'll also need to update RLS to use this path instead of its custom one.

**Comment by nrc** [comment]
This is work in progress, but I don't think there is anything left to do on the Rustup side (just RLS stuff to address).

**Comment by KalitaAlexey** [comment]
Hello @nrc,
Why does `multirust-channel-manifest.toml` have wrong target (x86_64-unknown-netbsd)?
I suppose it is the only problem between RLS and rustup.
I want to help.
Could you provide any guidance?

**Comment by nrc** [comment]
@KalitaAlexey this should be fixed now, I think there was a PR a while ago which addressed it.

**Comment by KalitaAlexey** [comment]
@nrc,
To check that I should reinstall rustup and check the manifest, right?

**Comment by nrc** [comment]
I'm not entirely sure, I wouldn't think you need to reinstall Rustup, but perhaps?

**Comment by Arnavion** [comment]
It was fixed for some time after my PR, but newer nightlies' manifests don't have the extension at all.

Edit: I assume this is because of the new release infra that doesn't use buildbot.

**Comment by Arnavion** [comment]
```
<Arnavion> acrichto or anyone else: With the new travis-based release infrastructure, is it that everything that used to be done by buildbot should now be done by `x.py dist` ?
<@acrichto> Arnavion: correct
```

So @nrc's change needs to be ported to x.py

**Comment by Arnavion** [comment]
https://github.com/rust-lang/rust/pull/40082
