### ISSUE TITLE
Setting default-host to something non-native displays infinite recursion error message

### ISSUE THREAD

**Issue by Fiveside** [rust-lang/rustup#937]
I've found that when you set the `default-host` in rustup to a non-native target, then running `cargo` and `rustc` prints an infinite recursion error.

Example (from a linux machine):
```
$ rustup toolchain list
stable-x86_64-pc-windows-gnu
stable-x86_64-unknown-linux-gnu (default)
$ cargo
<normal cargo help output>
$ rustc
<normal rustc help output>
$ rustup set default-host x86_64-pc-windows-gnu
$ rustup toolchain list
stable-x86_64-pc-windows-gnu (default)
stable-x86_64-unknown-linux-gnu
$ cargo
error: infinite recursion detected
$ rustc
error: infinite recursion detected
```

**Comment by Diggsey** [comment]
@Fiveside While it could possibly benefit from a more specific error message, this is not expected to work.

The "default-host" corresponds to the machine you are on - if you set it to a value which your system is not compatible with, it won't work.

**Comment by Fiveside** [comment]
Yeah I realized that that shouldn't work sometime after posting this.  I've updated the issue so that its more focused on the error message generated.  Thanks @Diggsey !

**Comment by brson** [comment]
I haven't been able to reproduce this so far. I made sure to install the windows toolchain with `rustup install nightly-x86_64-pc-windows-gnu` and to set the default to just 'nightly', but the error I see is:

```
error: toolchain 'nightly-x86_64-pc-windows-gnu' does not have the binary `rustc`
```
