### ISSUE TITLE
Cannot update to 1.15

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rustup#939]
`rustup update stable` is currently failing for me

```
→ rustup update stable
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: downloading component 'rustc'
 31.9 MiB /  31.9 MiB (100 %)   5.1 MiB/s ETA:   0 s
info: downloading component 'rust-std'
 42.4 MiB /  42.4 MiB (100 %)   3.5 MiB/s ETA:   0 s
info: downloading component 'cargo'
info: downloading component 'rust-docs'
  6.9 MiB /   6.9 MiB (100 %)   3.3 MiB/s ETA:   0 s
info: installing component 'rustc'
info: rolling back changes
error: failed to install component: 'rustc-x86_64-apple-darwin', detected conflict: '"lib/rustlib/etc/gdb_load_rust_pretty_printers.py"'
```

I also tried a `rustup self update` before trying again and got the same result, versions I tried on were

```
→ rustup --version
rustup 0.6.5 (88ef618 2016-11-04)
→ rustup --version
rustup 1.0.0 (17b6d21 2016-12-15)
```

This is updating from

```
→ rustc +stable --version
rustc 1.14.0 (e8a012324 2016-12-16)
```

In case this was related to some really old rust install I checked if I had this file anywhere else, but it's only in `rustup` managed installs and the `rust` source:

```
→ find / -name 'gdb_load_rust_pretty_printers.py' 2>/dev/null
/Users/Nemo157/.rustup/toolchains/beta-x86_64-apple-darwin/lib/rustlib/etc/gdb_load_rust_pretty_printers.py
/Users/Nemo157/.rustup/toolchains/nightly-2017-01-06-x86_64-apple-darwin/lib/rustlib/etc/gdb_load_rust_pretty_printers.py
/Users/Nemo157/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/etc/gdb_load_rust_pretty_printers.py
/Users/Nemo157/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/etc/gdb_load_rust_pretty_printers.py
/Users/Nemo157/sources/rust/src/etc/gdb_load_rust_pretty_printers.py
```

I've been able to update many times in the past, so not sure what's different about this release. I also just updated beta to 1.15.0-beta.5 a couple of days ago fine.

I normally develop on nightly anyway, so I'll leave stable as is in case someone has any debugging commands I could run.

**Comment by brson** [comment]
Thanks for the report @Nemo157.

I have a hunch of what happened here, and am hopeful it won't happen again. Need further investigation.

**Comment by Diggsey** [comment]
@brson Status?

**Comment by Nemo157** [comment]
I still have not touched my stable toolchain since I reported this, just tried again in case something changed between rustup 1.0 and now, still get the same error message

```
→ rustc +stable --version
rustc 1.14.0 (e8a012324 2016-12-16)

→ rustup --version
rustup 1.0.0 (17b6d21 2016-12-15)

→ rustup update stable
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: downloading component 'rustc'
 32.8 MiB /  32.8 MiB (100 %)   2.1 MiB/s ETA:   0 s
info: downloading component 'rust-std'
 43.9 MiB /  43.9 MiB (100 %)   3.0 MiB/s ETA:   0 s
info: downloading component 'cargo'
info: downloading component 'rust-docs'
  9.9 MiB /   9.9 MiB (100 %)   3.2 MiB/s ETA:   0 s
info: installing component 'rustc'
info: rolling back changes
error: failed to install component: 'rustc-x86_64-apple-darwin', detected conflict: '"lib/rustlib/etc/gdb_rust_pretty_printing.py"'

→ rustup self update
info: checking for self-updates
info: downloading self-update
info: rustup updated successfully to 1.2.0

→ rustup update stable
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: downloading component 'rustc'
 32.8 MiB /  32.8 MiB (100 %)   3.2 MiB/s ETA:   0 s
info: downloading component 'rust-std'
 43.9 MiB /  43.9 MiB (100 %)   3.3 MiB/s ETA:   0 s
info: downloading component 'cargo'
  3.5 MiB /   3.5 MiB (100 %)   3.1 MiB/s ETA:   0 s
info: downloading component 'rust-docs'
  9.9 MiB /   9.9 MiB (100 %)   3.3 MiB/s ETA:   0 s
info: installing component 'rustc'
info: rolling back changes
error: failed to install component: 'rustc-x86_64-apple-darwin', detected conflict: '"lib/rustlib/etc/gdb_rust_pretty_printing.py"'
 ```

still willing to run any kind of debugging commands if anyone has some.

**Comment by aswaving** [comment]
I had a similar problem when trying to update `stable-x86_64-pc-windows-msvc` on Windows (rustup version 1.5.0).

I solved it by removing the manifest file of the component that had the conflict (in my case `.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\manifest-rust-src`).

After this `rustup update` succeeded.

**Comment by agausmann** [comment]
I am having a similar issue installing 1.33.0-nightly (f960f377f 2018-12-24) alongside a fresh installation of 1.31.1-stable (b6c32da9b 2012-12-18) on target x86-64-unknown-linux-gnu.
Steps to reproduce:

- Remove current installation - `rm -rf ~/.cargo ~/.rustup`
- Install rustup according to the rustup.rs website - `curl https://sh.rustup.rs | sh`
- Attempt to install nightly - `rustup toolchain install nightly`

Output of `rustup toolchain install nightly`:

```
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2018-12-25, rust version 1.33.0-nightly (f960f377f 2018-12-24)
info: downloading component 'rustc'
 82.5 MiB /  82.5 MiB (100 %)   3.3 MiB/s ETA:   0 s
info: downloading component 'rust-std'
 71.5 MiB /  71.5 MiB (100 %)   5.7 MiB/s ETA:   0 s
info: downloading component 'cargo'
info: downloading component 'rust-docs'
  8.5 MiB /   8.5 MiB (100 %)   5.4 MiB/s ETA:   0 s
info: installing component 'rustc'
info: installing component 'rust-std'
info: rolling back changes
error: failed to install component: 'rust-std-x86_64-unknown-linux-gnu', detected conflict: '"lib/rustlib/x86_64-unknown-linux-gnu/lib/libLLVM-8svn.so"'
```

Output of `rustup show`:

```
Default host: x86_64-unknown-linux-gnu

stable-x86_64-unknown-linux-gnu (default)
rustc 1.31.1 (b6c32da9b 2018-12-18)
```

**Comment by agausmann** [comment]
The file `~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libLLVM-8svn.so` exists before and after attempting installation, and it is the only toolchain installed. Removing that file before attempting to install nightly does not work (same error), but the file reappears during installation of nightly, which seems odd.

**Comment by SlavojZizekIsASnack** [comment]
Main issue is #1590. Current workaround is `rustup toolchain add nightly-2018-12-23`

**Comment by MasterDeflate** [comment]
> Main issue is #1590. Current workaround is `rustup toolchain add nightly-2018-12-23`

```
# rustc +stable --version
rustc 1.31.1 (b6c32da9b 2018-12-18)

# rustup toolchain add nightly-2018-12-23
info: syncing channel updates for 'nightly-2018-12-23-x86_64-unknown-linux-gnu'

nightly-2018-12-23-x86_64-unknown-linux-gnu unchanged - rustc 1.33.0-nightly (2d3e909e4 2018-12-22)

# rustup toolchain install nightly-x86_64-unknown-linux-gnu
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2018-12-25, rust version 1.33.0-nightly (f960f377f 2018-12-24)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: rolling back changes


error: failed to install component: 'rust-std-x86_64-unknown-linux-gnu', detected conflict: '"lib/rustlib/x86_64-unknown-linux-gnu/lib/libLLVM-8svn.so"'

```


With using
rustup toolchain add nightly-2018-12-23

I get same problem.

**Comment by agausmann** [comment]
Hah, well I used `rustup toolchain add nightly` instead of `... install nightly` and that works for me.

**Comment by johanlindfors** [comment]
This happened for me as well on my Windows device just now, trying to update to latest stable. Even after restarting the computer (which pretty much works for fixing anything) the error occurred. I ended up deleting all of the folders in the toolchain directory, then running the update process again. Success!

**Comment by rbtcollins** [comment]
This is another instance of missing/corrupt manifest data. Without knowledge of the installed file, rustup cannot remove it prior to installing the updated version, and then hits a conflict due to the file already existing, and you get the error.

We've got a bunch of these bugs scattered all over the place, I'm closing them all to bring order. See #2417.
