### ISSUE TITLE
Document the use of toolchain link

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rustup#954]
The current output of `toolchain --help` mentions that "`rustup` can also install toolchains from [..] local builds", but then does not go into further detail. `toolchain link` is the command meant for that purpose, but its `--help` output is, well, unhelpful:
```console
$ rustup toolchain link --help
rustup-toolchain-link
Create a custom toolchain by symlinking to a directory

USAGE:
    rustup toolchain link <toolchain> <path>

FLAGS:
    -h, --help    Prints help information

ARGS:
    <toolchain>
    <path>
```

In particular, it should at the very least be noted that `path` should be `/path/to/rust/build/$triple/stage1`, and `link` should be pointed to from `toolchain --help`. It'd also be useful to mention that only a `rustc` build is required, not a full `cargo` build.

**Comment by brson** [comment]
Thank you for the bug report @jonhoo !

**Comment by typesanitizer** [comment]
PR submitted here: https://github.com/rust-lang-nursery/rustup.rs/pull/1017

**Comment by durka** [comment]
Would be great to also add some error checking, so if you try to `rustup toolchain link stage1/bin` or `stage1/bin/rustc` instead of totally mysterious "infinite recursion detected" later.

**Comment by typesanitizer** [comment]
1. @durka, what are all the things that need to be checked before linking? In my build, I have a lot of `.so` files inside `stage1/lib` and `.rlib` and `.so` files in `stage1/lib/x86_64-unknown-linux-gnu/lib`.
2. I'm not sure which function should handle the error checking though: `toolchain_link` calls `install_from_dir` which calls `install` which calls `run` which basically calls `utils::symlink_dir`. Which function's responsibility would it be to handle this error? I suppose we could do it in `toolchain_link` itself by just calling `rustup_utils::utils::assert_is_file` for `$path/bin/rustc`.

**Comment by durka** [comment]
At least a sanity check that bin, lib, and bin/rustc are in the expected
place would be nice.

**Comment by brson** [comment]
Looks like the original issue is fixed. Thanks @theindigamer. Do we need to open another issue for the followups mentioned here cc @durka @theindigamer ?

**Comment by typesanitizer** [comment]
@brson the merged PR included error checking for directories as suggested by @durka . Is there anything else that requires a follow up?

**Comment by brson** [comment]
Nope! Thanks @theindigamer.
