### ISSUE TITLE
rustup doc for toolchain doesn't show all subcommands?

### ISSUE THREAD

**Issue by ghost** [rust-lang/rustup#960]
I have multiple toolchains and when I do an `rustup update` it tries to update them all which I don't want.
I wanted to update only 1 toolchain but couldn't find it in the docs,
```
USAGE:
    rustup toolchain [SUBCOMMAND]

FLAGS:
    -h, --help    Prints help information

SUBCOMMANDS:
    list         List installed toolchains
    install      Install or update a given toolchain
    uninstall    Uninstall a toolchain
    link         Create a custom toolchain by symlinking to a directory
    help         Prints this message or the help of the given subcommand(s)
```
but the command `rustup toolchain update nightly-x86_64-unknown-linux-gnu` actually works. Maybe this command should be added in the subcommands list to avoid confusion.

**Comment by kbknapp** [comment]
That's because the `update` command [is hidden](https://github.com/rust-lang-nursery/rustup.rs/blob/master/src/rustup-cli/rustup_mode.rs#L173).

**Comment by ghost** [comment]
Oh lol I didn't see the help info for install which says it updates a given toolchain. But either way would be good to have it shown. Closing this for now.
