### ISSUE TITLE
rustup-init.exe tries iOS install on Windows?!

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rustup#966]
I don't know why exactly it fails – CI is a harsh mistress – but at least the error messages are plenty confusing.

See any of the failing builds at https://ci.appveyor.com/project/llogiq/bytecount

**Comment by Meralis40** [comment]
I have the same problem when updating or installing nightly (don't occurs with stable or nightly-2017-02-25).
It seems the manifest references the component "rust-analysis", but don't have any url for download it.

**Comment by Diggsey** [comment]
This is an upstream problem which should be fixed with the next nightly - rust-lang/rust#40106

**Comment by llogiq** [comment]
Thank you!
