### ISSUE TITLE
Move the rust source code to a reasonable location

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/rustup#973]
Given that `~/.rustup/toolchains/$toolchain/` appears to be following the FSH (approximately), the source really should go under `~/.rustup/toolchains/$toolchain/src/rust/`.

**Comment by brson** [comment]
Thank you for the suggestions @Stebalien. Rust has its own scheme for storing toolchain specific metadata, under 'rustlibs', and I am satisfied with it. I do not see great advantage to changing this scheme. If distros want to install Rust source to that location they may.

**Comment by brson** [comment]
I'll leave this open a bit for a rebuttal.

**Comment by Stebalien** [comment]
My primary complaint was that I had (and I'm guessing others have had) quite a bit of trouble actually finding the source after installing it. I'd suggest adding a symlink but that's not really an option on Windows...

> If distros want to install Rust source to that location they may.

That's an excellent reason to do so in rustup. After looking through existing packages in both Ubuntu and Arch, I believe most distros will likely just ignore the FSH and do whatever rustup does for compatibility. However,  tools like racer will still have to to check both locations if at least one major distro puts the sources where they belong (`SYSROOT/src`). If rustup put them where they belonged, we could avoid this entire mess.

---

This obviously isn't the end of the world, it just tickles my "but the spec!" reaction.

**Comment by kinnison** [comment]
I think at this point there's too much history in the source being where it is.  I'd be open to adding a symlink elsewhere, but the "FHS-like" shape is entirely incidental.
