### ISSUE TITLE
Environment not set up on Ubuntu at install

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rustup#975]
(moved here from https://github.com/rust-lang/book/issues/404)

@tsingi reported:

> Using Ubuntu, after the install the environment was not being sourced at shell startup.
> 
> tsingi@tsingi:~$ uname -a
> Linux tsingi 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> 
> The init script sets up .profile which doesn't seem to be sourced in Ubuntu when I start a shell.
> 
> I copied the PATH line:
> 
>     export PATH="$HOME/.cargo/bin:$PATH"
> 
> to .bashrc and it sources fine.
> 
> This should be corrected in the script and/or addressed in troubleshooting.  Or you could convince Ubuntu to use .profile by default.

I think this is an issue with rustup and/or rustup docs, and I hope we can figure this out over here rather than having to document it in the book.

This might be related to #211, #556, or #371, but I'm not sure.

**Comment by brson** [comment]
PATH handling needs overhaul completely.

**Comment by JekoTronik** [comment]
Hi,
I am running Debian Jessie stable. Environment not setup after 
`curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly`

**Comment by shepmaster** [comment]
Specifically, we see the Ubuntu issue on Ubuntu 16.04.2 LTX (Xenial) using bash.

**Comment by tesuji** [comment]
EDIT: I misunderstood the issue that the users want to use Rust right after
installation without restarting their shell.

When we use `curl https://sh.rustup.rs -sSf | sh` to install rustup and rust, 
we execute the installer script in the new child shell. The question now is 
[how to alter PATH within a shell script?][alter_path]. Only one solution is
appropriate here, that's to *spawn a new shell* that contains the altered
PATH. So we include the script below in `rustup-init.sh`:

```bash
export PATH="$HOME/.cargo/bin:$PATH"
exec "$SHELL"
```

But there is unresolved question here:
- This will spawn the new shell. So when users type `exit` in this shell, they will return 
  to the parent shell. Is this the behavior that users like or might be surprised?

  Temporary solution is to inform users that `rustup-init.sh` will spawn a
  new shell after installation.

[alter_path]: https://unix.stackexchange.com/questions/23426/how-to-alter-path-within-a-shell-script

**Comment by kinnison** [comment]
I'm not sure what approach is best.  Nominally `.profile` should be read by all shells (though bash will not read it if `.bash_profile` exists too.  I suppose really we should attempt to detect the right shell and adjust the right file, so `.bash_profile` if bash is detected, `.profile` if zsh etc.

**Comment by brson** [comment]
It is pretty infuriating that this is still a problem. Ubuntu is _very_ common, and rustup never installs correctly. IMO rustup should understand that `.bash_profile` supercedes `.profile`.

Basically, if either exists it should modify them.

**Comment by brson** [comment]
Just looking through the code now, both `.profile` and `.bash_profile` are modified if they exist.

**Comment by kinnison** [comment]
Yes I just noticed that.  In theory we should also support `.bash_login` but I'm less worried about that one since it seems pretty rare.  The OP posted on the 6th March 2017 and `.bash_profile` specific code has been present since June 24th 2017 That was `1.4.0+32` so I'm guessing that it was in `1.5.0` of rustup.

Do we think this could be closed?

**Comment by brson** [comment]
The problem I probably have, and I suspect many, is understanding the distinction between a shell and a login shell.

Most people probably just want cargo to work immediately, or to launch a new terminal and have it work, but for most configurations they have to literally log out of their GUI to get .profile to run.

I myself mostly work on WSL and I have no idea when .profile runs, but I've just discovered how to launch a terminal with a login shell (after years of frustration).

The instructions _do_ indicate how to get the current shell immediately working by sourcing `.cargo/env`.

@kinnison I kinda think _this_ should be closed, but I'm still not happy with the install experience here.

That it only works after a login is very confusing. I'm kinda thinking that putting some code in `.bashrc`, `.zshrc` that sources a clever script in `~/.cargo/`, that conditionally fixes the environment would be smart.

**Comment by brson** [comment]
In fact, `$CARGO_HOME/env` could just be smart in general and conditionally set up cargo if it isn't already. Then source that script from _every possible_ init script.

**Comment by brson** [comment]
@kinnison I filed another bug about making the post-install setup more robust https://github.com/rust-lang/rustup.rs/issues/1881

**Comment by kinnison** [comment]
Okay, we'll continue the work from there and I'll close this, thank you @brson.
