### ISSUE TITLE
`Cargo.lock` breaks build with libressl

### ISSUE THREAD

**Issue by ibabushkin** [rust-lang/rustup#978]
I am currently packaging `rustup` for void linux. During the build process, one issue caught my attention: the `Cargo.lock` provided with the project specifies `openssl-sys-0.9.2` as a dependency. Said version of the OpenSSL bindings doesn't detect LibreSSL properly and thus breaks the build. Deleting the `Cargo.lock` fixes the problem. Thus, I suggest that the `Cargo.lock` gets regenerated to avoid such issues for other users.

Cheers

**Comment by steveklabnik** [comment]
Cargo shouldn't use checked in cargo.lock files when determining deps, so that seems a bit odd...

**Comment by ibabushkin** [comment]
Hm. the version of the cargo used is `0.16.0`, provided by the distribution (for the package build, that is).

**Comment by brson** [comment]
@ibabushkin Running `cargo update` should fix the lockfile to be compatible.

**Comment by ibabushkin** [comment]
On 2017-03-16, Brian Anderson wrote:
> @ibabushkin Running `cargo update` should fix the lockfile to be compatible.

That's probably the best solution, thank you.

**Comment by tesuji** [comment]
Is this issue fixed? @kinnison

**Comment by kinnison** [comment]
Not until we do a `cargo update` and commit that to mainline, @steveklabnik we keep a lock file committed because we're slightly conservative about moving forwards - we've had certain deps s'plode on us in the past because they're still in the 0.x range :D

**Comment by steveklabnik** [comment]
even if you commit it, when people depend on your project, cargo won't use it for resolution, so that' wont help.

Oops, sorry, just realized which repo I'm in. Of course, nobody is depending on rustup as a library...

**Comment by kinnison** [comment]
We've updated the openssl crates in the past, I believe this is fixed now.
