### ISSUE TITLE
Consider distributing release + LTO binary

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rustup#982]
The current `rustup-init` binary is 9.3M in size, while it shouldn't be so big to bootstrap (you need to download 10M *before* even seeing a message.) It seems to contain debug symbols too.

Building with release resulted in 5.0M binary, with LTO it's 4.9M (doesn't make much sense). This halves download, and makes the experience better.

**Comment by brson** [comment]
Yes please. Patches wanted.

**Comment by remram44** [comment]
Adding `lto=true, panic=abort` I didn't actually see much of an improvement:  https://github.com/remram44/rustup.rs/commit/45342602d142b75a685002d8f64d6d2233c08c7f And reading CI scripts, isn't this already building as release?

How did you get those down to 5MB?

**Comment by ishitatsuyuki** [comment]
This is the result of my local toolchain (glibc, nightly). I'm not sure which configuration it uses for CI.
