### ISSUE TITLE
Installation failure via the script has bad error message

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#987]
```
~/C/h/e/duration ❯❯❯ curl https://sh.rustup.rs -sSf | sh

info: downloading installer
warning: it looks like you have existing multirust metadata
warning: rustup cannot be installed alongside multirust
warning: delete `/Users/wycats/.multirust` before installing rustup
error: cannot install while multirust is installed
rustup: command failed: /var/folders/qn/cf7wq1s54dlfg51t4xjt371c0000gn/T/tmp.mz2CwTMt/rustup-init
```

This last line comes from rustup-init.sh and is useless. Probably the right thing to do here is just not print anything in response to an error running rustup-init.exe, though there is the risk of some failure that produces no useful error text, like e.g. rustup-init.exe isn't runnable for some reason.

Let's just take out the error reporting and see how it goes.

**Comment by bitrauser** [comment]
Hello, I tried to take out the error reporting and made a PR. Is this what you intended?

**Comment by brson** [comment]
Looks fixed.
