### ISSUE TITLE
`rustup update stable` only updates the host build

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#989]
In this example I have two stable toolchains installed but only one is updated:

```
$ rustup update stable
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.15.1 (021bd294c 2017-02-08)
```

**Comment by Diggsey** [comment]
This is consistent with how toolchain names are handled in general. If I run `rustup install stable` I wouldn't expect it to install *all* stable toolchains for example.

**Comment by brson** [comment]
Good point.

**Comment by Diggsey** [comment]
Do you still consider this a bug?
