### ISSUE TITLE
"update not yet available" message should not error

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#990]
```
brian@DESKTOP-CODN6ST MINGW64 /c/Users/brian/Documents/dev/taskcluster-crater/rs
$ rustup update stable
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: update not yet available, sorry! try again later
error: checksum failed, expected: '6a73d4aa8eccdfe03fdd7ddd84685c8ccba3ca6516db0475197ef40a21686a52', calculated: '4cf9a1a74dd0d5fdf0b0fabf473e8940f759093b3a1f11c8cef7a9f554d99c5b'

```

The whole point of the "update not yet available" is to mask the spurious error!

**Comment by brson** [comment]
The thing to do here is locate this code path and make it exit successfully instead of error.

**Comment by alisha17** [comment]
Can I take up this issue ?

**Comment by brson** [comment]
@alisha17 Yes you may!

**Comment by alisha17** [comment]
This has to be updated in https://github.com/rust-lang-nursery/rustup.rs/blob/master/src/rustup-dist/src/dist.rs, dl_v2_manifest() function according to my understanding? This is my first bug in Rust/Rustup, so not as familiar with the code yet. Therefore, confirming before proceeding.

**Comment by brson** [comment]
This work item is still available.
