### ISSUE TITLE
Document the usage of CARGO_HOME and RUSTUP_HOME to install to a custom location

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#994]
It's a common complaint that rustup doesn't let you control where to install, but it actually does. It's just not documented. Setting CARGO_HOME and RUSTUP_HOME while running rustup-init will set those directories as desired. Note though that if one does this then they are on their own wrt ensuring their environment is set up right - those environment variables must be configured whenever the toolchain is executed, and CARGO_HOME/bin must be on the PATH.

**Comment by brson** [comment]
Document in README.md.

**Comment by Stebalien** [comment]
>  and CARGO_HOME/bin must be on the PATH.

Unless `install.root` is set in `$CARGO_HOME/config`

**Comment by brson** [comment]
> Unless install.root is set in $CARGO_HOME/config

That's an interesting complication, but setting that will have no impact on rustup. Actually, setting that seemingly would confuse rustup into using a different directory than cargo. rustup knows nothing about that setting.
